// Strings of M7 «Модель мира» (`m7w.*`, plus the `kind.world.*` / `target.world-*` labels). Russian is the primary UI
// language; the user is addressed as «ты» (male). The view speaks of names, nicknames and namesakes, not of entities,
// aliases and stores; book names, entry numbers and passport ids are details of the namesake question.
import type { I18nParts } from '../../shared/contracts';

export const WORLD_STRINGS: I18nParts = {
    en: {
        'm7w.title': 'World model',
        'm7w.tab': 'World',
        'kind.world.merge': 'Merging names',
        'kind.world.alias': 'Nicknames in this chat',
        'kind.world.separate': 'Different despite similar names',
        'kind.world.sameAs': 'Namesakes from other stories',
        'kind.world.apart': 'Namesakes from other stories: another one here',
        'target.world-alias': 'Nickname in this chat',
        'target.world-merge': 'Merged names',
        'target.world-separate': 'Different despite similar names',
        'target.world-identity': 'Answer about a namesake',
        'target.world-nai-excluded': 'Look from the card',
        'm7w.field.alias': 'Means',
        'm7w.field.merged': 'Now the same as',
        'm7w.field.cardLook': 'Look from the card in this chat',
        'm7w.value.notUsed': 'not used',
        'm7w.value.used': 'used',
        'm7w.hint':
            'Everyone and everything Maestro knows in this chat: the card’s character, your persona, who is in the DES scene, lore entries, the canon and places. When someone has several names, they are gathered into one — by the other names DES knows, nicknames of this chat and looks; doubtful matches wait for your decision. Namesakes from other stories stay out until you say it is the same character.',
        'm7w.noChat': 'No chat is open.',
        'm7w.count': 'Known: {count}',
        'm7w.lore.read': 'Lore read {time}',
        'm7w.lore.pending': 'The lore is being read: so far only cards, the DES scene, looks and places.',
        'm7w.rebuild': 'Rebuild',
        'm7w.rebuild.hint': 'Read everything again, the lore included',
        'm7w.search': 'Search by name, nickname or form',
        'm7w.empty': 'Nothing is known about this chat yet.',
        'm7w.nothingFound': 'Nothing matches the search.',
        'm7w.kind.persona': 'Persona ({count})',
        'm7w.kind.character': 'Characters ({count})',
        'm7w.kind.place': 'Places ({count})',
        'm7w.kind.item': 'Items ({count})',
        'm7w.kind.faction': 'Factions ({count})',
        'm7w.kind.event': 'Events ({count})',
        'm7w.kind.tradition': 'Traditions ({count})',
        'm7w.kind.promise': 'Promises ({count})',
        'm7w.kind.secret': 'Secrets ({count})',
        'm7w.kind.quest': 'Quests ({count})',
        'm7w.kind.mechanic': 'Mechanics ({count})',
        'm7w.present': 'in the scene',
        'm7w.absent': 'off scene',
        'm7w.sources': 'Known from: {count}',
        'm7w.aliasList': 'Also: {list}',
        'm7w.formList': 'Forms: {list}',
        'm7w.details': 'Details',
        'm7w.source.card': 'card',
        'm7w.source.persona': 'persona',
        'm7w.source.des.character': 'DES scene',
        'm7w.source.des.alias': 'other name in DES',
        'm7w.source.chat.alias': 'nickname in this chat',
        'm7w.source.lore.entry': 'lore entry',
        'm7w.source.canon.entry': 'chat canon',
        'm7w.source.ck.archive': 'character sheet (CarrotKernel)',
        'm7w.source.nai.passport': 'look for pictures (NAI Studio)',
        'm7w.source.qvink.memory': 'memories (Qvink)',
        'm7w.source.place': 'places',
        'm7w.source.des.workshop': 'DES (all chats)',
        'm7w.candidates.title': 'Maybe the same ({count})',
        'm7w.candidates.hint':
            'After merging, the second name means the first one — in this chat only. For every chat to know it, add the name to the character’s other names in the DES Workshop.',
        'm7w.candidates.none': 'No doubtful matches.',
        'm7w.candidate.pair': '«{a}» and «{b}»',
        'm7w.candidate.merge': 'Merge',
        'm7w.candidate.mergeHint': 'Keep «{a}» and treat «{b}» as the same',
        'm7w.candidate.separate': 'Different',
        'm7w.candidate.separateHint': 'Stop proposing this pair',
        'm7w.reason.sharedName': 'Both answer to «{name}».',
        'm7w.reason.sharedAlias': 'Several of them are also called «{name}».',
        'm7w.reason.firstName': '«{name}» may be the short name of «{a}».',
        'm7w.reason.anchors': 'The name «{name}» is shared by two different cards, personas or places.',
        'm7w.merge.title': '«{b}» — is it «{a}»?',
        'm7w.merge.body': 'Agree, and «{b}» means «{a}» in this chat; refuse, and they stay different.',
        'm7w.merge.details': 'Ids: {a} ← {b}',
        'm7w.merge.done':
            'Merged: in this chat «{alias}» means the same now. For every chat to know it, add this name to the character in the DES Workshop.',
        'm7w.separate.done': 'Noted: they are different.',
        'm7w.aliases.title': 'Nicknames in this chat',
        'm7w.aliases.hint': 'Nicknames that work in this chat only, for example «Рыжая» for Elizabeth.',
        'm7w.aliases.none': 'No nicknames yet.',
        'm7w.alias.input': 'Nickname',
        'm7w.alias.entity': 'Who or what it is',
        'm7w.alias.add': 'Add',
        'm7w.alias.remove': 'Remove',
        'm7w.alias.missing': '{id} (not met right now)',
        'm7w.error.emptyAlias': 'Enter a nickname.',
        'm7w.error.noEntity': 'There is no such character, place or thing in this chat.',
        'm7w.journal.merge': 'Merged names: «{b}» is «{a}»',
        'm7w.journal.separate': '«{a}» and «{b}» are different',
        'm7w.journal.alias': 'Nickname in this chat: «{alias}» is «{name}»',
        'm7w.journal.aliasRemoved': 'The nickname «{alias}» means nothing now',
        'm7w.sameAs.title.being': '{name} here — the same character as {where}?',
        'm7w.sameAs.title.place': '{name} here — the same place as {where}?',
        'm7w.sameAs.title.other': '«{name}» here — the same as {where}?',
        'm7w.where.archive': 'in the book «{book}»',
        'm7w.where.entry': 'in the book «{book}»',
        'm7w.where.passport': 'in the card «{card}»',
        'm7w.where.workshop': 'in other chats (DES)',
        'm7w.where.other': 'in other stories',
        'm7w.sameAs.body':
            'The name «{name}» is known from other stories already: {list}. Answer «{same}», and all that helps here too. «{other}» — everything here is its own, the old stays out. Until you answer, the old is not used here.',
        'm7w.brings.archive': 'character and way of speaking from the sheet in «{book}»',
        'm7w.brings.entry': 'the entry «{entry}» in the book «{book}»',
        'm7w.brings.passport': 'looks and outfits from the card «{card}»',
        'm7w.brings.workshop': 'portrait and description from DES',
        'm7w.sameAs.same.being': 'The same',
        'm7w.sameAs.other.being': 'Another one',
        'm7w.sameAs.same.place': 'The same place',
        'm7w.sameAs.other.place': 'Another place',
        'm7w.sameAs.same.other': 'The same',
        'm7w.sameAs.other.other': 'Something else',
        'm7w.detail.archive': 'CarrotKernel archive «{name}» in «{book}»',
        'm7w.detail.entry': 'entry #{uid} in «{book}»',
        'm7w.detail.passport': 'NAI Studio passport {id} ({card})',
        'm7w.detail.workshop': 'DES Workshop: {name}',
        'm7w.sameAs.badge.being': '{name} — the same character as in another story?',
        'm7w.sameAs.badge.place': '{name} — the same place as in another story?',
        'm7w.sameAs.badge.other': '«{name}» — the same as in another story?',
        'm7w.sameAs.answer': 'Answer',
        'm7w.journal.same.being': 'Noted: {name} here is the same character as {where}',
        'm7w.journal.same.place': 'Noted: {name} here is the same place as {where}',
        'm7w.journal.same.other': 'Noted: «{name}» here is the same as {where}',
        'm7w.journal.apart.being': 'Noted: {name} here is another character, not the one {where}',
        'm7w.journal.apart.place': 'Noted: {name} here is another place, not the one {where}',
        'm7w.journal.apart.other': 'Noted: «{name}» here is something else, not the one {where}',
        'm7w.error.noIdentity': 'There is nothing to decide about this name.',
    },
    ru: {
        'm7w.title': 'Модель мира',
        'm7w.tab': 'Мир',
        'kind.world.merge': 'Объединение имён',
        'kind.world.alias': 'Прозвища в этом чате',
        'kind.world.separate': 'Разные, хоть имена похожи',
        'kind.world.sameAs': 'Тёзки из других историй',
        'kind.world.apart': 'Тёзки из других историй: здесь другой',
        'target.world-alias': 'Прозвище в этом чате',
        'target.world-merge': 'Объединённые имена',
        'target.world-separate': 'Разные, хоть имена похожи',
        'target.world-identity': 'Ответ про тёзку',
        'target.world-nai-excluded': 'Внешность из карточки',
        'm7w.field.alias': 'Означает',
        'm7w.field.merged': 'Теперь то же, что',
        'm7w.field.cardLook': 'Внешность из карточки в этом чате',
        'm7w.value.notUsed': 'не используется',
        'm7w.value.used': 'используется',
        'm7w.hint':
            'Все, кого и что Maestro знает в этом чате: персонаж карточки, твоя персона, кто есть в сцене DES, записи лора, канон и места. Если у кого-то несколько имён, они собираются в одно — по другим именам из DES, прозвищам этого чата и внешности; сомнительные совпадения ждут твоего решения. Тёзки из других историй не подмешиваются, пока ты не скажешь, что это тот же персонаж.',
        'm7w.noChat': 'Чат не открыт.',
        'm7w.count': 'Известно: {count}',
        'm7w.lore.read': 'Лор прочитан {time}',
        'm7w.lore.pending': 'Лор ещё читается: пока известны только карточки, сцена DES, внешность и места.',
        'm7w.rebuild': 'Пересобрать',
        'm7w.rebuild.hint': 'Заново прочитать всё, включая лор',
        'm7w.search': 'Поиск по имени, прозвищу или падежной форме',
        'm7w.empty': 'Об этом чате пока ничего не известно.',
        'm7w.nothingFound': 'По запросу ничего не нашлось.',
        'm7w.kind.persona': 'Персона ({count})',
        'm7w.kind.character': 'Персонажи ({count})',
        'm7w.kind.place': 'Места ({count})',
        'm7w.kind.item': 'Предметы ({count})',
        'm7w.kind.faction': 'Фракции ({count})',
        'm7w.kind.event': 'События ({count})',
        'm7w.kind.tradition': 'Традиции ({count})',
        'm7w.kind.promise': 'Обещания ({count})',
        'm7w.kind.secret': 'Тайны ({count})',
        'm7w.kind.quest': 'Квесты ({count})',
        'm7w.kind.mechanic': 'Механики ({count})',
        'm7w.present': 'в сцене',
        'm7w.absent': 'вне сцены',
        'm7w.sources': 'Откуда известно: {count}',
        'm7w.aliasList': 'Ещё: {list}',
        'm7w.formList': 'Формы: {list}',
        'm7w.details': 'Подробнее',
        'm7w.source.card': 'карточка',
        'm7w.source.persona': 'персона',
        'm7w.source.des.character': 'сцена DES',
        'm7w.source.des.alias': 'другое имя в DES',
        'm7w.source.chat.alias': 'прозвище в этом чате',
        'm7w.source.lore.entry': 'запись лора',
        'm7w.source.canon.entry': 'канон чата',
        'm7w.source.ck.archive': 'лист характера (CarrotKernel)',
        'm7w.source.nai.passport': 'внешность для картинок (NAI Studio)',
        'm7w.source.qvink.memory': 'воспоминания (Qvink)',
        'm7w.source.place': 'места',
        'm7w.source.des.workshop': 'DES (все чаты)',
        'm7w.candidates.title': 'Возможно, одно и то же ({count})',
        'm7w.candidates.hint':
            'После объединения второе имя означает первое — только в этом чате. Чтобы это знали все чаты, добавь имя в другие имена персонажа в мастерской DES.',
        'm7w.candidates.none': 'Сомнительных совпадений нет.',
        'm7w.candidate.pair': '«{a}» и «{b}»',
        'm7w.candidate.merge': 'Объединить',
        'm7w.candidate.mergeHint': 'Оставить «{a}» и считать «{b}» тем же самым',
        'm7w.candidate.separate': 'Это разные',
        'm7w.candidate.separateHint': 'Больше не предлагать эту пару',
        'm7w.reason.sharedName': 'Оба отзываются на «{name}».',
        'm7w.reason.sharedAlias': '«{name}» зовут сразу нескольких.',
        'm7w.reason.firstName': '«{name}» может быть коротким именем «{a}».',
        'm7w.reason.anchors': 'Имя «{name}» есть у двух разных карточек, персон или мест.',
        'm7w.merge.title': '«{b}» — это «{a}»?',
        'm7w.merge.body': 'Согласишься — в этом чате «{b}» будет означать «{a}»; откажешься — они останутся разными.',
        'm7w.merge.details': 'Id: {a} ← {b}',
        'm7w.merge.done':
            'Объединил: в этом чате «{alias}» теперь означает то же самое. Чтобы это знали все чаты, добавь это имя персонажу в мастерской DES.',
        'm7w.separate.done': 'Запомнил: это разные.',
        'm7w.aliases.title': 'Прозвища в этом чате',
        'm7w.aliases.hint': 'Прозвища, которые действуют только в этом чате, — например «Рыжая» для Элизабет.',
        'm7w.aliases.none': 'Прозвищ пока нет.',
        'm7w.alias.input': 'Прозвище',
        'm7w.alias.entity': 'Кто или что это',
        'm7w.alias.add': 'Добавить',
        'm7w.alias.remove': 'Убрать',
        'm7w.alias.missing': '{id} (сейчас не встречается)',
        'm7w.error.emptyAlias': 'Введи прозвище.',
        'm7w.error.noEntity': 'Такого персонажа, места или предмета в этом чате нет.',
        'm7w.journal.merge': 'Объединены имена: «{b}» — это «{a}»',
        'm7w.journal.separate': '«{a}» и «{b}» — разные',
        'm7w.journal.alias': 'Прозвище в этом чате: «{alias}» — это «{name}»',
        'm7w.journal.aliasRemoved': 'Прозвище «{alias}» больше ничего не означает',
        'm7w.sameAs.title.being': '{name} здесь — тот же персонаж, что {where}?',
        'm7w.sameAs.title.place': '{name} здесь — то же место, что {where}?',
        'm7w.sameAs.title.other': '«{name}» здесь — то же самое, что {where}?',
        'm7w.where.archive': 'в книге «{book}»',
        'm7w.where.entry': 'в книге «{book}»',
        'm7w.where.passport': 'в карточке «{card}»',
        'm7w.where.workshop': 'в других чатах (DES)',
        'm7w.where.other': 'в других историях',
        'm7w.sameAs.body':
            'Имя «{name}» уже знакомо по другим историям: {list}. Ответишь «{same}» — всё это пригодится и здесь. «{other}» — здесь всё будет своё, старое не подмешается. Пока ответа нет, старое здесь не используется.',
        'm7w.brings.archive': 'характер и манера речи из листа в «{book}»',
        'm7w.brings.entry': 'запись «{entry}» в книге «{book}»',
        'm7w.brings.passport': 'внешность и наряды из карточки «{card}»',
        'm7w.brings.workshop': 'портрет и описание из DES',
        'm7w.sameAs.same.being': 'Тот же',
        'm7w.sameAs.other.being': 'Другой',
        'm7w.sameAs.same.place': 'То же место',
        'm7w.sameAs.other.place': 'Другое место',
        'm7w.sameAs.same.other': 'То же самое',
        'm7w.sameAs.other.other': 'Другое',
        'm7w.detail.archive': 'архив CarrotKernel «{name}» в «{book}»',
        'm7w.detail.entry': 'запись №{uid} в «{book}»',
        'm7w.detail.passport': 'паспорт NAI Studio {id} ({card})',
        'm7w.detail.workshop': 'мастерская DES: {name}',
        'm7w.sameAs.badge.being': '{name} — тот же персонаж, что в другой истории?',
        'm7w.sameAs.badge.place': '{name} — то же место, что в другой истории?',
        'm7w.sameAs.badge.other': '«{name}» — то же самое, что в другой истории?',
        'm7w.sameAs.answer': 'Ответить',
        'm7w.journal.same.being': 'Запомнил: {name} здесь — тот же персонаж, что {where}',
        'm7w.journal.same.place': 'Запомнил: {name} здесь — то же место, что {where}',
        'm7w.journal.same.other': 'Запомнил: «{name}» здесь — то же самое, что {where}',
        'm7w.journal.apart.being': 'Запомнил: {name} здесь — другой персонаж, не тот, что {where}',
        'm7w.journal.apart.place': 'Запомнил: {name} здесь — другое место, не то, что {where}',
        'm7w.journal.apart.other': 'Запомнил: «{name}» здесь — другое, не то, что {where}',
        'm7w.error.noIdentity': 'По этому имени решать нечего.',
    },
};
