// Strings of M7 «Модель мира» (`m7w.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const WORLD_STRINGS: I18nParts = {
    en: {
        'm7w.title': 'World model',
        'm7w.tab': 'World',
        'kind.world.merge': 'Merging names into one entity',
        'm7w.hint':
            'Everyone and everything the stack knows about in this chat: cards, your persona, the DES cast, NAI passports, CK archives, typed lorebook entries, the canon and places. One person under several names is merged by DES aliases, chat aliases and passport aliases; doubtful matches wait for your decision. Namesakes from other stories (CK archives, NPC passports of the card, global books) stay out until you say it is the same character.',
        'm7w.noChat': 'No chat is open.',
        'm7w.count': 'Entities: {count}',
        'm7w.lore.read': 'Lorebooks read {time}',
        'm7w.lore.pending': 'Lorebooks are not read yet: only cards, DES, passports and places so far.',
        'm7w.rebuild': 'Rebuild',
        'm7w.rebuild.hint': 'Read every source again, lorebooks included',
        'm7w.search': 'Search by name, alias or form',
        'm7w.empty': 'Nothing is known about this chat yet.',
        'm7w.nothingFound': 'Nothing matches the search.',
        'm7w.kind.persona': 'Persona ({count})',
        'm7w.kind.character': 'Characters ({count})',
        'm7w.kind.place': 'Places ({count})',
        'm7w.kind.item': 'Items ({count})',
        'm7w.kind.faction': 'Factions ({count})',
        'm7w.kind.event': 'Events ({count})',
        'm7w.kind.tradition': 'Traditions ({count})',
        'm7w.kind.promise': 'Promises ({count})',
        'm7w.kind.secret': 'Secrets ({count})',
        'm7w.kind.quest': 'Quests ({count})',
        'm7w.kind.mechanic': 'Mechanics ({count})',
        'm7w.present': 'in the scene',
        'm7w.absent': 'off scene',
        'm7w.sources': 'Sources: {count}',
        'm7w.aliasList': 'Also: {list}',
        'm7w.formList': 'Forms: {list}',
        'm7w.details': 'Details',
        'm7w.source.card': 'card',
        'm7w.source.persona': 'persona',
        'm7w.source.des.character': 'DES cast',
        'm7w.source.des.alias': 'DES alias',
        'm7w.source.chat.alias': 'chat alias',
        'm7w.source.lore.entry': 'lorebook entry',
        'm7w.source.canon.entry': 'chat canon',
        'm7w.source.ck.archive': 'CK archive',
        'm7w.source.nai.passport': 'NAI passport',
        'm7w.source.qvink.memory': 'Qvink memory',
        'm7w.source.place': 'place registry',
        'm7w.candidates.title': 'Maybe the same ({count})',
        'm7w.candidates.hint':
            'Merging writes a chat alias: the second name starts meaning the first one in this chat only. To make it global, add the alias in the DES Workshop.',
        'm7w.candidates.none': 'No doubtful matches.',
        'm7w.candidate.pair': '«{a}» and «{b}»',
        'm7w.candidate.merge': 'Merge',
        'm7w.candidate.mergeHint': 'Keep «{a}» and treat «{b}» as the same',
        'm7w.candidate.separate': 'Different',
        'm7w.candidate.separateHint': 'Stop proposing this pair',
        'm7w.reason.sharedName': 'Both answer to «{name}».',
        'm7w.reason.sharedAlias': '«{name}» is also an alias of several others.',
        'm7w.reason.firstName': '«{name}» may be the short name of «{a}».',
        'm7w.reason.anchors': 'An alias «{name}» joins two separate cards, personas or places.',
        'm7w.merge.title': 'Same entity: «{a}» and «{b}»?',
        'm7w.merge.done':
            'Merged for this chat (chat alias «{alias}»). DES aliases are not changed: add the alias in the DES Workshop if every chat should know it.',
        'm7w.separate.done': 'Marked as different.',
        'm7w.aliases.title': 'Chat aliases',
        'm7w.aliases.hint': 'Nicknames that work in this chat only, for example «Рыжая» for Elizabeth.',
        'm7w.aliases.none': 'No chat aliases yet.',
        'm7w.alias.input': 'Alias',
        'm7w.alias.entity': 'Who or what it is',
        'm7w.alias.add': 'Add',
        'm7w.alias.remove': 'Remove',
        'm7w.alias.missing': '{id} (not in the model now)',
        'm7w.error.emptyAlias': 'Enter an alias.',
        'm7w.error.noEntity': 'This entity is not in the world model.',
        'm7w.journal.merge': 'World model: «{b}» merged into «{a}»',
        'm7w.journal.separate': 'World model: «{a}» and «{b}» marked as different',
        'm7w.journal.alias': 'World model: chat alias «{alias}» → «{name}»',
        'm7w.journal.aliasRemoved': 'World model: chat alias «{alias}» removed',
        'm7w.source.des.workshop': 'DES Workshop',
        'kind.world.sameAs': 'Same character as in another story?',
        'kind.world.apart': 'Another character than in another story',
        'm7w.sameAs.title.being': '{name} here — the same character as {where}?',
        'm7w.sameAs.title.place': '{name} here — the same place as {where}?',
        'm7w.sameAs.title.other': '«{name}» here — the same as {where}?',
        'm7w.where.archive': 'in «{book}»',
        'm7w.where.entry': 'in the book «{book}»',
        'm7w.where.passport': 'in the passport of the card «{card}»',
        'm7w.where.workshop': 'in DES',
        'm7w.where.other': 'in other stories',
        'm7w.sameAs.body':
            'The name «{name}» came up in this story, and it is known elsewhere already: {list}. «{same}» — Maestro uses this data here as well. «{other}» — everything here will be its own, the old data stays out. Until you answer, the old data is not used.',
        'm7w.brings.archive': 'character and way of speaking from the sheet in «{book}»',
        'm7w.brings.entry': 'the entry «{entry}» in the book «{book}»',
        'm7w.brings.passport': 'looks and outfits from the passport of the card «{card}»',
        'm7w.brings.workshop': 'portrait and description from DES',
        'm7w.sameAs.same.being': 'The same',
        'm7w.sameAs.other.being': 'Another one',
        'm7w.sameAs.same.place': 'The same place',
        'm7w.sameAs.other.place': 'Another place',
        'm7w.sameAs.same.other': 'The same',
        'm7w.sameAs.other.other': 'Something else',
        'm7w.detail.archive': 'CK archive «{name}» in «{book}»',
        'm7w.detail.entry': 'entry #{uid} in «{book}»',
        'm7w.detail.passport': 'NAI passport {id} ({card})',
        'm7w.detail.workshop': 'DES Workshop: {name}',
        'm7w.sameAs.badge.being': '{name} — the same character as in another story?',
        'm7w.sameAs.badge.place': '{name} — the same place as in another story?',
        'm7w.sameAs.badge.other': '«{name}» — the same as in another story?',
        'm7w.sameAs.answer': 'Answer',
        'm7w.journal.same': 'Remembered: {name} here is the same as {where}; that data is used here now.',
        'm7w.journal.apart': 'Remembered: {name} here is not the one {where}; that data is not used here.',
        'm7w.error.noIdentity': 'There is nothing to decide about this name.',
    },
    ru: {
        'm7w.title': 'Модель мира',
        'm7w.tab': 'Мир',
        'kind.world.merge': 'Склейка имён в одну сущность',
        'm7w.hint':
            'Все, кого и что знает стек в этом чате: карточки, твоя персона, состав DES, паспорта NAI, архивы CK, записи лорбуков с типом, канон и места. Одно лицо под разными именами склеивается по алиасам DES, алиасам чата и паспортов; сомнительные совпадения ждут твоего решения. Тёзки из других историй (архивы CK, паспорта NPC в карточке, общие книги) не подмешиваются, пока ты не скажешь, что это тот же персонаж.',
        'm7w.noChat': 'Чат не открыт.',
        'm7w.count': 'Сущностей: {count}',
        'm7w.lore.read': 'Лорбуки прочитаны {time}',
        'm7w.lore.pending': 'Лорбуки ещё не прочитаны: пока только карточки, DES, паспорта и места.',
        'm7w.rebuild': 'Пересобрать',
        'm7w.rebuild.hint': 'Заново прочитать все источники, включая лорбуки',
        'm7w.search': 'Поиск по имени, алиасу или падежной форме',
        'm7w.empty': 'Об этом чате пока ничего не известно.',
        'm7w.nothingFound': 'По запросу ничего не нашлось.',
        'm7w.kind.persona': 'Персона ({count})',
        'm7w.kind.character': 'Персонажи ({count})',
        'm7w.kind.place': 'Места ({count})',
        'm7w.kind.item': 'Предметы ({count})',
        'm7w.kind.faction': 'Фракции ({count})',
        'm7w.kind.event': 'События ({count})',
        'm7w.kind.tradition': 'Традиции ({count})',
        'm7w.kind.promise': 'Обещания ({count})',
        'm7w.kind.secret': 'Тайны ({count})',
        'm7w.kind.quest': 'Квесты ({count})',
        'm7w.kind.mechanic': 'Механики ({count})',
        'm7w.present': 'в сцене',
        'm7w.absent': 'вне сцены',
        'm7w.sources': 'Источников: {count}',
        'm7w.aliasList': 'Ещё: {list}',
        'm7w.formList': 'Формы: {list}',
        'm7w.details': 'Подробнее',
        'm7w.source.card': 'карточка',
        'm7w.source.persona': 'персона',
        'm7w.source.des.character': 'состав DES',
        'm7w.source.des.alias': 'алиас DES',
        'm7w.source.chat.alias': 'алиас чата',
        'm7w.source.lore.entry': 'запись лорбука',
        'm7w.source.canon.entry': 'канон чата',
        'm7w.source.ck.archive': 'архив CK',
        'm7w.source.nai.passport': 'паспорт NAI',
        'm7w.source.qvink.memory': 'память Qvink',
        'm7w.source.place': 'реестр мест',
        'm7w.candidates.title': 'Возможно, одно и то же ({count})',
        'm7w.candidates.hint':
            'Объединение записывает алиас чата: второе имя начинает означать первое только в этом чате. Чтобы алиас знали все чаты, добавь его в Workshop DES.',
        'm7w.candidates.none': 'Сомнительных совпадений нет.',
        'm7w.candidate.pair': '«{a}» и «{b}»',
        'm7w.candidate.merge': 'Объединить',
        'm7w.candidate.mergeHint': 'Оставить «{a}» и считать «{b}» тем же самым',
        'm7w.candidate.separate': 'Это разные',
        'm7w.candidate.separateHint': 'Больше не предлагать эту пару',
        'm7w.reason.sharedName': 'Оба отзываются на «{name}».',
        'm7w.reason.sharedAlias': '«{name}» — алиас сразу у нескольких.',
        'm7w.reason.firstName': '«{name}» может быть коротким именем «{a}».',
        'm7w.reason.anchors': 'Алиас «{name}» связывает две разные карточки, персоны или места.',
        'm7w.merge.title': 'Одно и то же: «{a}» и «{b}»?',
        'm7w.merge.done':
            'Объединено в этом чате (алиас чата «{alias}»). Алиасы DES не меняются: если имя должны знать все чаты, добавь алиас в Workshop DES.',
        'm7w.separate.done': 'Отмечено как разные.',
        'm7w.aliases.title': 'Алиасы чата',
        'm7w.aliases.hint': 'Прозвища, которые действуют только в этом чате, — например «Рыжая» для Элизабет.',
        'm7w.aliases.none': 'Алиасов чата пока нет.',
        'm7w.alias.input': 'Алиас',
        'm7w.alias.entity': 'Кто или что это',
        'm7w.alias.add': 'Добавить',
        'm7w.alias.remove': 'Убрать',
        'm7w.alias.missing': '{id} (сейчас нет в модели)',
        'm7w.error.emptyAlias': 'Введи алиас.',
        'm7w.error.noEntity': 'Такой сущности нет в модели мира.',
        'm7w.journal.merge': 'Модель мира: «{b}» присоединено к «{a}»',
        'm7w.journal.separate': 'Модель мира: «{a}» и «{b}» отмечены как разные',
        'm7w.journal.alias': 'Модель мира: алиас чата «{alias}» → «{name}»',
        'm7w.journal.aliasRemoved': 'Модель мира: алиас чата «{alias}» убран',
        'm7w.source.des.workshop': 'данные DES (Workshop)',
        'kind.world.sameAs': 'Тот же персонаж, что в другой истории?',
        'kind.world.apart': 'Другой персонаж, не из той истории',
        'm7w.sameAs.title.being': '{name} здесь — тот же персонаж, что {where}?',
        'm7w.sameAs.title.place': '{name} здесь — то же место, что {where}?',
        'm7w.sameAs.title.other': '«{name}» здесь — то же самое, что {where}?',
        'm7w.where.archive': 'в «{book}»',
        'm7w.where.entry': 'в книге «{book}»',
        'm7w.where.passport': 'в паспорте карточки «{card}»',
        'm7w.where.workshop': 'в DES',
        'm7w.where.other': 'в других историях',
        'm7w.sameAs.body':
            'В этой истории встретилось имя «{name}», и его уже знают: {list}. «{same}» — Maestro будет брать эти данные и здесь. «{other}» — здесь всё будет своё, старое не подмешается. Пока ты не ответил, старые данные не используются.',
        'm7w.brings.archive': 'характер и манера речи из листа в «{book}»',
        'm7w.brings.entry': 'запись «{entry}» в книге «{book}»',
        'm7w.brings.passport': 'внешность и наряды из паспорта карточки «{card}»',
        'm7w.brings.workshop': 'портрет и описание из DES',
        'm7w.sameAs.same.being': 'Тот же',
        'm7w.sameAs.other.being': 'Другой',
        'm7w.sameAs.same.place': 'То же место',
        'm7w.sameAs.other.place': 'Другое место',
        'm7w.sameAs.same.other': 'То же самое',
        'm7w.sameAs.other.other': 'Другое',
        'm7w.detail.archive': 'архив CK «{name}» в «{book}»',
        'm7w.detail.entry': 'запись #{uid} в «{book}»',
        'm7w.detail.passport': 'паспорт NAI {id} ({card})',
        'm7w.detail.workshop': 'DES Workshop: {name}',
        'm7w.sameAs.badge.being': '{name} — тот же персонаж, что в другой истории?',
        'm7w.sameAs.badge.place': '{name} — то же место, что в другой истории?',
        'm7w.sameAs.badge.other': '«{name}» — то же самое, что в другой истории?',
        'm7w.sameAs.answer': 'Ответить',
        'm7w.journal.same': 'Запомнил: {name} здесь — тот же, что {where}; эти данные теперь используются и здесь.',
        'm7w.journal.apart': 'Запомнил: {name} здесь — не тот, что {where}; его данные здесь не используются.',
        'm7w.error.noIdentity': 'По этому имени решать нечего.',
    },
};
