// Strings of M16 «Закулисье» (`m16.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
// Plural keys end in .one / .few / .many (pluralForm in domain/offscreen-plan).
import type { I18nParts } from '../../shared/contracts';

export const OFFSCREEN_STRINGS: I18nParts = {
    en: {
        'm16.title': 'Backstage',
        'm16.tab': 'Backstage',
        'm16.profileTask': 'Backstage (what absent characters were doing)',
        'kind.offscreen.event': 'Backstage: an event of an absent character',
        'm16.hint':
            'The world lives while you are not looking: every few turns Maestro briefly asks the background model what the important characters who left the scene long ago were doing. The events go to the chat canon, so a returning character knows where they were. Death, prison, disappearance and anything that contradicts the canon wait for your decision in the Inbox first.',
        'm16.noChat': 'No chat is open.',
        'm16.group': 'Backstage does not work in group chats.',
        'm16.next.economy': 'In «Economy» backstage never runs by itself.',
        'm16.next.off': 'Automatic runs are off in this mode.',
        'm16.next.now': 'The next run comes after the next turn.',
        'm16.next.in.one': 'Next run in {count} turn.',
        'm16.next.in.few': 'Next run in {count} turns.',
        'm16.next.in.many': 'Next run in {count} turns.',
        'm16.next.sceneEnd': 'Also at the end of every scene.',
        'm16.status.queued': 'A run waits in the background queue.',
        'm16.status.saved': 'in the canon',
        'm16.status.inbox': 'in the Inbox',
        'm16.status.rejected': 'rejected',
        'm16.reason.interval': 'on schedule',
        'm16.reason.sceneEnd': 'scene end',
        'm16.reason.manual': 'by hand',
        'm16.lastRun': 'Last run: {time}, {reason} — {names}; events: {count}, {cost}.',
        'm16.lastRun.failed': 'Last run: {time}, {reason} — failed: {error}.',
        'm16.runError.noCandidates': 'nobody to visit: the important characters are here or were in the scene recently',
        'm16.runError.cap': 'the daily background spending cap is reached',
        'm16.runError.noProfile': 'no profile for background tasks (or it is paused for a while)',
        'm16.runError.noCanon': 'the chat canon is off',
        'm16.runError.parse': 'the model did not answer in the expected format',
        'm16.runError.refusal': 'the model refused to answer',
        'm16.runError.empty': 'the model wrote no events',
        'm16.runError.other': '{error}',
        'm16.now.title': 'Now',
        'm16.now.hint': 'Tick whom to look in on (up to three). Nothing ticked: Maestro picks by itself.',
        'm16.now.none': 'All the important characters are here right now: nobody to look in on.',
        'm16.now.run': 'Run now',
        'm16.now.run.hint': 'Find out what the ticked characters are doing (at most {max})',
        'm16.now.queued': 'Backstage started: the events appear here in a minute.',
        'm16.now.neverSeen': '{name} — not in any scene yet',
        'm16.now.absent.one': 'away for {count} turn',
        'm16.now.absent.few': 'away for {count} turns',
        'm16.now.absent.many': 'away for {count} turns',
        'm16.events.title': 'Recent events',
        'm16.events.empty': 'Nothing has happened off-screen yet.',
        'm16.event.drastic': 'drastic turn',
        'm16.event.location': 'Now at: {place}',
        'm16.event.rumour': 'Rumour: {text}',
        'm16.event.rumourUsed': 'Rumour (already heard): {text}',
        'm16.event.conflict': 'Contradicts: {list}',
        'm16.event.openCanon': 'Canon',
        'm16.event.openInbox': 'Inbox',
        'm16.settings.title': 'Settings',
        'm16.settings.every.hint':
            'After how many of your turns backstage runs by itself; 0 = never. In «Economy» it never runs by itself.',
        'm16.settings.every.balanced': 'Turns between runs in «Balanced»',
        'm16.settings.every.cinema': 'Turns between runs in «Cinema»',
        'm16.settings.sceneEnd.balanced': 'In «Balanced», also at the end of a scene',
        'm16.settings.sceneEnd.cinema': 'In «Cinema», also at the end of a scene',
        'm16.settings.max': 'Characters per run',
        'm16.settings.absent': 'Turns a character must be away',
        'm16.settings.absent.hint': 'Characters who were in the scene recently are left alone.',
        'm16.settings.rumours': 'Rumours',
        'm16.settings.rumours.hint':
            'Present characters may mention an event when they were at the same place or know that character. At most one rumour per turn, each only once.',
        'm16.card.title': 'Backstage: {name}',
        'm16.card.body': '{text}',
        'm16.card.body.time': '{time}: {text}',
        'm16.card.location': 'Now at: {place}.',
        'm16.card.drastic':
            'A drastic turn (death, captivity, disappearance or a radical change): it is never written without your decision.',
        'm16.card.conflict': 'Contradicts the canon: {list}',
        'm16.card.unchecked': 'The contradiction check could not run.',
        'm16.error.noChat': 'No chat is open.',
        'm16.error.group': 'Backstage does not work in group chats.',
        'm16.error.noCanon': 'The chat canon is off: the events have nowhere to go.',
        'm16.error.noCandidates':
            'Nobody to look in on: the important characters are here or were in the scene recently.',
        'm16.error.empty': 'The event text is empty.',
    },
    ru: {
        'm16.title': 'Закулисье',
        'm16.tab': 'Закулисье',
        'm16.profileTask': 'Закулисье (чем заняты отсутствующие персонажи)',
        'kind.offscreen.event': 'Закулисье: событие с отсутствующим персонажем',
        'm16.hint':
            'Пока ты не смотришь, мир живёт: раз в несколько ходов Maestro коротко спрашивает фоновую модель, чем были заняты важные персонажи, которых давно нет в сцене. События попадают в канон чата — вернувшись, персонаж знает, где был. Смерть, плен, исчезновение и всё, что спорит с каноном, сначала ждут твоего решения во «Входящих».',
        'm16.noChat': 'Чат не открыт.',
        'm16.group': 'В групповых чатах закулисье не работает.',
        'm16.next.economy': 'В режиме «Экономный» закулисье само не запускается.',
        'm16.next.off': 'В этом режиме закулисье само не запускается.',
        'm16.next.now': 'Следующий запуск — после ближайшего хода.',
        'm16.next.in.one': 'Следующий запуск — через {count} ход.',
        'm16.next.in.few': 'Следующий запуск — через {count} хода.',
        'm16.next.in.many': 'Следующий запуск — через {count} ходов.',
        'm16.next.sceneEnd': 'И ещё в конце каждой сцены.',
        'm16.status.queued': 'Запуск ждёт в очереди фоновых задач.',
        'm16.status.saved': 'в каноне',
        'm16.status.inbox': 'во «Входящих»',
        'm16.status.rejected': 'отклонено',
        'm16.reason.interval': 'по расписанию',
        'm16.reason.sceneEnd': 'конец сцены',
        'm16.reason.manual': 'вручную',
        'm16.lastRun': 'Последний запуск: {time}, {reason} — {names}; событий: {count}, {cost}.',
        'm16.lastRun.failed': 'Последний запуск: {time}, {reason} — не вышло: {error}.',
        'm16.runError.noCandidates': 'заглянуть не к кому: важные персонажи рядом или недавно были в сцене',
        'm16.runError.cap': 'достигнут дневной лимит фоновых трат',
        'm16.runError.noProfile': 'нет профиля для фоновых задач (или он временно на паузе)',
        'm16.runError.noCanon': 'канон чата выключен',
        'm16.runError.parse': 'модель ответила не в том формате',
        'm16.runError.refusal': 'модель отказалась отвечать',
        'm16.runError.empty': 'модель не написала ни одного события',
        'm16.runError.other': '{error}',
        'm16.now.title': 'Сейчас',
        'm16.now.hint': 'Отметь, к кому заглянуть (до трёх). Ничего не отмечено — Maestro выберет сам.',
        'm16.now.none': 'Все важные персонажи сейчас рядом — заглянуть не к кому.',
        'm16.now.run': 'Сейчас',
        'm16.now.run.hint': 'Узнать, чем заняты отмеченные персонажи (не больше {max})',
        'm16.now.queued': 'Закулисье запущено: события появятся здесь через минуту.',
        'm16.now.neverSeen': '{name} — пока ни в одной сцене',
        'm16.now.absent.one': 'нет в сцене {count} ход',
        'm16.now.absent.few': 'нет в сцене {count} хода',
        'm16.now.absent.many': 'нет в сцене {count} ходов',
        'm16.events.title': 'Последние события',
        'm16.events.empty': 'За кадром пока ничего не случилось.',
        'm16.event.drastic': 'резкий поворот',
        'm16.event.location': 'Теперь: {place}',
        'm16.event.rumour': 'Слух: {text}',
        'm16.event.rumourUsed': 'Слух (уже прозвучал): {text}',
        'm16.event.conflict': 'Спорит с: {list}',
        'm16.event.openCanon': 'Канон',
        'm16.event.openInbox': 'Входящие',
        'm16.settings.title': 'Настройки',
        'm16.settings.every.hint':
            'Через сколько твоих ходов закулисье запускается само; 0 — никогда. В «Экономном» оно само не запускается.',
        'm16.settings.every.balanced': 'Ходов между запусками в «Сбалансированном»',
        'm16.settings.every.cinema': 'Ходов между запусками в «Кино»',
        'm16.settings.sceneEnd.balanced': 'В «Сбалансированном» — ещё и в конце сцены',
        'm16.settings.sceneEnd.cinema': 'В «Кино» — ещё и в конце сцены',
        'm16.settings.max': 'Персонажей за запуск',
        'm16.settings.absent': 'Сколько ходов персонажа не должно быть в сцене',
        'm16.settings.absent.hint': 'Кто был в сцене недавно, того закулисье не трогает.',
        'm16.settings.rumours': 'Слухи',
        'm16.settings.rumours.hint':
            'Присутствующие могут обмолвиться о событии, если были там же или знают этого персонажа. Не больше одного слуха за ход, каждый — один раз.',
        'm16.card.title': 'Закулисье: {name}',
        'm16.card.body': '{text}',
        'm16.card.body.time': '{time}: {text}',
        'm16.card.location': 'Теперь: {place}.',
        'm16.card.drastic':
            'Резкий поворот (смерть, плен, исчезновение или коренная перемена): без твоего решения такое не записывается.',
        'm16.card.conflict': 'Спорит с каноном: {list}',
        'm16.card.unchecked': 'Проверить на противоречия не удалось.',
        'm16.error.noChat': 'Чат не открыт.',
        'm16.error.group': 'В групповых чатах закулисье не работает.',
        'm16.error.noCanon': 'Канон чата выключен: событиям некуда записываться.',
        'm16.error.noCandidates': 'Заглянуть не к кому: важные персонажи рядом или недавно были в сцене.',
        'm16.error.empty': 'Текст события пуст.',
    },
};
