// Strings of the localization jobs (Russian keys of a book or an entry through Lorebook Localizer, plan-2 §8):
// keys m23.job.*. Counted words come in .one / .few / .many forms (pluralForm in domain/offscreen-plan); English
// uses .one and .many and repeats .many as .few so both languages keep the same keys.
import type { I18nParts } from '../../shared/contracts';

const en: Record<string, string> = {
    'm23.job.titleBook': 'Russian keys for «{book}»',
    'm23.job.titleEntry': 'Russian keys for «{entry}»',
    'm23.job.open': 'Open the Lore Studio',
    'm23.job.notice': '{title} — {result}',

    'm23.job.queued': 'Waiting: Lorebook Localizer is busy with another job',
    'm23.job.progress': 'Localizing: {progress}',
    'm23.job.ofEntries.one': '{done} of {total} entry',
    'm23.job.ofEntries.few': '{done} of {total} entries',
    'm23.job.ofEntries.many': '{done} of {total} entries',
    'm23.job.working': 'Working… {elapsed}',
    'm23.job.workingEntry': 'Translating the keys… {elapsed}',
    'm23.job.saving': 'Saving the book…',
    'm23.job.stopping': 'Stopping after the current batch…',
    'm23.job.oldLocalizer': 'Lorebook Localizer 0.3 shows a live count of entries here and lets you stop the job.',

    'm23.job.keys.one': 'added {count} key',
    'm23.job.keys.few': 'added {count} keys',
    'm23.job.keys.many': 'added {count} keys',
    'm23.job.entries.one': '{count} entry',
    'm23.job.entries.few': '{count} entries',
    'm23.job.entries.many': '{count} entries',
    'm23.job.failures.one': '{count} entry failed',
    'm23.job.failures.few': '{count} entries failed',
    'm23.job.failures.many': '{count} entries failed',
    'm23.job.done': 'Done: {keys} to {entries}',
    'm23.job.doneEntry': 'Done: {keys}',
    'm23.job.doneNothing': 'Done: no new keys were needed',
    'm23.job.cancelled.one': 'Stopped: {progress} processed',
    'm23.job.cancelled.few': 'Stopped: {progress} processed',
    'm23.job.cancelled.many': 'Stopped: {progress} processed',
    'm23.job.cancelledEntry': 'Stopped',
    'm23.job.error': 'Error: {reason}',

    'm23.job.reason.timeout': 'the model did not answer within {seconds} s',
    'm23.job.reason.invalid': 'the model gave no usable Russian keys',
    'm23.job.reason.error': 'the request to the model failed',
    'm23.job.reason.allFailed': 'the model did not translate a single entry',
    'm23.job.reason.protected': 'Lorebook Localizer never touches BunnyMo books',
    'm23.job.reason.notFound': 'the book was not found — was it renamed or deleted?',
    'm23.job.reason.language': 'no translation language is chosen in Lorebook Localizer',
    'm23.job.reason.profile': 'the connection profile chosen in Lorebook Localizer does not work',
    'm23.job.reason.connection': 'there is no connection to the model',
    'm23.job.reason.other': 'Lorebook Localizer could not finish',

    'm23.job.stop': 'Stop',
    'm23.job.retry': 'Retry',
    'm23.job.retryFailed': 'Retry the failed ones',
    'm23.job.hide': 'Hide',
    'm23.job.details': 'Details',
    'm23.job.detail.entry': '«{entry}»: {reason}',
    'm23.job.detail.more': '…and {count} more',
    'm23.job.detail.message': 'Lorebook Localizer said: {message}',
    'm23.job.detail.book': 'Book: {book}',
};

const ru: Record<string, string> = {
    'm23.job.titleBook': 'Русские ключи для книги «{book}»',
    'm23.job.titleEntry': 'Русские ключи для записи «{entry}»',
    'm23.job.open': 'Открыть Лор-студию',
    'm23.job.notice': '{title} — {result}',

    'm23.job.queued': 'Жду: Localizer занят другой задачей',
    'm23.job.progress': 'Локализую: {progress}',
    'm23.job.ofEntries.one': '{done} из {total} записи',
    'm23.job.ofEntries.few': '{done} из {total} записей',
    'm23.job.ofEntries.many': '{done} из {total} записей',
    'm23.job.working': 'Идёт… {elapsed}',
    'm23.job.workingEntry': 'Перевожу ключи… {elapsed}',
    'm23.job.saving': 'Сохраняю книгу…',
    'm23.job.stopping': 'Останавливаю после текущей порции…',
    'm23.job.oldLocalizer': 'С Lorebook Localizer 0.3 здесь будет живой счётчик записей и кнопка «Остановить».',

    'm23.job.keys.one': 'добавлен {count} ключ',
    'm23.job.keys.few': 'добавлено {count} ключа',
    'm23.job.keys.many': 'добавлено {count} ключей',
    'm23.job.entries.one': '{count} запись',
    'm23.job.entries.few': '{count} записи',
    'm23.job.entries.many': '{count} записей',
    'm23.job.failures.one': '{count} запись не удалась',
    'm23.job.failures.few': '{count} записи не удались',
    'm23.job.failures.many': '{count} записей не удались',
    'm23.job.done': 'Готово: {keys} в {entries}',
    'm23.job.doneEntry': 'Готово: {keys}',
    'm23.job.doneNothing': 'Готово: новых ключей не понадобилось',
    'm23.job.cancelled.one': 'Остановлено: обработана {progress}',
    'm23.job.cancelled.few': 'Остановлено: обработаны {progress}',
    'm23.job.cancelled.many': 'Остановлено: обработано {progress}',
    'm23.job.cancelledEntry': 'Остановлено',
    'm23.job.error': 'Ошибка: {reason}',

    'm23.job.reason.timeout': 'модель не ответила за {seconds} с',
    'm23.job.reason.invalid': 'модель не дала годных русских ключей',
    'm23.job.reason.error': 'запрос к модели не прошёл',
    'm23.job.reason.allFailed': 'модель не перевела ни одной записи',
    'm23.job.reason.protected': 'Localizer не трогает книги BunnyMo',
    'm23.job.reason.notFound': 'книга не нашлась — её переименовали или удалили?',
    'm23.job.reason.language': 'в Localizer не выбран язык перевода',
    'm23.job.reason.profile': 'профиль подключения, выбранный в Localizer, не работает',
    'm23.job.reason.connection': 'нет подключения к модели',
    'm23.job.reason.other': 'Localizer не справился',

    'm23.job.stop': 'Остановить',
    'm23.job.retry': 'Повторить',
    'm23.job.retryFailed': 'Повторить неудачные',
    'm23.job.hide': 'Скрыть',
    'm23.job.details': 'Подробнее',
    'm23.job.detail.entry': '«{entry}»: {reason}',
    'm23.job.detail.more': '…и ещё {count}',
    'm23.job.detail.message': 'Ответ Localizer: {message}',
    'm23.job.detail.book': 'Книга: {book}',
};

export const LOCALIZE_STRINGS: I18nParts = { en, ru };
