// Strings of M23 «Лор-студия» (keys m23.*). Russian is the primary language; ST's own Russian labels are reused
// for the parity controls (research/parity-lore.md, column RU) so the studio and the classic window speak alike.
import type { I18nParts } from '../../shared/contracts';

const en: Record<string, string> = {
    'm23.title': 'Lore Studio',
    'm23.close': 'Close',
    'm23.classic': 'Classic editor',
    'm23.classicHint': "Open SillyTavern's own Worlds/Lorebooks window",
    'm23.nav.label': 'Lore Studio sections',
    'm23.nav.library': 'Books',
    'm23.nav.settings': 'WI settings',
    'm23.nav.campaigns': 'DES campaigns',
    'm23.nav.books': 'Back to books',

    'm23.section.chat': 'This chat',
    'm23.section.card': 'Card',
    'm23.section.world': 'World',
    'm23.section.characters': 'Characters',
    'm23.section.system': 'System',
    'm23.section.maestro': 'Maestro',
    'm23.section.backup': 'Copies',

    'm23.role.bunnymoCore': 'BunnyMo core',
    'm23.role.bunnymoPack': 'BunnyMo pack',
    'm23.role.ckArchive': 'CK archive',
    'm23.role.world': 'world',
    'm23.role.card': 'card',
    'm23.role.npc': 'NPC',
    'm23.role.canon': 'canon',
    'm23.role.maestro': 'Maestro',
    'm23.role.chat': 'chat',
    'm23.role.persona': 'persona',
    'm23.role.backup': 'copy',
    'm23.role.unknown': 'book',

    'm23.reason.global': 'global',
    'm23.reason.character': 'character',
    'm23.reason.characterExtra': 'character (additional)',
    'm23.reason.chat': 'chat book',
    'm23.reason.persona': 'persona',
    'm23.reason.desCampaign': 'DES campaign',
    'm23.reason.desAutoLink': 'DES auto-link',
    'm23.reason.ckConnector': 'CarrotKernel',
    'm23.reason.workshop': 'DES Workshop',
    'm23.reason.canon': 'chat canon',

    'm23.books.search': 'Find a book…',
    'm23.books.create': 'New',
    'm23.books.createTitle': 'New lorebook',
    'm23.books.newName': 'New World',
    'm23.books.import': 'Import',
    'm23.books.importHint':
        'SillyTavern JSON, NovelAI (.lorebook, .png), Agnai and RisuAI — the same import as SillyTavern',
    'm23.books.onlyActive': 'Active in this chat',
    'm23.books.onlyActiveHint': 'Only books the next scan will read, with the reason',
    'm23.books.none': 'No books match.',
    'm23.books.readOnly': 'Read only: BunnyMo books are never edited (P13)',
    'm23.books.globalToggle': 'Active for all chats: {book}',
    'm23.books.globalHint': 'Active for all chats (global)',
    'm23.books.activeBecause': 'Active: {reasons}',
    'm23.books.notImported': '{file} was not imported.',

    'm23.bindings.title': 'Bindings of this chat',
    'm23.bindings.global': 'Active for all chats',
    'm23.bindings.noGlobal': 'No global books.',
    'm23.bindings.addGlobal': 'Add a global book…',
    'm23.bindings.removeGlobal': 'Remove {book} from the global books',
    'm23.bindings.character': 'Character: {name}',
    'm23.bindings.primary': 'Primary lorebook (stored in the card)',
    'm23.bindings.extra': 'Additional lorebooks ({count})',
    'm23.bindings.chat': 'Chat lorebook',
    'm23.bindings.persona': 'Persona lorebook',
    'm23.bindings.none': '— none —',
    'm23.bindings.missing': '{book} (missing)',
    'm23.bindings.group': 'Group chat: character lorebooks are set in each member card.',
    'm23.bindings.noCharacter': 'No character is selected.',

    'm23.book.rename': 'Rename book',
    'm23.book.renameTitle': 'Rename «{book}»',
    'm23.book.renameLinks': 'Links will move to the new name: {links}.',
    'm23.book.duplicate': 'Duplicate book',
    'm23.book.duplicateTitle': 'Copy of «{book}»',
    'm23.book.export': 'Export (download JSON)',
    'm23.book.localize': 'Russian keys for the book (Lorebook Localizer)',
    'm23.book.localizeBody':
        'Lorebook Localizer will translate the keys of all {count} entries of «{book}» and add Russian forms. It uses your Localizer settings and connection. The change can be undone from the journal of each entry.',
    'm23.book.localizeRun': 'Add keys',
    'm23.book.localizeProtected': 'Lorebook Localizer does not touch this book (BunnyMo).',
    'm23.book.localizeDone': 'Keys added: {added} in {entries} entries; not translated: {failures}.',
    'm23.book.classic': 'Open in the classic editor',
    'm23.book.delete': 'Delete book',
    'm23.book.deleteTitle': 'Delete the lorebook',
    'm23.book.deleteBody': 'Delete «{book}» and all its entries?',
    'm23.book.deleteLinks': 'It is still linked: {links}. These links will point to a missing book.',
    'm23.book.deleteUndo': 'A copy is kept: the deletion can be undone from the Maestro journal.',

    'm23.links.global': 'active for all chats',
    'm23.links.primary': 'primary book of {names}',
    'm23.links.extra': 'additional book of {names}',
    'm23.links.personas': 'persona book of {names}',
    'm23.links.persona': 'current persona',
    'm23.links.chat': 'book of this chat',
    'm23.links.campaigns': 'DES campaign {names}',
    'm23.links.workshop': 'Workshop: {names}',

    'm23.entries.pickBook': 'Pick a book on the left.',
    'm23.entries.loading': 'Loading…',
    'm23.entries.empty': 'No entries yet.',
    'm23.entries.noMatch': 'Nothing found.',
    'm23.entries.readOnly': 'read only',
    'm23.entries.inactive': 'Not active in this chat',
    'm23.entries.workshop': 'Workshop: {names}',
    'm23.entries.search': 'Search entries…',
    'm23.entries.sort': 'Sort',
    'm23.entries.pageSize': 'Entries per page',
    'm23.entries.perPage': '{count} per page',
    'm23.entries.new': 'New entry',
    'm23.entries.applyOrder': 'Apply current sorting as Order',
    'm23.entries.backfill': 'Fill empty titles with keywords',
    'm23.entries.expandAll': 'Open all previews on this page',
    'm23.entries.collapseAll': 'Close all previews on this page',
    'm23.entries.refresh': 'Reload from disk',
    'm23.entries.prevPage': 'Previous page',
    'm23.entries.nextPage': 'Next page',
    'm23.entries.range': '{from}–{to} of {total}',
    'm23.entries.untitled': 'Entry {uid}',
    'm23.entries.select': 'Select {title}',
    'm23.entries.drag': 'Drag to reorder',
    'm23.entries.up': 'Move up',
    'm23.entries.down': 'Move down',
    'm23.entries.enable': 'Enable entry',
    'm23.entries.disable': 'Disable entry',
    'm23.entries.openHint': 'Open the entry',
    'm23.entries.order': 'order {value}',
    'm23.entries.preview': 'Preview',
    'm23.entries.duplicate': 'Duplicate entry',
    'm23.entries.moveCopy': 'Move or copy to another book',
    'm23.entries.delete': 'Delete entry',
    'm23.entries.deleteTitle': 'Delete entries',
    'm23.entries.deleteOne': 'Delete «{title}» (UID {uid})? It can be undone from the Maestro journal.',
    'm23.entries.deleteMany': 'Delete {count} entries? It can be undone from the Maestro journal.',
    'm23.entries.findings': 'Doctor findings: {count}',
    'm23.entries.lastSeen': 'msg {index}',
    'm23.entries.lastSeenHint': 'Last turn this entry reached the prompt (lore journal)',
    'm23.entries.keys': 'Keys: {keys}',
    'm23.entries.secondary': 'Secondary: {keys}',

    'm23.status.constant': 'Constant',
    'm23.status.normal': 'Normal',
    'm23.status.vectorized': 'Vectorized',

    'm23.canon.override': 'Chat canon overrides this entry',
    'm23.canon.suppress': 'Chat canon suppresses this entry',
    'm23.canon.pin': 'Chat canon pins this entry',
    'm23.canon.addition': 'Chat canon adds to this entry',

    'm23.sort.search': 'Search',
    'm23.sort.priority': 'Priority',
    'm23.sort.custom': 'Custom',
    'm23.sort.titleAsc': 'Title A-Z',
    'm23.sort.titleDesc': 'Title Z-A',
    'm23.sort.tokensAsc': 'Tokens ↗',
    'm23.sort.tokensDesc': 'Tokens ↘',
    'm23.sort.depthAsc': 'Depth ↗',
    'm23.sort.depthDesc': 'Depth ↘',
    'm23.sort.orderAsc': 'Order ↗',
    'm23.sort.orderDesc': 'Order ↘',
    'm23.sort.uidAsc': 'UID ↗',
    'm23.sort.uidDesc': 'UID ↘',
    'm23.sort.probabilityAsc': 'Trigger% ↗',
    'm23.sort.probabilityDesc': 'Trigger% ↘',

    'm23.bulk.title': 'Selected entries',
    'm23.bulk.selected': 'Selected: {count}',
    'm23.bulk.selectPage': 'Whole page',
    'm23.bulk.selectAll': 'All found',
    'm23.bulk.clear': 'Clear',
    'm23.bulk.edit': 'Change fields…',
    'm23.bulk.enable': 'Enable selected',
    'm23.bulk.disable': 'Disable selected',
    'm23.bulk.moveCopy': 'Move or copy selected',
    'm23.bulk.delete': 'Delete selected',
    'm23.bulkEdit.title': 'Change {count} entries',
    'm23.bulkEdit.intro': 'Ticked fields are set on all {count} entries; the rest stay as they are.',
    'm23.bulkEdit.change': 'Change {field}',
    'm23.bulkEdit.mixed': 'differs',
    'm23.bulkEdit.global': 'Use global setting',
    'm23.bulkEdit.yes': 'Yes',
    'm23.bulkEdit.no': 'No',
    'm23.bulkEdit.emptyGlobal': 'empty = off / global',

    'm23.field.disable': 'Disabled',
    'm23.field.status': 'Status',
    'm23.field.positionChoice': 'Position',
    'm23.field.depth': 'Depth',
    'm23.field.order': 'Order',
    'm23.field.probability': 'Trigger %',
    'm23.field.useProbability': 'Use probability',
    'm23.field.selectiveLogic': 'Logic',
    'm23.field.group': 'Inclusion group',
    'm23.field.groupOverride': 'Prioritize in group',
    'm23.field.groupWeight': 'Group weight',
    'm23.field.scanDepth': 'Scan depth',
    'm23.field.caseSensitive': 'Case-sensitive',
    'm23.field.matchWholeWords': 'Whole words',
    'm23.field.useGroupScoring': 'Group scoring',
    'm23.field.excludeRecursion': 'Non-recursable',
    'm23.field.preventRecursion': 'Prevent further recursion',
    'm23.field.delayUntilRecursion': 'Delay until recursion (level)',
    'm23.field.ignoreBudget': 'Ignore budget',
    'm23.field.sticky': 'Sticky',
    'm23.field.cooldown': 'Cooldown',
    'm23.field.delay': 'Delay',
    'm23.field.automationId': 'Automation ID',
    'm23.field.outletName': 'Outlet name',
    'm23.field.matchPersonaDescription': 'Match persona description',
    'm23.field.matchCharacterDescription': 'Match character description',
    'm23.field.matchCharacterPersonality': 'Match character personality',
    'm23.field.matchCharacterDepthPrompt': "Match character's note",
    'm23.field.matchScenario': 'Match scenario',
    'm23.field.matchCreatorNotes': "Match creator's notes",

    'm23.position.before': '↑Char (before character)',
    'm23.position.after': '↓Char (after character)',
    'm23.position.emTop': '↑EM (before examples)',
    'm23.position.emBottom': '↓EM (after examples)',
    'm23.position.anTop': "↑AN (before author's note)",
    'm23.position.anBottom': "↓AN (after author's note)",
    'm23.position.depthSystem': '@D ⚙️ (at depth, system)',
    'm23.position.depthUser': '@D 👤 (at depth, user)',
    'm23.position.depthAssistant': '@D 🤖 (at depth, assistant)',
    'm23.position.outlet': '➡️ Outlet',

    'm23.logic.0': 'AND ANY',
    'm23.logic.3': 'AND ALL',
    'm23.logic.1': 'NOT ALL',
    'm23.logic.2': 'NOT ANY',

    'm23.order.title': 'Apply current sorting as Order',
    'm23.order.intro':
        'Assigns Order values to all entries of the book in the current sort order. Descending by default: the first entry gets the highest value.',
    'm23.order.count': '{count} entries in the book',
    'm23.order.start': 'Starting value',
    'm23.order.step': 'Step',
    'm23.order.ascending': 'Ascending order',
    'm23.order.clamped':
        'Some entries will be clamped to Order 0: the last one would reach {value} ({count} entries, step {step}).',
    'm23.order.invalid.start': 'The starting value must be 0 or more.',
    'm23.order.invalid.step': 'The step must be 1 or more.',
    'm23.order.upToDate': 'All Order values are already up to date.',
    'm23.order.updated': 'Updated {count} Order values.',

    'm23.backfill.none': 'No entries without a title have keywords.',
    'm23.backfill.done': 'Filled {count} titles.',

    'm23.move.target': 'Target book',
    'm23.move.titleOne': 'Move or copy «{title}»',
    'm23.move.titleMany': 'Move or copy {count} entries',
    'm23.move.move': 'Move',
    'm23.move.copy': 'Copy',
    'm23.move.noTargets': 'There are no other lorebooks to move to.',
    'm23.move.moved': 'Moved {count} entries to «{book}».',
    'm23.move.copied': 'Copied {count} entries to «{book}».',

    'm23.form.unavailable': 'The entry form is not available in this build.',
    'm23.form.failed': 'The entry form failed to open (see the log).',

    'm23.wi.title': 'Global World Info activation settings',
    'm23.wi.intro':
        'The same settings as in SillyTavern’s Worlds/Lorebooks window; changes go through SillyTavern’s own handlers.',
    'm23.wi.related':
        'Related settings outside this window: «Lorebook Import Dialog» in User Settings, the World Info format for Chat Completion, «Allow WI scan» in Author’s Note and Vector Storage.',
    'm23.wi.depth': 'Scan depth',
    'm23.wi.depthHint': 'How many recent messages are scanned ({min}–{max}).',
    'm23.wi.budget': 'Context %',
    'm23.wi.budgetHint': 'World Info budget as a share of the context ({min}–{max}).',
    'm23.wi.budgetCap': 'Budget cap',
    'm23.wi.budgetCapHint': 'Upper limit of the budget in tokens, 0 = no limit ({min}–{max}).',
    'm23.wi.minActivations': 'Min activations',
    'm23.wi.minActivationsHint':
        'If fewer entries activate, scanning goes further back in the history. Resets max recursion steps ({min}–{max}).',
    'm23.wi.minActivationsDepth': 'Max depth',
    'm23.wi.minActivationsDepthHint':
        'How far min activations may go back, 0 = to the start of the chat ({min}–{max}).',
    'm23.wi.maxRecursion': 'Max recursion steps',
    'm23.wi.maxRecursionHint':
        '0 = no limit, 1 = initial scan only. Disabled while min activations is set; resets it ({min}–{max}).',
    'm23.wi.strategy': 'Insertion strategy',
    'm23.wi.strategyHint': 'Chat and persona books always go first.',
    'm23.wi.strategyEven': 'Sorted evenly',
    'm23.wi.strategyCharacter': 'Character lore first',
    'm23.wi.strategyGlobal': 'Global lore first',
    'm23.wi.includeNames': 'Include names',
    'm23.wi.includeNamesHint': 'Messages are scanned as «Name: text».',
    'm23.wi.recursive': 'Recursive scan',
    'm23.wi.recursiveHint': 'Activated entries are scanned for keys of other entries.',
    'm23.wi.caseSensitive': 'Case-sensitive',
    'm23.wi.caseSensitiveHint': 'Default for entries set to «use global».',
    'm23.wi.wholeWords': 'Match whole words',
    'm23.wi.wholeWordsHint': 'Default for entries set to «use global». Cyrillic needs Maestro’s rule (M22).',
    'm23.wi.groupScoring': 'Use group scoring',
    'm23.wi.groupScoringHint': 'Default for entries set to «use global».',
    'm23.wi.overflowAlert': 'Alert on overflow',
    'm23.wi.overflowAlertHint': 'A toast when the budget is reached.',

    'm23.des.absent': "Doom's Enhancement Suite is not installed or is turned off.",
    'm23.des.loading': 'DES has not finished loading yet. Try again in a moment.',
    'm23.des.intro':
        'Campaigns belong to DES: the studio shows them and asks DES to change them (switching a campaign also swaps Workshop character versions).',
    'm23.des.activeIs': 'Active campaign: {name}',
    'm23.des.noActive': 'No active campaign.',
    'm23.des.create': 'New campaign',
    'm23.des.createTitle': 'New campaign',
    'm23.des.rename': 'Rename',
    'm23.des.renameTitle': 'Rename the campaign',
    'm23.des.delete': 'Delete campaign',
    'm23.des.deleteTitle': 'Delete the campaign',
    'm23.des.deleteBody': 'Delete «{name}»? Its books become unfiled; its character versions are deleted.',
    'm23.des.deleteActive':
        '«{name}» is active: it will be switched off first (its books turned off, characters back to base), then deleted with its character versions.',
    'm23.des.activate': 'Make active',
    'm23.des.deactivate': 'Switch off the active campaign',
    'm23.des.active': 'ACTIVE',
    'm23.des.countHint': 'Active / all books',
    'm23.des.up': 'Move up',
    'm23.des.down': 'Move down',
    'm23.des.icon': 'Icon and colour',
    'm23.des.defaultColor': 'Default colour',
    'm23.des.emptyCampaign': 'No books in this campaign.',
    'm23.des.noCampaigns': 'No campaigns yet.',
    'm23.des.unfiled': 'Unfiled',
    'm23.des.unfiledCount': 'Unfiled books ({count})',
    'm23.des.moveBook': 'Campaign of {book}',
    'm23.des.openBook': 'Open in the studio',
    'm23.des.autoLinked': 'auto-linked',
    'm23.des.globalOn': 'DES global book: never switched off by campaigns or auto-link',
    'm23.des.globalOff': 'Mark as a DES global book',
    'm23.des.autoLink': 'Auto-link books by character name (DES)',
    'm23.des.autoLinkHint': 'A book named exactly like a character of the chat roster is switched on by DES.',
    'm23.des.autoLinkTitle': 'Auto-link is a DES setting',
    'm23.des.autoLinkExplain':
        'This switch changes the DES setting itself: DES will keep turning on books named after characters of the chat. Change it?',
    'm23.des.interceptOn': 'DES Lore Library takes over the Worlds/Lorebooks button (DES setting).',
    'm23.des.interceptOff': 'DES Lore Library does not take over the Worlds/Lorebooks button.',
    'm23.des.switching': 'DES is switching campaigns…',
    'm23.des.manualOffHint':
        '«{book}» belongs to the active campaign or was auto-linked: DES may switch it on again on its next sync.',
    'm23.des.workshop': 'Workshop book links ({count})',
    'm23.des.workshopHint': 'Read only: change them in the DES Workshop.',

    'm23.tab.intro':
        'A lorebook editor that knows about roles, the chat canon and Russian keys. It works next to SillyTavern’s own window.',
    'm23.tab.books': 'Books: {count}',
    'm23.tab.open': 'Open the Lore Studio',
    'm23.tab.takeoverTitle': 'The Worlds/Lorebooks button',
    'm23.tab.takeover': 'Open the Lore Studio from the Worlds/Lorebooks button',
    'm23.tab.takeoverHint':
        'SillyTavern’s handler and DES Lore Library’s interception are put aside and restored when this is turned off or Maestro is disabled. The classic window stays one click away.',
    'm23.tab.takeoverActive': 'The button opens the Lore Studio now.',
    'm23.tab.takeoverInactive': 'The button opens SillyTavern’s window (or DES Lore Library).',
    'm23.tab.takeoverFailed': 'The button could not be taken over: SillyTavern’s handler or the button was not found.',
    'm23.tab.slash': 'Command: /maestro-lore [book] opens the studio.',

    'm23.slash.help': 'Opens the Maestro Lore Studio, optionally on a book.',
    'm23.slash.book': 'Book name',

    'm23.dialog.ok': 'OK',
    'm23.dialog.cancel': 'Cancel',
    'm23.dialog.apply': 'Apply',
    'm23.dialog.delete': 'Delete',

    'm23.history.external': 'Changed outside Maestro',

    'm23.journal.createBook': 'Created the lorebook «{book}»',
    'm23.journal.duplicateBook': 'Copied «{book}» to «{copy}»',
    'm23.journal.renameBook': 'Renamed «{book}» to «{to}»',
    'm23.journal.deleteBook': 'Deleted the lorebook «{book}»',
    'm23.journal.importBook': 'Imported the lorebook «{book}»',
    'm23.journal.createEntry': 'New entry in «{book}»',
    'm23.journal.duplicateEntry': 'Duplicated entry {uid} in «{book}»',
    'm23.journal.deleteEntries': 'Deleted {count} entries in «{book}»',
    'm23.journal.moveEntries': 'Moved {count} entries from «{from}» to «{to}»',
    'm23.journal.copyEntries': 'Copied {count} entries from «{from}» to «{to}»',
    'm23.journal.enable': 'Enabled {count} entries in «{book}»',
    'm23.journal.disable': 'Disabled {count} entries in «{book}»',
    'm23.journal.status': 'Changed the status of entry {uid} in «{book}»',
    'm23.journal.reorder': 'Changed the manual order in «{book}»',
    'm23.journal.applyOrder': 'Set Order of {count} entries in «{book}»',
    'm23.journal.backfill': 'Filled {count} titles in «{book}»',
    'm23.journal.bulkEdit': 'Changed {count} entries in «{book}»',
    'm23.journal.restoreVersion': 'Restored a version of entry {uid} in «{book}»',
    'm23.journal.undo': 'Undo in «{book}»',
    'm23.journal.settings': 'Changed {count} World Info settings',
    'm23.journal.binding.global': 'Changed the global books',
    'm23.journal.binding.primary': 'Changed the primary lorebook of the character',
    'm23.journal.binding.extra': 'Changed the additional lorebooks of the character',
    'm23.journal.binding.chat': 'Changed the chat lorebook',
    'm23.journal.binding.persona': 'Changed the persona lorebook',

    'm23.card.embedded': 'The card has an embedded lorebook «{book}».',
    'm23.card.import': 'Import card lore',
    'm23.card.importTitle': 'Import «{book}»?',
    'm23.card.importBody': 'The embedded book is saved as a lorebook and becomes the character’s primary lorebook.',
    'm23.card.overwrite':
        'A lorebook with this name exists and will be overwritten (the old content can be restored from the Maestro journal).',
    'm23.journal.importCardBook': 'Imported the card lore «{book}» of {name}',
    'm23.error.noCardBook': 'This character has no embedded lorebook.',
    'm23.error.generic': 'Lore Studio: {error}',
    'm23.error.readOnly': '«{book}» is read-only (BunnyMo books are never edited).',
    'm23.error.missing': 'The book «{book}» was not found.',
    'm23.error.missingEntry': 'Entry {uid} was not found in «{book}».',
    'm23.error.exists': 'A book named «{name}» already exists.',
    'm23.error.sameName': 'The new name is the same as the old one (ignoring case and accents).',
    'm23.error.emptyName': 'The name is empty or has no allowed characters.',
    'm23.error.deleteFailed': 'SillyTavern did not delete «{book}».',
    'm23.error.unavailable': 'This SillyTavern does not offer what the studio needs here.',
    'm23.error.noChat': 'Open a chat first.',
    'm23.error.noCharacter': 'Select a character first (group chats bind books in each member card).',
    'm23.error.personaName': 'Bind a name to this persona before setting its lorebook.',
    'm23.error.desUnavailable': 'DES is not available.',
    'm23.error.workshopOpen': 'Close the DES Workshop first: switching campaigns rewrites its characters.',
    'm23.error.classicUnavailable': 'The classic Worlds/Lorebooks window could not be opened.',
};

const ru: Record<string, string> = {
    'm23.title': 'Лор-студия',
    'm23.close': 'Закрыть',
    'm23.classic': 'Классический редактор',
    'm23.classicHint': 'Открыть штатное окно «Миры и лорбуки» SillyTavern',
    'm23.nav.label': 'Разделы Лор-студии',
    'm23.nav.library': 'Книги',
    'm23.nav.settings': 'Настройки WI',
    'm23.nav.campaigns': 'Кампании DES',
    'm23.nav.books': 'К списку книг',

    'm23.section.chat': 'Этот чат',
    'm23.section.card': 'Карточка',
    'm23.section.world': 'Мир',
    'm23.section.characters': 'Персонажи',
    'm23.section.system': 'Система',
    'm23.section.maestro': 'Maestro',
    'm23.section.backup': 'Копии',

    'm23.role.bunnymoCore': 'ядро BunnyMo',
    'm23.role.bunnymoPack': 'пак BunnyMo',
    'm23.role.ckArchive': 'архив CK',
    'm23.role.world': 'мир',
    'm23.role.card': 'карточка',
    'm23.role.npc': 'NPC',
    'm23.role.canon': 'канон',
    'm23.role.maestro': 'Maestro',
    'm23.role.chat': 'чат',
    'm23.role.persona': 'персона',
    'm23.role.backup': 'копия',
    'm23.role.unknown': 'книга',

    'm23.reason.global': 'глобально',
    'm23.reason.character': 'персонаж',
    'm23.reason.characterExtra': 'персонаж (дополнительная)',
    'm23.reason.chat': 'книга чата',
    'm23.reason.persona': 'персона',
    'm23.reason.desCampaign': 'кампания DES',
    'm23.reason.desAutoLink': 'автопривязка DES',
    'm23.reason.ckConnector': 'CarrotKernel',
    'm23.reason.workshop': 'Workshop DES',
    'm23.reason.canon': 'канон чата',

    'm23.books.search': 'Найти книгу…',
    'm23.books.create': 'Создать',
    'm23.books.createTitle': 'Новый лорбук',
    'm23.books.newName': 'Новый мир',
    'm23.books.import': 'Импорт',
    'm23.books.importHint':
        'JSON SillyTavern, NovelAI (.lorebook, .png), Agnai и RisuAI — тот же импорт, что в SillyTavern',
    'm23.books.onlyActive': 'Активные в этом чате',
    'm23.books.onlyActiveHint': 'Только книги, которые прочитает следующее сканирование, с причиной',
    'm23.books.none': 'Подходящих книг нет.',
    'm23.books.readOnly': 'Только чтение: книги BunnyMo не правятся (P13)',
    'm23.books.globalToggle': 'Активна во всех чатах: {book}',
    'm23.books.globalHint': 'Активна во всех чатах (глобально)',
    'm23.books.activeBecause': 'Активна: {reasons}',
    'm23.books.notImported': '{file} не импортирован.',

    'm23.bindings.title': 'Привязки этого чата',
    'm23.bindings.global': 'Активные во всех чатах',
    'm23.bindings.noGlobal': 'Глобальных книг нет.',
    'm23.bindings.addGlobal': 'Добавить глобальную книгу…',
    'm23.bindings.removeGlobal': 'Убрать {book} из глобальных',
    'm23.bindings.character': 'Персонаж: {name}',
    'm23.bindings.primary': 'Основной лорбук (хранится в карточке)',
    'm23.bindings.extra': 'Вспомогательные лорбуки ({count})',
    'm23.bindings.chat': 'Лорбук чата',
    'm23.bindings.persona': 'Лорбук персоны',
    'm23.bindings.none': '— нет —',
    'm23.bindings.missing': '{book} (нет такой книги)',
    'm23.bindings.group': 'Групповой чат: книги персонажей задаются в карточке каждого участника.',
    'm23.bindings.noCharacter': 'Персонаж не выбран.',

    'm23.book.rename': 'Переименовать книгу',
    'm23.book.renameTitle': 'Переименовать «{book}»',
    'm23.book.renameLinks': 'Ссылки перейдут на новое имя: {links}.',
    'm23.book.duplicate': 'Копия книги',
    'm23.book.duplicateTitle': 'Копия «{book}»',
    'm23.book.export': 'Экспорт (скачать JSON)',
    'm23.book.localize': 'Русские ключи для книги (Lorebook Localizer)',
    'm23.book.localizeBody':
        'Lorebook Localizer переведёт ключи всех записей книги «{book}» ({count}) и добавит русские формы. Используются твои настройки и подключение Localizer.',
    'm23.book.localizeRun': 'Добавить ключи',
    'm23.book.localizeProtected': 'Эту книгу Lorebook Localizer не трогает (BunnyMo).',
    'm23.book.localizeDone': 'Добавлено ключей: {added} в {entries} записях; без перевода: {failures}.',
    'm23.book.classic': 'Открыть в классическом редакторе',
    'm23.book.delete': 'Удалить книгу',
    'm23.book.deleteTitle': 'Удаление лорбука',
    'm23.book.deleteBody': 'Удалить «{book}» вместе со всеми записями?',
    'm23.book.deleteLinks': 'На неё ещё ссылаются: {links}. Эти ссылки будут вести в пустоту.',
    'm23.book.deleteUndo': 'Копия сохранится: удаление можно отменить в журнале Maestro.',

    'm23.links.global': 'активна во всех чатах',
    'm23.links.primary': 'основная книга: {names}',
    'm23.links.extra': 'вспомогательная книга: {names}',
    'm23.links.personas': 'книга персоны: {names}',
    'm23.links.persona': 'текущая персона',
    'm23.links.chat': 'книга этого чата',
    'm23.links.campaigns': 'кампания DES {names}',
    'm23.links.workshop': 'Workshop: {names}',

    'm23.entries.pickBook': 'Выбери книгу слева.',
    'm23.entries.loading': 'Загрузка…',
    'm23.entries.empty': 'Записей пока нет.',
    'm23.entries.noMatch': 'Ничего не найдено.',
    'm23.entries.readOnly': 'только чтение',
    'm23.entries.inactive': 'В этом чате не активна',
    'm23.entries.workshop': 'Workshop: {names}',
    'm23.entries.search': 'Поиск по записям…',
    'm23.entries.sort': 'Сортировка',
    'm23.entries.pageSize': 'Записей на странице',
    'm23.entries.perPage': 'по {count}',
    'm23.entries.new': 'Новая запись',
    'm23.entries.applyOrder': 'Выставить приоритеты по текущей сортировке',
    'm23.entries.backfill': 'Заполнить пустые названия ключевыми словами',
    'm23.entries.expandAll': 'Раскрыть все превью на странице',
    'm23.entries.collapseAll': 'Свернуть все превью на странице',
    'm23.entries.refresh': 'Перечитать с диска',
    'm23.entries.prevPage': 'Предыдущая страница',
    'm23.entries.nextPage': 'Следующая страница',
    'm23.entries.range': '{from}–{to} из {total}',
    'm23.entries.untitled': 'Запись {uid}',
    'm23.entries.select': 'Выбрать: {title}',
    'm23.entries.drag': 'Перетащи, чтобы поменять порядок',
    'm23.entries.up': 'Выше',
    'm23.entries.down': 'Ниже',
    'm23.entries.enable': 'Включить запись',
    'm23.entries.disable': 'Выключить запись',
    'm23.entries.openHint': 'Открыть запись',
    'm23.entries.order': 'приоритет {value}',
    'm23.entries.preview': 'Превью',
    'm23.entries.duplicate': 'Дублировать запись',
    'm23.entries.moveCopy': 'Переместить или скопировать в другую книгу',
    'm23.entries.delete': 'Удалить запись',
    'm23.entries.deleteTitle': 'Удаление записей',
    'm23.entries.deleteOne': 'Удалить «{title}» (UID {uid})? Отменить можно в журнале Maestro.',
    'm23.entries.deleteMany': 'Удалить записей: {count}? Отменить можно в журнале Maestro.',
    'm23.entries.findings': 'Находок доктора: {count}',
    'm23.entries.lastSeen': 'сообщ. {index}',
    'm23.entries.lastSeenHint': 'Последний ход, когда запись попала в промпт (журнал лора)',
    'm23.entries.keys': 'Ключи: {keys}',
    'm23.entries.secondary': 'Дополнительный фильтр: {keys}',

    'm23.status.constant': 'Постоянная',
    'm23.status.normal': 'Обычная',
    'm23.status.vectorized': 'Векторизованная',

    'm23.canon.override': 'Канон чата переопределяет эту запись',
    'm23.canon.suppress': 'Канон чата подавляет эту запись',
    'm23.canon.pin': 'Канон чата закрепляет эту запись',
    'm23.canon.addition': 'Канон чата дополняет эту запись',

    'm23.sort.search': 'Поиск',
    'm23.sort.priority': 'Приоритет',
    'm23.sort.custom': 'Пользовательский',
    'm23.sort.titleAsc': 'Название от A до Z',
    'm23.sort.titleDesc': 'Название от Z до A',
    'm23.sort.tokensAsc': 'Токены ↗',
    'm23.sort.tokensDesc': 'Токены ↘',
    'm23.sort.depthAsc': 'Глубина ↗',
    'm23.sort.depthDesc': 'Глубина ↘',
    'm23.sort.orderAsc': 'Порядок ↗',
    'm23.sort.orderDesc': 'Порядок ↘',
    'm23.sort.uidAsc': 'UID ↗',
    'm23.sort.uidDesc': 'UID ↘',
    'm23.sort.probabilityAsc': '% срабатываний ↗',
    'm23.sort.probabilityDesc': '% срабатываний ↘',

    'm23.bulk.title': 'Выбранные записи',
    'm23.bulk.selected': 'Выбрано: {count}',
    'm23.bulk.selectPage': 'Всю страницу',
    'm23.bulk.selectAll': 'Все найденные',
    'm23.bulk.clear': 'Снять выбор',
    'm23.bulk.edit': 'Изменить поля…',
    'm23.bulk.enable': 'Включить выбранные',
    'm23.bulk.disable': 'Выключить выбранные',
    'm23.bulk.moveCopy': 'Переместить или скопировать выбранные',
    'm23.bulk.delete': 'Удалить выбранные',
    'm23.bulkEdit.title': 'Изменить записи: {count}',
    'm23.bulkEdit.intro':
        'Отмеченные поля получат одно значение во всех записях ({count}); остальные останутся как есть.',
    'm23.bulkEdit.change': 'Изменить: {field}',
    'm23.bulkEdit.mixed': 'разные',
    'm23.bulkEdit.global': 'Глоб. настройка',
    'm23.bulkEdit.yes': 'Да',
    'm23.bulkEdit.no': 'Нет',
    'm23.bulkEdit.emptyGlobal': 'пусто = выкл. / глобально',

    'm23.field.disable': 'Выключена',
    'm23.field.status': 'Статус',
    'm23.field.positionChoice': 'Положение',
    'm23.field.depth': 'Глубина',
    'm23.field.order': 'Приоритет',
    'm23.field.probability': 'Вероятность, %',
    'm23.field.useProbability': 'Использовать вероятность',
    'm23.field.selectiveLogic': 'Логика',
    'm23.field.group': 'Группа записей',
    'm23.field.groupOverride': 'Важная в группе',
    'm23.field.groupWeight': 'Вес в группе',
    'm23.field.scanDepth': 'Глубина сканирования',
    'm23.field.caseSensitive': 'С учётом регистра',
    'm23.field.matchWholeWords': 'Целые слова',
    'm23.field.useGroupScoring': 'Group Scoring',
    'm23.field.excludeRecursion': 'Не рекурсивная',
    'm23.field.preventRecursion': 'Пресечь дальнейшую рекурсию',
    'm23.field.delayUntilRecursion': 'Рекурсивная (уровень)',
    'm23.field.ignoreBudget': 'Игнорировать бюджет',
    'm23.field.sticky': 'Липучка',
    'm23.field.cooldown': 'Кулдаун',
    'm23.field.delay': 'Задержка',
    'm23.field.automationId': 'Automation ID',
    'm23.field.outletName': 'Outlet',
    'm23.field.matchPersonaDescription': 'Искать в описании персоны',
    'm23.field.matchCharacterDescription': 'Искать в описании персонажа',
    'm23.field.matchCharacterPersonality': 'Искать в характере персонажа',
    'm23.field.matchCharacterDepthPrompt': 'Искать в заметке о персонаже',
    'm23.field.matchScenario': 'Искать в сценарии',
    'm23.field.matchCreatorNotes': 'Искать в примечании от создателя',

    'm23.position.before': '↑Перс. (перед описанием персонажа)',
    'm23.position.after': '↓Перс. (после описания персонажа)',
    'm23.position.emTop': '↑ПС (перед примерами сообщений)',
    'm23.position.emBottom': '↓ПС (после примеров сообщений)',
    'm23.position.anTop': '↑АЗ (перед заметками автора)',
    'm23.position.anBottom': '↓АЗ (после заметок автора)',
    'm23.position.depthSystem': 'На глуб. ⚙️ (система)',
    'm23.position.depthUser': 'На глуб. 👤 (пользователь)',
    'm23.position.depthAssistant': 'На глуб. 🤖 (ассистент)',
    'm23.position.outlet': '➡️ Outlet',

    'm23.logic.0': 'И ЛЮБОЙ',
    'm23.logic.3': 'И ВСЕ',
    'm23.logic.1': 'НЕ ВСЕ',
    'm23.logic.2': 'НЕ ЛЮБОЙ',

    'm23.order.title': 'Приоритеты по текущей сортировке',
    'm23.order.intro':
        'Всем записям книги выставляется «Приоритет» в порядке текущей сортировки. По умолчанию по убыванию: первая запись получает наибольшее значение.',
    'm23.order.count': 'Записей в книге: {count}',
    'm23.order.start': 'Начальное значение',
    'm23.order.step': 'Шаг',
    'm23.order.ascending': 'По возрастанию',
    'm23.order.clamped':
        'Часть записей упрётся в 0 и получит одинаковый приоритет: последняя дошла бы до {value} (записей {count}, шаг {step}).',
    'm23.order.invalid.start': 'Начальное значение должно быть не меньше 0.',
    'm23.order.invalid.step': 'Шаг должен быть не меньше 1.',
    'm23.order.upToDate': 'Все приоритеты уже такие.',
    'm23.order.updated': 'Обновлено приоритетов: {count}.',

    'm23.backfill.none': 'Нет записей без названия, у которых есть ключи.',
    'm23.backfill.done': 'Заполнено названий: {count}.',

    'm23.move.target': 'Куда',
    'm23.move.titleOne': 'Переместить или скопировать «{title}»',
    'm23.move.titleMany': 'Переместить или скопировать записи: {count}',
    'm23.move.move': 'Переместить',
    'm23.move.copy': 'Скопировать',
    'm23.move.noTargets': 'Других лорбуков, куда можно перенести, нет.',
    'm23.move.moved': 'Перемещено в «{book}»: {count}.',
    'm23.move.copied': 'Скопировано в «{book}»: {count}.',

    'm23.form.unavailable': 'Форма записи в этой сборке недоступна.',
    'm23.form.failed': 'Форма записи не открылась (подробности в логе).',

    'm23.wi.title': 'Глобальные настройки активации лорбуков',
    'm23.wi.intro':
        'Те же настройки, что в окне «Миры и лорбуки» SillyTavern; изменения проходят через обработчики самого SillyTavern.',
    'm23.wi.related':
        'Смежные настройки вне этого окна: «Показывать окно импорта лорбука» в настройках пользователя, формат World Info для Chat Completion, «Allow WI scan» в заметках автора и Vector Storage.',
    'm23.wi.depth': 'Глубина сканирования',
    'm23.wi.depthHint': 'Сколько последних сообщений сканировать ({min}–{max}).',
    'm23.wi.budget': 'Процент контекста',
    'm23.wi.budgetHint': 'Бюджет World Info в процентах от контекста ({min}–{max}).',
    'm23.wi.budgetCap': 'Лимит бюджета',
    'm23.wi.budgetCapHint': 'Верхний предел бюджета в токенах, 0 — без предела ({min}–{max}).',
    'm23.wi.minActivations': 'Мин. число активаций',
    'm23.wi.minActivationsHint':
        'Если сработало меньше записей, сканирование уходит глубже в историю. Обнуляет «Макс. глубину рекурсии» ({min}–{max}).',
    'm23.wi.minActivationsDepth': 'Макс. глубина',
    'm23.wi.minActivationsDepthHint':
        'Насколько глубоко может уйти «Мин. число активаций», 0 — до начала чата ({min}–{max}).',
    'm23.wi.maxRecursion': 'Макс. глубина рекурсии',
    'm23.wi.maxRecursionHint':
        '0 — без предела, 1 — только начальный проход. Не действует при заданном мин. числе активаций и обнуляет его ({min}–{max}).',
    'm23.wi.strategy': 'Как инжектить',
    'm23.wi.strategyHint': 'Книги чата и персоны всегда идут первыми.',
    'm23.wi.strategyEven': 'Равномерная сортировка',
    'm23.wi.strategyCharacter': 'Сначала лор персонажа',
    'm23.wi.strategyGlobal': 'Сначала глобальный лор',
    'm23.wi.includeNames': 'Добавлять имена',
    'm23.wi.includeNamesHint': 'Сообщения сканируются в виде «Имя: текст».',
    'm23.wi.recursive': 'Рекурсивное сканирование',
    'm23.wi.recursiveHint': 'Текст сработавших записей проверяется на ключи других записей.',
    'm23.wi.caseSensitive': 'Учитывать регистр',
    'm23.wi.caseSensitiveHint': 'Значение для записей с «глоб. настройкой».',
    'm23.wi.wholeWords': 'Только полное совпадение',
    'm23.wi.wholeWordsHint': 'Значение для записей с «глоб. настройкой». Для кириллицы нужно правило Maestro (M22).',
    'm23.wi.groupScoring': 'Использовать Group Scoring',
    'm23.wi.groupScoringHint': 'Значение для записей с «глоб. настройкой».',
    'm23.wi.overflowAlert': 'Оповещение о превышении бюджета',
    'm23.wi.overflowAlertHint': 'Всплывающее сообщение, когда бюджет исчерпан.',

    'm23.des.absent': "Doom's Enhancement Suite не установлен или выключен.",
    'm23.des.loading': 'DES ещё не загрузился. Попробуй чуть позже.',
    'm23.des.intro':
        'Кампании принадлежат DES: студия их показывает и просит DES их менять (переключение кампании ещё и меняет версии персонажей в Workshop).',
    'm23.des.activeIs': 'Активная кампания: {name}',
    'm23.des.noActive': 'Активной кампании нет.',
    'm23.des.create': 'Новая кампания',
    'm23.des.createTitle': 'Новая кампания',
    'm23.des.rename': 'Переименовать',
    'm23.des.renameTitle': 'Новое имя кампании',
    'm23.des.delete': 'Удалить кампанию',
    'm23.des.deleteTitle': 'Удаление кампании',
    'm23.des.deleteBody': 'Удалить «{name}»? Книги останутся без кампании, версии персонажей этой кампании удалятся.',
    'm23.des.deleteActive':
        '«{name}» сейчас активна: сначала она будет снята (её книги выключатся, персонажи вернутся к базовым версиям), затем удалена вместе с версиями персонажей.',
    'm23.des.activate': 'Сделать активной',
    'm23.des.deactivate': 'Снять активную кампанию',
    'm23.des.active': 'АКТИВНА',
    'm23.des.countHint': 'Активных книг / всего',
    'm23.des.up': 'Выше',
    'm23.des.down': 'Ниже',
    'm23.des.icon': 'Значок и цвет',
    'm23.des.defaultColor': 'Цвет по умолчанию',
    'm23.des.emptyCampaign': 'В кампании нет книг.',
    'm23.des.noCampaigns': 'Кампаний пока нет.',
    'm23.des.unfiled': 'Без кампании',
    'm23.des.unfiledCount': 'Книги без кампании ({count})',
    'm23.des.moveBook': 'Кампания книги {book}',
    'm23.des.openBook': 'Открыть в студии',
    'm23.des.autoLinked': 'автопривязка',
    'm23.des.globalOn': 'Глобальная книга DES: ни кампании, ни автопривязка её не выключают',
    'm23.des.globalOff': 'Отметить как глобальную книгу DES',
    'm23.des.autoLink': 'Автопривязка книг по имени персонажа (DES)',
    'm23.des.autoLinkHint': 'Книгу, названную точно как персонаж из состава чата, DES включает сам.',
    'm23.des.autoLinkTitle': 'Автопривязка — настройка DES',
    'm23.des.autoLinkExplain':
        'Переключатель меняет настройку самого DES: он будет включать книги, названные по именам персонажей чата. Изменить?',
    'm23.des.interceptOn': 'Lore Library DES перехватывает кнопку «Миры и лорбуки» (настройка DES).',
    'm23.des.interceptOff': 'Lore Library DES не перехватывает кнопку «Миры и лорбуки».',
    'm23.des.switching': 'DES переключает кампанию…',
    'm23.des.manualOffHint':
        '«{book}» входит в активную кампанию или включена автопривязкой: при следующей сверке DES может включить её снова.',
    'm23.des.workshop': 'Книги в Workshop ({count})',
    'm23.des.workshopHint': 'Только просмотр: менять — в Workshop DES.',

    'm23.tab.intro':
        'Редактор лорбуков, который знает про роли книг, канон чата и русские ключи. Работает рядом со штатным окном SillyTavern.',
    'm23.tab.books': 'Книг: {count}',
    'm23.tab.open': 'Открыть Лор-студию',
    'm23.tab.takeoverTitle': 'Кнопка «Миры и лорбуки»',
    'm23.tab.takeover': 'Открывать Лор-студию кнопкой «Миры и лорбуки»',
    'm23.tab.takeoverHint':
        'Обработчик SillyTavern и перехват Lore Library DES откладываются в сторону и возвращаются, когда выключишь это или Maestro. Классическое окно остаётся в один клик.',
    'm23.tab.takeoverActive': 'Сейчас кнопка открывает Лор-студию.',
    'm23.tab.takeoverInactive': 'Сейчас кнопка открывает окно SillyTavern (или Lore Library DES).',
    'm23.tab.takeoverFailed': 'Перехватить кнопку не удалось: не нашлись кнопка или обработчик SillyTavern.',
    'm23.tab.slash': 'Команда /maestro-lore [книга] открывает студию.',

    'm23.slash.help': 'Открывает Лор-студию Maestro, можно сразу на книге.',
    'm23.slash.book': 'Название книги',

    'm23.dialog.ok': 'ОК',
    'm23.dialog.cancel': 'Отмена',
    'm23.dialog.apply': 'Применить',
    'm23.dialog.delete': 'Удалить',

    'm23.history.external': 'Изменено вне Maestro',

    'm23.journal.createBook': 'Создан лорбук «{book}»',
    'm23.journal.duplicateBook': '«{book}» скопирован в «{copy}»',
    'm23.journal.renameBook': '«{book}» переименован в «{to}»',
    'm23.journal.deleteBook': 'Удалён лорбук «{book}»',
    'm23.journal.importBook': 'Импортирован лорбук «{book}»',
    'm23.journal.createEntry': 'Новая запись в «{book}»',
    'm23.journal.duplicateEntry': 'Копия записи {uid} в «{book}»',
    'm23.journal.deleteEntries': 'Удалено записей в «{book}»: {count}',
    'm23.journal.moveEntries': 'Перенесено записей из «{from}» в «{to}»: {count}',
    'm23.journal.copyEntries': 'Скопировано записей из «{from}» в «{to}»: {count}',
    'm23.journal.enable': 'Включено записей в «{book}»: {count}',
    'm23.journal.disable': 'Выключено записей в «{book}»: {count}',
    'm23.journal.status': 'Статус записи {uid} в «{book}»',
    'm23.journal.reorder': 'Ручной порядок в «{book}»',
    'm23.journal.applyOrder': 'Приоритеты записей в «{book}»: {count}',
    'm23.journal.backfill': 'Заполнено названий в «{book}»: {count}',
    'm23.journal.bulkEdit': 'Изменено записей в «{book}»: {count}',
    'm23.journal.restoreVersion': 'Возвращена версия записи {uid} в «{book}»',
    'm23.journal.undo': 'Отмена в «{book}»',
    'm23.journal.settings': 'Изменено настроек World Info: {count}',
    'm23.journal.binding.global': 'Изменены глобальные книги',
    'm23.journal.binding.primary': 'Изменён основной лорбук персонажа',
    'm23.journal.binding.extra': 'Изменены вспомогательные лорбуки персонажа',
    'm23.journal.binding.chat': 'Изменён лорбук чата',
    'm23.journal.binding.persona': 'Изменён лорбук персоны',

    'm23.card.embedded': 'В карточке есть встроенный лорбук «{book}».',
    'm23.card.import': 'Импортировать лор карточки',
    'm23.card.importTitle': 'Импортировать «{book}»?',
    'm23.card.importBody': 'Встроенная книга сохранится как лорбук и станет основным лорбуком персонажа.',
    'm23.card.overwrite':
        'Лорбук с таким именем уже есть и будет перезаписан (прежнее содержимое можно вернуть из журнала Maestro).',
    'm23.journal.importCardBook': 'Импортирован лор карточки «{book}» ({name})',
    'm23.error.noCardBook': 'У этого персонажа нет встроенного лорбука.',
    'm23.error.generic': 'Лор-студия: {error}',
    'm23.error.readOnly': '«{book}» — только для чтения (книги BunnyMo не правятся).',
    'm23.error.missing': 'Книга «{book}» не найдена.',
    'm23.error.missingEntry': 'В «{book}» нет записи {uid}.',
    'm23.error.exists': 'Книга «{name}» уже есть.',
    'm23.error.sameName': 'Новое имя совпадает со старым (без учёта регистра и диакритики).',
    'm23.error.emptyName': 'Имя пустое или состоит из недопустимых символов.',
    'm23.error.deleteFailed': 'SillyTavern не удалил «{book}».',
    'm23.error.unavailable': 'В этой версии SillyTavern нет того, что здесь нужно студии.',
    'm23.error.noChat': 'Сначала открой чат.',
    'm23.error.noCharacter': 'Сначала выбери персонажа (в групповом чате книги задаются в карточке каждого участника).',
    'm23.error.personaName': 'Сначала дай этой персоне имя — без него лорбук не привязать.',
    'm23.error.desUnavailable': 'DES недоступен.',
    'm23.error.workshopOpen': 'Сначала закрой Workshop DES: переключение кампаний переписывает его персонажей.',
    'm23.error.classicUnavailable': 'Не удалось открыть классическое окно «Миры и лорбуки».',
};

export const M23_STRINGS: I18nParts = { en, ru };
