// Strings of M9 «Летопись, автопамять и „Ранее в истории…"» (`m9.*`, autonomy kinds `kind.chronicle.*`, journal
// targets `target.m9.*`) and how those targets read in Inbox cards and the journal. Russian is the primary UI language;
// the user is addressed as «ты» (male).
import { formatClip, formatEnum, formatPlain } from '../../core/labels';
import type { I18nParts, TargetSpec } from '../../shared/contracts';

/**
 * A chapter reads by its title; keys and the typed content (English field labels) stay under «Подробнее», as do the
 * canon drafts of a merge and Qvink's per-swipe flags of a «remember» mark.
 */
export const CHRONICLE_TARGETS: TargetSpec[] = [
    {
        target: 'm9.chapter',
        fields: {
            title: { labelKey: 'm9.field.chapter', format: formatClip(100) },
            keys: { labelKey: 'm9.field.keys', hidden: true },
            secondary: { labelKey: 'm9.field.keys', hidden: true },
            content: { labelKey: 'm9.field.text', hidden: true },
        },
    },
    {
        target: 'm9.merge',
        fields: {
            title: { labelKey: 'm9.field.chapter', format: formatClip(100) },
            keys: { labelKey: 'm9.field.keys', hidden: true },
            secondary: { labelKey: 'm9.field.keys', hidden: true },
        },
    },
    // before 'active' → after 'archived'
    { target: 'm9.archive', valueLabelKey: 'm9.field.state', format: formatEnum('m9.state.') },
    {
        target: 'm9.remember',
        fields: {
            remember: { labelKey: 'm9.field.remember', format: formatPlain },
            live: { labelKey: 'm9.field.remember', hidden: true },
            swipes: { labelKey: 'm9.field.remember', hidden: true },
        },
    },
];

export const CHRONICLE_STRINGS: I18nParts = {
    en: {
        'm9.title': 'Chronicle and memory',
        'm9.tab': 'Chronicle',
        'm9.noChat': 'No chat is open.',
        'm9.profileTask': 'Chronicle: «Previously in the story…»',
        'kind.chronicle.chapter': 'Chronicle chapters from forgotten memories',
        'kind.chronicle.merge': 'Merging small chronicle chapters',
        'kind.chronicle.archive': 'Archiving old chronicle chapters',
        'kind.chronicle.remember': '«Remember» marks in Qvink',
        'target.m9.chapter': 'Chronicle chapter',
        'target.m9.merge': 'Merged chronicle chapters',
        'target.m9.archive': 'Chronicle chapter',
        'target.m9.remember': '«Remember» mark in Qvink',
        'm9.field.chapter': 'Chapter',
        'm9.field.keys': 'Keys',
        'm9.field.text': 'Text',
        'm9.field.state': 'State',
        'm9.field.remember': 'Keep in long-term memory',
        'm9.state.active': 'active',
        'm9.state.archived': 'archived',
        'm9.warn.noQvink':
            'Qvink Memory is not installed or is off for this chat: no chapters and no «remember» marks.',
        'm9.warn.noCanon': 'Chronicle chapters have nowhere to go: the «Chat canon» module is off.',
        'm9.error.noCanon': 'The chronicle has nowhere to go: the «Chat canon» module is off.',
        'm9.error.messageGone': 'The message has changed or is gone.',
        'm9.error.noStudio': 'The Lore Studio is off: open the canon book in the lorebook editor.',
        'm9.chapter.comment': 'Chronicle: {title} (#{from}–{to})',
        'm9.range.one': 'message #{from}',
        'm9.range.many': 'messages #{from}–{to}',
        'm9.chapter.label': '«{name}» ({range})',
        'm9.chapter.proposal': 'New chronicle chapter: {title} ({range})',
        'm9.chapter.proposal.range': 'New chronicle chapter: {range}',
        'm9.chapter.description':
            "The memories of {range} no longer fit in Qvink's long-term memory. I will keep them as a chronicle chapter in the chat canon, so the model recalls them when the story comes back to them.",
        'm9.chapter.events': 'What it holds:',
        'm9.chapter.keys': 'Keys: {primary} AND one of: {secondary}',
        'm9.chapter.applied': 'Added a chapter to the chronicle: {title}.',
        'm9.chapter.appliedMany.one': 'Added {count} chapter to the chronicle',
        'm9.chapter.appliedMany.few': 'Added {count} chapters to the chronicle',
        'm9.chapter.appliedMany.many': 'Added {count} chapters to the chronicle',
        'm9.merge.proposal': 'Merging chronicle chapters: {first} and {second}',
        'm9.merge.description':
            'Two small chronicle chapters tell about the same thing. I will merge them into one, «{name}», so they take less room in the canon.',
        'm9.merge.applied': 'Merged two chronicle chapters into one: «{name}».',
        'm9.merge.appliedMany.one': 'Merged chronicle chapters: {count} pair',
        'm9.merge.appliedMany.few': 'Merged chronicle chapters: {count} pairs',
        'm9.merge.appliedMany.many': 'Merged chronicle chapters: {count} pairs',
        'm9.archive.proposal.one': 'To the archive: {count} old chronicle chapter',
        'm9.archive.proposal.few': 'To the archive: {count} old chronicle chapters',
        'm9.archive.proposal.many': 'To the archive: {count} old chronicle chapters',
        'm9.archive.description':
            'Chronicle chapters take more than half of the room the canon has. I will archive the oldest: {list}. They come back when the story mentions them again.',
        'm9.archive.applied.one': 'Archived {count} old chronicle chapter: it comes back when the story mentions it.',
        'm9.archive.applied.few':
            'Archived {count} old chronicle chapters: they come back when the story mentions them.',
        'm9.archive.applied.many':
            'Archived {count} old chronicle chapters: they come back when the story mentions them.',
        'm9.remember.proposal': 'Message #{index} into long-term memory: {reason}',
        'm9.remember.description':
            "Message #{index} holds an important moment: {reason}. I will set Qvink's «remember» mark on it so it stays in the long-term memory.",
        'm9.remember.applied': 'Kept message #{index} in long-term memory: {reason}.',
        'm9.remember.appliedMany.one': 'Kept {count} important moment in long-term memory',
        'm9.remember.appliedMany.few': 'Kept {count} important moments in long-term memory',
        'm9.remember.appliedMany.many': 'Kept {count} important moments in long-term memory',
        'm9.reason.important': 'important event',
        'm9.reason.quest': 'new quest',
        'm9.reason.relationship': 'relationship turn',
        'm9.reason.oath': 'oath',
        'm9.reason.secret': 'revealed secret',
        'm9.reason.withText': '{reason} ({text})',
        'm9.chapters.title': 'Chronicle',
        'm9.chapters.hint':
            'When a remembered Qvink memory no longer fits its long-term memory, it becomes a chapter of the chat canon. A chapter fires on two keys at once (a participant AND a place, an item or another participant), so chapters about the main heroes do not fire every turn.',
        'm9.chapters.empty': 'No chapters yet: nothing has fallen out of the long-term memory.',
        'm9.chapters.waiting': 'Waiting for a chapter: {waiting}; left out (no keys): {nokeys}',
        'm9.chapter.range': 'Messages #{from}–{to}',
        'm9.chapter.chars': '{count} chars',
        'm9.chapter.archived': 'archive',
        'm9.chapter.open': 'Open',
        'm9.chapter.openHint': 'Open the chapter in the Lore Studio',
        'm9.keys.and': 'AND',
        'm9.keys.hint': 'Primary keys AND any of the secondary keys',
        'm9.keys.more': '+{count}',
        'm9.remembered.title': 'Remembered by Maestro',
        'm9.remembered.hint':
            "Important moments get Qvink's «remember» mark by themselves: a new quest, a relationship turn, a revealed secret, an oath. Undo is in the journal. A mark you set or removed yourself is left as it is.",
        'm9.remembered.empty': 'Nothing marked yet.',
        'm9.remembered.index': '#{index}',
        'm9.recap.title': 'Previously in the story…',
        'm9.recap.hint':
            'After a break the chat opens with a short reminder of what happened. It is shown once per break — not again after a reload or on another device.',
        'm9.recap.afterHours': 'After a break of (hours)',
        'm9.recap.target': 'Show',
        'm9.recap.target.user': 'only to me',
        'm9.recap.target.userAndPrompt': 'to me and in the first prompt',
        'm9.recap.target.off': 'never',
        'm9.recap.source': 'Made from',
        'm9.recap.source.memory': 'Qvink memory and the canon (free)',
        'm9.recap.source.ai': 'a background model summary',
        'm9.recap.sourceHint':
            'The model writes up to 120 words in the language of the chat; its profile is set in Settings.',
        'm9.recap.now': 'Show now',
        'm9.recap.last': 'Last recap',
        'm9.recap.close': 'Close',
        'm9.recap.openTab': 'Chronicle',
        'm9.recap.empty': 'Nothing to recap yet: no memories and no chapters.',
        'm9.recap.section.chapters': 'Chronicle:',
        'm9.recap.section.long': 'Remembered:',
        'm9.recap.section.recent': 'Lately:',
        'm9.settings.title': 'Settings',
        'm9.settings.chapters': 'Chronicle chapters',
        'm9.settings.chaptersHint': "Memories that fall out of Qvink's long-term memory become canon chapters",
        'm9.settings.maxChapterChars': 'Chapter size limit (chars)',
        'm9.settings.maxChapterCharsHint': 'Also at most a quarter of the canon budget.',
        'm9.settings.autoMemory': 'Auto-memory',
        'm9.settings.autoMemoryHint': "Maestro sets Qvink's «remember» mark on important moments",
        'm9.settings.keywords': 'Look for oaths, secrets and quests in replies',
        'm9.settings.keywordsHint': "Cheap word search in each committed reply, besides the revision's signals",
    },
    ru: {
        'm9.title': 'Летопись и автопамять',
        'm9.tab': 'Летопись',
        'm9.noChat': 'Чат не открыт.',
        'm9.profileTask': 'Летопись: «Ранее в истории…»',
        'kind.chronicle.chapter': 'Главы летописи из забытых воспоминаний',
        'kind.chronicle.merge': 'Склейка мелких глав летописи',
        'kind.chronicle.archive': 'Архив старых глав летописи',
        'kind.chronicle.remember': 'Отметки «запомнить» в Qvink',
        'target.m9.chapter': 'Глава летописи',
        'target.m9.merge': 'Склейка глав летописи',
        'target.m9.archive': 'Глава летописи',
        'target.m9.remember': 'Отметка «запомнить» в Qvink',
        'm9.field.chapter': 'Глава',
        'm9.field.keys': 'Ключи',
        'm9.field.text': 'Текст',
        'm9.field.state': 'Состояние',
        'm9.field.remember': 'Запомнить надолго',
        'm9.state.active': 'действует',
        'm9.state.archived': 'в архиве',
        'm9.warn.noQvink': 'Qvink Memory не установлен или выключен в этом чате: ни глав, ни отметок «запомнить».',
        'm9.warn.noCanon': 'Главы летописи некуда записать: выключен «Канон чата».',
        'm9.error.noCanon': 'Летопись некуда записать: выключен «Канон чата».',
        'm9.error.messageGone': 'Сообщение изменилось или удалено.',
        'm9.error.noStudio': 'Лор-студия выключена: открой книгу канона в редакторе книг лора SillyTavern.',
        'm9.chapter.comment': 'Летопись: {title} (№{from}–{to})',
        'm9.range.one': 'сообщение №{from}',
        'm9.range.many': 'сообщения №{from}–{to}',
        'm9.chapter.label': '«{name}» ({range})',
        'm9.chapter.proposal': 'Новая глава летописи: {title} ({range})',
        'm9.chapter.proposal.range': 'Новая глава летописи: {range}',
        'm9.chapter.description':
            'Воспоминания ({range}) уже не помещаются в долгую память Qvink. Сохраню их главой летописи в каноне чата — модель вспомнит о них, когда история к ним вернётся.',
        'm9.chapter.events': 'Что в ней:',
        'm9.chapter.keys': 'Ключи: {primary} И одно из: {secondary}',
        'm9.chapter.applied': 'Записал в летопись новую главу: {title}.',
        'm9.chapter.appliedMany.one': 'Записал в летопись {count} новую главу',
        'm9.chapter.appliedMany.few': 'Записал в летопись {count} новые главы',
        'm9.chapter.appliedMany.many': 'Записал в летопись {count} новых глав',
        'm9.merge.proposal': 'Склейка глав летописи: {first} и {second}',
        'm9.merge.description':
            'Две небольшие главы летописи рассказывают об одном и том же. Склею их в одну, «{name}», — так они займут меньше места в каноне.',
        'm9.merge.applied': 'Склеил две главы летописи в одну: «{name}».',
        'm9.merge.appliedMany.one': 'Склеил главы летописи: {count} пара',
        'm9.merge.appliedMany.few': 'Склеил главы летописи: {count} пары',
        'm9.merge.appliedMany.many': 'Склеил главы летописи: {count} пар',
        'm9.archive.proposal.one': 'В архив: {count} старая глава летописи',
        'm9.archive.proposal.few': 'В архив: {count} старые главы летописи',
        'm9.archive.proposal.many': 'В архив: {count} старых глав летописи',
        'm9.archive.description':
            'Главы летописи заняли больше половины места, отведённого канону. Уберу в архив самые старые: {list}. Они вернутся, когда о них снова зайдёт речь.',
        'm9.archive.applied.one': 'Убрал в архив {count} старую главу летописи: она вернётся, когда о ней зайдёт речь.',
        'm9.archive.applied.few': 'Убрал в архив {count} старые главы летописи: они вернутся, когда о них зайдёт речь.',
        'm9.archive.applied.many': 'Убрал в архив {count} старых глав летописи: они вернутся, когда о них зайдёт речь.',
        'm9.remember.proposal': 'Сообщение №{index} — в долгую память: {reason}',
        'm9.remember.description':
            'В сообщении №{index} важный момент: {reason}. Поставлю на нём отметку «запомнить» в Qvink — тогда он останется в долгой памяти.',
        'm9.remember.applied': 'Запомнил надолго сообщение №{index}: {reason}.',
        'm9.remember.appliedMany.one': 'Запомнил надолго {count} важный момент',
        'm9.remember.appliedMany.few': 'Запомнил надолго {count} важных момента',
        'm9.remember.appliedMany.many': 'Запомнил надолго {count} важных моментов',
        'm9.reason.important': 'важное событие',
        'm9.reason.quest': 'новый квест',
        'm9.reason.relationship': 'перелом в отношениях',
        'm9.reason.oath': 'клятва',
        'm9.reason.secret': 'раскрытый секрет',
        'm9.reason.withText': '{reason} ({text})',
        'm9.chapters.title': 'Летопись',
        'm9.chapters.hint':
            'Когда отмеченное воспоминание Qvink перестаёт помещаться в его долгую память, оно становится главой канона чата. Глава срабатывает только по двум ключам сразу (участник И место, предмет или второй участник), поэтому главы о главных героях не лезут в каждый ход.',
        'm9.chapters.empty': 'Глав пока нет: из долгой памяти ещё ничего не выпало.',
        'm9.chapters.waiting': 'Ждут главы: {waiting}; пропущено (не нашлось ключей): {nokeys}',
        'm9.chapter.range': 'Сообщения №{from}–{to}',
        'm9.chapter.chars': '{count} симв.',
        'm9.chapter.archived': 'архив',
        'm9.chapter.open': 'Открыть',
        'm9.chapter.openHint': 'Открыть главу в Лор-студии',
        'm9.keys.and': 'И',
        'm9.keys.hint': 'Основные ключи И любой из дополнительных',
        'm9.keys.more': 'ещё {count}',
        'm9.remembered.title': 'Запомнил Maestro',
        'm9.remembered.hint':
            'Важные моменты сами получают отметку «запомнить» в Qvink: новый квест, перелом в отношениях, раскрытый секрет, клятва. Отменить можно в журнале. Отметки, которые ты поставил или снял сам, Maestro не трогает.',
        'm9.remembered.empty': 'Пока ничего не отмечено.',
        'm9.remembered.index': '№{index}',
        'm9.recap.title': 'Ранее в истории…',
        'm9.recap.hint':
            'После перерыва чат открывается коротким напоминанием о том, что было. Показывается один раз за перерыв — не повторяется ни после перезагрузки, ни на другом устройстве.',
        'm9.recap.afterHours': 'После перерыва дольше (часов)',
        'm9.recap.target': 'Показывать',
        'm9.recap.target.user': 'только мне',
        'm9.recap.target.userAndPrompt': 'мне и в промпт первого хода',
        'm9.recap.target.off': 'никогда',
        'm9.recap.source': 'Из чего',
        'm9.recap.source.memory': 'память Qvink и канон (бесплатно)',
        'm9.recap.source.ai': 'пересказ фоновой моделью',
        'm9.recap.sourceHint': 'Модель пишет до 120 слов на языке чата; её профиль выбирается в настройках.',
        'm9.recap.now': 'Показать сейчас',
        'm9.recap.last': 'Последний пересказ',
        'm9.recap.close': 'Закрыть',
        'm9.recap.openTab': 'Летопись',
        'm9.recap.empty': 'Пересказывать пока нечего: нет ни воспоминаний, ни глав.',
        'm9.recap.section.chapters': 'Летопись:',
        'm9.recap.section.long': 'Запомнилось:',
        'm9.recap.section.recent': 'Недавно:',
        'm9.settings.title': 'Настройки',
        'm9.settings.chapters': 'Главы летописи',
        'm9.settings.chaptersHint': 'Воспоминания, выпавшие из долгой памяти Qvink, становятся главами канона',
        'm9.settings.maxChapterChars': 'Предел размера главы (символов)',
        'm9.settings.maxChapterCharsHint': 'И не больше четверти бюджета канона.',
        'm9.settings.autoMemory': 'Автопамять',
        'm9.settings.autoMemoryHint': 'Maestro сам ставит отметку «запомнить» в Qvink на важных моментах',
        'm9.settings.keywords': 'Искать в ответах клятвы, секреты и квесты',
        'm9.settings.keywordsHint':
            'Дешёвый поиск по словам в каждом зафиксированном ответе, вдобавок к сигналам ревизии',
    },
};
