// Strings of S4 «Сигналы» (`s4.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const SIGNALS_STRINGS: I18nParts = {
    en: {
        's4.title': 'Signals',
        's4.tab': 'Signals',
        's4.hint':
            'What changed in the story, noticed without AI when you send your next message: the DES tracker and Qvink memory of the reply are compared with the turn before, plus new DES aliases and new names. Free-text values count only when they hold two turns in a row, so swiped replies and one-turn slips leave nothing behind. The revision takes these signals to update the canon.',
        's4.noChat': 'No chat is open.',
        's4.loading': 'Loading…',
        's4.notLeader': 'Another tab of this chat compares the turns; this one only shows them.',
        's4.stats': 'Waiting for the revision: {count} · replies since the last revision: {since}',
        's4.pending': 'Waiting for the revision',
        's4.pending.empty': 'No new signals.',
        's4.last': 'Last turn (message #{index})',
        's4.last.none': 'No turn has been compared yet.',
        's4.last.empty': 'Nothing changed in this turn.',
        's4.last.folded': 'Folded: {count}',
        's4.late': 'added later',
        's4.jump': 'Go to message #{index}',
        's4.folded': '×{count}',
        's4.kind.relationship.changed': 'Relationship changed',
        's4.kind.appearance.changed': 'Appearance changed',
        's4.kind.location.changed': 'New place',
        's4.kind.time.skipped': 'Time skip',
        's4.kind.scene.ended': 'Scene ended',
        's4.kind.quest.added': 'New quest',
        's4.kind.quest.removed': 'Quest gone',
        's4.kind.character.appeared': 'Character appeared',
        's4.kind.character.left': 'Character left',
        's4.kind.alias.added': 'New DES alias',
        's4.kind.memory.long': 'Long-term memory',
        's4.kind.memory.added': 'Qvink memory',
        's4.kind.name.new': 'New name',
        's4.kind.fact.new': 'New fact',
        's4.text.change': '{name}: {from} → {to}',
        's4.text.appearance': '{name}: {fields}',
        's4.text.move': '{from} → {to}',
        's4.text.hours': '{from} → {to} (≈ {hours} h)',
        's4.text.scene': 'because of {reasons}',
        's4.reason.location': 'a new place',
        's4.reason.time': 'a time skip',
        's4.text.main': '{title} (main)',
        's4.text.first': '{name} (first time)',
        's4.text.aliases': '{name}: {aliases}',
        's4.text.memory': 'messages {indices}',
        's4.aspect.appearance': 'appearance',
        's4.aspect.outfit': 'outfit',
        's4.none': '—',
    },
    ru: {
        's4.title': 'Сигналы',
        's4.tab': 'Сигналы',
        's4.hint':
            'Что изменилось в истории — замечено без ИИ, когда ты отправляешь следующее сообщение: трекер DES и память Qvink ответа сравниваются с прошлым ходом, плюс новые алиасы DES и новые имена. Свободный текст засчитывается, только если продержался два хода подряд, поэтому свайпы и случайные оговорки ничего не оставляют. Эти сигналы забирает ревизия и по ним обновляет канон.',
        's4.noChat': 'Чат не открыт.',
        's4.loading': 'Загрузка…',
        's4.notLeader': 'Ходы этого чата сравнивает другая вкладка, здесь они только показываются.',
        's4.stats': 'Ждут ревизии: {count} · ответов с прошлой ревизии: {since}',
        's4.pending': 'Ждут ревизии',
        's4.pending.empty': 'Новых сигналов нет.',
        's4.last': 'Последний ход (сообщение #{index})',
        's4.last.none': 'Ни один ход ещё не сравнивался.',
        's4.last.empty': 'В этом ходе ничего не изменилось.',
        's4.last.folded': 'Свёрнуто: {count}',
        's4.late': 'добавлено позже',
        's4.jump': 'К сообщению #{index}',
        's4.folded': '×{count}',
        's4.kind.relationship.changed': 'Отношение изменилось',
        's4.kind.appearance.changed': 'Внешность изменилась',
        's4.kind.location.changed': 'Новое место',
        's4.kind.time.skipped': 'Пропуск времени',
        's4.kind.scene.ended': 'Сцена закончилась',
        's4.kind.quest.added': 'Новый квест',
        's4.kind.quest.removed': 'Квест исчез',
        's4.kind.character.appeared': 'Персонаж появился',
        's4.kind.character.left': 'Персонаж ушёл',
        's4.kind.alias.added': 'Новый алиас DES',
        's4.kind.memory.long': 'Долгая память',
        's4.kind.memory.added': 'Память Qvink',
        's4.kind.name.new': 'Новое имя',
        's4.kind.fact.new': 'Новый факт',
        's4.text.change': '{name}: {from} → {to}',
        's4.text.appearance': '{name}: {fields}',
        's4.text.move': '{from} → {to}',
        's4.text.hours': '{from} → {to} (≈ {hours} ч)',
        's4.text.scene': 'причина: {reasons}',
        's4.reason.location': 'смена места',
        's4.reason.time': 'пропуск времени',
        's4.text.main': '{title} (главный)',
        's4.text.first': '{name} (впервые)',
        's4.text.aliases': '{name}: {aliases}',
        's4.text.memory': 'сообщения {indices}',
        's4.aspect.appearance': 'внешность',
        's4.aspect.outfit': 'наряд',
        's4.none': '—',
    },
};
