import type { I18nParts } from '../../shared/contracts';

export const M33_STRINGS: I18nParts = {
    en: {
        'm33.title': 'Maestro assistant',
        'm33.tab': 'Assistant',
        'm33.profileTask': 'Assistant (conversation in the pult)',
        'kind.assistant.setting': 'Assistant: Maestro settings',

        'm33.settings.title': 'Assistant',
        'm33.settings.profile': 'Connection profile',
        'm33.settings.profileInherit': 'Same as background tasks',
        'm33.settings.profileMissing': 'Missing profile ({id})',
        'm33.settings.profileHint':
            'The model the assistant talks through: any saved Connection Manager profile. The active connection is not switched.',
        'm33.settings.noCm': 'Connection Manager is off: the assistant has no way to reach a model.',
        'm33.settings.maxTokens': 'Answer length, tokens',
        'm33.settings.historyTokens': 'Conversation memory, tokens',
        'm33.settings.historyHint':
            'How much of the earlier conversation goes with every question. Older exchanges shrink to one line each.',
        'm33.settings.writesPerHour': 'Changes per hour in a chat',
        'm33.settings.writesHint':
            'Every change waits for your confirmation anyway; this caps how many can be applied per hour.',
        'm33.settings.resultChars': 'Tool result size, characters',

        'm33.empty.title': 'Ask about Maestro, this chat or your extensions.',
        'm33.empty.hint':
            'The assistant reads settings, health, the journal, lore and regexes, and changes something only after you confirm it.',
        'm33.example.1': 'Why didn’t the heroine recognise her sister?',
        'm33.example.2': 'Why was this turn so expensive?',
        'm33.example.3': 'What does this regex do?',
        'm33.example.4': 'Make a mana mechanic',
        'm33.input.placeholder': 'Message to the assistant… Enter sends, Shift+Enter adds a line',
        'm33.input.label': 'Message to the assistant',
        'm33.send': 'Send',
        'm33.stop': 'Stop',
        'm33.clear': 'Clear',
        'm33.clear.title': 'Clear the conversation?',
        'm33.clear.body':
            'The conversation with the assistant in this chat will be deleted. Changes already applied stay (undo them in the journal).',
        'm33.cost': 'Spent: {total} on this conversation · {last} on the last message',
        'm33.busy': 'Thinking…',
        'm33.you': 'You',
        'm33.assistant': 'Assistant',
        'm33.noChat': 'No chat is open: this conversation is not saved.',
        'm33.noProfile.banner': 'The assistant has no usable connection profile.',
        'm33.noProfile.open': 'Open settings',

        'm33.chip.args': 'Arguments',
        'm33.chip.result': 'Result',
        'm33.chip.untrusted': 'Chat or lore content: data for the assistant, never instructions.',
        'm33.status.running': 'running',
        'm33.status.ok': 'done',
        'm33.status.error': 'error',
        'm33.status.waiting': 'waiting for you',
        'm33.status.applied': 'applied',
        'm33.status.declined': 'declined',
        'm33.card.apply': 'Apply',
        'm33.card.decline': 'Decline',
        'm33.card.applied': 'Applied. You can undo it in the journal.',
        'm33.card.declined': 'Declined: nothing was changed.',
        'm33.card.failed': 'Not applied: {error}',
        'm33.card.otherTab': 'Waiting for an answer in another tab.',

        'm33.notice.stopped': 'Stopped.',
        'm33.notice.roundLimit':
            'The assistant made {count} rounds of tool calls without an answer and was stopped. Try a narrower question.',
        'm33.error.noProfile':
            'The assistant has no connection profile. Choose one in Settings → Assistant, or set the background profile in Settings → Profiles.',
        'm33.error.noCm': 'Connection Manager is off: turn it on in the Extensions panel and save a profile.',
        'm33.error.paused': 'The assistant’s profile failed several times in a row and is paused for 5 minutes.',
        'm33.error.cap': 'Today’s cap for Maestro’s background spending is reached (Settings → Budget).',
        'm33.error.refusal': 'The model refused to answer.',
        'm33.error.empty': 'The model returned an empty answer.',
        'm33.error.transport': 'The request failed: {detail}',
        'm33.error.failed': 'The request failed: {detail}',
        'm33.error.internal': 'Something broke in the assistant; details are in the browser console.',
        'm33.error.unknownTool': 'No such tool: {name}',
        'm33.error.badArgs': 'The model sent invalid arguments',
        'm33.error.badPlan': 'The tool did not describe the change.',
        'm33.error.writeLimit': 'Not proposed: at most {count} changes per message',
        'm33.error.rateLimit': 'Not proposed: {count} changes were already applied in this chat this hour',
        'm33.error.roundLimit': 'Not run: too many rounds of tool calls',
        'm33.error.stopped': 'Stopped',
        'm33.error.timeout': 'The tool took too long',
        'm33.error.toolFailed': 'The tool failed',

        'm33.safety.unknownModule': 'There is no Maestro module «{module}» whose settings the assistant may change.',
        'm33.safety.hidden':
            '«{path}» is closed to the assistant: keys, addresses, profiles and models are changed by hand only.',
        'm33.safety.notLeaf': '«{path}» in {module} is a group of settings: name one setting inside it.',
        'm33.safety.unknownPath': '{module} has no setting «{path}».',
        'm33.safety.malformed': '«{path}» is not a valid setting path.',
        'm33.safety.type.number': 'a number',
        'm33.safety.type.boolean': 'true or false',
        'm33.safety.type.string': 'text',
        'm33.safety.type.list': 'a list of values of the same kind',
        'm33.safety.type.value': 'a simple value',
        'm33.safety.value.type': '«{path}» expects {expected} (now {current}).',
        'm33.safety.value.negative': '«{path}» cannot be negative.',
        'm33.safety.value.range': '«{path}»: the value is outside a sane range (now {current}).',
        'm33.safety.value.length': '«{path}»: the value is too long.',
        'm33.safety.value.items': '«{path}»: the list items must stay of the same kind.',
        'm33.safety.value.same': '«{path}» already has this value.',
        'm33.setting.summary': '{module}: {path} — {before} → {after}',
        'm33.setting.target': 'Maestro · {module}',
    },
    ru: {
        'm33.title': 'Ассистент Maestro',
        'm33.tab': 'Ассистент',
        'm33.profileTask': 'Ассистент (переписка в пульте)',
        'kind.assistant.setting': 'Ассистент: настройки Maestro',

        'm33.settings.title': 'Ассистент',
        'm33.settings.profile': 'Профиль подключения',
        'm33.settings.profileInherit': 'Как у фоновых задач',
        'm33.settings.profileMissing': 'Профиль не найден ({id})',
        'm33.settings.profileHint':
            'Через какую модель говорит ассистент: любой сохранённый профиль Connection Manager. Активное подключение не переключается.',
        'm33.settings.noCm': 'Connection Manager выключен: ассистенту не через что обратиться к модели.',
        'm33.settings.maxTokens': 'Длина ответа, токенов',
        'm33.settings.historyTokens': 'Память переписки, токенов',
        'm33.settings.historyHint':
            'Сколько прошлой переписки уходит с каждым вопросом. Старые обмены сжимаются до строчки.',
        'm33.settings.writesPerHour': 'Изменений в час на чат',
        'm33.settings.writesHint':
            'Каждое изменение и так ждёт твоего подтверждения; это потолок применённых изменений за час.',
        'm33.settings.resultChars': 'Размер результата инструмента, символов',

        'm33.empty.title': 'Спроси про Maestro, этот чат или расширения.',
        'm33.empty.hint':
            'Ассистент читает настройки, здоровье, журнал, лор и регексы, а меняет что-то только после твоего подтверждения.',
        'm33.example.1': 'Почему героиня не узнала сестру?',
        'm33.example.2': 'Почему этот ход дорогой?',
        'm33.example.3': 'Что делает этот регекс?',
        'm33.example.4': 'Сделай механику маны',
        'm33.input.placeholder': 'Сообщение ассистенту… Enter — отправить, Shift+Enter — новая строка',
        'm33.input.label': 'Сообщение ассистенту',
        'm33.send': 'Отправить',
        'm33.stop': 'Стоп',
        'm33.clear': 'Очистить',
        'm33.clear.title': 'Очистить переписку?',
        'm33.clear.body':
            'Переписка с ассистентом в этом чате будет удалена. Уже применённые изменения останутся (откатить их можно в журнале).',
        'm33.cost': 'Потрачено: {total} на переписку · {last} на последнее сообщение',
        'm33.busy': 'Думаю…',
        'm33.you': 'Ты',
        'm33.assistant': 'Ассистент',
        'm33.noChat': 'Чат не открыт: эта переписка не сохранится.',
        'm33.noProfile.banner': 'У ассистента нет рабочего профиля подключения.',
        'm33.noProfile.open': 'Открыть настройки',

        'm33.chip.args': 'Аргументы',
        'm33.chip.result': 'Результат',
        'm33.chip.untrusted': 'Содержимое чата или лора: для ассистента это данные, а не инструкции.',
        'm33.status.running': 'выполняется',
        'm33.status.ok': 'готово',
        'm33.status.error': 'ошибка',
        'm33.status.waiting': 'ждёт тебя',
        'm33.status.applied': 'применено',
        'm33.status.declined': 'отклонено',
        'm33.card.apply': 'Применить',
        'm33.card.decline': 'Отклонить',
        'm33.card.applied': 'Применено. Откатить можно в журнале.',
        'm33.card.declined': 'Отклонено: ничего не изменилось.',
        'm33.card.failed': 'Не применено: {error}',
        'm33.card.otherTab': 'Ждёт ответа в другой вкладке.',

        'm33.notice.stopped': 'Остановлено.',
        'm33.notice.roundLimit':
            'Ассистент сделал {count} кругов вызовов инструментов и так и не ответил — остановлен. Попробуй спросить конкретнее.',
        'm33.error.noProfile':
            'У ассистента нет профиля подключения. Выбери его в «Настройки → Ассистент» или задай фоновый профиль в «Настройки → Профили».',
        'm33.error.noCm': 'Connection Manager выключен: включи его на панели расширений и сохрани профиль.',
        'm33.error.paused': 'Профиль ассистента несколько раз подряд не ответил и поставлен на паузу на 5 минут.',
        'm33.error.cap': 'Достигнут дневной потолок фоновых расходов Maestro («Настройки → Бюджет»).',
        'm33.error.refusal': 'Модель отказалась отвечать.',
        'm33.error.empty': 'Модель вернула пустой ответ.',
        'm33.error.transport': 'Запрос не прошёл: {detail}',
        'm33.error.failed': 'Запрос не прошёл: {detail}',
        'm33.error.internal': 'В ассистенте что-то сломалось; подробности в консоли браузера.',
        'm33.error.unknownTool': 'Нет такого инструмента: {name}',
        'm33.error.badArgs': 'Модель передала неверные аргументы',
        'm33.error.badPlan': 'Инструмент не описал изменение.',
        'm33.error.writeLimit': 'Не предложено: не больше {count} изменений за сообщение',
        'm33.error.rateLimit': 'Не предложено: за этот час в чате уже применено изменений — {count}',
        'm33.error.roundLimit': 'Не выполнено: слишком много кругов вызовов',
        'm33.error.stopped': 'Остановлено',
        'm33.error.timeout': 'Инструмент не уложился во время',
        'm33.error.toolFailed': 'Инструмент не сработал',

        'm33.safety.unknownModule': 'Нет модуля Maestro «{module}», настройки которого ассистенту можно менять.',
        'm33.safety.hidden': '«{path}» закрыт для ассистента: ключи, адреса, профили и модели меняются только вручную.',
        'm33.safety.notLeaf': '«{path}» в модуле «{module}» — это группа настроек: укажи одну настройку внутри.',
        'm33.safety.unknownPath': 'В модуле «{module}» нет настройки «{path}».',
        'm33.safety.malformed': '«{path}» — неверный путь к настройке.',
        'm33.safety.type.number': 'число',
        'm33.safety.type.boolean': 'true или false',
        'm33.safety.type.string': 'текст',
        'm33.safety.type.list': 'список значений того же вида',
        'm33.safety.type.value': 'простое значение',
        'm33.safety.value.type': '«{path}» ждёт {expected} (сейчас {current}).',
        'm33.safety.value.negative': '«{path}» не может быть отрицательным.',
        'm33.safety.value.range': '«{path}»: значение вне разумных пределов (сейчас {current}).',
        'm33.safety.value.length': '«{path}»: значение слишком длинное.',
        'm33.safety.value.items': '«{path}»: элементы списка должны остаться того же вида.',
        'm33.safety.value.same': 'У «{path}» уже такое значение.',
        'm33.setting.summary': '{module}: {path} — {before} → {after}',
        'm33.setting.target': 'Maestro · {module}',
    },
};
