// Strings of M24 «Места» (`m24.*`). Russian is the primary UI language; the user is addressed as «ты».
import type { I18nParts } from '../../shared/contracts';

export const PLACES_STRINGS: I18nParts = {
    en: {
        'm24.title': 'Places',
        'm24.tab': 'Places',
        'kind.places.merge': 'Merging places',
        'kind.places.create': 'New places',
        'kind.places.update': 'Place edits',
        'kind.places.remove': 'Removing places',
        'kind.places.alias': 'Other names of places',
        'target.places.place': 'Place',
        'target.places.current': 'Where the scene is',
        'm24.field.name': 'Name',
        'm24.field.aliases': 'Other names',
        'm24.field.parent': 'Part of',
        'm24.field.technical': 'Technical data',
        'm24.hint':
            'Places come from the location DES writes into its tracker. A new name becomes a place once it holds for two turns in a row; a name that looks like a known place waits for your decision in the Inbox. Swiping or deleting a reply takes back what it changed here.',
        'm24.noChat': 'No chat is open.',
        'm24.now': 'Now: {path}',
        'm24.now.unknown': 'The current place is unknown.',
        'm24.add.name': 'New place',
        'm24.add.placeholder': 'Name of a place',
        'm24.add.action': 'Add',
        'm24.places': 'Places ({count})',
        'm24.empty': 'No places yet: they appear as the story moves.',
        'm24.here': 'here',
        'm24.described': 'described',
        'm24.lastSeen': 'last seen: message #{at}',
        'm24.notSeen': 'not visited yet',
        'm24.name': 'Name',
        'm24.rename': 'Rename',
        'm24.aliases': 'Other names',
        'm24.aliases.none': 'No other names.',
        'm24.alias.add': 'Add a name',
        'm24.alias.placeholder': 'Another name',
        'm24.alias.remove': 'Remove «{alias}»',
        'm24.forms': 'Case forms: {forms}',
        'm24.parent': 'Part of',
        'm24.parent.none': '— top level —',
        'm24.inside': 'Inside: {names}',
        'm24.merge.into': 'Merge into another place',
        'm24.merge.pick': '— choose a place —',
        'm24.merge.action': 'Merge',
        'm24.merge.confirmTitle': 'Merge the places?',
        'm24.merge.confirmBody':
            '«{from}» becomes another name of «{to}»: its visits, inner places and description move over. You can undo it from the journal.',
        'm24.entry.action': 'Description',
        'm24.entry.hint': 'Open the description entry of this place (made in the chat canon when there is none)',
        'm24.entry.ready': 'The description is entry #{uid} of the lorebook «{book}».',
        'm24.remove': 'Remove',
        'm24.remove.title': 'Remove the place?',
        'm24.remove.body':
            '«{name}» leaves the registry; the places inside it move one level up. You can undo it from the journal.',
        'm24.visits': 'Visits ({count})',
        'm24.visits.none': 'No visits recorded yet.',
        'm24.visits.more': 'Earlier visits: {count}',
        'm24.visit.now': 'Since message #{from}, now',
        'm24.visit.one': 'Message #{at}',
        'm24.visit.range': 'Messages #{from}–#{to}',
        'm24.visit.present': 'There: {names}',
        'm24.candidates': 'New names ({count})',
        'm24.candidates.hint':
            'Locations DES named that are not places yet. Create a place now, tie the name to a known place, or tell Maestro it is not a place.',
        'm24.candidate.seen': 'seen {count}×',
        'm24.candidate.inbox': 'in the Inbox',
        'm24.candidate.label': 'DES: {label}',
        'm24.candidate.in': 'Inside: {place}',
        'm24.candidate.similar': 'Looks like: {places}',
        'm24.candidate.create': 'Create a place',
        'm24.candidate.pick': 'Known place',
        'm24.candidate.same': 'It is this place',
        'm24.candidate.dismiss': 'Not a place',
        'm24.candidate.dismissHint': 'Forget this name in this chat; DES writing it again will not bring it back',
        'm24.merge.title': '«{name}» may be «{place}»',
        'm24.merge.description':
            'For two turns in a row the scene was at «{label}», which looks like the known place {place}. Accept and «{name}» becomes another name of it; reject and it becomes a place of its own.',
        'm24.merge.others': 'Also similar: {places}.',
        'm24.merge.details': 'DES tracker location: {label}',
        'm24.merge.applied': 'Noted: «{name}» is another name of «{place}».',
        'm24.journal.create': 'New place: «{name}»',
        'm24.journal.rename': 'The place «{from}» is now called «{to}»',
        'm24.journal.update': 'Place «{name}» changed',
        'm24.journal.merge': 'The place «{from}» merged into «{to}»',
        'm24.journal.remove': 'Place «{name}» removed',
        'm24.journal.alias': '«{alias}» is another name of the place «{name}»',
        'm24.error.missing': 'This place (or name) is gone.',
        'm24.error.empty-name': 'A place needs a name.',
        'm24.error.bad-parent': 'The chosen place cannot contain this one: it is the place itself or lies inside it.',
        'm24.error.same': 'A place cannot be merged into itself.',
        'm24.error.save': 'The places could not be saved. Try again.',
        'm24.error.noCanon': 'The description has nowhere to go: the «Chat canon» module is off.',
        'm24.error.noChat': 'No chat is open.',
    },
    ru: {
        'm24.title': 'Места',
        'm24.tab': 'Места',
        'kind.places.merge': 'Объединение мест',
        'kind.places.create': 'Новые места',
        'kind.places.update': 'Правка мест',
        'kind.places.remove': 'Удаление мест',
        'kind.places.alias': 'Другие названия мест',
        'target.places.place': 'Место',
        'target.places.current': 'Где идёт сцена',
        'm24.field.name': 'Название',
        'm24.field.aliases': 'Другие названия',
        'm24.field.parent': 'Входит в',
        'm24.field.technical': 'Служебные данные',
        'm24.hint':
            'Места берутся из локации, которую DES пишет в трекер. Новое название становится местом, если продержалось два хода подряд; название, похожее на уже известное место, ждёт твоего решения во «Входящих». Свайп или удаление ответа отменяет всё, что он здесь изменил.',
        'm24.noChat': 'Чат не открыт.',
        'm24.now': 'Сейчас: {path}',
        'm24.now.unknown': 'Где сейчас — неизвестно.',
        'm24.add.name': 'Новое место',
        'm24.add.placeholder': 'Название места',
        'm24.add.action': 'Добавить',
        'm24.places': 'Места ({count})',
        'm24.empty': 'Мест пока нет — они появятся по ходу истории.',
        'm24.here': 'здесь',
        'm24.described': 'есть описание',
        'm24.lastSeen': 'последний раз: сообщение #{at}',
        'm24.notSeen': 'здесь ещё не были',
        'm24.name': 'Название',
        'm24.rename': 'Переименовать',
        'm24.aliases': 'Другие названия',
        'm24.aliases.none': 'Других названий нет.',
        'm24.alias.add': 'Добавить название',
        'm24.alias.placeholder': 'Другое название',
        'm24.alias.remove': 'Убрать «{alias}»',
        'm24.forms': 'Падежные формы: {forms}',
        'm24.parent': 'Входит в',
        'm24.parent.none': '— верхний уровень —',
        'm24.inside': 'Внутри: {names}',
        'm24.merge.into': 'Слить с другим местом',
        'm24.merge.pick': '— выбери место —',
        'm24.merge.action': 'Слить',
        'm24.merge.confirmTitle': 'Слить места?',
        'm24.merge.confirmBody':
            '«{from}» станет другим названием «{to}»: визиты, вложенные места и описание перейдут к нему. Отменить можно в журнале.',
        'm24.entry.action': 'Описание',
        'm24.entry.hint': 'Открыть запись с описанием места (если её нет, она появится в каноне чата)',
        'm24.entry.ready': 'Описание места — запись №{uid} в книге лора «{book}».',
        'm24.remove': 'Удалить',
        'm24.remove.title': 'Удалить место?',
        'm24.remove.body':
            '«{name}» уйдёт из реестра, вложенные места поднимутся на уровень выше. Отменить можно в журнале.',
        'm24.visits': 'Визиты ({count})',
        'm24.visits.none': 'Визитов пока нет.',
        'm24.visits.more': 'Более ранних визитов: {count}',
        'm24.visit.now': 'С сообщения #{from} и по сей момент',
        'm24.visit.one': 'Сообщение #{at}',
        'm24.visit.range': 'Сообщения #{from}–#{to}',
        'm24.visit.present': 'Были здесь: {names}',
        'm24.candidates': 'Новые названия ({count})',
        'm24.candidates.hint':
            'Локации, которые назвал DES, но которых ещё нет среди мест. Создай место сразу, привяжи название к известному месту или скажи Maestro, что это не место.',
        'm24.candidate.seen': 'встречалось: {count}',
        'm24.candidate.inbox': 'во «Входящих»',
        'm24.candidate.label': 'DES: {label}',
        'm24.candidate.in': 'Внутри: {place}',
        'm24.candidate.similar': 'Похоже на: {places}',
        'm24.candidate.create': 'Создать место',
        'm24.candidate.pick': 'Известное место',
        'm24.candidate.same': 'Это то же место',
        'm24.candidate.dismiss': 'Не место',
        'm24.candidate.dismissHint': 'Забыть это название в этом чате: если DES напишет его снова, оно не вернётся',
        'm24.merge.title': '«{name}» — это «{place}»?',
        'm24.merge.description':
            'Два хода подряд сцена шла в «{label}» — похоже, это известное место {place}. Согласишься — «{name}» станет его другим названием; откажешься — появится отдельное место.',
        'm24.merge.others': 'Похожи также: {places}.',
        'm24.merge.details': 'Локация в трекере DES: {label}',
        'm24.merge.applied': 'Запомнил: «{name}» — другое название места «{place}».',
        'm24.journal.create': 'Новое место: «{name}»',
        'm24.journal.rename': 'Место «{from}» теперь называется «{to}»',
        'm24.journal.update': 'Изменено место «{name}»',
        'm24.journal.merge': 'Место «{from}» объединено с «{to}»',
        'm24.journal.remove': 'Удалено место «{name}»',
        'm24.journal.alias': '«{alias}» — другое название места «{name}»',
        'm24.error.missing': 'Этого места (или названия) больше нет.',
        'm24.error.empty-name': 'У места должно быть название.',
        'm24.error.bad-parent': 'Выбранное место не может содержать это: это оно само или место внутри него.',
        'm24.error.same': 'Место нельзя слить с самим собой.',
        'm24.error.save': 'Не удалось сохранить места. Попробуй ещё раз.',
        'm24.error.noCanon': 'Описание места некуда записать: выключен «Канон чата».',
        'm24.error.noChat': 'Чат не открыт.',
    },
};
