import { describe, expect, it } from 'vitest';
import {
    archiveBlocks,
    findArchiveIssues,
    findWrapperCollisions,
    isArchive,
    placeholderTags,
} from '../../src/domain/doctor-ck';
import type { BunnyBookKind } from '../../src/domain/doctor-types';
import { archive, entry } from '../helpers/doctor-entries';

const bunny = new Map<string, BunnyBookKind>([
    ['BunnyMo', 'core'],
    ['CarrotCast Limited', 'pack'],
]);

describe('archive helpers', () => {
    it('finds blocks in any case and placeholder tags of the first block', () => {
        expect(archiveBlocks('<BunnymoTags>a</BunnymoTags><BUNNYMOTAGS>b</BUNNYMOTAGS>')).toEqual([
            'BunnymoTags',
            'BUNNYMOTAGS',
        ]);
        expect(
            placeholderTags('<BunnymoTags><Name:NAME>, <GENRE:BLANK>, <Dere:NEW>, <LING:NONE></BunnymoTags>'),
        ).toEqual(['<GENRE:BLANK>', '<Dere:NEW>']);
        expect(placeholderTags('no block')).toEqual([]);
        expect(isArchive(entry('A', archive('Анна')))).toBe(true);
        expect(isArchive(entry('A', { ...archive('Анна'), disable: true }))).toBe(false);
        expect(isArchive(entry('A', { content: '<BunnymoTags><Name:NAME></BunnymoTags>' }))).toBe(false);
    });
});

describe('findArchiveIssues', () => {
    it('reports scan depth 1, several blocks, wrong spelling and placeholders', () => {
        const entries = [
            entry('Архив', archive('Анна')),
            entry('Архив', archive('Боря', { scanDepth: null }, '<BunnyMoTags><Name:Боря2></BunnyMoTags>')),
            entry('Архив', {
                ...archive('Вера', { scanDepth: 2 }),
                content: '<bunnymotags><Name:Вера>, <GENRE:BLANK></bunnymotags>',
            }),
            entry('BunnyMo', archive('Example')),
            entry('Лор', { key: ['таверна'], content: 'A tavern.' }),
        ];
        const issues = findArchiveIssues(entries, { ckPresent: false, repoBooks: [], bunnyBooks: bunny });
        expect(issues.map((issue) => [issue.kind, issue.params?.entry])).toEqual([
            ['ck.archiveScanDepth', 'Анна Character Archive - Generated by Baby Bunny Mode'],
            ['ck.archiveMultiBlock', 'Боря Character Archive - Generated by Baby Bunny Mode'],
            ['ck.archiveTagCase', 'Боря Character Archive - Generated by Baby Bunny Mode'],
            ['ck.archiveTagCase', 'Вера Character Archive - Generated by Baby Bunny Mode'],
            ['ck.archivePlaceholder', 'Вера Character Archive - Generated by Baby Bunny Mode'],
        ]);
        expect(issues[1]?.params?.count).toBe(2);
        expect(issues[2]?.params?.found).toBe('<BunnyMoTags>');
        expect(issues[4]?.params?.tags).toBe('<GENRE:BLANK>');
        expect(issues.every((issue) => issue.fileFix === true)).toBe(true);
    });

    it('reports archive books CK does not scan, only when CK is present', () => {
        const entries = [
            entry('Архив', archive('Анна', { scanDepth: null })),
            entry('Repo', archive('Боря', { scanDepth: null })),
        ];
        const issues = findArchiveIssues(entries, { ckPresent: true, repoBooks: ['Repo'], bunnyBooks: bunny });
        expect(issues).toEqual([
            expect.objectContaining({
                kind: 'ck.archiveNotRepo',
                params: expect.objectContaining({ book: 'Архив', count: 1 }),
                fileFix: false,
            }),
        ]);
        expect(findArchiveIssues(entries, { ckPresent: false, repoBooks: [], bunnyBooks: bunny })).toEqual([]);
    });
});

describe('findWrapperCollisions', () => {
    const options = { recursive: true, caseSensitiveGlobal: false, wholeWordsGlobal: false };
    const erotic = entry('CarrotCast Limited', { key: ['<NSFW>'], comment: 'Erotic', content: 'erotic genre' });

    it('groups archives whose <NSFW> wrapper fires the bare-tag entry', () => {
        const entries = [
            erotic,
            entry('Архив', archive('Анна', {}, '<NSFW>secret</NSFW>')),
            entry('Архив', archive('Боря', {}, '<nsfw>x</nsfw>')),
            entry('Архив', archive('Вера', { preventRecursion: true }, '<NSFW>x</NSFW>')),
            entry('Архив', archive('Галя', {}, 'mentions <DERE> once')),
            entry('Dere', { key: ['<DERE>'], comment: 'Deredere', content: 'sweet' }),
            entry('MBTI', { key: ['<ESFP-H>'], content: 'mbti' }),
            entry('Off', { key: ['<NSFW>'], content: 'off', disable: true }),
        ];
        const issues = findWrapperCollisions(entries, options);
        expect(issues).toHaveLength(2);
        expect(issues[0]).toMatchObject({
            kind: 'wrapper.collision',
            severity: 'warn',
            messageKey: 'm5.f.wrapperCollision',
            params: { tag: '<NSFW>', closing: '</NSFW>', count: 2, target: 'Erotic', targetBook: 'CarrotCast Limited' },
        });
        expect(issues[1]).toMatchObject({
            severity: 'info',
            messageKey: 'm5.f.bareTagCollision',
            params: { tag: '<DERE>', count: 1, target: 'Deredere' },
        });
    });

    it('does nothing without recursion or bare-tag keys, and honours whole words', () => {
        const entries = [erotic, entry('Архив', archive('Анна', {}, 'x<NSFW>y</NSFW>'))];
        expect(findWrapperCollisions(entries, { ...options, recursive: false })).toEqual([]);
        expect(findWrapperCollisions([entry('Архив', archive('Анна'))], options)).toEqual([]);
        expect(findWrapperCollisions(entries, { ...options, wholeWordsGlobal: true })).toEqual([]);
        expect(findWrapperCollisions(entries, options)).toHaveLength(1);
    });

    it('points the CarrotCast <NSFW> collision to its rule and leaves the others without one (stage 2)', () => {
        const nsfw = findWrapperCollisions([erotic, entry('Архив', archive('Анна', {}, '<NSFW>x</NSFW>'))], options);
        expect(nsfw[0]).toMatchObject({ fixRule: 'wrapper.nsfwCollision', fileFix: false });
        const other = entry('Genres', { key: ['<NSFW>'], comment: 'Adult', content: 'adult themes' });
        const mixed = findWrapperCollisions([other, entry('Архив', archive('Анна', {}, '<NSFW>x</NSFW>'))], options);
        expect(mixed[0]?.fixRule).toBeUndefined();
        const dere = entry('Dere', { key: ['<DERE>'], comment: 'Deredere', content: 'sweet' });
        const bare = findWrapperCollisions([dere, entry('Архив', archive('Галя', {}, 'mentions <DERE>'))], options);
        expect(bare[0]?.fixRule).toBeUndefined();
    });
});
