import { describe, expect, it } from 'vitest';
import {
    archiveName,
    buildSheetMessages,
    cleanExcerptText,
    formatCharacterData,
    formatExcerpt,
    isArchiveOf,
    nameWords,
    parseSheetTarget,
    sameCharacter,
    sheetCommandOfEntry,
    sheetDirective,
    stripDecorators,
} from '../../src/domain/sheet-context';

describe('parseSheetTarget', () => {
    it('reads the name after the command', () => {
        expect(parseSheetTarget('!fullsheet Вера')).toBe('Вера');
        expect(parseSheetTarget('!fullsheet  «Вера Лин», пожалуйста подробно')).toBe('Вера Лин');
        expect(parseSheetTarget('!quicksheet for Atsu.')).toBe('Atsu');
        expect(parseSheetTarget('Сделай !tagsheet на Веру')).toBe('Веру');
        expect(parseSheetTarget('!physheet "Martin"\nmore text')).toBe('Martin');
    });

    it('returns null without a command, without a name or for another command', () => {
        expect(parseSheetTarget('!fullsheet')).toBeNull();
        expect(parseSheetTarget('!fullsheet ,')).toBeNull();
        expect(parseSheetTarget('просто текст')).toBeNull();
        expect(parseSheetTarget(undefined)).toBeNull();
        expect(parseSheetTarget('!quicksheet Вера', 'fullsheet')).toBeNull();
        expect(parseSheetTarget('!quicksheet Вера', 'quicksheet')).toBe('Вера');
        expect(parseSheetTarget(`!fullsheet ${'x'.repeat(80)}`)).toBeNull();
        expect(parseSheetTarget('a!fullsheet Вера')).toBeNull();
    });
});

describe('stripDecorators', () => {
    it('drops leading @@ lines only', () => {
        expect(stripDecorators('@@activate\n@@dont_activate\nText\n@@not a decorator')).toBe('Text\n@@not a decorator');
        expect(stripDecorators('Plain text')).toBe('Plain text');
        expect(stripDecorators('@@only')).toBe('');
        expect(stripDecorators(null)).toBe('');
    });
});

describe('names', () => {
    it('splits names into normalised words', () => {
        expect(nameWords('Atsu_Ibn_Oba Al-Masri')).toEqual(['atsu', 'ibn', 'oba', 'al', 'masri']);
        expect(nameWords('Алёна')).toEqual(['алена']);
        expect(nameWords(null)).toEqual([]);
    });

    it('matches one character across forms', () => {
        expect(sameCharacter('Вера', 'Веру')).toBe(true);
        expect(sameCharacter('Вера', 'Веры')).toBe(true);
        expect(sameCharacter('Мартин', 'Мартина')).toBe(true);
        expect(sameCharacter('Лира', 'Лира Вэнс')).toBe(true);
        expect(sameCharacter('Atsu_Ibn_Oba', 'atsu ibn oba')).toBe(true);
        expect(sameCharacter('Ёлка', 'елка')).toBe(true);
        expect(sameCharacter('Ия', 'Ия')).toBe(true);
    });

    it('does not match different characters', () => {
        expect(sameCharacter('Вера', 'Мартин')).toBe(false);
        expect(sameCharacter('Ия', 'Ию')).toBe(false);
        expect(sameCharacter('Анна', 'Анатолий')).toBe(false);
        expect(sameCharacter('', 'Вера')).toBe(false);
        expect(sameCharacter('Вера', undefined)).toBe(false);
    });
});

const archive = (name: string, extra: Record<string, unknown> = {}) => ({
    key: [name],
    comment: `${name} Character Archive - Generated by Baby Bunny Mode`,
    content: `<BunnymoTags><Name:${name.replace(/ /g, '_')}>, <SPECIES:HUMAN>, <TRAIT:STOIC></BunnymoTags>`,
    ...extra,
});

describe('lore entries', () => {
    it('finds the sheet command of a BunnyMo core entry', () => {
        expect(sheetCommandOfEntry({ key: ['!fullsheet'], content: 'x' })).toBe('fullsheet');
        expect(sheetCommandOfEntry({ key: ['other', '!PhySheet'] })).toBe('physheet');
        expect(sheetCommandOfEntry({ key: ['!conditions'], comment: '🏥 Master - Physical Conditions System' })).toBe(
            null,
        );
        expect(sheetCommandOfEntry({ key: ['Вера'] })).toBeNull();
        expect(sheetCommandOfEntry(null)).toBeNull();
    });

    it('names an archive by its <Name:…> or by the Baby Bunny comment', () => {
        expect(archiveName(archive('Atsu Ibn'))).toBe('Atsu Ibn');
        expect(
            archiveName({
                comment: 'Вера Character Archive (Batch)',
                content: '<BunnymoTags><TRAIT:KIND></BunnymoTags>',
            }),
        ).toBe('Вера');
        expect(archiveName({ comment: 'Something', content: 'none' })).toBeNull();
    });

    it('recognises the archive of a character', () => {
        expect(isArchiveOf(archive('Вера'), 'Веру')).toBe(true);
        expect(isArchiveOf(archive('Вера'), 'Мартин')).toBe(false);
        expect(
            isArchiveOf(
                {
                    key: ['/вер[аы]/i', 'Вера'],
                    comment: 'notes',
                    content: '<BunnymoTags><TRAIT:KIND>, <SPECIES:ELF></BunnymoTags>',
                },
                'Вера',
            ),
        ).toBe(true);
        expect(isArchiveOf({ key: ['Вера'], content: 'no tags here' }, 'Вера')).toBe(false);
        expect(isArchiveOf(null, 'Вера')).toBe(false);
    });
});

describe('cleanExcerptText', () => {
    it('removes tracker JSON, CK and tag blocks, images and HTML', () => {
        const text = [
            '```json\n{"characters": []}\n```',
            '<div class="x">Вера улыбается.</div>',
            '<details><summary>Thoughts</summary>secret</details>',
            '<img src="a.png"> [nai:img:abc]',
            '<!-- hidden --><style>.a{}</style>',
            '<BunnyMoTags>\nВера:\n• TRAIT: kind\n</BunnyMoTags>',
            'Она — <SPECIES:ELF>.',
        ].join('\n');
        expect(cleanExcerptText(text)).toBe('Вера улыбается.\n\nОна — <SPECIES:ELF>.');
        expect(
            cleanExcerptText({ mes: `Текст\n\n${'```json\n{"a": 1}\n```'}\n\n<BunnymoTags><Name:A></BunnymoTags>` }),
        ).toBe('Текст');
        expect(cleanExcerptText(undefined)).toBe('');
        expect(cleanExcerptText({ mes: 42 })).toBe('');
    });

    it('drops NAI Studio picture posts', () => {
        expect(cleanExcerptText({ mes: '', extra: { nai_studio: { prompt: 'x' } } })).toBe('');
    });
});

describe('formatExcerpt', () => {
    it('prefixes names and caps long messages', () => {
        expect(
            formatExcerpt(
                [
                    { name: 'Кай', text: 'Привет' },
                    { name: '', text: 'abcdef' },
                ],
                4,
            ),
        ).toBe('Кай: Прив…\n\nabcd…');
    });
});

describe('formatCharacterData', () => {
    it('lists every source it has', () => {
        const text = formatCharacterData({
            target: 'Вера',
            card: { description: 'Капитан стражи.', personality: 'Упрямая', scenario: '' },
            persona: null,
            archives: ['<BunnymoTags><Name:Вера></BunnymoTags>'],
            tracker: { details: { appearance: 'плащ', demeanor: ' ' }, relationship: 'Friend', thoughts: 'Устала' },
        });
        expect(text).toContain('[Character data for the sheet: Вера]');
        expect(text).toContain('Character card — description:\nКапитан стражи.');
        expect(text).toContain('Character card — personality:\nУпрямая');
        expect(text).not.toContain('scenario');
        expect(text).toContain('Existing archive entry (CarrotKernel):\n<BunnymoTags><Name:Вера></BunnymoTags>');
        expect(text).toContain('- appearance: плащ\n- relationship: Friend\n- current thoughts: Устала');
        expect(text).not.toContain('demeanor');
    });

    it('says so when it has nothing, and caps very long fields', () => {
        expect(formatCharacterData({ target: 'X' })).toContain('No stored data for this character');
        const long = formatCharacterData({ target: 'X', persona: 'y'.repeat(9000) });
        expect(long).toContain('Persona description:');
        expect(long.length).toBeLessThan(8200);
        expect(formatCharacterData({ target: 'X', tracker: { details: {} } })).toContain('No stored data');
    });
});

describe('sheet messages', () => {
    it('builds the instruction, data, excerpt and command messages', () => {
        const directive = sheetDirective('fullsheet', 'Вера');
        expect(directive).toContain('Output ONLY the !fullsheet sheet for Вера');
        const messages = buildSheetMessages({
            instruction: '  BunnyMo rules  ',
            directive,
            characterData: 'data',
            excerpt: 'Кай: привет',
            command: ' !fullsheet Вера ',
        });
        expect(messages).toEqual([
            { role: 'system', content: `BunnyMo rules\n\n${directive}` },
            { role: 'system', content: 'data' },
            { role: 'user', content: '[Recent roleplay, oldest first]\n\nКай: привет' },
            { role: 'user', content: '!fullsheet Вера' },
        ]);
        expect(
            buildSheetMessages({ instruction: 'i', directive: 'd', characterData: 'c', excerpt: ' ', command: '!x' }),
        ).toHaveLength(3);
    });
});
