// M28 «Паспорта в лорбуках», stage 10 (plan M28, §2.1, P2, P13, §16): visual passports of lore entries in NAI
// Studio's format — kept in the entry for Maestro and canon books, in the bookRoles sidecar for base books, never for
// BunnyMo; generated by NAI Studio or the background model; handed to NAI Studio for the scene through its passport
// provider; edited in the Lore Studio entry form (section «Паспорт»); the pult tab lists them.
// Exposed as app.modules.api<LorePassportsApi>('lorePassports').
import { formatEnum } from '../../core/labels';
import type { MaestroModule, TargetSpec } from '../../shared/contracts';
import type { LorePassportsApi } from './api';
import {
    LORE_PASSPORTS_ID,
    LORE_PASSPORTS_KEY,
    LorePassportsService,
    PASSPORT_TARGET,
    defaultLorePassportsSettings,
} from './service';
import type { LorePassportsSettings } from './service';
import { LORE_PASSPORTS_STRINGS } from './strings';
import { LORE_PASSPORTS_CSS, lorePassportsTab } from './view';

/** The settings slice with junk values replaced by the defaults. */
function readSettings(slice: Partial<LorePassportsSettings>): LorePassportsSettings {
    const defaults = defaultLorePassportsSettings();
    if (typeof slice.provider !== 'boolean') slice.provider = defaults.provider;
    for (const key of ['lastMessages', 'maxPerScene'] as const) {
        const value = slice[key];
        if (typeof value !== 'number' || !Number.isFinite(value) || value < 1) slice[key] = defaults[key];
    }
    return slice as LorePassportsSettings;
}

/** A passport reads by who wrote it; the passport itself is NAI Studio's tags and fields (technical). */
export const LORE_PASSPORTS_TARGETS: TargetSpec[] = [
    {
        target: PASSPORT_TARGET,
        fields: {
            generatedBy: { labelKey: 'm28.field.by', format: formatEnum('m28.by.') },
            passport: { labelKey: 'm28.field.look', hidden: true },
        },
    },
];

export const lorePassportsModule: MaestroModule<LorePassportsSettings> = {
    id: LORE_PASSPORTS_ID,
    key: LORE_PASSPORTS_KEY,
    stage: 10,
    titleKey: 'm28.title',
    enabledByDefault: true,
    defaults: defaultLorePassportsSettings,
    i18n: LORE_PASSPORTS_STRINGS,
    targets: LORE_PASSPORTS_TARGETS,
    init({ app, log, own }) {
        const settings = () => readSettings(app.settings.module<Partial<LorePassportsSettings>>(LORE_PASSPORTS_KEY));
        const service = new LorePassportsService(app, log.scope('lorePassports'), settings);
        for (const off of service.install()) own(off);
        app.modules.expose(LORE_PASSPORTS_KEY, service satisfies LorePassportsApi);
        own(() => app.modules.expose(LORE_PASSPORTS_KEY, undefined));
        own(app.ui.style('m28-lore-passports', LORE_PASSPORTS_CSS));
        own(app.ui.addTab(lorePassportsTab(app, service, settings)));
    },
};

export { LORE_PASSPORTS_STRINGS } from './strings';
export { LORE_PASSPORTS_ID, LORE_PASSPORTS_KEY, LorePassportsService, defaultLorePassportsSettings } from './service';
export type { BatchState, LorePassportsSettings } from './service';
export { PROVIDER_ID, PROVIDER_PRIORITY } from './scene';
export type { LorePassport, LorePassportsApi, PassportPlace, ProposedPassport } from './api';
