// Strings of M38 «Проверка промпта» (keys `m38.*`, plus the labels of its journal kinds).
import type { I18nParts } from '../../shared/contracts';

const EN: Record<string, string> = {
    'm38.title': 'Prompt check',
    'm38.profileTask': 'Prompt check (AI)',

    /* owners */
    'm38.owner.gone': 'An instruction that is gone',
    'm38.owner.preset': 'Preset «{preset}», block «{block}»',
    'm38.owner.card.system': 'Character card: system prompt',
    'm38.owner.card.postHistory': 'Character card: instructions after the history',
    'm38.owner.card.depth': 'Character card: note at a depth',
    'm38.owner.authorsNote': 'Author’s note',
    'm38.owner.maestro': 'Maestro: {module}',
    'm38.owner.bunnymo': 'BunnyMo: «{entry}»',
    'm38.owner.lore': 'Lorebook «{book}»: «{entry}»',
    'm38.owner.other': 'Another extension',
    'm38.owner.desTracker': 'DES tracker: instructions',
    'm38.owner.desHtml': 'DES: HTML pieces',
    'm38.owner.desColors': 'DES: dialogue colours',
    'm38.owner.desContext': 'DES: scene context',
    'm38.owner.des': 'DES tracker',
    'm38.owner.nai': 'NAI Studio picture rules',
    'm38.owner.qvink': 'Qvink memory',
    'm38.owner.desru': 'DES-RU language rule',
    'm38.owner.ck': 'CarrotKernel character data',
    'm38.owner.dramatis': 'Dramatis: {part}',
    'm38.dramatis.cast': 'motive card of the characters',

    /* values */
    'm38.unit.words': 'words',
    'm38.unit.paragraphs': 'paragraphs',
    'm38.unit.sentences': 'sentences',
    'm38.unit.tokens': 'tokens',
    'm38.unit.lines': 'line',
    'm38.lang.en': 'English',
    'm38.lang.ru': 'Russian',
    'm38.lang.ja': 'Japanese',
    'm38.lang.zh': 'Chinese',
    'm38.lang.de': 'German',
    'm38.lang.fr': 'French',
    'm38.lang.es': 'Spanish',
    'm38.value.first': 'first person',
    'm38.value.second': 'second person',
    'm38.value.third': 'third person',
    'm38.value.past': 'past tense',
    'm38.value.present': 'present tense',
    'm38.value.json': 'a JSON block',
    'm38.value.images': 'pictures',
    'm38.value.infobox': 'an info box',
    'm38.value.html': 'HTML',
    'm38.value.markdown': 'markdown',
    'm38.value.code': 'code blocks',
    'm38.value.plain': 'plain text only',
    'm38.value.not': 'not {value}',
    'm38.and': 'and',

    /* topics */
    'm38.topic.language': 'Reply language',
    'm38.topic.pov': 'Narration person',
    'm38.topic.tense': 'Tense',
    'm38.topic.length': 'Reply length',
    'm38.topic.format': 'Reply format',
    'm38.topic.userAgency': 'Writing for your character',
    'm38.topic.askUser': 'Asking you',
    'm38.topic.images': 'Number of pictures',
    'm38.topic.pacing': 'Pace of the story',
    'm38.topic.tight': 'The reply cannot hold everything',
    'm38.topic.duplicate': 'The same instruction twice',
    'm38.topic.role': 'A risky system message',
    'm38.topic.prefill': 'A prefill at the end',
    'm38.topic.assistantDepth': 'An instruction in the assistant’s name',
    'm38.topic.unused': 'A block that does not go out',
    'm38.topic.ai': 'Found by the AI check',
    'm38.demand.json': 'the tracker JSON',
    'm38.demand.images': 'picture markers',
    'm38.demand.infobox': 'the info box',
    'm38.demand.html': 'HTML pieces',
    'm38.demand.event': 'a world event every turn',

    /* why */
    'm38.why.language':
        'One instruction asks for replies in {a}, the other in {b}. The model will pick one at random or mix them.',
    'm38.why.pov': 'One instruction wants the story told in {a}, the other in {b}.',
    'm38.why.tense': 'One instruction asks for {a}, the other for {b}.',
    'm38.why.length': 'The length limits do not overlap: {a} against {b}. The model will break one of them.',
    'm38.why.format': 'One instruction requires {value}, the other forbids it. The model will drop one of them.',
    'm38.why.plain':
        'One instruction allows plain text only, the other requires {value}. The model will drop one of them.',
    'm38.why.userAgency':
        'One instruction forbids writing for your character, the other asks to describe their actions or words. The model will sometimes take over your character and sometimes not.',
    'm38.why.askUser':
        'One instruction asks the model to ask you (consent, what you do next), the other forbids it. Replies will swing between the two.',
    'm38.why.images': 'The number of pictures does not add up: {a} against {b}.',
    'm38.why.pacing':
        'One instruction wants the story pushed forward every turn, the other wants the model to wait for you.',
    'm38.why.tight':
        'The reply is limited ({limit}), while other instructions want more in every reply: {demands}. It cannot all fit — the model will drop something required, most often the tracker JSON or the pictures.',
    'm38.why.duplicate':
        'The same instruction comes twice from different places. It costs tokens, and when one copy is edited the other stays old.',
    'm38.why.roleTrailing':
        'At the end of the prompt one big system message is glued together from several instructions (about {chars} characters).',
    'm38.why.roleEnd': 'A system message stands after the chat history.',
    'm38.why.roleMiddle': 'A system message stands in the middle of the chat history.',
    'm38.why.prefill': 'The last message of the prompt is in the assistant’s name (a prefill).',
    'm38.why.assistantDepth': 'An instruction is put into the history in the assistant’s name.',
    'm38.why.unused': 'This block does not reach the model.',
    'm38.why.ai': 'The AI check found a disagreement here.',
    'm38.risk.systemMerge':
        'On {model} system messages inside or after the history get no role of their own and are glued to the turns around them: the model may stop writing the tracker JSON and the dialogue colours — that is what happened when the tracker instructions were switched to the system role.',
    'm38.risk.prefillEos':
        'On {model} through OpenRouter such a prefill is closed at once: the reply comes back empty.',
    'm38.risk.assistantDepth': '{model} takes it for its own earlier reply and may repeat it.',
    'm38.model.this': 'this model',

    /* fixes */
    'm38.change.edit': 'replace «{before}» with «{after}»',
    'm38.change.remove': 'remove «{before}»',
    'm38.change.toggle': 'switch it off',
    'm38.change.role': 'set the role to «{role}»',
    'm38.change.move': 'move it to depth {depth}',
    'm38.role.system': 'system',
    'm38.role.user': 'user',
    'm38.role.assistant': 'assistant',
    'm38.reason.removeSide':
        'I suggest removing the demand from «{target}»: then only what «{other}» asks for stays. If you want it the other way round, change the other side by hand.',
    'm38.reason.exception':
        'The length limit stays, but it says that the required blocks do not count toward it — so the model fits both the story and the extra parts.',
    'm38.reason.duplicate': 'The repeat goes from «{target}»; the same instruction stays in «{other}».',
    'm38.reason.duplicateBlock': 'Block «{target}» almost fully repeats «{other}»: it can be switched off.',
    'm38.reason.prefill': 'The prefill is switched off: on this model it only does harm.',
    'm38.reason.roleUser': 'The role becomes «user»: such messages are not glued to the ones around them.',
    'm38.advice.bunnymo':
        'This is a BunnyMo entry — Maestro never changes BunnyMo. Remove the conflict from the other side instead.',
    'm38.advice.lore': 'This is an entry of lorebook «{book}». Change it in the Lore Studio: {change}.',
    'm38.advice.card': 'This is a field of the character card. Change it in the card: {change}.',
    'm38.advice.authorsNote': 'This is the author’s note. Change it in its window: {change}.',
    'm38.advice.neighbourSetting':
        'This is a setting of the extension, not its text. Change it in its settings: {change}.',
    'm38.advice.desRole': 'In DES: tracker settings → prompt injection → role of the tracker instructions → «{role}».',
    'm38.advice.maestro': 'This is a Maestro insert. It is set up in the settings of «{module}».',
    'm38.advice.dramatis':
        'This is part of Dramatis («{module}»): Maestro does not change it. Change it in the Dramatis settings: {change}.',
    'm38.advice.risky': 'Better not change the role like this on your model: {risk}',
    'm38.advice.other': 'Change it by hand in «{target}»: {change}.',
    'm38.advice.missing': 'This instruction is no longer in the prompt map. Run the check again.',
    'm38.state.on': 'on',
    'm38.state.off': 'off',
    'm38.fix.scopeUnavailable': 'This scope is not available here.',
    'm38.fix.none': 'There is no ready fix for this conflict.',
    'm38.fix.noScope.global': 'Nothing to change.',
    'm38.fix.noScope.character': 'No character is open: a copy for the character cannot be made.',
    'm38.fix.noScope.chat': 'No chat is open: a copy for the chat cannot be made.',
    'm38.fix.done.global': 'Fixed everywhere: {target}.',
    'm38.fix.done.character': 'Fixed for this character: {target}.',
    'm38.fix.done.chat': 'Fixed for this chat: {target}.',
    'm38.fix.globalOnly': '«{target}» can only be changed everywhere.',
    'm38.fix.noPreset': 'The Preset Studio is off: preset blocks cannot be changed now.',
    'm38.fix.noLayer': 'Your preset layer is not available: only an edit everywhere is possible.',
    'm38.fix.gone': '«{target}» is no longer there.',
    'm38.fix.changed': '«{target}» has changed since the check: run the check again.',
    'm38.fix.noNeighbours': 'Neighbour prompts are off: the extension’s text cannot be changed now.',
    'm38.fix.notEditable': '«{target}» cannot be changed everywhere: only a copy for the character or the chat.',
    'm38.fix.notScopable': '«{target}» cannot get its own copy for the character or the chat.',
    'm38.fix.already': 'This one is already fixed.',
    'm38.fix.failed': 'The fix did not go through: {error}',
    'm38.fix.batchDone': 'Fixed: {count}. One undo in the journal brings them all back.',
    'm38.fix.batchPartial': 'Fixed: {done}, not fixed: {failed}. {reasons}',
    'm38.journal.setting': 'Prompt check: switched off {target}',
    'm38.journal.batch': 'Prompt check: fixed {count} at once',
    'm38.target.setting': 'Maestro setting',
    'm38.target.value': 'Value',
    'm38.target.on': 'on',
    'm38.target.off': 'off',
    'm38.target.batch': 'Prompt check fixes',
    'm38.target.batchValue': 'fixes: {count}',
    'kind.promptAudit.setting': 'Prompt check: a Maestro insert switched off',
    'kind.promptAudit.batch': 'Prompt check: several fixes at once',

    /* the dry run and the AI */
    'm38.dry.failed': 'The test assembly did not work out: the last turn is checked instead.',
    'm38.ai.noProfile': 'No connection profile for the AI check: choose one in Maestro’s settings.',
    'm38.ai.cap':
        'Today’s limit of background spending is reached: the AI check waits until tomorrow, or raise the limit in Maestro’s settings.',
    'm38.ai.job': 'Prompt check by AI',
    'm38.ai.phase.asking': 'The model reads {count} instructions…',
    'm38.ai.stopped': 'The AI check was stopped.',
    'm38.ai.badAnswer': 'the model’s answer could not be read',
    'm38.ai.failed': 'the request failed',
    'm38.ai.failedNotice': 'The AI check did not work out.',
    'm38.ai.found': 'The AI check found conflicts: {count}.',
    'm38.ai.none': 'The AI check found no conflicts.',
    'm38.ai.confirmTitle': 'Check the prompt with AI?',
    'm38.ai.confirmBody':
        'The background model gets the map of instructions (no lore and no chat history): about {tokens} tokens, roughly {cost}.',

    /* the view */
    'm38.view.intro':
        'Everything that goes to the model as an instruction — the preset, the card, the author’s note, every extension and Maestro itself — checked for demands that contradict each other.',
    'm38.view.sourceTurn': 'Last turn, {time}',
    'm38.view.sourceDry': 'Test assembly, {time}',
    'm38.view.preset': 'preset «{name}»',
    'm38.view.model': 'model {model}',
    'm38.view.items': 'instructions: {count}',
    'm38.view.fromTurn':
        'In a test assembly ST skips the extensions that add their texts while generating: those are taken from the last turn.',
    'm38.view.noCapture':
        'There was no turn in this chat yet. Send a message, or make a test assembly — then there is something to check.',
    'm38.view.check': 'Check',
    'm38.view.dry': 'Test assembly',
    'm38.view.dryHint': 'Assemble the prompt now without sending it, then check it.',
    'm38.view.ai': 'AI check…',
    'm38.view.estimate': 'AI check: about {tokens} tokens, roughly {cost}.',
    'm38.view.stop': 'Stop',
    'm38.view.busy.check': 'Checking…',
    'm38.view.busy.dry': 'Assembling the prompt…',
    'm38.view.busy.fix': 'Fixing…',
    'm38.view.aiError': 'The last AI check failed: {error}',
    'm38.view.summary': 'Serious: {high} · medium: {medium} · minor: {low}',
    'm38.view.clean': 'No conflicts found.',
    'm38.view.hidden': 'Marked as not a conflict: {count}',
    'm38.view.restore': 'Show them again',
    'm38.view.scope': 'Where',
    'm38.view.fixSelected': 'Fix the ticked ones ({count})',
    'm38.view.recheck': 'Check again',
    'm38.view.recheckHint':
        'The check again looks at the last turn with your fixes. For a full picture send a message or make a test assembly.',
    'm38.view.notChecked': 'Not checked yet.',
    'm38.view.select': 'Tick for fixing together',
    'm38.view.byAi': 'AI',
    'm38.view.byRules': 'rules',
    'm38.view.fixed': 'fixed',
    'm38.view.also': 'Also involved: {names}',
    'm38.view.risk': 'What it risks: {risk}',
    'm38.view.skip': 'Skip',
    'm38.view.ignore': 'Not a conflict',
    'm38.view.ignoreHint': 'Hide it in later checks too.',
    'm38.view.details': 'Details',
    'm38.view.fixTarget': 'What to change: {target}',
    'm38.view.wasBecame': 'Before → after',
    'm38.view.stateChange': '{before} → {after}',
    'm38.view.fix': 'Fix',
    'm38.severity.high': 'Serious',
    'm38.severity.medium': 'Medium',
    'm38.severity.low': 'Minor',
    'm38.scope.global': 'Everywhere',
    'm38.scope.character': 'This character',
    'm38.scope.chat': 'This chat',

    /* the slash command and the assistant */
    'm38.slash.help':
        'Checks the prompt of the last turn for conflicting instructions and opens the report («dry» — a test assembly first).',
    'm38.slash.mode': '«dry» to check a test assembly',
    'm38.slash.none': 'Nothing to check yet: send a message first.',
    'm38.slash.result': 'Prompt check: conflicts {count}, serious {high}.',
    'm38.tool.noConflict': 'There is no such conflict in the last report: run prompt_audit again.',
    'm38.tool.scope': 'This fix can be written here only: {scopes}.',
    'm38.tool.summary': 'Prompt check: {title} — {target}',
    'm38.tool.noCapture': 'There was no turn yet: send a message, or ask for a test assembly.',
};

const RU: Record<string, string> = {
    'm38.title': 'Проверка промпта',
    'm38.profileTask': 'Проверка промпта (ИИ)',

    'm38.owner.gone': 'Инструкция, которой больше нет',
    'm38.owner.preset': 'Пресет «{preset}», блок «{block}»',
    'm38.owner.card.system': 'Карточка персонажа: системный промпт',
    'm38.owner.card.postHistory': 'Карточка персонажа: инструкции после истории',
    'm38.owner.card.depth': 'Карточка персонажа: заметка на глубине',
    'm38.owner.authorsNote': 'Заметка автора',
    'm38.owner.maestro': 'Maestro: {module}',
    'm38.owner.bunnymo': 'BunnyMo: «{entry}»',
    'm38.owner.lore': 'Книга «{book}»: «{entry}»',
    'm38.owner.other': 'Другое расширение',
    'm38.owner.desTracker': 'Трекер DES: инструкции',
    'm38.owner.desHtml': 'DES: HTML-вставки',
    'm38.owner.desColors': 'DES: цвета реплик',
    'm38.owner.desContext': 'DES: контекст сцены',
    'm38.owner.des': 'Трекер DES',
    'm38.owner.nai': 'Правила картинок NAI Studio',
    'm38.owner.qvink': 'Память Qvink',
    'm38.owner.desru': 'Языковое правило DES-RU',
    'm38.owner.ck': 'Данные персонажей CarrotKernel',
    'm38.owner.dramatis': 'Dramatis: {part}',
    'm38.dramatis.cast': 'карточка мотивов персонажей',

    'm38.unit.words': 'слов',
    'm38.unit.paragraphs': 'абзацев',
    'm38.unit.sentences': 'предложений',
    'm38.unit.tokens': 'токенов',
    'm38.unit.lines': 'строка',
    'm38.lang.en': 'английском',
    'm38.lang.ru': 'русском',
    'm38.lang.ja': 'японском',
    'm38.lang.zh': 'китайском',
    'm38.lang.de': 'немецком',
    'm38.lang.fr': 'французском',
    'm38.lang.es': 'испанском',
    'm38.value.first': 'первого лица',
    'm38.value.second': 'второго лица',
    'm38.value.third': 'третьего лица',
    'm38.value.past': 'прошедшее время',
    'm38.value.present': 'настоящее время',
    'm38.value.json': 'JSON-блок',
    'm38.value.images': 'картинки',
    'm38.value.infobox': 'инфобокс',
    'm38.value.html': 'HTML',
    'm38.value.markdown': 'разметку markdown',
    'm38.value.code': 'блоки кода',
    'm38.value.plain': 'только простой текст',
    'm38.value.not': 'не {value}',
    'm38.and': 'и',

    'm38.topic.language': 'Язык ответа',
    'm38.topic.pov': 'Лицо повествования',
    'm38.topic.tense': 'Время повествования',
    'm38.topic.length': 'Длина ответа',
    'm38.topic.format': 'Оформление ответа',
    'm38.topic.userAgency': 'Кто пишет за твоего персонажа',
    'm38.topic.askUser': 'Вопросы к тебе',
    'm38.topic.images': 'Сколько картинок',
    'm38.topic.pacing': 'Темп истории',
    'm38.topic.tight': 'В ответ всё не помещается',
    'm38.topic.duplicate': 'Одна инструкция дважды',
    'm38.topic.role': 'Опасное системное сообщение',
    'm38.topic.prefill': 'Префилл в конце',
    'm38.topic.assistantDepth': 'Инструкция от имени ассистента',
    'm38.topic.unused': 'Блок не доходит до модели',
    'm38.topic.ai': 'Нашла проверка ИИ',
    'm38.demand.json': 'JSON трекера',
    'm38.demand.images': 'маркеры картинок',
    'm38.demand.infobox': 'инфобокс',
    'm38.demand.html': 'HTML-вставки',
    'm38.demand.event': 'событие в мире каждый ход',

    'm38.why.language':
        'Одна инструкция велит отвечать на {a}, другая — на {b}. Модель будет выбирать язык наугад или смешивать их.',
    'm38.why.pov': 'Одна инструкция велит вести рассказ от {a}, другая — от {b}.',
    'm38.why.tense': 'Одна инструкция просит {a}, другая — {b}.',
    'm38.why.length': 'Ограничения длины не пересекаются: {a} против {b}. Одно из них модель нарушит обязательно.',
    'm38.why.format': 'Одна инструкция требует {value}, другая это запрещает. Модель выбросит что-то одно.',
    'm38.why.plain':
        'Одна инструкция разрешает только простой текст, другая требует {value}. Модель выбросит что-то одно.',
    'm38.why.userAgency':
        'Одна инструкция запрещает писать за твоего персонажа, другая просит описывать его действия или слова. Модель будет то перехватывать твоего персонажа, то нет.',
    'm38.why.askUser':
        'Одна инструкция велит модели спрашивать тебя (согласие, что дальше), другая это запрещает. Ответы будут скакать между тем и другим.',
    'm38.why.images': 'Число картинок не сходится: {a} против {b}.',
    'm38.why.pacing': 'Одна инструкция требует двигать сюжет каждый ход, другая — ждать твоих действий.',
    'm38.why.tight':
        'Ответ ограничен ({limit}), а другие инструкции требуют в каждом ответе ещё: {demands}. Всё сразу не помещается — модель выбросит что-то обязательное, чаще всего JSON трекера или картинки.',
    'm38.why.duplicate':
        'Одна и та же инструкция приходит дважды из разных мест. Это лишние токены, а если поправить одну копию, вторая останется старой.',
    'm38.why.roleTrailing':
        'В конце промпта одно большое системное сообщение склеено из нескольких инструкций (около {chars} символов).',
    'm38.why.roleEnd': 'Системное сообщение стоит после истории чата.',
    'm38.why.roleMiddle': 'Системное сообщение стоит посреди истории чата.',
    'm38.why.prefill': 'Последнее сообщение промпта — от имени ассистента (префилл).',
    'm38.why.assistantDepth': 'Инструкция вставлена в историю от имени ассистента.',
    'm38.why.unused': 'Этот блок не доходит до модели.',
    'm38.why.ai': 'Проверка ИИ нашла здесь расхождение.',
    'm38.risk.systemMerge':
        'На {model} системные сообщения посреди и после истории не получают своей роли и склеиваются с соседними репликами: модель может перестать писать JSON трекера и цвета реплик — так уже было, когда инструкции трекера перевели в системную роль.',
    'm38.risk.prefillEos': 'На {model} через OpenRouter такой префилл сразу закрывается: ответ приходит пустым.',
    'm38.risk.assistantDepth': '{model} примет это за свой прошлый ответ и может его повторять.',
    'm38.model.this': 'этой модели',

    'm38.change.edit': 'замени «{before}» на «{after}»',
    'm38.change.remove': 'удали «{before}»',
    'm38.change.toggle': 'выключи',
    'm38.change.role': 'поставь роль «{role}»',
    'm38.change.move': 'перенеси на глубину {depth}',
    'm38.role.system': 'система',
    'm38.role.user': 'пользователь',
    'm38.role.assistant': 'ассистент',
    'm38.reason.removeSide':
        'Предлагаю убрать требование из «{target}» — тогда останется только то, что просит «{other}». Если нужно наоборот, поправь другую сторону вручную.',
    'm38.reason.exception':
        'Лимит длины остаётся, но с уточнением, что обязательные блоки в него не входят, — так модель уложит и историю, и служебные части.',
    'm38.reason.duplicate': 'Повтор уходит из «{target}», та же инструкция остаётся в «{other}».',
    'm38.reason.duplicateBlock': 'Блок «{target}» почти целиком повторяет «{other}» — его можно выключить.',
    'm38.reason.prefill': 'Префилл выключается: на этой модели он только вредит.',
    'm38.reason.roleUser': 'Роль становится «пользователь»: такие сообщения модель не склеивает с соседними.',
    'm38.advice.bunnymo': 'Это запись BunnyMo — Maestro никогда не правит BunnyMo. Убери конфликт с другой стороны.',
    'm38.advice.lore': 'Это запись книги «{book}». Поправь её в Лор-студии: {change}.',
    'm38.advice.card': 'Это поле карточки персонажа. Поправь его в карточке: {change}.',
    'm38.advice.authorsNote': 'Это заметка автора. Поправь её в окне заметки: {change}.',
    'm38.advice.neighbourSetting': 'Это настройка расширения, а не его текст. Поменяй в его настройках: {change}.',
    'm38.advice.desRole': 'В DES: настройки трекера → внедрение промпта → роль инструкций трекера → «{role}».',
    'm38.advice.maestro': 'Это вставка Maestro. Она настраивается в разделе «{module}».',
    'm38.advice.dramatis':
        'Это часть Dramatis («{module}») — Maestro её не меняет. Поправь в настройках Dramatis: {change}.',
    'm38.advice.risky': 'Так менять роль на твоей модели не стоит: {risk}',
    'm38.advice.other': 'Поправь вручную в «{target}»: {change}.',
    'm38.advice.missing': 'Этой инструкции уже нет в карте промпта. Запусти проверку заново.',
    'm38.state.on': 'включён',
    'm38.state.off': 'выключен',
    'm38.fix.scopeUnavailable': 'Здесь такая область недоступна.',
    'm38.fix.none': 'Для этого конфликта нет готового исправления.',
    'm38.fix.noScope.global': 'Менять нечего.',
    'm38.fix.noScope.character': 'Персонаж не открыт — копию для персонажа сделать нельзя.',
    'm38.fix.noScope.chat': 'Чат не открыт — копию для чата сделать нельзя.',
    'm38.fix.done.global': 'Исправил везде: {target}.',
    'm38.fix.done.character': 'Исправил для этого персонажа: {target}.',
    'm38.fix.done.chat': 'Исправил для этого чата: {target}.',
    'm38.fix.globalOnly': '«{target}» можно поменять только везде.',
    'm38.fix.noPreset': 'Пресет-студия выключена — блоки пресета сейчас не поправить.',
    'm38.fix.noLayer': 'Твой слой пресета недоступен — можно поправить только везде.',
    'm38.fix.gone': '«{target}» уже нет.',
    'm38.fix.changed': '«{target}» изменился после проверки — проверь заново.',
    'm38.fix.noNeighbours': 'Промпты соседей выключены — текст расширения сейчас не поправить.',
    'm38.fix.notEditable': '«{target}» нельзя поменять везде — только копией для персонажа или чата.',
    'm38.fix.notScopable': 'Для «{target}» нельзя сделать свою копию для персонажа или чата.',
    'm38.fix.already': 'Это уже исправлено.',
    'm38.fix.failed': 'Исправить не вышло: {error}',
    'm38.fix.batchDone': 'Исправлено: {count}. Одна отмена в журнале вернёт всё разом.',
    'm38.fix.batchPartial': 'Исправлено: {done}, не вышло: {failed}. {reasons}',
    'm38.journal.setting': 'Проверка промпта: выключил «{target}»',
    'm38.journal.batch': 'Проверка промпта: исправил сразу {count}',
    'm38.target.setting': 'Настройка Maestro',
    'm38.target.value': 'Значение',
    'm38.target.on': 'включено',
    'm38.target.off': 'выключено',
    'm38.target.batch': 'Исправления проверки промпта',
    'm38.target.batchValue': 'исправлений: {count}',
    'kind.promptAudit.setting': 'Проверка промпта: выключена вставка Maestro',
    'kind.promptAudit.batch': 'Проверка промпта: несколько исправлений сразу',

    'm38.dry.failed': 'Пробная сборка не получилась — проверяю последний ход.',
    'm38.ai.noProfile': 'Нет профиля подключения для проверки ИИ — выбери его в настройках Maestro.',
    'm38.ai.cap':
        'Дневной лимит фоновых трат исчерпан: проверка ИИ подождёт до завтра, или подними лимит в настройках Maestro.',
    'm38.ai.job': 'Проверка промпта ИИ',
    'm38.ai.phase.asking': 'Модель читает инструкции ({count})…',
    'm38.ai.stopped': 'Проверку ИИ остановили.',
    'm38.ai.badAnswer': 'ответ модели не удалось разобрать',
    'm38.ai.failed': 'запрос не прошёл',
    'm38.ai.failedNotice': 'Проверка ИИ не получилась.',
    'm38.ai.found': 'Проверка ИИ нашла конфликты: {count}.',
    'm38.ai.none': 'Проверка ИИ конфликтов не нашла.',
    'm38.ai.confirmTitle': 'Проверить промпт ИИ?',
    'm38.ai.confirmBody':
        'Фоновая модель получит карту инструкций (без лора и истории чата): около {tokens} токенов, примерно {cost}.',

    'm38.view.intro':
        'Всё, что уходит модели как инструкция, — пресет, карточка, заметка автора, каждое расширение и сам Maestro, — проверяется на требования, которые спорят друг с другом.',
    'm38.view.sourceTurn': 'Последний ход, {time}',
    'm38.view.sourceDry': 'Пробная сборка, {time}',
    'm38.view.preset': 'пресет «{name}»',
    'm38.view.model': 'модель {model}',
    'm38.view.items': 'инструкций: {count}',
    'm38.view.fromTurn':
        'В пробной сборке ST пропускает расширения, которые добавляют свои тексты во время генерации, — их тексты взяты из последнего хода.',
    'm38.view.noCapture':
        'В этом чате ещё не было ни одного хода. Отправь сообщение или сделай пробную сборку — тогда будет что проверять.',
    'm38.view.check': 'Проверить',
    'm38.view.dry': 'Пробная сборка',
    'm38.view.dryHint': 'Собрать промпт сейчас без отправки модели и проверить его.',
    'm38.view.ai': 'Проверка ИИ…',
    'm38.view.estimate': 'Проверка ИИ: около {tokens} токенов, примерно {cost}.',
    'm38.view.stop': 'Остановить',
    'm38.view.busy.check': 'Проверяю…',
    'm38.view.busy.dry': 'Собираю промпт…',
    'm38.view.busy.fix': 'Исправляю…',
    'm38.view.aiError': 'Прошлая проверка ИИ не получилась: {error}',
    'm38.view.summary': 'Серьёзные: {high} · средние: {medium} · мелкие: {low}',
    'm38.view.clean': 'Конфликтов не нашлось.',
    'm38.view.hidden': 'Отмечено как не конфликт: {count}',
    'm38.view.restore': 'Показать снова',
    'm38.view.scope': 'Где',
    'm38.view.fixSelected': 'Исправить отмеченные ({count})',
    'm38.view.recheck': 'Проверить ещё раз',
    'm38.view.recheckHint':
        'Повторная проверка смотрит последний ход с твоими исправлениями. Для полной картины отправь сообщение или сделай пробную сборку.',
    'm38.view.notChecked': 'Ещё не проверялось.',
    'm38.view.select': 'Отметить, чтобы исправить вместе',
    'm38.view.byAi': 'ИИ',
    'm38.view.byRules': 'правила',
    'm38.view.fixed': 'исправлено',
    'm38.view.also': 'Ещё участвуют: {names}',
    'm38.view.risk': 'Чем грозит: {risk}',
    'm38.view.skip': 'Пропустить',
    'm38.view.ignore': 'Не считать конфликтом',
    'm38.view.ignoreHint': 'Не показывать и в следующих проверках.',
    'm38.view.details': 'Подробнее',
    'm38.view.fixTarget': 'Что поправить: {target}',
    'm38.view.wasBecame': 'Было → стало',
    'm38.view.stateChange': '{before} → {after}',
    'm38.view.fix': 'Исправить',
    'm38.severity.high': 'Серьёзные',
    'm38.severity.medium': 'Средние',
    'm38.severity.low': 'Мелкие',
    'm38.scope.global': 'Везде',
    'm38.scope.character': 'Этот персонаж',
    'm38.scope.chat': 'Этот чат',

    'm38.slash.help':
        'Проверяет промпт последнего хода на спорящие инструкции и открывает отчёт («dry» — сначала пробная сборка).',
    'm38.slash.mode': '«dry» — проверить пробную сборку',
    'm38.slash.none': 'Проверять пока нечего: сначала отправь сообщение.',
    'm38.slash.result': 'Проверка промпта: конфликтов {count}, серьёзных {high}.',
    'm38.tool.noConflict': 'В последнем отчёте нет такого конфликта — запусти prompt_audit заново.',
    'm38.tool.scope': 'Это исправление можно записать только сюда: {scopes}.',
    'm38.tool.summary': 'Проверка промпта: {title} — {target}',
    'm38.tool.noCapture': 'Ходов ещё не было: отправь сообщение или попроси пробную сборку.',
};

export const M38_STRINGS: I18nParts = { en: EN, ru: RU };
