// Strings of M13 «Режиссёр сцены» (`m13.*`) and M14 «Темп и повороты» (`m14.*`). Russian is the primary UI language;
// the user is addressed as «ты» (male). Flag titles follow DIRECTOR_FLAGS (`m13.flag.<name without maestro_>`).
import type { I18nParts } from '../../shared/contracts';

export const DIRECTOR_STRINGS: I18nParts = {
    en: {
        'm13.title': 'Scene director',
        'm13.tab': 'Director',
        'm13.profileTask': 'Scene type when unsure (director)',
        'm13.noChat': 'No chat is open.',
        'm13.hint':
            'The director reads every reply you answer: what kind of scene it is, who is there, whether the story moves. It tunes the next generation with one-shot flags for your preset and, when the story stalls, a short director’s note. It never softens a scene.',
        'm13.scene.title': 'Scene',
        'm13.scene.none': 'Not decided yet: the director reads the scene once you answer a reply.',
        'm13.scene.type.dialogue': 'Dialogue',
        'm13.scene.type.combat': 'Combat and danger',
        'm13.scene.type.intimate': 'Intimate scene',
        'm13.scene.type.exploration': 'Exploration and travel',
        'm13.scene.type.timeskip': 'Time skip',
        'm13.scene.type.social': 'Social scene',
        'm13.scene.type.drama': 'Drama and conflict',
        'm13.scene.confidence': 'confidence {value}%',
        'm13.scene.held.one': 'holds {count} turn',
        'm13.scene.held.few': 'holds {count} turns',
        'm13.scene.held.many': 'holds {count} turns',
        'm13.scene.by.rules': 'by the rules',
        'm13.scene.by.model': 'by the model',
        'm13.scene.by.user': 'chosen by you',
        'm13.scene.by.userMessage': 'by your message',
        'm13.scene.candidate': 'Waiting for confirmation: {type} ({value}%). It takes over if the next turn agrees.',
        'm13.model.queued': 'The rules hesitate: asking the background model…',
        'm13.model.answered': 'The background model says: {type}.',
        'm13.model.failed': 'The background model did not answer: the rules’ decision stays.',
        'm13.override.label': 'Scene type',
        'm13.override.auto': 'Automatic',
        'm13.override.hint': 'Your choice holds until you switch back to automatic.',
        'm13.slash.help':
            'Sets the scene type for the next turns (dialogue, combat, intimate, exploration, time skip, social, drama), or “auto” to let the director decide again. Without a value: names the current one.',
        'm13.slash.type': 'scene type or “auto”',
        'm13.slash.noChat': 'Open a chat first: the scene type is set per chat.',
        'm13.slash.current': 'The scene now: {type} (the director decided). Types: {list}.',
        'm13.slash.currentUser':
            'The scene now: {type} (your choice). Types: {list}; “auto” gives it back to the director.',
        'm13.slash.none': 'The scene type is not decided yet. Types: {list}.',
        'm13.slash.unknown': 'There is no scene type “{name}”. Types: {list}, or “auto”.',
        'm13.slash.set': 'Scene: {type}. It holds from the next reply until you switch back to automatic.',
        'm13.slash.auto': 'The director picks the scene type again.',
        'm13.flags.title': 'Flags for the next generation',
        'm13.flags.hint':
            'One-shot chat variables for conditional preset blocks, for example {{if .maestro_scene_combat}}…{{/if}} (needs the new macro engine). Set right before the generation and cleared after it.',
        'm13.flags.none': 'No flags yet.',
        'm13.picture.cues': 'A picture fits: {cues}',
        'm13.picture.cue.firstAppearance': 'first appearance',
        'm13.picture.cue.placeChange': 'a new place',
        'm13.picture.cue.climax': 'a climax',
        'm13.settings.model': 'Ask the background model when the scene type is unclear',
        'm13.settings.model.hint':
            'One short request, only when the two likeliest types are close; never in «Economy». Its profile is set in Settings → Profiles.',
        'm13.settings.userWeight': 'Weight of your message',
        'm13.settings.userWeight.hint':
            'How much your message counts for the scene type against the reply: 0 ignores it, 0.6 by default. A clear move ("I draw my sword", "I kiss her", "three days later") changes the scene at once.',
        'm13.settings.pictures': 'Hint the moment for a picture (NAI Studio)',
        'm13.settings.pictures.hint':
            'Sets maestro_picture_moment on a first appearance, a new place or a climax. Never in «Economy»; stricter when NAI Studio may spend Anlas.',
        'm13.flag.scene_dialogue': 'Scene: dialogue',
        'm13.flag.scene_dialogue.hint': 'The scene is a conversation without a stronger focus.',
        'm13.flag.scene_combat': 'Scene: combat and danger',
        'm13.flag.scene_combat.hint': 'A fight, a chase or immediate danger.',
        'm13.flag.scene_intimate': 'Scene: intimate',
        'm13.flag.scene_intimate.hint': 'Romance, seduction or an explicit scene.',
        'm13.flag.scene_exploration': 'Scene: exploration and travel',
        'm13.flag.scene_exploration.hint': 'Travel, exploring a place, searching.',
        'm13.flag.scene_timeskip': 'Scene: time skip',
        'm13.flag.scene_timeskip.hint': 'The story has just skipped forward in time.',
        'm13.flag.scene_social': 'Scene: social',
        'm13.flag.scene_social.hint': 'Many people: a feast, a ball, a court, a tavern, etiquette.',
        'm13.flag.scene_drama': 'Scene: drama and conflict',
        'm13.flag.scene_drama.hint': 'An argument, a confrontation or strong emotions.',
        'm13.flag.explicit': 'Explicit scene',
        'm13.flag.explicit.hint': 'The scene is intimate or the last reply was explicit.',
        'm13.flag.lang_ru': 'Chat language: Russian',
        'm13.flag.lang_ru.hint': 'The chat is written in Russian.',
        'm13.flag.lang_en': 'Chat language: English',
        'm13.flag.lang_en.hint': 'The chat is written in English.',
        'm13.flag.picture_moment': 'A moment for a picture',
        'm13.flag.picture_moment.hint':
            'A picture fits the next reply: a first appearance, a new place or a climax (NAI Studio, within the Anlas settings).',
        'm13.flag.reply_short': 'Reply length: short',
        'm13.flag.reply_short.hint': 'Quick scenes: dialogue, combat.',
        'm13.flag.reply_medium': 'Reply length: medium',
        'm13.flag.reply_medium.hint': 'Social scenes, drama, a time skip.',
        'm13.flag.reply_long': 'Reply length: long',
        'm13.flag.reply_long.hint': 'Scenes that take their time: exploration, intimacy.',
        'm14.title': 'Pacing and twists',
        'm14.stall.title': 'Pacing',
        'm14.stall.turns': 'Turns without change: {count}',
        'm14.stall.none': 'No stall.',
        'm14.stall.reasons': 'Stall: {reasons}',
        'm14.reason.samePlace': 'the same place',
        'm14.reason.noEvents': 'nothing happens',
        'm14.reason.repetition': 'repetition',
        'm14.reason.loop': 'the conversation goes in circles',
        'm14.pending.title': 'Note for the next turn',
        'm14.pending.hint': 'It is added to the next generation unless you steer the plot yourself in your message.',
        'm14.suppressed': 'The note was not added: you steered the plot yourself ({reason}).',
        'm14.steer.ooc': 'an out-of-character direction',
        'm14.steer.request': 'a scene request',
        'm14.steer.plot': 'plot words',
        'm14.steer.long': 'a long description of events',
        'm14.steer.action': 'a clear move in the scene',
        'm14.nudge': 'Shake it up',
        'm14.nudge.hint': 'Prepare a director’s note for the next turn now, regardless of the frequency limit',
        'm14.nudge.done':
            "The director's note is ready: it nudges the plot in the next reply unless you steer it yourself first.",
        'm14.nudge.nothing': 'Nothing to build a twist from: the story has no open quests or loose threads.',
        'm14.mode.off': 'In «{mode}» the director writes no notes by itself, only on «Shake it up».',
        'm14.notes.title': 'Director’s notes',
        'm14.notes.empty': 'No notes yet.',
        'm14.notes.index': 'reply #{index}',
        'm14.notes.nudged': 'on request',
        'm14.source.quest': 'Quest',
        'm14.source.thread': 'Unresolved thread',
        'm14.source.deadline': 'Deadline',
        'm14.source.offscreen': 'Offscreen',
        'm14.source.mechanic': 'Mechanic',
        'm14.source.agenda': 'Agenda (Dramatis)',
        'm14.settings.title': 'Settings',
        'm14.settings.stall': 'Stall after this many turns',
        'm14.settings.stall.hint': 'The same place and nothing happening for this many turns in a row, or repetition.',
        'm14.settings.every': 'A note at most once in N turns',
        'm14.settings.every.hint': '0: the director writes no notes by itself in this mode.',
    },
    ru: {
        'm13.title': 'Режиссёр сцены',
        'm13.tab': 'Режиссёр',
        'm13.profileTask': 'Тип сцены при сомнении (режиссёр)',
        'm13.noChat': 'Чат не открыт.',
        'm13.hint':
            'Режиссёр читает каждый ответ, на который ты ответил: что за сцена, кто в ней, движется ли история. Он настраивает следующую генерацию одноразовыми флагами для пресета, а если история встала — короткой заметкой режиссёра. Сцены он никогда не смягчает.',
        'm13.scene.title': 'Сцена',
        'm13.scene.none': 'Пока не определена: режиссёр прочтёт сцену, когда ты ответишь на реплику.',
        'm13.scene.type.dialogue': 'Диалог',
        'm13.scene.type.combat': 'Бой и опасность',
        'm13.scene.type.intimate': 'Интимная сцена',
        'm13.scene.type.exploration': 'Исследование и путь',
        'm13.scene.type.timeskip': 'Пропуск времени',
        'm13.scene.type.social': 'Светская сцена',
        'm13.scene.type.drama': 'Драма и конфликт',
        'm13.scene.confidence': 'уверенность {value}%',
        'm13.scene.held.one': 'держится {count} ход',
        'm13.scene.held.few': 'держится {count} хода',
        'm13.scene.held.many': 'держится {count} ходов',
        'm13.scene.by.rules': 'по правилам',
        'm13.scene.by.model': 'по модели',
        'm13.scene.by.user': 'выбрана тобой',
        'm13.scene.by.userMessage': 'по твоему сообщению',
        'm13.scene.candidate':
            'Ждёт подтверждения: {type} ({value}%). Сменит текущую, если следующий ход скажет то же.',
        'm13.model.queued': 'Правила сомневаются: уточняю у фоновой модели…',
        'm13.model.answered': 'Фоновая модель считает: {type}.',
        'm13.model.failed': 'Фоновая модель не ответила — остаётся решение правил.',
        'm13.override.label': 'Тип сцены',
        'm13.override.auto': 'Автоматически',
        'm13.override.hint': 'Твой выбор держится, пока не вернёшь «Автоматически».',
        'm13.slash.help':
            'Задаёт тип сцены на следующие ходы (диалог, бой, интимная, исследование, пропуск времени, светская, драма) или «авто» — тогда снова решает режиссёр. Без значения — называет текущий.',
        'm13.slash.type': 'тип сцены или «авто»',
        'm13.slash.noChat': 'Сначала открой чат: тип сцены задаётся для чата.',
        'm13.slash.current': 'Сейчас сцена: {type} (решил режиссёр). Типы: {list}.',
        'm13.slash.currentUser': 'Сейчас сцена: {type} (твой выбор). Типы: {list}; «авто» вернёт выбор режиссёру.',
        'm13.slash.none': 'Тип сцены пока не определён. Типы: {list}.',
        'm13.slash.unknown': 'Типа сцены «{name}» нет. Есть: {list} или «авто».',
        'm13.slash.set': 'Сцена: {type}. Держится со следующего ответа, пока не вернёшь «авто».',
        'm13.slash.auto': 'Тип сцены снова выбирает режиссёр.',
        'm13.flags.title': 'Флаги на следующую генерацию',
        'm13.flags.hint':
            'Одноразовые переменные чата для условных блоков пресета, например {{if .maestro_scene_combat}}…{{/if}} (нужен новый движок макросов). Ставятся прямо перед генерацией и снимаются после неё.',
        'm13.flags.none': 'Флагов пока нет.',
        'm13.picture.cues': 'Картинка к месту: {cues}',
        'm13.picture.cue.firstAppearance': 'первое появление',
        'm13.picture.cue.placeChange': 'новое место',
        'm13.picture.cue.climax': 'кульминация',
        'm13.settings.model': 'Спрашивать фоновую модель, когда тип сцены неясен',
        'm13.settings.model.hint':
            'Один короткий запрос, только когда два самых вероятных типа близки; в «Экономном» — никогда. Профиль задаётся в «Настройки → Профили».',
        'm13.settings.userWeight': 'Вес твоего сообщения',
        'm13.settings.userWeight.hint':
            'Насколько твоё сообщение влияет на тип сцены по сравнению с ответом: 0 — не учитывать, по умолчанию 0,6. Явный ход («выхватываю меч», «целую её», «прошло три дня») меняет сцену сразу.',
        'm13.settings.pictures': 'Подсказывать момент для картинки (NAI Studio)',
        'm13.settings.pictures.hint':
            'Ставит maestro_picture_moment при первом появлении, смене места или кульминации. В «Экономном» — никогда; строже, если NAI Studio может тратить Anlas.',
        'm13.flag.scene_dialogue': 'Сцена: диалог',
        'm13.flag.scene_dialogue.hint': 'Разговор без более сильного акцента.',
        'm13.flag.scene_combat': 'Сцена: бой и опасность',
        'm13.flag.scene_combat.hint': 'Схватка, погоня или прямая опасность.',
        'm13.flag.scene_intimate': 'Сцена: интимная',
        'm13.flag.scene_intimate.hint': 'Романтика, соблазнение или откровенная сцена.',
        'm13.flag.scene_exploration': 'Сцена: исследование и путь',
        'm13.flag.scene_exploration.hint': 'Дорога, осмотр места, поиски.',
        'm13.flag.scene_timeskip': 'Сцена: пропуск времени',
        'm13.flag.scene_timeskip.hint': 'История только что перескочила вперёд во времени.',
        'm13.flag.scene_social': 'Сцена: светская',
        'm13.flag.scene_social.hint': 'Много людей: пир, бал, двор, таверна, этикет.',
        'm13.flag.scene_drama': 'Сцена: драма и конфликт',
        'm13.flag.scene_drama.hint': 'Ссора, противостояние или сильные чувства.',
        'm13.flag.explicit': 'Откровенная сцена',
        'm13.flag.explicit.hint': 'Сцена интимная, или прошлый ответ был откровенным.',
        'm13.flag.lang_ru': 'Язык чата: русский',
        'm13.flag.lang_ru.hint': 'Чат идёт на русском.',
        'm13.flag.lang_en': 'Язык чата: английский',
        'm13.flag.lang_en.hint': 'Чат идёт на английском.',
        'm13.flag.picture_moment': 'Момент для картинки',
        'm13.flag.picture_moment.hint':
            'К следующему ответу уместна картинка: первое появление, новое место или кульминация (NAI Studio, в рамках настроек Anlas).',
        'm13.flag.reply_short': 'Длина ответа: короткий',
        'm13.flag.reply_short.hint': 'Быстрые сцены: диалог, бой.',
        'm13.flag.reply_medium': 'Длина ответа: средний',
        'm13.flag.reply_medium.hint': 'Светские сцены, драма, пропуск времени.',
        'm13.flag.reply_long': 'Длина ответа: длинный',
        'm13.flag.reply_long.hint': 'Неспешные сцены: исследование, близость.',
        'm14.title': 'Темп и повороты',
        'm14.stall.title': 'Темп',
        'm14.stall.turns': 'Ходов без перемен: {count}',
        'm14.stall.none': 'Застоя нет.',
        'm14.stall.reasons': 'Застой: {reasons}',
        'm14.reason.samePlace': 'одно и то же место',
        'm14.reason.noEvents': 'ничего не происходит',
        'm14.reason.repetition': 'повторы',
        'm14.reason.loop': 'разговор ходит по кругу',
        'm14.pending.title': 'Заметка на следующий ход',
        'm14.pending.hint': 'Она уйдёт в следующую генерацию, если в своём сообщении ты сам не направишь сюжет.',
        'm14.suppressed': 'Заметка не добавлена: ты сам направил сюжет ({reason}).',
        'm14.steer.ooc': 'указание вне роли',
        'm14.steer.request': 'просьба о сцене',
        'm14.steer.plot': 'сюжетные слова',
        'm14.steer.action': 'ясное действие в сцене',
        'm14.steer.long': 'длинное описание событий',
        'm14.nudge': 'Встряхнуть',
        'm14.nudge.hint': 'Подготовить заметку режиссёра к следующему ходу сейчас, без ограничения частоты',
        'm14.nudge.done':
            'Заметка режиссёра готова: она подтолкнёт сюжет в следующем ответе, если ты сам не направишь его раньше.',
        'm14.nudge.nothing': 'Поворот не из чего строить: в истории нет открытых квестов и незакрытых сюжетных линий.',
        'm14.mode.off': 'В режиме «{mode}» режиссёр сам заметок не пишет — только по кнопке «Встряхнуть».',
        'm14.notes.title': 'Заметки режиссёра',
        'm14.notes.empty': 'Заметок пока нет.',
        'm14.notes.index': 'ответ №{index}',
        'm14.notes.nudged': 'по кнопке',
        'm14.source.quest': 'Квест',
        'm14.source.thread': 'Незакрытая нить',
        'm14.source.deadline': 'Срок',
        'm14.source.offscreen': 'Закулисье',
        'm14.source.mechanic': 'Механика',
        'm14.source.agenda': 'Повестка (Dramatis)',
        'm14.settings.title': 'Настройки',
        'm14.settings.stall': 'Застой — после стольких ходов',
        'm14.settings.stall.hint': 'Столько ходов подряд то же место и ничего не происходит, или повторы.',
        'm14.settings.every': 'Заметка не чаще раза в N ходов',
        'm14.settings.every.hint': '0 — в этом режиме режиссёр сам заметок не пишет.',
    },
};
