// Strings of the Preset Studio for release 1.13 (plan-2 «Области действия»): scopes of the layer, the preset bound to a
// card or a chat, and the «Промпты соседей» tab. Merged into PRESET_STUDIO_STRINGS (module.ts).
import type { I18nParts } from '../../shared/contracts';

export const SCOPE_STRINGS: I18nParts = {
    en: {
        'm34.tab.neighbours': 'Neighbour prompts',
        'm34.tab.audit': 'Prompt check',
        'm34.audit.unavailable': 'The prompt check module is off.',

        'm34.scope.global': 'Everywhere',
        'm34.scope.character': 'This character',
        'm34.scope.characterNamed': 'This character ({name})',
        'm34.scope.chat': 'This chat',
        'm34.scope.where': 'Where the edit works',
        'm34.scope.hint':
            'Everywhere — in every chat; this character — in all chats of this card; this chat — only here. Edits of a character or a chat never go into the preset file.',
        'm34.scope.badge': 'Edits → {scope}',
        'm34.scope.group': '{scope}: {count}',
        'm34.scope.move': 'Where this edit works',

        'm34.binding.button': 'Own preset of this character or chat',
        'm34.binding.title': 'Own preset of this character or chat',
        'm34.binding.body':
            'A bound preset is selected when you open the chat; when you leave, the preset that was on before comes back. Bind «{name}»?',
        'm34.binding.nowChat': 'Now this chat has «{name}».',
        'm34.binding.nowCharacter': 'Now {character} has «{name}».',
        'm34.binding.toChat': 'To this chat',
        'm34.binding.toCharacter': 'To {character}',
        'm34.binding.offChat': 'Unbind from the chat',
        'm34.binding.offCharacter': 'Unbind from the character',
        'm34.binding.noChat': 'Open a character’s chat first: a preset is bound to a character or a chat.',
        'm34.binding.done.chat': 'Preset «{name}» bound to this chat.',
        'm34.binding.done.character': 'Preset «{name}» bound to {character}.',
        'm34.binding.removed.chat': 'This chat has no own preset any more.',
        'm34.binding.removed.character': '{character} has no own preset any more.',
        'm34.binding.activeChat': 'Preset of this chat: {name}',
        'm34.binding.activeCharacter': 'Preset of {character}: {name}',
        'm34.binding.hint': 'Selected when this chat opens; the preset that was on before comes back when you leave.',
        'm34.binding.reason.chat': 'This chat has its own preset «{name}»: I switched to it.',
        'm34.binding.reason.character': '{character} has an own preset «{name}»: I switched to it.',
        'm34.binding.reason.restore': 'Back to the preset «{name}» that was on before the bound chat.',
        'm34.binding.missing': 'The preset «{name}» bound to this chat is gone: the current preset stays.',

        'm34.neighbours.unavailable': 'The neighbour prompts module is off.',
        'm34.neighbours.intro':
            'Instructions other extensions put into the prompt. «Everywhere» changes the extension’s own setting; a copy for this character or this chat is put in by Maestro only when the reply is generated — the extension keeps its own text.',
        'm34.neighbours.none': 'No extension with prompts of its own is on.',
        'm34.neighbours.replaced': 'Last reply: own copies used — {names}.',
        'm34.neighbours.notFound': 'Not found in the prompt, the copy did not work: {names}.',
        'm34.neighbours.owner.des': 'Doom’s Enhancement Suite',
        'm34.neighbours.owner.nai': 'NAI Studio',
        'm34.neighbours.owner.qvink': 'Qvink Memory',
        'm34.neighbours.owner.desru': 'DES-RU',
        'm34.neighbours.owner.ck': 'CarrotKernel',
        'm34.neighbours.owner.maestro': 'Maestro',
        'm34.neighbours.badge.chat': 'own in this chat',
        'm34.neighbours.badge.character': 'own for the character',
        'm34.neighbours.badge.readOnly': 'read only',
        'm34.neighbours.badge.background': 'not in the main prompt',
        'm34.neighbours.showText': 'What goes to the model here',
        'm34.neighbours.emptyText': 'Nothing has been sent yet',
        'm34.neighbours.edit': 'Change',
        'm34.neighbours.scope.global': 'Everywhere (the extension’s setting)',
        'm34.neighbours.scope.character': 'Copy for this character',
        'm34.neighbours.scope.chat': 'Copy for this chat',
        'm34.neighbours.scopeHint':
            'A copy works only in this character’s chats or in this chat; with Maestro off the extension sends its own text.',
        'm34.neighbours.save': 'Save',
        'm34.neighbours.cancel': 'Cancel',
        'm34.neighbours.saved.global': '«{name}» changed everywhere.',
        'm34.neighbours.saved.character': 'This character now has an own «{name}».',
        'm34.neighbours.saved.chat': 'This chat now has an own «{name}».',
        'm34.neighbours.resetTitle': 'Put it back?',
        'm34.neighbours.resetBody.global': '«{name}» gets the extension’s own text again.',
        'm34.neighbours.resetBody.character': 'This character’s copy of «{name}» goes away.',
        'm34.neighbours.resetBody.chat': 'This chat’s copy of «{name}» goes away.',
        'm34.neighbours.reset.global': 'As it was',
        'm34.neighbours.reset.character': 'Remove the character’s copy',
        'm34.neighbours.reset.chat': 'Remove the chat’s copy',
        'm34.neighbours.error.unknown': 'There is no such prompt.',
        'm34.neighbours.error.readOnly': 'This text cannot be changed from here.',
        'm34.neighbours.error.absent': 'The extension is off or did not take the text.',
        'm34.neighbours.error.busy': 'DES’s Workshop is open: close it and try again.',
        'm34.neighbours.error.notScopable': 'This text cannot have a copy for a character or a chat.',
        'm34.neighbours.error.noScope': 'Open the character’s chat first.',
    },
    ru: {
        'm34.tab.neighbours': 'Промпты соседей',
        'm34.tab.audit': 'Проверка промпта',
        'm34.audit.unavailable': 'Модуль проверки промпта выключен.',

        'm34.scope.global': 'Везде',
        'm34.scope.character': 'Этот персонаж',
        'm34.scope.characterNamed': 'Этот персонаж ({name})',
        'm34.scope.chat': 'Этот чат',
        'm34.scope.where': 'Где действует правка',
        'm34.scope.hint':
            'Везде — во всех чатах; этот персонаж — во всех чатах этой карточки; этот чат — только здесь. Правки персонажа и чата никогда не попадают в файл пресета.',
        'm34.scope.badge': 'Правки → {scope}',
        'm34.scope.group': '{scope}: {count}',
        'm34.scope.move': 'Где действует эта правка',

        'm34.binding.button': 'Свой пресет персонажа или чата',
        'm34.binding.title': 'Свой пресет персонажа или чата',
        'm34.binding.body':
            'Привязанный пресет включается, когда открываешь чат, а при выходе возвращается тот, что был до него. Привязать «{name}»?',
        'm34.binding.nowChat': 'Сейчас у этого чата — «{name}».',
        'm34.binding.nowCharacter': 'Сейчас у персонажа {character} — «{name}».',
        'm34.binding.toChat': 'К этому чату',
        'm34.binding.toCharacter': 'К персонажу {character}',
        'm34.binding.offChat': 'Отвязать от чата',
        'm34.binding.offCharacter': 'Отвязать от персонажа',
        'm34.binding.noChat': 'Сначала открой чат с персонажем: пресет привязывается к персонажу или чату.',
        'm34.binding.done.chat': 'Пресет «{name}» привязан к этому чату.',
        'm34.binding.done.character': 'Пресет «{name}» привязан к персонажу {character}.',
        'm34.binding.removed.chat': 'У этого чата больше нет своего пресета.',
        'm34.binding.removed.character': 'У персонажа {character} больше нет своего пресета.',
        'm34.binding.activeChat': 'Пресет этого чата: {name}',
        'm34.binding.activeCharacter': 'Пресет персонажа {character}: {name}',
        'm34.binding.hint': 'Включается, когда открываешь этот чат; при выходе возвращается прежний пресет.',
        'm34.binding.reason.chat': 'У этого чата свой пресет «{name}» — включил его.',
        'm34.binding.reason.character': 'У персонажа {character} свой пресет «{name}» — включил его.',
        'm34.binding.reason.restore': 'Вернул пресет «{name}», который был до чата со своим пресетом.',
        'm34.binding.missing': 'Пресета «{name}», привязанного к этому чату, больше нет — оставил текущий.',

        'm34.neighbours.unavailable': 'Модуль «Промпты соседей» выключен.',
        'm34.neighbours.intro':
            'Инструкции, которые другие расширения добавляют в промпт. «Везде» меняет настройку самого расширения; копию для персонажа или чата Maestro подставляет только в момент генерации — у расширения остаётся свой текст.',
        'm34.neighbours.none': 'Не включено ни одного расширения со своими промптами.',
        'm34.neighbours.replaced': 'В последнем ответе сработали свои копии: {names}.',
        'm34.neighbours.notFound': 'Не нашёл в промпте, копия не сработала: {names}.',
        'm34.neighbours.owner.des': 'Doom’s Enhancement Suite',
        'm34.neighbours.owner.nai': 'NAI Studio',
        'm34.neighbours.owner.qvink': 'Qvink Memory',
        'm34.neighbours.owner.desru': 'DES-RU',
        'm34.neighbours.owner.ck': 'CarrotKernel',
        'm34.neighbours.owner.maestro': 'Maestro',
        'm34.neighbours.badge.chat': 'свой в этом чате',
        'm34.neighbours.badge.character': 'свой у персонажа',
        'm34.neighbours.badge.readOnly': 'только чтение',
        'm34.neighbours.badge.background': 'не в основном промпте',
        'm34.neighbours.showText': 'Что уходит модели здесь',
        'm34.neighbours.emptyText': 'Пока ничего не отправлялось',
        'm34.neighbours.edit': 'Изменить',
        'm34.neighbours.scope.global': 'Везде (настройка расширения)',
        'm34.neighbours.scope.character': 'Копия для этого персонажа',
        'm34.neighbours.scope.chat': 'Копия для этого чата',
        'm34.neighbours.scopeHint':
            'Копия действует только в чатах этого персонажа или только в этом чате; без Maestro расширение отправляет свой текст.',
        'm34.neighbours.save': 'Сохранить',
        'm34.neighbours.cancel': 'Отмена',
        'm34.neighbours.saved.global': '«{name}» изменён везде.',
        'm34.neighbours.saved.character': 'У этого персонажа теперь свой «{name}».',
        'm34.neighbours.saved.chat': 'У этого чата теперь свой «{name}».',
        'm34.neighbours.resetTitle': 'Вернуть как было?',
        'm34.neighbours.resetBody.global': '«{name}» снова получит собственный текст расширения.',
        'm34.neighbours.resetBody.character': 'Копия «{name}» для этого персонажа будет удалена.',
        'm34.neighbours.resetBody.chat': 'Копия «{name}» для этого чата будет удалена.',
        'm34.neighbours.reset.global': 'Вернуть как было',
        'm34.neighbours.reset.character': 'Убрать копию персонажа',
        'm34.neighbours.reset.chat': 'Убрать копию чата',
        'm34.neighbours.error.unknown': 'Такого промпта нет.',
        'm34.neighbours.error.readOnly': 'Этот текст отсюда не меняется.',
        'm34.neighbours.error.absent': 'Расширение выключено или не приняло текст.',
        'm34.neighbours.error.busy': 'Открыта Мастерская DES — закрой её и повтори.',
        'm34.neighbours.error.notScopable': 'Для этого текста нельзя сделать копию для персонажа или чата.',
        'm34.neighbours.error.noScope': 'Сначала открой чат с персонажем.',
    },
};
