// Strings of M34 «Пресет-студия»: the shell and the views (keys m34.*). The data layer, the user's layer and the
// analysis register their own (store.ts, layer-strings.ts, analysis-strings.ts). Russian is the primary language;
// ST's own Russian labels (public/locales/ru-ru.json) are reused for the parity controls so the studio and Prompt
// Manager speak alike.
import type { I18nParts } from '../../shared/contracts';

const en: Record<string, string> = {
    'm34.title': 'Preset Studio',
    'm34.close': 'Close',
    'm34.classic': 'Classic editor',
    'm34.classicHint': 'Show ST’s own Prompt Manager in the AI Response Configuration panel (for this session)',
    'm34.nav.label': 'Preset Studio sections',
    'm34.tab.map': 'Map',
    'm34.tab.blocks': 'Blocks',
    'm34.tab.analysis': 'Analysis',
    'm34.tab.layer': 'Your layer',
    'm34.tab.versions': 'Versions',
    'm34.tab.params': 'Parameters',

    'm34.error.generic': 'Preset Studio: {error}',
    'm34.error.noStore': 'The preset data layer is not running, so the Preset Studio cannot open. See Maestro’s log.',
    'm34.error.textCompletion':
        'The Preset Studio works with Chat Completion. With Text Completion use SillyTavern’s own preset panels.',

    'm34.dialog.ok': 'OK',
    'm34.dialog.cancel': 'Cancel',
    'm34.dialog.apply': 'Apply',
    'm34.dialog.delete': 'Delete',
    'm34.dialog.save': 'Save',

    'm34.role.system': 'System',
    'm34.role.user': 'User',
    'm34.role.assistant': 'AI Assistant',
    'm34.kind.inChat': 'In-chat injection',
    'm34.kind.marker': 'Marker (filled by SillyTavern)',
    'm34.kind.important': 'Important prompt (a card cannot override it)',
    'm34.kind.global': 'Global prompt',
    'm34.kind.user': 'Preset prompt',
    'm34.trigger.normal': 'Normal',
    'm34.trigger.continue': 'Continue',
    'm34.trigger.impersonate': 'Impersonate',
    'm34.trigger.swipe': 'Swipe',
    'm34.trigger.regenerate': 'Regenerate',
    'm34.trigger.quiet': 'Quiet',
    'm34.source.charDescription': 'Character Description',
    'm34.source.charPersonality': 'Character Personality',
    'm34.source.scenario': 'Character Scenario',
    'm34.source.personaDescription': 'Persona Description',
    'm34.source.worldInfoBefore': 'World Info (↑Char)',
    'm34.source.worldInfoAfter': 'World Info (↓Char)',

    'm34.header.preset': 'Preset',
    'm34.header.actions': 'Preset actions',
    'm34.header.unsaved': 'Unsaved',
    'm34.header.pmError': 'Assembly error',
    'm34.header.unsavedHint':
        'The working copy differs from the saved preset: blocks {prompts}, keys {keys}. Switching presets in ST would drop it.',
    'm34.header.modeLayer': 'Edits → your layer',
    'm34.header.modeLayerHint':
        'Edits made here go into your layer for «{base}» and into the working copy at once; the base file stays as it is.',
    'm34.header.modeStore': 'Edits → preset',
    'm34.header.modeStoreHint': 'Edits change the working copy; «Save» writes them into the preset file.',
    'm34.header.save': 'Save',
    'm34.header.saveHint': 'Write the working copy into the preset file (a version is kept)',
    'm34.header.saveLayer': 'Save',
    'm34.header.saveLayerHint':
        'Your studio edits are already in the layer. Changes made elsewhere (classic editor, commands) go into the layer or the base — you choose.',
    'm34.header.saveBase': 'Save base',
    'm34.header.saveBaseHint': 'Write the working copy without your layer into the base preset file',
    'm34.header.saveAs': 'Save preset as…',
    'm34.header.rename': 'Rename preset',
    'm34.header.import': 'Import preset',
    'm34.header.export': 'Export preset',
    'm34.header.delete': 'Delete preset',

    'm34.switch.title': 'Unsaved changes',
    'm34.switch.body':
        'The preset «{from}» has unsaved changes. SillyTavern drops them silently when switching to «{to}». Save them first?',
    'm34.switch.bodyLayer':
        'The preset «{from}» has changes outside your layer. Switching to «{to}» drops them. Keep them in your layer, save them into the base, or drop them?',
    'm34.switch.save': 'Save',
    'm34.switch.saveLayer': 'Into the layer',
    'm34.switch.saveBase': 'Into the base',
    'm34.switch.discard': 'Drop',
    'm34.leave.title': 'Unsaved block',
    'm34.leave.body': 'The block «{name}» has unsaved edits.',
    'm34.leave.save': 'Save',
    'm34.leave.discard': 'Drop',

    'm34.save.summary': 'Saved in the Preset Studio',
    'm34.save.done': 'Preset «{name}» saved.',
    'm34.save.inLayer': 'Your edits are already in the layer of «{base}»; nothing else to save.',
    'm34.save.layerTitle': 'Save changes',
    'm34.save.layerBody':
        'The working copy of «{base}» has changes that are not in your layer (classic editor, commands, neighbours). Keep them in your layer (they survive a base update) or write them into the base file?',
    'm34.save.toLayer': 'Changes moved into your layer of «{base}»: {applied}. Conflicts: {conflicts}.',
    'm34.saveBase.title': 'Save the base',
    'm34.saveBase.body':
        'The working copy without your layer is written into the preset file «{base}». Your layer stays apart and is laid over the base again.',
    'm34.saveBase.ok': 'Save base',
    'm34.saveAs.title': 'Save preset as',
    'm34.saveAs.hint': 'Tip: name it after a character or group to bind the preset to their chats.',
    'm34.saveAs.done': 'Saved as «{name}».',
    'm34.rename.title': 'Rename «{name}»',
    'm34.rename.hint': 'Connection profiles that use the old name are offered a fix.',
    'm34.rename.done': '«{from}» renamed to «{to}».',
    'm34.delete.title': 'Delete preset',
    'm34.delete.body':
        'Delete the preset «{name}»? SillyTavern switches to the first preset left. Maestro keeps the versions of the deleted preset.',
    'm34.delete.done': 'Preset «{name}» deleted.',
    'm34.import.title': 'Import a preset',
    'm34.import.dirty':
        'The current preset has unsaved changes; importing applies the new preset and drops them. Go on?',
    'm34.import.done': 'Preset «{name}» imported and selected.',
    'm34.export.title': 'Export «{name}»',
    'm34.export.body':
        'The saved preset is exported. Connection data and secret keys (proxy, addresses) are left out unless you choose otherwise.',
    'm34.export.safe': 'Without connection data',
    'm34.export.all': 'With everything (secrets too)',

    'm34.blocks.search': 'Find a block…',
    'm34.blocks.new': 'New block',
    'm34.blocks.newName': 'New block',
    'm34.blocks.copySuffix': 'copy',
    'm34.blocks.insert': 'Insert the block (at the start, off)',
    'm34.blocks.insertPick': 'Blocks outside the list…',
    'm34.blocks.importList': 'Import a prompt list',
    'm34.blocks.exportList': 'Export this prompt list',
    'm34.blocks.resetOrder': 'Reset the order to SillyTavern’s default',
    'm34.blocks.enabled': 'On: {enabled} of {total}',
    'm34.blocks.tokens': 'Tokens: {count}',
    'm34.blocks.tokensHint': 'Tokens of the block (Maestro’s count, or Prompt Manager’s last assembly)',
    'm34.blocks.toLayer': 'edits go to your layer',
    'm34.blocks.dragOff': 'Reordering is off while searching.',
    'm34.blocks.empty': 'The prompt list is empty.',
    'm34.blocks.noMatch': 'No block matches.',
    'm34.blocks.select': 'Select «{name}»',
    'm34.blocks.drag': 'Drag to reorder (Alt+↑/↓ from the keyboard)',
    'm34.blocks.up': 'Move up',
    'm34.blocks.down': 'Move down',
    'm34.blocks.enable': 'Turn on',
    'm34.blocks.disable': 'Turn off',
    'm34.blocks.openHint': 'Edit the block',
    'm34.blocks.viewHint': 'Show the block (SillyTavern fills it)',
    'm34.blocks.missing': 'no such block (an order entry left behind)',
    'm34.blocks.metaRelative': '{role} · in order',
    'm34.blocks.metaInChat': '{role} · in chat at depth {depth}, order {order}',
    'm34.blocks.preview': 'Preview',
    'm34.blocks.duplicate': 'Duplicate',
    'm34.blocks.detach': 'Remove from the list (the block stays)',
    'm34.blocks.delete': 'Delete the block',
    'm34.blocks.conflict': 'conflict',
    'm34.blocks.inLayer': 'in layer',
    'm34.blocks.overridden': 'card',
    'm34.blocks.overriddenHint': 'The character card replaced this block in the last assembly',
    'm34.blocks.types': 'types',
    'm34.blocks.typesHint':
        'Stored with types SillyTavern does not accept (a string depth, an unknown role, no system_prompt=false): the block may be dropped. Saving it in the editor fixes the types.',
    'm34.blocks.markerPreview': 'A marker: SillyTavern puts its text here when it assembles the prompt.',
    'm34.blocks.emptyText': 'The block is empty.',
    'm34.blocks.substitute': 'Substitute macros',
    'm34.blocks.substituted': 'With macros substituted (as now, for the current chat):',
    'm34.blocks.effectsTitle': 'Macros with side effects',
    'm34.blocks.effectsBody':
        'The block uses {macros}: substituting runs them and changes chat variables, like a real generation would. Substitute anyway?',
    'm34.blocks.deleteTitle': 'Delete block',
    'm34.blocks.deleteBody': 'Delete the block «{name}»? It can be undone from Maestro’s journal.',
    'm34.blocks.deleteLayerBody':
        'Delete the block «{name}»? A block you added in your layer is deleted with its operations. A block of the base cannot be deleted by the layer: it is switched off in your layer instead.',
    'm34.blocks.disabledInLayer': '«{name}» belongs to the base preset: it is switched off in your layer.',
    'm34.blocks.resetTitle': 'Reset the order',
    'm34.blocks.resetBody':
        'Put the list back to SillyTavern’s default order? Your blocks leave the list but are not deleted (insert them again from «Blocks outside the list»).',
    'm34.blocks.resetBodyKeep':
        'Put the default blocks back into SillyTavern’s default order and states? Your own blocks stay after them.',
    'm34.bulk.title': 'Selected blocks',
    'm34.bulk.selected': 'Selected: {count}',
    'm34.bulk.selectAll': 'Select all shown',
    'm34.bulk.clear': 'Clear',
    'm34.bulk.enable': 'Turn on',
    'm34.bulk.disable': 'Turn off',

    'm34.list.importTitle': 'Import a prompt list',
    'm34.list.importBody': 'Existing prompts with the same ID will be overridden. Do you want to proceed?',
    'm34.list.imported': 'Prompt list imported: {updated} updated, {added} added.',
    'm34.list.invalid.json': '«{file}» is not JSON.',
    'm34.list.invalid.shape': '«{file}» is not a prompt list (version, type, data.prompts).',

    'm34.editor.panel': 'Block editor',
    'm34.editor.title': 'Block «{name}»',
    'm34.editor.newTitle': 'New block',
    'm34.editor.identifier': 'ID: {id}',
    'm34.editor.close': 'Close',
    'm34.editor.save': 'Save',
    'm34.editor.reset': 'Reset',
    'm34.editor.resetHint': 'Put SillyTavern’s default name and text into the form (nothing is written until Save)',
    'm34.editor.name': 'Name',
    'm34.editor.role': 'Role',
    'm34.editor.roleHint': 'Who the message is sent as.',
    'm34.editor.position': 'Injection position',
    'm34.editor.relative': 'Relative',
    'm34.editor.inChat': 'In-chat',
    'm34.editor.depth': 'Depth',
    'm34.editor.depthHint': '0 = after the last message, 1 = before the last message, and so on.',
    'm34.editor.order': 'Order',
    'm34.editor.orderHint':
        'Lower goes higher. Injections of other sources (lore, Author’s Note) have order 100 and are glued to blocks of order 100 at the same depth and role.',
    'm34.editor.triggers': 'Triggers',
    'm34.editor.triggersHint': 'None checked: every generation type.',
    'm34.editor.forbid': 'Forbid overrides (a character card cannot replace this prompt)',
    'm34.editor.source': 'Source: {source}',
    'm34.editor.content': 'Prompt',
    'm34.editor.tokens': '≈ {count} tokens',
    'm34.editor.highlight': 'Macros and flags',
    'm34.editor.flags': 'Maestro flags: {flags}',
    'm34.editor.sideEffects': 'Changes variables when evaluated: {macros}',
    'm34.editor.keys': 'Ctrl+S saves',
    'm34.editor.layerMode': 'Saving puts the change into your layer and into the working copy.',
    'm34.editor.readOnly': 'SillyTavern fills this marker and keeps its settings: it cannot be edited.',
    'm34.editor.markerText':
        'A marker: SillyTavern fills the text. Role, position, depth, order and triggers can be changed.',
    'm34.editor.types': 'Stored with foreign types ({fields}); saving writes the types SillyTavern accepts.',
    'm34.editor.stale':
        'The preset changed while you were editing. Saving writes into the block of the preset now selected.',
    'm34.editor.missing': 'The block {id} is not in this preset any more.',
    'm34.editor.added': 'Block «{name}» added and switched on.',
    'm34.editor.changedTitle': 'The block changed meanwhile',
    'm34.editor.changedBody':
        '«{name}» was changed outside the studio (classic editor, a command or an extension) while it was open. Write your fields over it?',
    'm34.editor.overwrite': 'Write my fields',

    'm34.map.total': 'Sent: ≈ {count} tokens',
    'm34.map.hint': 'How SillyTavern assembles the prompt from this preset, in order.',
    'm34.map.type': 'Generation',
    'm34.map.refresh': 'Recount',
    'm34.map.reduced':
        'The analysis module is not running: the map shows the order and Prompt Manager’s last counts only.',
    'm34.map.failed': 'The map could not be built: {error}',
    'm34.map.loading': 'Building the map…',
    'm34.map.empty': 'Nothing to show.',
    'm34.map.relative': 'in order',
    'm34.map.depth': 'in chat, depth {depth}, order {order}',
    'm34.map.marker': 'marker',
    'm34.map.off': 'off',
    'm34.map.open': 'Open the block',
    'm34.map.triggersHint': 'Only for these generation types',
    'm34.map.injections': 'Extension injections here',
    'm34.map.injection': '{owner}: {key} (≈ {count})',
    'm34.map.where.start': 'before the text',
    'm34.map.where.end': 'after the text',
    'm34.map.where.chat': 'in chat at depth {depth}',
    'm34.map.dropped': 'Not sent: {reason}',

    'm34.analysis.hint':
        'What may go wrong with this preset: blocks that are never sent, traps, repeats, heavy blocks.',
    'm34.analysis.refresh': 'Check again',
    'm34.analysis.unavailable': 'The analysis module is not running.',
    'm34.analysis.failed': 'The analysis failed: {error}',
    'm34.analysis.loading': 'Checking…',
    'm34.analysis.findings': 'Findings: {count}',
    'm34.analysis.clean': 'Nothing found.',
    'm34.analysis.hints': 'Model and provider',
    'm34.analysis.noHints': 'No specifics for the current connection.',
    'm34.analysis.open': 'Open the block',
    'm34.finding.neverIncluded': 'Never sent',
    'm34.finding.typeMismatch': 'Wrong types',
    'm34.finding.contradiction': 'Contradiction',
    'm34.finding.duplicateWithLore': 'Repeats the lore',
    'm34.finding.duplicateWithInjection': 'Repeats an extension injection',
    'm34.finding.duplicateBlock': 'Repeated block',
    'm34.finding.heavyBlock': 'Heavy block',
    'm34.finding.unsaved': 'Unsaved changes',
    'm34.finding.macroEngineOff': 'Macro engine',
    'm34.finding.modelQuirk': 'Model specifics',
    'm34.finding.emptyMessage': 'Empty message',

    'm34.layer.unavailable': 'The layer module is not running: edits go straight into the preset.',
    'm34.layer.modeLayer': 'Edits made in the studio go into your layer for «{base}».',
    'm34.layer.modeStore': 'Edits made in the studio go straight into the preset «{base}».',
    'm34.layer.editsToLayer': 'Keep my edits in my layer',
    'm34.layer.editsToLayerHint':
        'Your blocks and edits are kept apart from the base preset and laid over it, so a new version of the base (e.g. a Marinara update) does not wipe them.',
    'm34.layer.start': 'Start a layer for this preset',
    'm34.layer.startHint': 'From now on the studio’s edits go into the layer.',
    'm34.layer.started': 'Your edits to «{base}» now go into your layer.',
    'm34.layer.conflicts': 'Conflicts: {count}',
    'm34.layer.conflictsHint':
        'The base changed under your edit. Compare the old base, the new base and yours, and choose.',
    'm34.layer.oldBase': 'Old base',
    'm34.layer.newBase': 'New base (changes)',
    'm34.layer.mine': 'Mine (changes)',
    'm34.layer.keepMine': 'Keep mine',
    'm34.layer.takeNew': 'Take the new base',
    'm34.layer.custom': 'My own text…',
    'm34.layer.customTitle': 'Your text for the block',
    'm34.layer.customHint': 'This text goes into your layer instead of both versions.',
    'm34.layer.ops': 'Operations of your layer for «{base}»: {count}',
    'm34.layer.noOps': 'The layer is empty.',
    'm34.layer.openBlock': 'Open the block',
    'm34.layer.removeOp': 'Remove the operation',
    'm34.layer.removeTitle': 'Remove the operation',
    'm34.layer.removeBody':
        'Remove this operation from your layer? The working copy keeps the change until the preset is selected again.',
    'm34.layer.orphaned': 'Did not fit this base (block or anchor not found): {count}',
    'm34.layer.anchor.after': 'after «{name}»',
    'm34.layer.anchor.before': 'before «{name}»',
    'm34.layer.anchor.afterText': 'after the text «{text}»',
    'm34.layer.anchor.start': 'at the start',
    'm34.layer.anchor.end': 'at the end',
    'm34.layer.op.add': 'Your block «{name}» {anchor}',
    'm34.layer.op.edit': 'Edit of «{name}»: {fields}',
    'm34.layer.op.on': '«{name}» on',
    'm34.layer.op.off': '«{name}» off',
    'm34.layer.op.move': '«{name}» moved {anchor}',
    'm34.layer.op.key': '{key} = {value}',
    'm34.layer.migrateTitle': 'Move my edits into the layer',
    'm34.layer.migrateHint':
        'Pick the original base (e.g. a freshly imported Marinara). Everything the working copy of «{base}» does differently becomes operations of your layer.',
    'm34.layer.reference': 'Original base',
    'm34.layer.migrate': 'Move my edits into the layer',
    'm34.layer.migrateBody':
        'Compare the working copy of «{base}» with «{reference}» and keep the differences in your layer?',
    'm34.layer.migratePreview': 'Operations: {ops}, conflicts: {conflicts}, not fitting: {orphaned}.',
    'm34.layer.noReference': 'The preset «{name}» could not be read.',
    'm34.layer.transferTitle': 'Transfer to another preset',
    'm34.layer.transferHint': 'Your layer is copied onto another preset by anchors (e.g. «after </task>»).',
    'm34.layer.target': 'Target preset',
    'm34.layer.transfer': 'Transfer',
    'm34.layer.transferBody': 'Copy your layer of «{base}» onto «{target}»?',
    'm34.layer.report.migrate': 'Moved into the layer: {applied}. Conflicts: {conflicts}. Not fitting: {orphaned}.',
    'm34.layer.report.transfer': 'Transferred: {applied}. Conflicts: {conflicts}. Not fitting: {orphaned}.',
    'm34.layer.report.removed': 'Missing in your copy, switched off in the layer: {names}.',
    'm34.layer.foreignTitle': 'Blocks from another preset',
    'm34.layer.foreignHint':
        'Open someone else’s preset (e.g. Yablochny), pick blocks — they are added to your layer switched off.',
    'm34.layer.foreignPick': 'Open a preset file',
    'm34.layer.foreignFile': '«{file}»: blocks {count}',
    'm34.layer.foreignAdd': 'Add to my layer ({count})',
    'm34.layer.foreignClear': 'Close',
    'm34.layer.foreignInvalid': '«{file}» is not a preset.',
    'm34.layer.foreignAdded': 'Blocks added to your layer of «{base}»: {count} (switched off).',
    'm34.layer.workingTitle': 'Working copy',
    'm34.layer.reselect': 'Reselect the preset with the layer',
    'm34.layer.reselectHint':
        'Selects the preset again through SillyTavern, so your layer is laid over the saved base.',
    'm34.layer.reselectBody': 'Select the preset again with your layer on top?',
    'm34.layer.reselectDirty': 'The working copy has unsaved changes: selecting the preset again replaces them. Go on?',
    'm34.layer.reselected': 'Preset «{name}» selected again with your layer.',
    'm34.layer.prepareHint':
        'Before disabling Maestro: the layer lives in the working copy only while Maestro lays it over. Either go back to the plain base, or save base + layer as an ordinary preset.',
    'm34.layer.prepareBase': 'Back to the clean base',
    'm34.layer.prepareMerged': 'Save base + layer as a separate preset',
    'm34.layer.prepareTitle': 'Prepare for disabling',
    'm34.layer.prepareBaseBody': 'Select «{base}» again without your layer? Your layer stays in Maestro’s files.',
    'm34.layer.prepareMergedBody':
        'Save «{base}» with your layer as a separate ordinary preset and select it? It works without Maestro.',
    'm34.layer.prepared': 'Preset «{name}» selected.',

    'm34.versions.hint':
        'Versions of «{name}»: every save, the drafts SillyTavern would have dropped, saves made outside Maestro.',
    'm34.versions.refresh': 'Reload',
    'm34.versions.failed': 'Versions could not be read: {error}',
    'm34.versions.loading': 'Reading versions…',
    'm34.versions.empty': 'No versions yet: they appear with the first save.',
    'm34.versions.same': 'same as now',
    'm34.versions.counts': 'blocks {prompts}, order {order}, keys {keys}',
    'm34.versions.diffHint': 'What a rollback changes in the working copy:',
    'm34.versions.restore': 'Roll back to this version',
    'm34.versions.restoreTitle': 'Roll back',
    'm34.versions.restoreBody':
        'Write the version of {when} into «{name}» and load it? The current state stays as a version too.',
    'm34.versions.restored': '«{name}» rolled back.',
    'm34.versions.by.user': 'studio',
    'm34.versions.by.layer': 'layer',
    'm34.versions.by.import': 'import',
    'm34.versions.by.st': 'outside Maestro',
    'm34.versions.by.migration': 'migration',
    'm34.versions.by.draft': 'unsaved draft',
    'm34.versions.by.other': 'other',
    'm34.diff.same': 'No differences.',
    'm34.diff.blocks': 'Blocks',
    'm34.diff.added': 'added',
    'm34.diff.removed': 'removed',
    'm34.diff.changed': 'changed',
    'm34.diff.order': 'Order',
    'm34.diff.moved': 'Moved: {names}',
    'm34.diff.enabled': 'On: {names}',
    'm34.diff.disabled': 'Off: {names}',
    'm34.diff.orderAdded': 'Into the list: {names}',
    'm34.diff.orderRemoved': 'Out of the list: {names}',
    'm34.diff.keys': 'Keys',
    'm34.diff.sensitive': 'changed (secret value hidden)',

    'm34.params.hint':
        'Generation keys of this preset. Connection keys (source, model, proxy) stay in SillyTavern’s panel.',
    'm34.params.layerMode': 'Changes go into your layer too.',
    'm34.params.unset': 'not set',
    'm34.params.error.notNumber': '{key}: a number is expected.',
    'm34.params.error.range': '{key}: out of SillyTavern’s range.',
    'm34.params.error.option': '{key}: unknown value.',
    'm34.params.group.samplers': 'Samplers',
    'm34.params.group.context': 'Context and response',
    'm34.params.group.reasoning': 'Reasoning and tools',
    'm34.params.group.misc': 'Prompt behaviour, formats and utility prompts',
    'm34.params.key.temperature': 'Temperature',
    'm34.params.key.frequency_penalty': 'Frequency Penalty',
    'm34.params.key.presence_penalty': 'Presence Penalty',
    'm34.params.key.top_p': 'Top P',
    'm34.params.key.top_k': 'Top K',
    'm34.params.key.top_a': 'Top A',
    'm34.params.key.min_p': 'Min P',
    'm34.params.key.repetition_penalty': 'Repetition Penalty',
    'm34.params.key.seed': 'Seed',
    'm34.params.key.n': 'Multiple swipes per generation',
    'm34.params.key.openai_max_context': 'Context Size (tokens)',
    'm34.params.key.openai_max_tokens': 'Max Response Length (tokens)',
    'm34.params.key.max_context_unlocked': 'Unlocked Context Size',
    'm34.params.key.stream_openai': 'Streaming',
    'm34.params.key.show_thoughts': 'Request model reasoning',
    'm34.params.key.reasoning_effort': 'Reasoning Effort',
    'm34.params.key.verbosity': 'Verbosity',
    'm34.params.key.function_calling': 'Enable function calling',
    'm34.params.key.tool_call_recurse_limit': 'Tool calls recursion limit',
    'm34.params.key.enable_web_search': 'Enable web search',
    'm34.params.key.request_images': 'Request inline images',
    'm34.params.key.names_behavior': 'Character Names Behavior',
    'm34.params.key.squash_system_messages': 'Squash system messages',
    'm34.params.key.continue_prefill': 'Continue prefill',
    'm34.params.key.continue_postfix': 'Continue Postfix',
    'm34.params.key.use_sysprompt': 'Use system prompt',
    'm34.params.key.assistant_prefill': 'Assistant Prefill',
    'm34.params.key.assistant_impersonation': 'Assistant Impersonation Prefill',
    'm34.params.key.wi_format': 'World Info format template',
    'm34.params.key.scenario_format': 'Scenario format template',
    'm34.params.key.personality_format': 'Personality format template',
    'm34.params.key.impersonation_prompt': 'Impersonation prompt',
    'm34.params.key.new_chat_prompt': 'New Chat',
    'm34.params.key.new_group_chat_prompt': 'New Group Chat',
    'm34.params.key.new_example_chat_prompt': 'New Example Chat',
    'm34.params.key.continue_nudge_prompt': 'Continue nudge',
    'm34.params.key.group_nudge_prompt': 'Group nudge',
    'm34.params.key.send_if_empty': 'Replace empty message',
    'm34.params.opt.reasoning_effort.auto': 'Auto',
    'm34.params.opt.reasoning_effort.min': 'Minimum',
    'm34.params.opt.reasoning_effort.low': 'Low',
    'm34.params.opt.reasoning_effort.medium': 'Medium',
    'm34.params.opt.reasoning_effort.high': 'High',
    'm34.params.opt.reasoning_effort.max': 'Maximum',
    'm34.params.opt.verbosity.auto': 'Auto',
    'm34.params.opt.verbosity.low': 'Low',
    'm34.params.opt.verbosity.medium': 'Medium',
    'm34.params.opt.verbosity.high': 'High',
    'm34.params.opt.names_behavior.-1': 'None',
    'm34.params.opt.names_behavior.0': 'Default',
    'm34.params.opt.names_behavior.1': 'Completion Object',
    'm34.params.opt.names_behavior.2': 'Message Content',
    'm34.params.opt.continue_postfix.none': 'None',
    'm34.params.opt.continue_postfix.space': 'Space',
    'm34.params.opt.continue_postfix.newline': 'Newline',
    'm34.params.opt.continue_postfix.doubleNewline': 'Double Newline',

    'm34.launcher.open': 'Open the Preset Studio',
    'm34.launcher.hideClassic': 'Hide the classic editor',
    'm34.launcher.noPreset': '(no preset)',
    'm34.launcher.unsaved': 'unsaved',
    'm34.launcher.unsavedHint': 'The working copy differs from the saved preset; switching presets would drop it.',
    'm34.launcher.blocks': 'Blocks on: {enabled} of {total}',
    'm34.launcher.tokens': 'Total tokens: {count}',
    'm34.launcher.noTokens': 'tokens: after the first assembly',

    'm34.tab.intro':
        'The Preset Studio replaces the Prompt Manager section: the prompt map, blocks with search and drag, analysis, versions, and your layer that survives preset updates.',
    'm34.tab.preset': 'Preset: {name}',
    'm34.tab.settings': 'Replacing the Prompt Manager',
    'm34.tab.replace': 'Replace the Prompt Manager section with the Preset Studio',
    'm34.tab.replaceHint':
        'Prompt Manager is only hidden and keeps working for SillyTavern, commands and extensions; «Classic editor» shows it. Turn it on when the parity table is green.',
    'm34.tab.replaceActive': 'Prompt Manager is replaced by the Preset Studio button.',
    'm34.tab.replaceWaiting':
        'Waiting for the Prompt Manager section to appear (open the AI Response Configuration once).',
    'm34.tab.replaceInactive': 'Prompt Manager is shown as usual.',
    'm34.tab.replaceLater': 'The Prompt Manager section is not on the page yet: it is replaced as soon as it appears.',
    'm34.tab.textCompletion': 'Text Completion is active: the Preset Studio is for Chat Completion.',
    'm34.tab.slash': 'Command: /maestro-preset [block] opens the studio (on a block, by ID or name).',
    'm34.slash.help': 'Opens Maestro’s Preset Studio, on a block when given (ID or name).',
    'm34.slash.block': 'block ID or name',

    'm34.export.connection': 'With connection data, without secrets',
    'm34.map.estimated': 'Maestro’s own estimate (no Prompt Manager count for this block)',
    'm34.map.counted': 'Prompt Manager’s count of the last assembly',
    'm34.layer.migrateOk': 'Move into the layer',
    'm34.layer.previewBlocks': 'Block operations: {count}',
    'm34.layer.previewKeys': 'Body keys: {count}',
    'm34.layer.previewKeysHint':
        'Untick the keys that must not go into your layer. Connection keys (source, model, addresses) are unticked: a reference file should not pin your model.',
    'm34.layer.previewNone': 'none',
    'm34.layer.connectionKey': 'connection',
    'm34.save.layerIntro':
        'The changes of the working copy of «{base}» that are not in your layer become its operations.',
    'm34.scn.title': 'Parameters by scenario',
    'm34.scn.hint':
        'A scenario changes one kind of generation without switching the preset: response length, stop strings, reasoning and, if you want, its own message set.',
    'm34.scn.unavailable': 'The generation-scenario module is not running or offers no parameters.',
    'm34.scn.empty': 'No scenarios with parameters.',
    'm34.scn.reset': 'Defaults',
    'm34.scn.field.enabled': 'Take over this generation',
    'm34.scn.field.max_tokens': 'Max response length (tokens)',
    'm34.scn.field.temperature': 'Temperature',
    'm34.scn.field.historyMessages': 'Messages in {{history}}',
    'm34.scn.field.stop': 'Stop strings',
    'm34.scn.field.reasoning': 'Reasoning',
    'm34.scn.field.messages': 'Own message set',
    'm34.scn.stopPlaceholder': 'one per line',
    'm34.scn.stopHint':
        'One per line; a line break inside a stop string is written as \\n. {{char}} and {{user}} become the names. Empty: no stop strings.',
    'm34.scn.reasoning.keep': 'As in the connection',
    'm34.scn.reasoning.off': 'Off for this request',
    'm34.scn.messagesHint':
        'Empty: the preset’s prompt stays and only the parameters change. A message that is exactly {{history}} stands for the recent chat.',
    'm34.scn.addMessage': 'Add a message',
    'm34.scn.addHistory': 'Add {{history}}',
    'm34.scn.removeMessage': 'Remove the message',
    'm34.scn.role': 'Role of message {index}',
    'm34.scn.content': 'Text of message {index}',
};

const ru: Record<string, string> = {
    'm34.title': 'Пресет-студия',
    'm34.close': 'Закрыть',
    'm34.classic': 'Классический редактор',
    'm34.classicHint': 'Показать штатный Prompt Manager в панели «Настройка ответа ИИ» (до перезагрузки страницы)',
    'm34.nav.label': 'Разделы Пресет-студии',
    'm34.tab.map': 'Карта',
    'm34.tab.blocks': 'Блоки',
    'm34.tab.analysis': 'Анализ',
    'm34.tab.layer': 'Слой',
    'm34.tab.versions': 'Версии',
    'm34.tab.params': 'Параметры',

    'm34.error.generic': 'Пресет-студия: {error}',
    'm34.error.noStore':
        'Слой данных пресетов не запущен, поэтому Пресет-студия не открывается. Подробности — в журнале Maestro.',
    'm34.error.textCompletion':
        'Пресет-студия работает с Chat Completion. Для Text Completion пользуйся штатными панелями пресетов SillyTavern.',

    'm34.dialog.ok': 'ОК',
    'm34.dialog.cancel': 'Отмена',
    'm34.dialog.apply': 'Применить',
    'm34.dialog.delete': 'Удалить',
    'm34.dialog.save': 'Сохранить',

    'm34.role.system': 'Система',
    'm34.role.user': 'Пользователь',
    'm34.role.assistant': 'ИИ-ассистент',
    'm34.kind.inChat': 'Вставка в чат',
    'm34.kind.marker': 'Маркер (текст подставляет SillyTavern)',
    'm34.kind.important': 'Важный промпт (карточка не перезапишет)',
    'm34.kind.global': 'Глобальный промпт',
    'm34.kind.user': 'Промпт пресета',
    'm34.trigger.normal': 'Обычный',
    'm34.trigger.continue': 'Продолжить',
    'm34.trigger.impersonate': 'Перевоплощение',
    'm34.trigger.swipe': 'Свайп',
    'm34.trigger.regenerate': 'Повторная генерация',
    'm34.trigger.quiet': 'Тихая',
    'm34.source.charDescription': 'Описание персонажа',
    'm34.source.charPersonality': 'Личность персонажа',
    'm34.source.scenario': 'Сценарий персонажа',
    'm34.source.personaDescription': 'Описание персоны',
    'm34.source.worldInfoBefore': 'Информация о мире (↑ перс.)',
    'm34.source.worldInfoAfter': 'Информация о мире (↓ перс.)',

    'm34.header.preset': 'Пресет',
    'm34.header.actions': 'Действия с пресетом',
    'm34.header.unsaved': 'Не сохранено',
    'm34.header.pmError': 'Ошибка сборки',
    'm34.header.unsavedHint':
        'Рабочая копия отличается от сохранённого пресета: блоков — {prompts}, ключей — {keys}. При смене пресета SillyTavern это потеряет.',
    'm34.header.modeLayer': 'Правки → твой слой',
    'm34.header.modeLayerHint':
        'Правки студии сразу идут в твой слой для «{base}» и в рабочую копию; файл базы не меняется.',
    'm34.header.modeStore': 'Правки → пресет',
    'm34.header.modeStoreHint': 'Правки меняют рабочую копию; «Сохранить» записывает их в файл пресета.',
    'm34.header.save': 'Сохранить',
    'm34.header.saveHint': 'Записать рабочую копию в файл пресета (прежнее состояние останется версией)',
    'm34.header.saveLayer': 'Сохранить',
    'm34.header.saveLayerHint':
        'Правки студии уже в слое. Правки, сделанные в другом месте (классический редактор, команды), можно отправить в слой или в базу — на выбор.',
    'm34.header.saveBase': 'Сохранить базу',
    'm34.header.saveBaseHint': 'Записать рабочую копию без твоего слоя в файл базового пресета',
    'm34.header.saveAs': 'Сохранить пресет как…',
    'm34.header.rename': 'Переименовать пресет',
    'm34.header.import': 'Импортировать пресет',
    'm34.header.export': 'Экспортировать пресет',
    'm34.header.delete': 'Удалить пресет',

    'm34.switch.title': 'Есть несохранённые правки',
    'm34.switch.body':
        'В пресете «{from}» есть несохранённые правки. При переходе на «{to}» SillyTavern молча их сотрёт. Сохранить сначала?',
    'm34.switch.bodyLayer':
        'В пресете «{from}» есть правки вне твоего слоя. При переходе на «{to}» они пропадут. Перенести их в слой, сохранить в базу или отбросить?',
    'm34.switch.save': 'Сохранить',
    'm34.switch.saveLayer': 'В слой',
    'm34.switch.saveBase': 'В базу',
    'm34.switch.discard': 'Отбросить',
    'm34.leave.title': 'Блок не сохранён',
    'm34.leave.body': 'В блоке «{name}» есть несохранённые правки.',
    'm34.leave.save': 'Сохранить',
    'm34.leave.discard': 'Отбросить',

    'm34.save.summary': 'Сохранено в Пресет-студии',
    'm34.save.done': 'Пресет «{name}» сохранён.',
    'm34.save.inLayer': 'Твои правки уже в слое «{base}» — сохранять больше нечего.',
    'm34.save.layerTitle': 'Сохранить правки',
    'm34.save.layerBody':
        'В рабочей копии «{base}» есть правки, которых нет в твоём слое (классический редактор, команды, соседи). Перенести их в слой (переживут обновление базы) или записать в файл базы?',
    'm34.save.toLayer': 'Перенесено в слой «{base}»: {applied}. Конфликтов: {conflicts}.',
    'm34.saveBase.title': 'Сохранить базу',
    'm34.saveBase.body':
        'Рабочая копия без твоего слоя запишется в файл пресета «{base}». Слой останется отдельно и снова ляжет поверх базы.',
    'm34.saveBase.ok': 'Сохранить базу',
    'm34.saveAs.title': 'Сохранить пресет как',
    'm34.saveAs.hint': 'Совет: назови его как персонажа или группу, чтобы пресет привязался к их чатам.',
    'm34.saveAs.done': 'Сохранено как «{name}».',
    'm34.rename.title': 'Переименовать «{name}»',
    'm34.rename.hint': 'Профили подключения со старым именем студия предложит поправить.',
    'm34.rename.done': '«{from}» переименован в «{to}».',
    'm34.delete.title': 'Удалить пресет',
    'm34.delete.body':
        'Удалить пресет «{name}»? SillyTavern переключится на первый оставшийся. Версии удалённого пресета Maestro сохранит.',
    'm34.delete.done': 'Пресет «{name}» удалён.',
    'm34.import.title': 'Импорт пресета',
    'm34.import.dirty':
        'В текущем пресете есть несохранённые правки: импорт применит новый пресет, и они пропадут. Продолжить?',
    'm34.import.done': 'Пресет «{name}» импортирован и выбран.',
    'm34.export.title': 'Экспорт «{name}»',
    'm34.export.body':
        'Выгружается сохранённый пресет. Данные подключения и секретные ключи (прокси, адреса) по умолчанию не попадают в файл.',
    'm34.export.safe': 'Без данных подключения',
    'm34.export.all': 'Со всем (и с секретами)',

    'm34.blocks.search': 'Найти блок…',
    'm34.blocks.new': 'Новый блок',
    'm34.blocks.newName': 'Новый блок',
    'm34.blocks.copySuffix': 'копия',
    'm34.blocks.insert': 'Вставить блок (в начало, выключенным)',
    'm34.blocks.insertPick': 'Блоки вне списка…',
    'm34.blocks.importList': 'Импортировать список промптов',
    'm34.blocks.exportList': 'Экспортировать этот список промптов',
    'm34.blocks.resetOrder': 'Сбросить порядок к стандартному SillyTavern',
    'm34.blocks.enabled': 'Включено: {enabled} из {total}',
    'm34.blocks.tokens': 'Токенов: {count}',
    'm34.blocks.tokensHint': 'Токены блока (подсчёт Maestro или последняя сборка Prompt Manager)',
    'm34.blocks.toLayer': 'правки идут в твой слой',
    'm34.blocks.dragOff': 'Во время поиска порядок не меняется.',
    'm34.blocks.empty': 'Список промптов пуст.',
    'm34.blocks.noMatch': 'Ничего не найдено.',
    'm34.blocks.select': 'Выбрать «{name}»',
    'm34.blocks.drag': 'Перетащи, чтобы поменять порядок (с клавиатуры — Alt+↑/↓)',
    'm34.blocks.up': 'Выше',
    'm34.blocks.down': 'Ниже',
    'm34.blocks.enable': 'Включить',
    'm34.blocks.disable': 'Выключить',
    'm34.blocks.openHint': 'Править блок',
    'm34.blocks.viewHint': 'Показать блок (его заполняет SillyTavern)',
    'm34.blocks.missing': 'такого блока нет (осталась запись в порядке)',
    'm34.blocks.metaRelative': '{role} · по порядку',
    'm34.blocks.metaInChat': '{role} · в чате на глубине {depth}, порядок {order}',
    'm34.blocks.preview': 'Предпросмотр',
    'm34.blocks.duplicate': 'Дублировать',
    'm34.blocks.detach': 'Убрать из списка (блок останется)',
    'm34.blocks.delete': 'Удалить блок',
    'm34.blocks.conflict': 'конфликт',
    'm34.blocks.inLayer': 'в слое',
    'm34.blocks.overridden': 'карточка',
    'm34.blocks.overriddenHint': 'В последней сборке этот блок заменила карточка персонажа',
    'm34.blocks.types': 'типы',
    'm34.blocks.typesHint':
        'Записан с типами, которые SillyTavern не принимает (глубина строкой, незнакомая роль, нет system_prompt=false): блок может не уйти в промпт. Сохранение в редакторе исправит типы.',
    'm34.blocks.markerPreview': 'Маркер: сюда SillyTavern подставит свой текст при сборке промпта.',
    'm34.blocks.emptyText': 'Блок пуст.',
    'm34.blocks.substitute': 'Подставить макросы',
    'm34.blocks.substituted': 'С подставленными макросами (как сейчас, для текущего чата):',
    'm34.blocks.effectsTitle': 'Макросы с побочными действиями',
    'm34.blocks.effectsBody':
        'В блоке есть {macros}: подстановка выполнит их и изменит переменные чата, как при настоящей генерации. Всё равно подставить?',
    'm34.blocks.deleteTitle': 'Удалить блок',
    'm34.blocks.deleteBody': 'Удалить блок «{name}»? Отменить можно из журнала Maestro.',
    'm34.blocks.deleteLayerBody':
        'Удалить блок «{name}»? Блок, добавленный в твоём слое, удалится вместе с его операциями. Блок базы слой удалить не может — он будет выключен в слое.',
    'm34.blocks.disabledInLayer': '«{name}» — блок базового пресета: в слое он выключен.',
    'm34.blocks.resetTitle': 'Сбросить порядок',
    'm34.blocks.resetBody':
        'Вернуть список к стандартному порядку SillyTavern? Твои блоки уйдут из списка, но не удалятся (их можно вставить снова из «Блоков вне списка»).',
    'm34.blocks.resetBodyKeep':
        'Вернуть стандартные блоки к порядку и состоянию SillyTavern по умолчанию? Твои блоки останутся после них.',
    'm34.bulk.title': 'Выбранные блоки',
    'm34.bulk.selected': 'Выбрано: {count}',
    'm34.bulk.selectAll': 'Выбрать все показанные',
    'm34.bulk.clear': 'Снять выбор',
    'm34.bulk.enable': 'Включить',
    'm34.bulk.disable': 'Выключить',

    'm34.list.importTitle': 'Импорт списка промптов',
    'm34.list.importBody': 'Блоки с тем же ID будут перезаписаны. Продолжить?',
    'm34.list.imported': 'Список промптов импортирован: обновлено — {updated}, добавлено — {added}.',
    'm34.list.invalid.json': '«{file}» — не JSON.',
    'm34.list.invalid.shape': '«{file}» — не список промптов (нужны version, type, data.prompts).',

    'm34.editor.panel': 'Редактор блока',
    'm34.editor.title': 'Блок «{name}»',
    'm34.editor.newTitle': 'Новый блок',
    'm34.editor.identifier': 'ID: {id}',
    'm34.editor.close': 'Закрыть',
    'm34.editor.save': 'Сохранить',
    'm34.editor.reset': 'Сброс',
    'm34.editor.resetHint':
        'Подставить в форму стандартные имя и текст SillyTavern (записывается только по «Сохранить»)',
    'm34.editor.name': 'Имя',
    'm34.editor.role': 'Роль',
    'm34.editor.roleHint': 'От чьего лица будет отправляться сообщение.',
    'm34.editor.position': 'Точка инжекта',
    'm34.editor.relative': 'Относительная',
    'm34.editor.inChat': 'На глубине в чате',
    'm34.editor.depth': 'Глубина',
    'm34.editor.depthHint': '0 — после последнего сообщения, 1 — перед последним сообщением и т. д.',
    'm34.editor.order': 'Порядок',
    'm34.editor.orderHint':
        'Меньше — выше. Вставки других источников (лор, заметка автора) имеют порядок 100 и склеиваются с блоками порядка 100 той же глубины и роли.',
    'm34.editor.triggers': 'Триггеры',
    'm34.editor.triggersHint': 'Ничего не отмечено — любой тип генерации.',
    'm34.editor.forbid': 'Запретить перезапись (карточка персонажа не сможет заменить этот промпт)',
    'm34.editor.source': 'Источник: {source}',
    'm34.editor.content': 'Промпт',
    'm34.editor.tokens': '≈ {count} ток.',
    'm34.editor.highlight': 'Макросы и флаги',
    'm34.editor.flags': 'Флаги Maestro: {flags}',
    'm34.editor.sideEffects': 'При вычислении меняет переменные: {macros}',
    'm34.editor.keys': 'Ctrl+S — сохранить',
    'm34.editor.layerMode': 'Сохранение отправит правку в твой слой и в рабочую копию.',
    'm34.editor.readOnly': 'Этот маркер заполняет и настраивает сам SillyTavern: правке не подлежит.',
    'm34.editor.markerText':
        'Маркер: текст подставляет SillyTavern. Менять можно роль, точку инжекта, глубину, порядок и триггеры.',
    'm34.editor.types':
        'Записан с чужими типами ({fields}); при сохранении запишутся типы, которые понимает SillyTavern.',
    'm34.editor.stale': 'Пока ты правил блок, пресет сменился. Сохранение запишет в блок выбранного сейчас пресета.',
    'm34.editor.missing': 'Блока {id} в этом пресете больше нет.',
    'm34.editor.added': 'Блок «{name}» добавлен и включён.',
    'm34.editor.changedTitle': 'Блок изменили',
    'm34.editor.changedBody':
        'Пока блок «{name}» был открыт, его изменили вне студии (классический редактор, команда или расширение). Записать твои поля поверх?',
    'm34.editor.overwrite': 'Записать мои поля',

    'm34.map.total': 'Уходит: ≈ {count} ток.',
    'm34.map.hint': 'Как SillyTavern соберёт промпт из этого пресета — по порядку.',
    'm34.map.type': 'Генерация',
    'm34.map.refresh': 'Пересчитать',
    'm34.map.reduced':
        'Модуль анализа не запущен: карта показывает только порядок и последние счётчики Prompt Manager.',
    'm34.map.failed': 'Карту построить не удалось: {error}',
    'm34.map.loading': 'Строю карту…',
    'm34.map.empty': 'Показывать нечего.',
    'm34.map.relative': 'по порядку',
    'm34.map.depth': 'в чате, глубина {depth}, порядок {order}',
    'm34.map.marker': 'маркер',
    'm34.map.off': 'выкл.',
    'm34.map.open': 'Открыть блок',
    'm34.map.triggersHint': 'Только для этих типов генерации',
    'm34.map.injections': 'Вставки расширений здесь',
    'm34.map.injection': '{owner}: {key} (≈ {count})',
    'm34.map.where.start': 'перед текстом',
    'm34.map.where.end': 'после текста',
    'm34.map.where.chat': 'в чате на глубине {depth}',
    'm34.map.dropped': 'Не уйдёт: {reason}',

    'm34.analysis.hint': 'Что может пойти не так: блоки, которые не уходят, ловушки, повторы, тяжёлые блоки.',
    'm34.analysis.refresh': 'Проверить заново',
    'm34.analysis.unavailable': 'Модуль анализа не запущен.',
    'm34.analysis.failed': 'Анализ не удался: {error}',
    'm34.analysis.loading': 'Проверяю…',
    'm34.analysis.findings': 'Находки: {count}',
    'm34.analysis.clean': 'Ничего не найдено.',
    'm34.analysis.hints': 'Модель и провайдер',
    'm34.analysis.noHints': 'Для текущего подключения особенностей нет.',
    'm34.analysis.open': 'Открыть блок',
    'm34.finding.neverIncluded': 'Не уходит в промпт',
    'm34.finding.typeMismatch': 'Неверные типы',
    'm34.finding.contradiction': 'Противоречие',
    'm34.finding.duplicateWithLore': 'Повтор с лором',
    'm34.finding.duplicateWithInjection': 'Повтор со вставкой расширения',
    'm34.finding.duplicateBlock': 'Повтор блока',
    'm34.finding.heavyBlock': 'Тяжёлый блок',
    'm34.finding.unsaved': 'Несохранённые правки',
    'm34.finding.macroEngineOff': 'Движок макросов',
    'm34.finding.modelQuirk': 'Особенность модели',
    'm34.finding.emptyMessage': 'Пустое сообщение',

    'm34.layer.unavailable': 'Модуль слоя не запущен: правки идут прямо в пресет.',
    'm34.layer.modeLayer': 'Правки студии идут в твой слой для «{base}».',
    'm34.layer.modeStore': 'Правки студии идут прямо в пресет «{base}».',
    'm34.layer.editsToLayer': 'Держать мои правки в моём слое',
    'm34.layer.editsToLayerHint':
        'Твои блоки и правки хранятся отдельно от базового пресета и накладываются поверх, поэтому новая версия базы (например, обновление Marinara) их не сотрёт.',
    'm34.layer.start': 'Завести слой для этого пресета',
    'm34.layer.startHint': 'Дальше правки студии пойдут в слой.',
    'm34.layer.started': 'Теперь правки «{base}» идут в твой слой.',
    'm34.layer.conflicts': 'Конфликты: {count}',
    'm34.layer.conflictsHint': 'База изменилась под твоей правкой. Сравни старую базу, новую и свою — и выбери.',
    'm34.layer.oldBase': 'Старая база',
    'm34.layer.newBase': 'Новая база (изменения)',
    'm34.layer.mine': 'Моё (изменения)',
    'm34.layer.keepMine': 'Оставить моё',
    'm34.layer.takeNew': 'Взять новую базу',
    'm34.layer.custom': 'Своя версия…',
    'm34.layer.customTitle': 'Твой текст блока',
    'm34.layer.customHint': 'Этот текст ляжет в слой вместо обеих версий.',
    'm34.layer.ops': 'Операции слоя «{base}»: {count}',
    'm34.layer.noOps': 'Слой пуст.',
    'm34.layer.openBlock': 'Открыть блок',
    'm34.layer.removeOp': 'Убрать операцию',
    'm34.layer.removeTitle': 'Убрать операцию',
    'm34.layer.removeBody':
        'Убрать эту операцию из слоя? Рабочая копия сохранит изменение, пока пресет не будет выбран заново.',
    'm34.layer.orphaned': 'Не легли на эту базу (нет блока или якоря): {count}',
    'm34.layer.anchor.after': 'после «{name}»',
    'm34.layer.anchor.before': 'перед «{name}»',
    'm34.layer.anchor.afterText': 'после текста «{text}»',
    'm34.layer.anchor.start': 'в начало',
    'm34.layer.anchor.end': 'в конец',
    'm34.layer.op.add': 'Свой блок «{name}» {anchor}',
    'm34.layer.op.edit': 'Правка «{name}»: {fields}',
    'm34.layer.op.on': '«{name}» включён',
    'm34.layer.op.off': '«{name}» выключен',
    'm34.layer.op.move': '«{name}» перемещён {anchor}',
    'm34.layer.op.key': '{key} = {value}',
    'm34.layer.migrateTitle': 'Перенести мои правки в слой',
    'm34.layer.migrateHint':
        'Выбери исходную базу (например, только что импортированную Marinara). Всё, чем рабочая копия «{base}» от неё отличается, станет операциями твоего слоя.',
    'm34.layer.reference': 'Исходная база',
    'm34.layer.migrate': 'Перенести мои правки в слой',
    'm34.layer.migrateBody': 'Сравнить рабочую копию «{base}» с «{reference}» и сохранить различия в твоём слое?',
    'm34.layer.migratePreview': 'Операций: {ops}, конфликтов: {conflicts}, не ложится: {orphaned}.',
    'm34.layer.noReference': 'Пресет «{name}» прочитать не удалось.',
    'm34.layer.transferTitle': 'Перенос на другой пресет',
    'm34.layer.transferHint': 'Слой копируется на другой пресет по якорям (например, «после </task>»).',
    'm34.layer.target': 'Пресет, куда переносить',
    'm34.layer.transfer': 'Перенести',
    'm34.layer.transferBody': 'Скопировать твой слой «{base}» на «{target}»?',
    'm34.layer.report.migrate': 'Перенесено в слой: {applied}. Конфликтов: {conflicts}. Не легло: {orphaned}.',
    'm34.layer.report.transfer': 'Перенесено: {applied}. Конфликтов: {conflicts}. Не легло: {orphaned}.',
    'm34.layer.report.removed': 'В твоей копии их нет — в слое выключены: {names}.',
    'm34.layer.foreignTitle': 'Блоки из чужого пресета',
    'm34.layer.foreignHint':
        'Открой чужой пресет (например, Yablochny) и отметь блоки — они добавятся в твой слой выключенными.',
    'm34.layer.foreignPick': 'Открыть файл пресета',
    'm34.layer.foreignFile': '«{file}»: блоков — {count}',
    'm34.layer.foreignAdd': 'Добавить в мой слой ({count})',
    'm34.layer.foreignClear': 'Закрыть',
    'm34.layer.foreignInvalid': '«{file}» — не пресет.',
    'm34.layer.foreignAdded': 'В слой «{base}» добавлено блоков: {count} (выключены).',
    'm34.layer.workingTitle': 'Рабочая копия',
    'm34.layer.reselect': 'Перевыбрать пресет со слоем',
    'm34.layer.reselectHint': 'Пресет выбирается заново через SillyTavern, и слой ложится поверх сохранённой базы.',
    'm34.layer.reselectBody': 'Выбрать пресет заново с твоим слоем сверху?',
    'm34.layer.reselectDirty':
        'В рабочей копии есть несохранённые правки: повторный выбор пресета их заменит. Продолжить?',
    'm34.layer.reselected': 'Пресет «{name}» выбран заново со слоем.',
    'm34.layer.prepareHint':
        'Перед отключением Maestro: слой живёт в рабочей копии, только пока Maestro его накладывает. Вернись к чистой базе или сохрани базу со слоем обычным пресетом.',
    'm34.layer.prepareBase': 'Вернуть чистую базу',
    'm34.layer.prepareMerged': 'Сохранить базу со слоем как отдельный пресет',
    'm34.layer.prepareTitle': 'Подготовить к отключению',
    'm34.layer.prepareBaseBody': 'Выбрать «{base}» заново без слоя? Сам слой останется в файлах Maestro.',
    'm34.layer.prepareMergedBody':
        'Сохранить «{base}» вместе со слоем отдельным обычным пресетом и выбрать его? Он работает и без Maestro.',
    'm34.layer.prepared': 'Выбран пресет «{name}».',

    'm34.versions.hint':
        'Версии «{name}»: каждое сохранение, черновики, которые SillyTavern стёр бы, и сохранения в обход Maestro.',
    'm34.versions.refresh': 'Обновить',
    'm34.versions.failed': 'Версии прочитать не удалось: {error}',
    'm34.versions.loading': 'Читаю версии…',
    'm34.versions.empty': 'Версий пока нет: они появятся с первым сохранением.',
    'm34.versions.same': 'как сейчас',
    'm34.versions.counts': 'блоки {prompts}, порядок {order}, ключи {keys}',
    'm34.versions.diffHint': 'Что изменится в рабочей копии при откате:',
    'm34.versions.restore': 'Откатить к этой версии',
    'm34.versions.restoreTitle': 'Откат',
    'm34.versions.restoreBody':
        'Записать версию от {when} в «{name}» и загрузить её? Текущее состояние тоже останется версией.',
    'm34.versions.restored': '«{name}» откачен.',
    'm34.versions.by.user': 'студия',
    'm34.versions.by.layer': 'слой',
    'm34.versions.by.import': 'импорт',
    'm34.versions.by.st': 'вне Maestro',
    'm34.versions.by.migration': 'перенос',
    'm34.versions.by.draft': 'несохранённый черновик',
    'm34.versions.by.other': 'другое',
    'm34.diff.same': 'Различий нет.',
    'm34.diff.blocks': 'Блоки',
    'm34.diff.added': 'добавлен',
    'm34.diff.removed': 'удалён',
    'm34.diff.changed': 'изменён',
    'm34.diff.order': 'Порядок',
    'm34.diff.moved': 'Перемещены: {names}',
    'm34.diff.enabled': 'Включены: {names}',
    'm34.diff.disabled': 'Выключены: {names}',
    'm34.diff.orderAdded': 'В списке: {names}',
    'm34.diff.orderRemoved': 'Вне списка: {names}',
    'm34.diff.keys': 'Ключи',
    'm34.diff.sensitive': 'изменён (секретное значение скрыто)',

    'm34.params.hint':
        'Ключи генерации этого пресета. Ключи подключения (источник, модель, прокси) остаются в панели SillyTavern.',
    'm34.params.layerMode': 'Изменения пойдут и в твой слой.',
    'm34.params.unset': 'не задано',
    'm34.params.error.notNumber': '{key}: нужно число.',
    'm34.params.error.range': '{key}: вне допустимого в SillyTavern диапазона.',
    'm34.params.error.option': '{key}: незнакомое значение.',
    'm34.params.group.samplers': 'Сэмплеры',
    'm34.params.group.context': 'Контекст и ответ',
    'm34.params.group.reasoning': 'Рассуждения и инструменты',
    'm34.params.group.misc': 'Поведение промпта, форматы и служебные промпты',
    'm34.params.key.temperature': 'Температура',
    'm34.params.key.frequency_penalty': 'Штраф за частоту',
    'm34.params.key.presence_penalty': 'Штраф за присутствие',
    'm34.params.key.top_p': 'Top P',
    'm34.params.key.top_k': 'Top K',
    'm34.params.key.top_a': 'Top A',
    'm34.params.key.min_p': 'Min P',
    'm34.params.key.repetition_penalty': 'Штраф за повторы',
    'm34.params.key.seed': 'Зерно',
    'm34.params.key.n': 'Несколько свайпов на генерацию',
    'm34.params.key.openai_max_context': 'Размер контекста (в токенах)',
    'm34.params.key.openai_max_tokens': 'Макс. длина ответа (в токенах)',
    'm34.params.key.max_context_unlocked': 'Неограниченный размер контекста',
    'm34.params.key.stream_openai': 'Стриминг текста',
    'm34.params.key.show_thoughts': 'Запрашивать рассуждения',
    'm34.params.key.reasoning_effort': 'Рассуждения',
    'm34.params.key.verbosity': 'Подробность ответа',
    'm34.params.key.function_calling': 'Включить функции',
    'm34.params.key.tool_call_recurse_limit': 'Предел цепочки вызовов инструментов',
    'm34.params.key.enable_web_search': 'Включить поиск в Интернете',
    'm34.params.key.request_images': 'Запрашивать inline-изображения',
    'm34.params.key.names_behavior': 'Вставка имени персонажа',
    'm34.params.key.squash_system_messages': 'Склеивать сообщения системы',
    'm34.params.key.continue_prefill': 'Префилл для продолжения',
    'm34.params.key.continue_postfix': 'Постфикс для продолжения',
    'm34.params.key.use_sysprompt': 'Включить системный промпт',
    'm34.params.key.assistant_prefill': 'Префилл для ассистента',
    'm34.params.key.assistant_impersonation': 'Префилл для ассистента при перевоплощении',
    'm34.params.key.wi_format': 'Шаблон информации о мире',
    'm34.params.key.scenario_format': 'Шаблон сценария',
    'm34.params.key.personality_format': 'Шаблон личности',
    'm34.params.key.impersonation_prompt': 'Промпт для перевоплощения',
    'm34.params.key.new_chat_prompt': 'Новый чат',
    'm34.params.key.new_group_chat_prompt': 'Новый групповой чат',
    'm34.params.key.new_example_chat_prompt': 'Новый образец чата',
    'm34.params.key.continue_nudge_prompt': 'Подсказка для продолжения',
    'm34.params.key.group_nudge_prompt': 'Подсказка для группы',
    'm34.params.key.send_if_empty': 'Заменять пустые сообщения',
    'm34.params.opt.reasoning_effort.auto': 'Авто',
    'm34.params.opt.reasoning_effort.min': 'Минимальные',
    'm34.params.opt.reasoning_effort.low': 'Низкие',
    'm34.params.opt.reasoning_effort.medium': 'Средние',
    'm34.params.opt.reasoning_effort.high': 'Высокие',
    'm34.params.opt.reasoning_effort.max': 'Максимальные',
    'm34.params.opt.verbosity.auto': 'Авто',
    'm34.params.opt.verbosity.low': 'Низкая',
    'm34.params.opt.verbosity.medium': 'Средняя',
    'm34.params.opt.verbosity.high': 'Высокая',
    'm34.params.opt.names_behavior.-1': 'Отсутствует',
    'm34.params.opt.names_behavior.0': 'По умолчанию',
    'm34.params.opt.names_behavior.1': 'Как часть Completion Object',
    'm34.params.opt.names_behavior.2': 'Внутри сообщения',
    'm34.params.opt.continue_postfix.none': 'Отсутствует',
    'm34.params.opt.continue_postfix.space': 'Пробел',
    'm34.params.opt.continue_postfix.newline': 'Новая строка',
    'm34.params.opt.continue_postfix.doubleNewline': 'Две новые строки',

    'm34.launcher.open': 'Открыть Пресет-студию',
    'm34.launcher.hideClassic': 'Скрыть классический редактор',
    'm34.launcher.noPreset': '(пресет не выбран)',
    'm34.launcher.unsaved': 'не сохранено',
    'm34.launcher.unsavedHint': 'Рабочая копия отличается от сохранённого пресета; при смене пресета это пропадёт.',
    'm34.launcher.blocks': 'Включено блоков: {enabled} из {total}',
    'm34.launcher.tokens': 'Всего токенов: {count}',
    'm34.launcher.noTokens': 'токены — после первой сборки',

    'm34.tab.intro':
        'Пресет-студия заменяет раздел Prompt Manager: карта промпта, блоки с поиском и перетаскиванием, анализ, версии и твой слой, который переживает обновления пресета.',
    'm34.tab.preset': 'Пресет: {name}',
    'm34.tab.settings': 'Замена Prompt Manager',
    'm34.tab.replace': 'Заменить раздел Prompt Manager Пресет-студией',
    'm34.tab.replaceHint':
        'Prompt Manager только скрывается и продолжает работать для SillyTavern, команд и расширений; «Классический редактор» его показывает. Включай, когда таблица паритета зелёная.',
    'm34.tab.replaceActive': 'Вместо Prompt Manager — кнопка Пресет-студии.',
    'm34.tab.replaceWaiting': 'Жду, когда появится раздел Prompt Manager (открой «Настройка ответа ИИ» хотя бы раз).',
    'm34.tab.replaceInactive': 'Prompt Manager показывается как обычно.',
    'm34.tab.replaceLater': 'Раздела Prompt Manager на странице пока нет: замена произойдёт, как только он появится.',
    'm34.tab.textCompletion': 'Включён Text Completion: Пресет-студия рассчитана на Chat Completion.',
    'm34.tab.slash': 'Команда /maestro-preset [блок] открывает студию (на блоке — по ID или имени).',
    'm34.slash.help': 'Открывает Пресет-студию Maestro — на блоке, если он указан (ID или имя).',
    'm34.slash.block': 'ID или имя блока',

    'm34.export.connection': 'С данными подключения, без секретов',
    'm34.map.estimated': 'Оценка Maestro (для этого блока у Prompt Manager нет счётчика)',
    'm34.map.counted': 'Счётчик Prompt Manager по последней сборке',
    'm34.layer.migrateOk': 'Перенести в слой',
    'm34.layer.previewBlocks': 'Операции с блоками: {count}',
    'm34.layer.previewKeys': 'Ключи тела: {count}',
    'm34.layer.previewKeysHint':
        'Сними галочки с ключей, которым не место в твоём слое. Ключи подключения (источник, модель, адреса) уже сняты: файл-образец не должен закреплять модель.',
    'm34.layer.previewNone': 'нет',
    'm34.layer.connectionKey': 'подключение',
    'm34.save.layerIntro': 'Правки рабочей копии «{base}», которых нет в твоём слое, станут его операциями.',
    'm34.scn.title': 'Параметры по сценариям',
    'm34.scn.hint':
        'Сценарий меняет один вид генерации, не переключая пресет: длину ответа, стоп-строки, рассуждения и, если нужно, свой набор сообщений.',
    'm34.scn.unavailable': 'Модуль сценариев генерации не запущен или не даёт настроек.',
    'm34.scn.empty': 'Сценариев с параметрами нет.',
    'm34.scn.reset': 'По умолчанию',
    'm34.scn.field.enabled': 'Перехватывать эту генерацию',
    'm34.scn.field.max_tokens': 'Макс. длина ответа (в токенах)',
    'm34.scn.field.temperature': 'Температура',
    'm34.scn.field.historyMessages': 'Сообщений в {{history}}',
    'm34.scn.field.stop': 'Стоп-строки',
    'm34.scn.field.reasoning': 'Рассуждения',
    'm34.scn.field.messages': 'Свой набор сообщений',
    'm34.scn.stopPlaceholder': 'по одной на строку',
    'm34.scn.stopHint':
        'По одной на строку; перевод строки внутри стоп-строки пиши как \\n. {{char}} и {{user}} заменятся именами. Пусто — без стоп-строк.',
    'm34.scn.reasoning.keep': 'Как в подключении',
    'm34.scn.reasoning.off': 'Выключить для этого запроса',
    'm34.scn.messagesHint':
        'Пусто — промпт пресета остаётся, меняются только параметры. Сообщение ровно {{history}} заменяется последними сообщениями чата.',
    'm34.scn.addMessage': 'Добавить сообщение',
    'm34.scn.addHistory': 'Добавить {{history}}',
    'm34.scn.removeMessage': 'Убрать сообщение',
    'm34.scn.role': 'Роль сообщения {index}',
    'm34.scn.content': 'Текст сообщения {index}',
};

export const M34_STRINGS: I18nParts = { en, ru };
