// Strings of M35 «Роли книг» (`m35r.*`). Russian is the primary UI language; the user is addressed as «ты».
import type { I18nParts } from '../../shared/contracts';

export const BOOK_ROLES_STRINGS: I18nParts = {
    en: {
        'm35r.title': 'Book roles',
        'm35r.role.bunnymo.core': 'BunnyMo core',
        'm35r.role.bunnymo.pack': 'BunnyMo pack',
        'm35r.role.ck.archive': 'Character archive',
        'm35r.role.world': 'World',
        'm35r.role.card': 'Card book',
        'm35r.role.npc': 'NPC book',
        'm35r.role.canon': 'Chat canon',
        'm35r.role.maestro': 'Maestro book',
        'm35r.role.chat': 'Chat book',
        'm35r.role.persona': 'Persona book',
        'm35r.role.backup': 'Backup copy',
        'm35r.role.unknown': 'Not recognised yet',
        'm35r.source.auto': 'detected',
        'm35r.source.user': 'set by you',
        'm35r.readOnly': 'Read-only: BunnyMo books are never edited',
        'm35r.journal.set': 'Role of «{book}»: {role}',
        'm35r.journal.reset': 'Role of «{book}» is detected again: {role}',
        'm35r.error.noBook': 'Lorebook «{book}» could not be read.',
        'm35r.error.noEntry': 'Lorebook «{book}» has no entry {uid}.',
    },
    ru: {
        'm35r.title': 'Роли книг',
        'm35r.role.bunnymo.core': 'Ядро BunnyMo',
        'm35r.role.bunnymo.pack': 'Пак BunnyMo',
        'm35r.role.ck.archive': 'Архив персонажей',
        'm35r.role.world': 'Мир',
        'm35r.role.card': 'Книга карточки',
        'm35r.role.npc': 'Книга NPC',
        'm35r.role.canon': 'Канон чата',
        'm35r.role.maestro': 'Книга Maestro',
        'm35r.role.chat': 'Книга чата',
        'm35r.role.persona': 'Книга персоны',
        'm35r.role.backup': 'Резервная копия',
        'm35r.role.unknown': 'Ещё не распознана',
        'm35r.source.auto': 'определена сама',
        'm35r.source.user': 'задана тобой',
        'm35r.readOnly': 'Только чтение: книги BunnyMo не правятся',
        'm35r.journal.set': 'Роль книги «{book}»: {role}',
        'm35r.journal.reset': 'Роль книги «{book}» снова определяется сама: {role}',
        'm35r.error.noBook': 'Не удалось прочитать лорбук «{book}».',
        'm35r.error.noEntry': 'В лорбуке «{book}» нет записи {uid}.',
    },
};
