// Strings of M41 «Персона для персонажа» (en + ru).
import type { I18nParts } from '../../shared/contracts';

export const PERSONA_CREATOR_STRINGS: I18nParts = {
    en: {
        'm41.title': 'Persona for a character',
        'm41.profileTask': 'Persona for a character',
        'm41.button.title': "Create the player's persona for this character",
        'm41.option': 'Create a persona',
        'm41.noCard': 'Open the card of one character (not a group)',
        'm41.noWindow': 'SillyTavern could not open the window',
        'm41.busy': 'Already making a persona for «{name}»',
        'm41.slash.help': 'Make your persona for the character of this chat: /maestro-persona [who you want to be]',
        'm41.slash.value': 'who you want to be (optional)',
        'm41.slash.noCard': 'Open a chat with one character',

        'm41.dialog.title': 'Persona for «{name}»',
        'm41.dialog.intro':
            'Maestro reads the card, the scenario, the starting scene and the lorebook and makes up your character: the look, a background and 5–6 outfits.',
        'm41.dialog.comment': 'Who do you want to be?',
        'm41.dialog.commentHint': 'For example: a mercenary from the north who has long known Vera',
        'm41.dialog.commentHelp': 'You may leave it empty: then Maestro decides by the card.',

        'm41.opt.passport': 'NAI passport',
        'm41.opt.passportHint': 'The look and the outfits for NAI Studio pictures',
        'm41.opt.picture': 'Picture (free)',
        'm41.opt.pictureHint': 'The persona avatar, drawn by NAI Studio from the passport',
        'm41.opt.link': 'Link to «{name}»',
        'm41.opt.linkHint': 'SillyTavern offers this persona when you open the character',
        'm41.opt.current': 'Make it current in this chat',
        'm41.opt.currentHint': 'Switch the chat to the new persona right away',
        'm41.nai.absent': 'The passport and the picture are made by NAI Studio: it is not installed or is off.',
        'm41.nai.old': 'The passport and the picture need a newer NAI Studio (passports for any persona).',

        'm41.action.think': 'Make up',
        'm41.action.cancel': 'Cancel',
        'm41.action.stop': 'Stop',
        'm41.action.create': 'Create',
        'm41.action.again': 'Once more',
        'm41.action.hide': 'Hide',
        'm41.action.makeCurrent': 'Make current',
        'm41.action.isCurrent': 'Current',
        'm41.action.openPersonas': 'Open personas',
        'm41.action.done': 'Done',
        'm41.action.removeOutfit': 'Remove the outfit',

        'm41.phase.reading': 'Reading the card and the lore…',
        'm41.phase.thinking': 'Making up the persona…',
        'm41.phase.retry': 'The answer did not fit, asking once more…',
        'm41.phase.wait': 'It usually takes up to a minute.',

        'm41.review.name': 'Name',
        'm41.review.title': 'Title',
        'm41.review.description': 'Description for SillyTavern',
        'm41.review.descriptionHint':
            'This text becomes the persona description. The «Гардероб» line follows the list of outfits.',
        'm41.review.outfits': 'Outfits: {count}',
        'm41.review.outfitsHint': 'Name, what it is made of, and the tags NovelAI draws it by.',
        'm41.review.outfitName': 'Outfit name',
        'm41.review.outfitWording': 'What it is made of',
        'm41.review.outfitTags': 'Tags for NovelAI',
        'm41.review.comment': 'Comment for «Once more»',
        'm41.review.lore': 'Lore entries read: {picked} of {total}',
        'm41.review.noLore': 'The card has no lorebook entries',
        'm41.review.noName': 'Give the persona a name',

        'm41.creating.title': 'Creating «{name}»',
        'm41.done.title': 'Persona «{name}» is ready',
        'm41.done.partial': 'Persona «{name}» is created, but not everything worked',
        'm41.done.failed': 'The persona was not created',
        'm41.done.noUndo': "There is no undo: an unneeded persona is deleted in SillyTavern's persona window.",

        'm41.step.persona': 'Persona in SillyTavern',
        'm41.step.avatar': 'Default avatar',
        'm41.step.link': 'Link to «{name}»',
        'm41.step.passport': 'NAI passport',
        'm41.step.picture': 'Picture',
        'm41.step.current': 'Current persona',

        'm41.detail.notChosen': 'not chosen',
        'm41.detail.naiAbsent': 'NAI Studio is not installed or is off',
        'm41.detail.naiOld': 'needs a newer NAI Studio',
        'm41.detail.noPassport': 'no passport to draw from',
        'm41.detail.passportFailed': 'NAI Studio made no passport: {reason}',
        'm41.detail.passportNotSaved': 'NAI Studio did not save the passport',
        'm41.detail.outfits.one': '{count} outfit',
        'm41.detail.outfits.few': '{count} outfits',
        'm41.detail.outfits.many': '{count} outfits',
        'm41.detail.pictureFailed': 'NAI Studio did not draw: {reason}',
        'm41.detail.avatarFailed': 'did not upload: set a picture in the persona window',
        'm41.detail.cancelled': 'stopped',
        'm41.detail.unknown': 'reason unknown',

        'm41.error.noProfile':
            'No connection profile for Maestro background tasks: choose one in the settings (Profiles).',
        'm41.error.noCard': 'The character card did not load',
        'm41.error.request': 'The model did not answer: {reason}',
        'm41.error.refusal': 'The model refused',
        'm41.error.answer.shape': 'The model answered with something other than a persona',
        'm41.error.answer.name': 'The model gave no name',
        'm41.error.answer.appearance': 'The model did not describe the look',
        'm41.error.answer.language': 'The model did not write in Russian',
        'm41.error.answer.outfits': 'The model gave {count} outfits instead of 5–6',
        'm41.error.create': 'SillyTavern did not create the persona: {reason}',
        'm41.error.select': 'SillyTavern did not switch the persona',

        'm41.job.title': 'Persona for «{name}»',
        'm41.job.thought': 'made up «{name}»',
        'm41.job.show': 'Show',
        'm41.summary': '«{name}»: {parts}',
        'm41.part.persona': 'persona',
        'm41.part.link': 'linked to the character',
        'm41.part.passport': 'passport ({outfits})',
        'm41.part.noPassport': 'no passport ({why})',
        'm41.part.picture': 'picture',
        'm41.part.noPicture': 'no picture ({why})',
        'm41.part.current': 'current in this chat',
    },
    ru: {
        'm41.title': 'Персона для персонажа',
        'm41.profileTask': 'Персона для персонажа',
        'm41.button.title': 'Создать персону игрока для этого персонажа',
        'm41.option': 'Создать персону',
        'm41.noCard': 'Открой карточку одного персонажа (не группы)',
        'm41.noWindow': 'SillyTavern не смог открыть окно',
        'm41.busy': 'Уже создаю персону для «{name}»',
        'm41.slash.help': 'Создать персону игрока для персонажа этого чата: /maestro-persona [кем ты хочешь быть]',
        'm41.slash.value': 'кем ты хочешь быть (необязательно)',
        'm41.slash.noCard': 'Открой чат с одним персонажем',

        'm41.dialog.title': 'Персона для «{name}»',
        'm41.dialog.intro':
            'Maestro прочитает карточку, сценарий, стартовую сцену и лорбук и придумает твоего персонажа: внешность, предысторию и 5–6 нарядов.',
        'm41.dialog.comment': 'Кем ты хочешь быть?',
        'm41.dialog.commentHint': 'Например: наёмница с севера, давно знает Веру',
        'm41.dialog.commentHelp': 'Можно оставить пустым — тогда Maestro решит сам по карточке.',

        'm41.opt.passport': 'Паспорт NAI',
        'm41.opt.passportHint': 'Внешность и наряды для картинок NAI Studio',
        'm41.opt.picture': 'Картинка (бесплатно)',
        'm41.opt.pictureHint': 'Аватар персоны — рисует NAI Studio по паспорту',
        'm41.opt.link': 'Связать с «{name}»',
        'm41.opt.linkHint': 'SillyTavern предложит эту персону, когда откроешь персонажа',
        'm41.opt.current': 'Сделать текущей в этом чате',
        'm41.opt.currentHint': 'Сразу переключить чат на новую персону',
        'm41.nai.absent': 'Паспорт и картинку делает NAI Studio — он не установлен или выключен.',
        'm41.nai.old': 'Для паспорта и картинки нужна свежая NAI Studio (паспорта для любой персоны).',

        'm41.action.think': 'Придумать',
        'm41.action.cancel': 'Отмена',
        'm41.action.stop': 'Остановить',
        'm41.action.create': 'Создать',
        'm41.action.again': 'Ещё раз',
        'm41.action.hide': 'Скрыть',
        'm41.action.makeCurrent': 'Сделать текущей',
        'm41.action.isCurrent': 'Текущая',
        'm41.action.openPersonas': 'Открыть персоны',
        'm41.action.done': 'Готово',
        'm41.action.removeOutfit': 'Убрать наряд',

        'm41.phase.reading': 'Читаю карточку и лор…',
        'm41.phase.thinking': 'Придумываю персону…',
        'm41.phase.retry': 'Ответ не подошёл, спрашиваю ещё раз…',
        'm41.phase.wait': 'Обычно это занимает до минуты.',

        'm41.review.name': 'Имя',
        'm41.review.title': 'Подпись',
        'm41.review.description': 'Описание для SillyTavern',
        'm41.review.descriptionHint':
            'Этот текст станет описанием персоны. Строка «Гардероб» следует за списком нарядов.',
        'm41.review.outfits': 'Наряды: {count}',
        'm41.review.outfitsHint': 'Название, из чего состоит, и теги, по которым его рисует NovelAI.',
        'm41.review.outfitName': 'Название наряда',
        'm41.review.outfitWording': 'Из чего состоит',
        'm41.review.outfitTags': 'Теги для NovelAI',
        'm41.review.comment': 'Комментарий для «Ещё раз»',
        'm41.review.lore': 'Прочитано записей лора: {picked} из {total}',
        'm41.review.noLore': 'У карточки нет записей лорбука',
        'm41.review.noName': 'Дай персоне имя',

        'm41.creating.title': 'Создаю «{name}»',
        'm41.done.title': 'Персона «{name}» готова',
        'm41.done.partial': 'Персона «{name}» создана, но не всё получилось',
        'm41.done.failed': 'Персона не создана',
        'm41.done.noUndo': 'Отмены нет: лишнюю персону удаляют в окне персон SillyTavern.',

        'm41.step.persona': 'Персона в SillyTavern',
        'm41.step.avatar': 'Аватар по умолчанию',
        'm41.step.link': 'Связь с «{name}»',
        'm41.step.passport': 'Паспорт NAI',
        'm41.step.picture': 'Картинка',
        'm41.step.current': 'Текущая персона',

        'm41.detail.notChosen': 'не выбрано',
        'm41.detail.naiAbsent': 'NAI Studio не установлен или выключен',
        'm41.detail.naiOld': 'нужна свежая NAI Studio',
        'm41.detail.noPassport': 'нет паспорта, по которому рисовать',
        'm41.detail.passportFailed': 'NAI Studio не сделал паспорт: {reason}',
        'm41.detail.passportNotSaved': 'NAI Studio не сохранил паспорт',
        'm41.detail.outfits.one': '{count} наряд',
        'm41.detail.outfits.few': '{count} наряда',
        'm41.detail.outfits.many': '{count} нарядов',
        'm41.detail.pictureFailed': 'NAI Studio не нарисовал: {reason}',
        'm41.detail.avatarFailed': 'не загрузился — поставь картинку в окне персон',
        'm41.detail.cancelled': 'остановлено',
        'm41.detail.unknown': 'причина неизвестна',

        'm41.error.noProfile': 'Нет профиля подключения для фоновых задач Maestro — выбери его в настройках (Профили).',
        'm41.error.noCard': 'Карточка персонажа не загрузилась',
        'm41.error.request': 'Модель не ответила: {reason}',
        'm41.error.refusal': 'Модель отказалась',
        'm41.error.answer.shape': 'Модель ответила не персоной',
        'm41.error.answer.name': 'Модель не дала имени',
        'm41.error.answer.appearance': 'Модель не описала внешность',
        'm41.error.answer.language': 'Модель написала не по-русски',
        'm41.error.answer.outfits': 'Модель дала нарядов: {count} вместо 5–6',
        'm41.error.create': 'SillyTavern не создал персону: {reason}',
        'm41.error.select': 'SillyTavern не переключил персону',

        'm41.job.title': 'Персона для «{name}»',
        'm41.job.thought': 'придумал «{name}»',
        'm41.job.show': 'Показать',
        'm41.summary': '«{name}»: {parts}',
        'm41.part.persona': 'персона',
        'm41.part.link': 'связь с персонажем',
        'm41.part.passport': 'паспорт ({outfits})',
        'm41.part.noPassport': 'без паспорта ({why})',
        'm41.part.picture': 'картинка',
        'm41.part.noPicture': 'без картинки ({why})',
        'm41.part.current': 'текущая в этом чате',
    },
};
