// Strings of M8 «Ревизия „сюжет → канон“ и „Входящие“» (`m8.*`, the Inbox view's additions `m8.inbox.*`, autonomy
// kind labels `kind.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const REVISION_STRINGS: I18nParts = {
    en: {
        'm8.title': 'Revision «story → canon»',
        'm8.tab': 'Revision',
        'm8.hint':
            'When the story changes something known — a fact, a character trait, lasting appearance, a nickname, a place — the revision proposes to update its owner: the chat canon, the CK archive, the NAI passport, the alias map, the place registry. It runs in the background after enough signals, every N messages or at the end of a scene; only committed turns are read.',
        'm8.profileTask': 'Revision «story → canon»',
        'm8.slash.help': 'Run the story → canon revision now (it runs in the background).',
        'm8.slash.queued': 'The revision is queued: it runs in the background, proposals go to the Inbox.',
        'm8.noChat': 'No chat is open.',
        'm8.group': 'Maestro sleeps in group chats.',
        'm8.runNow': 'Revise now',
        'm8.runNow.hint': 'Read the committed messages since the last revision and propose canon updates',
        'm8.queued': 'The revision is queued.',
        'm8.status': 'Signals waiting: {pending} · messages since the last revision: {since}',
        'm8.status.queued': 'A revision is queued or running.',
        'm8.status.noSignals': 'The signals service is off: the revision counts messages and signals itself.',
        'm8.settings.title': 'When to revise',
        'm8.settings.threshold': 'Signals before a revision',
        'm8.settings.threshold.hint': 'Changes noticed in the tracker and memory (relationship, appearance, place…).',
        'm8.settings.every': 'Every N messages',
        'm8.settings.every.hint': '0 — off.',
        'm8.settings.sceneEnd': 'Revise at the end of a scene',
        'm8.settings.sceneEnd.hint': 'A change of location or a time skip ends a scene.',
        'm8.settings.confidence': 'Minimum confidence, %',
        'm8.settings.confidence.hint': 'Changes the model is less sure about are not proposed.',
        'm8.runs.title': 'Last revisions',
        'm8.runs.empty': 'No revisions in this chat yet.',
        'm8.run.reason.signals': 'signals',
        'm8.run.reason.interval': 'every N messages',
        'm8.run.reason.sceneEnd': 'end of a scene',
        'm8.run.reason.manual': 'by hand',
        'm8.run.range': 'messages #{from}–#{to}',
        'm8.run.changes': 'Changes: {count}',
        'm8.run.rejected': 'Rejected: {count}',
        'm8.run.cost': 'Cost: {cost}',
        'm8.run.error': 'Not done: {error}',
        'm8.run.new': 'new → living canon',
        'm8.run.change': '{target} · {name}: {value}',
        'm8.target.canon.fact': 'canon fact',
        'm8.target.ck.tags': 'character tags',
        'm8.target.nai.appearance': 'appearance',
        'm8.target.chat.alias': 'nickname',
        'm8.target.des.alias': 'new name',
        'm8.target.chronicle.event': 'important moment',
        'm8.target.places.state': 'place state',
        'm8.target.deferred.outfit': 'outfit',
        'm8.target.deferred.promise': 'promise',
        'm8.target.deferred.secret': 'secret',
        'm8.reject.lowConfidence': 'the model is not sure enough ({detail})',
        'm8.reject.unknownEntity': 'unknown character or thing «{detail}»',
        'm8.reject.unknownPlace': 'unknown place «{detail}»',
        'm8.reject.noTarget': 'nowhere to write it (module or neighbour is off, or the entity has no such store)',
        'm8.reject.noDictionary': 'the BunnyMo tag dictionary is not available',
        'm8.reject.tag': 'tag not from the loaded packs: {detail}',
        'm8.reject.cyrillic': 'Russian in a tag: {detail}',
        'm8.reject.notEnglish': 'canon text must be English',
        'm8.reject.placeholder': 'placeholder instead of a value: {detail}',
        'm8.reject.transitional': '!updatesheet transition markup: {detail}',
        'm8.reject.malformed': 'unreadable value: {detail}',
        'm8.reject.duplicate': 'repeats something that exists: {detail}',
        'm8.reject.multiBlock': 'the archive holds several characters',
        'm8.reject.anatomy': 'explicit anatomy outside the NSFW layer: {detail}',
        'm8.reject.uppercase': 'passport tags must be lower case: {detail}',
        'm8.reject.slot': 'not a passport slot the revision may change: {detail}',
        'm8.reject.keys': 'invalid keys: {detail}',
        'm8.reject.name': 'would change the archive name <Name:…>',
        'm8.reject.markup': 'CK markup in canon text',
        'm8.reject.beforeMissing': 'the old value is not there: {detail}',
        'm8.reject.noChange': 'already so',
        'm8.reject.protectedBook': 'BunnyMo book, never edited: {detail}',
        'm8.reject.empty': 'empty value',
        'm8.reject.tooLong': 'too long',
        'm8.reject.failed': 'not applied: {detail}',
        'm8.error.noChat': 'No chat is open.',
        'm8.error.group': 'Maestro sleeps in group chats.',
        'm8.error.noCanon': 'The chat canon module is off.',
        'm8.error.protected': '«{book}» is a BunnyMo book: Maestro never edits it.',
        'm8.error.gone': 'The entry or passport is gone.',
        'm8.error.noNai': 'NAI Studio API is not available.',
        'm8.error.noWorld': 'The world model is off.',
        'm8.error.cap': 'the daily background budget is spent',
        'm8.error.no-cm': 'Connection Manager is off',
        'm8.error.no-profile': 'no connection profile for background tasks',
        'm8.error.breaker-open': 'the profile failed several times; paused for a few minutes',
        'm8.error.refusal': 'the model refused',
        'm8.error.parse': 'the model answered with broken JSON twice',
        'm8.error.aborted': 'interrupted',
        'm8.error.empty': 'nothing new since the last revision',
        'm8.error.failed': 'failed',
        'm8.error.other': '{error}',
        'm8.card.fact.title': '{name}: canon fact',
        'm8.card.fact.body': 'A new fact for the chat canon ({dest}).',
        'm8.card.fact.replace': 'Replaces an outdated statement in the chat canon ({dest}).',
        'm8.card.conflict': 'Conflicts with confirmed canon: {list}. Nothing is overwritten by itself — check it.',
        'm8.card.unchecked':
            'The contradiction check did not answer: the fact waits for you instead of going in by itself.',
        'm8.card.tags.title': '{name}: character tags',
        'm8.card.tags.body':
            'CK archive in «{book}», through the chat canon: + {added}; − {removed}. CarrotKernel re-reads its repos afterwards.',
        'm8.card.appearance.title': '{name}: appearance ({slot})',
        'm8.card.appearance.body': 'NAI passport of this chat, slot «{slot}».',
        'm8.slot.hair': 'hair',
        'm8.slot.eyes': 'eyes',
        'm8.slot.body': 'body',
        'm8.slot.skin': 'skin',
        'm8.slot.base': 'base',
        'm8.card.alias.title': '{name}: nickname «{alias}»',
        'm8.card.alias.body': 'A nickname of this chat (alias map).',
        'm8.card.alias.keys': 'A nickname of this chat (alias map) and a key of «{dest}».',
        'm8.card.desAlias.title': '{name}: new name «{alias}»',
        'm8.note.desAlias':
            'The story calls {name} «{alias}» now. DES owns canonical names: add the alias in the DES Character Workshop yourself.',
        'm8.card.event.title': '{name}: an important moment',
        'm8.card.event.body': 'For the chronicle (auto-memory): {value}',
        'm8.card.place.title': '{name}: {key}',
        'm8.card.place.body': 'Place registry: {key} — {value}',
        'm8.store.revision.canon': 'Chat canon',
        'm8.store.revision.ck': 'CK archive (through the chat canon)',
        'm8.store.revision.keys': 'Entry keys (through the chat canon)',
        'm8.store.revision.passport': 'NAI passport of this chat',
        'm8.store.revision.alias': 'Chat alias map',
        'm8.store.revision.place': 'Place registry',
        'm8.store.revision.note': 'Note for DES',
        'm8.store.revision.event': 'Chronicle',
        'm8.inbox.edit': 'Edit',
        'm8.inbox.editLabel': 'New value',
        'm8.inbox.save': 'Save and accept',
        'm8.inbox.cancel': 'Cancel',
        'm8.inbox.editFailed': '«{title}» was not applied: check the value (details are in the log).',
        'm8.inbox.always': 'Always',
        'm8.inbox.always.hint': 'Accept and do such changes by itself from now on',
        'm8.inbox.always.done': '«{kind}» is now done by itself. You can change it in Settings.',
        'm8.inbox.snooze.hint': 'Put off until tomorrow',
        'm8.inbox.confidence': 'confidence {value}%',
        'm8.inbox.other': 'Other',
        'm8.inbox.deferred.title': 'Deferred',
        'm8.inbox.deferred.hint': 'Changes for modules of later stages; they wait here until those modules arrive.',
        'm8.inbox.deferred.stage': 'Deferred until stage {stage}',
        'm8.inbox.deferred.dismiss': 'Remove',
        'kind.canon.fact': 'Canon facts about known entities (revision)',
        'kind.ck.tags': 'Character tags of CK archives (revision)',
        'kind.nai.appearance': 'Lasting appearance in NAI passports (revision)',
        'kind.chat.alias': 'Nicknames of the chat (revision)',
        'kind.des.alias': 'New canonical names for DES (revision)',
        'kind.chronicle.event': 'Important moments for the chronicle (revision)',
        'kind.places.state': 'Place states (revision)',
    },
    ru: {
        'm8.title': 'Ревизия «сюжет → канон»',
        'm8.tab': 'Ревизия',
        'm8.hint':
            'Когда история меняет что-то известное — факт, черту характера, стойкую внешность, прозвище, место, — ревизия предлагает обновить того, кто это хранит: канон чата, архив CK, паспорт NAI, карту алиасов, реестр мест. Работает в фоне: после нескольких сигналов, каждые N сообщений или в конце сцены; читает только зафиксированные ходы.',
        'm8.profileTask': 'Ревизия «сюжет → канон»',
        'm8.slash.help': 'Запустить ревизию «сюжет → канон» сейчас (пройдёт в фоне).',
        'm8.slash.queued': 'Ревизия поставлена в очередь: пройдёт в фоне, предложения появятся во «Входящих».',
        'm8.noChat': 'Чат не открыт.',
        'm8.group': 'В групповых чатах Maestro спит.',
        'm8.runNow': 'Ревизия сейчас',
        'm8.runNow.hint': 'Прочитать зафиксированные сообщения с прошлой ревизии и предложить обновления канона',
        'm8.queued': 'Ревизия поставлена в очередь.',
        'm8.status': 'Ждут сигналов: {pending} · сообщений с прошлой ревизии: {since}',
        'm8.status.queued': 'Ревизия в очереди или уже идёт.',
        'm8.status.noSignals': 'Сервис сигналов выключен: ревизия сама считает сообщения и сигналы.',
        'm8.settings.title': 'Когда запускать',
        'm8.settings.threshold': 'Сигналов до ревизии',
        'm8.settings.threshold.hint': 'Перемены, замеченные в трекере и памяти (отношения, внешность, место…).',
        'm8.settings.every': 'Каждые N сообщений',
        'm8.settings.every.hint': '0 — выключено.',
        'm8.settings.sceneEnd': 'Ревизия в конце сцены',
        'm8.settings.sceneEnd.hint': 'Сцену заканчивает смена места или пропуск времени.',
        'm8.settings.confidence': 'Минимальная уверенность, %',
        'm8.settings.confidence.hint': 'Изменения, в которых модель уверена меньше, не предлагаются.',
        'm8.runs.title': 'Последние ревизии',
        'm8.runs.empty': 'В этом чате ревизий ещё не было.',
        'm8.run.reason.signals': 'по сигналам',
        'm8.run.reason.interval': 'каждые N сообщений',
        'm8.run.reason.sceneEnd': 'конец сцены',
        'm8.run.reason.manual': 'вручную',
        'm8.run.range': 'сообщения №{from}–{to}',
        'm8.run.changes': 'Изменений: {count}',
        'm8.run.rejected': 'Отклонено проверками: {count}',
        'm8.run.cost': 'Стоимость: {cost}',
        'm8.run.error': 'Не выполнена: {error}',
        'm8.run.new': 'новое → живой канон',
        'm8.run.change': '{target} · {name}: {value}',
        'm8.target.canon.fact': 'факт канона',
        'm8.target.ck.tags': 'теги характера',
        'm8.target.nai.appearance': 'внешность',
        'm8.target.chat.alias': 'прозвище',
        'm8.target.des.alias': 'новое имя',
        'm8.target.chronicle.event': 'важный момент',
        'm8.target.places.state': 'состояние места',
        'm8.target.deferred.outfit': 'наряд',
        'm8.target.deferred.promise': 'обещание',
        'm8.target.deferred.secret': 'секрет',
        'm8.reject.lowConfidence': 'модель не уверена ({detail})',
        'm8.reject.unknownEntity': 'неизвестный персонаж или предмет «{detail}»',
        'm8.reject.unknownPlace': 'неизвестное место «{detail}»',
        'm8.reject.noTarget': 'некуда записать (модуль или сосед выключен, или у сущности нет такого хранилища)',
        'm8.reject.noDictionary': 'словарь тегов BunnyMo недоступен',
        'm8.reject.tag': 'тег не из загруженных паков: {detail}',
        'm8.reject.cyrillic': 'русский текст в теге: {detail}',
        'm8.reject.notEnglish': 'текст канона должен быть на английском',
        'm8.reject.placeholder': 'заглушка вместо значения: {detail}',
        'm8.reject.transitional': 'переходная разметка !updatesheet: {detail}',
        'm8.reject.malformed': 'значение не читается: {detail}',
        'm8.reject.duplicate': 'повторяет то, что уже есть: {detail}',
        'm8.reject.multiBlock': 'в архиве несколько персонажей',
        'm8.reject.anatomy': 'явная анатомия вне слоя NSFW: {detail}',
        'm8.reject.uppercase': 'теги паспорта пишутся строчными: {detail}',
        'm8.reject.slot': 'этот слот паспорта ревизия не меняет: {detail}',
        'm8.reject.keys': 'неверные ключи: {detail}',
        'm8.reject.name': 'изменилось бы имя архива <Name:…>',
        'm8.reject.markup': 'разметка CK в тексте канона',
        'm8.reject.beforeMissing': 'прежнего значения уже нет: {detail}',
        'm8.reject.noChange': 'уже так',
        'm8.reject.protectedBook': 'книга BunnyMo, её не правим: {detail}',
        'm8.reject.empty': 'пустое значение',
        'm8.reject.tooLong': 'слишком длинно',
        'm8.reject.failed': 'не применено: {detail}',
        'm8.error.noChat': 'Чат не открыт.',
        'm8.error.group': 'В групповых чатах Maestro спит.',
        'm8.error.noCanon': 'Модуль канона чата выключен.',
        'm8.error.protected': '«{book}» — книга BunnyMo: Maestro её не правит.',
        'm8.error.gone': 'Запись или паспорт больше не существует.',
        'm8.error.noNai': 'API NAI Studio недоступен.',
        'm8.error.noWorld': 'Модель мира выключена.',
        'm8.error.cap': 'дневной бюджет фоновых задач исчерпан',
        'm8.error.no-cm': 'Connection Manager выключен',
        'm8.error.no-profile': 'нет профиля подключения для фоновых задач',
        'm8.error.breaker-open': 'профиль несколько раз подряд не ответил; пауза на несколько минут',
        'm8.error.refusal': 'модель отказалась отвечать',
        'm8.error.parse': 'модель дважды прислала испорченный JSON',
        'm8.error.aborted': 'прервано',
        'm8.error.empty': 'с прошлой ревизии ничего нового',
        'm8.error.failed': 'не получилось',
        'm8.error.other': '{error}',
        'm8.card.fact.title': '{name}: факт канона',
        'm8.card.fact.body': 'Новый факт в канон чата ({dest}).',
        'm8.card.fact.replace': 'Заменяет устаревшее утверждение в каноне чата ({dest}).',
        'm8.card.conflict': 'Противоречит подтверждённому канону: {list}. Само ничего не перезапишется — проверь.',
        'm8.card.unchecked': 'Проверка противоречий не ответила: факт ждёт тебя, а не вписывается сам.',
        'm8.card.tags.title': '{name}: теги характера',
        'm8.card.tags.body':
            'Архив CK в «{book}» через канон чата: + {added}; − {removed}. После изменения CarrotKernel перечитает репозитории.',
        'm8.card.appearance.title': '{name}: внешность ({slot})',
        'm8.card.appearance.body': 'Паспорт NAI этого чата, слот «{slot}».',
        'm8.slot.hair': 'волосы',
        'm8.slot.eyes': 'глаза',
        'm8.slot.body': 'тело',
        'm8.slot.skin': 'кожа',
        'm8.slot.base': 'основа',
        'm8.card.alias.title': '{name}: прозвище «{alias}»',
        'm8.card.alias.body': 'Прозвище в этом чате (карта алиасов).',
        'm8.card.alias.keys': 'Прозвище в этом чате (карта алиасов) и ключ записи «{dest}».',
        'm8.card.desAlias.title': '{name}: новое имя «{alias}»',
        'm8.note.desAlias':
            'Теперь история называет {name} «{alias}». Канонические имена — дело DES: добавь алиас сам в мастерской персонажей DES.',
        'm8.card.event.title': '{name}: важный момент',
        'm8.card.event.body': 'В летопись (автопамять): {value}',
        'm8.card.place.title': '{name}: {key}',
        'm8.card.place.body': 'Реестр мест: {key} — {value}',
        'm8.store.revision.canon': 'Канон чата',
        'm8.store.revision.ck': 'Архив CK (через канон чата)',
        'm8.store.revision.keys': 'Ключи записи (через канон чата)',
        'm8.store.revision.passport': 'Паспорт NAI этого чата',
        'm8.store.revision.alias': 'Карта алиасов чата',
        'm8.store.revision.place': 'Реестр мест',
        'm8.store.revision.note': 'Заметка для DES',
        'm8.store.revision.event': 'Летопись',
        'm8.inbox.edit': 'Изменить',
        'm8.inbox.editLabel': 'Новое значение',
        'm8.inbox.save': 'Сохранить и принять',
        'm8.inbox.cancel': 'Отмена',
        'm8.inbox.editFailed': '«{title}» не применено: проверь значение (подробности — в журнале ошибок).',
        'm8.inbox.always': 'Всегда так',
        'm8.inbox.always.hint': 'Принять и дальше делать такие изменения самому',
        'm8.inbox.always.done': '«{kind}» теперь делается само. Вернуть можно в настройках.',
        'm8.inbox.snooze.hint': 'Отложить до завтра',
        'm8.inbox.confidence': 'уверенность {value}%',
        'm8.inbox.other': 'Прочее',
        'm8.inbox.deferred.title': 'Отложено',
        'm8.inbox.deferred.hint': 'Изменения для модулей следующих этапов; ждут здесь, пока эти модули не появятся.',
        'm8.inbox.deferred.stage': 'Отложено до этапа {stage}',
        'm8.inbox.deferred.dismiss': 'Убрать',
        'kind.canon.fact': 'Факты канона об известных сущностях (ревизия)',
        'kind.ck.tags': 'Теги характера в архивах CK (ревизия)',
        'kind.nai.appearance': 'Стойкая внешность в паспортах NAI (ревизия)',
        'kind.chat.alias': 'Прозвища в чате (ревизия)',
        'kind.des.alias': 'Новые канонические имена для DES (ревизия)',
        'kind.chronicle.event': 'Важные моменты для летописи (ревизия)',
        'kind.places.state': 'Состояния мест (ревизия)',
    },
};
