// Strings of M8 «Ревизия „сюжет → канон“ и „Входящие“» (`m8.*`, the Inbox view's additions `m8.inbox.*`, autonomy
// kind labels `kind.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const REVISION_STRINGS: I18nParts = {
    en: {
        'm8.title': 'Revision «story → canon»',
        'm8.tab': 'Revision',
        'm8.hint':
            'When the story changes something known — a fact, a character trait, lasting appearance, a nickname, a place — the revision proposes to update its owner: the chat canon, the CK archive, the NAI passport, the alias map, the place registry. It runs in the background after enough signals, every N messages or at the end of a scene; only committed turns are read.',
        'm8.profileTask': 'Revision «story → canon»',
        'm8.slash.help': 'Run the story → canon revision now (it runs in the background).',
        'm8.slash.queued': 'I will go through the story in the background; proposals will appear in the Inbox.',
        'm8.noChat': 'No chat is open.',
        'm8.group': 'Maestro sleeps in group chats.',
        'm8.runNow': 'Revise now',
        'm8.runNow.hint': 'Read the committed messages since the last revision and propose canon updates',
        'm8.queued': 'I will go through the story in the background; proposals will appear in the Inbox.',
        'm8.status': 'Signals waiting: {pending} · messages since the last revision: {since}',
        'm8.status.queued': 'A revision is queued or running.',
        'm8.status.noSignals': 'The signals service is off: the revision counts messages and signals itself.',
        'm8.settings.title': 'When to revise',
        'm8.settings.threshold': 'Signals before a revision',
        'm8.settings.threshold.hint': 'Changes noticed in the tracker and memory (relationship, appearance, place…).',
        'm8.settings.every': 'Every N messages',
        'm8.settings.every.hint': '0 — off.',
        'm8.settings.sceneEnd': 'Revise at the end of a scene',
        'm8.settings.sceneEnd.hint': 'A change of location or a time skip ends a scene.',
        'm8.settings.confidence': 'Minimum confidence, %',
        'm8.settings.confidence.hint': 'Changes the model is less sure about are not proposed.',
        'm8.runs.title': 'Last revisions',
        'm8.runs.empty': 'No revisions in this chat yet.',
        'm8.run.reason.signals': 'signals',
        'm8.run.reason.interval': 'every N messages',
        'm8.run.reason.sceneEnd': 'end of a scene',
        'm8.run.reason.manual': 'by hand',
        'm8.run.range': 'messages #{from}–#{to}',
        'm8.run.changes': 'Changes: {count}',
        'm8.run.rejected': 'Rejected: {count}',
        'm8.run.cost': 'Cost: {cost}',
        'm8.run.error': 'Not done: {error}',
        'm8.run.new': 'new → living canon',
        'm8.run.change': '{target} · {name}: {value}',
        'm8.target.canon.fact': 'canon fact',
        'm8.target.ck.tags': 'character tags',
        'm8.target.nai.appearance': 'appearance',
        'm8.target.chat.alias': 'nickname',
        'm8.target.des.alias': 'new name',
        'm8.target.chronicle.event': 'important moment',
        'm8.target.places.state': 'place state',
        'm8.target.deferred.outfit': 'outfit',
        'm8.target.deferred.promise': 'promise',
        'm8.target.deferred.secret': 'secret',
        'm8.reject.lowConfidence': 'the model is not sure enough ({detail})',
        'm8.reject.unknownEntity': 'unknown character or thing «{detail}»',
        'm8.reject.unknownPlace': 'unknown place «{detail}»',
        'm8.reject.noTarget': 'nowhere to write it (module or neighbour is off, or the entity has no such store)',
        'm8.reject.noDictionary': 'the BunnyMo tag dictionary is not available',
        'm8.reject.tag': 'tag not from the loaded packs: {detail}',
        'm8.reject.cyrillic': 'Russian in a tag: {detail}',
        'm8.reject.notEnglish': 'canon text must be English',
        'm8.reject.placeholder': 'placeholder instead of a value: {detail}',
        'm8.reject.transitional': '!updatesheet transition markup: {detail}',
        'm8.reject.malformed': 'unreadable value: {detail}',
        'm8.reject.duplicate': 'repeats something that exists: {detail}',
        'm8.reject.multiBlock': 'the archive holds several characters',
        'm8.reject.anatomy': 'explicit anatomy outside the NSFW layer: {detail}',
        'm8.reject.uppercase': 'passport tags must be lower case: {detail}',
        'm8.reject.slot': 'not a passport slot the revision may change: {detail}',
        'm8.reject.keys': 'invalid keys: {detail}',
        'm8.reject.name': 'would change the archive name <Name:…>',
        'm8.reject.markup': 'CK markup in canon text',
        'm8.reject.beforeMissing': 'the old value is not there: {detail}',
        'm8.reject.noChange': 'already so',
        'm8.reject.protectedBook': 'BunnyMo book, never edited: {detail}',
        'm8.reject.empty': 'empty value',
        'm8.reject.tooLong': 'too long',
        'm8.reject.failed': 'not applied: {detail}',
        'm8.error.noChat': 'No chat is open.',
        'm8.error.group': 'Maestro sleeps in group chats.',
        'm8.error.noCanon': '“Chat canon” is off.',
        'm8.error.protected': '«{book}» is a BunnyMo book: I never change it.',
        'm8.error.gone': 'The entry or the appearance description is gone.',
        'm8.error.noNai': 'NAI Studio is not available.',
        'm8.error.noWorld': 'The world model is off.',
        'm8.error.cap': 'the daily background budget is spent',
        'm8.error.no-cm': 'Connection Manager is off',
        'm8.error.no-profile': 'no connection profile for background tasks',
        'm8.error.breaker-open': 'the profile failed several times; paused for a few minutes',
        'm8.error.refusal': 'the model refused',
        'm8.error.parse': 'the model answered with broken JSON twice',
        'm8.error.aborted': 'interrupted',
        'm8.error.empty': 'nothing new since the last revision',
        'm8.error.failed': 'failed',
        'm8.error.other': '{error}',
        'm8.card.fact.title': '{name}: something new',
        'm8.card.fact.replaceTitle': '{name}: something changed',
        'm8.card.fact.body': '{statement}\nI will write it into the chat canon.',
        'm8.card.fact.replace': '{statement}\nI will update the old statement in the chat canon.',
        'm8.card.conflict':
            'This disagrees with what is already known: {list}. Nothing is overwritten by itself — you decide.',
        'm8.card.unchecked':
            'The contradiction check did not answer in time, so the fact waits for you instead of going in by itself.',
        'm8.card.tags.title': '{name}: the character changes',
        'm8.card.tags.body': '{statement}\nUpdate the character sheet in this chat? The card itself stays as it is.',
        'm8.card.appearance.title': '{name}: appearance ({slot})',
        'm8.card.appearance.body': '{statement}\nUpdate how the pictures of this chat draw it?',
        'm8.slot.hair': 'hair',
        'm8.slot.eyes': 'eyes',
        'm8.slot.body': 'body',
        'm8.slot.skin': 'skin',
        'm8.slot.base': 'base',
        'm8.card.alias.title': '{name}: nickname «{alias}»',
        'm8.card.alias.body': 'The story calls {name} «{alias}». I will remember the nickname in this chat.',
        'm8.card.alias.keys':
            'The story calls {name} «{alias}». I will remember the nickname in this chat and let the lore react to it too.',
        'm8.card.desAlias.title': '{name}: new name «{alias}»',
        'm8.note.desAlias':
            'The story calls {name} «{alias}» now. Character names are kept by DES, so I do not change them myself: add the new name in the DES Character Workshop.',
        'm8.card.event.title': '{name}: an important moment',
        'm8.card.event.body': '{statement}\nI will write it into the chronicle so the model remembers it.',
        'm8.card.place.title': '{name}: {key}',
        'm8.card.place.body': '{statement}\nI will note it in the description of the place.',
        'm8.placeKey.condition': 'condition',
        'm8.placeKey.owner': 'owner',
        'm8.placeKey.decoration': 'decoration',
        'm8.placeKey.other': 'a change',
        'm8.notice.alias': 'Remembered a nickname: {name} — «{alias}»',
        'm8.notice.aliasMany.one': 'Remembered {count} nickname',
        'm8.notice.aliasMany.few': 'Remembered {count} nicknames',
        'm8.notice.aliasMany.many': 'Remembered {count} nicknames',
        'm8.notice.event': 'Wrote into the chronicle: {what}',
        'm8.notice.eventMany.one': 'Wrote {count} important moment into the chronicle',
        'm8.notice.eventMany.few': 'Wrote {count} important moments into the chronicle',
        'm8.notice.eventMany.many': 'Wrote {count} important moments into the chronicle',
        'm8.notice.place': 'Noted about {name}: {what}',
        'm8.notice.placeMany.one': 'Noted {count} change of places',
        'm8.notice.placeMany.few': 'Noted {count} changes of places',
        'm8.notice.placeMany.many': 'Noted {count} changes of places',
        'm8.details.entry': 'Entry: {value}',
        'm8.details.book': 'Book: {value}',
        'm8.details.english': 'Canon text (English): {value}',
        'm8.details.replaces': 'Replaces: {value}',
        'm8.details.conflict': 'Contradiction: {value}',
        'm8.details.tagsAdded': 'Tags added: {value}',
        'm8.details.tagsRemoved': 'Tags removed: {value}',
        'm8.details.ckRescan': 'CarrotKernel re-reads its books after the change.',
        'm8.details.slot': 'Passport slot: {value}',
        'm8.details.naiTags': 'NAI tags: {value}',
        'm8.details.field': 'Field: {value}',
        'target.revision.canon': 'Chat canon',
        'target.revision.ck': 'Character sheet',
        'target.revision.keys': 'Keywords of the entry',
        'target.revision.passport': 'Appearance for pictures',
        'target.revision.alias': 'Nickname',
        'target.revision.place': 'Place',
        'target.revision.note': 'New name (for DES)',
        'target.revision.event': 'Chronicle',
        'm8.field.alias': 'Nickname',
        'm8.field.entity': 'Who',
        'm8.field.name': 'Name',
        'm8.inbox.edit': 'Edit',
        'm8.inbox.editLabel': 'New value',
        'm8.inbox.save': 'Save and accept',
        'm8.inbox.cancel': 'Cancel',
        'm8.inbox.editFailed': '«{title}» was not applied: check the value (details are in the log).',
        'm8.inbox.always': 'Always',
        'm8.inbox.always.hint': 'Accept, and I make such changes myself from now on',
        'm8.inbox.always.done': 'Fine: I do «{kind}» myself from now on. You can change it in Settings.',
        'm8.inbox.snooze.hint': 'Put off until tomorrow',
        'm8.inbox.confidence': 'confidence {value}%',
        'm8.inbox.other': 'Other',
        'm8.inbox.deferred.title': 'Deferred',
        'm8.inbox.deferred.hint': 'Changes for modules of later stages; they wait here until those modules arrive.',
        'm8.inbox.deferred.stage': 'Deferred until stage {stage}',
        'm8.inbox.deferred.dismiss': 'Remove',
        'kind.canon.fact': 'Changes in what is known about characters and places',
        'kind.ck.tags': 'Changes of character',
        'kind.nai.appearance': 'Lasting changes of appearance',
        'kind.chat.alias': 'Nicknames',
        'kind.des.alias': 'New names of characters',
        'kind.chronicle.event': 'Important moments for the chronicle',
        'kind.places.state': 'Changes of places',
    },
    ru: {
        'm8.title': 'Ревизия «сюжет → канон»',
        'm8.tab': 'Ревизия',
        'm8.hint':
            'Когда история меняет что-то известное — факт, черту характера, стойкую внешность, прозвище, место, — ревизия предлагает обновить того, кто это хранит: канон чата, архив CK, паспорт NAI, карту алиасов, реестр мест. Работает в фоне: после нескольких сигналов, каждые N сообщений или в конце сцены; читает только зафиксированные ходы.',
        'm8.profileTask': 'Ревизия «сюжет → канон»',
        'm8.slash.help': 'Запустить ревизию «сюжет → канон» сейчас (пройдёт в фоне).',
        'm8.slash.queued': 'Пройдусь по истории в фоне — предложения появятся во «Входящих».',
        'm8.noChat': 'Чат не открыт.',
        'm8.group': 'В групповых чатах Maestro спит.',
        'm8.runNow': 'Ревизия сейчас',
        'm8.runNow.hint': 'Прочитать зафиксированные сообщения с прошлой ревизии и предложить обновления канона',
        'm8.queued': 'Пройдусь по истории в фоне — предложения появятся во «Входящих».',
        'm8.status': 'Ждут сигналов: {pending} · сообщений с прошлой ревизии: {since}',
        'm8.status.queued': 'Ревизия в очереди или уже идёт.',
        'm8.status.noSignals': 'Сервис сигналов выключен: ревизия сама считает сообщения и сигналы.',
        'm8.settings.title': 'Когда запускать',
        'm8.settings.threshold': 'Сигналов до ревизии',
        'm8.settings.threshold.hint': 'Перемены, замеченные в трекере и памяти (отношения, внешность, место…).',
        'm8.settings.every': 'Каждые N сообщений',
        'm8.settings.every.hint': '0 — выключено.',
        'm8.settings.sceneEnd': 'Ревизия в конце сцены',
        'm8.settings.sceneEnd.hint': 'Сцену заканчивает смена места или пропуск времени.',
        'm8.settings.confidence': 'Минимальная уверенность, %',
        'm8.settings.confidence.hint': 'Изменения, в которых модель уверена меньше, не предлагаются.',
        'm8.runs.title': 'Последние ревизии',
        'm8.runs.empty': 'В этом чате ревизий ещё не было.',
        'm8.run.reason.signals': 'по сигналам',
        'm8.run.reason.interval': 'каждые N сообщений',
        'm8.run.reason.sceneEnd': 'конец сцены',
        'm8.run.reason.manual': 'вручную',
        'm8.run.range': 'сообщения №{from}–{to}',
        'm8.run.changes': 'Изменений: {count}',
        'm8.run.rejected': 'Отклонено проверками: {count}',
        'm8.run.cost': 'Стоимость: {cost}',
        'm8.run.error': 'Не выполнена: {error}',
        'm8.run.new': 'новое → живой канон',
        'm8.run.change': '{target} · {name}: {value}',
        'm8.target.canon.fact': 'факт канона',
        'm8.target.ck.tags': 'теги характера',
        'm8.target.nai.appearance': 'внешность',
        'm8.target.chat.alias': 'прозвище',
        'm8.target.des.alias': 'новое имя',
        'm8.target.chronicle.event': 'важный момент',
        'm8.target.places.state': 'состояние места',
        'm8.target.deferred.outfit': 'наряд',
        'm8.target.deferred.promise': 'обещание',
        'm8.target.deferred.secret': 'секрет',
        'm8.reject.lowConfidence': 'модель не уверена ({detail})',
        'm8.reject.unknownEntity': 'неизвестный персонаж или предмет «{detail}»',
        'm8.reject.unknownPlace': 'неизвестное место «{detail}»',
        'm8.reject.noTarget': 'некуда записать (модуль или сосед выключен, или у сущности нет такого хранилища)',
        'm8.reject.noDictionary': 'словарь тегов BunnyMo недоступен',
        'm8.reject.tag': 'тег не из загруженных паков: {detail}',
        'm8.reject.cyrillic': 'русский текст в теге: {detail}',
        'm8.reject.notEnglish': 'текст канона должен быть на английском',
        'm8.reject.placeholder': 'заглушка вместо значения: {detail}',
        'm8.reject.transitional': 'переходная разметка !updatesheet: {detail}',
        'm8.reject.malformed': 'значение не читается: {detail}',
        'm8.reject.duplicate': 'повторяет то, что уже есть: {detail}',
        'm8.reject.multiBlock': 'в архиве несколько персонажей',
        'm8.reject.anatomy': 'явная анатомия вне слоя NSFW: {detail}',
        'm8.reject.uppercase': 'теги паспорта пишутся строчными: {detail}',
        'm8.reject.slot': 'этот слот паспорта ревизия не меняет: {detail}',
        'm8.reject.keys': 'неверные ключи: {detail}',
        'm8.reject.name': 'изменилось бы имя архива <Name:…>',
        'm8.reject.markup': 'разметка CK в тексте канона',
        'm8.reject.beforeMissing': 'прежнего значения уже нет: {detail}',
        'm8.reject.noChange': 'уже так',
        'm8.reject.protectedBook': 'книга BunnyMo, её не правим: {detail}',
        'm8.reject.empty': 'пустое значение',
        'm8.reject.tooLong': 'слишком длинно',
        'm8.reject.failed': 'не применено: {detail}',
        'm8.error.noChat': 'Чат не открыт.',
        'm8.error.group': 'В групповых чатах Maestro спит.',
        'm8.error.noCanon': 'Выключен «Канон чата».',
        'm8.error.protected': '«{book}» — книга BunnyMo: её я не меняю.',
        'm8.error.gone': 'Запись или описание внешности уже удалены.',
        'm8.error.noNai': 'NAI Studio недоступна.',
        'm8.error.noWorld': 'Модель мира выключена.',
        'm8.error.cap': 'дневной бюджет фоновых задач исчерпан',
        'm8.error.no-cm': 'Connection Manager выключен',
        'm8.error.no-profile': 'нет профиля подключения для фоновых задач',
        'm8.error.breaker-open': 'профиль несколько раз подряд не ответил; пауза на несколько минут',
        'm8.error.refusal': 'модель отказалась отвечать',
        'm8.error.parse': 'модель дважды прислала испорченный JSON',
        'm8.error.aborted': 'прервано',
        'm8.error.empty': 'с прошлой ревизии ничего нового',
        'm8.error.failed': 'не получилось',
        'm8.error.other': '{error}',
        'm8.card.fact.title': '{name}: новое в истории',
        'm8.card.fact.replaceTitle': '{name}: в истории что-то изменилось',
        'm8.card.fact.body': '{statement}\nЗапишу это в канон чата.',
        'm8.card.fact.replace': '{statement}\nОбновлю старую запись в каноне чата.',
        'm8.card.conflict': 'Это спорит с уже известным: {list}. Само ничего не перезапишется — решай сам.',
        'm8.card.unchecked':
            'Проверка на противоречия не успела ответить, поэтому факт ждёт тебя, а не записывается сам.',
        'm8.card.tags.title': '{name}: характер меняется',
        'm8.card.tags.body': '{statement}\nОбновить лист характера в этом чате? Сама карточка не изменится.',
        'm8.card.appearance.title': '{name}: внешность ({slot})',
        'm8.card.appearance.body': '{statement}\nОбновить, как это рисуется на картинках этого чата?',
        'm8.slot.hair': 'волосы',
        'm8.slot.eyes': 'глаза',
        'm8.slot.body': 'тело',
        'm8.slot.skin': 'кожа',
        'm8.slot.base': 'основа',
        'm8.card.alias.title': '{name}: прозвище «{alias}»',
        'm8.card.alias.body': 'История называет {name} «{alias}». Запомню это прозвище в этом чате.',
        'm8.card.alias.keys':
            'История называет {name} «{alias}». Запомню прозвище в этом чате, и лор будет откликаться и на него.',
        'm8.card.desAlias.title': '{name}: новое имя «{alias}»',
        'm8.note.desAlias':
            'Теперь история называет {name} «{alias}». Имена персонажей хранит DES, поэтому сам я их не меняю: добавь новое имя в мастерской персонажей DES.',
        'm8.card.event.title': '{name}: важный момент',
        'm8.card.event.body': '{statement}\nЗапишу в летопись, чтобы модель это помнила.',
        'm8.card.place.title': '{name}: {key}',
        'm8.card.place.body': '{statement}\nОтмечу это в описании места.',
        'm8.placeKey.condition': 'состояние',
        'm8.placeKey.owner': 'владелец',
        'm8.placeKey.decoration': 'убранство',
        'm8.placeKey.other': 'изменение',
        'm8.notice.alias': 'Запомнил прозвище: {name} — «{alias}»',
        'm8.notice.aliasMany.one': 'Запомнил {count} прозвище',
        'm8.notice.aliasMany.few': 'Запомнил {count} прозвища',
        'm8.notice.aliasMany.many': 'Запомнил {count} прозвищ',
        'm8.notice.event': 'Записал в летопись: {what}',
        'm8.notice.eventMany.one': 'Записал в летопись {count} важный момент',
        'm8.notice.eventMany.few': 'Записал в летопись {count} важных момента',
        'm8.notice.eventMany.many': 'Записал в летопись {count} важных моментов',
        'm8.notice.place': 'Отметил про {name}: {what}',
        'm8.notice.placeMany.one': 'Отметил {count} перемену в местах',
        'm8.notice.placeMany.few': 'Отметил {count} перемены в местах',
        'm8.notice.placeMany.many': 'Отметил {count} перемен в местах',
        'm8.details.entry': 'Запись: {value}',
        'm8.details.book': 'Книга: {value}',
        'm8.details.english': 'Текст канона (англ.): {value}',
        'm8.details.replaces': 'Заменяет: {value}',
        'm8.details.conflict': 'Противоречие: {value}',
        'm8.details.tagsAdded': 'Добавить теги: {value}',
        'm8.details.tagsRemoved': 'Убрать теги: {value}',
        'm8.details.ckRescan': 'После изменения CarrotKernel перечитает книги.',
        'm8.details.slot': 'Слот паспорта: {value}',
        'm8.details.naiTags': 'Теги NAI: {value}',
        'm8.details.field': 'Поле: {value}',
        'target.revision.canon': 'Канон чата',
        'target.revision.ck': 'Лист характера',
        'target.revision.keys': 'Ключевые слова записи',
        'target.revision.passport': 'Внешность для картинок',
        'target.revision.alias': 'Прозвище',
        'target.revision.place': 'Место',
        'target.revision.note': 'Новое имя (для DES)',
        'target.revision.event': 'Летопись',
        'm8.field.alias': 'Прозвище',
        'm8.field.entity': 'Кто',
        'm8.field.name': 'Имя',
        'm8.inbox.edit': 'Изменить',
        'm8.inbox.editLabel': 'Новое значение',
        'm8.inbox.save': 'Сохранить и принять',
        'm8.inbox.cancel': 'Отмена',
        'm8.inbox.editFailed': '«{title}» не применено: проверь значение (подробности — в журнале ошибок).',
        'm8.inbox.always': 'Всегда так',
        'm8.inbox.always.hint': 'Принять, и дальше такие изменения я делаю сам',
        'm8.inbox.always.done': 'Хорошо: «{kind}» дальше делаю сам. Вернуть можно в настройках.',
        'm8.inbox.snooze.hint': 'Отложить до завтра',
        'm8.inbox.confidence': 'уверенность {value}%',
        'm8.inbox.other': 'Прочее',
        'm8.inbox.deferred.title': 'Отложено',
        'm8.inbox.deferred.hint': 'Изменения для модулей следующих этапов; ждут здесь, пока эти модули не появятся.',
        'm8.inbox.deferred.stage': 'Отложено до этапа {stage}',
        'm8.inbox.deferred.dismiss': 'Убрать',
        'kind.canon.fact': 'Перемены в известном о персонажах и местах',
        'kind.ck.tags': 'Перемены в характере',
        'kind.nai.appearance': 'Стойкие перемены во внешности',
        'kind.chat.alias': 'Прозвища',
        'kind.des.alias': 'Новые имена персонажей',
        'kind.chronicle.event': 'Важные моменты для летописи',
        'kind.places.state': 'Перемены в местах',
    },
};
