// M4 «Страж настроек и вкладок» strings. Russian is the primary language; the user is addressed with masculine
// or neutral forms.
import type { I18nParts } from '../../shared/contracts';

export const GUARDIAN_STRINGS: I18nParts = {
    en: {
        'm4.title': 'Settings and tab guardian',
        'm4.tab': 'Guardian',
        'kind.guardian.drift': 'Settings drift from the baseline',

        'm4.state.fresh': 'This tab is up to date',
        'm4.state.stale': 'This tab is out of date',
        'm4.state.checking': 'Checking the tab…',
        'm4.state.unknown': 'Tab state unknown (the server did not answer)',

        'm4.banner.title': 'This tab is out of date',
        'm4.banner.text':
            'Settings were saved in another tab or on another device. Saves from this tab are held so they do not overwrite them.',
        'm4.banner.held': 'Held: {list}.',
        'm4.banner.vetoed': 'Not saved (older copies): {list}.',
        'm4.banner.overwrites': 'Saving from this tab would overwrite:',
        'm4.banner.more': '…and {count} more',
        'm4.banner.reload': 'Reload',
        'm4.banner.saveAnyway': 'Save anyway',
        'm4.banner.saveAnywayHint': "This tab's settings replace what the other tab saved.",
        'm4.kind.settings': 'settings',
        'm4.kind.preset': 'presets',
        'm4.kind.worldinfo': 'lorebooks',

        'm4.view.tab': 'Tab',
        'm4.view.lastCheck': 'Last check: {time}',
        'm4.view.checkTab': 'Check now',
        'm4.view.baseline': 'Baseline',
        'm4.view.baselineAt': 'Taken {time} ({reason}).',
        'm4.view.noBaseline': 'No baseline yet.',
        'm4.view.take': 'Take baseline',
        'm4.view.drift': 'Changes since the baseline',
        'm4.view.loading': 'Comparing…',
        'm4.view.noDrift': 'Everything matches the baseline.',
        'm4.view.what': 'What',
        'm4.view.baselineValue': 'Baseline',
        'm4.view.currentValue': 'Now',
        'm4.view.restore': 'Restore',
        'm4.view.accept': 'Keep',
        'm4.view.restoreAll': 'Restore all',
        'm4.view.acceptAll': 'Keep all as the baseline',
        'm4.reason.manual': 'by hand',
        'm4.reason.first-start': 'first start',
        'm4.reason.wizard': 'first-run wizard',

        'm4.notice.taken': 'Baseline taken.',
        'm4.notice.restored': 'Settings restored: {count}.',
        'm4.journal.restore': 'Settings restored from the baseline: {count}',

        'm4.card.title': 'Settings changed since the baseline: {count}',
        'm4.card.intro':
            'Accept — restore the baseline values (what cannot be restored becomes the new baseline). Reject — keep everything as it is.',
        'm4.card.more': '…and {count} more',
        'm4.confirm.presetTitle': 'Restore the whole preset?',
        'm4.confirm.presetBody':
            'The preset "{name}" will be saved with its baseline content and selected. Unsaved changes of the current preset are lost.',

        'm4.value.added': 'added',
        'm4.value.removed': 'removed',
        'm4.value.changed': 'was {before} → now {after}',
        'm4.value.changedOpaque': 'changed',

        'm4.group.preset': 'Preset',
        'm4.group.regex': 'Regex',
        'm4.group.qvink': 'Qvink',
        'm4.group.ck': 'CarrotKernel',
        'm4.group.nai': 'NAI Studio',
        'm4.group.des': 'DES',
        'm4.group.worldInfo': 'Lorebooks',
        'm4.group.profiles': 'Connection profiles',
        'm4.group.extensions': 'Extensions',
        'm4.preset.name': 'active preset',
        'm4.preset.order': 'prompt order',
        'm4.preset.toggles': 'prompts on/off',
        'm4.preset.roles': 'prompt roles',
        'm4.preset.contents': 'prompt texts',
        'm4.preset.body': 'samplers and other preset fields',
    },
    ru: {
        'm4.title': 'Страж настроек и вкладок',
        'm4.tab': 'Страж',
        'kind.guardian.drift': 'Настройки разошлись с эталоном',

        'm4.state.fresh': 'Вкладка актуальна',
        'm4.state.stale': 'Вкладка устарела',
        'm4.state.checking': 'Проверяю вкладку…',
        'm4.state.unknown': 'Состояние вкладки неизвестно (сервер не ответил)',

        'm4.banner.title': 'Вкладка устарела',
        'm4.banner.text':
            'Настройки сохранили в другой вкладке или на другом устройстве. Сохранения из этой вкладки задержаны, чтобы не затереть их.',
        'm4.banner.held': 'Задержано: {list}.',
        'm4.banner.vetoed': 'Не сохранено (старые копии): {list}.',
        'm4.banner.overwrites': 'Сохранение из этой вкладки перезапишет:',
        'm4.banner.more': '…и ещё {count}',
        'm4.banner.reload': 'Перезагрузить',
        'm4.banner.saveAnyway': 'Сохранить всё равно',
        'm4.banner.saveAnywayHint': 'Настройки этой вкладки заменят то, что сохранила другая.',
        'm4.kind.settings': 'настройки',
        'm4.kind.preset': 'пресеты',
        'm4.kind.worldinfo': 'лорбуки',

        'm4.view.tab': 'Вкладка',
        'm4.view.lastCheck': 'Последняя проверка: {time}',
        'm4.view.checkTab': 'Проверить сейчас',
        'm4.view.baseline': 'Эталон',
        'm4.view.baselineAt': 'Снят {time} ({reason}).',
        'm4.view.noBaseline': 'Эталона пока нет.',
        'm4.view.take': 'Снять эталон',
        'm4.view.drift': 'Что изменилось после эталона',
        'm4.view.loading': 'Сравниваю…',
        'm4.view.noDrift': 'Всё совпадает с эталоном.',
        'm4.view.what': 'Что',
        'm4.view.baselineValue': 'Эталон',
        'm4.view.currentValue': 'Сейчас',
        'm4.view.restore': 'Вернуть',
        'm4.view.accept': 'Оставить',
        'm4.view.restoreAll': 'Вернуть всё',
        'm4.view.acceptAll': 'Оставить всё как эталон',
        'm4.reason.manual': 'вручную',
        'm4.reason.first-start': 'при первом запуске',
        'm4.reason.wizard': 'в мастере первого запуска',

        'm4.notice.taken': 'Эталон снят.',
        'm4.notice.restored': 'Восстановлено настроек: {count}.',
        'm4.journal.restore': 'Настройки возвращены к эталону: {count}',

        'm4.card.title': 'Настройки разошлись с эталоном: {count}',
        'm4.card.intro':
            'Принять — вернуть значения эталона (то, что вернуть нельзя, станет новым эталоном). Отклонить — оставить всё как есть.',
        'm4.card.more': '…и ещё {count}',
        'm4.confirm.presetTitle': 'Вернуть пресет целиком?',
        'm4.confirm.presetBody':
            'Пресет «{name}» сохранится в том виде, что был в эталоне, и станет активным. Несохранённые правки текущего пресета пропадут.',

        'm4.value.added': 'добавлено',
        'm4.value.removed': 'удалено',
        'm4.value.changed': 'было {before} → стало {after}',
        'm4.value.changedOpaque': 'изменено',

        'm4.group.preset': 'Пресет',
        'm4.group.regex': 'Регекс',
        'm4.group.qvink': 'Qvink',
        'm4.group.ck': 'CarrotKernel',
        'm4.group.nai': 'NAI Studio',
        'm4.group.des': 'DES',
        'm4.group.worldInfo': 'Лорбуки',
        'm4.group.profiles': 'Профили подключения',
        'm4.group.extensions': 'Расширения',
        'm4.preset.name': 'активный пресет',
        'm4.preset.order': 'порядок блоков',
        'm4.preset.toggles': 'включённые блоки',
        'm4.preset.roles': 'роли блоков',
        'm4.preset.contents': 'тексты блоков',
        'm4.preset.body': 'сэмплеры и прочие поля пресета',
    },
};
