// M4 «Страж настроек и вкладок» strings. Russian is the primary language; the user is addressed with masculine
// or neutral forms.
import type { I18nParts } from '../../shared/contracts';

export const GUARDIAN_STRINGS: I18nParts = {
    en: {
        'm4.title': 'Settings and tab guardian',
        'm4.tab': 'Guardian',
        'kind.guardian.drift': 'Settings changed since the baseline',
        'kind.guardian.restore': 'Settings put back to the baseline',
        'target.guardian-setting': 'Setting',

        'm4.state.fresh': 'This tab is up to date',
        'm4.state.stale': 'This tab is out of date',
        'm4.state.checking': 'Checking the tab…',
        'm4.state.unknown': 'Tab state unknown (the server did not answer)',

        'm4.banner.title': 'This tab is out of date',
        'm4.banner.text':
            'Settings were saved in another tab or on another device. Saves from this tab are held so they do not overwrite them.',
        'm4.banner.held': 'Held: {list}.',
        'm4.banner.vetoed': 'Not saved (older copies): {list}.',
        'm4.banner.overwrites': 'Saving from this tab would overwrite:',
        'm4.banner.more': '…and {count} more',
        'm4.banner.reload': 'Reload',
        'm4.banner.saveAnyway': 'Save anyway',
        'm4.banner.saveAnywayHint': "This tab's settings replace what the other tab saved.",
        'm4.kind.settings': 'settings',
        'm4.kind.preset': 'presets',
        'm4.kind.worldinfo': 'lorebooks',

        'm4.view.tab': 'Tab',
        'm4.view.lastCheck': 'Last check: {time}',
        'm4.view.checkTab': 'Check now',
        'm4.view.baseline': 'Baseline',
        'm4.view.baselineAt': 'Taken {time} ({reason}).',
        'm4.view.noBaseline': 'No baseline yet.',
        'm4.view.scope':
            'The baseline keeps system settings only: the preset and how the model is called, regexes, how lorebooks are scanned, which extensions are on and how they behave. Which lorebooks are on, chats, characters, personas and styles picked in panels do not count.',
        'm4.view.take': 'Take baseline',
        'm4.view.drift': 'Changes since the baseline',
        'm4.view.loading': 'Comparing…',
        'm4.view.noDrift': 'Everything matches the baseline.',
        'm4.view.what': 'What',
        'm4.view.baselineValue': 'Baseline',
        'm4.view.currentValue': 'Now',
        'm4.view.restore': 'Restore',
        'm4.view.accept': 'Keep',
        'm4.view.restoreAll': 'Restore all',
        'm4.view.acceptAll': 'Keep all as the baseline',
        'm4.reason.manual': 'by hand',
        'm4.reason.first-start': 'first start',
        'm4.reason.wizard': 'first-run wizard',

        'm4.notice.taken': 'Saved the current settings as the baseline.',
        'm4.notice.restored': 'Put settings back to the baseline: {count}.',
        'm4.journal.restore': 'Settings put back to the baseline: {count}',

        'm4.card.title.one': '{count} setting changed since the baseline — put it back?',
        'm4.card.title.few': '{count} settings changed since the baseline — put them back?',
        'm4.card.title.many': '{count} settings changed since the baseline — put them back?',
        'm4.card.lead':
            'Since the baseline snapshot these settings changed — by hand, by another extension or by an update: {where}.',
        'm4.card.intro':
            'Accept — put the baseline values back (what cannot be put back becomes the new baseline). Reject — keep everything as it is.',
        'm4.card.more': '…and {count} more',
        'm4.confirm.presetTitle': 'Restore the whole preset?',
        'm4.confirm.presetBody':
            'The preset "{name}" will be saved with its baseline content (with the model and its settings) and selected. Unsaved changes of the current preset are lost.',

        'm4.value.added': 'added',
        'm4.value.removed': 'removed',
        'm4.value.changed': 'was {before} → now {after}',
        'm4.value.changedOpaque': 'changed',

        'm4.group.preset': 'Preset',
        'm4.group.regex': 'Regex',
        'm4.group.qvink': 'Qvink',
        'm4.group.ck': 'CarrotKernel',
        'm4.group.nai': 'NAI Studio',
        'm4.group.des': 'DES',
        'm4.group.worldInfo': 'Lorebook settings',
        'm4.group.profiles': 'Connection profiles',
        'm4.group.extensions': 'Extensions',
        'm4.group.api': 'Connection',
        'm4.preset.name': 'active preset',
        'm4.preset.order': 'prompt order',
        'm4.preset.toggles': 'prompts on/off',
        'm4.preset.roles': 'prompt roles',
        'm4.preset.contents': 'prompt texts',
        'm4.preset.body': 'samplers and other preset fields',
        'm4.api.mainApi': 'API type',
        'm4.api.profile': 'connection profile',
        'm4.api.model': 'source and model',
        'm4.api.maxContext': 'context size',
        'm4.api.maxTokens': 'reply length',
        'm4.api.reasoningEffort': 'reasoning effort',
        'm4.api.showThoughts': 'show thoughts',
        'm4.api.stream': 'streaming',
        'm4.api.instruct': 'instruct template',
        'm4.api.context': 'context template',
        'm4.api.sysprompt': 'system prompt',
        'm4.api.reasoningTemplate': 'reasoning template',
        'm4.api.reasoningParse': 'reasoning parsing',
        'm4.api.reasoningAddToPrompts': 'reasoning sent back to the model',
        'm4.qvink.profile': 'profile "{name}"',
        'm4.qvink.notify_on_profile_switch': 'notice on profile switch',
        'm4.profiles.list': 'list',
        'm4.extensions.disabled': 'turned off',
        'm4.extensions.version': 'version of {name}',
        'm4.worldInfo.world_info_depth': 'scan depth',
        'm4.worldInfo.world_info_min_activations': 'minimum activations',
        'm4.worldInfo.world_info_min_activations_depth_max': 'depth limit for minimum activations',
        'm4.worldInfo.world_info_budget': 'budget (% of context)',
        'm4.worldInfo.world_info_include_names': 'names in the scan',
        'm4.worldInfo.world_info_recursive': 'recursive scan',
        'm4.worldInfo.world_info_overflow_alert': 'budget overflow alert',
        'm4.worldInfo.world_info_case_sensitive': 'case-sensitive keys',
        'm4.worldInfo.world_info_match_whole_words': 'whole words only',
        'm4.worldInfo.world_info_character_strategy': 'order of character lore',
        'm4.worldInfo.world_info_budget_cap': 'budget cap',
        'm4.worldInfo.world_info_use_group_scoring': 'group scoring',
        'm4.worldInfo.world_info_max_recursion_steps': 'recursion steps',
    },
    ru: {
        'm4.title': 'Страж настроек и вкладок',
        'm4.tab': 'Страж',
        'kind.guardian.drift': 'Настройки изменились после эталона',
        'kind.guardian.restore': 'Возврат настроек к эталону',
        'target.guardian-setting': 'Настройка',

        'm4.state.fresh': 'Вкладка актуальна',
        'm4.state.stale': 'Вкладка устарела',
        'm4.state.checking': 'Проверяю вкладку…',
        'm4.state.unknown': 'Состояние вкладки неизвестно (сервер не ответил)',

        'm4.banner.title': 'Вкладка устарела',
        'm4.banner.text':
            'Настройки сохранили в другой вкладке или на другом устройстве. Сохранения из этой вкладки задержаны, чтобы не затереть их.',
        'm4.banner.held': 'Задержано: {list}.',
        'm4.banner.vetoed': 'Не сохранено (старые копии): {list}.',
        'm4.banner.overwrites': 'Сохранение из этой вкладки перезапишет:',
        'm4.banner.more': '…и ещё {count}',
        'm4.banner.reload': 'Перезагрузить',
        'm4.banner.saveAnyway': 'Сохранить всё равно',
        'm4.banner.saveAnywayHint': 'Настройки этой вкладки заменят то, что сохранила другая.',
        'm4.kind.settings': 'настройки',
        'm4.kind.preset': 'пресеты',
        'm4.kind.worldinfo': 'книги лора',

        'm4.view.tab': 'Вкладка',
        'm4.view.lastCheck': 'Последняя проверка: {time}',
        'm4.view.checkTab': 'Проверить сейчас',
        'm4.view.baseline': 'Эталон',
        'm4.view.baselineAt': 'Снят {time} ({reason}).',
        'm4.view.noBaseline': 'Эталона пока нет.',
        'm4.view.scope':
            'Эталон хранит только системные настройки: пресет и то, как вызывается модель, регексы, как ищутся записи лорбуков, какие расширения включены и как они работают. Какие лорбуки включены, чаты, персонажи, персоны и стили, выбранные в панелях, не в счёт.',
        'm4.view.take': 'Снять эталон',
        'm4.view.drift': 'Что изменилось после эталона',
        'm4.view.loading': 'Сравниваю…',
        'm4.view.noDrift': 'Всё совпадает с эталоном.',
        'm4.view.what': 'Что',
        'm4.view.baselineValue': 'Эталон',
        'm4.view.currentValue': 'Сейчас',
        'm4.view.restore': 'Вернуть',
        'm4.view.accept': 'Оставить',
        'm4.view.restoreAll': 'Вернуть всё',
        'm4.view.acceptAll': 'Оставить всё как эталон',
        'm4.reason.manual': 'вручную',
        'm4.reason.first-start': 'при первом запуске',
        'm4.reason.wizard': 'в мастере первого запуска',

        'm4.notice.taken': 'Запомнил текущие настройки как эталон.',
        'm4.notice.restored': 'Вернул настройки к эталону: {count}.',
        'm4.journal.restore': 'Возврат настроек к эталону: {count}',

        'm4.card.title.one': 'После эталона изменилась {count} настройка — вернуть как было?',
        'm4.card.title.few': 'После эталона изменились {count} настройки — вернуть как было?',
        'm4.card.title.many': 'После эталона изменилось {count} настроек — вернуть как было?',
        'm4.card.lead':
            'С момента снимка-эталона эти настройки поменялись — вручную, другим расширением или обновлением: {where}.',
        'm4.card.intro':
            'Принять — вернуть прежние значения (то, что вернуть нельзя, станет новым эталоном). Отклонить — оставить всё как есть.',
        'm4.card.more': '…и ещё {count}',
        'm4.confirm.presetTitle': 'Вернуть пресет целиком?',
        'm4.confirm.presetBody':
            'Пресет «{name}» сохранится в том виде, что был в эталоне (вместе с моделью и её настройками), и станет активным. Несохранённые правки текущего пресета пропадут.',

        'm4.value.added': 'добавлено',
        'm4.value.removed': 'удалено',
        'm4.value.changed': 'было {before} → стало {after}',
        'm4.value.changedOpaque': 'изменено',

        'm4.group.preset': 'Пресет',
        'm4.group.regex': 'Регекс',
        'm4.group.qvink': 'Qvink',
        'm4.group.ck': 'CarrotKernel',
        'm4.group.nai': 'NAI Studio',
        'm4.group.des': 'DES',
        'm4.group.worldInfo': 'Настройки лорбуков',
        'm4.group.profiles': 'Профили подключения',
        'm4.group.extensions': 'Расширения',
        'm4.group.api': 'Подключение',
        'm4.preset.name': 'активный пресет',
        'm4.preset.order': 'порядок блоков',
        'm4.preset.toggles': 'включённые блоки',
        'm4.preset.roles': 'роли блоков',
        'm4.preset.contents': 'тексты блоков',
        'm4.preset.body': 'сэмплеры и прочие поля пресета',
        'm4.api.mainApi': 'тип API',
        'm4.api.profile': 'профиль подключения',
        'm4.api.model': 'источник и модель',
        'm4.api.maxContext': 'размер контекста',
        'm4.api.maxTokens': 'длина ответа',
        'm4.api.reasoningEffort': 'сила рассуждений',
        'm4.api.showThoughts': 'показ мыслей',
        'm4.api.stream': 'потоковый вывод',
        'm4.api.instruct': 'шаблон инструкций',
        'm4.api.context': 'шаблон контекста',
        'm4.api.sysprompt': 'системный промпт',
        'm4.api.reasoningTemplate': 'шаблон рассуждений',
        'm4.api.reasoningParse': 'разбор рассуждений',
        'm4.api.reasoningAddToPrompts': 'рассуждения обратно в промпт',
        'm4.qvink.profile': 'профиль «{name}»',
        'm4.qvink.notify_on_profile_switch': 'сообщать о смене профиля',
        'm4.profiles.list': 'список',
        'm4.extensions.disabled': 'выключенные',
        'm4.extensions.version': 'версия {name}',
        'm4.worldInfo.world_info_depth': 'глубина поиска',
        'm4.worldInfo.world_info_min_activations': 'минимум срабатываний',
        'm4.worldInfo.world_info_min_activations_depth_max': 'предел глубины для минимума',
        'm4.worldInfo.world_info_budget': 'бюджет (% контекста)',
        'm4.worldInfo.world_info_include_names': 'имена в поиске',
        'm4.worldInfo.world_info_recursive': 'рекурсивный поиск',
        'm4.worldInfo.world_info_overflow_alert': 'предупреждение о переполнении',
        'm4.worldInfo.world_info_case_sensitive': 'с учётом регистра',
        'm4.worldInfo.world_info_match_whole_words': 'только целые слова',
        'm4.worldInfo.world_info_character_strategy': 'порядок лора персонажа',
        'm4.worldInfo.world_info_budget_cap': 'потолок бюджета',
        'm4.worldInfo.world_info_use_group_scoring': 'очки групп',
        'm4.worldInfo.world_info_max_recursion_steps': 'шаги рекурсии',
    },
};
