import type { I18nParts } from '../../shared/contracts';

/** Strings of the UI shell and core views (`ui.*`). Russian is the primary UI language. */
export const UI_STRINGS: I18nParts = {
    en: {
        'ui.title': 'Maestro',
        'ui.refresh': 'Refresh',
        'ui.actionFailed': 'Action failed: {error}',
        'ui.notice.tapTo': '(click: {label})',
        'ui.confirm.yes': 'Yes',
        'ui.confirm.no': 'No',

        'ui.entry.topTitle': 'Maestro — open the control panel',
        'ui.entry.topTitleCount': 'Maestro — {count} waiting',
        'ui.entry.topTitleJob': '{title}: {status}',
        'ui.entry.topTitleJobs': 'your tasks running: {count}',
        'ui.entry.wandTitle': 'Open the Maestro control panel',
        'ui.entry.description':
            'Conductor of the extension stack: one canon, one prompt, one panel. Everything lives in the control panel.',
        'ui.entry.open': 'Open Maestro',

        'ui.pult.tabs': 'Maestro sections',
        'ui.pult.close': 'Close',
        'ui.pult.noTabs': 'Nothing here yet.',
        'ui.pult.renderFailed': 'This section failed to open. Details are in the browser console.',

        'ui.tab.overview': 'Overview',
        'ui.tab.inbox': 'Inbox',
        'ui.tab.health': 'Health',
        'ui.tab.tasks': 'Tasks',
        'ui.tab.journal': 'Journal',
        'ui.tab.settings': 'Settings',

        'ui.group.turn': 'Turn',
        'ui.group.inbox': 'Inbox',
        'ui.group.canon': 'Canon',
        'ui.group.dossier': 'Dossier',
        'ui.group.world': 'World',
        'ui.group.mechanics': 'Mechanics',
        'ui.group.health': 'Health',
        'ui.group.journal': 'Journal',
        'ui.group.assistant': 'Assistant',
        'ui.group.extensions': 'Extensions',
        'ui.group.settings': 'Settings',
        'ui.group.more': 'More',
        'ui.group.collapse': 'Collapse the group',
        'ui.group.expand': 'Expand the group',

        'ui.lamp.ok': 'Works',
        'ui.lamp.warn': 'Partly works',
        'ui.lamp.error': 'Not available',

        'ui.mode.economy': 'Economy',
        'ui.mode.balanced': 'Balanced',
        'ui.mode.cinema': 'Cinema',
        'ui.mode.economyHint':
            'Minimum background AI: cheap checks only; the director only sets scene flags (no notes), no backstage.',
        'ui.mode.balancedHint': 'Revisions on signals, AI judge only when in doubt. The default.',
        'ui.mode.cinemaHint': 'More director, backstage and pictures; costs more.',

        'ui.overview.groupChat': 'Group chats are not supported: Maestro sleeps in this chat.',
        'ui.overview.textCompletion':
            'Text Completion API: studios and generation scenarios fall back to the classic windows.',
        'ui.overview.inbox': 'Inbox',
        'ui.overview.inboxCount': 'Proposals waiting: {count}',
        'ui.overview.inboxEmpty': 'Nothing waiting for a decision.',
        'ui.overview.openInbox': 'Open',
        'ui.overview.mode': 'Mode',
        'ui.overview.cost': 'Spend today',
        'ui.overview.stack': 'Extension stack',
        'ui.overview.stackEmpty': 'No capability checks yet.',
        'ui.overview.capsCount': '{ok} of {total}',
        'ui.overview.capsMissing': 'Missing: {count}',
        'ui.overview.modules': 'Modules',
        'ui.overview.notices': 'Notices',
        'ui.overview.noticesEmpty': 'No notices.',
        'ui.overview.clearNotices': 'Clear',

        'ui.stack.st': 'SillyTavern',
        'ui.stack.des': "Doom's Enhancement Suite",
        'ui.stack.desru': 'DES-RU',
        'ui.stack.ck': 'CarrotKernel',
        'ui.stack.bunnymo': 'BunnyMo',
        'ui.stack.qvink': 'Qvink Memory',
        'ui.stack.nai': 'NAI Studio',
        'ui.stack.localizer': 'Lorebook Localizer',
        'ui.stack.preset': 'Preset',

        'ui.cost.today': 'Total',
        'ui.cost.background': 'Maestro background',
        'ui.cost.backgroundOfCap': '{spent} of {cap}',
        'ui.cost.backgroundNoCap': '{spent} (no cap)',
        'ui.cost.anlas': 'Anlas',
        'ui.cost.capReached':
            'The background cap is reached: background tasks wait until tomorrow or until the cap is raised.',
        'ui.cost.bySource': 'Spend by source',
        'ui.cost.source': 'Source',
        'ui.cost.usd': 'USD',
        'ui.cost.source.main': 'Main chat',
        'ui.cost.source.qvink': 'Qvink summaries',
        'ui.cost.source.maestro': 'Maestro',
        'ui.cost.source.nai': 'NovelAI',
        'ui.cost.source.other': 'Other',

        'ui.modules.stage': 'Stage',
        'ui.modules.module': 'Module',
        'ui.modules.status': 'Status',
        'ui.modules.missing': 'Missing',
        'ui.modules.running': 'Running',
        'ui.modules.off': 'Off',
        'ui.modules.blocked': 'Waiting for capabilities',
        'ui.modules.stopped': 'Not running',
        'ui.modules.none': 'No modules yet: they arrive with the next stages.',

        'ui.inbox.title': 'Proposals',
        'ui.inbox.empty': 'Inbox is empty.',
        'ui.inbox.accept': 'Accept',
        'ui.inbox.reject': 'Reject',
        'ui.inbox.snooze': 'Tomorrow',
        'ui.inbox.acceptAll': 'Accept all ({count})',
        'ui.inbox.acceptAllDone': 'Accepted: {accepted}.',
        'ui.inbox.acceptAllPartial': 'Accepted: {accepted}; out of date and skipped: {failed}.',
        'ui.inbox.stale': '“{title}” is out of date: the data changed since the proposal.',
        'ui.inbox.deferred': 'Waits for a module',
        'ui.inbox.deferredHint': 'This proposal needs a module of a later stage.',
        'ui.inbox.expires': 'until {time}',
        'ui.inbox.source': 'Message #{index}',

        'ui.diff.before': 'Before',
        'ui.diff.after': 'After',
        'ui.diff.added': 'Added',
        'ui.diff.removed': 'Removed',
        'ui.diff.value': 'Value',
        'ui.diff.noChanges': 'No changes.',
        'ui.diff.unchanged': 'Unchanged fields: {count}',

        'ui.journal.title': 'Actions',
        'ui.journal.empty': 'No actions yet.',
        'ui.journal.filter': 'Module filter',
        'ui.journal.allModules': 'All modules',
        'ui.journal.changes': 'Changes: {count}',
        'ui.journal.undo': 'Undo',
        'ui.journal.undoneLabel': 'Undone',
        'ui.journal.undoDone': 'Undone: {summary}',
        'ui.journal.undoFailed': 'Could not undo: {summary}',
        'ui.journal.stats': 'Decision stats',
        'ui.journal.statsEmpty': 'No decisions yet.',
        'ui.journal.kind': 'Action kind',
        'ui.journal.accepted': 'Accepted',
        'ui.journal.edited': 'Edited',
        'ui.journal.rejected': 'Rejected',
        'ui.journal.undoneCount': 'Undone',
        'ui.journal.streak': 'In a row',

        'ui.health.checks': 'Checks',
        'ui.health.noChecks': 'No checks registered yet.',
        'ui.health.runAll': 'Run again',
        'ui.health.fix': 'Fix',
        'ui.health.status.ok': 'OK',
        'ui.health.status.warn': 'Warning',
        'ui.health.status.error': 'Problem',
        'ui.health.status.skip': 'Skipped',
        'ui.health.status.running': 'Checking…',
        'ui.health.capabilities': 'Capabilities',
        'ui.health.recheck': 'Recheck',
        'ui.health.state': 'State',
        'ui.health.capability': 'Capability',
        'ui.health.detail': 'Details',
        'ui.health.log': 'Recent warnings and errors',
        'ui.health.logEmpty': 'No warnings.',

        'ui.tasks.title': 'Background tasks',
        'ui.tasks.empty': 'The queue is empty.',
        'ui.tasks.kind': 'Task',
        'ui.tasks.state': 'State',
        'ui.tasks.attempts': 'Attempts',
        'ui.tasks.created': 'Created',
        'ui.tasks.error': 'Error',
        'ui.tasks.kick': 'Run now',
        'ui.tasks.hint': 'Tasks run only in the leading tab and never during a generation.',
        'ui.tasks.state.pending': 'Waiting',
        'ui.tasks.state.running': 'Running',
        'ui.tasks.state.done': 'Done',
        'ui.tasks.state.failed': 'Failed',
        'ui.tasks.state.expired': 'Expired',

        'ui.jobs.title': 'Your tasks',
        'ui.jobs.empty': 'Nothing you started is running.',
        'ui.jobs.hint':
            'Tasks you started yourself. They keep going when you close the window you started them in; finished ones stay here for 10 minutes.',
        'ui.jobs.queued': 'Waiting for its turn…',
        'ui.jobs.running': 'Working…',
        'ui.jobs.saving': 'Saving…',
        'ui.jobs.progress': '{done} of {total}',
        'ui.jobs.stopping': 'Stopping after the current step…',
        'ui.jobs.started': 'started at {time}',
        'ui.jobs.stop': 'Stop',
        'ui.jobs.open': 'Open',
        'ui.jobs.hide': 'Hide',

        'ui.settings.general': 'General',
        'ui.settings.language': 'Interface language',
        'ui.settings.language.auto': 'As in SillyTavern',
        'ui.settings.language.ru': 'Русский',
        'ui.settings.language.en': 'English',
        'ui.settings.mode': 'Mode',
        'ui.settings.modeHint': 'Each module can still be switched on or off on top of the mode.',
        'ui.settings.debug': 'Debug mode',
        'ui.settings.debugHint': 'Detailed log in the browser console.',
        'ui.settings.budget': 'Budget',
        'ui.settings.backgroundCap': 'Background cap per day, USD',
        'ui.settings.backgroundCapHint': "Maestro's own background AI spend; 0 means no cap.",
        'ui.settings.dailyLimit': 'Overall daily limit',
        'ui.settings.dailyLimitHint': 'Counts the main chat too. Off by default.',
        'ui.settings.dailyLimitUsd': 'Limit per day, USD',
        'ui.settings.dailyLimitAction': 'When reached',
        'ui.settings.limitAction.warn': 'Warn',
        'ui.settings.limitAction.economy': 'Switch to Economy',
        'ui.settings.limitAction.stopBackground': 'Stop background tasks',
        'ui.settings.profiles': 'Connection profiles',
        'ui.settings.profilesHint':
            'Background tasks go through saved Connection Manager profiles; the active connection is not switched.',
        'ui.settings.profileDefault': 'Main background profile',
        'ui.settings.profileFallback': 'Fallback profile',
        'ui.settings.profileNone': 'Not selected',
        'ui.settings.profileInherit': 'Same as main',
        'ui.settings.profileNoFallback': 'No fallback',
        'ui.settings.profileMissing': 'Missing profile ({id})',
        'ui.settings.noConnectionManager': 'Connection Manager is off: background tasks are not possible.',
        'ui.settings.autonomy': 'Autonomy levels',
        'ui.settings.autonomyHint': 'How Maestro handles each kind of action.',
        'ui.settings.autonomyEmpty': 'Action kinds appear here once modules start proposing changes.',
        'ui.settings.autonomyDefault': 'Module default',
        'ui.autonomy.auto': 'Auto',
        'ui.autonomy.notify': 'Notify',
        'ui.autonomy.inbox': 'Inbox',
        'ui.autonomy.ask': 'Ask',
        'ui.autonomy.off': 'Off',
        'ui.settings.modules': 'Modules',
        'ui.settings.moduleMissing': 'Missing capabilities: {caps}',
        'ui.settings.moduleToggleFailed': 'Could not switch “{title}”.',
        'ui.settings.data': 'Data',
        'ui.settings.export': 'Export Maestro data',
        'ui.settings.import': 'Import',
        'ui.settings.prepareDisable': 'Prepare to disable',
        'ui.settings.prepareDisableHint':
            '“Prepare to disable” moves chat canon into regular lorebooks and leaves the stack working without Maestro.',
        'ui.settings.actionUnavailable': 'Not available yet: this action arrives in a later version.',
        'ui.settings.runWizard': 'Run the first-run wizard again',

        'ui.slash.maestroOff': 'Maestro is disabled.',
        'ui.slash.moduleOff': '/{name} is unavailable: its Maestro module is off.',
        'ui.slash.failed': '/{name} failed: {error}',

        'ui.wizard.welcomeTitle': 'Welcome to Maestro',
        'ui.wizard.welcome1':
            'Maestro conducts your extension stack: it watches the lore, the prompt and the neighbours, fixes what breaks and keeps a canon for each chat.',
        'ui.wizard.welcome2':
            'Nothing important happens silently: proposals land in the Inbox, every action goes to the journal and can be undone.',
        'ui.wizard.welcome3': 'The control panel opens with the wand icon in the top bar. A few setup steps follow.',
        'ui.wizard.stepOf': 'Step {step} of {total}',
        'ui.wizard.back': 'Back',
        'ui.wizard.next': 'Next',
        'ui.wizard.skipStep': 'Skip',
        'ui.wizard.finish': 'Finish',
        'ui.wizard.skipAll': 'Skip setup',
        'ui.wizard.stepFailed': 'This step failed to open. It can be skipped.',
        'ui.wizard.finished': 'Setup complete.',
    },
    ru: {
        'ui.title': 'Maestro',
        'ui.refresh': 'Обновить',
        'ui.actionFailed': 'Не получилось: {error}',
        'ui.notice.tapTo': '(по нажатию: {label})',
        'ui.confirm.yes': 'Да',
        'ui.confirm.no': 'Нет',

        'ui.entry.topTitle': 'Maestro — открыть пульт',
        'ui.entry.topTitleCount': 'Maestro — ждут решения: {count}',
        'ui.entry.topTitleJob': '{title}: {status}',
        'ui.entry.topTitleJobs': 'идут твои задачи: {count}',
        'ui.entry.wandTitle': 'Открыть пульт Maestro',
        'ui.entry.description':
            'Дирижёр стека расширений: один канон, один промпт, один пульт. Всё управление — в пульте.',
        'ui.entry.open': 'Открыть Maestro',

        'ui.pult.tabs': 'Разделы Maestro',
        'ui.pult.close': 'Закрыть',
        'ui.pult.noTabs': 'Здесь пока пусто.',
        'ui.pult.renderFailed': 'Раздел не открылся. Подробности — в консоли браузера.',

        'ui.tab.overview': 'Обзор',
        'ui.tab.inbox': 'Входящие',
        'ui.tab.health': 'Здоровье',
        'ui.tab.tasks': 'Задачи',
        'ui.tab.journal': 'Журнал',
        'ui.tab.settings': 'Настройки',

        'ui.group.turn': 'Ход',
        'ui.group.inbox': 'Входящие',
        'ui.group.canon': 'Канон',
        'ui.group.dossier': 'Досье',
        'ui.group.world': 'Мир',
        'ui.group.mechanics': 'Механики',
        'ui.group.health': 'Здоровье',
        'ui.group.journal': 'Журнал',
        'ui.group.assistant': 'Ассистент',
        'ui.group.extensions': 'Расширения',
        'ui.group.settings': 'Настройки',
        'ui.group.more': 'Ещё',
        'ui.group.collapse': 'Свернуть группу',
        'ui.group.expand': 'Развернуть группу',

        'ui.lamp.ok': 'Работает',
        'ui.lamp.warn': 'Работает частично',
        'ui.lamp.error': 'Недоступно',

        'ui.mode.economy': 'Экономный',
        'ui.mode.balanced': 'Сбалансированный',
        'ui.mode.cinema': 'Кино',
        'ui.mode.economyHint':
            'Минимум фонового ИИ: только дешёвые проверки; режиссёр лишь ставит флаги сцены (без заметок), без закулисья.',
        'ui.mode.balancedHint': 'Ревизия по сигналам, ИИ-судья — только при подозрении. Режим по умолчанию.',
        'ui.mode.cinemaHint': 'Больше режиссёра, закулисья и картинок; дороже.',

        'ui.overview.groupChat': 'Групповые чаты не поддерживаются: в этом чате Maestro спит.',
        'ui.overview.textCompletion': 'Text Completion: студии и сценарии генерации уступают место классическим окнам.',
        'ui.overview.inbox': 'Входящие',
        'ui.overview.inboxCount': 'Ждут решения: {count}',
        'ui.overview.inboxEmpty': 'Решений не ждёт ничего.',
        'ui.overview.openInbox': 'Открыть',
        'ui.overview.mode': 'Режим',
        'ui.overview.cost': 'Расходы за сегодня',
        'ui.overview.stack': 'Стек расширений',
        'ui.overview.stackEmpty': 'Проверок возможностей пока нет.',
        'ui.overview.capsCount': '{ok} из {total}',
        'ui.overview.capsMissing': 'Не хватает: {count}',
        'ui.overview.modules': 'Модули',
        'ui.overview.notices': 'Уведомления',
        'ui.overview.noticesEmpty': 'Уведомлений нет.',
        'ui.overview.clearNotices': 'Очистить',

        'ui.stack.st': 'SillyTavern',
        'ui.stack.des': "Doom's Enhancement Suite",
        'ui.stack.desru': 'DES-RU',
        'ui.stack.ck': 'CarrotKernel',
        'ui.stack.bunnymo': 'BunnyMo',
        'ui.stack.qvink': 'Qvink Memory',
        'ui.stack.nai': 'NAI Studio',
        'ui.stack.localizer': 'Lorebook Localizer',
        'ui.stack.preset': 'Пресет',

        'ui.cost.today': 'Всего',
        'ui.cost.background': 'Фон Maestro',
        'ui.cost.backgroundOfCap': '{spent} из {cap}',
        'ui.cost.backgroundNoCap': '{spent} (без потолка)',
        'ui.cost.anlas': 'Anlas',
        'ui.cost.capReached':
            'Потолок фоновых расходов достигнут: фоновые задачи ждут завтрашнего дня или повышения потолка.',
        'ui.cost.bySource': 'Расходы по источникам',
        'ui.cost.source': 'Источник',
        'ui.cost.usd': 'USD',
        'ui.cost.source.main': 'Основной чат',
        'ui.cost.source.qvink': 'Пересказы Qvink',
        'ui.cost.source.maestro': 'Maestro',
        'ui.cost.source.nai': 'NovelAI',
        'ui.cost.source.other': 'Прочее',

        'ui.modules.stage': 'Этап',
        'ui.modules.module': 'Модуль',
        'ui.modules.status': 'Состояние',
        'ui.modules.missing': 'Не хватает',
        'ui.modules.running': 'Работает',
        'ui.modules.off': 'Выключен',
        'ui.modules.blocked': 'Ждёт возможностей',
        'ui.modules.stopped': 'Не запущен',
        'ui.modules.none': 'Модулей пока нет — они появятся на следующих этапах.',

        'ui.inbox.title': 'Предложения',
        'ui.inbox.empty': 'Во «Входящих» пусто.',
        'ui.inbox.accept': 'Принять',
        'ui.inbox.reject': 'Отклонить',
        'ui.inbox.snooze': 'Завтра',
        'ui.inbox.acceptAll': 'Принять все ({count})',
        'ui.inbox.acceptAllDone': 'Принято: {accepted}.',
        'ui.inbox.acceptAllPartial': 'Принято: {accepted}; устарели и пропущены: {failed}.',
        'ui.inbox.stale': '«{title}» устарело: данные изменились после предложения.',
        'ui.inbox.deferred': 'Ждёт модуля',
        'ui.inbox.deferredHint': 'Для этого предложения нужен модуль следующего этапа.',
        'ui.inbox.expires': 'до {time}',
        'ui.inbox.source': 'Сообщение №{index}',

        'ui.diff.before': 'Было',
        'ui.diff.after': 'Стало',
        'ui.diff.added': 'Добавлено',
        'ui.diff.removed': 'Удалено',
        'ui.diff.value': 'Значение',
        'ui.diff.noChanges': 'Изменений нет.',
        'ui.diff.unchanged': 'Без изменений: {count}',

        'ui.journal.title': 'Действия',
        'ui.journal.empty': 'Действий пока нет.',
        'ui.journal.filter': 'Фильтр по модулю',
        'ui.journal.allModules': 'Все модули',
        'ui.journal.changes': 'Изменения: {count}',
        'ui.journal.undo': 'Откатить',
        'ui.journal.undoneLabel': 'Откачено',
        'ui.journal.undoDone': 'Откачено: {summary}',
        'ui.journal.undoFailed': 'Откатить не удалось: {summary}',
        'ui.journal.stats': 'Статистика решений',
        'ui.journal.statsEmpty': 'Решений пока нет.',
        'ui.journal.kind': 'Вид действия',
        'ui.journal.accepted': 'Принято',
        'ui.journal.edited': 'Исправлено',
        'ui.journal.rejected': 'Отклонено',
        'ui.journal.undoneCount': 'Откачено',
        'ui.journal.streak': 'Подряд',

        'ui.health.checks': 'Проверки',
        'ui.health.noChecks': 'Проверок пока нет.',
        'ui.health.runAll': 'Проверить снова',
        'ui.health.fix': 'Исправить',
        'ui.health.status.ok': 'В порядке',
        'ui.health.status.warn': 'Предупреждение',
        'ui.health.status.error': 'Проблема',
        'ui.health.status.skip': 'Пропущено',
        'ui.health.status.running': 'Проверяется…',
        'ui.health.capabilities': 'Возможности',
        'ui.health.recheck': 'Перепроверить',
        'ui.health.state': 'Состояние',
        'ui.health.capability': 'Возможность',
        'ui.health.detail': 'Подробности',
        'ui.health.log': 'Последние предупреждения и ошибки',
        'ui.health.logEmpty': 'Предупреждений нет.',

        'ui.tasks.title': 'Фоновые задачи',
        'ui.tasks.empty': 'Очередь пуста.',
        'ui.tasks.kind': 'Задача',
        'ui.tasks.state': 'Состояние',
        'ui.tasks.attempts': 'Попытки',
        'ui.tasks.created': 'Создана',
        'ui.tasks.error': 'Ошибка',
        'ui.tasks.kick': 'Запустить сейчас',
        'ui.tasks.hint': 'Задачи выполняет только ведущая вкладка и никогда — во время генерации.',
        'ui.tasks.state.pending': 'Ждёт',
        'ui.tasks.state.running': 'Выполняется',
        'ui.tasks.state.done': 'Готово',
        'ui.tasks.state.failed': 'Сбой',
        'ui.tasks.state.expired': 'Устарела',

        'ui.jobs.title': 'Твои задачи',
        'ui.jobs.empty': 'Сейчас ничего из запущенного тобой не идёт.',
        'ui.jobs.hint':
            'Задачи, которые ты запустил сам. Они продолжаются, даже если закрыть окно, где ты их начал; готовые видны здесь 10 минут.',
        'ui.jobs.queued': 'Ждёт своей очереди…',
        'ui.jobs.running': 'Идёт…',
        'ui.jobs.saving': 'Сохраняю…',
        'ui.jobs.progress': '{done} из {total}',
        'ui.jobs.stopping': 'Останавливаю после текущего шага…',
        'ui.jobs.started': 'начата в {time}',
        'ui.jobs.stop': 'Остановить',
        'ui.jobs.open': 'Открыть',
        'ui.jobs.hide': 'Скрыть',

        'ui.settings.general': 'Общие',
        'ui.settings.language': 'Язык интерфейса',
        'ui.settings.language.auto': 'Как в SillyTavern',
        'ui.settings.language.ru': 'Русский',
        'ui.settings.language.en': 'English',
        'ui.settings.mode': 'Режим',
        'ui.settings.modeHint': 'Любой модуль можно включить или выключить отдельно поверх режима.',
        'ui.settings.debug': 'Режим отладки',
        'ui.settings.debugHint': 'Подробный журнал в консоли браузера.',
        'ui.settings.budget': 'Бюджет',
        'ui.settings.backgroundCap': 'Потолок фона в день, USD',
        'ui.settings.backgroundCapHint': 'Собственные фоновые запросы Maestro к ИИ; 0 — без потолка.',
        'ui.settings.dailyLimit': 'Общий дневной лимит',
        'ui.settings.dailyLimitHint': 'Учитывает и основной чат. По умолчанию выключен.',
        'ui.settings.dailyLimitUsd': 'Лимит в день, USD',
        'ui.settings.dailyLimitAction': 'Когда достигнут',
        'ui.settings.limitAction.warn': 'Предупредить',
        'ui.settings.limitAction.economy': 'Перейти в «Экономный»',
        'ui.settings.limitAction.stopBackground': 'Остановить фоновые задачи',
        'ui.settings.profiles': 'Профили подключения',
        'ui.settings.profilesHint':
            'Фоновые задачи идут через сохранённые профили Connection Manager; активное подключение не переключается.',
        'ui.settings.profileDefault': 'Основной фоновый профиль',
        'ui.settings.profileFallback': 'Запасной профиль',
        'ui.settings.profileNone': 'Не выбран',
        'ui.settings.profileInherit': 'Как основной',
        'ui.settings.profileNoFallback': 'Без запасного',
        'ui.settings.profileMissing': 'Профиль не найден ({id})',
        'ui.settings.noConnectionManager': 'Connection Manager выключен: фоновые задачи невозможны.',
        'ui.settings.autonomy': 'Уровни автономии',
        'ui.settings.autonomyHint': 'Как Maestro поступает с каждым видом действий.',
        'ui.settings.autonomyEmpty': 'Виды действий появятся здесь, когда модули начнут что-то предлагать.',
        'ui.settings.autonomyDefault': 'Как задано в модуле',
        'ui.autonomy.auto': 'Само',
        'ui.autonomy.notify': 'Уведомить',
        'ui.autonomy.inbox': 'Входящие',
        'ui.autonomy.ask': 'Спросить',
        'ui.autonomy.off': 'Выкл',
        'ui.settings.modules': 'Модули',
        'ui.settings.moduleMissing': 'Не хватает возможностей: {caps}',
        'ui.settings.moduleToggleFailed': 'Не удалось переключить «{title}».',
        'ui.settings.data': 'Данные',
        'ui.settings.export': 'Экспорт данных Maestro',
        'ui.settings.import': 'Импорт',
        'ui.settings.prepareDisable': 'Подготовить к отключению',
        'ui.settings.prepareDisableHint':
            '«Подготовить к отключению» переносит канон чатов в обычные лорбуки и оставляет стек рабочим без Maestro.',
        'ui.settings.actionUnavailable': 'Пока недоступно: это действие появится в следующих версиях.',
        'ui.settings.runWizard': 'Запустить мастер первого запуска снова',

        'ui.slash.maestroOff': 'Maestro отключён.',
        'ui.slash.moduleOff': '/{name} недоступна: её модуль Maestro выключен.',
        'ui.slash.failed': '/{name}: ошибка — {error}',

        'ui.wizard.welcomeTitle': 'Добро пожаловать в Maestro',
        'ui.wizard.welcome1':
            'Maestro дирижирует стеком расширений: следит за лором, промптом и соседями, чинит то, что ломается, и ведёт канон каждого чата.',
        'ui.wizard.welcome2':
            'Важное не делается молча: предложения попадают во «Входящие», каждое действие пишется в журнал и откатывается.',
        'ui.wizard.welcome3':
            'Пульт открывается значком волшебной палочки в верхней панели. Дальше — несколько шагов настройки.',
        'ui.wizard.stepOf': 'Шаг {step} из {total}',
        'ui.wizard.back': 'Назад',
        'ui.wizard.next': 'Далее',
        'ui.wizard.skipStep': 'Пропустить',
        'ui.wizard.finish': 'Готово',
        'ui.wizard.skipAll': 'Пропустить настройку',
        'ui.wizard.stepFailed': 'Шаг не открылся. Его можно пропустить.',
        'ui.wizard.finished': 'Настройка завершена.',
    },
};
