// Strings of M7 «Досье» (`m7.*`, autonomy kinds `kind.dossier.*`). Russian is the primary UI language; the user is
// addressed as «ты» (masculine).
import type { I18nParts } from '../../shared/contracts';

export const DOSSIER_STRINGS: I18nParts = {
    en: {
        'm7.title': 'Dossier',
        'm7.tab': 'Dossier',
        'kind.dossier.fix': 'Dossier fixes (keys through the chat canon, place descriptions)',
        'kind.dossier.fixFile': 'Dossier fixes written into lorebook files',
        'kind.dossier.spread': '«Spread» from the dossier',
        'kind.dossier.note': 'Dossier notes about DES',
        'm7.worldOff':
            'The world model is off: only the card character, your persona, DES characters and registered places are listed.',
        'm7.picker.search': 'Search by name, alias or case form',
        'm7.picker.hint': 'Everything the stack knows about a character, a place or your persona on one page.',
        'm7.picker.noMatch': 'Nobody matches this search.',
        'm7.picker.empty': 'No characters known yet: open a chat.',
        'm7.picker.more': 'Showing {shown} of {total}: narrow the search.',
        'm7.entity.persona': 'persona',
        'm7.entity.character': 'character',
        'm7.entity.place': 'place',
        'm7.entity.item': 'item',
        'm7.entity.faction': 'faction',
        'm7.entity.event': 'event',
        'm7.entity.tradition': 'tradition',
        'm7.entity.promise': 'promise',
        'm7.entity.secret': 'secret',
        'm7.entity.quest': 'quest',
        'm7.entity.mechanic': 'mechanic',
        'm7.present': 'on scene',
        'm7.aliases': 'Also: {list}',
        'm7.builtAt': 'Built at {time}',
        'm7.back': 'All',
        'm7.refresh': 'Refresh',
        'm7.loading': 'Collecting the dossier…',
        'm7.open': 'Open',
        'm7.findings.title': 'Checks ({count})',
        'm7.findings.none': 'No structural problems found.',
        'm7.sections.title': 'What the stack knows ({count})',
        'm7.sections.none': 'Nothing is stored about this entity yet.',
        'm7.text.more': 'Show all',
        'm7.text.less': 'Collapse',
        'm7.kind.lore': 'Lore',
        'm7.kind.canon': 'Canon',
        'm7.kind.ck': 'CK archive',
        'm7.kind.tags': 'Tags',
        'm7.kind.nai': 'NAI',
        'm7.kind.des': 'DES',
        'm7.kind.forms': 'Forms',
        'm7.kind.qvink': 'Qvink',
        'm7.kind.rag': 'RAG',
        'm7.kind.sheet': 'Sheet',
        'm7.kind.place': 'Place',
        'm7.kind.persona': 'Persona',
        'm7.source.card': 'card',
        'm7.source.persona': 'persona',
        'm7.source.des.character': 'DES',
        'm7.source.des.alias': 'DES alias',
        'm7.source.chat.alias': 'chat nickname',
        'm7.source.lore.entry': 'lore',
        'm7.source.canon.entry': 'canon',
        'm7.source.ck.archive': 'CK archive',
        'm7.source.nai.passport': 'NAI passport',
        'm7.source.qvink.memory': 'Qvink',
        'm7.source.place': 'place',
        'm7.findingKind.missingEntry': 'no entry',
        'm7.findingKind.missingPassport': 'no passport',
        'm7.findingKind.missingArchive': 'no archive',
        'm7.findingKind.aliasNotKey': 'alias is not a key',
        'm7.findingKind.nameMismatch': 'names differ',
        'm7.findingKind.formsMissing': 'no case forms',
        'm7.findingKind.appearanceMismatch': 'appearance (AI)',
        'm7.findingKind.descriptionMismatch': 'description (AI)',
        'm7.finding.missingEntry':
            '{name} has a DES card but no lorebook entry and nothing in the chat canon: the model learns about them only from the scene.',
        'm7.finding.missingPassport': '{name} has no NAI Studio passport: pictures will guess the appearance.',
        'm7.finding.missingArchive': '{name} has no CarrotKernel archive (BunnyMo tags).',
        'm7.finding.aliasNotKey':
            'The DES alias «{alias}» is not a key of «{entry}»: the entry stays silent when only this name is used.',
        'm7.finding.nameMismatch': 'Stores name {name} differently: {names}.',
        'm7.finding.formsMissing': 'The key «{key}» of «{entry}» has no case forms ({count}): {forms}.',
        'm7.finding.placeEntry': '{name} has no description entry yet.',
        'm7.finding.p13': 'The only entries are in BunnyMo books: they are never changed (P13).',
        'm7.fix.alias': 'Add «{alias}» as a key',
        'm7.fix.forms': 'Add the case forms',
        'm7.fix.desAlias': 'Note: add «{alias}» to DES aliases',
        'm7.fix.placeEntry': 'Create the description entry',
        'm7.fix.keys.title': 'Keys for «{entry}»: {keys}',
        'm7.fix.keys.canon':
            'The chat canon overrides the keys of «{entry}» ({book}) with {keys} added. The book itself does not change.',
        'm7.fix.keys.file': 'Adds {keys} to the keys of «{entry}» right in the book {book} (there is no chat canon).',
        'm7.fix.placeEntry.title': 'Description entry for {name}',
        'm7.fix.placeEntry.body': 'Creates the place entry for {name} in the chat canon.',
        'm7.decision.applied': 'Done.',
        'm7.decision.queued': 'Sent to the Inbox.',
        'm7.decision.notified': 'Proposed: confirm it from the notice.',
        'm7.decision.rejected': 'Cancelled.',
        'm7.decision.skipped': 'Nothing to change.',
        'm7.note.alias.title': 'DES alias «{alias}» for {name}',
        'm7.note.alias.body':
            'DES owns aliases, so Maestro does not write them. Open the DES Workshop for {name} and add «{alias}» to the aliases.',
        'm7.note.relationship.title': 'Relationship of {name} in DES: {value}',
        'm7.note.relationship.body':
            'DES owns the relationship. If it should stay, set «{value}» for {name} in the DES Workshop.',
        'm7.spread.title': 'Spread',
        'm7.spread.hint':
            'One edit, proposed to every chosen store by its owner’s rules: lore through the chat canon, passports through NAI Studio, DES only as a note.',
        'm7.spread.field': 'What changes',
        'm7.spread.value': 'New value',
        'm7.spread.action': 'Spread',
        'm7.spread.empty': 'Enter a value and pick at least one store.',
        'm7.spread.done': 'Proposals made: {count}.',
        'm7.spread.nothing': 'No store needs this change.',
        'm7.spread.noTargets': 'No store can take this field.',
        'm7.spread.chatAlias': 'nickname in this chat',
        'm7.spread.field.alias': 'Alias',
        'm7.spread.field.name': 'Name',
        'm7.spread.field.appearance': 'Appearance',
        'm7.spread.field.description': 'Description',
        'm7.spread.field.relationship': 'Relationship',
        'm7.spread.field.custom': 'Note',
        'm7.spread.lore.title': '{field} → «{entry}»: {value}',
        'm7.spread.lore.body': 'The chat canon overrides «{entry}» for this chat; the base book does not change.',
        'm7.spread.canon.body': 'Updates the canon entry «{entry}» of this chat.',
        'm7.spread.nai.title': '{field} → passport {name}: {value}',
        'm7.spread.nai.body':
            'Changes the passport of {name} for this chat only, through NAI Studio (the card stays as it is).',
        'm7.spread.place.title': '{field} → place {name}: {value}',
        'm7.spread.place.body': 'Updates the place registry of this chat.',
        'm7.spread.alias.title': 'Nickname «{alias}» → {name}',
        'm7.spread.alias.body': 'In this chat «{alias}» will mean {name}.',
        'm7.compare.action': 'Compare with AI',
        'm7.compare.hint':
            'The background model looks for contradictions in appearance and descriptions between the stores. Runs in the background, never while a reply is generated.',
        'm7.compare.estimate': '{stores} stores, ≈ {tokens} tokens, ≈ {usd}.',
        'm7.compare.tooFew': 'Fewer than two stores describe this entity: nothing to compare.',
        'm7.compare.noChat': 'Open a chat to compare.',
        'm7.compare.notLeader': 'Background work runs in another tab: compare there.',
        'm7.compare.noProfile': 'No connection profile for background tasks (Settings → profiles).',
        'm7.compare.cap': 'The daily cap for background tasks is reached.',
        'm7.compare.last': 'Last comparison at {time}: {count} found.',
        'm7.compare.lastCost': 'Last comparison at {time}: {count} found, cost {usd}.',
        'm7.compare.today': 'Background spend today: {usd}.',
        'm7.compare.found': 'AI found contradictions: {count}.',
        'm7.compare.none': 'AI found no contradictions.',
        'm7.compare.error.timeout': 'The comparison did not finish in time; it may still arrive later.',
        'm7.compare.error.refusal': 'The model refused to compare.',
        'm7.compare.error.parse': 'The model answered with something that is not the expected JSON.',
        'm7.compare.error.cap': 'The daily cap for background tasks is reached.',
        'm7.compare.error.gone': 'This entity is gone.',
        'm7.compare.error.sources': 'The stores could not be read.',
        'm7.compare.error.disabled': 'The dossier was switched off.',
        'm7.compare.error.no-cm': 'Connection Manager is off.',
        'm7.compare.error.no-profile': 'No connection profile for background tasks.',
        'm7.compare.error.breaker-open': 'The background profile keeps failing; paused for a few minutes.',
        'm7.compare.error.other': 'The comparison failed: {error}.',
        'm7.ai.finding': '{summary}\n«{quoteA}» ({a}) vs «{quoteB}» ({b})',
        'm7.ai.kind.appearance': 'Appearance differs',
        'm7.ai.kind.description': 'Description differs',
        'm7.p13': '«{book}» is a BunnyMo book: Maestro never changes it (P13).',
        'm7.error.noWorldInfo': 'This SillyTavern cannot load or save lorebooks.',
        'm7.error.stale': 'The entry in «{book}» changed since the proposal; nothing was written.',
        'm7.error.noNaiApi': 'NAI Studio 0.10 or newer is needed to change passports.',
        'm7.error.noPlaces': 'The places module is off.',
        'm7.error.noWorld': 'The world model is off.',
        'm7.error.noCanon': 'The chat canon is off.',
        'm7.error.gone': 'The canon entry is gone.',
        'm7.error.unknown': 'Unknown entity: {id}.',
        'm7.persona.noDescription': 'The persona has no description.',
        'm7.place.nobody': 'nobody',
        'm7.place.visits': 'Visits:',
        'm7.des.offScene': 'off scene',
        'm7.des.noTracker': 'Not in the recent DES trackers.',
        'm7.lore.protected': 'BunnyMo book (read-only)',
        'm7.lore.suppressed': 'hidden in this chat',
        'm7.lore.overridden': 'overridden in this chat',
        'm7.canon.status.active': 'active',
        'm7.canon.status.provisional': 'provisional',
        'm7.canon.status.archived': 'archived',
        'm7.mbti.H': 'healthy',
        'm7.mbti.U': 'unhealthy',
        'm7.passport.level.card': 'card',
        'm7.passport.level.persona': 'persona',
        'm7.passport.chatSame': 'same as the card',
        'm7.passport.level.chat': 'this chat only',
        'm7.passport.cardLine': 'On the card: {tags}',
        'm7.passport.where': 'NAI Studio → passport manager',
        'm7.field.base': '{field} on the card',
        'm7.field.edit': 'Edit in',
        'm7.forms.noDesru': 'DES-RU is off',
        'm7.rag.on': 'CarrotKernel RAG is on.',
        'm7.rag.onNone': 'CarrotKernel RAG is on, but this character has no collection.',
        'm7.rag.off': 'CarrotKernel RAG is off.',
        'm7.rag.noTriggers': 'no triggers',
        'm7.rag.always': 'always',
        'm7.section.persona': 'Persona: {name}',
        'm7.section.place': 'Place: {name}',
        'm7.section.des': 'DES: {name}',
        'm7.section.lore': '{title}',
        'm7.section.placeEntry': 'Description: {title}',
        'm7.section.override': 'Canon of this chat: {title}',
        'm7.section.canonAddition': 'Canon: {title}',
        'm7.section.archive': 'Archive: {name}',
        'm7.section.tags': 'BunnyMo tags',
        'm7.section.passport': 'Passport: {name}',
        'm7.section.forms': 'Russian case forms',
        'm7.section.qvink': 'Memories ({count})',
        'm7.section.rag': 'CarrotKernel RAG',
        'm7.section.sheet': 'Last BunnyMo sheet',
        'm7.field.avatar': 'Avatar',
        'm7.field.lorebook': 'Lorebook',
        'm7.field.lorebookEntries': 'Entries',
        'm7.field.color': 'Colour',
        'm7.field.pronouns': 'Pronouns',
        'm7.field.relationship': 'Relationship now',
        'm7.field.aliases': 'Aliases',
        'm7.field.forms': 'Case forms',
        'm7.field.path': 'Where',
        'm7.field.children': 'Inside',
        'm7.field.firstSeen': 'First seen',
        'm7.field.lastSeen': 'Last seen',
        'm7.field.visits': 'Visits',
        'm7.field.passport': 'Passport',
        'm7.field.emoji': 'Emoji',
        'm7.field.relationshipOverride': 'Relationship (Workshop)',
        'm7.field.portraitPrompt': 'Portrait prompt',
        'm7.field.offScene': 'Scene',
        'm7.field.book': 'Book',
        'm7.field.keys': 'Keys',
        'm7.field.protected': 'Protection',
        'm7.field.canon': 'Canon',
        'm7.field.status': 'Status',
        'm7.field.overrides': 'Overridden fields',
        'm7.field.origin': 'Origin',
        'm7.field.type': 'Type',
        'm7.field.name': 'Name',
        'm7.field.mbti': 'MBTI',
        'm7.field.tagCount': 'Tags',
        'm7.field.id': 'Id',
        'm7.field.kind': 'Kind',
        'm7.field.tags': 'Tags',
        'm7.field.outfits': 'Outfits',
        'm7.field.activeOutfit': 'Outfit now',
        'm7.field.states': 'States on',
        'm7.field.negative': 'Never draw',
        'm7.field.level': 'Level',
        'm7.field.owner': 'Card',
        'm7.field.chatOverride': 'Changed in this chat',
        'm7.field.formsKey': 'Regex key',
        'm7.field.desru': 'DES-RU',
        'm7.field.longTerm': 'Long-term',
        'm7.field.recent': 'Recent',
        'm7.field.command': 'Command',
        'm7.field.message': 'Message',
        'm7.field.slot.base': 'Base',
        'm7.field.slot.hair': 'Hair',
        'm7.field.slot.eyes': 'Eyes',
        'm7.field.slot.body': 'Body',
        'm7.field.slot.skin': 'Skin',
        'm7.field.slot.clothing': 'Clothing',
        'm7.field.slot.accessories': 'Accessories',
        'm7.field.slot.style': 'Style',
        'm7.slash.help': 'Opens the dossier of a character, place or your persona: /maestro-dossier [name].',
        'm7.slash.name': 'Name, alias or case form (empty: the list)',
        'm7.slash.notFound': 'Nobody named «{name}» is known.',
    },
    ru: {
        'm7.title': 'Досье',
        'm7.tab': 'Досье',
        'kind.dossier.fix': 'Исправления из досье (ключи через канон чата, описания мест)',
        'kind.dossier.fixFile': 'Исправления из досье прямо в файлах лорбуков',
        'kind.dossier.spread': '«Разнести» из досье',
        'kind.dossier.note': 'Заметки досье для DES',
        'm7.worldOff':
            'Модель мира выключена: в списке только персонаж карточки, твоя персона, персонажи DES и известные места.',
        'm7.picker.search': 'Поиск по имени, алиасу или падежной форме',
        'm7.picker.hint': 'Всё, что стек знает о персонаже, месте или твоей персоне, — на одной странице.',
        'm7.picker.noMatch': 'Никого не нашлось.',
        'm7.picker.empty': 'Пока никого нет: открой чат.',
        'm7.picker.more': 'Показано {shown} из {total} — уточни поиск.',
        'm7.entity.persona': 'персона',
        'm7.entity.character': 'персонаж',
        'm7.entity.place': 'место',
        'm7.entity.item': 'предмет',
        'm7.entity.faction': 'фракция',
        'm7.entity.event': 'событие',
        'm7.entity.tradition': 'традиция',
        'm7.entity.promise': 'обещание',
        'm7.entity.secret': 'секрет',
        'm7.entity.quest': 'квест',
        'm7.entity.mechanic': 'механика',
        'm7.present': 'в сцене',
        'm7.aliases': 'Также: {list}',
        'm7.builtAt': 'Собрано в {time}',
        'm7.back': 'Все',
        'm7.refresh': 'Обновить',
        'm7.loading': 'Собираю досье…',
        'm7.open': 'Открыть',
        'm7.findings.title': 'Сверка ({count})',
        'm7.findings.none': 'Структурных проблем нет.',
        'm7.sections.title': 'Что знает стек ({count})',
        'm7.sections.none': 'Об этом пока ничего не записано.',
        'm7.text.more': 'Показать всё',
        'm7.text.less': 'Свернуть',
        'm7.kind.lore': 'Лор',
        'm7.kind.canon': 'Канон',
        'm7.kind.ck': 'Архив CK',
        'm7.kind.tags': 'Теги',
        'm7.kind.nai': 'NAI',
        'm7.kind.des': 'DES',
        'm7.kind.forms': 'Падежи',
        'm7.kind.qvink': 'Qvink',
        'm7.kind.rag': 'RAG',
        'm7.kind.sheet': 'Лист',
        'm7.kind.place': 'Место',
        'm7.kind.persona': 'Персона',
        'm7.source.card': 'карточка',
        'm7.source.persona': 'персона',
        'm7.source.des.character': 'DES',
        'm7.source.des.alias': 'алиас DES',
        'm7.source.chat.alias': 'прозвище в чате',
        'm7.source.lore.entry': 'лор',
        'm7.source.canon.entry': 'канон',
        'm7.source.ck.archive': 'архив CK',
        'm7.source.nai.passport': 'паспорт NAI',
        'm7.source.qvink.memory': 'Qvink',
        'm7.source.place': 'место',
        'm7.findingKind.missingEntry': 'нет записи',
        'm7.findingKind.missingPassport': 'нет паспорта',
        'm7.findingKind.missingArchive': 'нет архива',
        'm7.findingKind.aliasNotKey': 'алиас не ключ',
        'm7.findingKind.nameMismatch': 'имена расходятся',
        'm7.findingKind.formsMissing': 'нет падежей',
        'm7.findingKind.appearanceMismatch': 'внешность (ИИ)',
        'm7.findingKind.descriptionMismatch': 'описание (ИИ)',
        'm7.finding.missingEntry':
            '{name}: есть карточка DES, но нет ни записи в лорбуках, ни канона чата — модель знает о персонаже только из сцены.',
        'm7.finding.missingPassport': '{name}: нет паспорта NAI Studio — внешность на картинках будет угадываться.',
        'm7.finding.missingArchive': '{name}: нет архива CarrotKernel (тегов BunnyMo).',
        'm7.finding.aliasNotKey':
            'Алиас DES «{alias}» — не ключ записи «{entry}»: если звать персонажа только так, запись молчит.',
        'm7.finding.nameMismatch': 'Имя «{name}» в хранилищах записано по-разному: {names}.',
        'm7.finding.formsMissing': 'У ключа «{key}» записи «{entry}» нет падежных форм ({count}): {forms}.',
        'm7.finding.placeEntry': 'У места «{name}» ещё нет записи с описанием.',
        'm7.finding.p13': 'Записи есть только в книгах BunnyMo, а их Maestro не меняет (P13).',
        'm7.fix.alias': 'Добавить «{alias}» в ключи',
        'm7.fix.forms': 'Добавить падежные формы',
        'm7.fix.desAlias': 'Заметка: добавить «{alias}» в алиасы DES',
        'm7.fix.placeEntry': 'Создать запись с описанием',
        'm7.fix.keys.title': 'Ключи для «{entry}»: {keys}',
        'm7.fix.keys.canon':
            'Канон чата переопределит ключи записи «{entry}» ({book}), добавив {keys}. Сама книга не меняется.',
        'm7.fix.keys.file': 'Добавит {keys} в ключи записи «{entry}» прямо в книге {book} (канона чата нет).',
        'm7.fix.placeEntry.title': 'Запись с описанием места «{name}»',
        'm7.fix.placeEntry.body': 'Создаёт в каноне чата запись о месте «{name}».',
        'm7.decision.applied': 'Готово.',
        'm7.decision.queued': 'Отправлено во «Входящие».',
        'm7.decision.notified': 'Предложено: подтверди в уведомлении.',
        'm7.decision.rejected': 'Отменено.',
        'm7.decision.skipped': 'Менять нечего.',
        'm7.note.alias.title': 'Алиас DES «{alias}» → {name}',
        'm7.note.alias.body':
            'Алиасами владеет DES, Maestro их не пишет. Открой Workshop DES на персонаже «{name}» и добавь «{alias}» в алиасы.',
        'm7.note.relationship.title': 'Отношение в DES: {name} — {value}',
        'm7.note.relationship.body':
            'Отношениями владеет DES. Если отношение должно закрепиться, задай «{value}» персонажу «{name}» в Workshop DES.',
        'm7.spread.title': 'Разнести',
        'm7.spread.hint':
            'Одна правка — предложения во все выбранные хранилища по правилам их владельцев: лор через канон чата, паспорта через NAI Studio, DES только заметкой.',
        'm7.spread.field': 'Что меняется',
        'm7.spread.value': 'Новое значение',
        'm7.spread.action': 'Разнести',
        'm7.spread.empty': 'Введи значение и отметь хотя бы одно хранилище.',
        'm7.spread.done': 'Предложений: {count}.',
        'm7.spread.nothing': 'Ни одному хранилищу эта правка не нужна.',
        'm7.spread.noTargets': 'Это поле некуда разнести.',
        'm7.spread.chatAlias': 'прозвище в этом чате',
        'm7.spread.field.alias': 'Алиас',
        'm7.spread.field.name': 'Имя',
        'm7.spread.field.appearance': 'Внешность',
        'm7.spread.field.description': 'Описание',
        'm7.spread.field.relationship': 'Отношение',
        'm7.spread.field.custom': 'Заметка',
        'm7.spread.lore.title': '{field} → «{entry}»: {value}',
        'm7.spread.lore.body': 'Канон чата переопределит запись «{entry}» в этом чате; базовая книга не меняется.',
        'm7.spread.canon.body': 'Обновляет запись канона «{entry}» в этом чате.',
        'm7.spread.nai.title': '{field} → паспорт «{name}»: {value}',
        'm7.spread.nai.body':
            'Меняет паспорт «{name}» только в этом чате, через NAI Studio (карточка остаётся как есть).',
        'm7.spread.place.title': '{field} → место «{name}»: {value}',
        'm7.spread.place.body': 'Обновляет реестр мест этого чата.',
        'm7.spread.alias.title': 'Прозвище «{alias}» → {name}',
        'm7.spread.alias.body': 'В этом чате «{alias}» будет означать «{name}».',
        'm7.compare.action': 'Сверить с ИИ',
        'm7.compare.hint':
            'Фоновая модель ищет противоречия во внешности и описаниях между хранилищами. Работает в фоне и никогда — во время генерации ответа.',
        'm7.compare.estimate': 'Хранилищ: {stores}, ≈ {tokens} токенов, ≈ {usd}.',
        'm7.compare.tooFew': 'Описаний меньше двух — сверять нечего.',
        'm7.compare.noChat': 'Чтобы сверить, открой чат.',
        'm7.compare.notLeader': 'Фоновая работа идёт в другой вкладке — сверяй там.',
        'm7.compare.noProfile': 'Нет профиля подключения для фоновых задач (Настройки → профили).',
        'm7.compare.cap': 'Дневной лимит фоновых задач исчерпан.',
        'm7.compare.last': 'Последняя сверка в {time}: найдено {count}.',
        'm7.compare.lastCost': 'Последняя сверка в {time}: найдено {count}, стоила {usd}.',
        'm7.compare.today': 'Фоновые расходы сегодня: {usd}.',
        'm7.compare.found': 'ИИ нашёл противоречия: {count}.',
        'm7.compare.none': 'ИИ противоречий не нашёл.',
        'm7.compare.error.timeout': 'Сверка не успела завершиться; результат может прийти позже.',
        'm7.compare.error.refusal': 'Модель отказалась сверять.',
        'm7.compare.error.parse': 'Модель ответила не тем JSON, который ожидался.',
        'm7.compare.error.cap': 'Дневной лимит фоновых задач исчерпан.',
        'm7.compare.error.gone': 'Этой сущности больше нет.',
        'm7.compare.error.sources': 'Не удалось прочитать хранилища.',
        'm7.compare.error.disabled': 'Досье выключено.',
        'm7.compare.error.no-cm': 'Connection Manager выключен.',
        'm7.compare.error.no-profile': 'Нет профиля подключения для фоновых задач.',
        'm7.compare.error.breaker-open': 'Фоновый профиль раз за разом падает; пауза на несколько минут.',
        'm7.compare.error.other': 'Сверка не удалась: {error}.',
        'm7.ai.finding': '{summary}\n«{quoteA}» ({a}) против «{quoteB}» ({b})',
        'm7.ai.kind.appearance': 'Внешность расходится',
        'm7.ai.kind.description': 'Описание расходится',
        'm7.p13': '«{book}» — книга BunnyMo: Maestro её не меняет (P13).',
        'm7.error.noWorldInfo': 'Этот SillyTavern не умеет загружать или сохранять лорбуки.',
        'm7.error.stale': 'Запись в «{book}» изменилась после предложения; ничего не записано.',
        'm7.error.noNaiApi': 'Чтобы менять паспорта, нужен NAI Studio 0.10 или новее.',
        'm7.error.noPlaces': 'Модуль мест выключен.',
        'm7.error.noWorld': 'Модель мира выключена.',
        'm7.error.noCanon': 'Канон чата выключен.',
        'm7.error.gone': 'Записи канона больше нет.',
        'm7.error.unknown': 'Неизвестная сущность: {id}.',
        'm7.persona.noDescription': 'У персоны нет описания.',
        'm7.place.nobody': 'никого',
        'm7.place.visits': 'Визиты:',
        'm7.des.offScene': 'вне сцены',
        'm7.des.noTracker': 'В последних трекерах DES не встречается.',
        'm7.lore.protected': 'книга BunnyMo (только чтение)',
        'm7.lore.suppressed': 'скрыта в этом чате',
        'm7.lore.overridden': 'переопределена в этом чате',
        'm7.canon.status.active': 'действует',
        'm7.canon.status.provisional': 'пробная',
        'm7.canon.status.archived': 'в архиве',
        'm7.mbti.H': 'здоровый',
        'm7.mbti.U': 'нездоровый',
        'm7.passport.level.card': 'карточка',
        'm7.passport.level.persona': 'персона',
        'm7.passport.chatSame': 'как в карточке',
        'm7.passport.level.chat': 'только этот чат',
        'm7.passport.cardLine': 'В карточке: {tags}',
        'm7.passport.where': 'NAI Studio → менеджер паспортов',
        'm7.field.base': '{field} в карточке',
        'm7.field.edit': 'Где править',
        'm7.forms.noDesru': 'DES-RU выключен',
        'm7.rag.on': 'RAG CarrotKernel включён.',
        'm7.rag.onNone': 'RAG CarrotKernel включён, но у персонажа нет коллекции.',
        'm7.rag.off': 'RAG CarrotKernel выключен.',
        'm7.rag.noTriggers': 'без триггеров',
        'm7.rag.always': 'всегда',
        'm7.section.persona': 'Персона: {name}',
        'm7.section.place': 'Место: {name}',
        'm7.section.des': 'DES: {name}',
        'm7.section.lore': '{title}',
        'm7.section.placeEntry': 'Описание: {title}',
        'm7.section.override': 'Канон этого чата: {title}',
        'm7.section.canonAddition': 'Канон: {title}',
        'm7.section.archive': 'Архив: {name}',
        'm7.section.tags': 'Теги BunnyMo',
        'm7.section.passport': 'Паспорт: {name}',
        'm7.section.forms': 'Падежные формы',
        'm7.section.qvink': 'Воспоминания ({count})',
        'm7.section.rag': 'RAG CarrotKernel',
        'm7.section.sheet': 'Последний лист BunnyMo',
        'm7.field.avatar': 'Аватар',
        'm7.field.lorebook': 'Лорбук',
        'm7.field.lorebookEntries': 'Записи',
        'm7.field.color': 'Цвет',
        'm7.field.pronouns': 'Местоимения',
        'm7.field.relationship': 'Отношение сейчас',
        'm7.field.aliases': 'Алиасы',
        'm7.field.forms': 'Падежные формы',
        'm7.field.path': 'Где',
        'm7.field.children': 'Внутри',
        'm7.field.firstSeen': 'Впервые',
        'm7.field.lastSeen': 'Последний раз',
        'm7.field.visits': 'Визитов',
        'm7.field.passport': 'Паспорт',
        'm7.field.emoji': 'Эмодзи',
        'm7.field.relationshipOverride': 'Отношение (Workshop)',
        'm7.field.portraitPrompt': 'Промпт портрета',
        'm7.field.offScene': 'Сцена',
        'm7.field.book': 'Книга',
        'm7.field.keys': 'Ключи',
        'm7.field.protected': 'Защита',
        'm7.field.canon': 'Канон',
        'm7.field.status': 'Статус',
        'm7.field.overrides': 'Переопределённые поля',
        'm7.field.origin': 'Откуда',
        'm7.field.type': 'Тип',
        'm7.field.name': 'Имя',
        'm7.field.mbti': 'MBTI',
        'm7.field.tagCount': 'Тегов',
        'm7.field.id': 'Id',
        'm7.field.kind': 'Вид',
        'm7.field.tags': 'Теги',
        'm7.field.outfits': 'Наряды',
        'm7.field.activeOutfit': 'Наряд сейчас',
        'm7.field.states': 'Состояния',
        'm7.field.negative': 'Никогда не рисовать',
        'm7.field.level': 'Уровень',
        'm7.field.owner': 'Карточка',
        'm7.field.chatOverride': 'Изменено в этом чате',
        'm7.field.formsKey': 'Ключ-регулярка',
        'm7.field.desru': 'DES-RU',
        'm7.field.longTerm': 'Долгих',
        'm7.field.recent': 'Недавних',
        'm7.field.command': 'Команда',
        'm7.field.message': 'Сообщение',
        'm7.field.slot.base': 'Основа',
        'm7.field.slot.hair': 'Волосы',
        'm7.field.slot.eyes': 'Глаза',
        'm7.field.slot.body': 'Тело',
        'm7.field.slot.skin': 'Кожа',
        'm7.field.slot.clothing': 'Одежда',
        'm7.field.slot.accessories': 'Аксессуары',
        'm7.field.slot.style': 'Стиль',
        'm7.slash.help': 'Открывает досье персонажа, места или твоей персоны: /maestro-dossier [имя].',
        'm7.slash.name': 'Имя, алиас или падежная форма (пусто — список)',
        'm7.slash.notFound': 'Никого по имени «{name}» не знаю.',
    },
};
