// Strings of M7 «Досье» (`m7.*`, action kinds `kind.dossier.*`, journal targets `target.dossier-*`). Russian is the
// primary UI language; the user is addressed as «ты» (masculine). Cards, notices and findings use story words (plan-2
// §3): book names, entry numbers, keys, passport ids and tags go to `Proposal.details` («Подробнее»).
import type { I18nParts } from '../../shared/contracts';

export const DOSSIER_STRINGS: I18nParts = {
    en: {
        'm7.title': 'Dossier',
        'm7.tab': 'Dossier',
        'kind.dossier.fix': 'Fixes from the dossier check',
        'kind.dossier.fixFile': 'New keys right in a lore book',
        'kind.dossier.spread': 'Edits spread to every source',
        'kind.dossier.note': 'Reminders of what to change in DES yourself',
        'kind.dossier.styleUp': 'Setting up a new character or place',
        'kind.dossier.promoteToCard': 'Moving canon entries into the card’s lore book',
        'target.dossier-entry': 'Lore book entry',
        'target.dossier-canon': 'Chat canon entry',
        'target.dossier-passport': 'Looks for pictures',
        'target.dossier-place': 'Place',
        'target.dossier-chat-alias': 'Nickname in this chat',
        'target.dossier-note': 'Reminder',
        'target.dossier-place-entry': 'Place description',
        'm7.field.place': 'Place',
        'target.dossier-styleup': 'Style up',
        'target.dossier-styleup-part': 'Part of a style up',
        'm7.worldOff':
            'The world model is off: only the card character, your persona, DES characters and registered places are listed.',
        'm7.picker.search': 'Search by name, nickname or case form',
        'm7.picker.hint': 'Everything known about a character, a place or your persona on one page.',
        'm7.picker.noMatch': 'Nobody matches this search.',
        'm7.picker.empty': 'No characters known yet: open a chat.',
        'm7.picker.more': 'Showing {shown} of {total}: narrow the search.',
        'm7.entity.persona': 'persona',
        'm7.entity.character': 'character',
        'm7.entity.place': 'place',
        'm7.entity.item': 'item',
        'm7.entity.faction': 'faction',
        'm7.entity.event': 'event',
        'm7.entity.tradition': 'tradition',
        'm7.entity.promise': 'promise',
        'm7.entity.secret': 'secret',
        'm7.entity.quest': 'quest',
        'm7.entity.mechanic': 'mechanic',
        'm7.present': 'on scene',
        'm7.aliases': 'Also: {list}',
        'm7.builtAt': 'Built at {time}',
        'm7.back': 'All',
        'm7.refresh': 'Refresh',
        'm7.loading': 'Collecting the dossier…',
        'm7.open': 'Open',
        'm7.findings.title': 'Checks ({count})',
        'm7.findings.none': 'No mismatches found.',
        'm7.sections.title': 'What is known ({count})',
        'm7.sections.none': 'Nothing is written down about this yet.',
        'm7.text.more': 'Show all',
        'm7.text.less': 'Collapse',
        'm7.kind.lore': 'Lore',
        'm7.kind.canon': 'Canon',
        'm7.kind.ck': 'Character sheet',
        'm7.kind.tags': 'Tags',
        'm7.kind.nai': 'NAI',
        'm7.kind.des': 'DES',
        'm7.kind.forms': 'Forms',
        'm7.kind.qvink': 'Qvink',
        'm7.kind.rag': 'RAG',
        'm7.kind.sheet': 'BunnyMo sheet',
        'm7.kind.place': 'Place',
        'm7.kind.persona': 'Persona',
        'm7.source.card': 'card',
        'm7.source.persona': 'persona',
        'm7.source.des.character': 'DES',
        'm7.source.des.alias': 'other name in DES',
        'm7.source.des.workshop': 'DES portrait and description',
        'm7.source.chat.alias': 'chat nickname',
        'm7.source.lore.entry': 'lore entry',
        'm7.source.canon.entry': 'chat canon',
        'm7.source.ck.archive': 'character sheet',
        'm7.source.nai.passport': 'looks for pictures',
        'm7.source.qvink.memory': 'Qvink',
        'm7.source.place': 'place',
        'm7.findingKind.missingEntry': 'no entry',
        'm7.findingKind.missingPassport': 'no looks for pictures',
        'm7.findingKind.missingArchive': 'no character sheet',
        'm7.findingKind.aliasNotKey': 'does not answer to a name',
        'm7.findingKind.nameMismatch': 'names differ',
        'm7.findingKind.formsMissing': 'no case forms',
        'm7.findingKind.appearanceMismatch': 'appearance (AI)',
        'm7.findingKind.descriptionMismatch': 'description (AI)',
        'm7.findingKind.otherStory': 'another story',
        'm7.findingKind.sharedStory': 'from outside this chat',
        'm7.finding.otherPending.being':
            'The name {name} was met in other stories before, and they bring: {list}. Is it the same character here? Until you answer, that data is not used here.',
        'm7.finding.otherPending.place':
            'The name {name} was met in other stories before, and they bring: {list}. Is it the same place here? Until you answer, that data is not used here.',
        'm7.finding.otherPending.other':
            'The name «{name}» was met in other stories before, and they bring: {list}. Is it the same thing here? Until you answer, that data is not used here.',
        'm7.finding.otherPendingApart.being':
            'If {name} here is another character, everything here stays their own and the old data never shows up.',
        'm7.finding.otherPendingApart.place':
            'If {name} here is another place, everything here stays its own and the old data never shows up.',
        'm7.finding.otherPendingApart.other':
            'If «{name}» here is something else, everything here stays its own and the old data never shows up.',
        'm7.finding.otherApart.being': 'You said {name} here is another character: {list} stay out of this chat.',
        'm7.finding.otherApart.place': 'You said {name} here is another place: {list} stay out of this chat.',
        'm7.finding.otherApart.other': 'You said «{name}» here is something else: {list} stay out of this chat.',
        'm7.finding.shared': '{name}: part of the data comes from outside this chat — {list}.',
        'm7.fix.sameAs.being': 'The same',
        'm7.fix.sameAs.place': 'The same place',
        'm7.fix.sameAs.other': 'The same',
        'm7.fix.apart.being': 'Another one',
        'm7.fix.apart.place': 'Another place',
        'm7.fix.apart.other': 'Something else',
        'm7.brings.archive': 'character and way of speaking from the sheet in «{book}»',
        'm7.brings.entry': 'the entry «{entry}» in the book «{book}»',
        'm7.brings.passport': 'looks and outfits from the card «{card}»',
        'm7.brings.workshop': 'portrait and description from DES',
        'm7.finding.missingEntry':
            '{name} shows up in the scene, but neither the lore books nor the chat canon have an entry: the model knows only what it sees in the scene.',
        'm7.finding.missingPassport': '{name}: no looks for pictures are written down — NAI Studio will guess them.',
        'm7.finding.missingArchive':
            '{name}: no character sheet — CarrotKernel will not remind the model of the traits and way of speaking.',
        'm7.finding.aliasNotKey':
            'When only «{alias}» is said in the scene, the entry «{entry}» stays silent: it does not answer to this name.',
        'm7.finding.nameMismatch': 'The name «{name}» is not written the same everywhere: there is also {names}.',
        'm7.finding.formsMissing': 'The entry «{entry}» does not answer to «{key}» as {forms}.',
        'm7.finding.placeEntry':
            'The place «{name}» has no description yet: the model knows only what it sees in the scene.',
        'm7.finding.p13': 'The only entries are in BunnyMo books, and I never edit those.',
        'm7.fix.alias': 'Add the name «{alias}» to the entry',
        'm7.fix.forms': 'Add the case forms',
        'm7.fix.desAlias': 'Remind me to add «{alias}» in DES',
        'm7.fix.placeEntry': 'Start an entry for the place',
        'm7.fix.keys.title': 'The entry «{entry}» will also answer to {names}',
        'm7.fix.keys.applied': 'The entry «{entry}» now also answers to {names}.',
        'm7.fix.forms.title': 'The entry «{entry}» will recognise the name in every case',
        'm7.fix.forms.applied': 'The entry «{entry}» now recognises the name in every case.',
        'm7.fix.keys.file':
            'There is no chat canon, so the change goes right into the lore book and works in every chat that uses it. You can undo it from the journal.',
        'm7.fix.placeEntry.title': 'The place «{name}» has no description yet — start an entry for it?',
        'm7.fix.placeEntry.body':
            'A blank chat canon entry about «{name}» appears: fill in the description, and the model will know it.',
        'm7.fix.placeEntry.applied': 'Started a chat canon entry about the place «{name}» — fill in the description.',
        'm7.where.canonOverride': 'Only in this chat, through the chat canon; the lore book itself does not change.',
        'm7.where.canonItem': 'An entry of this chat’s canon; other chats are not affected.',
        'm7.details.entry': 'Book «{book}», entry #{uid} «{entry}».',
        'm7.details.canonItem': 'Chat canon, entry #{uid}.',
        'm7.details.keys': 'New keys: {keys}',
        'm7.details.passport': 'NAI Studio passport: {id}',
        'm7.details.tags': 'Tags: {tags}',
        'm7.decision.applied': 'Done.',
        'm7.decision.queued': 'Sent to the Inbox.',
        'm7.decision.notified': 'Proposed: confirm it from the notice.',
        'm7.decision.rejected': 'Cancelled.',
        'm7.decision.skipped': 'Nothing to change.',
        'm7.note.alias.title': '{name}: add the other name «{alias}» in DES',
        'm7.note.alias.body':
            'DES keeps the other names of characters, and I do not write there. Open the DES Workshop for {name} and add «{alias}» to the names (Aliases) — then DES knows the character by this name too.',
        'm7.note.relationship.title': '{name}: set the relationship «{value}» in DES',
        'm7.note.relationship.body':
            'DES keeps relationships, and I do not change them. If it should stay like this, open the DES Workshop for {name} and set the relationship to «{value}».',
        'm7.spread.title': 'Spread',
        'm7.spread.hint':
            'One edit goes to every source you tick, each by its own rules: lore books through the chat canon, the looks for pictures through NAI Studio, DES only as a reminder.',
        'm7.spread.field': 'What changes',
        'm7.spread.value': 'New value',
        'm7.spread.action': 'Spread',
        'm7.spread.empty': 'Enter a value and tick at least one source.',
        'm7.spread.done': 'Edits prepared: {count}.',
        'm7.spread.nothing': 'It is already like that everywhere — nothing to change.',
        'm7.spread.noTargets': 'There is nowhere to write this field.',
        'm7.spread.chatAlias': 'nickname in this chat',
        'm7.spread.field.alias': 'Other name',
        'm7.spread.field.name': 'Name',
        'm7.spread.field.appearance': 'Appearance',
        'm7.spread.field.description': 'Description',
        'm7.spread.field.relationship': 'Relationship',
        'm7.spread.field.custom': 'Note',
        'm7.spread.what.appearance': 'appearance',
        'm7.spread.what.relationship': 'relationship',
        'm7.spread.what.custom': 'note',
        'm7.spread.newText': 'New text: {value}',
        'm7.spread.lore.names': 'The entry «{entry}» will also answer to «{value}»',
        'm7.spread.lore.namesApplied': 'The entry «{entry}» now also answers to «{value}».',
        'm7.spread.lore.text': 'Add to the entry «{entry}»: {what} — {value}',
        'm7.spread.lore.textApplied': 'Added to the entry «{entry}»: {what} — {value}.',
        'm7.spread.lore.description': 'A new description in the entry «{entry}»',
        'm7.spread.lore.descriptionApplied': 'Replaced the description in the entry «{entry}».',
        'm7.spread.nai.names': 'Pictures: «{value}» is {name} too',
        'm7.spread.nai.namesApplied': 'Noted for pictures: «{value}» is {name} too.',
        'm7.spread.nai.looks': '{name} in pictures: {value}',
        'm7.spread.nai.looksApplied': 'Looks for pictures updated — {name}: {value}.',
        'm7.spread.nai.body': 'In this chat only: NAI Studio updates the looks for pictures, the card stays as it is.',
        'm7.spread.place.name': 'Rename the place «{name}» to «{value}»',
        'm7.spread.place.nameApplied': 'Renamed the place «{name}» to «{value}».',
        'm7.spread.place.alias': 'The place «{name}» gets another name — «{value}»',
        'm7.spread.place.aliasApplied': 'Added another name to the place «{name}» — «{value}».',
        'm7.spread.place.body': 'In this chat only, in the list of places.',
        'm7.spread.alias.title': 'In this chat «{alias}» means {name}',
        'm7.spread.alias.applied': 'Noted: in this chat «{alias}» means {name}.',
        'm7.spread.alias.body':
            'When «{alias}» comes up in the scene, I will know it means {name}. Other chats are not affected.',
        'm7.spread.appliedMany.one': 'Wrote the edit to {count} source',
        'm7.spread.appliedMany.few': 'Wrote the edit to {count} sources',
        'm7.spread.appliedMany.many': 'Wrote the edit to {count} sources',
        'm7.compare.action': 'Compare with AI',
        'm7.compare.hint':
            'The background model looks for contradictions in appearance and descriptions between the sources. Runs in the background, never while a reply is generated.',
        'm7.compare.estimate': '{stores} sources, ≈ {tokens} tokens, ≈ {usd}.',
        'm7.compare.tooFew': 'Fewer than two sources describe it: nothing to compare.',
        'm7.compare.noChat': 'Open a chat to compare.',
        'm7.compare.notLeader': 'Background work runs in another tab: compare there.',
        'm7.compare.noProfile': 'No connection profile for background tasks (Settings → profiles).',
        'm7.compare.cap': 'The daily cap for background tasks is reached.',
        'm7.compare.last': 'Last comparison at {time}: {count} found.',
        'm7.compare.lastCost': 'Last comparison at {time}: {count} found, cost {usd}.',
        'm7.compare.today': 'Background spend today: {usd}.',
        'm7.compare.found': 'AI found contradictions: {count}.',
        'm7.compare.none': 'AI found no contradictions.',
        'm7.compare.error.timeout': 'The comparison did not finish in time; it may still arrive later.',
        'm7.compare.error.refusal': 'The model refused to compare.',
        'm7.compare.error.parse': 'The model answered in a form I cannot use.',
        'm7.compare.error.cap': 'The daily cap for background tasks is reached.',
        'm7.compare.error.gone': 'This character or place is gone.',
        'm7.compare.error.sources': 'The sources could not be read.',
        'm7.compare.error.disabled': 'The dossier was switched off.',
        'm7.compare.error.no-cm': 'Connection Manager is off.',
        'm7.compare.error.no-profile': 'No connection profile for background tasks.',
        'm7.compare.error.breaker-open': 'The background profile keeps failing; paused for a few minutes.',
        'm7.compare.error.other': 'The comparison failed: {error}.',
        'm7.ai.finding': '{summary}\n«{quoteA}» ({a}) vs «{quoteB}» ({b})',
        'm7.ai.kind.appearance': 'Appearance differs',
        'm7.ai.kind.description': 'Description differs',
        'm7.p13': '«{book}» is a BunnyMo book, and I never change it.',
        'm7.error.noWorldInfo': 'This SillyTavern does not let extensions read and save lore books.',
        'm7.error.stale': 'The entry in the book «{book}» changed since then — nothing was written.',
        'm7.error.noNaiApi': 'NAI Studio 0.10 or newer is needed.',
        'm7.error.noPlaces': 'The «Places» module is off.',
        'm7.error.noWorld': 'The «World model» is off.',
        'm7.error.noCanon': 'The «Chat canon» is off.',
        'm7.error.gone': 'This chat canon entry is gone.',
        'm7.error.passportGone': 'NAI Studio no longer has this passport.',
        'm7.error.unknown': 'I do not know who this is: there is no such character or place in this chat.',
        'm7.persona.noDescription': 'The persona has no description.',
        'm7.place.nobody': 'nobody',
        'm7.place.visits': 'Visits:',
        'm7.des.offScene': 'off scene',
        'm7.des.noTracker': 'Not in the recent DES trackers.',
        'm7.lore.protected': 'BunnyMo book (read-only)',
        'm7.lore.suppressed': 'hidden in this chat',
        'm7.lore.overridden': 'overridden in this chat',
        'm7.canon.status.active': 'active',
        'm7.canon.status.provisional': 'provisional',
        'm7.canon.status.archived': 'archived',
        'm7.mbti.H': 'healthy',
        'm7.mbti.U': 'unhealthy',
        'm7.passport.level.card': 'card',
        'm7.passport.level.persona': 'persona',
        'm7.passport.chatSame': 'same as the card',
        'm7.passport.level.chat': 'this chat only',
        'm7.passport.cardLine': 'On the card: {tags}',
        'm7.passport.where': 'NAI Studio → passport manager',
        'm7.field.base': '{field} on the card',
        'm7.field.edit': 'Edit in',
        'm7.forms.noDesru': 'DES-RU is off',
        'm7.rag.on': 'CarrotKernel RAG is on.',
        'm7.rag.onNone': 'CarrotKernel RAG is on, but this character has no collection.',
        'm7.rag.off': 'CarrotKernel RAG is off.',
        'm7.rag.noTriggers': 'no triggers',
        'm7.rag.always': 'always',
        'm7.section.persona': 'Persona: {name}',
        'm7.section.place': 'Place: {name}',
        'm7.section.des': 'DES: {name}',
        'm7.section.lore': '{title}',
        'm7.section.placeEntry': 'Description: {title}',
        'm7.section.override': 'Canon of this chat: {title}',
        'm7.section.canonAddition': 'Canon: {title}',
        'm7.section.archive': 'Character sheet: {name}',
        'm7.section.tags': 'BunnyMo tags',
        'm7.section.passport': 'Looks for pictures: {name}',
        'm7.section.forms': 'Russian case forms',
        'm7.section.qvink': 'Memories ({count})',
        'm7.section.rag': 'CarrotKernel RAG',
        'm7.section.sheet': 'Last BunnyMo sheet',
        'm7.field.avatar': 'Avatar',
        'm7.field.lorebook': 'Lore book',
        'm7.field.lorebookEntries': 'Entries',
        'm7.field.color': 'Colour',
        'm7.field.pronouns': 'Pronouns',
        'm7.field.relationship': 'Relationship now',
        'm7.field.aliases': 'Other names',
        'm7.field.forms': 'Case forms',
        'm7.field.path': 'Where',
        'm7.field.children': 'Inside',
        'm7.field.firstSeen': 'First seen',
        'm7.field.lastSeen': 'Last seen',
        'm7.field.visits': 'Visits',
        'm7.field.passport': 'Passport',
        'm7.field.emoji': 'Emoji',
        'm7.field.relationshipOverride': 'Relationship (Workshop)',
        'm7.field.portraitPrompt': 'Portrait prompt',
        'm7.field.offScene': 'Scene',
        'm7.field.book': 'Book',
        'm7.field.keys': 'Keys',
        'm7.field.protected': 'Protection',
        'm7.field.canon': 'Canon',
        'm7.field.status': 'Status',
        'm7.field.overrides': 'Overridden fields',
        'm7.field.origin': 'Origin',
        'm7.field.type': 'Type',
        'm7.field.name': 'Name',
        'm7.field.mbti': 'MBTI',
        'm7.field.tagCount': 'Tags',
        'm7.field.id': 'Id',
        'm7.field.kind': 'Kind',
        'm7.field.tags': 'Tags',
        'm7.field.outfits': 'Outfits',
        'm7.field.activeOutfit': 'Outfit now',
        'm7.field.states': 'States on',
        'm7.field.negative': 'Never draw',
        'm7.field.level': 'Level',
        'm7.field.owner': 'Card',
        'm7.field.chatOverride': 'Changed in this chat',
        'm7.field.formsKey': 'Regex key',
        'm7.field.desru': 'DES-RU',
        'm7.field.longTerm': 'Long-term',
        'm7.field.recent': 'Recent',
        'm7.field.command': 'Command',
        'm7.field.message': 'Message',
        'm7.field.slot.base': 'Base',
        'm7.field.slot.hair': 'Hair',
        'm7.field.slot.eyes': 'Eyes',
        'm7.field.slot.body': 'Body',
        'm7.field.slot.skin': 'Skin',
        'm7.field.slot.clothing': 'Clothing',
        'm7.field.slot.accessories': 'Accessories',
        'm7.field.slot.style': 'Style',
        'm7.field.text': 'Text',
        'm7.field.looks': 'Looks (tags)',
        'm7.field.otherNames': 'Other names',
        'm7.field.placeName': 'Name',
        'm7.field.placeAliases': 'Other names',
        'm7.field.nickname': 'Nickname',
        'm7.field.means': 'Means',
        'm7.slash.help': 'Opens the dossier of a character, place or your persona: /maestro-dossier [name].',
        'm7.slash.name': 'Name, nickname or case form (empty: the list)',
        'm7.slash.notFound': 'Nobody named «{name}» is known.',
        'm7.styleUp.action': 'Style up',
        'm7.styleUp.profileTask': 'Dossier: character sheet traits for «Style up»',
        'm7.styleUp.actionHint':
            'Sets up everything that is missing in one go: a chat canon entry, a character sheet, the looks for pictures.',
        'm7.styleUp.missing': 'Missing: {list}.',
        'm7.styleUp.title': 'Style up: {name}',
        'm7.styleUp.planning': 'Preparing the plan… (the background model picks the traits for the character sheet)',
        'm7.styleUp.intro':
            'This is what will appear. Untick what you do not need. Everything goes as one card to the Inbox (or is applied at once if you set it so).',
        'm7.styleUp.apply': 'Style up',
        'm7.styleUp.cancel': 'Cancel',
        'm7.styleUp.close': 'Close',
        'm7.styleUp.nothing': 'Nothing can be created right now.',
        'm7.styleUp.none': 'Tick at least one part.',
        'm7.styleUp.book': 'Book for the character sheet',
        'm7.styleUp.bookLine': 'Book: {book}',
        'm7.styleUp.keys': 'Keys: {list}',
        'm7.styleUp.tags': 'Tags: {list}',
        'm7.styleUp.rejected': 'Did not pass the check: {list}',
        'm7.styleUp.cost': 'Planning cost {usd}.',
        'm7.styleUp.before': 'Now: none',
        'm7.styleUp.show': 'What will be written',
        'm7.styleUp.status.title': 'Style up at {time}',
        'm7.styleUp.status.ok': '✓ {part}',
        'm7.styleUp.status.failed': '✗ {part}: {error}',
        'm7.styleUp.status.sent': 'The plan for {name} is in the Inbox.',
        'm7.styleUp.part.canon': 'Chat canon entry',
        'm7.styleUp.part.archive': 'Character sheet',
        'm7.styleUp.part.passport': 'Looks for pictures',
        'm7.styleUp.part.placeEntry': 'Place description',
        'm7.styleUp.part.lorePassport': 'Place in pictures',
        'm7.styleUp.part.promote': 'Card’s lore book',
        'm7.styleUp.line.canon': 'An entry about the character in the chat canon',
        'm7.styleUp.line.archive': 'A character sheet — traits: {count}',
        'm7.styleUp.line.archiveNew': 'A character sheet in a new book — traits: {count}',
        'm7.styleUp.line.passport': 'The looks for pictures — in this chat only',
        'm7.styleUp.line.placeEntry': 'A description of the place «{name}» in the chat canon',
        'm7.styleUp.line.lorePassport': 'How the place looks in pictures (made from the description)',
        'm7.styleUp.preview.lorePassport': 'Made from the place description once it is written.',
        'm7.styleUp.card.title': '{name}: set up everything that is missing?',
        'm7.styleUp.card.place': 'The place «{name}»: set up everything that is missing?',
        'm7.styleUp.card.body': 'If you agree, this appears:',
        'm7.styleUp.card.undo': 'Each part can be undone on its own from the journal.',
        'm7.styleUp.card.applied': '{name}: set up everything that was missing.',
        'm7.styleUp.card.appliedPlace': 'The place «{name}»: set up everything that was missing.',
        'm7.styleUp.details.canon': 'Chat canon entry «{title}», keys: {keys}',
        'm7.styleUp.details.archive': 'Character sheet in the book «{book}»: {tags}',
        'm7.styleUp.details.archiveNew': 'Character sheet in the new book «{book}»: {tags}',
        'm7.styleUp.details.passport': 'NAI Studio passport {id}: {tags}',
        'm7.styleUp.partial': '{name}: not everything was set up. Failed — {errors}',
        'm7.styleUp.journal.canon': '{name}: started an entry in the chat canon',
        'm7.styleUp.journal.archive': '{name}: wrote a character sheet',
        'm7.styleUp.journal.passport': '{name}: wrote the looks for pictures in this chat',
        'm7.styleUp.journal.placeEntry': 'The place «{name}»: started a description in the chat canon',
        'm7.styleUp.journal.lorePassport': 'The place «{name}»: made its looks for pictures',
        'm7.styleUp.journal.promote': 'Moved «{title}» into the card’s lore book',
        'm7.styleUp.error.noBook': 'The book «{book}» is gone.',
        'm7.styleUp.error.archiveExists': '{name} already has a character sheet in the book «{book}».',
        'm7.styleUp.error.passport': 'The looks for pictures could not be read.',
        'm7.styleUp.error.placeGone': 'This place is gone from the list of places.',
        'm7.styleUp.error.noLorePassports': 'The «Passports in lorebooks» module is off.',
        'm7.styleUp.error.noPlaceEntry': 'The place has no description.',
        'm7.styleUp.error.lorePassport': 'The place’s looks for pictures could not be made.',
        'm7.styleUp.note.notRepo':
            'The sheet is written, but CarrotKernel does not see it yet: mark the book «{book}» as a Character Repo in CarrotKernel and attach it.',
        'm7.styleUp.note.placeLinked': 'The place already had a description entry: it is linked, not rewritten.',
        'm7.styleUp.note.passportExists': 'The place already had its looks for pictures.',
        'm7.styleUp.hint.noChat': 'Open a chat: «Style up» writes into this chat’s canon and Inbox.',
        'm7.styleUp.hint.failed': 'Could not prepare: {error}.',
        'm7.styleUp.hint.canonOff': 'The «Chat canon» is off: no entry about the character.',
        'm7.styleUp.hint.archiveNoBunnymo':
            'The «BunnyMo mode» is off: there is nothing to pick the character sheet’s traits from.',
        'm7.styleUp.hint.archiveNoProfile':
            'No connection profile for background tasks: the character sheet cannot be prepared.',
        'm7.styleUp.hint.archiveCap': 'The daily cap for background tasks is reached: no character sheet this time.',
        'm7.styleUp.hint.archiveBunnyRepo':
            '«{book}» is marked in CarrotKernel as a book for sheets, but it is a BunnyMo book: I never write there.',
        'm7.styleUp.hint.archiveNoPacks': 'No BunnyMo pack is loaded: there are no traits for the character sheet.',
        'm7.styleUp.hint.archiveFailed': 'The model did not pick traits: {error}.',
        'm7.styleUp.hint.archiveParse': 'The model answered in a form I cannot use.',
        'm7.styleUp.hint.archiveRejected': 'Did not pass the BunnyMo dictionary check: {tags}.',
        'm7.styleUp.hint.archiveDropped': 'Dramatis also offered traits the loaded BunnyMo packs do not know: {tags}.',
        'm7.styleUp.hint.archiveEmpty': 'None of the model’s traits passed the check: no character sheet.',
        'm7.styleUp.hint.archiveNewBook':
            'No book can take character sheets, so I will start a new one, «{book}». CarrotKernel sees it once you mark it there as a Character Repo and attach it (globally or to the card).',
        'm7.styleUp.hint.passportAuto':
            '{name}: NAI Studio describes the looks for pictures itself when the character shows up in the scene (its auto passports are on).',
        'm7.styleUp.hint.passportManual':
            'Set up the looks for pictures in NAI Studio → passport manager: NAI Studio cannot make them from here.',
        'm7.styleUp.hint.passportFailed': 'NAI Studio could not make the looks for pictures: {error}.',
        'm7.styleUp.hint.placesOff': 'The «Places» module is off: no place description.',
        'm7.styleUp.promote.action': 'To the card’s lore book',
        'm7.styleUp.promote.hint':
            'Moves the entry into the card’s lore book «{book}» so it works in every chat with this card (asks first).',
        'm7.styleUp.promote.noBook': 'The card has no lore book of its own.',
        'm7.styleUp.promote.title': 'Move «{title}» into the card’s lore book?',
        'm7.styleUp.promote.body':
            'The entry starts working in every chat with this card and leaves this chat’s canon so it does not fire twice. You can undo it from the journal.',
        'm7.styleUp.promote.details': 'The card’s lore book: «{book}».',
        'm7.mechanics.title': 'Mechanics',
        'm7.wardrobe.title': 'Outfits ({count})',
        'm7.wardrobe.active': 'worn',
        'm7.wardrobe.wear': 'Put on',
        'm7.wardrobe.wearHint': 'Make this the active outfit in this chat (the card is not changed).',
        'm7.wardrobe.worn': '«{name}» is on now.',
    },
    ru: {
        'm7.title': 'Досье',
        'm7.tab': 'Досье',
        'kind.dossier.fix': 'Исправления по сверке досье',
        'kind.dossier.fixFile': 'Новые ключи прямо в книге лора',
        'kind.dossier.spread': 'Правки, разнесённые по источникам',
        'kind.dossier.note': 'Напоминания, что поправить в DES самому',
        'kind.dossier.styleUp': 'Оформление нового персонажа или места',
        'kind.dossier.promoteToCard': 'Перенос записей канона в книгу карточки',
        'target.dossier-entry': 'Запись книги лора',
        'target.dossier-canon': 'Запись канона чата',
        'target.dossier-passport': 'Внешность для картинок',
        'target.dossier-place': 'Место',
        'target.dossier-chat-alias': 'Прозвище в этом чате',
        'target.dossier-note': 'Напоминание',
        'target.dossier-place-entry': 'Описание места',
        'm7.field.place': 'Место',
        'target.dossier-styleup': 'Оформление',
        'target.dossier-styleup-part': 'Часть оформления',
        'm7.worldOff':
            'Модель мира выключена: в списке только персонаж карточки, твоя персона, персонажи DES и известные места.',
        'm7.picker.search': 'Поиск по имени, прозвищу или падежной форме',
        'm7.picker.hint': 'Всё, что известно о персонаже, месте или твоей персоне, — на одной странице.',
        'm7.picker.noMatch': 'Никого не нашлось.',
        'm7.picker.empty': 'Пока никого нет: открой чат.',
        'm7.picker.more': 'Показано {shown} из {total} — уточни поиск.',
        'm7.entity.persona': 'персона',
        'm7.entity.character': 'персонаж',
        'm7.entity.place': 'место',
        'm7.entity.item': 'предмет',
        'm7.entity.faction': 'фракция',
        'm7.entity.event': 'событие',
        'm7.entity.tradition': 'традиция',
        'm7.entity.promise': 'обещание',
        'm7.entity.secret': 'секрет',
        'm7.entity.quest': 'квест',
        'm7.entity.mechanic': 'механика',
        'm7.present': 'в сцене',
        'm7.aliases': 'Также: {list}',
        'm7.builtAt': 'Собрано в {time}',
        'm7.back': 'Все',
        'm7.refresh': 'Обновить',
        'm7.loading': 'Собираю досье…',
        'm7.open': 'Открыть',
        'm7.findings.title': 'Сверка ({count})',
        'm7.findings.none': 'Нестыковок не нашлось.',
        'm7.sections.title': 'Что известно ({count})',
        'm7.sections.none': 'Об этом пока ничего не записано.',
        'm7.text.more': 'Показать всё',
        'm7.text.less': 'Свернуть',
        'm7.kind.lore': 'Лор',
        'm7.kind.canon': 'Канон',
        'm7.kind.ck': 'Лист характера',
        'm7.kind.tags': 'Теги',
        'm7.kind.nai': 'NAI',
        'm7.kind.des': 'DES',
        'm7.kind.forms': 'Падежи',
        'm7.kind.qvink': 'Qvink',
        'm7.kind.rag': 'RAG',
        'm7.kind.sheet': 'Лист BunnyMo',
        'm7.kind.place': 'Место',
        'm7.kind.persona': 'Персона',
        'm7.source.card': 'карточка',
        'm7.source.persona': 'персона',
        'm7.source.des.character': 'DES',
        'm7.source.des.alias': 'другое имя в DES',
        'm7.source.des.workshop': 'портрет и описание в DES',
        'm7.source.chat.alias': 'прозвище в чате',
        'm7.source.lore.entry': 'запись лора',
        'm7.source.canon.entry': 'канон чата',
        'm7.source.ck.archive': 'лист характера',
        'm7.source.nai.passport': 'внешность для картинок',
        'm7.source.qvink.memory': 'Qvink',
        'm7.source.place': 'место',
        'm7.findingKind.missingEntry': 'нет записи',
        'm7.findingKind.missingPassport': 'нет внешности для картинок',
        'm7.findingKind.missingArchive': 'нет листа характера',
        'm7.findingKind.aliasNotKey': 'не откликается на имя',
        'm7.findingKind.nameMismatch': 'имена расходятся',
        'm7.findingKind.formsMissing': 'нет падежей',
        'm7.findingKind.appearanceMismatch': 'внешность (ИИ)',
        'm7.findingKind.descriptionMismatch': 'описание (ИИ)',
        'm7.findingKind.otherStory': 'другая история',
        'm7.findingKind.sharedStory': 'не из этого чата',
        'm7.finding.otherPending.being':
            'Имя {name} уже встречалось в других историях, оттуда есть: {list}. Здесь это тот же персонаж? Пока ты не ответил, эти данные здесь не используются.',
        'm7.finding.otherPending.place':
            'Имя {name} уже встречалось в других историях, оттуда есть: {list}. Здесь это то же место? Пока ты не ответил, эти данные здесь не используются.',
        'm7.finding.otherPending.other':
            'Имя «{name}» уже встречалось в других историях, оттуда есть: {list}. Здесь это то же самое? Пока ты не ответил, эти данные здесь не используются.',
        'm7.finding.otherPendingApart.being':
            'Если здесь {name} — другой персонаж, всё здесь будет своё, а старое сюда так и не попадёт.',
        'm7.finding.otherPendingApart.place':
            'Если здесь {name} — другое место, всё здесь будет своё, а старое сюда так и не попадёт.',
        'm7.finding.otherPendingApart.other':
            'Если здесь «{name}» — что-то другое, всё здесь будет своё, а старое сюда так и не попадёт.',
        'm7.finding.otherApart.being': 'Ты ответил, что здесь {name} — другой персонаж: {list} сюда не попадают.',
        'm7.finding.otherApart.place': 'Ты ответил, что здесь {name} — другое место: {list} сюда не попадают.',
        'm7.finding.otherApart.other': 'Ты ответил, что здесь «{name}» — что-то другое: {list} сюда не попадают.',
        'm7.finding.shared': '{name}: часть данных берётся не из этого чата — {list}.',
        'm7.fix.sameAs.being': 'Тот же',
        'm7.fix.sameAs.place': 'То же место',
        'm7.fix.sameAs.other': 'То же самое',
        'm7.fix.apart.being': 'Другой',
        'm7.fix.apart.place': 'Другое место',
        'm7.fix.apart.other': 'Другое',
        'm7.brings.archive': 'характер и манера речи из листа в «{book}»',
        'm7.brings.entry': 'запись «{entry}» в книге «{book}»',
        'm7.brings.passport': 'внешность и наряды из карточки «{card}»',
        'm7.brings.workshop': 'портрет и описание из DES',
        'm7.finding.missingEntry':
            '{name} появляется в сцене, но записи о персонаже нет ни в книгах лора, ни в каноне чата: модель знает только то, что видит в сцене.',
        'm7.finding.missingPassport': '{name}: внешность для картинок не записана — NAI Studio будет её угадывать.',
        'm7.finding.missingArchive':
            '{name}: нет листа характера — CarrotKernel не подскажет модели черты и манеру речи.',
        'm7.finding.aliasNotKey':
            'Если в сцене звучит только «{alias}», запись «{entry}» молчит: на это имя она не откликается.',
        'm7.finding.nameMismatch': 'Имя «{name}» записано не везде одинаково: встречается и {names}.',
        'm7.finding.formsMissing': 'Запись «{entry}» не откликается на «{key}» в формах {forms}.',
        'm7.finding.placeEntry': 'Место «{name}» ещё не описано: модель знает о нём только то, что видит в сцене.',
        'm7.finding.p13': 'Записи о персонаже есть только в книгах BunnyMo, а их я не правлю.',
        'm7.fix.alias': 'Добавить имя «{alias}» в запись',
        'm7.fix.forms': 'Добавить падежные формы',
        'm7.fix.desAlias': 'Напомнить добавить «{alias}» в DES',
        'm7.fix.placeEntry': 'Завести запись о месте',
        'm7.fix.keys.title': 'Запись «{entry}» будет откликаться и на {names}',
        'm7.fix.keys.applied': 'Запись «{entry}» теперь откликается и на {names}.',
        'm7.fix.forms.title': 'Запись «{entry}» будет узнавать имя во всех падежах',
        'm7.fix.forms.applied': 'Запись «{entry}» теперь узнаёт имя во всех падежах.',
        'm7.fix.keys.file':
            'Канона чата нет, поэтому правка пойдёт прямо в книгу лора и будет действовать во всех чатах с ней. Отменить можно из журнала.',
        'm7.fix.placeEntry.title': 'Место «{name}» ещё не описано — завести для него запись?',
        'm7.fix.placeEntry.body':
            'В каноне чата появится заготовка записи о месте «{name}»: останется вписать описание, и модель будет его знать.',
        'm7.fix.placeEntry.applied': 'Завёл в каноне чата запись о месте «{name}» — впиши туда описание.',
        'm7.where.canonOverride': 'Только в этом чате, через канон чата; сама книга лора не изменится.',
        'm7.where.canonItem': 'Запись из канона этого чата; другие чаты это не затронет.',
        'm7.details.entry': 'Книга «{book}», запись №{uid} «{entry}».',
        'm7.details.canonItem': 'Канон чата, запись №{uid}.',
        'm7.details.keys': 'Новые ключи: {keys}',
        'm7.details.passport': 'Паспорт NAI Studio: {id}',
        'm7.details.tags': 'Теги: {tags}',
        'm7.decision.applied': 'Готово.',
        'm7.decision.queued': 'Отправил во «Входящие».',
        'm7.decision.notified': 'Предложил — подтверди в уведомлении.',
        'm7.decision.rejected': 'Отменено.',
        'm7.decision.skipped': 'Менять нечего.',
        'm7.note.alias.title': '{name}: добавь в DES другое имя — «{alias}»',
        'm7.note.alias.body':
            'Другие имена персонажей хранит DES, я их туда не пишу. Открой Workshop DES у персонажа {name} и впиши «{alias}» в список имён (Aliases) — тогда DES узнает персонажа и под этим именем.',
        'm7.note.relationship.title': '{name}: закрепи в DES отношение «{value}»',
        'm7.note.relationship.body':
            'Отношения хранит DES, я их не меняю. Если так и должно остаться, открой Workshop DES у персонажа {name} и задай отношение «{value}».',
        'm7.spread.title': 'Разнести',
        'm7.spread.hint':
            'Одна правка — сразу во все отмеченные источники, каждый по своим правилам: книги лора через канон чата, внешность для картинок через NAI Studio, в DES — только напоминанием.',
        'm7.spread.field': 'Что меняется',
        'm7.spread.value': 'Новое значение',
        'm7.spread.action': 'Разнести',
        'm7.spread.empty': 'Впиши значение и отметь хотя бы один источник.',
        'm7.spread.done': 'Правок подготовлено: {count}.',
        'm7.spread.nothing': 'Везде уже так — менять нечего.',
        'm7.spread.noTargets': 'Это поле некуда записать.',
        'm7.spread.chatAlias': 'прозвище в этом чате',
        'm7.spread.field.alias': 'Другое имя',
        'm7.spread.field.name': 'Имя',
        'm7.spread.field.appearance': 'Внешность',
        'm7.spread.field.description': 'Описание',
        'm7.spread.field.relationship': 'Отношение',
        'm7.spread.field.custom': 'Заметка',
        'm7.spread.what.appearance': 'внешность',
        'm7.spread.what.relationship': 'отношение',
        'm7.spread.what.custom': 'заметка',
        'm7.spread.newText': 'Новый текст: {value}',
        'm7.spread.lore.names': 'Запись «{entry}» будет откликаться и на «{value}»',
        'm7.spread.lore.namesApplied': 'Запись «{entry}» теперь откликается и на «{value}».',
        'm7.spread.lore.text': 'Дописать в запись «{entry}»: {what} — {value}',
        'm7.spread.lore.textApplied': 'Дописал в запись «{entry}»: {what} — {value}.',
        'm7.spread.lore.description': 'Новое описание в записи «{entry}»',
        'm7.spread.lore.descriptionApplied': 'Заменил описание в записи «{entry}».',
        'm7.spread.nai.names': 'Картинки: «{value}» — это тоже {name}',
        'm7.spread.nai.namesApplied': 'Запомнил для картинок: «{value}» — это тоже {name}.',
        'm7.spread.nai.looks': '{name} на картинках: {value}',
        'm7.spread.nai.looksApplied': 'Внешность для картинок дополнена — {name}: {value}.',
        'm7.spread.nai.body':
            'Только в этом чате: NAI Studio поправит внешность для картинок, карточка останется как есть.',
        'm7.spread.place.name': 'Переименовать место «{name}» в «{value}»',
        'm7.spread.place.nameApplied': 'Переименовал место «{name}» в «{value}».',
        'm7.spread.place.alias': 'У места «{name}» будет другое название — «{value}»',
        'm7.spread.place.aliasApplied': 'Добавил месту «{name}» другое название — «{value}».',
        'm7.spread.place.body': 'Только в этом чате, в списке мест.',
        'm7.spread.alias.title': 'В этом чате «{alias}» — это {name}',
        'm7.spread.alias.applied': 'Запомнил: в этом чате «{alias}» — это {name}.',
        'm7.spread.alias.body':
            'Когда в сцене прозвучит «{alias}», я пойму, что речь о персонаже {name}. Другие чаты это не затронет.',
        'm7.spread.appliedMany.one': 'Записал правку в {count} источник',
        'm7.spread.appliedMany.few': 'Записал правку в {count} источника',
        'm7.spread.appliedMany.many': 'Записал правку в {count} источников',
        'm7.compare.action': 'Сверить с ИИ',
        'm7.compare.hint':
            'Фоновая модель ищет противоречия во внешности и описаниях между источниками. Работает в фоне и никогда — во время генерации ответа.',
        'm7.compare.estimate': 'Источников: {stores}, ≈ {tokens} токенов, ≈ {usd}.',
        'm7.compare.tooFew': 'Описаний меньше двух — сверять нечего.',
        'm7.compare.noChat': 'Чтобы сверить, открой чат.',
        'm7.compare.notLeader': 'Фоновая работа идёт в другой вкладке — сверяй там.',
        'm7.compare.noProfile': 'Нет профиля подключения для фоновых задач (Настройки → профили).',
        'm7.compare.cap': 'Дневной лимит фоновых задач исчерпан.',
        'm7.compare.last': 'Последняя сверка в {time}: найдено {count}.',
        'm7.compare.lastCost': 'Последняя сверка в {time}: найдено {count}, стоила {usd}.',
        'm7.compare.today': 'Фоновые расходы сегодня: {usd}.',
        'm7.compare.found': 'ИИ нашёл противоречия: {count}.',
        'm7.compare.none': 'ИИ противоречий не нашёл.',
        'm7.compare.error.timeout': 'Сверка не успела завершиться; результат может прийти позже.',
        'm7.compare.error.refusal': 'Модель отказалась сверять.',
        'm7.compare.error.parse': 'Модель ответила не в том виде, который нужен.',
        'm7.compare.error.cap': 'Дневной лимит фоновых задач исчерпан.',
        'm7.compare.error.gone': 'Этого персонажа или места больше нет.',
        'm7.compare.error.sources': 'Не получилось прочитать источники.',
        'm7.compare.error.disabled': 'Досье выключено.',
        'm7.compare.error.no-cm': 'Connection Manager выключен.',
        'm7.compare.error.no-profile': 'Нет профиля подключения для фоновых задач.',
        'm7.compare.error.breaker-open': 'Фоновый профиль раз за разом падает; пауза на несколько минут.',
        'm7.compare.error.other': 'Сверка не удалась: {error}.',
        'm7.ai.finding': '{summary}\n«{quoteA}» ({a}) против «{quoteB}» ({b})',
        'm7.ai.kind.appearance': 'Внешность расходится',
        'm7.ai.kind.description': 'Описание расходится',
        'm7.p13': '«{book}» — книга BunnyMo, её я не меняю.',
        'm7.error.noWorldInfo': 'Этот SillyTavern не даёт расширениям читать и сохранять книги лора.',
        'm7.error.stale': 'Запись в книге «{book}» с тех пор изменилась — ничего не записал.',
        'm7.error.noNaiApi': 'Нужен NAI Studio 0.10 или новее.',
        'm7.error.noPlaces': 'Выключен модуль «Места».',
        'm7.error.noWorld': 'Выключена «Модель мира».',
        'm7.error.noCanon': 'Выключен «Канон чата».',
        'm7.error.gone': 'Этой записи в каноне чата больше нет.',
        'm7.error.passportGone': 'В NAI Studio этого паспорта больше нет.',
        'm7.error.unknown': 'Не знаю, кто это: в этом чате нет такого персонажа или места.',
        'm7.persona.noDescription': 'У персоны нет описания.',
        'm7.place.nobody': 'никого',
        'm7.place.visits': 'Визиты:',
        'm7.des.offScene': 'вне сцены',
        'm7.des.noTracker': 'В последних трекерах DES не встречается.',
        'm7.lore.protected': 'книга BunnyMo (только чтение)',
        'm7.lore.suppressed': 'скрыта в этом чате',
        'm7.lore.overridden': 'переопределена в этом чате',
        'm7.canon.status.active': 'действует',
        'm7.canon.status.provisional': 'пробная',
        'm7.canon.status.archived': 'в архиве',
        'm7.mbti.H': 'здоровый',
        'm7.mbti.U': 'нездоровый',
        'm7.passport.level.card': 'карточка',
        'm7.passport.level.persona': 'персона',
        'm7.passport.chatSame': 'как в карточке',
        'm7.passport.level.chat': 'только этот чат',
        'm7.passport.cardLine': 'В карточке: {tags}',
        'm7.passport.where': 'NAI Studio → менеджер паспортов',
        'm7.field.base': '{field} в карточке',
        'm7.field.edit': 'Где править',
        'm7.forms.noDesru': 'DES-RU выключен',
        'm7.rag.on': 'RAG CarrotKernel включён.',
        'm7.rag.onNone': 'RAG CarrotKernel включён, но у персонажа нет коллекции.',
        'm7.rag.off': 'RAG CarrotKernel выключен.',
        'm7.rag.noTriggers': 'без триггеров',
        'm7.rag.always': 'всегда',
        'm7.section.persona': 'Персона: {name}',
        'm7.section.place': 'Место: {name}',
        'm7.section.des': 'DES: {name}',
        'm7.section.lore': '{title}',
        'm7.section.placeEntry': 'Описание: {title}',
        'm7.section.override': 'Канон этого чата: {title}',
        'm7.section.canonAddition': 'Канон: {title}',
        'm7.section.archive': 'Лист характера: {name}',
        'm7.section.tags': 'Теги BunnyMo',
        'm7.section.passport': 'Внешность для картинок: {name}',
        'm7.section.forms': 'Падежные формы',
        'm7.section.qvink': 'Воспоминания ({count})',
        'm7.section.rag': 'RAG CarrotKernel',
        'm7.section.sheet': 'Последний лист BunnyMo',
        'm7.field.avatar': 'Аватар',
        'm7.field.lorebook': 'Книга лора',
        'm7.field.lorebookEntries': 'Записи',
        'm7.field.color': 'Цвет',
        'm7.field.pronouns': 'Местоимения',
        'm7.field.relationship': 'Отношение сейчас',
        'm7.field.aliases': 'Другие имена',
        'm7.field.forms': 'Падежные формы',
        'm7.field.path': 'Где',
        'm7.field.children': 'Внутри',
        'm7.field.firstSeen': 'Впервые',
        'm7.field.lastSeen': 'Последний раз',
        'm7.field.visits': 'Визитов',
        'm7.field.passport': 'Паспорт',
        'm7.field.emoji': 'Эмодзи',
        'm7.field.relationshipOverride': 'Отношение (Workshop)',
        'm7.field.portraitPrompt': 'Промпт портрета',
        'm7.field.offScene': 'Сцена',
        'm7.field.book': 'Книга',
        'm7.field.keys': 'Ключи',
        'm7.field.protected': 'Защита',
        'm7.field.canon': 'Канон',
        'm7.field.status': 'Статус',
        'm7.field.overrides': 'Переопределённые поля',
        'm7.field.origin': 'Откуда',
        'm7.field.type': 'Тип',
        'm7.field.name': 'Имя',
        'm7.field.mbti': 'MBTI',
        'm7.field.tagCount': 'Тегов',
        'm7.field.id': 'Id',
        'm7.field.kind': 'Вид',
        'm7.field.tags': 'Теги',
        'm7.field.outfits': 'Наряды',
        'm7.field.activeOutfit': 'Наряд сейчас',
        'm7.field.states': 'Состояния',
        'm7.field.negative': 'Никогда не рисовать',
        'm7.field.level': 'Уровень',
        'm7.field.owner': 'Карточка',
        'm7.field.chatOverride': 'Изменено в этом чате',
        'm7.field.formsKey': 'Ключ-регулярка',
        'm7.field.desru': 'DES-RU',
        'm7.field.longTerm': 'Долгих',
        'm7.field.recent': 'Недавних',
        'm7.field.command': 'Команда',
        'm7.field.message': 'Сообщение',
        'm7.field.slot.base': 'Основа',
        'm7.field.slot.hair': 'Волосы',
        'm7.field.slot.eyes': 'Глаза',
        'm7.field.slot.body': 'Тело',
        'm7.field.slot.skin': 'Кожа',
        'm7.field.slot.clothing': 'Одежда',
        'm7.field.slot.accessories': 'Аксессуары',
        'm7.field.slot.style': 'Стиль',
        'm7.field.text': 'Текст',
        'm7.field.looks': 'Внешность (теги)',
        'm7.field.otherNames': 'Другие имена',
        'm7.field.placeName': 'Название',
        'm7.field.placeAliases': 'Другие названия',
        'm7.field.nickname': 'Прозвище',
        'm7.field.means': 'Кто это',
        'm7.slash.help': 'Открывает досье персонажа, места или твоей персоны: /maestro-dossier [имя].',
        'm7.slash.name': 'Имя, прозвище или падежная форма (пусто — список)',
        'm7.slash.notFound': 'Никого по имени «{name}» не знаю.',
        'm7.styleUp.action': 'Оформить',
        'm7.styleUp.profileTask': 'Досье: черты листа характера для «Оформить»',
        'm7.styleUp.actionHint':
            'Заводит разом всё, чего не хватает: запись в каноне чата, лист характера, внешность для картинок.',
        'm7.styleUp.missing': 'Не хватает: {list}.',
        'm7.styleUp.title': 'Оформить: {name}',
        'm7.styleUp.planning': 'Готовлю план… (фоновая модель подбирает черты для листа характера)',
        'm7.styleUp.intro':
            'Вот что появится. Сними галочку с ненужного. Всё уйдёт одной карточкой во «Входящие» (или применится сразу, если ты так настроил).',
        'm7.styleUp.apply': 'Оформить',
        'm7.styleUp.cancel': 'Отмена',
        'm7.styleUp.close': 'Закрыть',
        'm7.styleUp.nothing': 'Сейчас создать нечего.',
        'm7.styleUp.none': 'Отметь хотя бы одну часть.',
        'm7.styleUp.book': 'Книга для листа характера',
        'm7.styleUp.bookLine': 'Книга: {book}',
        'm7.styleUp.keys': 'Ключи: {list}',
        'm7.styleUp.tags': 'Теги: {list}',
        'm7.styleUp.rejected': 'Не прошли проверку: {list}',
        'm7.styleUp.cost': 'План обошёлся в {usd}.',
        'm7.styleUp.before': 'Сейчас: нет',
        'm7.styleUp.show': 'Что запишется',
        'm7.styleUp.status.title': 'Оформление в {time}',
        'm7.styleUp.status.ok': '✓ {part}',
        'm7.styleUp.status.failed': '✗ {part}: {error}',
        'm7.styleUp.status.sent': 'План для «{name}» ждёт во «Входящих».',
        'm7.styleUp.part.canon': 'Запись в каноне чата',
        'm7.styleUp.part.archive': 'Лист характера',
        'm7.styleUp.part.passport': 'Внешность для картинок',
        'm7.styleUp.part.placeEntry': 'Описание места',
        'm7.styleUp.part.lorePassport': 'Место на картинках',
        'm7.styleUp.part.promote': 'Книга карточки',
        'm7.styleUp.line.canon': 'Запись о персонаже в каноне чата',
        'm7.styleUp.line.archive': 'Лист характера — черт: {count}',
        'm7.styleUp.line.archiveNew': 'Лист характера в новой книге — черт: {count}',
        'm7.styleUp.line.passport': 'Внешность для картинок — только в этом чате',
        'm7.styleUp.line.placeEntry': 'Описание места «{name}» в каноне чата',
        'm7.styleUp.line.lorePassport': 'Вид места для картинок (составится по описанию)',
        'm7.styleUp.preview.lorePassport': 'Составится по описанию места, когда оно будет записано.',
        'm7.styleUp.card.title': '{name}: завести всё, чего не хватает?',
        'm7.styleUp.card.place': 'Место «{name}»: завести всё, чего не хватает?',
        'm7.styleUp.card.body': 'Если согласишься, появится:',
        'm7.styleUp.card.undo': 'Каждую часть можно будет отменить отдельно — из журнала.',
        'm7.styleUp.card.applied': '{name}: завёл всё, чего не хватало.',
        'm7.styleUp.card.appliedPlace': 'Место «{name}»: завёл всё, чего не хватало.',
        'm7.styleUp.details.canon': 'Запись канона чата «{title}», ключи: {keys}',
        'm7.styleUp.details.archive': 'Лист характера в книге «{book}»: {tags}',
        'm7.styleUp.details.archiveNew': 'Лист характера в новой книге «{book}»: {tags}',
        'm7.styleUp.details.passport': 'Паспорт NAI Studio {id}: {tags}',
        'm7.styleUp.partial': '{name}: завёл не всё. Не получилось — {errors}',
        'm7.styleUp.journal.canon': '{name}: завёл запись в каноне чата',
        'm7.styleUp.journal.archive': '{name}: завёл лист характера',
        'm7.styleUp.journal.passport': '{name}: завёл внешность для картинок в этом чате',
        'm7.styleUp.journal.placeEntry': 'Место «{name}»: завёл описание в каноне чата',
        'm7.styleUp.journal.lorePassport': 'Место «{name}»: составил вид для картинок',
        'm7.styleUp.journal.promote': 'Перенёс «{title}» в книгу карточки',
        'm7.styleUp.error.noBook': 'Книги «{book}» больше нет.',
        'm7.styleUp.error.archiveExists': '{name}: лист характера уже есть в книге «{book}».',
        'm7.styleUp.error.passport': 'Не получилось прочитать внешность для картинок.',
        'm7.styleUp.error.placeGone': 'Этого места больше нет в списке мест.',
        'm7.styleUp.error.noLorePassports': 'Выключен модуль «Паспорта в лорбуках».',
        'm7.styleUp.error.noPlaceEntry': 'У места нет описания.',
        'm7.styleUp.error.lorePassport': 'Не получилось составить вид места для картинок.',
        'm7.styleUp.note.notRepo':
            'Лист записан, но CarrotKernel его пока не видит: отметь книгу «{book}» в CarrotKernel как Character Repo и подключи её.',
        'm7.styleUp.note.placeLinked': 'У места уже была запись с описанием: её привязал, а не переписал.',
        'm7.styleUp.note.passportExists': 'Вид места для картинок уже был.',
        'm7.styleUp.hint.noChat': 'Открой чат: «Оформить» пишет в канон и во «Входящие» этого чата.',
        'm7.styleUp.hint.failed': 'Не удалось подготовить: {error}.',
        'm7.styleUp.hint.canonOff': 'Выключен «Канон чата» — записи о персонаже не будет.',
        'm7.styleUp.hint.archiveNoBunnymo': 'Выключен «Режим BunnyMo» — черты для листа характера не из чего выбрать.',
        'm7.styleUp.hint.archiveNoProfile':
            'Нет профиля подключения для фоновых задач — лист характера не подготовить.',
        'm7.styleUp.hint.archiveCap': 'Дневной лимит фоновых задач исчерпан — листа характера в этот раз не будет.',
        'm7.styleUp.hint.archiveBunnyRepo':
            '«{book}» отмечена в CarrotKernel как книга для листов, но это книга BunnyMo — туда я ничего не пишу.',
        'm7.styleUp.hint.archiveNoPacks': 'Паки BunnyMo не загружены — черты для листа характера неоткуда взять.',
        'm7.styleUp.hint.archiveFailed': 'Модель не подобрала черты: {error}.',
        'm7.styleUp.hint.archiveParse': 'Модель ответила не в том виде, который нужен.',
        'm7.styleUp.hint.archiveRejected': 'Не прошли проверку словаря BunnyMo: {tags}.',
        'm7.styleUp.hint.archiveDropped':
            'Dramatis предложил ещё и черты, которых нет в подключённых паках BunnyMo: {tags}.',
        'm7.styleUp.hint.archiveEmpty': 'Ни одна черта от модели не прошла проверку — листа характера не будет.',
        'm7.styleUp.hint.archiveNewBook':
            'Подходящей книги для листов характера нет, поэтому заведу новую — «{book}». CarrotKernel увидит её, когда ты отметишь её там как Character Repo и подключишь (глобально или к карточке).',
        'm7.styleUp.hint.passportAuto':
            '{name}: NAI Studio сам опишет внешность для картинок, когда персонаж появится в сцене (у него включены автопаспорта).',
        'm7.styleUp.hint.passportManual':
            'Внешность для картинок заведи в NAI Studio → менеджер паспортов: отсюда NAI Studio её составить не может.',
        'm7.styleUp.hint.passportFailed': 'NAI Studio не смог составить внешность для картинок: {error}.',
        'm7.styleUp.hint.placesOff': 'Выключен модуль «Места» — описания места не будет.',
        'm7.styleUp.promote.action': 'В книгу карточки',
        'm7.styleUp.promote.hint':
            'Перенесёт запись в книгу карточки «{book}» — она будет работать во всех чатах с этой карточкой (сначала спрошу).',
        'm7.styleUp.promote.noBook': 'У карточки нет своей книги лора.',
        'm7.styleUp.promote.title': 'Перенести «{title}» в книгу карточки?',
        'm7.styleUp.promote.body':
            'Запись заработает во всех чатах с этой карточкой, а из канона этого чата уберётся, чтобы не срабатывать дважды. Отменить можно из журнала.',
        'm7.styleUp.promote.details': 'Книга карточки: «{book}».',
        'm7.mechanics.title': 'Механики',
        'm7.wardrobe.title': 'Наряды ({count})',
        'm7.wardrobe.active': 'надет',
        'm7.wardrobe.wear': 'Надеть',
        'm7.wardrobe.wearHint': 'Сделать этот наряд активным в этом чате (карточка не меняется).',
        'm7.wardrobe.worn': 'Теперь надет наряд «{name}».',
    },
};
