// @vitest-environment happy-dom
import { describe, expect, it } from 'vitest';
import type { LorePassportsApi } from '../../../src/features/lorePassports/api';
import type { WiBindings } from '../../../src/features/loreStudio/store-api';
import { ANNA_PASSPORT, createEnv, fakeNai, seedBooks, settle } from './helpers';
import type { Env } from './helpers';

function bind(env: Env, global: string[]): void {
    env.store.bindings = async (): Promise<WiBindings> => ({
        global,
        character: { primary: null, extra: [] },
        chat: null,
        persona: null,
    });
}

function buttons(root: ParentNode): string[] {
    return [...root.querySelectorAll('button')].map((node) => node.textContent?.trim() ?? '');
}

function click(root: ParentNode, label: string): void {
    const node = [...root.querySelectorAll('button')].find((item) => item.textContent?.trim().startsWith(label));
    if (!node) throw new Error(`no button ${label}`);
    node.click();
}

async function render(env: Env): Promise<{ root: HTMLElement; stop(): Promise<void>; dispose(): void }> {
    const running = await env.start();
    const tab = env.tabs.find((item) => item.id === 'lorePassports')!;
    expect(tab).toMatchObject({ titleKey: 'm28.tab', order: 61 });
    const root = document.createElement('div');
    document.body.append(root);
    const dispose = tab.render(root) as () => void;
    await settle(10);
    return { root, stop: () => running.stop(), dispose };
}

describe('lore passports: pult tab', () => {
    it('lists passports of the active books and the typed entries that could have one', async () => {
        const env = createEnv({ nai: fakeNai({ generator: true }) });
        seedBooks(env);
        bind(env, ['Places', 'World', 'Bunny']);
        const view = await render(env);
        const api = env.apis.get('lorePassports') as LorePassportsApi;
        await api.set('World', 0, ANNA_PASSPORT);
        await settle(10);
        const text = view.root.textContent ?? '';
        expect(text).toContain('Passports in active books (1)');
        expect(text).toContain('Anna');
        expect(text).toContain('1girl, elf, silver hair, green eyes');
        expect(text).toContain('Maestro registry');
        // The place is typed and can be drawn; the rule cannot; BunnyMo is never listed.
        expect(text).toContain('Typed entries without a passport (1)');
        expect(text).toContain('Silver Tower');
        expect(text).not.toContain('House rules');
        expect(text).not.toContain('Trait');
        expect(text).toContain('NAI Studio receives the passports of the scene.');
        expect(text).toContain('Passports are generated by NAI Studio.');
        expect(text).toContain('NAI Studio has not asked for passports yet.');
        view.dispose();
        expect(view.root.children).toHaveLength(0);
        await view.stop();
    });

    it('generates the missing passports after a confirmation with the estimate', async () => {
        const env = createEnv({ nai: fakeNai({ generator: true }) });
        seedBooks(env);
        bind(env, ['Places', 'World']);
        const view = await render(env);
        env.confirm.mockResolvedValueOnce(false);
        click(view.root, 'Generate missing (1)');
        await settle(10);
        expect(env.confirm).toHaveBeenCalledTimes(1);
        expect(String(env.confirm.mock.calls[0]![1])).toMatch(/1 entries .* NAI Studio\. Estimate: ≈ \d+ tokens/);
        expect(env.nai.generatePassport).not.toHaveBeenCalled();
        click(view.root, 'Generate missing (1)');
        await settle(20);
        expect(env.nai.generatePassport).toHaveBeenCalledTimes(1);
        const text = view.root.textContent ?? '';
        expect(text).toContain('Done: 1 of 1, failed 0, skipped 0.');
        expect(text).toContain('Passports in active books (1)');
        expect(text).toContain('Every typed entry that can be drawn has a passport.');
        await view.stop();
    });

    it('explains why nothing can generate, shows what NAI Studio received and toggles the provider', async () => {
        const env = createEnv({ nai: fakeNai() });
        seedBooks(env);
        bind(env, ['Places', 'World']);
        env.state.chatId = null;
        env.loreJournal.push(2, [{ world: 'World', uid: 0 }]);
        const view = await render(env);
        const api = env.apis.get('lorePassports') as LorePassportsApi;
        await api.set('World', 0, ANNA_PASSPORT);
        await settle(10);
        expect(view.root.textContent).toContain('Generation is not available now');
        click(view.root, 'Generate missing (1)');
        await settle();
        expect(env.notice).toHaveBeenCalledWith(expect.stringContaining('open chat'), { level: 'warn', urgent: true });
        await env.nai.providers[0]!.passports({ messageIndex: 2, text: '' });
        await settle(10);
        expect(view.root.textContent).toMatch(/For message #2, .*: Anna/);
        expect(view.root.textContent).toContain('In the scene now');
        const toggle = view.root.querySelector<HTMLInputElement>('input[name="m28Provider"]')!;
        toggle.checked = false;
        toggle.dispatchEvent(new Event('change'));
        await settle();
        expect(env.settings.provider).toBe(false);
        expect(env.app.settings.save).toHaveBeenCalled();
        expect(env.nai.providers).toHaveLength(0);
        expect(view.root.textContent).toContain('Sending passports to NAI Studio is switched off.');
        await view.stop();
    });

    it('opens an entry in the Lore Studio and refreshes', async () => {
        const env = createEnv();
        seedBooks(env);
        bind(env, ['Places']);
        const opened: unknown[] = [];
        env.apis.set('loreStudio', { open: (book: string, uid: number) => opened.push([book, uid]) });
        env.nai.present = () => false;
        const view = await render(env);
        expect(view.root.textContent).toContain('NAI Studio is not installed');
        expect(buttons(view.root)).toContain('Open in the Lore Studio');
        click(view.root, 'Open in the Lore Studio');
        expect(opened).toEqual([['Places', 0]]);
        expect(env.app.ui.closePult).toHaveBeenCalled();
        click(view.root, 'Refresh');
        await settle(10);
        expect(view.root.textContent).toContain('Typed entries without a passport (1)');
        await view.stop();
    });
});
