// Strings of M37 «Подготовить к игре» (en + ru) and how its journal steps read (plan-2 §3).
import type { I18nParts, TargetSpec } from '../../shared/contracts';
import { PREPARE_STEP_TARGET } from './settings';

export const PREPARE_STRINGS: I18nParts = {
    en: {
        'm37.title': 'Prepare to play',
        'm37.tab': 'Preparation',
        'kind.prepare.apply': 'Story preparation',
        'kind.prepare.import': 'Saved story preparation',
        'm37.target.step': 'Part of the preparation',
        'm37.field.what': 'What',
        'm37.field.name': 'Name',
        'm37.field.detail': 'Text',

        'm37.section.world': 'World',
        'm37.section.time': 'Time',
        'm37.section.place': 'Places',
        'm37.section.faction': 'Factions',
        'm37.section.character': 'Characters',
        'm37.section.item': 'Items',
        'm37.section.tradition': 'Traditions',
        'm37.section.secret': 'Secrets',
        'm37.section.promise': 'Promises',
        'm37.section.mechanic': 'Mechanics',
        'm37.section.scene': 'Starting scene',
        'm37.section.direction': 'Direction',

        'm37.describe.world': 'The world: {name}',
        'm37.describe.time': 'The story starts: {name}',
        'm37.describe.place': 'Place «{name}»',
        'm37.describe.faction': 'Faction «{name}»',
        'm37.describe.character': 'Character {name}',
        'm37.describe.item': 'Item «{name}»',
        'm37.describe.tradition': 'Tradition «{name}»',
        'm37.describe.secret': 'A secret: {name}',
        'm37.describe.promise': 'A promise: {name}',
        'm37.describe.mechanic': 'Mechanic «{name}»',
        'm37.describe.scene': 'Starting scene: {name}',
        'm37.describe.direction': 'Direction: {name}',

        'm37.source.description': 'Card description',
        'm37.source.personality': 'Card personality',
        'm37.source.scenario': 'Scenario',
        'm37.source.greeting': 'The chosen greeting',
        'm37.source.greetings': 'Other greetings',
        'm37.source.examples': 'Dialogue examples',
        'm37.source.notes': "Author's notes",
        'm37.source.system': 'System fields of the card',
        'm37.source.persona': 'Your persona',

        'm37.part.canon': 'into the canon',
        'm37.part.cardBook': 'saved for the character',
        'm37.part.place': 'place',
        'm37.part.passport': 'passport',
        'm37.part.passportCard': 'passport in the card',
        'm37.part.secret': 'secret',
        'm37.part.promise': 'into the calendar',
        'm37.part.mechanic': 'mechanic',
        'm37.part.mechanicCard': 'mechanic for the character',
        'm37.part.value': 'starting value',
        'm37.part.values': 'starting values: {count}',
        'm37.part.outfits': 'starting outfits',
        'm37.part.outfit': 'outfit',
        'm37.part.firstScene': 'type of the first scene',

        'm37.skip.persona': 'this is your character',
        'm37.skip.moduleOff': 'the «{module}» module is off',
        'm37.skip.inCanon': 'already in the canon',
        'm37.skip.placeExists': 'the place exists already',
        'm37.skip.passportsOff': 'passports are switched off',
        'm37.skip.passportExists': 'has a passport already',
        'm37.skip.noPassportGen': 'NAI Studio cannot make passports (0.12 or newer is needed)',
        'm37.skip.noAppearance': 'no appearance to make a passport from',
        'm37.skip.exists': 'exists already',
        'm37.skip.noChat': 'no chat is open',
        'm37.skip.values': 'starting values that did not fit: {count}',
        'm37.skip.noOutfits': 'nobody has a starting outfit',
        'm37.skip.noFirstScene': 'the type of the first scene is unclear',
        'm37.skip.nothing': 'nothing to write',

        'm37.module.canon': 'Chat canon',
        'm37.module.places': 'Places',
        'm37.module.knowledge': 'Who knows what',
        'm37.module.calendar': 'Calendar',
        'm37.module.mechanics': 'Mechanics',
        'm37.module.wardrobe': 'Wardrobe',
        'm37.module.director': 'Director',

        'm37.exists.canon': 'in the canon',
        'm37.exists.places': 'place exists',
        'm37.exists.mechanics': 'mechanic exists',
        'm37.exists.passport': 'has a passport',
        'm37.exists.persona': 'your character',
        'm37.exists.calendar': 'in the calendar',
        'm37.exists.knowledge': 'known already',
        'm37.conflict': 'the canon says otherwise: {fields}',
        'm37.conflictField.role': 'role',
        'm37.conflictField.appearance': 'appearance',
        'm37.conflictField.personality': 'personality',
        'm37.conflictField.description': 'description',
        'm37.conflictField.leader': 'leader',
        'm37.conflictField.goals': 'goals',
        'm37.conflictField.owner': 'owner',
        'm37.conflictField.practice': 'custom',
        'm37.scope.chat': 'for this chat',
        'm37.scope.character': 'for the character',

        'm37.scene.dialogue': 'conversation',
        'm37.scene.combat': 'fight',
        'm37.scene.intimate': 'intimacy',
        'm37.scene.exploration': 'exploration',
        'm37.scene.timeskip': 'time skip',
        'm37.scene.social': 'company',
        'm37.scene.drama': 'drama',

        'm37.result.failedPart': '{part}: failed ({error})',
        'm37.result.partly': '(failed: {parts})',
        'm37.journal.apply': 'Preparation: {title} — {parts}',
        'm37.journal.import': 'Saved preparation: {title} — {parts}',
        'm37.undo.cardPassport':
            'The passport of {name} was written into the card; Maestro cannot take it back from there — remove it in NAI Studio.',
        'm37.proposal.background': 'A library background fits «{place}»: {file}',
        'm37.proposal.generate':
            'The library has no background for «{place}»; you can generate one in the backgrounds window',

        'm37.error.noWorldInfo': 'This SillyTavern cannot save lorebooks',
        'm37.error.protectedBook': 'Maestro does not change the book «{book}»',
        'm37.error.passport': 'NAI Studio did not make a passport',
        'm37.error.noCard': 'Preparation works in a chat with one character',
        'm37.error.noChat': 'No chat is open',
        'm37.error.noPlan': 'Analyse the story first',
        'm37.error.noSaved': 'This character has no saved preparation',

        'm37.job.title': 'Preparing to play: {card}',
        'm37.job.open': 'Open',
        'm37.job.collecting': 'Reading the card and its books…',
        'm37.job.progress': 'Analysing: part {done} of {total}',
        'm37.job.done': 'The story is analysed: {count} items',
        'm37.job.stopped': 'Stopped; what was read is kept ({count} items)',
        'm37.job.failed': 'The model did not analyse the story: {error}',
        'm37.job.error': 'Preparation broke off: {error}',
        'm37.job.chatChanged': 'The chat changed; the analysis was not kept',
        'm37.job.cap': "Today's limit of Maestro's background spending is reached: the story was not analysed",

        'm37.confirm.title': 'Save for the character?',
        'm37.confirm.body':
            'Items for the character: {count}. They are kept for every new chat with «{card}»: the texts in a Maestro book of this card, the passports in the card. Go on?',
        'm37.notice.applied': 'Preparation applied: {count} parts',
        'm37.notice.appliedWithErrors': 'Preparation applied in part: {count} done, {failed} failed',

        'm37.ready.plan': 'The preparation is not applied yet',
        'm37.ready.passport': '{name} has no passport',
        'm37.ready.portrait': '{name} has no portrait',
        'm37.ready.place': 'The place «{name}» is not created yet',
        'm37.ready.background': '«{name}» has no background',

        'm37.view.intro':
            'Before the first move Maestro reads the card, its books and your persona and proposes characters, places, the world, time, secrets, mechanics and the first scene.',
        'm37.view.notNew.noChat': 'Open a chat to prepare it.',
        'm37.view.notNew.group': 'Group chats are not prepared.',
        'm37.view.notNew.noCard': 'Preparation works in a chat with one character.',
        'm37.view.notNew.started': 'The chat has begun: preparation is offered only before your first message.',
        'm37.view.estimate': 'Estimate',
        'm37.view.estimateLine': 'Requests: {chunks}, sources: {sources}, about {usd}',
        'm37.view.skipped': 'Did not fit the budget: {list}',
        'm37.view.start': 'Analyse',
        'm37.view.reuse': 'Analyse what changed',
        'm37.view.stop': 'Stop',
        'm37.view.plan': 'Plan',
        'm37.view.partial': 'The analysis was stopped: the plan is incomplete.',
        'm37.view.failedParts': 'Parts not read: {count}',
        'm37.view.applyChat': 'Apply for this chat',
        'm37.view.applyCharacter': 'Apply for the character',
        'm37.view.discard': 'Forget the plan',
        'm37.view.saved': 'Saved preparation',
        'm37.view.savedLine': 'Saved {time}: {count} items',
        'm37.view.changed': 'Changed since: {list}',
        'm37.view.applySaved': 'Apply the saved preparation',
        'm37.view.status': 'Ready to play',
        'm37.view.ready': 'Everything important is in place.',
        'm37.view.result': 'Result',
        'm37.view.applied': 'Applied: {list}',

        'm37.slash.help':
            'Prepare a new chat: /maestro-prepare analyses and lists the plan; again — analyse anew; apply — apply everything for this chat; saved — apply the saved preparation; status — what is missing',
        'm37.slash.value': 'again, apply, saved or status',
        'm37.slash.running': 'The analysis is running already',
        'm37.slash.empty': 'The plan is empty',
        'm37.slash.started': 'Analysis started',
    },
    ru: {
        'm37.title': 'Подготовка к игре',
        'm37.tab': 'Подготовка',
        'kind.prepare.apply': 'Подготовка к игре',
        'kind.prepare.import': 'Сохранённая подготовка к игре',
        'm37.target.step': 'Часть подготовки',
        'm37.field.what': 'Что',
        'm37.field.name': 'Название',
        'm37.field.detail': 'Текст',

        'm37.section.world': 'Мир',
        'm37.section.time': 'Время',
        'm37.section.place': 'Места',
        'm37.section.faction': 'Фракции',
        'm37.section.character': 'Персонажи',
        'm37.section.item': 'Предметы',
        'm37.section.tradition': 'Традиции',
        'm37.section.secret': 'Секреты',
        'm37.section.promise': 'Обещания',
        'm37.section.mechanic': 'Механики',
        'm37.section.scene': 'Стартовая сцена',
        'm37.section.direction': 'Режиссура',

        'm37.describe.world': 'Мир: {name}',
        'm37.describe.time': 'Начало истории: {name}',
        'm37.describe.place': 'Место «{name}»',
        'm37.describe.faction': 'Фракция «{name}»',
        'm37.describe.character': 'Персонаж {name}',
        'm37.describe.item': 'Предмет «{name}»',
        'm37.describe.tradition': 'Традиция «{name}»',
        'm37.describe.secret': 'Секрет: {name}',
        'm37.describe.promise': 'Обещание: {name}',
        'm37.describe.mechanic': 'Механика «{name}»',
        'm37.describe.scene': 'Стартовая сцена: {name}',
        'm37.describe.direction': 'Режиссура: {name}',

        'm37.source.description': 'Описание карточки',
        'm37.source.personality': 'Характер из карточки',
        'm37.source.scenario': 'Сценарий',
        'm37.source.greeting': 'Выбранное приветствие',
        'm37.source.greetings': 'Другие приветствия',
        'm37.source.examples': 'Примеры диалогов',
        'm37.source.notes': 'Заметки автора',
        'm37.source.system': 'Системные поля карточки',
        'm37.source.persona': 'Твоя персона',

        'm37.part.canon': 'в канон',
        'm37.part.cardBook': 'сохранено для персонажа',
        'm37.part.place': 'место',
        'm37.part.passport': 'паспорт',
        'm37.part.passportCard': 'паспорт в карточке',
        'm37.part.secret': 'секрет',
        'm37.part.promise': 'в календарь',
        'm37.part.mechanic': 'механика',
        'm37.part.mechanicCard': 'механика для персонажа',
        'm37.part.value': 'начальное значение',
        'm37.part.values': 'начальные значения: {count}',
        'm37.part.outfits': 'стартовые наряды',
        'm37.part.outfit': 'наряд',
        'm37.part.firstScene': 'тип первой сцены',

        'm37.skip.persona': 'это твой персонаж',
        'm37.skip.moduleOff': 'модуль «{module}» выключен',
        'm37.skip.inCanon': 'уже есть в каноне',
        'm37.skip.placeExists': 'место уже есть',
        'm37.skip.passportsOff': 'паспорта выключены',
        'm37.skip.passportExists': 'паспорт уже есть',
        'm37.skip.noPassportGen': 'NAI Studio не умеет делать паспорта (нужна версия 0.12 или новее)',
        'm37.skip.noAppearance': 'нет описания внешности для паспорта',
        'm37.skip.exists': 'уже есть',
        'm37.skip.noChat': 'чат не открыт',
        'm37.skip.values': 'не подошли начальные значения: {count}',
        'm37.skip.noOutfits': 'стартовых нарядов нет',
        'm37.skip.noFirstScene': 'тип первой сцены не ясен',
        'm37.skip.nothing': 'нечего записать',

        'm37.module.canon': 'Канон чата',
        'm37.module.places': 'Места',
        'm37.module.knowledge': 'Кто что знает',
        'm37.module.calendar': 'Календарь',
        'm37.module.mechanics': 'Механики',
        'm37.module.wardrobe': 'Гардероб',
        'm37.module.director': 'Режиссёр',

        'm37.exists.canon': 'уже в каноне',
        'm37.exists.places': 'место уже есть',
        'm37.exists.mechanics': 'механика уже есть',
        'm37.exists.passport': 'паспорт уже есть',
        'm37.exists.persona': 'твой персонаж',
        'm37.exists.calendar': 'уже в календаре',
        'm37.exists.knowledge': 'уже известно',
        'm37.conflict': 'в каноне иначе: {fields}',
        'm37.conflictField.role': 'роль',
        'm37.conflictField.appearance': 'внешность',
        'm37.conflictField.personality': 'характер',
        'm37.conflictField.description': 'описание',
        'm37.conflictField.leader': 'глава',
        'm37.conflictField.goals': 'цели',
        'm37.conflictField.owner': 'владелец',
        'm37.conflictField.practice': 'обычай',
        'm37.scope.chat': 'для чата',
        'm37.scope.character': 'для персонажа',

        'm37.scene.dialogue': 'разговор',
        'm37.scene.combat': 'бой',
        'm37.scene.intimate': 'близость',
        'm37.scene.exploration': 'исследование',
        'm37.scene.timeskip': 'пропуск времени',
        'm37.scene.social': 'общение',
        'm37.scene.drama': 'драма',

        'm37.result.failedPart': '{part}: не удалось ({error})',
        'm37.result.partly': '(не удалось: {parts})',
        'm37.journal.apply': 'Подготовка: {title} — {parts}',
        'm37.journal.import': 'Сохранённая подготовка: {title} — {parts}',
        'm37.undo.cardPassport':
            'Паспорт {name} записан в карточку, и Maestro не может его оттуда убрать — удали его в NAI Studio.',
        'm37.proposal.background': 'Для «{place}» есть подходящий фон из библиотеки: {file}',
        'm37.proposal.generate': 'Для «{place}» в библиотеке нет фона — его можно сгенерировать в окне фонов',

        'm37.error.noWorldInfo': 'Эта версия SillyTavern не умеет сохранять лорбуки',
        'm37.error.protectedBook': 'Книгу «{book}» Maestro не меняет',
        'm37.error.passport': 'NAI Studio не сделал паспорт',
        'm37.error.noCard': 'Подготовка работает в чате с одним персонажем',
        'm37.error.noChat': 'Чат не открыт',
        'm37.error.noPlan': 'Сначала разбери сценарий',
        'm37.error.noSaved': 'Для этого персонажа нет сохранённой подготовки',

        'm37.job.title': 'Подготовка к игре: {card}',
        'm37.job.open': 'Открыть',
        'm37.job.collecting': 'Читаю карточку и книги…',
        'm37.job.progress': 'Разбираю: часть {done} из {total}',
        'm37.job.done': 'Сценарий разобран, пунктов: {count}',
        'm37.job.stopped': 'Остановлено, разобранное сохранено (пунктов: {count})',
        'm37.job.failed': 'Модель не разобрала сценарий: {error}',
        'm37.job.error': 'Подготовка прервалась: {error}',
        'm37.job.chatChanged': 'Чат сменился — разбор не сохранён',
        'm37.job.cap': 'Дневной лимит фоновых трат Maestro исчерпан — сценарий не разобран',

        'm37.confirm.title': 'Сохранить для персонажа?',
        'm37.confirm.body':
            'Пунктов для персонажа: {count}. Они останутся для всех новых чатов с «{card}»: тексты — в отдельной книге Maestro этой карточки, паспорта — в карточке. Продолжить?',
        'm37.notice.applied': 'Подготовка применена, частей: {count}',
        'm37.notice.appliedWithErrors': 'Подготовка применена не вся: готово {count}, не удалось {failed}',

        'm37.ready.plan': 'Подготовка ещё не применена',
        'm37.ready.passport': 'Нет паспорта: {name}',
        'm37.ready.portrait': 'Нет портрета: {name}',
        'm37.ready.place': 'Место «{name}» ещё не создано',
        'm37.ready.background': 'Нет фона для «{name}»',

        'm37.view.intro':
            'До первого хода Maestro читает карточку, её книги и твою персону и предлагает персонажей, места, мир, время, секреты, механики и первую сцену.',
        'm37.view.notNew.noChat': 'Открой чат, чтобы подготовить его.',
        'm37.view.notNew.group': 'Групповые чаты не готовятся.',
        'm37.view.notNew.noCard': 'Подготовка работает в чате с одним персонажем.',
        'm37.view.notNew.started': 'Чат уже начат: подготовка доступна только до твоего первого сообщения.',
        'm37.view.estimate': 'Оценить',
        'm37.view.estimateLine': 'Запросов: {chunks}, источников: {sources}, примерно {usd}',
        'm37.view.skipped': 'Не вошло в бюджет: {list}',
        'm37.view.start': 'Разобрать',
        'm37.view.reuse': 'Разобрать изменения',
        'm37.view.stop': 'Остановить',
        'm37.view.plan': 'План',
        'm37.view.partial': 'Разбор остановлен — план неполный.',
        'm37.view.failedParts': 'Не прочитано частей: {count}',
        'm37.view.applyChat': 'Применить для чата',
        'm37.view.applyCharacter': 'Применить для персонажа',
        'm37.view.discard': 'Забыть план',
        'm37.view.saved': 'Сохранённая подготовка',
        'm37.view.savedLine': 'Сохранена {time}, пунктов: {count}',
        'm37.view.changed': 'С тех пор изменилось: {list}',
        'm37.view.applySaved': 'Применить сохранённую',
        'm37.view.status': 'Готово к игре',
        'm37.view.ready': 'Всё важное на месте.',
        'm37.view.result': 'Итог',
        'm37.view.applied': 'Применено: {list}',

        'm37.slash.help':
            'Подготовить новый чат: /maestro-prepare — разобрать и показать план; again — разобрать заново; apply — применить всё для чата; saved — применить сохранённую подготовку; status — чего не хватает',
        'm37.slash.value': 'again, apply, saved или status',
        'm37.slash.running': 'Разбор уже идёт',
        'm37.slash.empty': 'План пуст',
        'm37.slash.started': 'Разбор начат',
    },
};

/** How the steps of an applied item read in the journal and Inbox cards. */
export const PREPARE_TARGETS: TargetSpec[] = [
    {
        target: PREPARE_STEP_TARGET,
        labelKey: 'm37.target.step',
        fields: {
            what: { labelKey: 'm37.field.what' },
            name: { labelKey: 'm37.field.name' },
            detail: { labelKey: 'm37.field.detail', hidden: true },
        },
    },
];
