// Strings of M37 «Подготовить к игре» (en + ru) and how its journal steps read (plan-2 §3).
import type { I18nParts, TargetSpec } from '../../shared/contracts';
import { PREPARE_STEP_TARGET } from './settings';

export const PREPARE_STRINGS: I18nParts = {
    en: {
        'm37.title': 'Prepare to play',
        'm37.tab': 'Preparation',
        'kind.prepare.apply': 'Story preparation',
        'kind.prepare.import': 'Saved story preparation',
        'm37.target.step': 'Part of the preparation',
        'm37.field.what': 'What',
        'm37.field.name': 'Name',
        'm37.field.detail': 'Text',

        'm37.section.world': 'World',
        'm37.section.time': 'Time',
        'm37.section.place': 'Places',
        'm37.section.faction': 'Factions',
        'm37.section.character': 'Characters',
        'm37.section.item': 'Items',
        'm37.section.tradition': 'Traditions',
        'm37.section.secret': 'Secrets',
        'm37.section.promise': 'Promises',
        'm37.section.mechanic': 'Mechanics',
        'm37.section.scene': 'Starting scenes',
        'm37.section.direction': 'Direction',

        'm37.describe.world': 'The world: {name}',
        'm37.describe.time': 'The story starts: {name}',
        'm37.describe.place': 'Place «{name}»',
        'm37.describe.faction': 'Faction «{name}»',
        'm37.describe.character': 'Character {name}',
        'm37.describe.item': 'Item «{name}»',
        'm37.describe.tradition': 'Tradition «{name}»',
        'm37.describe.secret': 'A secret: {name}',
        'm37.describe.promise': 'A promise: {name}',
        'm37.describe.mechanic': 'Mechanic «{name}»',
        'm37.describe.scene': 'Starting scene: {name}',
        'm37.describe.direction': 'Direction: {name}',

        'm37.source.description': 'Card description',
        'm37.source.personality': 'Card personality',
        'm37.source.scenario': 'Scenario',
        'm37.source.greetingFirst': 'Starting scene 1 (the first message)',
        'm37.source.greetingN': 'Starting scene {n}',
        'm37.source.examples': 'Dialogue examples',
        'm37.source.notes': "Author's notes",
        'm37.source.system': 'System fields of the card',
        'm37.source.persona': 'Your persona',

        'm37.part.canon': 'into the canon',
        'm37.part.cardBook': 'saved for the character',
        'm37.part.place': 'place',
        'm37.part.passport': 'passport',
        'm37.part.passportCard': 'passport in the card',
        'm37.part.secret': 'secret',
        'm37.part.promise': 'into the calendar',
        'm37.part.mechanic': 'mechanic',
        'm37.part.mechanicCard': 'mechanic for the character',
        'm37.part.value': 'starting value',
        'm37.part.values': 'starting values: {count}',
        'm37.part.outfits': 'starting outfits',
        'm37.part.outfit': 'outfit',
        'm37.part.firstScene': 'type of the first scene',
        'm37.part.sceneStored': 'prepared',
        'm37.part.startNote': 'the start in the canon',

        'm37.skip.persona': 'this is your character',
        'm37.skip.moduleOff': 'the «{module}» module is off',
        'm37.skip.inCanon': 'already in the canon',
        'm37.skip.placeExists': 'the place exists already',
        'm37.skip.passportsOff': 'passports are switched off',
        'm37.skip.passportExists': 'has a passport already',
        'm37.skip.noPassportGen': 'NAI Studio cannot make passports (0.12 or newer is needed)',
        'm37.skip.noAppearance': 'no appearance to make a passport from',
        'm37.skip.exists': 'exists already',
        'm37.skip.noChat': 'no chat is open',
        'm37.skip.values': 'starting values that did not fit: {count}',
        'm37.skip.noFirstScene': 'the type of the first scene is unclear',
        'm37.skip.sceneSetsType': 'the starting scene sets the type of the first scene',
        'm37.skip.nothing': 'nothing to write',

        'm37.module.canon': 'Chat canon',
        'm37.module.places': 'Places',
        'm37.module.knowledge': 'Who knows what',
        'm37.module.calendar': 'Calendar',
        'm37.module.mechanics': 'Mechanics',
        'm37.module.wardrobe': 'Wardrobe',
        'm37.module.director': 'Director',

        'm37.exists.canon': 'in the canon',
        'm37.exists.places': 'place exists',
        'm37.exists.mechanics': 'mechanic exists',
        'm37.exists.passport': 'has a passport',
        'm37.exists.persona': 'your character',
        'm37.exists.calendar': 'in the calendar',
        'm37.exists.knowledge': 'known already',
        'm37.conflict': 'the canon says otherwise: {fields}',
        'm37.conflictField.role': 'role',
        'm37.conflictField.appearance': 'appearance',
        'm37.conflictField.personality': 'personality',
        'm37.conflictField.description': 'description',
        'm37.conflictField.leader': 'leader',
        'm37.conflictField.goals': 'goals',
        'm37.conflictField.owner': 'owner',
        'm37.conflictField.practice': 'custom',
        'm37.scope.chat': 'for this chat',
        'm37.scope.character': 'for the character',

        'm37.scene.dialogue': 'conversation',
        'm37.scene.combat': 'fight',
        'm37.scene.intimate': 'intimacy',
        'm37.scene.exploration': 'exploration',
        'm37.scene.timeskip': 'time skip',
        'm37.scene.social': 'company',
        'm37.scene.drama': 'drama',
        'm37.sceneTitle': 'Scene {n} ({place})',
        'm37.sceneNumber': 'Scene {n}',

        'm37.result.failedPart': '{part}: failed ({error})',
        'm37.result.partly': '(failed: {parts})',
        'm37.journal.apply': 'Preparation: {title} — {parts}',
        'm37.journal.import': 'Saved preparation: {title} — {parts}',
        'm37.undo.cardPassport':
            'The passport of {name} was written into the card; Maestro cannot take it back from there — remove it in NAI Studio.',
        'm37.proposal.background': 'A library background fits «{place}»: {file}',
        'm37.proposal.generate':
            'The library has no background for «{place}»; you can generate one in the backgrounds window',

        'm37.error.noWorldInfo': 'This SillyTavern cannot save lorebooks',
        'm37.error.protectedBook': 'Maestro does not change the book «{book}»',
        'm37.error.passport': 'NAI Studio did not make a passport',
        'm37.error.noCard': 'Preparation works in a chat with one character',
        'm37.error.noChat': 'No chat is open',
        'm37.error.noPlan': 'Analyse the story first',
        'm37.error.noSaved': 'This character has no saved preparation',

        'm37.job.title': 'Preparing to play: {card}',
        'm37.job.open': 'Open',
        'm37.job.collecting': 'Reading the card and its books…',
        'm37.job.progress': 'Analysing: part {done} of {total}',
        'm37.job.done': 'The story is analysed: {count} items',
        'm37.job.stopped': 'Stopped; what was read is kept ({count} items)',
        'm37.job.failed': 'The model did not analyse the story: {error}',
        'm37.job.error': 'Preparation broke off: {error}',
        'm37.job.chatChanged': 'The chat changed; the analysis was not kept',
        'm37.job.cap': "Today's limit of Maestro's background spending is reached: the story was not analysed",

        'm37.confirm.title': 'Save for the character?',
        'm37.confirm.body':
            'Items for the character: {count}. They are kept for every new chat with «{card}»: the texts in a Maestro book of this card, the passports in the card. Go on?',
        'm37.notice.applied': 'Preparation applied: {count} parts',
        'm37.notice.appliedWithErrors': 'Preparation applied in part: {count} done, {failed} failed',
        'm37.notice.scene': 'Starting scene: {what}',
        'm37.notice.sceneNone': 'This greeting is not prepared: the previous starting scene is taken back',

        'm37.des.title': 'Characters in DES',
        'm37.des.part': 'starting scenes in DES',
        'm37.des.scene': '{scene} — {names}',
        'm37.des.sceneOnly': '{scene}: the scene only',
        'm37.des.noModel': 'the model did not answer for {scenes}: names only',
        'm37.des.workshop': 'the DES Workshop is open: close it and apply again',
        'm37.des.started': 'the story has begun: the opening message stays as it is',
        'm37.des.noSwipe': '{scene} is not among the greetings of this chat',
        'm37.des.empty': '{scene}: DES shows nothing of it',
        'm37.des.notice': 'DES shows the first scene: {names}',
        'm37.des.noticeScenes': 'Starting scenes in DES: {count}',
        'm37.des.undoWorkshop': 'Close the DES Workshop to take the starting scenes back',
        'm37.des.profileTask': 'Preparation: characters in DES',

        'm37.ready.plan': 'The preparation is not applied yet',
        'm37.ready.passport': '{name} has no passport',
        'm37.ready.portrait': '{name} has no portrait',
        'm37.ready.place': 'The place «{name}» is not created yet',
        'm37.ready.background': '«{name}» has no background',
        'm37.ready.scenes': 'Starting scenes prepared: {count}. In the chat now: {scene}.',
        'm37.ready.scenesNone': 'Starting scenes prepared: {count}. The greeting in the chat now has none.',
        'm37.ready.scenesLocked': 'Starting scenes prepared: {count}. The story began with {scene}.',

        'm37.view.intro':
            'Before the first move Maestro reads the card, its books and your persona and proposes characters, places, the world, time, secrets, mechanics and every starting scene of the card.',
        'm37.view.notNew.noChat': 'Open a chat to prepare it.',
        'm37.view.notNew.group': 'Group chats are not prepared.',
        'm37.view.notNew.noCard': 'Preparation works in a chat with one character.',
        'm37.view.notNew.started': 'The chat has begun: preparation is offered only before your first message.',
        'm37.view.stop': 'Stop',
        'm37.view.plan': 'Plan',
        'm37.view.partial': 'The analysis was stopped: the plan is incomplete.',
        'm37.view.failedParts': 'Parts not read: {count}',
        'm37.view.discard': 'Forget the plan',
        'm37.view.savedLine': 'Saved {time}: {count} items',
        'm37.view.changed': 'Changed since: {list}',
        'm37.view.status': 'Ready to play',
        'm37.view.ready': 'Everything important is in place.',

        'm37.slash.help':
            'Prepare a new chat: /maestro-prepare opens the preparation window (what will be read and the price) or lists the plan; start — analyse now; again — analyse anew; apply — apply everything for this chat; saved — apply the saved preparation; status — what is missing',
        'm37.slash.value': 'start, again, apply, saved or status',
        'm37.slash.running': 'The analysis is running already',
        'm37.slash.empty': 'The plan is empty',
        'm37.slash.opened': 'Opened the preparation window: it shows what Maestro will read and what it costs.',

        'm37.window': 'Prepare to play',
        'm37.window.card': 'Preparing: {card}',

        'm37.offer.text':
            'Prepare the story to play? Maestro reads the card and the lore and fills in the characters, the world, places, mechanics…',
        'm37.offer.body':
            'First you see what will be read and what it costs. Nothing is written without you: every item can be edited, switched off or undone later.',
        'm37.offer.prepare': 'Prepare',
        'm37.offer.later': 'Not now',
        'm37.offer.saved': 'This character has a saved preparation ({count} items) — apply it?',
        'm37.offer.applySaved': 'Apply the saved one',
        'm37.offer.again': 'Analyse anew',
        'm37.offer.running': 'Preparing the story: {progress}',
        'm37.offer.ready': 'The preparation is ready ({count} items) — look it through and apply',
        'm37.offer.open': 'Look',
        'm37.offer.notice':
            'A new chat: Maestro can prepare the story — read the card and the lore and fill in the characters, the world, places and mechanics.',

        'm37.ui.step.start': 'What to read',
        'm37.ui.step.running': 'Analysis',
        'm37.ui.step.review': 'Review',
        'm37.ui.step.done': 'Result',
        'm37.ui.read': 'What Maestro reads',
        'm37.ui.counting': 'Working out what fits and what it costs…',
        'm37.ui.cost.one': '≈ {usd}, {count} part',
        'm37.ui.cost.few': '≈ {usd}, {count} parts',
        'm37.ui.cost.many': '≈ {usd}, {count} parts',
        'm37.ui.costHint':
            'One analysis by the background model. You start it yourself, so the daily cap of background spending does not stop it.',
        'm37.ui.skipped': 'Will not fit the budget: {list}',
        'm37.ui.nothingToRead': 'Nothing to read: nothing changed since the saved preparation.',
        'm37.ui.estimateFailed': 'Could not estimate: {error}',
        'm37.ui.reuse': 'Take the saved preparation and read only what changed',
        'm37.ui.start': 'Start',
        'm37.ui.notStarted': 'The analysis did not start: it is running already or the chat has begun.',
        'm37.ui.backToPlan': 'Back to the plan',
        'm37.ui.offerSetting': 'Offer preparation in new chats',
        'm37.ui.failed': 'The last analysis failed: {error}',
        'm37.ui.saved': 'Saved preparation of the character',
        'm37.ui.savedSame': 'Nothing in the card and its books changed since.',
        'm37.ui.running': 'Analysing the story',
        'm37.ui.readingPart': 'Reading part {part} of {total}…',
        'm37.ui.merging': 'Putting the plan together…',
        'm37.ui.stopping': 'Stopping after the current part…',
        'm37.ui.runningHint': 'You can close the window: the analysis goes on and the plan will wait here.',
        'm37.ui.reused': 'The plan comes from the saved preparation; only what changed was read again.',
        'm37.ui.empty': 'The model found nothing to prepare.',
        'm37.ui.selected': 'Chosen: {count} of {total}',
        'm37.ui.apply': 'Apply the chosen',
        'm37.ui.passports': 'Make NAI passports for those without one (text only, no Anlas)',
        'm37.ui.desSeed':
            'Characters in DES: who is in each starting scene, looks, mood, clothes, relationship and thoughts',
        'm37.ui.again': 'Analyse again',
        'm37.ui.discardTitle': 'Forget the plan?',
        'm37.ui.discardBody': "The chat's plan is forgotten. What was applied stays; undo it in the journal if needed.",
        'm37.ui.allSection': 'All of «{section}»',
        'm37.ui.scope': 'Where to keep it',
        'm37.ui.scopeSection': 'Where to keep «{section}»',
        'm37.ui.scopeMixed': 'mixed',
        'm37.ui.exists': '{where}: {label}',
        'm37.ui.conflictBadge': 'the canon says otherwise',
        'm37.ui.conflict': 'The canon («{with}») says otherwise about the {field}:',
        'm37.ui.savedItem': 'from the saved preparation',
        'm37.ui.edited': 'edited',
        'm37.ui.details': 'More',
        'm37.ui.editHint': 'Canon texts are kept in English: the model reads them best that way.',
        'm37.ui.sources': 'Read from: {list}',
        'm37.ui.reset': 'Drop my edits',
        'm37.ui.sceneAuto': 'decide by itself',
        'm37.ui.sceneTitle': 'Scene {n} · «{opening}»',
        'm37.ui.sceneShown': 'in the chat now',
        'm37.ui.sceneOutfits': 'Outfits at the start: {list}',
        'm37.ui.scenesHint':
            'Every checked start is prepared. The one in the chat now is active; swiping the greeting before your first message switches it.',
        'm37.ui.result': 'What was done',
        'm37.ui.nothingDone': 'Nothing was written.',
        'm37.ui.skippedLines': 'Skipped ({count})',
        'm37.ui.undo': 'Undo',
        'm37.ui.undone': 'undone',
        'm37.ui.undoFailed': 'Could not undo: {text}',
        'm37.ui.appliedAt': 'The preparation was applied {time}.',
        'm37.ui.toPlan': 'To the plan',
        'm37.ui.statusLoading': 'Checking what is ready…',
        'm37.ui.open.canon': 'Canon',
        'm37.ui.open.places': 'Places',
        'm37.ui.open.dossier': 'Characters',
        'm37.ui.open.knowledge': 'Who knows what',
        'm37.ui.open.calendar': 'Calendar',
        'm37.ui.open.mechanics': 'Mechanics',
        'm37.ui.open.wardrobe': 'Wardrobe',
        'm37.ui.open.director': 'Director',
        'm37.ui.open.backgrounds': 'Backgrounds',
        'm37.ui.fix.plan': 'To the plan',
        'm37.ui.fix.passport': 'Make a passport',
        'm37.ui.fix.portrait': 'Open the dossier',
        'm37.ui.fix.place': 'Create the place',
        'm37.ui.fix.background': 'Pick a background',

        'm37.fact.persona': 'your character',
        'm37.fact.present': 'in the first scene',
        'm37.fact.forms': 'Name forms: {list}',
        'm37.fact.parent': 'In: {name}',
        'm37.fact.leader': 'Led by: {name}',
        'm37.fact.owner': 'Owner: {name}',
        'm37.fact.calendar': 'a calendar of its own',
        'm37.fact.knownBy': 'Known to: {list}',
        'm37.fact.hiddenFrom': 'Hidden from: {list}',
        'm37.fact.promise': '{who} → {whom}',
        'm37.fact.due': 'Due: {due}',
        'm37.fact.date': 'Starts: {date}',
        'm37.fact.place': 'Place: {name}',
        'm37.fact.outfits': 'Outfits: {list}',
        'm37.fact.presentList': 'Present: {list}',
        'm37.fact.attributes': 'Values: {list}',
        'm37.fact.holders.persona': 'for you',
        'm37.fact.holders.characters': 'for the characters',
        'm37.fact.holders.named': 'for the named ones',
        'm37.fact.holders.world': 'for the world',
        'm37.fact.holders.factions': 'for the factions',
        'm37.fact.values': 'starting values: {count}',
        'm37.fact.firstScene': 'First scene: {type}',

        'm37.edit.name': 'Name as the story writes it',
        'm37.edit.english': 'Name in the canon (English)',
        'm37.edit.role': 'Role',
        'm37.edit.appearance': 'Appearance',
        'm37.edit.personality': 'Personality',
        'm37.edit.speech': 'Manner of speech',
        'm37.edit.outfit': 'Wears at the start',
        'm37.edit.setting': 'Setting',
        'm37.edit.era': 'Era',
        'm37.edit.tone': 'Tone',
        'm37.edit.laws': 'Laws of the world',
        'm37.edit.customs': 'Customs and taboos',
        'm37.edit.parent': 'Lies in',
        'm37.edit.kind': 'What it is',
        'm37.edit.description': 'Description',
        'm37.edit.state': 'State at the start',
        'm37.edit.leader': 'Leader',
        'm37.edit.goals': 'Goals',
        'm37.edit.owner': 'Owner',
        'm37.edit.when': 'When',
        'm37.edit.practice': 'How it goes',
        'm37.edit.meaning': 'What it means',
        'm37.edit.date': 'Date',
        'm37.edit.time': 'Time of day',
        'm37.edit.calendar': 'Calendar',
        'm37.edit.what': 'What is promised',
        'm37.edit.due': 'Due',
        'm37.edit.text': 'The secret',
        'm37.edit.about': 'About whom',
        'm37.edit.place': 'Where',
        'm37.edit.situation': 'What is going on',
        'm37.edit.summary': 'In short',
        'm37.edit.rules': 'Rules',
        'm37.edit.genre': 'Genre',
        'm37.edit.pacing': 'Pacing',
        'm37.edit.firstScene': 'First scene',
        'm37.edit.notes': 'Notes',
    },
    ru: {
        'm37.title': 'Подготовка к игре',
        'm37.tab': 'Подготовка',
        'kind.prepare.apply': 'Подготовка к игре',
        'kind.prepare.import': 'Сохранённая подготовка к игре',
        'm37.target.step': 'Часть подготовки',
        'm37.field.what': 'Что',
        'm37.field.name': 'Название',
        'm37.field.detail': 'Текст',

        'm37.section.world': 'Мир',
        'm37.section.time': 'Время',
        'm37.section.place': 'Места',
        'm37.section.faction': 'Фракции',
        'm37.section.character': 'Персонажи',
        'm37.section.item': 'Предметы',
        'm37.section.tradition': 'Традиции',
        'm37.section.secret': 'Секреты',
        'm37.section.promise': 'Обещания',
        'm37.section.mechanic': 'Механики',
        'm37.section.scene': 'Стартовые сцены',
        'm37.section.direction': 'Режиссура',

        'm37.describe.world': 'Мир: {name}',
        'm37.describe.time': 'Начало истории: {name}',
        'm37.describe.place': 'Место «{name}»',
        'm37.describe.faction': 'Фракция «{name}»',
        'm37.describe.character': 'Персонаж {name}',
        'm37.describe.item': 'Предмет «{name}»',
        'm37.describe.tradition': 'Традиция «{name}»',
        'm37.describe.secret': 'Секрет: {name}',
        'm37.describe.promise': 'Обещание: {name}',
        'm37.describe.mechanic': 'Механика «{name}»',
        'm37.describe.scene': 'Стартовая сцена: {name}',
        'm37.describe.direction': 'Режиссура: {name}',

        'm37.source.description': 'Описание карточки',
        'm37.source.personality': 'Характер из карточки',
        'm37.source.scenario': 'Сценарий',
        'm37.source.greetingFirst': 'Стартовая сцена 1 (первое сообщение)',
        'm37.source.greetingN': 'Стартовая сцена {n}',
        'm37.source.examples': 'Примеры диалогов',
        'm37.source.notes': 'Заметки автора',
        'm37.source.system': 'Системные поля карточки',
        'm37.source.persona': 'Твоя персона',

        'm37.part.canon': 'в канон',
        'm37.part.cardBook': 'сохранено для персонажа',
        'm37.part.place': 'место',
        'm37.part.passport': 'паспорт',
        'm37.part.passportCard': 'паспорт в карточке',
        'm37.part.secret': 'секрет',
        'm37.part.promise': 'в календарь',
        'm37.part.mechanic': 'механика',
        'm37.part.mechanicCard': 'механика для персонажа',
        'm37.part.value': 'начальное значение',
        'm37.part.values': 'начальные значения: {count}',
        'm37.part.outfits': 'стартовые наряды',
        'm37.part.outfit': 'наряд',
        'm37.part.firstScene': 'тип первой сцены',
        'm37.part.sceneStored': 'подготовлена',
        'm37.part.startNote': 'начало истории в каноне',

        'm37.skip.persona': 'это твой персонаж',
        'm37.skip.moduleOff': 'модуль «{module}» выключен',
        'm37.skip.inCanon': 'уже есть в каноне',
        'm37.skip.placeExists': 'место уже есть',
        'm37.skip.passportsOff': 'паспорта выключены',
        'm37.skip.passportExists': 'паспорт уже есть',
        'm37.skip.noPassportGen': 'NAI Studio не умеет делать паспорта (нужна версия 0.12 или новее)',
        'm37.skip.noAppearance': 'нет описания внешности для паспорта',
        'm37.skip.exists': 'уже есть',
        'm37.skip.noChat': 'чат не открыт',
        'm37.skip.values': 'не подошли начальные значения: {count}',
        'm37.skip.noFirstScene': 'тип первой сцены не ясен',
        'm37.skip.sceneSetsType': 'тип первой сцены задаёт стартовая сцена',
        'm37.skip.nothing': 'нечего записать',

        'm37.module.canon': 'Канон чата',
        'm37.module.places': 'Места',
        'm37.module.knowledge': 'Кто что знает',
        'm37.module.calendar': 'Календарь',
        'm37.module.mechanics': 'Механики',
        'm37.module.wardrobe': 'Гардероб',
        'm37.module.director': 'Режиссёр',

        'm37.exists.canon': 'уже в каноне',
        'm37.exists.places': 'место уже есть',
        'm37.exists.mechanics': 'механика уже есть',
        'm37.exists.passport': 'паспорт уже есть',
        'm37.exists.persona': 'твой персонаж',
        'm37.exists.calendar': 'уже в календаре',
        'm37.exists.knowledge': 'уже известно',
        'm37.conflict': 'в каноне иначе: {fields}',
        'm37.conflictField.role': 'роль',
        'm37.conflictField.appearance': 'внешность',
        'm37.conflictField.personality': 'характер',
        'm37.conflictField.description': 'описание',
        'm37.conflictField.leader': 'глава',
        'm37.conflictField.goals': 'цели',
        'm37.conflictField.owner': 'владелец',
        'm37.conflictField.practice': 'обычай',
        'm37.scope.chat': 'для чата',
        'm37.scope.character': 'для персонажа',

        'm37.scene.dialogue': 'разговор',
        'm37.scene.combat': 'бой',
        'm37.scene.intimate': 'близость',
        'm37.scene.exploration': 'исследование',
        'm37.scene.timeskip': 'пропуск времени',
        'm37.scene.social': 'общение',
        'm37.scene.drama': 'драма',
        'm37.sceneTitle': 'Сцена {n} ({place})',
        'm37.sceneNumber': 'Сцена {n}',

        'm37.result.failedPart': '{part}: не удалось ({error})',
        'm37.result.partly': '(не удалось: {parts})',
        'm37.journal.apply': 'Подготовка: {title} — {parts}',
        'm37.journal.import': 'Сохранённая подготовка: {title} — {parts}',
        'm37.undo.cardPassport':
            'Паспорт {name} записан в карточку, и Maestro не может его оттуда убрать — удали его в NAI Studio.',
        'm37.proposal.background': 'Для «{place}» есть подходящий фон из библиотеки: {file}',
        'm37.proposal.generate': 'Для «{place}» в библиотеке нет фона — его можно сгенерировать в окне фонов',

        'm37.error.noWorldInfo': 'Эта версия SillyTavern не умеет сохранять лорбуки',
        'm37.error.protectedBook': 'Книгу «{book}» Maestro не меняет',
        'm37.error.passport': 'NAI Studio не сделал паспорт',
        'm37.error.noCard': 'Подготовка работает в чате с одним персонажем',
        'm37.error.noChat': 'Чат не открыт',
        'm37.error.noPlan': 'Сначала разбери сценарий',
        'm37.error.noSaved': 'Для этого персонажа нет сохранённой подготовки',

        'm37.job.title': 'Подготовка к игре: {card}',
        'm37.job.open': 'Открыть',
        'm37.job.collecting': 'Читаю карточку и книги…',
        'm37.job.progress': 'Разбираю: часть {done} из {total}',
        'm37.job.done': 'Сценарий разобран, пунктов: {count}',
        'm37.job.stopped': 'Остановлено, разобранное сохранено (пунктов: {count})',
        'm37.job.failed': 'Модель не разобрала сценарий: {error}',
        'm37.job.error': 'Подготовка прервалась: {error}',
        'm37.job.chatChanged': 'Чат сменился — разбор не сохранён',
        'm37.job.cap': 'Дневной лимит фоновых трат Maestro исчерпан — сценарий не разобран',

        'm37.confirm.title': 'Сохранить для персонажа?',
        'm37.confirm.body':
            'Пунктов для персонажа: {count}. Они останутся для всех новых чатов с «{card}»: тексты — в отдельной книге Maestro этой карточки, паспорта — в карточке. Продолжить?',
        'm37.notice.applied': 'Подготовка применена, частей: {count}',
        'm37.notice.appliedWithErrors': 'Подготовка применена не вся: готово {count}, не удалось {failed}',
        'm37.notice.scene': 'Стартовая сцена: {what}',
        'm37.notice.sceneNone': 'Это приветствие не подготовлено — прежняя стартовая сцена снята',

        'm37.des.title': 'Персонажи в DES',
        'm37.des.part': 'стартовые сцены в DES',
        'm37.des.scene': '{scene} — {names}',
        'm37.des.sceneOnly': '{scene}: только сцена',
        'm37.des.noModel': 'модель не ответила для «{scenes}» — только имена',
        'm37.des.workshop': 'открыта Мастерская DES — закрой её и примени ещё раз',
        'm37.des.started': 'история уже началась — первое сообщение не меняется',
        'm37.des.noSwipe': '{scene} — такого приветствия в этом чате нет',
        'm37.des.empty': '{scene}: DES нечего показать',
        'm37.des.notice': 'В DES — персонажи первой сцены: {names}',
        'm37.des.noticeScenes': 'Стартовые сцены в DES: {count}',
        'm37.des.undoWorkshop': 'Закрой Мастерскую DES, чтобы отменить стартовые сцены в DES',
        'm37.des.profileTask': 'Подготовка: персонажи в DES',

        'm37.ready.plan': 'Подготовка ещё не применена',
        'm37.ready.passport': 'Нет паспорта: {name}',
        'm37.ready.portrait': 'Нет портрета: {name}',
        'm37.ready.place': 'Место «{name}» ещё не создано',
        'm37.ready.background': 'Нет фона для «{name}»',
        'm37.ready.scenes': 'Подготовлено стартовых сцен: {count}. Сейчас в чате: {scene}.',
        'm37.ready.scenesNone':
            'Подготовлено стартовых сцен: {count}. Для приветствия, что сейчас в чате, подготовки нет.',
        'm37.ready.scenesLocked': 'Подготовлено стартовых сцен: {count}. Игра началась: {scene}.',

        'm37.view.intro':
            'До первого хода Maestro читает карточку, её книги и твою персону и предлагает персонажей, места, мир, время, секреты, механики и все стартовые сцены карточки.',
        'm37.view.notNew.noChat': 'Открой чат, чтобы подготовить его.',
        'm37.view.notNew.group': 'Групповые чаты не готовятся.',
        'm37.view.notNew.noCard': 'Подготовка работает в чате с одним персонажем.',
        'm37.view.notNew.started': 'Чат уже начат: подготовка доступна только до твоего первого сообщения.',
        'm37.view.stop': 'Остановить',
        'm37.view.plan': 'План',
        'm37.view.partial': 'Разбор остановлен — план неполный.',
        'm37.view.failedParts': 'Не прочитано частей: {count}',
        'm37.view.discard': 'Забыть план',
        'm37.view.savedLine': 'Сохранена {time}, пунктов: {count}',
        'm37.view.changed': 'С тех пор изменилось: {list}',
        'm37.view.status': 'Готово к игре',
        'm37.view.ready': 'Всё важное на месте.',

        'm37.slash.help':
            'Подготовить новый чат: /maestro-prepare — открыть окно подготовки (что прочитается и сколько стоит) или показать план; start — разобрать сразу; again — разобрать заново; apply — применить всё для чата; saved — применить сохранённую подготовку; status — чего не хватает',
        'm37.slash.value': 'start, again, apply, saved или status',
        'm37.slash.running': 'Разбор уже идёт',
        'm37.slash.empty': 'План пуст',
        'm37.slash.opened': 'Открыл окно подготовки: там видно, что Maestro прочитает и сколько это стоит.',

        'm37.window': 'Подготовка к игре',
        'm37.window.card': 'Подготовка: {card}',

        'm37.offer.text':
            'Подготовить историю к игре? Maestro прочитает карточку и лор и заполнит персонажей, мир, места, механики…',
        'm37.offer.body':
            'Сначала покажу, что прочитаю и во сколько это обойдётся. Без тебя ничего не запишу: каждый пункт можно поправить, выключить или потом отменить.',
        'm37.offer.prepare': 'Подготовить',
        'm37.offer.later': 'Не сейчас',
        'm37.offer.saved': 'Есть подготовка для этого персонажа (пунктов: {count}) — применить?',
        'm37.offer.applySaved': 'Применить сохранённое',
        'm37.offer.again': 'Разобрать заново',
        'm37.offer.running': 'Готовлю историю к игре: {progress}',
        'm37.offer.ready': 'Подготовка готова (пунктов: {count}) — посмотри и примени',
        'm37.offer.open': 'Посмотреть',
        'm37.offer.notice':
            'Новый чат: Maestro может подготовить историю к игре — прочитать карточку и лор и заполнить персонажей, мир, места и механики.',

        'm37.ui.step.start': 'Что читать',
        'm37.ui.step.running': 'Разбор',
        'm37.ui.step.review': 'Просмотр',
        'm37.ui.step.done': 'Итог',
        'm37.ui.read': 'Что прочитает Maestro',
        'm37.ui.counting': 'Считаю, что войдёт и сколько это стоит…',
        'm37.ui.cost.one': '≈ {usd}, {count} часть',
        'm37.ui.cost.few': '≈ {usd}, {count} части',
        'm37.ui.cost.many': '≈ {usd}, {count} частей',
        'm37.ui.costHint':
            'Один разбор фоновой моделью. Его запускаешь ты сам, поэтому дневной лимит фоновых трат его не останавливает.',
        'm37.ui.skipped': 'Не войдёт в бюджет: {list}',
        'm37.ui.nothingToRead': 'Читать нечего: с сохранённой подготовки ничего не изменилось.',
        'm37.ui.estimateFailed': 'Не удалось оценить: {error}',
        'm37.ui.reuse': 'Взять сохранённую подготовку и прочитать только изменившееся',
        'm37.ui.start': 'Начать',
        'm37.ui.notStarted': 'Разбор не начался: он уже идёт или чат уже начат.',
        'm37.ui.backToPlan': 'Вернуться к плану',
        'm37.ui.offerSetting': 'Предлагать подготовку в новых чатах',
        'm37.ui.failed': 'Прошлый разбор не удался: {error}',
        'm37.ui.saved': 'Сохранённая подготовка персонажа',
        'm37.ui.savedSame': 'С тех пор в карточке и книгах ничего не изменилось.',
        'm37.ui.running': 'Разбираю историю',
        'm37.ui.readingPart': 'Читаю часть {part} из {total}…',
        'm37.ui.merging': 'Собираю план…',
        'm37.ui.stopping': 'Остановлюсь после текущей части…',
        'm37.ui.runningHint': 'Окно можно закрыть: разбор продолжится, а план будет ждать здесь.',
        'm37.ui.reused': 'План взят из сохранённой подготовки, заново прочитано только изменившееся.',
        'm37.ui.empty': 'Модель не нашла, что подготовить.',
        'm37.ui.selected': 'Выбрано: {count} из {total}',
        'm37.ui.apply': 'Применить выбранное',
        'm37.ui.passports': 'Сделать паспорта NAI тем, у кого их нет (только текст, без Anlas)',
        'm37.ui.desSeed':
            'Персонажи в DES: кто в каждой стартовой сцене, внешность, настроение, одежда, отношение и мысли',
        'm37.ui.again': 'Разобрать заново',
        'm37.ui.discardTitle': 'Забыть план?',
        'm37.ui.discardBody':
            'План этого чата будет забыт. Уже применённое останется — при желании его можно отменить в журнале.',
        'm37.ui.allSection': 'Весь раздел «{section}»',
        'm37.ui.scope': 'Где сохранить',
        'm37.ui.scopeSection': 'Где сохранить раздел «{section}»',
        'm37.ui.scopeMixed': 'по-разному',
        'm37.ui.exists': '{where}: {label}',
        'm37.ui.conflictBadge': 'в каноне иначе',
        'm37.ui.conflict': 'В каноне («{with}») сказано иначе — {field}:',
        'm37.ui.savedItem': 'из сохранённой подготовки',
        'm37.ui.edited': 'изменено',
        'm37.ui.details': 'Подробнее',
        'm37.ui.editHint': 'Тексты канона хранятся по-английски: так модель понимает их лучше.',
        'm37.ui.sources': 'Откуда: {list}',
        'm37.ui.reset': 'Убрать мои правки',
        'm37.ui.sceneAuto': 'решит сам',
        'm37.ui.sceneTitle': 'Сцена {n} · «{opening}»',
        'm37.ui.sceneShown': 'сейчас в чате',
        'm37.ui.sceneOutfits': 'Наряды в начале: {list}',
        'm37.ui.scenesHint':
            'Подготовятся все отмеченные сцены. Действует та, что сейчас в чате: свайп приветствия до твоего первого сообщения переключает её.',
        'm37.ui.result': 'Что сделано',
        'm37.ui.nothingDone': 'Ничего не записано.',
        'm37.ui.skippedLines': 'Пропущено ({count})',
        'm37.ui.undo': 'Отменить',
        'm37.ui.undone': 'отменено',
        'm37.ui.undoFailed': 'Не получилось отменить: {text}',
        'm37.ui.appliedAt': 'Подготовка применена {time}.',
        'm37.ui.toPlan': 'К плану',
        'm37.ui.statusLoading': 'Проверяю, всё ли готово…',
        'm37.ui.open.canon': 'Канон',
        'm37.ui.open.places': 'Места',
        'm37.ui.open.dossier': 'Персонажи',
        'm37.ui.open.knowledge': 'Кто что знает',
        'm37.ui.open.calendar': 'Календарь',
        'm37.ui.open.mechanics': 'Механики',
        'm37.ui.open.wardrobe': 'Гардероб',
        'm37.ui.open.director': 'Режиссёр',
        'm37.ui.open.backgrounds': 'Фоны',
        'm37.ui.fix.plan': 'К плану',
        'm37.ui.fix.passport': 'Сделать паспорт',
        'm37.ui.fix.portrait': 'Открыть досье',
        'm37.ui.fix.place': 'Создать место',
        'm37.ui.fix.background': 'Подобрать фон',

        'm37.fact.persona': 'твой персонаж',
        'm37.fact.present': 'в первой сцене',
        'm37.fact.forms': 'Формы имени: {list}',
        'm37.fact.parent': 'Где: {name}',
        'm37.fact.leader': 'Глава: {name}',
        'm37.fact.owner': 'Владелец: {name}',
        'm37.fact.calendar': 'свой календарь',
        'm37.fact.knownBy': 'Знают: {list}',
        'm37.fact.hiddenFrom': 'Скрыто от: {list}',
        'm37.fact.promise': '{who} → {whom}',
        'm37.fact.due': 'Срок: {due}',
        'm37.fact.date': 'Начало: {date}',
        'm37.fact.place': 'Место: {name}',
        'm37.fact.outfits': 'Наряды: {list}',
        'm37.fact.presentList': 'В сцене: {list}',
        'm37.fact.attributes': 'Показатели: {list}',
        'm37.fact.holders.persona': 'у тебя',
        'm37.fact.holders.characters': 'у персонажей',
        'm37.fact.holders.named': 'у названных',
        'm37.fact.holders.world': 'у мира',
        'm37.fact.holders.factions': 'у фракций',
        'm37.fact.values': 'начальных значений: {count}',
        'm37.fact.firstScene': 'Первая сцена: {type}',

        'm37.edit.name': 'Имя, как в истории',
        'm37.edit.english': 'Имя в каноне (по-английски)',
        'm37.edit.role': 'Роль',
        'm37.edit.appearance': 'Внешность',
        'm37.edit.personality': 'Характер',
        'm37.edit.speech': 'Манера речи',
        'm37.edit.outfit': 'Во что одет в начале',
        'm37.edit.setting': 'Сеттинг',
        'm37.edit.era': 'Эпоха',
        'm37.edit.tone': 'Тон',
        'm37.edit.laws': 'Законы мира',
        'm37.edit.customs': 'Обычаи и запреты',
        'm37.edit.parent': 'Где находится',
        'm37.edit.kind': 'Что это за место',
        'm37.edit.description': 'Описание',
        'm37.edit.state': 'Состояние в начале',
        'm37.edit.leader': 'Глава',
        'm37.edit.goals': 'Цели',
        'm37.edit.owner': 'Владелец',
        'm37.edit.when': 'Когда',
        'm37.edit.practice': 'Как проходит',
        'm37.edit.meaning': 'Что значит',
        'm37.edit.date': 'Дата',
        'm37.edit.time': 'Время суток',
        'm37.edit.calendar': 'Календарь',
        'm37.edit.what': 'Что обещано',
        'm37.edit.due': 'Срок',
        'm37.edit.text': 'Суть секрета',
        'm37.edit.about': 'О ком',
        'm37.edit.place': 'Где',
        'm37.edit.situation': 'Что происходит',
        'm37.edit.summary': 'Кратко',
        'm37.edit.rules': 'Правила',
        'm37.edit.genre': 'Жанр',
        'm37.edit.pacing': 'Темп',
        'm37.edit.firstScene': 'Первая сцена',
        'm37.edit.notes': 'Заметки',
    },
};

/** How the steps of an applied item read in the journal and Inbox cards. */
export const PREPARE_TARGETS: TargetSpec[] = [
    {
        target: PREPARE_STEP_TARGET,
        labelKey: 'm37.target.step',
        fields: {
            what: { labelKey: 'm37.field.what' },
            name: { labelKey: 'm37.field.name' },
            detail: { labelKey: 'm37.field.detail', hidden: true },
        },
    },
];
