// Strings of M22 «Правила» (`m22.*`, action kinds `kind.rules.*`, journal targets `target.m22.*`; 'lore-entry' is
// described by M5). Russian is the primary UI language.
import type { I18nParts } from '../../shared/contracts';

export const RULES_STRINGS: I18nParts = {
    en: {
        'm22.title': 'Rules',
        'm22.tab': 'Rules',
        'm22.owner.maestro': 'Maestro',
        'm22.owner.desru': 'DES-RU',
        'm22.kind.lore': 'lore',
        'm22.kind.prompt': 'prompt',
        'm22.kind.neighbour': 'neighbours',
        'm22.kind.display': 'display',
        'm22.kind.ui': 'interface',
        'm22.meta': '{owner} · stage {stage} · {kind}',
        'm22.section.rules': 'On-the-fly rules',
        'm22.intro':
            'Fixes for the known rough edges of the stack. Lore rules change only the copies of entries in each scan: your lorebook files stay as they are.',
        'm22.firstRun':
            'Lore, prompt and neighbour rules switch on after the first-run wizard. Display and interface fixes already work.',
        'm22.toggle': 'On',
        'm22.toggle.on': 'Switching on the rule «{rule}»',
        'm22.toggle.off': 'Switching off the rule «{rule}»',
        'm22.toggle.done.on': 'Switched on the rule «{rule}».',
        'm22.toggle.done.off': 'Switched off the rule «{rule}».',
        'm22.toggle.loreHint':
            'Switching a lore rule resets sticky and cooldown of the entries it touches (SillyTavern ties them to the entry text).',
        'm22.toggle.notApplied.queued': 'Switching the rule «{rule}» is waiting in the Inbox.',
        'm22.toggle.notApplied.notified': 'Switching the rule «{rule}» waits for «Apply» in the notice.',
        'm22.toggle.notApplied.rejected': 'The rule «{rule}» stays as it was.',
        'm22.toggle.notApplied.skipped': 'The rule «{rule}» was not switched: such changes are off or out of date.',
        'm22.default': 'default',
        'm22.explicit': 'set by you',
        'm22.waiting': 'waits for the first-run wizard',
        'm22.unavailable': 'Unavailable now: {missing}',
        'm22.changes': 'Last scan: {count} changes',
        'm22.changesNone': 'No changes on the last scan',
        'm22.changesMore': '…and {count} more',
        'm22.col.book': 'Book',
        'm22.col.entry': 'Entry',
        'm22.col.field': 'Field',
        'm22.col.before': 'Before',
        'm22.col.after': 'After',
        'm22.col.chars': 'Characters',
        'm22.compare': 'Compare before/after',
        'm22.compare.noJournal': 'The lore journal (M1) is off: the comparison is unavailable.',
        'm22.compare.failed': 'Comparison failed: {error}',
        'm22.compare.result': 'Removed: {removed} · added: {added} · characters: {delta}',
        'm22.compare.same': 'The rule changes no activation in the current chat.',
        'm22.compare.removed': 'Entries that leave the prompt',
        'm22.compare.added': 'Entries that join the prompt',
        'm22.compare.busy': 'A comparison is already running.',
        'm22.gap.limit': 'Return at most this many messages',
        'm22.refresh': 'Refresh',
        'm22.caps.title': 'Book caps',
        'm22.caps.hint':
            'How much of a big book may go into the prompt. Entries above the cap are dropped at every scan step, entries with a higher order stay first. A recursion limit also stops this book’s entries from triggering other entries.',
        'm22.caps.maxTokens': 'Cap, tokens (0 = none)',
        'm22.caps.maxRecursion': 'Recursion limit',
        'm22.caps.noLimit': 'No limit',
        'm22.caps.level0': '0 — direct matches only',
        'm22.caps.level': 'Level {level}',
        'm22.caps.none': 'No active books yet: open a chat with lorebooks or send a message.',
        'm22.caps.heavy': 'about {chars} characters per turn, {count} activations',
        'm22.caps.heaviest': 'Heaviest books in the lore journal: {list}',
        'm22.caps.inactive': 'not active now',
        'm22.caps.cut': 'Cut on the last scan: {count}',
        'm22.caps.ruleOff': 'The «Book cap and recursion limit» rule is off: the limits are kept but not applied.',
        'm22.qvinkExclude.title': 'Leaving picture post #{index} out of Qvink summaries',
        'm22.qvinkExclude.description':
            'This is an NAI picture post: there is nothing to summarise in it, so Qvink skips it.',
        'm22.qvinkExclude.done': 'Left picture post #{index} out of Qvink summaries.',
        'm22.qvinkExclude.doneMany.one': 'Left {count} picture post out of Qvink summaries',
        'm22.qvinkExclude.doneMany.few': 'Left {count} picture posts out of Qvink summaries',
        'm22.qvinkExclude.doneMany.many': 'Left {count} picture posts out of Qvink summaries',
        'm22.task.qvinkSummarize': 'Qvink: summarise messages that left the prompt',
        'kind.rules.toggle': 'Switching rules on and off',
        'kind.rules.qvinkExclude': 'Pictures left out of Qvink summaries',
        'target.m22.rule': 'Rule',
        'target.m22.qvinkExclude': 'Picture in Qvink summaries',
        'target.m22.packChoice': 'Pack version',
        'm22.value.ruleOn': 'on',
        'm22.value.ruleOff': 'off',
        'm22.value.excluded': 'left out',
        'm22.value.summarised': 'summarised',

        'm22.rule.role.assistantToSystem.title': 'Assistant role → system',
        'm22.rule.role.assistantToSystem.description':
            'Lore entries injected at depth with the assistant role (BunnyMo #64, Ozone Filter, Baby Bunny archives) are sent as system. Entries with the user role are not touched.',
        'm22.rule.book.cap.title': 'Book cap and recursion limit',
        'm22.rule.book.cap.description':
            'Your limits per book (see «Book caps»): entries above the token cap or deeper than the recursion limit are dropped at every scan step and switched off in the scan copy so they do not come back.',
        'm22.rule.pack.duplicates.title': 'Byte-identical pack duplicates',
        'm22.rule.pack.duplicates.description':
            'When two active books carry the same entry (same keys and identical text — MBTI v1 and V2, Species merged and split), only the copy from the newest book stays. Versions with different text are not touched here.',
        'm22.rule.qvink.gapGuard.title': 'Qvink: no gaps',
        'm22.rule.qvink.gapGuard.description':
            'Messages Qvink has already removed from the prompt but not summarised yet go back into the prompt (as copies, only the newest ones up to the limit) and are queued for summarising.',
        'm22.rule.qvink.excludeImagePosts.title': 'NAI picture posts in Qvink',
        'm22.rule.qvink.excludeImagePosts.description':
            'NAI Studio picture posts get the «exclude» mark in Qvink, so it does not summarise image prompts.',
        'm22.rule.display.bunnymoTags.title': 'Show BunnyMo tags',
        'm22.rule.display.bunnymoTags.description':
            'Messages show <KEY:VALUE> tags, MBTI and BunnyMo wrappers as text instead of hiding them. Display only: the prompt and real HTML are untouched, and it goes away with Maestro.',
        'm22.rule.ui.ckVectorizeButton.title': 'CarrotKernel vectorize button',
        'm22.rule.ui.ckVectorizeButton.description':
            'CarrotKernel’s «Vectorize Fullsheet» button moves from the top of the message, where it covers the ST and DES buttons, to the bottom, and hides while the message is edited.',
        'm22.rule.ui.desPortraitBarMobile.title': 'DES portrait bar on phones',
        'm22.rule.ui.desPortraitBarMobile.description':
            'On narrow screens the side portrait bar becomes a bottom panel of limited height. Once per page load it is collapsed with DES’s own button, so DES knows its state.',
        'm22.rule.prompt.ckDumpsIgnore.title': 'CarrotKernel dumps in analysis',
        'm22.rule.prompt.ckDumpsIgnore.description':
            'Maestro’s analysis reads messages without CarrotKernel tag dumps, DES tracker JSON, HTML and NAI image placeholders, and skips picture posts. The chat and the prompt do not change.',
        'm22.rule.keys.cyrillicLeftBoundary.title': 'Cyrillic keys and whole words',
        'm22.rule.keys.cyrillicLeftBoundary.description':
            'In SillyTavern “match whole words” does not work for Cyrillic, so “аня” fires inside “Таня”. Cyrillic one-word keys of such entries become regex keys with a word boundary on the left only: case endings keep working (“Иван” finds “Ивану”). Keys with macros and regex keys stay; CK archives are left to DES-RU when it adds case forms.',
        'm22.rule.pack.versionConflict.title': 'Pack version conflicts',
        'm22.rule.pack.versionConflict.description':
            'When BunnyMo books have entries with the same keys but different text (MBTI v1 and V2 “Analysts”), one tag fires both texts. Maestro asks once which book to keep (the newest is offered); after the answer the copies of the other books are switched off in every scan. Until then nothing is suppressed; pack files stay as they are.',
        'm22.rule.wrapper.nsfwCollision.title': '<NSFW> in archives → CarrotCast “Erotic”',
        'm22.rule.wrapper.nsfwCollision.description':
            'Archives wrap text in <NSFW>…</NSFW>, and through recursion this fires CarrotCast Limited’s “Erotic” entry keyed by the bare tag <NSFW>. The rule keeps recursion from firing it; a direct mention in the chat still works.',
        'm22.rule.ck.archiveDepth.title': 'CK archives that fire only on the last message',
        'm22.rule.ck.archiveDepth.description':
            'Baby Bunny saves archives with scan depth 1, so a character fires only when the name is in the very last message. For each of your archive books the Inbox gets one proposal: switch them to the global scan depth and, with DES-RU, add Russian case forms to the name keys. BunnyMo packs are never touched.',
        'm22.packVersion.title': 'Several versions of one BunnyMo pack — keep “{book}”?',
        'm22.packVersion.description':
            '{books}: {count} entries with the same keys but different text, so one tag fires both texts and the model gets two different descriptions.\n\nYes: keep “{book}” (looks newest); the copies from {others} are switched off on the fly, the files do not change.\nNo: keep every version.\n\nYou can change the choice on the “Rules” tab at any time.',
        'm22.packVersion.details': 'For example the tags {sample}',
        'm22.pack.title': 'Pack versions',
        'm22.pack.none': 'No version conflicts in the last scan.',
        'm22.pack.group': '{books}: {count} entries',
        'm22.pack.unanswered': 'not decided yet (both versions work)',
        'm22.pack.keepAll': 'keep every version',
        'm22.pack.keep': 'keep “{book}”',
        'm22.pack.keepNewest': 'keep “{book}” (newest)',
        'm22.archiveDepth.title': 'Character sheets in “{book}” fire only on the last message — fix them?',
        'm22.archiveDepth.description':
            'Characters of this book ({count}) come back only when their name is in the very last message. I will give their character sheets the global scan depth; the book “{book}” is saved right away, and the journal keeps the previous values.',
        'm22.archiveDepth.forms':
            'I will also add every Russian case form of the names (through DES-RU), so other forms of a name are recognised too.',
        'm22.archiveDepth.noForms': 'Name keys stay as they are (DES-RU is not available).',
        'm22.archiveDepth.entries': 'Sheets: {list}',
        'm22.archiveDepth.more': '…and {count} more',
        'm22.archiveDepth.failed.missing': 'The book “{book}” or its entries are gone.',
        'm22.archiveDepth.failed.stale': 'The archives in “{book}” changed after the proposal.',
        'm22.archiveDepth.failed.protected': '“{book}” is a BunnyMo book: its file is never edited.',
        'kind.rules.packVersion': 'Choice of a BunnyMo pack version',
        'kind.rules.ckArchiveDepth': 'Character sheet fixes',
    },
    ru: {
        'm22.title': 'Правила',
        'm22.tab': 'Правила',
        'm22.owner.maestro': 'Maestro',
        'm22.owner.desru': 'DES-RU',
        'm22.kind.lore': 'лор',
        'm22.kind.prompt': 'промпт',
        'm22.kind.neighbour': 'соседи',
        'm22.kind.display': 'показ',
        'm22.kind.ui': 'интерфейс',
        'm22.meta': '{owner} · этап {stage} · {kind}',
        'm22.section.rules': 'Правила на лету',
        'm22.intro':
            'Исправления известных «углов» стека. Правила лора меняют только копии записей при каждом сканировании — файлы лорбуков остаются как есть.',
        'm22.firstRun':
            'Правила лора, промпта и соседей включатся после мастера первого запуска. Исправления показа и интерфейса уже работают.',
        'm22.toggle': 'Включено',
        'm22.toggle.on': 'Включение правила «{rule}»',
        'm22.toggle.off': 'Выключение правила «{rule}»',
        'm22.toggle.done.on': 'Включил правило «{rule}».',
        'm22.toggle.done.off': 'Выключил правило «{rule}».',
        'm22.toggle.loreHint':
            'Включение и выключение правила лора сбрасывает sticky и cooldown затронутых записей (в SillyTavern они привязаны к тексту записи).',
        'm22.toggle.notApplied.queued': 'Переключение правила «{rule}» ждёт во «Входящих».',
        'm22.toggle.notApplied.notified': 'Переключение правила «{rule}» ждёт: нажми «Применить» в уведомлении.',
        'm22.toggle.notApplied.rejected': 'Правило «{rule}» осталось как было.',
        'm22.toggle.notApplied.skipped':
            'Правило «{rule}» не переключилось: такие изменения сейчас выключены или предложение устарело.',
        'm22.default': 'по умолчанию',
        'm22.explicit': 'задано тобой',
        'm22.waiting': 'ждёт мастера первого запуска',
        'm22.unavailable': 'Сейчас недоступно: {missing}',
        'm22.changes': 'Последнее сканирование: правок — {count}',
        'm22.changesNone': 'На последнем сканировании правок не было',
        'm22.changesMore': '…и ещё {count}',
        'm22.col.book': 'Книга',
        'm22.col.entry': 'Запись',
        'm22.col.field': 'Поле',
        'm22.col.before': 'Было',
        'm22.col.after': 'Стало',
        'm22.col.chars': 'Символы',
        'm22.compare': 'Сравнить до/после',
        'm22.compare.noJournal': 'Журнал лора (M1) выключен — сравнение недоступно.',
        'm22.compare.failed': 'Сравнение не удалось: {error}',
        'm22.compare.result': 'Уходит: {removed} · добавляется: {added} · символов: {delta}',
        'm22.compare.same': 'В текущем чате правило не меняет ни одного срабатывания.',
        'm22.compare.removed': 'Записи, которые уходят из промпта',
        'm22.compare.added': 'Записи, которые добавляются в промпт',
        'm22.compare.busy': 'Сравнение уже идёт.',
        'm22.gap.limit': 'Возвращать не больше сообщений',
        'm22.refresh': 'Обновить',
        'm22.caps.title': 'Потолки книг',
        'm22.caps.hint':
            'Сколько большой книги может попасть в промпт. Записи сверх потолка снимаются на каждом шаге сканирования, первыми остаются записи с большим порядком. Лимит рекурсии к тому же запрещает записям книги вызывать другие записи.',
        'm22.caps.maxTokens': 'Потолок, токенов (0 — без потолка)',
        'm22.caps.maxRecursion': 'Лимит рекурсии',
        'm22.caps.noLimit': 'Без лимита',
        'm22.caps.level0': '0 — только прямые совпадения',
        'm22.caps.level': 'Уровень {level}',
        'm22.caps.none': 'Активных книг пока нет — открой чат с лорбуками или отправь сообщение.',
        'm22.caps.heavy': 'в среднем {chars} симв. за ход, срабатываний: {count}',
        'm22.caps.heaviest': 'Самые тяжёлые книги по журналу лора: {list}',
        'm22.caps.inactive': 'сейчас не активна',
        'm22.caps.cut': 'Снято на последнем сканировании: {count}',
        'm22.caps.ruleOff':
            'Правило «Потолок книги и лимит рекурсии» выключено: ограничения сохранены, но не применяются.',
        'm22.qvinkExclude.title': 'Исключение картинки №{index} из пересказов Qvink',
        'm22.qvinkExclude.description':
            'Это пост с картинкой NAI: пересказывать в нём нечего, поэтому Qvink его пропустит.',
        'm22.qvinkExclude.done': 'Убрал картинку №{index} из пересказов Qvink.',
        'm22.qvinkExclude.doneMany.one': 'Убрал из пересказов Qvink {count} картинку',
        'm22.qvinkExclude.doneMany.few': 'Убрал из пересказов Qvink {count} картинки',
        'm22.qvinkExclude.doneMany.many': 'Убрал из пересказов Qvink {count} картинок',
        'm22.task.qvinkSummarize': 'Qvink: пересказать сообщения, выпавшие из промпта',
        'kind.rules.toggle': 'Включение и выключение правил',
        'kind.rules.qvinkExclude': 'Картинки без пересказа в Qvink',
        'target.m22.rule': 'Правило',
        'target.m22.qvinkExclude': 'Картинка в пересказах Qvink',
        'target.m22.packChoice': 'Версия пака',
        'm22.value.ruleOn': 'включено',
        'm22.value.ruleOff': 'выключено',
        'm22.value.excluded': 'не пересказывается',
        'm22.value.summarised': 'пересказывается',

        'm22.rule.role.assistantToSystem.title': 'Роль assistant → system',
        'm22.rule.role.assistantToSystem.description':
            'Записи лора на глубине с ролью assistant (BunnyMo #64, Ozone Filter, архивы Baby Bunny) уходят в промпт с ролью system. Записи с ролью user не трогаются.',
        'm22.rule.book.cap.title': 'Потолок книги и лимит рекурсии',
        'm22.rule.book.cap.description':
            'Твои ограничения для книг (раздел «Потолки книг»): записи сверх потолка токенов или глубже лимита рекурсии снимаются на каждом шаге сканирования и выключаются в копии, чтобы не вернуться.',
        'm22.rule.pack.duplicates.title': 'Побайтные дубли паков',
        'm22.rule.pack.duplicates.description':
            'Если две активные книги содержат одну и ту же запись (те же ключи и тот же текст — MBTI v1 и V2, Species целиком и по частям), остаётся копия из самой новой книги. Версии с разным текстом здесь не трогаются.',
        'm22.rule.qvink.gapGuard.title': '«Дыры» Qvink',
        'm22.rule.qvink.gapGuard.description':
            'Сообщения, которые Qvink уже убрал из промпта, но ещё не пересказал, возвращаются в промпт (копиями, только самые новые в пределах лимита) и ставятся в очередь пересказа.',
        'm22.rule.qvink.excludeImagePosts.title': 'Посты-картинки NAI в Qvink',
        'm22.rule.qvink.excludeImagePosts.description':
            'Посты-картинки NAI Studio получают в Qvink отметку «исключить», чтобы он не пересказывал промпты картинок.',
        'm22.rule.display.bunnymoTags.title': 'Показ тегов BunnyMo',
        'm22.rule.display.bunnymoTags.description':
            'Сообщения показывают теги <KEY:VALUE>, MBTI и обёртки BunnyMo текстом, а не прячут их. Только показ: промпт и настоящий HTML не меняются, правило исчезает вместе с Maestro.',
        'm22.rule.ui.ckVectorizeButton.title': 'Кнопка векторизации CarrotKernel',
        'm22.rule.ui.ckVectorizeButton.description':
            'Кнопка CarrotKernel «Vectorize Fullsheet» переезжает с верха сообщения, где закрывает кнопки ST и DES, вниз и прячется, пока сообщение редактируется.',
        'm22.rule.ui.desPortraitBarMobile.title': 'Полоса портретов DES на телефоне',
        'm22.rule.ui.desPortraitBarMobile.description':
            'На узком экране боковая полоса портретов становится нижней панелью ограниченной высоты. При загрузке страницы она один раз сворачивается кнопкой самого DES, чтобы DES знал о состоянии.',
        'm22.rule.prompt.ckDumpsIgnore.title': 'Дампы CarrotKernel в анализе',
        'm22.rule.prompt.ckDumpsIgnore.description':
            'Анализ Maestro читает сообщения без дампов тегов CarrotKernel, JSON трекера DES, HTML и плейсхолдеров картинок NAI, а посты-картинки пропускает. Чат и промпт не меняются.',
        'm22.rule.keys.cyrillicLeftBoundary.title': 'Кириллица и «целые слова»',
        'm22.rule.keys.cyrillicLeftBoundary.description':
            'В SillyTavern «только целые слова» не работает для кириллицы, и «аня» срабатывает внутри «Таня». Кириллические ключи из одного слова у таких записей становятся регулярками с границей слова только слева: падежи продолжают работать («Иван» находит «Ивану»). Ключи с макросами и регулярки не трогаются; архивы CK остаются DES-RU, когда он добавляет падежи.',
        'm22.rule.pack.versionConflict.title': 'Конфликт версий паков',
        'm22.rule.pack.versionConflict.description':
            'Если в книгах BunnyMo есть записи с одинаковыми ключами и разным текстом (MBTI v1 и V2, «Аналитики»), на один тег срабатывают оба текста. Maestro один раз спрашивает, какую книгу оставить (предлагает самую новую), и после ответа выключает копии из остальных книг при каждом сканировании. До ответа ничего не подавляется; файлы паков не меняются.',
        'm22.rule.wrapper.nsfwCollision.title': '<NSFW> в архивах → «Erotic» из CarrotCast',
        'm22.rule.wrapper.nsfwCollision.description':
            'Архивы оборачивают текст в <NSFW>…</NSFW>, а через рекурсию это включает запись «Erotic» из CarrotCast Limited с голым ключом <NSFW>. Правило не даёт рекурсии её включать; прямое упоминание в чате по-прежнему работает.',
        'm22.rule.ck.archiveDepth.title': 'Архивы CK по последнему сообщению',
        'm22.rule.ck.archiveDepth.description':
            'Baby Bunny сохраняет архивы с глубиной сканирования 1 — персонаж срабатывает, только если имя есть в самом последнем сообщении. Для каждой твоей книги архивов во «Входящие» приходит одно предложение: перевести их на общую глубину сканирования, а с DES-RU — ещё и добавить ключам имён русские падежи. Паки BunnyMo не трогаются никогда.',
        'm22.packVersion.title': 'Несколько версий одного пака BunnyMo — оставить «{book}»?',
        'm22.packVersion.description':
            '{books}: записей с одинаковыми ключами, но разным текстом — {count}. На один тег срабатывают оба текста, и модель получает два разных описания.\n\nДа — оставить «{book}» (похоже, самую новую): копии из {others} выключаются на лету, файлы не меняются.\nНет — оставить все версии.\n\nВыбор можно поменять в любой момент во вкладке «Правила».',
        'm22.packVersion.details': 'Например, теги {sample}',
        'm22.pack.title': 'Версии паков',
        'm22.pack.none': 'На последнем сканировании конфликтов версий не было.',
        'm22.pack.group': '{books}: записей — {count}',
        'm22.pack.unanswered': 'ещё не решено (работают обе версии)',
        'm22.pack.keepAll': 'оставить все версии',
        'm22.pack.keep': 'оставить «{book}»',
        'm22.pack.keepNewest': 'оставить «{book}» (новее)',
        'm22.archiveDepth.title': 'Листы характера в «{book}» срабатывают только по последнему сообщению — исправить?',
        'm22.archiveDepth.description':
            'Персонажи из этой книги ({count}) вспоминаются, только если имя прозвучало в самом последнем сообщении. Поставлю их листам характера общую глубину сканирования; книга «{book}» сохранится сразу, прежние значения останутся в журнале.',
        'm22.archiveDepth.forms':
            'Заодно добавлю к именам все падежи (через DES-RU), чтобы персонажей узнавали и в других формах имени.',
        'm22.archiveDepth.noForms': 'Ключи имён останутся как есть (DES-RU недоступен).',
        'm22.archiveDepth.entries': 'Листы: {list}',
        'm22.archiveDepth.more': '…и ещё {count}',
        'm22.archiveDepth.failed.missing': 'Книги «{book}» или её записей больше нет.',
        'm22.archiveDepth.failed.stale': 'Архивы в «{book}» изменились после предложения.',
        'm22.archiveDepth.failed.protected': '«{book}» — книга BunnyMo, её файл не правится.',
        'kind.rules.packVersion': 'Выбор версии пака BunnyMo',
        'kind.rules.ckArchiveDepth': 'Исправление листов характера',
    },
};
