import type { I18nParts } from '../../shared/contracts';

export const M2_STRINGS: I18nParts = {
    en: {
        'm2.title': 'Turn inspector',
        'm2.tab': 'Turn prompt',
        'm2.noChat': 'Open a chat to see what its prompt is made of.',
        'm2.ccOnly': 'The inspector takes the prompt apart in Chat Completion mode only.',

        'm2.turn.title': 'Last turn',
        'm2.turn.pick': 'Turn',
        'm2.turn.option': 'Message #{index} · {type} · {time}',
        'm2.turn.empty':
            'No turns yet. Send a message: after the reply the inspector shows what the prompt was made of.',
        'm2.turn.summary': 'Messages in the prompt: {messages} · ~{tokens} tokens',
        'm2.turn.exact': 'Counts by the Prompt Manager.',
        'm2.turn.estimate': 'Estimated by Maestro (no Prompt Manager counts).',
        'm2.turn.chars': 'Chars: system {system} · user {user} · assistant {assistant}',
        'm2.turn.loreNoBooks': 'The lore journal is off, so lore is not split by book.',
        'm2.turn.reconstructed':
            'Weights are reconstructed: ST merges injections of one depth and role into a single message.',

        'm2.col.source': 'Source',
        'm2.col.tokens': 'Tokens',
        'm2.col.share': 'Share',
        'm2.col.prev': 'vs last turn',
        'm2.col.avg': 'vs chat average',

        'm2.group.preset': 'Preset',
        'm2.group.card': 'Card and persona',
        'm2.group.lore': 'Lore',
        'm2.group.history': 'Chat history',
        'm2.owner.des': 'DES',
        'm2.owner.ck': 'CarrotKernel',
        'm2.owner.qvink': 'Qvink memory',
        'm2.owner.nai': 'NAI Studio',
        'm2.owner.desru': 'DES-RU',
        'm2.owner.maestro': 'Maestro',
        'm2.owner.wiOutlet': 'WI outlets',
        'm2.owner.wiDepth': 'WI at depth',
        'm2.owner.summary': 'Summary',
        'm2.owner.authorsNote': 'Author’s Note',
        'm2.owner.card': 'Card',
        'm2.owner.other': 'Other insertions',

        'm2.src.lore': 'Lore: {book}',
        'm2.src.loreAll': 'Lore (all books)',
        'm2.src.history': 'Chat history',
        'm2.src.wiFormat': 'Lore wrapper',
        'm2.card.charDescription': 'Character description',
        'm2.card.charPersonality': 'Character personality',
        'm2.card.scenario': 'Scenario',
        'm2.card.personaDescription': 'Persona',
        'm2.card.dialogueExamples': 'Dialogue examples',
        'm2.card.depthPrompt': 'Character’s note at depth',

        'm2.repeats.title': 'Repeated facts',
        'm2.repeats.hint': 'Identical sentences of 60+ chars found in two or more sources: the model reads them twice.',
        'm2.repeats.none': 'No repeats found.',
        'm2.repeats.unavailable': 'Available for the last turn of this session (texts are not stored).',
        'm2.repeats.in': 'in: {sources}',

        'm2.export.title': 'Export for debugging',
        'm2.export.redact': 'Hide chat text (user and character messages)',
        'm2.export.hint': 'No keys or connection settings are exported; key-like strings are masked.',
        'm2.export.download': 'Download JSON',
        'm2.export.copy': 'Copy JSON',
        'm2.export.copied': 'Copied.',
        'm2.export.noPrompt':
            'The prompt text is kept only for the last turn of this session; the export has weights only.',

        'm2.settings.title': 'Inspector settings',
        'm2.settings.keepTurns': 'Turns to keep per chat',
    },
    ru: {
        'm2.title': 'Инспектор хода',
        'm2.tab': 'Промпт хода',
        'm2.noChat': 'Откройте чат — здесь будет видно, из чего собран его промпт.',
        'm2.ccOnly': 'Инспектор разбирает промпт только в режиме Chat Completion.',

        'm2.turn.title': 'Последний ход',
        'm2.turn.pick': 'Ход',
        'm2.turn.option': 'Сообщение №{index} · {type} · {time}',
        'm2.turn.empty': 'Ходов пока нет. Отправьте сообщение — после ответа здесь будет видно, из чего собран промпт.',
        'm2.turn.summary': 'Сообщений в промпте: {messages} · ~{tokens} токенов',
        'm2.turn.exact': 'Счёт Prompt Manager.',
        'm2.turn.estimate': 'Оценка Maestro (счётчиков Prompt Manager нет).',
        'm2.turn.chars': 'Символов: system {system} · user {user} · assistant {assistant}',
        'm2.turn.loreNoBooks': 'Журнал лора выключен, поэтому лор не разбит по книгам.',
        'm2.turn.reconstructed':
            'Веса восстановлены по частям: ST склеивает вставки одной глубины и роли в одно сообщение.',

        'm2.col.source': 'Источник',
        'm2.col.tokens': 'Токены',
        'm2.col.share': 'Доля',
        'm2.col.prev': 'к прошлому ходу',
        'm2.col.avg': 'к среднему по чату',

        'm2.group.preset': 'Пресет',
        'm2.group.card': 'Карточка и персона',
        'm2.group.lore': 'Лор',
        'm2.group.history': 'История чата',
        'm2.owner.des': 'DES',
        'm2.owner.ck': 'CarrotKernel',
        'm2.owner.qvink': 'Память Qvink',
        'm2.owner.nai': 'NAI Studio',
        'm2.owner.desru': 'DES-RU',
        'm2.owner.maestro': 'Maestro',
        'm2.owner.wiOutlet': 'Аутлеты лора',
        'm2.owner.wiDepth': 'Лор на глубине',
        'm2.owner.summary': 'Пересказ',
        'm2.owner.authorsNote': 'Заметка автора',
        'm2.owner.card': 'Карточка',
        'm2.owner.other': 'Прочие вставки',

        'm2.src.lore': 'Лор: {book}',
        'm2.src.loreAll': 'Лор (все книги)',
        'm2.src.history': 'История чата',
        'm2.src.wiFormat': 'Обёртка лора',
        'm2.card.charDescription': 'Описание персонажа',
        'm2.card.charPersonality': 'Характер персонажа',
        'm2.card.scenario': 'Сценарий',
        'm2.card.personaDescription': 'Персона',
        'm2.card.dialogueExamples': 'Примеры диалогов',
        'm2.card.depthPrompt': 'Заметка персонажа на глубине',

        'm2.repeats.title': 'Повторы фактов',
        'm2.repeats.hint':
            'Одинаковые фразы от 60 символов, найденные в двух и более источниках: модель читает их дважды.',
        'm2.repeats.none': 'Повторов не найдено.',
        'm2.repeats.unavailable': 'Доступно для последнего хода этой сессии (тексты не сохраняются).',
        'm2.repeats.in': 'где: {sources}',

        'm2.export.title': 'Экспорт для отладки',
        'm2.export.redact': 'Скрыть текст чата (сообщения игрока и персонажа)',
        'm2.export.hint': 'Ключи и настройки подключения не выгружаются; строки, похожие на ключи, маскируются.',
        'm2.export.download': 'Скачать JSON',
        'm2.export.copy': 'Скопировать JSON',
        'm2.export.copied': 'Скопировано.',
        'm2.export.noPrompt':
            'Текст промпта хранится только для последнего хода этой сессии; в экспорте будут только веса.',

        'm2.settings.title': 'Настройки инспектора',
        'm2.settings.keepTurns': 'Сколько ходов хранить в чате',
    },
};
