// Strings of M27 «Гардероб и состояния» (`m27.*`, plus the `kind.wardrobe.*` / `target.wardrobe.*` labels). Russian is
// the primary UI language; the user is addressed as «ты» (male). State names are nouns so they read the same for any
// character; phrases with a verb about a character come as `.f` / `.m` / `.n` (domain/name-gender.ts: the neutral form
// when the name does not tell). Cards speak of clothes and pictures, not of passports and slots: NAI tags, field names
// and ids go to «Подробнее».
import type { I18nParts } from '../../shared/contracts';

export const WARDROBE_STRINGS: I18nParts = {
    en: {
        'm27.title': 'Wardrobe and states',
        'm27.tab': 'Wardrobe',
        'kind.wardrobe.outfit': 'Outfit changes',
        'kind.wardrobe.state': 'States of characters',
        'kind.wardrobe.placeState': 'States of places',
        'kind.wardrobe.desField': 'Clothing field in the DES tracker',
        'kind.wardrobe.wear': 'Outfits chosen by hand',
        'target.wardrobe.passport': 'Look in this chat',
        'target.wardrobe.desField': 'DES tracker field',
        'm27.field.outfit': 'Outfit',
        'm27.field.newOutfit': 'New outfit',
        'm27.field.copied': 'A look of their own in this chat',
        'm27.field.state': 'State',
        'm27.field.technical': 'Technical data',
        'm27.value.own': 'own clothes',
        'm27.field.desField': 'Field',
        'm27.hint':
            'The wardrobe follows who wears what, so pictures draw the clothes the same way every time. New clothes that hold for two turns become an outfit, and a known outfit is recognised when it comes back. Wet clothes, wounds, tiredness and the like are noted on the character; ruins, fire, night or rain on the place. Only this chat changes — the card stays as it is.',
        'm27.noChat': 'No chat is open.',
        'm27.group': 'Maestro sleeps in group chats.',
        'm27.noNai':
            'Pictures cannot get the clothes without NAI Studio 0.10 or newer. Below is the outfit library Maestro remembers.',
        'm27.notLeader':
            'Another Maestro tab follows the story right now; here you can still put an outfit on and undo changes.',

        'm27.section.present': 'In the scene',
        'm27.section.all': 'Characters with a look for pictures',
        'm27.empty.characters': 'No character of this chat has a look for pictures (a NAI Studio passport) yet.',
        'm27.wearing': 'Wearing: {outfit}',
        'm27.clothing': 'own clothes (from the card)',
        'm27.outfits': 'Outfits ({count})',
        'm27.outfits.empty': 'No named outfits yet.',
        'm27.wear': 'Put on',
        'm27.wear.hint': 'Make this the active outfit in this chat (the card is not changed).',
        'm27.wear.clothing': 'Own clothes',
        'm27.wear.clothing.hint': 'Back to the character’s usual clothes in this chat.',
        'm27.active': 'worn',
        'm27.seenAs': 'Recognised from: {text}',
        'm27.states': 'States: {list}',
        'm27.states.none': 'No states on.',
        'm27.recent': 'Recent changes',
        'm27.recent.none': 'No changes yet.',
        'm27.change.created': 'New outfit «{name}»',
        'm27.change.worn': 'Put on «{name}»',
        'm27.change.clothing': 'Back to own clothes',
        'm27.change.on': 'Now: {state}',
        'm27.change.off': 'Over: {state}',
        'm27.change.message': 'message #{index}',
        'm27.change.byHand': 'by hand',
        'm27.change.revision': 'from the revision',
        'm27.undo': 'Undo',
        'm27.undo.hint': 'Puts back what was there before this change.',
        'm27.undo.failed': 'Could not undo the change.',
        'm27.undone': 'undone',

        'm27.place.title': 'Place',
        'm27.place.none': 'The current place is not known yet.',
        'm27.place.noPassport':
            'This place has no look for pictures (a NAI Studio location passport), so its states have nowhere to go.',
        'm27.place.passport': 'Drawn as: {name}',
        'm27.place.states': 'States: {list}',

        'm27.settings.title': 'What the wardrobe follows',
        'm27.settings.hint':
            'Untick something and the wardrobe stops following it. Whether a change happens at once, waits in the Inbox or asks first is set in Settings → «Autonomy levels».',
        'm27.settings.outfits': 'Outfits (from the DES tracker and the revision)',
        'm27.settings.states': 'Character states',
        'm27.settings.places': 'Place states',
        'm27.settings.promptLine': 'A line «who wears what» in the prompt',
        'm27.settings.promptLine.hint':
            'Near the end of the prompt: only the characters of the scene and you, about 30–80 tokens. It helps the model keep clothes consistent.',
        'm27.settings.promptDepth': 'Depth in the chat',
        'm27.settings.redrawPortrait': 'Redraw the DES portrait when the outfit changes',
        'm27.settings.persona': 'Follow what your character wears (background model)',
        'm27.settings.personaEvery': 'At most every N turns',

        'm27.card.wear.f': '{name} changed clothes: «{outfit}»',
        'm27.card.wear.m': '{name} changed clothes: «{outfit}»',
        'm27.card.wear.n': '{name} changed clothes: «{outfit}»',
        'm27.card.wear.body': 'Now: {text}. That is the known outfit «{outfit}» — put it on in this chat?',
        'm27.card.create.body':
            'Now: {text}. Remember this as a new outfit «{outfit}»? Then pictures in this chat draw it the same way every time, and I recognise it when it comes back.',
        'm27.card.created.f': '{name} changed clothes: «{outfit}» (a new outfit)',
        'm27.card.created.m': '{name} changed clothes: «{outfit}» (a new outfit)',
        'm27.card.created.n': '{name} changed clothes: «{outfit}» (a new outfit)',
        'm27.card.clothing': '{name} is in their own clothes again',
        'm27.card.clothing.body': 'Now: {text}. Put the character’s usual clothes back on in this chat?',
        'm27.card.undress.naked': '{name} has no clothes on',
        'm27.card.undress.towel': '{name} is in a towel',
        'm27.card.undress.underwear': '{name} is in underwear',
        'm27.card.undress.partial': '{name} is partly undressed',
        'm27.card.undress.body': 'Now: {text}. Until {name} dresses again, pictures in this chat draw it so.',
        'm27.card.copy': '{name}: a look of their own in this chat',
        'm27.card.copy.body':
            'The look of «{name}» is written only in the lore. Copy it into this chat, so outfits can be remembered here? The lore stays as it is.',
        'm27.card.copy.done': 'Copied the look of «{name}» into this chat: outfits are remembered here now.',
        'm27.card.stateOn': '{name}: {state}',
        'm27.card.stateOff': '{name}: {state} — no longer',
        'm27.card.stateOn.body': 'That is how it is in the story now. Pictures in this chat show it while it lasts.',
        'm27.card.stateOff.body': 'The story no longer says so. Pictures in this chat stop showing it.',
        'm27.card.placeOn.body': 'That is how the place is in the story now. Its pictures show it while it lasts.',
        'm27.card.placeOff.body': 'The story no longer says so. Pictures of the place stop showing it.',
        'm27.card.stateOn.done': 'Noted: {name} — {state}',
        'm27.card.stateOff.done': 'Over: {name} — {state}',
        'm27.card.details.tags': 'Tags for pictures: {tags}',
        'm27.card.details.copy': 'NAI Studio passport of the lore entry, copied into the chat passport {id}',
        'm27.done.outfits.one': '{count} character changed clothes',
        'm27.done.outfits.few': '{count} characters changed clothes',
        'm27.done.outfits.many': '{count} characters changed clothes',
        'm27.done.states.one': 'Noted {count} change in how characters and places look',
        'm27.done.states.few': 'Noted {count} changes in how characters and places look',
        'm27.done.states.many': 'Noted {count} changes in how characters and places look',
        'm27.journal.wear': '{name}: outfit «{outfit}», chosen by hand',
        'm27.journal.wearOwn': '{name}: own clothes again, chosen by hand',

        'm27.error.noNai': 'NAI Studio 0.10 or newer is needed for this.',
        'm27.error.gone': 'This character has no look in this chat any more.',
        'm27.error.noOutfit': 'There is no outfit «{name}».',
        'm27.error.noChat': 'No chat is open.',
        'm27.error.noPassport': 'This character has no look for pictures in this chat.',
        'm27.error.noGarment': 'No garment is recognised in what they wear now.',

        'm27.now.title': 'Who is in the scene and what they wear',
        'm27.now.empty': 'The tracker has not said what anyone wears yet.',
        'm27.now.outfit': 'Outfit: «{name}»',
        'm27.now.own': 'Own clothes',
        'm27.now.new': 'New — remembered if it stays one more turn',
        'm27.now.queued': 'Waiting for your decision: «{name}»',
        'm27.now.noPassport': 'No look for pictures: only remembered',
        'm27.now.since': 'since message #{index}',
        'm27.now.away': 'not in the scene',
        'm27.now.you': 'you',
        'm27.now.fromField': 'from the clothing field',
        'm27.now.fromAppearance': 'from the appearance',
        'm27.now.other': 'Put on another',
        'm27.now.other.hint': 'Choose which outfit this clothing really is: Maestro remembers it.',
        'm27.now.other.pick': 'Outfit',
        'm27.now.markNew': 'This is a new outfit',
        'm27.now.markNew.hint': 'Remember what is worn now as a new outfit and put it on.',
        'm27.now.created': 'Remembered as «{name}».',
        'm27.undress.naked': 'no clothes',
        'm27.undress.towel': 'in a towel',
        'm27.undress.underwear': 'in underwear',
        'm27.undress.partial': 'partly undressed',

        'm27.persona.title': 'What you wear now',
        'm27.persona.placeholder': 'e.g. a grey travel cloak and boots',
        'm27.persona.save': 'Remember',
        'm27.persona.saved': 'Remembered what you wear.',
        'm27.persona.empty': 'Write what your character wears.',
        'm27.persona.hint':
            'Maestro also reads it from your messages («I change into my pyjamas») and, when the text does not say, asks the background model.',

        'kind.wardrobe.wearNow': 'Changes of clothes («Change now», from messages)',
        'target.wardrobe.current': 'What they wear now',
        'target.wardrobe.desTracker': 'Clothes in the DES tracker',
        'm27.field.wearing': 'Wears',
        'm27.field.desWording': 'In the DES tracker',
        'm27.journal.wearNow': '{name} → {outfit}',
        'm27.wearNow': 'Change now',
        'm27.wearNow.own': 'Own clothes now',
        'm27.wearNow.hint':
            'Put it on everywhere at once: what everyone wears now, the look for pictures, the DES tracker and portrait, the line for the model.',
        'm27.quick.group': 'Change clothes',
        'm27.quick.me': 'Me ({name})',
        'm27.quick.describe': 'Describe…',
        'm27.quick.describe.short': 'in your own words',
        'm27.quick.describe.title': 'What does {name} wear now?',
        'm27.quick.describe.hint': 'Garments, shoes, jewellery: «a house dress and slippers».',
        'm27.quick.open': 'Open the wardrobe',
        'm27.quick.done': '{name} → {outfit}',
        'm27.strip.text': '{name} → {outfit}',
        'm27.strip.undo': 'Undo',
        'm27.strip.other': 'Other…',
        'm27.slash.help': 'Change clothes now: /maestro-wear <who> <outfit or description>. «me» is your character.',
        'm27.slash.value': 'who, then an outfit or the clothes in words',
        'm27.slash.who': 'Whom to change? Start with a name or «me».',
        'm27.slash.what': 'Into what? Add an outfit name or describe the clothes.',
        'm27.slash.nothing': 'Nothing changed.',
        'm27.settings.triggers': 'Changes of clothes from messages',
        'm27.settings.triggers.hint':
            'Write «I change into my pyjamas» and the reply is already written in them; what the narration says counts too. What the text does not tell, the background model reads after the reply (not in economy mode).',
        'm27.settings.desWrite': 'Write the clothes into the DES tracker',
        'm27.settings.desWrite.hint':
            'Into the character’s clothing field, or into the appearance when the clothes are written there.',
        'm27.settings.composer': '«Change clothes» at the Maestro button at the message box',
        'm27.settings.personaEvery.hint':
            'The check every N turns works only while «Changes of clothes from messages» is off.',
        'm27.change.profileTask': 'Wardrobe: changes of clothes',

        'm27.desField.missing':
            'Nobody asks the model what everyone wears, so I guess clothes from the description of their appearance and can miss a change. Let DES ask about clothes separately every reply? Only the field «{name}» is added to its tracker; you can undo it in the journal.',
        'm27.desField.add': 'Add the field',
        'm27.desField.added': 'DES now asks what everyone wears: I added the field «{name}».',
        'm27.desField.workshop': 'Close the DES Workshop first: when it saves, it overwrites the tracker settings.',
        'm27.desField.failed': 'Could not add the field: the DES settings are not available.',
        'm27.desField.proposal': 'Ask the model what everyone wears',
        'm27.desField.body':
            'DES will ask the model every reply what each character wears, in a separate field «{name}». I recognise outfits by it more surely, and pictures draw them the same way. Nothing else in DES changes.',
        'm27.desField.details': 'DES tracker: new character field «{name}» (id {id})',
        'm27.desField.notice':
            'I guess clothes from the description of appearance. Let DES ask the model about clothes separately?',
        'm27.health.desField': 'Wardrobe: does DES ask about clothes',
        'm27.health.desField.ok': 'DES asks what everyone wears.',
        'm27.health.desField.missing': 'DES does not ask about clothes: outfits are guessed from the appearance.',

        'm27.dropped.title': 'Not taken from the revision',
        'm27.dropped.unknown': '{name}: «{text}» — nobody of this chat has that name.',
        'm27.dropped.noGarment': '{name}: «{text}» — no garment is recognised.',
        'm27.dropped.removal': '{name}: «{text}» — it says what was taken off, not what is worn.',
        'm27.dropped.noPassport': '{name}: «{text}» — this character has no look for pictures.',

        'm27.state.wet': 'wet',
        'm27.state.injured': 'wounds',
        'm27.state.bloody': 'blood',
        'm27.state.tired': 'tiredness',
        'm27.state.dirty': 'dirt',
        'm27.state.sweaty': 'sweat',
        'm27.state.drunk': 'drunkenness',
        'm27.state.messy': 'dishevelled',
        'm27.state.tears': 'tears',
        'm27.state.sick': 'sickness',
        'm27.state.cold': 'shivering',
        'm27.state.bound': 'bonds',
        'm27.state.ruined': 'ruins',
        'm27.state.decorated': 'decorations',
        'm27.state.abandoned': 'neglect',
        'm27.state.burning': 'fire',
        'm27.state.night': 'night',
        'm27.state.evening': 'evening',
        'm27.state.dawn': 'morning',
        'm27.state.rain': 'rain',
        'm27.state.snow': 'snow',
        'm27.state.fog': 'fog',
        'm27.state.storm': 'storm',
        'm27.state.winter': 'winter',
        'm27.state.spring': 'spring',
        'm27.state.summer': 'summer',
        'm27.state.autumn': 'autumn',
    },
    ru: {
        'm27.title': 'Гардероб и состояния',
        'm27.tab': 'Гардероб',
        'kind.wardrobe.outfit': 'Смена нарядов',
        'kind.wardrobe.state': 'Состояния персонажей',
        'kind.wardrobe.placeState': 'Состояния мест',
        'kind.wardrobe.desField': 'Поле «Одежда» в трекере DES',
        'kind.wardrobe.wear': 'Наряды, выбранные вручную',
        'target.wardrobe.passport': 'Внешность в этом чате',
        'target.wardrobe.desField': 'Поле трекера DES',
        'm27.field.outfit': 'Наряд',
        'm27.field.newOutfit': 'Новый наряд',
        'm27.field.copied': 'Своя внешность в этом чате',
        'm27.field.state': 'Состояние',
        'm27.field.technical': 'Служебные данные',
        'm27.value.own': 'своя одежда',
        'm27.field.desField': 'Поле',
        'm27.hint':
            'Гардероб следит, кто во что одет, чтобы картинки рисовали одежду каждый раз одинаково. Новая одежда, которая держится два хода, становится нарядом, а знакомый наряд узнаётся, когда возвращается. Мокрая одежда, раны, усталость и подобное отмечаются у персонажа; руины, пожар, ночь или дождь — у места. Меняется только этот чат, карточка остаётся как есть.',
        'm27.noChat': 'Чат не открыт.',
        'm27.group': 'В групповых чатах Maestro спит.',
        'm27.noNai':
            'Без NAI Studio 0.10 или новее картинки не узнают про одежду. Ниже — библиотека нарядов, которую помнит Maestro.',
        'm27.notLeader':
            'За историей сейчас следит другая вкладка Maestro; надеть наряд и отменить изменения можно и здесь.',

        'm27.section.present': 'В сцене',
        'm27.section.all': 'Персонажи с внешностью для картинок',
        'm27.empty.characters':
            'Ни у одного персонажа этого чата пока нет внешности для картинок (паспорта NAI Studio).',
        'm27.wearing': 'Сейчас: {outfit}',
        'm27.clothing': 'своя одежда (из карточки)',
        'm27.outfits': 'Наряды ({count})',
        'm27.outfits.empty': 'Именованных нарядов пока нет.',
        'm27.wear': 'Надеть',
        'm27.wear.hint': 'Сделать этот наряд активным в этом чате (карточка не меняется).',
        'm27.wear.clothing': 'Своя одежда',
        'm27.wear.clothing.hint': 'Вернуть в этом чате обычную одежду персонажа.',
        'm27.active': 'надет',
        'm27.seenAs': 'Узнаётся по: {text}',
        'm27.states': 'Состояния: {list}',
        'm27.states.none': 'Состояния не включены.',
        'm27.recent': 'Последние изменения',
        'm27.recent.none': 'Изменений пока нет.',
        'm27.change.created': 'Новый наряд «{name}»',
        'm27.change.worn': 'Надет наряд «{name}»',
        'm27.change.clothing': 'Снова своя одежда',
        'm27.change.on': 'Отмечено: {state}',
        'm27.change.off': 'Прошло: {state}',
        'm27.change.message': 'сообщение №{index}',
        'm27.change.byHand': 'вручную',
        'm27.change.revision': 'по ревизии',
        'm27.undo': 'Отменить',
        'm27.undo.hint': 'Вернуть то, что было до этого изменения.',
        'm27.undo.failed': 'Отменить изменение не удалось.',
        'm27.undone': 'отменено',

        'm27.place.title': 'Место',
        'm27.place.none': 'Текущее место пока не известно.',
        'm27.place.noPassport':
            'У этого места нет внешности для картинок (паспорта локации NAI Studio), поэтому его состояния некуда записать.',
        'm27.place.passport': 'Рисуется как: {name}',
        'm27.place.states': 'Состояния: {list}',

        'm27.settings.title': 'За чем следит гардероб',
        'm27.settings.hint':
            'Сними галочку — и гардероб перестанет за этим следить. Меняется ли всё сразу, ждёт во «Входящих» или сначала спрашивает — задаётся в настройках, в «Уровнях автономии».',
        'm27.settings.outfits': 'Наряды (из трекера DES и ревизии)',
        'm27.settings.states': 'Состояния персонажей',
        'm27.settings.places': 'Состояния мест',
        'm27.settings.promptLine': 'Строка «кто во что одет» в промпте',
        'm27.settings.promptLine.hint':
            'Ближе к концу промпта: только персонажи сцены и ты, примерно 30–80 токенов. Помогает модели не путать одежду.',
        'm27.settings.promptDepth': 'Глубина в чате',
        'm27.settings.redrawPortrait': 'Перерисовывать портрет DES при смене наряда',
        'm27.settings.persona': 'Следить, во что одет твой персонаж (фоновая модель)',
        'm27.settings.personaEvery': 'Не чаще чем раз в N ходов',

        'm27.card.wear.f': '{name} переоделась: «{outfit}»',
        'm27.card.wear.m': '{name} переоделся: «{outfit}»',
        'm27.card.wear.n': '{name} — в другой одежде: «{outfit}»',
        'm27.card.wear.body': 'Сейчас: {text}. Это знакомый наряд «{outfit}» — надеть его в этом чате?',
        'm27.card.create.body':
            'Сейчас: {text}. Запомнить это как новый наряд «{outfit}»? Тогда картинки в этом чате будут рисовать его каждый раз одинаково, а когда он вернётся, я его узнаю.',
        'm27.card.created.f': '{name} переоделась: «{outfit}» (новый наряд)',
        'm27.card.created.m': '{name} переоделся: «{outfit}» (новый наряд)',
        'm27.card.created.n': '{name} — в другой одежде: «{outfit}» (новый наряд)',
        'm27.card.clothing': '{name} снова в своей одежде',
        'm27.card.clothing.body': 'Сейчас: {text}. Вернуть в этом чате обычную одежду персонажа?',
        'm27.card.undress.naked': '{name} без одежды',
        'm27.card.undress.towel': '{name} в полотенце',
        'm27.card.undress.underwear': '{name} в нижнем белье',
        'm27.card.undress.partial': '{name} частично без одежды',
        'm27.card.undress.body':
            'Сейчас: {text}. Пока {name} снова не оденется, картинки в этом чате будут рисовать так.',
        'm27.card.copy': '{name}: своя внешность в этом чате',
        'm27.card.copy.body':
            'Внешность «{name}» записана только в лоре. Скопировать её в этот чат, чтобы здесь запоминались наряды? Сам лор не изменится.',
        'm27.card.copy.done': 'Скопировал внешность «{name}» в этот чат: теперь здесь запоминаются наряды.',
        'm27.card.stateOn': '{name}: {state}',
        'm27.card.stateOff': '{name}: {state} — уже нет',
        'm27.card.stateOn.body': 'Так сейчас в истории. Картинки в этом чате будут это показывать, пока так и есть.',
        'm27.card.stateOff.body': 'В истории этого больше нет. Картинки в этом чате перестанут это показывать.',
        'm27.card.placeOn.body': 'Так сейчас в истории. Картинки этого места будут это показывать, пока так и есть.',
        'm27.card.placeOff.body': 'В истории этого больше нет. Картинки этого места перестанут это показывать.',
        'm27.card.stateOn.done': 'Отметил: {name} — {state}',
        'm27.card.stateOff.done': 'Прошло: {name} — {state}',
        'm27.card.details.tags': 'Теги для картинок: {tags}',
        'm27.card.details.copy': 'Паспорт NAI Studio из записи лора скопирован в паспорт чата {id}',
        'm27.done.outfits.one': 'Переоделся {count} персонаж',
        'm27.done.outfits.few': 'Переоделись {count} персонажа',
        'm27.done.outfits.many': 'Переоделись {count} персонажей',
        'm27.done.states.one': 'Отметил {count} перемену в том, как выглядят персонажи и места',
        'm27.done.states.few': 'Отметил {count} перемены в том, как выглядят персонажи и места',
        'm27.done.states.many': 'Отметил {count} перемен в том, как выглядят персонажи и места',
        'm27.journal.wear': '{name}: наряд «{outfit}», выбран вручную',
        'm27.journal.wearOwn': '{name}: снова своя одежда, выбрано вручную',

        'm27.error.noNai': 'Для этого нужен NAI Studio 0.10 или новее.',
        'm27.error.gone': 'У этого персонажа больше нет внешности в этом чате.',
        'm27.error.noOutfit': 'Наряда «{name}» нет.',
        'm27.error.noChat': 'Чат не открыт.',
        'm27.error.noPassport': 'У этого персонажа нет внешности для картинок в этом чате.',
        'm27.error.noGarment': 'В том, что сейчас надето, не узнаётся ни одной вещи.',

        'm27.now.title': 'Кто в сцене и что на нём',
        'm27.now.empty': 'Трекер пока не говорил, кто во что одет.',
        'm27.now.outfit': 'Наряд: «{name}»',
        'm27.now.own': 'Своя одежда',
        'm27.now.new': 'Новое — запомню, если продержится ещё ход',
        'm27.now.queued': 'Ждёт твоего решения: «{name}»',
        'm27.now.noPassport': 'Внешности для картинок нет — только запоминаю',
        'm27.now.since': 'с сообщения №{index}',
        'm27.now.away': 'не в сцене',
        'm27.now.you': 'ты',
        'm27.now.fromField': 'из поля «Одежда»',
        'm27.now.fromAppearance': 'из «Внешности»',
        'm27.now.other': 'Надеть другое',
        'm27.now.other.hint': 'Выбрать, какой это на самом деле наряд, — Maestro запомнит.',
        'm27.now.other.pick': 'Наряд',
        'm27.now.markNew': 'Это новый наряд',
        'm27.now.markNew.hint': 'Запомнить то, что сейчас надето, как новый наряд и надеть его.',
        'm27.now.created': 'Запомнил как «{name}».',
        'm27.undress.naked': 'без одежды',
        'm27.undress.towel': 'в полотенце',
        'm27.undress.underwear': 'в нижнем белье',
        'm27.undress.partial': 'частично без одежды',

        'm27.persona.title': 'Сейчас на тебе',
        'm27.persona.placeholder': 'например: серый дорожный плащ и сапоги',
        'm27.persona.save': 'Запомнить',
        'm27.persona.saved': 'Запомнил, что на тебе.',
        'm27.persona.empty': 'Напиши, во что одет твой персонаж.',
        'm27.persona.hint':
            'Maestro и сам читает это из твоих сообщений («переодеваюсь в домашнее»), а когда текст не говорит — спрашивает фоновую модель.',

        'kind.wardrobe.wearNow': 'Переодевания («Переодеть сейчас», по сообщениям)',
        'target.wardrobe.current': 'Что надето сейчас',
        'target.wardrobe.desTracker': 'Одежда в трекере DES',
        'm27.field.wearing': 'Надето',
        'm27.field.desWording': 'В трекере DES',
        'm27.journal.wearNow': '{name} → {outfit}',
        'm27.wearNow': 'Переодеть сейчас',
        'm27.wearNow.own': 'Переодеть в своё',
        'm27.wearNow.hint':
            'Переодеть сразу везде: «что надето сейчас», внешность для картинок, трекер и портрет DES, строка для модели.',
        'm27.quick.group': 'Переодеться',
        'm27.quick.me': 'Я ({name})',
        'm27.quick.describe': 'Описать…',
        'm27.quick.describe.short': 'своими словами',
        'm27.quick.describe.title': 'Во что переодеть — {name}?',
        'm27.quick.describe.hint': 'Одежда, обувь, украшения: «домашнее платье и тапочки».',
        'm27.quick.open': 'Открыть гардероб',
        'm27.quick.done': '{name} → {outfit}',
        'm27.strip.text': '{name} → {outfit}',
        'm27.strip.undo': 'Отменить',
        'm27.strip.other': 'Другое…',
        'm27.slash.help': 'Переодеть сейчас: /maestro-wear <кто> <наряд или описание>. «я» — твой персонаж.',
        'm27.slash.value': 'кто, потом наряд или одежда словами',
        'm27.slash.who': 'Кого переодеть? Начни с имени или «я».',
        'm27.slash.what': 'Во что? Добавь название наряда или опиши одежду.',
        'm27.slash.nothing': 'Ничего не поменялось.',
        'm27.settings.triggers': 'Переодевание по сообщениям',
        'm27.settings.triggers.hint':
            'Пишешь «переодеваюсь в домашнее» — и ответ уже пишется в новой одежде; то, что говорит рассказ, тоже считается. Чего текст не сказал, фоновая модель уточнит после ответа (не в экономном режиме).',
        'm27.settings.desWrite': 'Записывать одежду в трекер DES',
        'm27.settings.desWrite.hint': 'В поле одежды персонажа или во внешность, если одежда записана там.',
        'm27.settings.composer': '«Переодеться» в кнопке Maestro у поля ввода',
        'm27.settings.personaEvery.hint':
            'Проверка раз в N ходов работает, только пока «Переодевание по сообщениям» выключено.',
        'm27.change.profileTask': 'Гардероб: переодевания',

        'm27.desField.missing':
            'Никто не спрашивает у модели, кто во что одет, поэтому одежду я угадываю по описанию внешности и могу пропустить переодевание. Пусть DES каждый ход спрашивает про одежду отдельно? В его трекер добавится только поле «{name}»; отменить можно в журнале.',
        'm27.desField.add': 'Добавить поле',
        'm27.desField.added': 'Теперь DES спрашивает, кто во что одет: добавил поле «{name}».',
        'm27.desField.workshop': 'Сначала закрой мастерскую DES: при сохранении она перезаписывает настройки трекера.',
        'm27.desField.failed': 'Не получилось добавить поле: настройки DES недоступны.',
        'm27.desField.proposal': 'Спрашивать у модели, кто во что одет',
        'm27.desField.body':
            'DES будет каждый ход спрашивать у модели, во что одет каждый персонаж, — отдельным полем «{name}». По нему я точнее узнаю наряды, и картинки рисуют их одинаково. Больше в DES ничего не меняется.',
        'm27.desField.details': 'Трекер DES: новое поле персонажа «{name}» (id {id})',
        'm27.desField.notice':
            'Одежду я сейчас угадываю по описанию внешности. Пусть DES спрашивает у модели про одежду отдельно?',
        'm27.health.desField': 'Гардероб: спрашивает ли DES про одежду',
        'm27.health.desField.ok': 'DES спрашивает, кто во что одет.',
        'm27.health.desField.missing': 'DES не спрашивает про одежду: наряды угадываются по описанию внешности.',

        'm27.dropped.title': 'Не взял из ревизии',
        'm27.dropped.unknown': '{name}: «{text}» — в этом чате нет такого персонажа.',
        'm27.dropped.noGarment': '{name}: «{text}» — не узнал ни одной вещи.',
        'm27.dropped.removal': '{name}: «{text}» — тут сказано, что сняли, а не что надето.',
        'm27.dropped.noPassport': '{name}: «{text}» — у персонажа нет внешности для картинок.',

        'm27.state.wet': 'мокрая одежда',
        'm27.state.injured': 'раны',
        'm27.state.bloody': 'кровь',
        'm27.state.tired': 'усталость',
        'm27.state.dirty': 'грязь',
        'm27.state.sweaty': 'пот',
        'm27.state.drunk': 'опьянение',
        'm27.state.messy': 'растрёпанность',
        'm27.state.tears': 'слёзы',
        'm27.state.sick': 'болезнь',
        'm27.state.cold': 'озноб',
        'm27.state.bound': 'путы',
        'm27.state.ruined': 'разрушения',
        'm27.state.decorated': 'украшения',
        'm27.state.abandoned': 'запустение',
        'm27.state.burning': 'пожар',
        'm27.state.night': 'ночь',
        'm27.state.evening': 'вечер',
        'm27.state.dawn': 'утро',
        'm27.state.rain': 'дождь',
        'm27.state.snow': 'снег',
        'm27.state.fog': 'туман',
        'm27.state.storm': 'гроза',
        'm27.state.winter': 'зима',
        'm27.state.spring': 'весна',
        'm27.state.summer': 'лето',
        'm27.state.autumn': 'осень',
    },
};
