// Strings of M27 «Гардероб и состояния» (`m27.*`). Russian is the primary UI language; the user is addressed as «ты»
// (male). State names are nouns so they read the same for any character.
import type { I18nParts } from '../../shared/contracts';

export const WARDROBE_STRINGS: I18nParts = {
    en: {
        'm27.title': 'Wardrobe and states',
        'm27.tab': 'Wardrobe',
        'm27.hint':
            'Clothes and states of characters and places are kept and drawn the same way. A new outfit in the DES tracker (two turns in a row) becomes a named outfit of the chat-level NAI passport and is recognised when it comes back; wet, wounded, tired and the like switch passport states; ruins, fire, night or rain go to the location passport. Only this chat changes — the card stays as it is.',
        'm27.noChat': 'No chat is open.',
        'm27.group': 'Maestro sleeps in group chats.',
        'm27.noNai':
            'NAI Studio 0.10 or newer is needed: without its API outfits and states cannot be written. The outfit library below is what Maestro remembers.',
        'm27.notLeader':
            'Another Maestro tab follows the story and writes the passports; here you can still put an outfit on and undo changes.',

        'm27.section.present': 'In the scene',
        'm27.section.all': 'Characters with passports',
        'm27.empty.characters': 'No character of this chat has a NAI passport.',
        'm27.wearing': 'Wearing: {outfit}',
        'm27.clothing': 'own clothes (clothing slot)',
        'm27.outfits': 'Outfits ({count})',
        'm27.outfits.empty': 'No named outfits yet.',
        'm27.wear': 'Put on',
        'm27.wear.hint': 'Make this the active outfit in this chat (the card is not changed).',
        'm27.wear.clothing': 'Own clothes',
        'm27.wear.clothing.hint': 'Back to the clothing slot of the passport in this chat.',
        'm27.active': 'worn',
        'm27.seenAs': 'Recognised from: {text}',
        'm27.states': 'States: {list}',
        'm27.states.none': 'No states on.',
        'm27.recent': 'Recent changes',
        'm27.recent.none': 'No changes yet.',
        'm27.change.created': 'New outfit «{name}»',
        'm27.change.worn': 'Put on «{name}»',
        'm27.change.clothing': 'Back to own clothes',
        'm27.change.on': 'On: {state}',
        'm27.change.off': 'Off: {state}',
        'm27.change.message': 'message #{index}',
        'm27.change.byHand': 'by hand',
        'm27.change.revision': 'from the revision',
        'm27.undo': 'Undo',
        'm27.undo.hint': 'Restores the passport as it was before this change.',
        'm27.undo.failed': 'Could not undo the change.',
        'm27.undone': 'undone',

        'm27.place.title': 'Place',
        'm27.place.none': 'The current place is not known yet.',
        'm27.place.noPassport': 'This place has no NAI location passport, so its states are not written.',
        'm27.place.passport': 'Location passport: {name}',
        'm27.place.states': 'States: {list}',

        'm27.settings.title': 'By itself',
        'm27.settings.hint':
            'Off: Maestro leaves that part of the passports alone. How changes are confirmed (by itself, Inbox …) is set by the autonomy levels of the kinds wardrobe.* in the settings.',
        'm27.settings.outfits': 'Outfits from the DES tracker and the revision',
        'm27.settings.states': 'Character states',
        'm27.settings.places': 'Place states',

        'm27.proposal.create': '{name}: new outfit «{outfit}»',
        'm27.proposal.wear': '{name}: outfit «{outfit}» again',
        'm27.proposal.clothing': '{name}: own clothes again',
        'm27.proposal.stateOn': '{name}: {state}',
        'm27.proposal.stateOff': '{name}: no longer {state}',
        'm27.proposal.placeOn': '{place}: {state}',
        'm27.proposal.placeOff': '{place}: {state} is over',
        'm27.proposal.body.outfit': 'Tags: {tags}. DES: «{text}». Only this chat; the card is not changed.',
        'm27.proposal.body.state': 'Tags: {tags}. Only this chat; the card is not changed.',
        'm27.journal.wear': '{name}: «{outfit}» put on by hand',

        'm27.error.noNai': 'NAI Studio 0.10 or newer is needed (its API is not available).',
        'm27.error.gone': 'The passport is no longer in this chat.',
        'm27.error.noOutfit': 'The passport has no outfit «{name}».',
        'm27.error.noChat': 'No chat is open.',

        'm27.state.wet': 'wet',
        'm27.state.injured': 'wounds',
        'm27.state.bloody': 'blood',
        'm27.state.tired': 'tiredness',
        'm27.state.dirty': 'dirt',
        'm27.state.sweaty': 'sweat',
        'm27.state.drunk': 'drunkenness',
        'm27.state.messy': 'dishevelled',
        'm27.state.tears': 'tears',
        'm27.state.sick': 'sickness',
        'm27.state.cold': 'shivering',
        'm27.state.bound': 'bonds',
        'm27.state.ruined': 'ruins',
        'm27.state.decorated': 'decorations',
        'm27.state.abandoned': 'neglect',
        'm27.state.burning': 'fire',
        'm27.state.night': 'night',
        'm27.state.evening': 'evening',
        'm27.state.dawn': 'morning',
        'm27.state.rain': 'rain',
        'm27.state.snow': 'snow',
        'm27.state.fog': 'fog',
        'm27.state.storm': 'storm',
        'm27.state.winter': 'winter',
        'm27.state.spring': 'spring',
        'm27.state.summer': 'summer',
        'm27.state.autumn': 'autumn',
    },
    ru: {
        'm27.title': 'Гардероб и состояния',
        'm27.tab': 'Гардероб',
        'm27.hint':
            'Одежда и состояние персонажей и мест сохраняются и рисуются одинаково. Новый наряд в трекере DES (два хода подряд) становится именованным нарядом паспорта NAI уровня чата и узнаётся, когда возвращается; мокрая одежда, раны, усталость и подобное включают состояния паспорта; руины, пожар, ночь или дождь попадают в паспорт места. Меняется только этот чат — карточка остаётся как есть.',
        'm27.noChat': 'Чат не открыт.',
        'm27.group': 'В групповых чатах Maestro спит.',
        'm27.noNai':
            'Нужен NAI Studio 0.10 или новее: без его API наряды и состояния не записать. Ниже — библиотека нарядов, которую помнит Maestro.',
        'm27.notLeader':
            'За историей следит и пишет паспорта другая вкладка Maestro; надеть наряд и отменить изменения можно и здесь.',

        'm27.section.present': 'В сцене',
        'm27.section.all': 'Персонажи с паспортами',
        'm27.empty.characters': 'Ни у одного персонажа этого чата нет паспорта NAI.',
        'm27.wearing': 'Сейчас: {outfit}',
        'm27.clothing': 'своя одежда (слот «clothing»)',
        'm27.outfits': 'Наряды ({count})',
        'm27.outfits.empty': 'Именованных нарядов пока нет.',
        'm27.wear': 'Надеть',
        'm27.wear.hint': 'Сделать этот наряд активным в этом чате (карточка не меняется).',
        'm27.wear.clothing': 'Своя одежда',
        'm27.wear.clothing.hint': 'Вернуть в этом чате одежду из слота «clothing» паспорта.',
        'm27.active': 'надет',
        'm27.seenAs': 'Узнаётся по: {text}',
        'm27.states': 'Состояния: {list}',
        'm27.states.none': 'Состояния не включены.',
        'm27.recent': 'Последние изменения',
        'm27.recent.none': 'Изменений пока нет.',
        'm27.change.created': 'Новый наряд «{name}»',
        'm27.change.worn': 'Надет наряд «{name}»',
        'm27.change.clothing': 'Снова своя одежда',
        'm27.change.on': 'Включено: {state}',
        'm27.change.off': 'Выключено: {state}',
        'm27.change.message': 'сообщение №{index}',
        'm27.change.byHand': 'вручную',
        'm27.change.revision': 'по ревизии',
        'm27.undo': 'Отменить',
        'm27.undo.hint': 'Вернуть паспорт к виду до этого изменения.',
        'm27.undo.failed': 'Отменить изменение не удалось.',
        'm27.undone': 'отменено',

        'm27.place.title': 'Место',
        'm27.place.none': 'Текущее место пока не известно.',
        'm27.place.noPassport': 'У этого места нет паспорта локации NAI, поэтому его состояния не записываются.',
        'm27.place.passport': 'Паспорт места: {name}',
        'm27.place.states': 'Состояния: {list}',

        'm27.settings.title': 'Само',
        'm27.settings.hint':
            'Выключено — Maestro не трогает эту часть паспортов. Как подтверждаются изменения (само, «Входящие» …), задают уровни автономии видов wardrobe.* в настройках.',
        'm27.settings.outfits': 'Наряды из трекера DES и ревизии',
        'm27.settings.states': 'Состояния персонажей',
        'm27.settings.places': 'Состояния мест',

        'm27.proposal.create': '{name}: новый наряд «{outfit}»',
        'm27.proposal.wear': '{name}: снова наряд «{outfit}»',
        'm27.proposal.clothing': '{name}: снова своя одежда',
        'm27.proposal.stateOn': '{name}: {state}',
        'm27.proposal.stateOff': '{name}: {state} — уже нет',
        'm27.proposal.placeOn': '{place}: {state}',
        'm27.proposal.placeOff': '{place}: {state} — уже нет',
        'm27.proposal.body.outfit':
            'Теги: {tags}. В трекере DES: «{text}». Только для этого чата, карточка не меняется.',
        'm27.proposal.body.state': 'Теги: {tags}. Только для этого чата, карточка не меняется.',
        'm27.journal.wear': '{name}: наряд «{outfit}» надет вручную',

        'm27.error.noNai': 'Нужен NAI Studio 0.10 или новее (его API недоступен).',
        'm27.error.gone': 'Паспорта больше нет в этом чате.',
        'm27.error.noOutfit': 'В паспорте нет наряда «{name}».',
        'm27.error.noChat': 'Чат не открыт.',

        'm27.state.wet': 'мокрая одежда',
        'm27.state.injured': 'раны',
        'm27.state.bloody': 'кровь',
        'm27.state.tired': 'усталость',
        'm27.state.dirty': 'грязь',
        'm27.state.sweaty': 'пот',
        'm27.state.drunk': 'опьянение',
        'm27.state.messy': 'растрёпанность',
        'm27.state.tears': 'слёзы',
        'm27.state.sick': 'болезнь',
        'm27.state.cold': 'озноб',
        'm27.state.bound': 'путы',
        'm27.state.ruined': 'разрушения',
        'm27.state.decorated': 'украшения',
        'm27.state.abandoned': 'запустение',
        'm27.state.burning': 'пожар',
        'm27.state.night': 'ночь',
        'm27.state.evening': 'вечер',
        'm27.state.dawn': 'утро',
        'm27.state.rain': 'дождь',
        'm27.state.snow': 'снег',
        'm27.state.fog': 'туман',
        'm27.state.storm': 'гроза',
        'm27.state.winter': 'зима',
        'm27.state.spring': 'весна',
        'm27.state.summer': 'лето',
        'm27.state.autumn': 'осень',
    },
};
