// Strings of the assistant's preset and neighbour-prompt tools (M33 over M34/M36, plan-2 §1): scopes, card fields in
// words, summaries, warnings and refusals. Merged into WRITE_STRINGS (strings.ts); prefix `m33w.`. Russian is the
// primary UI language; the user is male (masculine or neutral forms).
import type { I18nParts } from '../../../../shared/contracts';

export const PRESET_WRITE_STRINGS: I18nParts = {
    en: {
        'm33w.scope.global': 'Everywhere',
        'm33w.scope.character': 'This character',
        'm33w.scope.characterNamed': 'This character ({name})',
        'm33w.scope.chat': 'This chat',

        'm33w.field.text': 'Text',
        'm33w.field.name': 'Name',
        'm33w.field.role': 'Role',
        'm33w.field.place': 'Where',
        'm33w.field.order': 'Order in the chat',
        'm33w.field.state': 'State',
        'm33w.field.position': 'Place in the list',
        'm33w.field.warnings': 'Note',
        'm33w.field.base': 'Based on',
        'm33w.field.blocks': 'Blocks that go out',
        'm33w.field.added': 'Added',
        'm33w.field.binding': 'Bound',
        'm33w.field.select': 'After creating',
        'm33w.field.unsaved': 'Unsaved edits',
        'm33w.field.version': 'Version',
        'm33w.field.what': 'What it was',
        'm33w.field.bound.character': 'Preset of the character',
        'm33w.field.bound.chat': 'Preset of the chat',

        'm33w.word.text': 'text',
        'm33w.word.name': 'name',
        'm33w.word.role': 'role',
        'm33w.word.place': 'place',
        'm33w.word.order': 'order',

        'm33w.role.system': 'system',
        'm33w.role.user': 'user',
        'm33w.role.assistant': 'assistant',

        'm33w.preset.place.inList': 'in the prompt list',
        'm33w.preset.place.inChat': 'in the chat at depth {depth}',

        'm33w.preset.summary.edit': 'Block «{name}»: {fields}',
        'm33w.preset.summary.on': 'Block «{name}»: switch on',
        'm33w.preset.summary.off': 'Block «{name}»: switch off',
        'm33w.preset.summary.move': 'Block «{name}»: move {place}',
        'm33w.preset.summary.removeOwn': 'Remove the block «{name}» (it was added by your layer)',
        'm33w.preset.summary.removeBase': 'Block «{name}»: switch off (the layer cannot delete a block of the preset)',
        'm33w.preset.summary.param': '{param}: {before} → {after}',
        'm33w.preset.warn.shadowed':
            'In «{scope}» this is already changed differently: here that edit wins, this one works where it does not.',
        'm33w.preset.warn.conflictAbove':
            'In «{scope}» this block has its own text edit: it becomes a conflict to resolve in the Preset Studio (the «Your layer» tab), and until then this text works there too.',
        'm33w.preset.warn.prefillEos':
            'With this model an assistant message at the end of the prompt (a prefill) breaks the reply: it ends at once.',
        'm33w.preset.warn.systemMerge':
            'With this model system messages inside the history merge into the neighbouring message: the user role is safer.',
        'm33w.preset.warn.assistantDepth':
            'An assistant message inside the history reads to the model as its own earlier reply.',
        'm33w.preset.warn.trackerSystem':
            'Moving the DES tracker instructions to the system role broke the tracker JSON and the coloured dialogue in practice: keep them as user.',
        'm33w.preset.warn.baseKept': 'The preset file keeps the block: you can switch it back on.',
        'm33w.preset.journal.one': 'Assistant: {summary}',
        'm33w.preset.journal.pack': 'Assistant: {count} edits of the preset «{preset}» at once',
        'm33w.pack.summary': 'Pack of edits ({count}): {summary}',

        'm33w.err.presetMarkerText': '«{name}» is filled by SillyTavern itself: its text cannot be edited.',
        'm33w.err.presetMarkerPlace': '«{name}» is a fixed place of SillyTavern: its role and place cannot be changed.',
        'm33w.err.presetNothing': 'Nothing changes in «{name}».',
        'm33w.err.presetDetached': '«{name}» is not in the prompt list now: put it back in the Preset Studio first.',
        'm33w.err.presetHistoryOff': 'Chat History must stay on: without it the model gets no chat at all.',
        'm33w.err.presetAlreadyState': '«{name}» is already {state}.',
        'm33w.err.presetOrderChanged': 'The order of the blocks changed after the plan: ask again.',
        'm33w.err.presetParamSame': '«{key}» already has this value.',
        'm33w.err.presetParamChanged': '«{key}» changed after the plan: ask again.',
        'm33w.err.presetScopeOff': '«{scope}» is not available now: open a chat with a character first.',
        'm33w.err.presetFindMissing': 'The block has no text «{find}»: read it again and copy the exact piece.',
        'm33w.err.presetFindAmbiguous': '«{find}» occurs {count} times: take a longer piece that occurs once.',
        'm33w.err.presetSelfAnchor': 'A block cannot go after or before itself.',
        'm33w.err.presetAnchorOff': '«{block}» is not in the prompt list.',
        'm33w.err.presetSamePlace': 'The block already stands there.',
        'm33w.err.presetParamHidden':
            '«{key}» is a connection setting (source, model, address or key): it is changed by hand only.',
        'm33w.err.presetParamUnknown': '«{key}» is not a generation parameter the Preset Studio edits.',
        'm33w.err.presetParamType': '«{key}» must be {expected}.',
        'm33w.err.presetParamRange': '«{key}» must be from {min} to {max}.',
        'm33w.err.presetParamOption': '«{key}» must be one of: {options}.',
        'm33w.err.presetPackTooBig': 'A pack holds at most {max} edits ({count} given).',
        'm33w.err.presetPackTwice': 'The pack changes the same thing twice («{summary}»): merge them into one edit.',
        'm33w.err.presetPackTool': 'Edit {index} of the pack: «tool» must be one of {tools}.',
        'm33w.err.presetPackItem': 'Edit {index} of the pack: {error}',

        'm33w.target.presets': 'Presets',
        'm33w.target.binding': 'Preset of the character and the chat',
        'm33w.err.presetUnknown': 'There is no preset «{preset}». Presets: {list}.',
        'm33w.err.presetExists': 'A preset «{preset}» already exists: choose another name.',
        'm33w.err.presetPastedInvalid': 'The pasted text is not a preset (JSON of a preset file is needed).',
        'm33w.err.presetPastedMissing': 'A block is taken from a pasted preset, but nothing was pasted.',
        'm33w.err.presetBindUnavailable': 'Binding presets is not available (the Preset Studio has no layer).',
        'm33w.err.presetBindNoChat': 'Open a character’s chat first: a preset is bound to a character or a chat.',
        'm33w.err.presetNotBound': 'No preset is bound {where}.',
        'm33w.err.presetAlreadyBound': '«{preset}» is already bound {where}.',
        'm33w.err.presetNothingToSave':
            'The preset «{preset}» has no unsaved edits: what the assistant changed is saved by «Apply» already.',
        'm33w.err.presetNoVersion': 'The preset «{preset}» has no such version.',
        'm33w.err.presetStoreUnavailable': 'The preset store is not ready yet: try again in a moment.',
        'm33w.err.presetStoreMissing': 'The preset or its version is gone.',
        'm33w.err.presetStoreExists': 'A preset with this name already exists.',
        'm33w.err.presetStoreInvalid': 'SillyTavern did not take this preset (the name or the content is not valid).',
        'm33w.err.presetStoreBusy': 'SillyTavern is generating a reply now: try again when it is done.',
        'm33w.err.presetStoreCancelled': 'Cancelled.',
        'm33w.err.presetStoreProtected': 'This preset is protected and cannot be changed.',
        'm33w.err.presetStoreHttp': 'The server did not save the preset.',

        'm33w.bind.toChat': 'to this chat',
        'm33w.bind.toCharacter': 'to {character}',
        'm33w.bind.none': 'none',
        'm33w.bind.summary': 'Bind the preset «{preset}» {where}',
        'm33w.unbind.summary': 'Unbind the preset «{preset}» {where}',
        'm33w.bind.switchNote':
            'The preset is switched on at once (with the question about unsaved edits) and also every time this chat opens.',

        'm33w.create.base.empty': 'a fresh SillyTavern preset',
        'm33w.create.base.preset': 'the preset «{preset}»',
        'm33w.create.base.current': 'the current preset «{preset}» with your edits',
        'm33w.create.pasted': 'the pasted preset',
        'm33w.create.picked': '«{name}» from {preset}',
        'm33w.create.new': '«{name}» (new)',
        'm33w.create.selectNow': 'switch to it',
        'm33w.create.summary': 'New preset «{name}»: {count} blocks, based on {base}',
        'm33w.create.journal': 'Assistant: created the preset «{name}»',
        'm33w.create.version': 'Created by the assistant',

        'm33w.save.as.summary': 'Save the preset «{preset}» as «{name}» and switch to it',
        'm33w.save.summary': 'Save the unsaved edits of the preset «{preset}» into its file',
        'm33w.save.unsaved': 'blocks: {blocks}, parameters: {params}',
        'm33w.save.saved': 'saved',
        'm33w.save.version': 'Saved by the assistant',
        'm33w.restore.summary': 'Bring the preset «{preset}» back to the version of {date}',
        'm33w.restore.draftKept': 'The unsaved edits are kept as a version too.',
        'm33w.restore.now': 'as it is now',

        'm33w.target.neighbour': 'Prompts of the extensions · «{name}»',
        'm33w.neighbour.scope.global': 'Everywhere (the extension’s setting)',
        'm33w.neighbour.scope.character': 'Copy for this character',
        'm33w.neighbour.scope.characterNamed': 'Copy for this character ({name})',
        'm33w.neighbour.scope.chat': 'Copy for this chat',
        'm33w.neighbour.summary.set': '«{name}»: new text',
        'm33w.neighbour.summary.reset': '«{name}»: back to how it was',
        'm33w.neighbour.warn.copyWins':
            'This character or chat has its own copy: here the copy keeps working, the new text works in the other chats.',
        'm33w.neighbour.warn.absent': 'The extension is off now: the text takes effect when it is on.',
        'm33w.err.neighbourUnavailable': 'The neighbour prompts module is off.',
        'm33w.err.neighbourUnknown': 'There is no entry «{id}». Entries: {list}.',
        'm33w.err.neighbourForbidden': '«{name}» belongs to CarrotKernel or BunnyMo packs: Maestro never changes them.',
        'm33w.err.neighbourReadOnlyEntry': '«{name}» cannot be changed from here. {note}',
        'm33w.err.neighbourNoGlobal':
            '«{name}» cannot be changed everywhere, only as a copy for a character or a chat.',
        'm33w.err.neighbourNoCopyHere': '«{name}» cannot get a copy here ({scope}).',
        'm33w.err.neighbourUnknownId': 'There is no such entry («{name}»).',
        'm33w.err.neighbourReadOnly': '«{name}» cannot be changed from here.',
        'm33w.err.neighbourAbsent': 'The extension of «{name}» is off or did not take the text.',
        'm33w.err.neighbourBusy': 'DES Workshop is open: close it and try again.',
        'm33w.err.neighbourNoCopy': '«{name}» cannot get a copy for a character or a chat.',
        'm33w.err.neighbourNoScope': 'Open a character’s chat first.',
    },
    ru: {
        'm33w.scope.global': 'Везде',
        'm33w.scope.character': 'Этот персонаж',
        'm33w.scope.characterNamed': 'Этот персонаж ({name})',
        'm33w.scope.chat': 'Этот чат',

        'm33w.field.text': 'Текст',
        'm33w.field.name': 'Название',
        'm33w.field.role': 'Роль',
        'm33w.field.place': 'Где',
        'm33w.field.order': 'Порядок в чате',
        'm33w.field.state': 'Состояние',
        'm33w.field.position': 'Место в списке',
        'm33w.field.warnings': 'Обрати внимание',
        'm33w.field.base': 'Основа',
        'm33w.field.blocks': 'Что уходит модели',
        'm33w.field.added': 'Добавлено',
        'm33w.field.binding': 'Привязка',
        'm33w.field.select': 'После создания',
        'm33w.field.unsaved': 'Несохранённые правки',
        'm33w.field.version': 'Версия',
        'm33w.field.what': 'Что это было',
        'm33w.field.bound.character': 'Пресет персонажа',
        'm33w.field.bound.chat': 'Пресет чата',

        'm33w.word.text': 'текст',
        'm33w.word.name': 'название',
        'm33w.word.role': 'роль',
        'm33w.word.place': 'место',
        'm33w.word.order': 'порядок',

        'm33w.role.system': 'система',
        'm33w.role.user': 'пользователь',
        'm33w.role.assistant': 'ассистент',

        'm33w.preset.place.inList': 'в списке промпта',
        'm33w.preset.place.inChat': 'в чате на глубине {depth}',

        'm33w.preset.summary.edit': 'Блок «{name}»: {fields}',
        'm33w.preset.summary.on': 'Блок «{name}»: включить',
        'm33w.preset.summary.off': 'Блок «{name}»: выключить',
        'm33w.preset.summary.move': 'Блок «{name}»: перенести {place}',
        'm33w.preset.summary.removeOwn': 'Удалить блок «{name}» (его добавил твой слой)',
        'm33w.preset.summary.removeBase': 'Блок «{name}»: выключить (блок самого пресета слой удалить не может)',
        'm33w.preset.summary.param': '{param}: {before} → {after}',
        'm33w.preset.warn.shadowed':
            'В области «{scope}» это уже изменено по-другому: там сработает та правка, эта — везде, где её нет.',
        'm33w.preset.warn.conflictAbove':
            'В области «{scope}» у блока своя правка текста: она станет конфликтом, который решается в Пресет-студии (вкладка «Слой»), а до тех пор и там будет работать этот текст.',
        'm33w.preset.warn.prefillEos':
            'У этой модели сообщение ассистента в конце промпта (префилл) ломает ответ: он сразу обрывается.',
        'm33w.preset.warn.systemMerge':
            'У этой модели системные сообщения посреди истории склеиваются с соседним сообщением: надёжнее роль пользователя.',
        'm33w.preset.warn.assistantDepth': 'Сообщение ассистента внутри истории модель читает как свой прошлый ответ.',
        'm33w.preset.warn.trackerSystem':
            'Перенос инструкций трекера DES в системную роль на практике ломал JSON трекера и цвета реплик: оставь роль пользователя.',
        'm33w.preset.warn.baseKept': 'В файле пресета блок останется: его можно будет включить обратно.',
        'm33w.preset.journal.one': 'Ассистент: {summary}',
        'm33w.preset.journal.pack': 'Ассистент: правки пресета «{preset}» одним пакетом ({count})',
        'm33w.pack.summary': 'Пакет правок ({count}): {summary}',

        'm33w.err.presetMarkerText': '«{name}» заполняет сам SillyTavern — его текст не правится.',
        'm33w.err.presetMarkerPlace': '«{name}» — постоянное место SillyTavern: его роль и место не меняются.',
        'm33w.err.presetNothing': 'В «{name}» ничего не меняется.',
        'm33w.err.presetDetached': '«{name}» сейчас не в списке промпта — сначала верни его в Пресет-студии.',
        'm33w.err.presetHistoryOff': 'История чата должна оставаться включённой: без неё модель не получит чат вовсе.',
        'm33w.err.presetAlreadyState': '«{name}» уже {state}.',
        'm33w.err.presetOrderChanged': 'Порядок блоков изменился после плана — спроси ещё раз.',
        'm33w.err.presetParamSame': 'У «{key}» уже такое значение.',
        'm33w.err.presetParamChanged': '«{key}» изменился после плана — спроси ещё раз.',
        'm33w.err.presetScopeOff': '«{scope}» сейчас недоступно: сначала открой чат с персонажем.',
        'm33w.err.presetFindMissing': 'В блоке нет текста «{find}» — перечитай блок и возьми точный кусок.',
        'm33w.err.presetFindAmbiguous':
            '«{find}» встречается не один раз (найдено: {count}) — возьми кусок длиннее, который есть только однажды.',
        'm33w.err.presetSelfAnchor': 'Блок не может встать после или перед самим собой.',
        'm33w.err.presetAnchorOff': '«{block}» нет в списке промпта.',
        'm33w.err.presetSamePlace': 'Блок уже стоит там.',
        'm33w.err.presetParamHidden':
            '«{key}» — настройка подключения (источник, модель, адрес или ключ): она меняется только вручную.',
        'm33w.err.presetParamUnknown': '«{key}» — не параметр генерации, который правит Пресет-студия.',
        'm33w.err.presetParamType': '«{key}» должен быть: {expected}.',
        'm33w.err.presetParamRange': '«{key}» должен быть от {min} до {max}.',
        'm33w.err.presetParamOption': '«{key}» может быть только: {options}.',
        'm33w.err.presetPackTooBig': 'В пакете не больше {max} правок (а дано {count}).',
        'm33w.err.presetPackTwice': 'Пакет дважды меняет одно и то же («{summary}») — объедини в одну правку.',
        'm33w.err.presetPackTool': 'Правка {index} пакета: «tool» должен быть одним из {tools}.',
        'm33w.err.presetPackItem': 'Правка {index} пакета: {error}',

        'm33w.target.presets': 'Пресеты',
        'm33w.target.binding': 'Пресет персонажа и чата',
        'm33w.err.presetUnknown': 'Пресета «{preset}» нет. Есть: {list}.',
        'm33w.err.presetExists': 'Пресет «{preset}» уже есть — выбери другое название.',
        'm33w.err.presetPastedInvalid': 'Вставленный текст — не пресет (нужен JSON файла пресета).',
        'm33w.err.presetPastedMissing': 'Блок берётся из вставленного пресета, но ничего не вставлено.',
        'm33w.err.presetBindUnavailable': 'Привязка пресетов недоступна (у Пресет-студии нет слоя).',
        'm33w.err.presetBindNoChat': 'Сначала открой чат персонажа: пресет привязывается к персонажу или к чату.',
        'm33w.err.presetNotBound': 'Пресет {where} не привязан.',
        'm33w.err.presetAlreadyBound': '«{preset}» уже привязан {where}.',
        'm33w.err.presetNothingToSave':
            'У пресета «{preset}» нет несохранённых правок: то, что менял ассистент, уже сохранено кнопкой «Применить».',
        'm33w.err.presetNoVersion': 'У пресета «{preset}» нет такой версии.',
        'm33w.err.presetStoreUnavailable': 'Хранилище пресетов ещё не готово — попробуй через минуту.',
        'm33w.err.presetStoreMissing': 'Пресета или его версии уже нет.',
        'm33w.err.presetStoreExists': 'Пресет с таким названием уже есть.',
        'm33w.err.presetStoreInvalid': 'SillyTavern не принял этот пресет (неверное название или содержимое).',
        'm33w.err.presetStoreBusy': 'SillyTavern сейчас пишет ответ — попробуй, когда закончит.',
        'm33w.err.presetStoreCancelled': 'Отменено.',
        'm33w.err.presetStoreProtected': 'Этот пресет защищён от изменений.',
        'm33w.err.presetStoreHttp': 'Сервер не сохранил пресет.',

        'm33w.bind.toChat': 'к этому чату',
        'm33w.bind.toCharacter': 'к персонажу {character}',
        'm33w.bind.none': 'нет',
        'm33w.bind.summary': 'Привязать пресет «{preset}» {where}',
        'm33w.unbind.summary': 'Отвязать пресет «{preset}» {where}',
        'm33w.bind.switchNote':
            'Пресет включится сразу (с вопросом о несохранённых правках) и потом — каждый раз при входе в этот чат.',

        'm33w.create.base.empty': 'чистый пресет SillyTavern',
        'm33w.create.base.preset': 'пресет «{preset}»',
        'm33w.create.base.current': 'текущий пресет «{preset}» с твоими правками',
        'm33w.create.pasted': 'вставленного пресета',
        'm33w.create.picked': '«{name}» из {preset}',
        'm33w.create.new': '«{name}» (новый)',
        'm33w.create.selectNow': 'сразу включить',
        'm33w.create.summary': 'Новый пресет «{name}»: блоков {count}, основа — {base}',
        'm33w.create.journal': 'Ассистент: создал пресет «{name}»',
        'm33w.create.version': 'Создан ассистентом',

        'm33w.save.as.summary': 'Сохранить пресет «{preset}» как «{name}» и переключиться на него',
        'm33w.save.summary': 'Сохранить несохранённые правки пресета «{preset}» в его файл',
        'm33w.save.unsaved': 'блоков: {blocks}, параметров: {params}',
        'm33w.save.saved': 'сохранены',
        'm33w.save.version': 'Сохранён ассистентом',
        'm33w.restore.summary': 'Вернуть пресет «{preset}» к версии от {date}',
        'm33w.restore.draftKept': 'Несохранённые правки тоже сохранятся отдельной версией.',
        'm33w.restore.now': 'как сейчас',

        'm33w.target.neighbour': 'Промпты расширений · «{name}»',
        'm33w.neighbour.scope.global': 'Везде (настройка расширения)',
        'm33w.neighbour.scope.character': 'Копия для этого персонажа',
        'm33w.neighbour.scope.characterNamed': 'Копия для этого персонажа ({name})',
        'm33w.neighbour.scope.chat': 'Копия для этого чата',
        'm33w.neighbour.summary.set': '«{name}»: новый текст',
        'm33w.neighbour.summary.reset': '«{name}»: вернуть как было',
        'm33w.neighbour.warn.copyWins':
            'У этого персонажа или чата своя копия: здесь продолжит работать она, новый текст — в остальных чатах.',
        'm33w.neighbour.warn.absent': 'Расширение сейчас выключено: текст заработает, когда его включат.',
        'm33w.err.neighbourUnavailable': 'Модуль «Промпты соседей» выключен.',
        'm33w.err.neighbourUnknown': 'Записи «{id}» нет. Есть: {list}.',
        'm33w.err.neighbourForbidden': '«{name}» — часть CarrotKernel или паков BunnyMo: Maestro их никогда не меняет.',
        'm33w.err.neighbourReadOnlyEntry': '«{name}» отсюда не меняется. {note}',
        'm33w.err.neighbourNoGlobal': '«{name}» нельзя поменять везде — только копией для персонажа или чата.',
        'm33w.err.neighbourNoCopyHere': 'Для «{name}» здесь нельзя сделать копию ({scope}).',
        'm33w.err.neighbourUnknownId': 'Такой записи нет («{name}»).',
        'm33w.err.neighbourReadOnly': '«{name}» отсюда не меняется.',
        'm33w.err.neighbourAbsent': 'Расширение для «{name}» выключено или не приняло текст.',
        'm33w.err.neighbourBusy': 'Открыта мастерская DES — закрой её и попробуй снова.',
        'm33w.err.neighbourNoCopy': 'Для «{name}» нельзя сделать копию для персонажа или чата.',
        'm33w.err.neighbourNoScope': 'Сначала открой чат персонажа.',
    },
};
