// Strings of the assistant's write tools (M33): card summaries and targets, refusals and validation errors, journal
// lines. Prefix `m33w.` (the module's own `m33.` keys belong to the core). Russian is the primary UI language; the
// user is male (masculine or neutral forms). Exported for the module's i18n; the tools translate with the
// conversation's locale (ToolContext.locale) through `sayer()`.
import type { I18nParts } from '../../../../shared/contracts';

export const WRITE_STRINGS: I18nParts = {
    en: {
        'm33w.on': 'on',
        'm33w.off': 'off',
        'm33w.state.on': 'on',
        'm33w.state.off': 'off',
        'm33w.stateF.on': 'on',
        'm33w.stateF.off': 'off',

        'm33w.type.string': 'a text',
        'm33w.type.boolean': 'true or false',
        'm33w.type.number': 'a number',
        'm33w.type.integer': 'a whole number',
        'm33w.type.list': 'a list of texts',
        'm33w.type.object': 'a JSON object',

        'm33w.err.argMissing': 'The parameter «{name}» is missing.',
        'm33w.err.argType': '«{name}» must be {expected}.',
        'm33w.err.argEmpty': '«{name}» is empty.',
        'm33w.err.argTooLong': '«{name}» is longer than {max} characters.',
        'm33w.err.argRange': '«{name}» must be from {min} to {max}.',
        'm33w.err.argEnum': '«{name}» must be one of: {options}.',
        'm33w.err.argTooMany': '«{name}» has more than {max} items.',
        'm33w.err.argOneOf': 'Give either «{a}» or «{b}», not both.',
        'm33w.err.argNeedOne': 'Give «{a}» or «{b}».',

        'm33w.target.modules': 'Maestro · modules',
        'm33w.err.moduleUnknown': 'There is no module «{module}». Modules: {list}.',
        'm33w.err.moduleSelf': 'The assistant does not switch its own module.',
        'm33w.err.moduleAlready': '«{title}» is already {state}.',
        'm33w.err.moduleMissing': '«{title}» cannot start: this SillyTavern lacks {caps}.',
        'm33w.module.summary.on': '{title} ({id}): switch on',
        'm33w.module.summary.off': '{title} ({id}): switch off',
        'm33w.module.journal.on': 'Switched on the module «{title}»',
        'm33w.module.journal.off': 'Switched off the module «{title}»',

        'm33w.target.autonomy': 'Maestro · autonomy',
        'm33w.err.autonomyKind': 'Unknown kind of actions «{kind}». Known kinds: {list}.',
        'm33w.err.autonomyNeverAuto': '«{kind}» can never be done automatically.',
        'm33w.err.autonomyAlready': '«{kind}» already has «{level}».',
        'm33w.autonomy.none': 'none yet',
        'm33w.autonomy.summary': 'Autonomy of «{kind}»: {from} → {to}',
        'm33w.autonomy.newKind': 'This kind of actions has not come up yet.',
        'm33w.autonomy.journal': 'Set «{level}» for «{kind}»',
        'm33w.autonomy.journalUnnamed': 'Set «{level}» for one kind of actions',
        'm33w.level.auto': 'Auto',
        'm33w.level.notify': 'Notify',
        'm33w.level.inbox': 'Inbox',
        'm33w.level.ask': 'Ask',
        'm33w.level.off': 'Off',
        'm33w.level.default': 'Module default',

        'm33w.target.mechanic': 'Mechanics · «{name}»',
        'm33w.target.mechanicChat': 'Mechanics · this chat',
        'm33w.err.mechanicUnavailable': 'The Mechanics module is off.',
        'm33w.err.mechanicTemplate': 'There is no template «{template}». Templates: {list}.',
        'm33w.err.mechanicInvalid': 'The mechanic cannot be saved: {issues}',
        'm33w.err.mechanicNotDef': 'This is not a mechanic definition (it needs at least a name).',
        'm33w.err.mechanicUnknown': 'There is no mechanic «{id}» here. Mechanics: {list}.',
        'm33w.err.mechanicNoChat': 'Open a chat first.',
        'm33w.err.mechanicAlready': '«{name}» is already {state} in this chat.',
        'm33w.err.mechanicScope': 'The scope «{scope}» is not possible here (no single character or no chat).',
        'm33w.mechanic.summary.create': 'New mechanic «{name}»: {attributes} attributes, {checks} checks, {scope}',
        'm33w.mechanic.summary.update': 'Mechanic «{name}»: changes',
        'm33w.mechanic.summary.chatOn': 'Mechanic «{name}» in this chat: switch on',
        'm33w.mechanic.summary.chatOff': 'Mechanic «{name}» in this chat: switch off',
        'm33w.mechanic.journal.chatOn': 'Switched on the mechanic «{name}» in this chat',
        'm33w.mechanic.journal.chatOff': 'Switched off the mechanic «{name}» in this chat',
        'm33w.mechanic.scope.card': 'for this character',
        'm33w.mechanic.scope.chat': 'in this chat',
        'm33w.mechanic.scope.global': 'everywhere',

        'm33w.target.regex': 'SillyTavern regexes · global',
        'm33w.err.regexUnavailable': 'SillyTavern regex scripts are not available.',
        'm33w.err.regexCompile': 'The regex does not compile: {error}',
        'm33w.err.regexFlags': 'Flags «{flags}» do not fit: SillyTavern takes g, i, m, s, u (each once).',
        'm33w.err.regexFlagsConflict': 'The flags are given twice and differ: «{a}» in find, «{b}» in flags.',
        'm33w.err.regexDepth': 'minDepth is above maxDepth.',
        'm33w.err.regexNoMatch':
            'Test failed: the regex changes none of the samples. Give a sample it is meant to change, or fix the regex.',
        'm33w.err.regexExpected': 'Test failed on sample {index}: expected «{expected}», got «{actual}».',
        'm33w.err.regexExpectedCount': '«expected» needs one text per sample ({count}).',
        'm33w.err.regexUnknown': 'There is no global regex «{id}».',
        'm33w.err.regexAmbiguous': 'Several global regexes are called «{id}»: use the id.',
        'm33w.err.regexForeign':
            'Only global regexes can be switched here: «{id}» belongs to a character card or a preset.',
        'm33w.err.regexAlready': 'The regex «{name}» is already {state}.',
        'm33w.err.regexGone': 'The regex «{name}» is gone.',
        'm33w.regex.summary.create': 'New regex «{name}» ({where}; {mode}); test: {changed} of {total} samples changed',
        'm33w.regex.summary.on': 'Regex «{name}»: switch on',
        'm33w.regex.summary.off': 'Regex «{name}»: switch off',
        'm33w.regex.journal.create': 'Added the regex «{name}»',
        'm33w.regex.journal.on': 'Switched on the regex «{name}»',
        'm33w.regex.journal.off': 'Switched off the regex «{name}»',
        'm33w.regex.place.user_input': 'user input',
        'm33w.regex.place.ai_output': 'AI output',
        'm33w.regex.place.slash_command': 'slash commands',
        'm33w.regex.place.world_info': 'World Info',
        'm33w.regex.place.reasoning': 'reasoning',
        'm33w.regex.mode.display': 'display only',
        'm33w.regex.mode.prompt': 'prompt only',
        'm33w.regex.mode.displayAndPrompt': 'display and prompt',
        'm33w.regex.mode.edit': 'changes the stored message text',
        'm33w.regex.warn.breaksJson': 'Breaks the DES tracker JSON in replies.',
        'm33w.regex.warn.stripsTags': 'Removes BunnyMo tags.',
        'm33w.regex.warn.breaksMarkers': 'Damages NAI Studio image markers.',
        'm33w.regex.warn.worldInfoNotPrompt': 'On World Info a regex works only in the «prompt only» mode.',
        'm33w.regex.warn.matchesEmpty': 'Matches empty text: the replacement goes between characters.',
        'm33w.regex.warn.macros': 'Macros ({{…}}) were not filled in during the test.',
        'm33w.regex.warn.sameName': 'A global regex with this name already exists.',
        'm33w.regex.warn.extensionOff': 'The Regex extension is disabled in SillyTavern: no script runs.',

        'm33w.target.preset': 'Preset «{preset}» · your layer',
        'm33w.target.presetBlock': 'Preset «{preset}» · your layer · «{name}»',
        'm33w.err.presetUnavailable': 'The Preset Studio is off or has no layer.',
        'm33w.err.presetNone': 'No Chat Completion preset is selected.',
        'm33w.err.presetNoBlock': 'There is no block «{block}» in the preset «{preset}».',
        'm33w.err.presetAmbiguous': 'Several blocks are called «{block}»: use the identifier.',
        'm33w.err.presetNeedAnchor': 'Name the block to put the new one «{place}».',
        'm33w.err.presetMarker': '«{name}» is filled by SillyTavern itself: its text cannot get a condition.',
        'm33w.err.presetOutside':
            '«{name}» is neither in the saved preset nor in your layer (made outside the studio and not saved).',
        'm33w.err.presetFlagInvalid': '«{flag}» cannot be a flag name.',
        'm33w.err.presetFlagUnknown':
            'Unknown flag «{flag}»: take one from the catalogue or a maestro_… name. Catalogue: {list}.',
        'm33w.err.presetFlagNeeded': 'The mode «{mode}» needs a flag.',
        'm33w.err.presetBlocked': 'The block text has stray {{if}}/{{else}}/{{/if}} tags: fix them first.',
        'm33w.err.presetAlready': '«{name}» already has this condition.',
        'm33w.err.presetChanged': 'The preset changed after the plan («{preset}» → «{current}»).',
        'm33w.err.presetBlockChanged': 'The block «{name}» changed after the plan: ask again.',
        'm33w.preset.summary.add': 'New block «{name}» ({role}) {place}{condition}',
        'm33w.preset.place.start': 'at the start',
        'm33w.preset.place.end': 'at the end',
        'm33w.preset.place.after': 'after «{block}»',
        'm33w.preset.place.before': 'before «{block}»',
        'm33w.preset.place.depth': 'in the chat at depth {depth}',
        'm33w.preset.cond.only': ', only when {flag}',
        'm33w.preset.cond.except': ', except when {flag}',
        'm33w.preset.summary.only': 'Block «{name}»: only when {flag}',
        'm33w.preset.summary.except': 'Block «{name}»: except when {flag}',
        'm33w.preset.summary.always': 'Block «{name}»: always (no condition)',
        'm33w.preset.warn.flagNotInCatalogue':
            'Nothing sets «{flag}» yet: until something does, an «only when» block stays silent and an «except» block is always sent.',
        'm33w.preset.warn.macroEngine':
            'The new macro engine of SillyTavern is not on: {{if}} would reach the model as plain text.',
        'm33w.preset.warn.disabled': 'The block is added switched off.',

        'm33w.target.loreNew': 'Book «{book}» · new entry',
        'm33w.target.loreEntry': 'Book «{book}» · entry {uid}',
        'm33w.target.passport': 'Book «{book}» · entry {uid} · passport',
        'm33w.err.loreUnavailable': 'The Lore Studio is off.',
        'm33w.err.loreNoBook': 'There is no book «{book}».',
        'm33w.err.loreAmbiguous': 'Several books are called «{book}»: use the exact name.',
        'm33w.err.loreBunnyMo': '«{book}» is a BunnyMo book: its files are never changed (P13).',
        'm33w.err.loreReadOnly': '«{book}» is read-only.',
        'm33w.err.loreNoEntry': 'There is no entry {uid} in «{book}».',
        'm33w.err.loreBadType': 'Unknown entry type «{type}». Types: {list}.',
        'm33w.err.loreBadField': 'The type «{type}» has no field «{field}». Fields: {list}.',
        'm33w.err.loreNoContent': 'The entry has no text: give «content» or the fields of its type.',
        'm33w.err.loreNoKeys': 'The entry needs keys (or constant: true).',
        'm33w.err.loreTypeNeeded': 'The entry has no type: give «type» together with the fields.',
        'm33w.err.loreNothing': 'Nothing changes.',
        'm33w.lore.summary.create': 'New entry «{title}» in «{book}»',
        'm33w.lore.summary.update': 'Entry «{title}» in «{book}»: {fields}',
        'm33w.lore.journal.create': 'Added the lore entry «{title}»',
        'm33w.lore.journal.update': 'Changed the lore entry «{title}»',
        'm33w.lore.typedNone': 'The Book roles module is off: the type is not kept, only the text.',
        'm33w.lore.untitled': 'untitled',

        'm33w.err.passportUnavailable': 'The lorebook passports module is off.',
        'm33w.err.passportNoRegistry':
            'Passports of base books live in the Maestro registry: switch on the Book roles module.',
        'm33w.err.passportInvalid': 'This is not a passport.',
        'm33w.err.passportIssues': 'The passport cannot be saved: {issues}',
        'm33w.passport.issue.notEnglish': '{field}: «{tag}» is not an English tag',
        'm33w.passport.issue.upperCase': '{field}: «{tag}» has capital letters',
        'm33w.passport.issue.anatomy': '{field}: «{tag}» belongs to the NSFW layer',
        'm33w.passport.fixed': 'Tags were tidied: lower case, no underscores, explicit anatomy moved to NSFW.',
        'm33w.passport.empty': 'The passport is empty: there is nothing to draw.',
        'm33w.passport.summary': 'Passport of «{entry}» in «{book}»',
    },
    ru: {
        'm33w.on': 'вкл',
        'm33w.off': 'выкл',
        'm33w.state.on': 'включён',
        'm33w.state.off': 'выключен',
        'm33w.stateF.on': 'включена',
        'm33w.stateF.off': 'выключена',

        'm33w.type.string': 'текст',
        'm33w.type.boolean': 'true или false',
        'm33w.type.number': 'число',
        'm33w.type.integer': 'целое число',
        'm33w.type.list': 'список текстов',
        'm33w.type.object': 'объект JSON',

        'm33w.err.argMissing': 'Не хватает параметра «{name}».',
        'm33w.err.argType': 'Параметр «{name}»: ожидается {expected}.',
        'm33w.err.argEmpty': 'Параметр «{name}» пустой.',
        'm33w.err.argTooLong': 'Параметр «{name}» длиннее {max} символов.',
        'm33w.err.argRange': 'Параметр «{name}» должен быть от {min} до {max}.',
        'm33w.err.argEnum': 'Параметр «{name}» — одно из: {options}.',
        'm33w.err.argTooMany': 'В «{name}» больше {max} элементов.',
        'm33w.err.argOneOf': 'Нужно что-то одно: «{a}» или «{b}».',
        'm33w.err.argNeedOne': 'Нужно указать «{a}» или «{b}».',

        'm33w.target.modules': 'Maestro · модули',
        'm33w.err.moduleUnknown': 'Модуля «{module}» нет. Есть: {list}.',
        'm33w.err.moduleSelf': 'Свой модуль ассистент не переключает.',
        'm33w.err.moduleAlready': '«{title}» и так {state}.',
        'm33w.err.moduleMissing': '«{title}» не запустится: в этом SillyTavern нет {caps}.',
        'm33w.module.summary.on': '{title} ({id}): включить',
        'm33w.module.summary.off': '{title} ({id}): выключить',
        'm33w.module.journal.on': 'Включил модуль «{title}»',
        'm33w.module.journal.off': 'Выключил модуль «{title}»',

        'm33w.target.autonomy': 'Maestro · автономия',
        'm33w.err.autonomyKind': 'Неизвестный вид действий «{kind}». Известные: {list}.',
        'm33w.err.autonomyNeverAuto': '«{kind}» никогда не делается само.',
        'm33w.err.autonomyAlready': 'У «{kind}» и так «{level}».',
        'm33w.autonomy.none': 'пока нет',
        'm33w.autonomy.summary': 'Автономия «{kind}»: {from} → {to}',
        'm33w.autonomy.newKind': 'Такие действия ещё не встречались.',
        'm33w.autonomy.journal': 'Поставил «{level}» для «{kind}»',
        'm33w.autonomy.journalUnnamed': 'Поставил «{level}» для одного из видов действий',
        'm33w.level.auto': 'Само',
        'm33w.level.notify': 'Уведомить',
        'm33w.level.inbox': 'Входящие',
        'm33w.level.ask': 'Спросить',
        'm33w.level.off': 'Выкл',
        'm33w.level.default': 'Как задано в модуле',

        'm33w.target.mechanic': 'Механики · «{name}»',
        'm33w.target.mechanicChat': 'Механики · этот чат',
        'm33w.err.mechanicUnavailable': 'Модуль «Механики» выключен.',
        'm33w.err.mechanicTemplate': 'Шаблона «{template}» нет. Есть: {list}.',
        'm33w.err.mechanicInvalid': 'Механику нельзя сохранить: {issues}',
        'm33w.err.mechanicNotDef': 'Это не описание механики (нужно хотя бы название).',
        'm33w.err.mechanicUnknown': 'Здесь нет механики «{id}». Есть: {list}.',
        'm33w.err.mechanicNoChat': 'Сначала открой чат.',
        'm33w.err.mechanicAlready': '«{name}» и так {state} в этом чате.',
        'm33w.err.mechanicScope': 'Область «{scope}» здесь невозможна (нет одного персонажа или нет чата).',
        'm33w.mechanic.summary.create':
            'Новая механика «{name}»: атрибутов — {attributes}, проверок — {checks}, действует {scope}',
        'm33w.mechanic.summary.update': 'Механика «{name}»: изменения',
        'm33w.mechanic.summary.chatOn': 'Механика «{name}» в этом чате: включить',
        'm33w.mechanic.summary.chatOff': 'Механика «{name}» в этом чате: выключить',
        'm33w.mechanic.journal.chatOn': 'Включил механику «{name}» в этом чате',
        'm33w.mechanic.journal.chatOff': 'Выключил механику «{name}» в этом чате',
        'm33w.mechanic.scope.card': 'у этого персонажа',
        'm33w.mechanic.scope.chat': 'в этом чате',
        'm33w.mechanic.scope.global': 'везде',

        'm33w.target.regex': 'Регексы ST · общие',
        'm33w.err.regexUnavailable': 'Регексы SillyTavern недоступны.',
        'm33w.err.regexCompile': 'Регекс не собирается: {error}',
        'm33w.err.regexFlags': 'Флаги «{flags}» не подходят: SillyTavern понимает g, i, m, s, u (каждый по разу).',
        'm33w.err.regexFlagsConflict': 'Флаги указаны дважды и расходятся: «{a}» в find, «{b}» в flags.',
        'm33w.err.regexDepth': 'minDepth больше maxDepth.',
        'm33w.err.regexNoMatch':
            'Проверка не прошла: регекс не меняет ни один пример. Дай пример, который он должен менять, или поправь регекс.',
        'm33w.err.regexExpected': 'Проверка не прошла на примере {index}: ждали «{expected}», вышло «{actual}».',
        'm33w.err.regexExpectedCount': 'В «expected» нужен один текст на каждый пример ({count}).',
        'm33w.err.regexUnknown': 'Общего регекса «{id}» нет.',
        'm33w.err.regexAmbiguous': 'Общих регексов «{id}» несколько — укажи id.',
        'm33w.err.regexForeign': 'Здесь переключаются только общие регексы: «{id}» принадлежит карточке или пресету.',
        'm33w.err.regexAlready': 'Регекс «{name}» и так {state}.',
        'm33w.err.regexGone': 'Регекса «{name}» уже нет.',
        'm33w.regex.summary.create':
            'Новый регекс «{name}» ({where}; {mode}); проверка: изменено примеров — {changed} из {total}',
        'm33w.regex.summary.on': 'Регекс «{name}»: включить',
        'm33w.regex.summary.off': 'Регекс «{name}»: выключить',
        'm33w.regex.journal.create': 'Добавил регекс «{name}»',
        'm33w.regex.journal.on': 'Включил регекс «{name}»',
        'm33w.regex.journal.off': 'Выключил регекс «{name}»',
        'm33w.regex.place.user_input': 'ввод пользователя',
        'm33w.regex.place.ai_output': 'ответы ИИ',
        'm33w.regex.place.slash_command': 'слэш-команды',
        'm33w.regex.place.world_info': 'лор',
        'm33w.regex.place.reasoning': 'размышления',
        'm33w.regex.mode.display': 'только показ',
        'm33w.regex.mode.prompt': 'только промпт',
        'm33w.regex.mode.displayAndPrompt': 'показ и промпт',
        'm33w.regex.mode.edit': 'меняет сам текст сообщения',
        'm33w.regex.warn.breaksJson': 'Ломает JSON трекера DES в ответах.',
        'm33w.regex.warn.stripsTags': 'Убирает теги BunnyMo.',
        'm33w.regex.warn.breaksMarkers': 'Портит маркеры картинок NAI Studio.',
        'm33w.regex.warn.worldInfoNotPrompt': 'На лор регекс действует только в режиме «только промпт».',
        'm33w.regex.warn.matchesEmpty': 'Совпадает с пустым текстом: замена встанет между символами.',
        'm33w.regex.warn.macros': 'Макросы ({{…}}) в проверке не подставлялись.',
        'm33w.regex.warn.sameName': 'Общий регекс с таким именем уже есть.',
        'm33w.regex.warn.extensionOff': 'Расширение Regex в SillyTavern выключено: ни один регекс не работает.',

        'm33w.target.preset': 'Пресет «{preset}» · твой слой',
        'm33w.target.presetBlock': 'Пресет «{preset}» · твой слой · «{name}»',
        'm33w.err.presetUnavailable': 'Пресет-студия выключена или без слоя.',
        'm33w.err.presetNone': 'Не выбран пресет Chat Completion.',
        'm33w.err.presetNoBlock': 'В пресете «{preset}» нет блока «{block}».',
        'm33w.err.presetAmbiguous': 'Блоков «{block}» несколько — укажи идентификатор.',
        'm33w.err.presetNeedAnchor': 'Укажи блок, рядом с которым ставить новый («{place}»).',
        'm33w.err.presetMarker': '«{name}» заполняет сам SillyTavern — его тексту условие не поставить.',
        'm33w.err.presetOutside':
            '«{name}» нет ни в сохранённом пресете, ни в твоём слое (сделан вне студии и не сохранён).',
        'm33w.err.presetFlagInvalid': '«{flag}» не годится в имя флага.',
        'm33w.err.presetFlagUnknown':
            'Неизвестный флаг «{flag}»: возьми из каталога или имя maestro_…. Каталог: {list}.',
        'm33w.err.presetFlagNeeded': 'Для режима «{mode}» нужен флаг.',
        'm33w.err.presetBlocked': 'В тексте блока лишние теги {{if}}/{{else}}/{{/if}} — сначала поправь их.',
        'm33w.err.presetAlready': 'У «{name}» уже такое условие.',
        'm33w.err.presetChanged': 'Пресет сменился после плана («{preset}» → «{current}»).',
        'm33w.err.presetBlockChanged': 'Блок «{name}» изменился после плана — спроси ещё раз.',
        'm33w.preset.summary.add': 'Новый блок «{name}» ({role}) {place}{condition}',
        'm33w.preset.place.start': 'в начале',
        'm33w.preset.place.end': 'в конце',
        'm33w.preset.place.after': 'после «{block}»',
        'm33w.preset.place.before': 'перед «{block}»',
        'm33w.preset.place.depth': 'в чате на глубине {depth}',
        'm33w.preset.cond.only': ', только при {flag}',
        'm33w.preset.cond.except': ', кроме {flag}',
        'm33w.preset.summary.only': 'Блок «{name}»: только при {flag}',
        'm33w.preset.summary.except': 'Блок «{name}»: кроме {flag}',
        'm33w.preset.summary.always': 'Блок «{name}»: всегда (без условия)',
        'm33w.preset.warn.flagNotInCatalogue':
            'Флаг «{flag}» пока никто не ставит: блок «только при» будет молчать, а «кроме» — уходить всегда, пока флаг не начнут ставить.',
        'm33w.preset.warn.macroEngine': 'Новый движок макросов SillyTavern не включён: {{if}} уйдёт модели текстом.',
        'm33w.preset.warn.disabled': 'Блок добавляется выключенным.',

        'm33w.target.loreNew': 'Книга «{book}» · новая запись',
        'm33w.target.loreEntry': 'Книга «{book}» · запись {uid}',
        'm33w.target.passport': 'Книга «{book}» · запись {uid} · паспорт',
        'm33w.err.loreUnavailable': 'Лор-студия выключена.',
        'm33w.err.loreNoBook': 'Книги «{book}» нет.',
        'm33w.err.loreAmbiguous': 'Книг «{book}» несколько — укажи точное название.',
        'm33w.err.loreBunnyMo': '«{book}» — книга BunnyMo: её файлы не меняются никогда (P13).',
        'm33w.err.loreReadOnly': '«{book}» только для чтения.',
        'm33w.err.loreNoEntry': 'В «{book}» нет записи {uid}.',
        'm33w.err.loreBadType': 'Неизвестный тип записи «{type}». Есть: {list}.',
        'm33w.err.loreBadField': 'У типа «{type}» нет поля «{field}». Есть: {list}.',
        'm33w.err.loreNoContent': 'У записи нет текста: дай «content» или поля её типа.',
        'm33w.err.loreNoKeys': 'Записи нужны ключи (или constant: true).',
        'm33w.err.loreTypeNeeded': 'У записи нет типа: укажи «type» вместе с полями.',
        'm33w.err.loreNothing': 'Ничего не меняется.',
        'm33w.lore.summary.create': 'Новая запись «{title}» в «{book}»',
        'm33w.lore.summary.update': 'Запись «{title}» в «{book}»: {fields}',
        'm33w.lore.journal.create': 'Добавил в лор запись «{title}»',
        'm33w.lore.journal.update': 'Поправил запись лора «{title}»',
        'm33w.lore.typedNone': 'Модуль «Роли книг» выключен: тип не сохранится, только текст.',
        'm33w.lore.untitled': 'без названия',

        'm33w.err.passportUnavailable': 'Модуль паспортов выключен.',
        'm33w.err.passportNoRegistry': 'Паспорта базовых книг хранятся в реестре Maestro — включи модуль «Роли книг».',
        'm33w.err.passportInvalid': 'Это не паспорт.',
        'm33w.err.passportIssues': 'Паспорт нельзя сохранить: {issues}',
        'm33w.passport.issue.notEnglish': '{field}: «{tag}» — не английский тег',
        'm33w.passport.issue.upperCase': '{field}: в «{tag}» заглавные буквы',
        'm33w.passport.issue.anatomy': '{field}: «{tag}» — это для слоя NSFW',
        'm33w.passport.fixed': 'Теги приведены в порядок: строчные, без подчёркиваний, откровенная анатомия — в NSFW.',
        'm33w.passport.empty': 'Паспорт пустой — рисовать нечего.',
        'm33w.passport.summary': 'Паспорт записи «{entry}» в «{book}»',
    },
};

export type Say = (key: string, params?: Record<string, string | number>) => string;

/** Translator for a locale (falls back to English, then the key); `{name}` placeholders are filled from params. */
export function sayer(locale: 'en' | 'ru'): Say {
    const primary = locale === 'ru' ? WRITE_STRINGS.ru : WRITE_STRINGS.en;
    return (key, params) => {
        const text = primary[key] ?? WRITE_STRINGS.en[key] ?? key;
        if (!params) return text;
        return text.replace(/\{(\w+)\}/g, (match, name: string) => (name in params ? String(params[name]) : match));
    };
}
