// Strings of M12 «Контроль качества ответа» (`m12.*`, autonomy kinds `kind.quality.*`, journal targets
// `target.quality-*`). Russian is the primary UI language; the user is addressed as «ты» (masculine).
import type { I18nParts } from '../../shared/contracts';

export const QUALITY_STRINGS: I18nParts = {
    en: {
        'm12.title': 'Reply quality',
        'm12.tab': 'Quality',
        'm12.profileTask': 'Reply quality judge',
        'm12.hint':
            'Every reply is checked right after it arrives, before NAI Studio draws: free rules first, the cheap model only when a rule is not sure. Sheets are skipped. What happens to each kind of defect is set below.',
        'm12.economy': '«Economy» mode: the judge is off and every defect only gets a notice.',
        'm12.nai.on': 'NAI Studio waits for the check before drawing.',
        'm12.nai.off': 'NAI Studio does not wait for the check (not installed, off, or older than 0.11).',
        'm12.noChat': 'No chat is open.',
        'm12.group': 'Group chats are not supported: Maestro sleeps here.',

        'm12.verdicts': 'Last checks',
        'm12.verdicts.empty': 'No reply checked in this chat yet.',
        'm12.verdict.title': 'Message #{index}, swipe {swipe}',
        'm12.verdict.ok': 'all good',
        'm12.verdict.clean': 'No defects.',
        'm12.verdict.judged': 'judge asked ({cost})',
        'm12.verdict.jump': 'Show',
        'm12.verdict.recheck': 'Check again',
        'm12.action.none': 'defects left as they are',
        'm12.action.cleaned': 'cleaned',
        'm12.action.continued': 'asked to continue',
        'm12.action.swiped': 'redone with a swipe',
        'm12.action.notified': 'waiting for you',
        'm12.action.repaired': 'tracker repaired',
        'm12.invalidated.swiped': 'swiped away',
        'm12.invalidated.deleted': 'deleted',
        'm12.invalidated.edited': 'edited after the check',
        'm12.status.cleaned': 'cleaned',
        'm12.status.continued': 'continuing',
        'm12.status.swiped': 'redoing',
        'm12.status.repaired': 'repaired',
        'm12.status.delegated': 'the Medic repairs it',
        'm12.status.notified': 'notice',
        'm12.status.dismissed': 'not a defect',
        'm12.defect.suspected': 'possible',
        'm12.defect.byJudge': 'judge',

        'm12.badge.text': 'Defect in this reply: {kinds}',
        'm12.badge.possible': 'Possible defect: {kinds}',
        'm12.badge.redo': 'Redo',
        'm12.badge.falseText': 'False alarm?',
        'm12.badge.dismiss': 'Not a defect',
        'm12.redo.notLast': 'Only the last reply can be redone with a swipe.',
        'm12.redo.failed': 'SillyTavern is busy: the swipe did not start. Try again in a moment.',
        'm12.journal.clean': 'Cleaning reply #{index}: {kinds}',
        'm12.journal.swipe': 'Redoing reply #{index} with a swipe: {kinds}',
        'm12.journal.continue': 'Continuing the cut-off reply #{index}',
        'm12.applied.clean': 'Cleaned reply #{index}: {kinds}.',
        'm12.applied.swipe': 'Asked the model to rewrite reply #{index}: {kinds}.',
        'm12.applied.continue': 'Reply #{index} was cut off: asked the model to finish it.',
        'm12.applied.many.one': 'Fixed defects in replies: {count} fix',
        'm12.applied.many.few': 'Fixed defects in replies: {count} fixes',
        'm12.applied.many.many': 'Fixed defects in replies: {count} fixes',
        'target.quality-text': 'Reply',
        'target.quality-swipe': 'Redo with a swipe',
        'target.quality-continue': 'Continuation of a reply',
        'm12.target.text': 'Reply text',

        'm12.actions': 'What to do with defects',
        'm12.actions.hint':
            '«Auto» cleans, continues or swipes once per turn with an exact instruction; «Notify» puts «Redo» and «Not a defect» under the reply. Each automatic swipe is a full generation and costs like one. After several confirmed notices Maestro may offer to switch a kind to «Auto»; the content boundary always stays a notice.',
        'm12.actionSetting.off': 'Off',
        'm12.actionSetting.auto': 'Auto',
        'm12.actionSetting.notify': 'Notify',
        'm12.kindHint.junk':
            'Service tokens, code or leaked HTML (the DES tracker block and NAI markers are fine). Auto: cleaned.',
        'm12.kindHint.truncated': 'The reply stops mid-sentence or hit the token limit. Auto: /continue.',
        'm12.kindHint.missingTracker': 'No DES tracker JSON in «together» mode. Auto: repaired by the Medic (M3).',
        'm12.kindHint.language': 'The reply drifts into another language, calques and stock phrases. Auto: swipe.',
        'm12.kindHint.userSpeech': 'Lines or actions written for you. Auto: swipe.',
        'm12.kindHint.refusal': 'Refusals and out-of-character remarks. Auto: swipe.',
        'm12.kindHint.moralizing': 'Lectures, warnings, disclaimers. Auto: swipe.',
        'm12.kindHint.softening':
            'A softened or skipped scene, endless «are you sure?», everyone too agreeable. Auto: swipe.',
        'm12.kindHint.boundary': 'Your content boundary (rules below). Never automatic.',
        'm12.kindHint.repetition': 'Phrases and beats repeated from earlier replies. Auto: swipe.',
        'm12.kindHint.canonContradiction': 'Contradicts the chat canon. Auto: swipe.',
        'm12.judge': 'Ask the judge when a rule is not sure',
        'm12.judge.hint':
            'One quick request to the cheap model (profile «Reply quality judge»), only in the leading tab and under the daily background limit. Never in «Economy».',
        'm12.cutoff': 'Stop the stream on service tokens',
        'm12.cutoff.hint':
            'A known junk token in the stream (<｜begin▁of▁sentence｜>, <|im_start|>, <|eot_id|>…) stops the generation and swipes once. Works while «Service junk» is set to «Auto».',

        'm12.stats': 'Statistics',
        'm12.stats.kind': 'Defect',
        'm12.stats.detected': 'Found',
        'm12.stats.falsePositives': 'False alarms',
        'm12.stats.rate': 'False alarm rate',
        'm12.stats.auto': 'Fixed automatically',
        'm12.stats.hint':
            'A false alarm is «Not a defect» on a notice or an undone automatic fix. Low rates are the reason to switch a kind to «Auto».',

        'm12.boundary': 'Content boundary',
        'm12.boundary.hint':
            'Rules, not code: one pattern per line — a word or a regular expression (case-insensitive, Unicode), in English and Russian. `both:<A>&&<B>` hits only when both parts are in the same reply. One hit is a suspicion for the judge, two hits are a defect. Use the test mode below to try the rules on a text.',
        'm12.boundary.empty': 'No rules. The default rule forbids any sexual content with minors.',
        'm12.boundary.ruleTitle': 'Title',
        'm12.boundary.patterns': 'Patterns, one per line',
        'm12.boundary.enabled': 'On',
        'm12.boundary.remove': 'Remove',
        'm12.boundary.add': 'Add a rule',
        'm12.boundary.reset': 'Back to the default',
        'm12.boundary.save': 'Save the rules',
        'm12.boundary.saved': 'Boundary rules saved.',
        'm12.boundary.invalid': 'Some rule has no patterns or a broken pattern: fix it before saving.',
        'm12.boundary.badPattern': 'Not a valid pattern: {pattern}',

        'm12.test': 'Test mode',
        'm12.test.hint':
            'Paste a text: the free checks run over it as if it were the next reply of this chat, with the rules above (saved or not). Nothing is changed and the judge is not asked.',
        'm12.test.run': 'Check the text',
        'm12.test.clean': 'No defects found.',
        'm12.test.judge': 'the judge would be asked',

        'm12.kind.language': 'wrong language',
        'm12.kind.userSpeech': 'speaking for you',
        'm12.kind.refusal': 'refusal',
        'm12.kind.moralizing': 'lecturing',
        'm12.kind.softening': 'softened scene',
        'm12.kind.repetition': 'repetition',
        'm12.kind.truncated': 'cut off',
        'm12.kind.junk': 'service junk',
        'm12.kind.missingTracker': 'no DES tracker',
        'm12.kind.canonContradiction': 'contradicts the canon',
        'm12.kind.boundary': 'content boundary',

        'kind.quality.language': 'Wrong language in a reply',
        'kind.quality.userSpeech': 'Lines written for you',
        'kind.quality.refusal': 'Refusal or out-of-character remark',
        'kind.quality.moralizing': 'Lecturing in a reply',
        'kind.quality.softening': 'Softened scene',
        'kind.quality.repetition': 'Repetition in a reply',
        'kind.quality.truncated': 'Cut-off reply',
        'kind.quality.junk': 'Junk in a reply',
        'kind.quality.missingTracker': 'Reply without a DES tracker',
        'kind.quality.canonContradiction': 'Contradiction with the chat canon',
        'kind.quality.boundary': 'Crossed content boundary',
    },
    ru: {
        'm12.title': 'Качество ответа',
        'm12.tab': 'Качество',
        'm12.profileTask': 'Судья качества ответа',
        'm12.hint':
            'Каждый ответ проверяется сразу, как пришёл, — до того, как NAI Studio начнёт рисовать: сначала бесплатные правила, дешёвая модель — только если правило не уверено. Листы не проверяются. Что делать с каждым видом брака, настраивается ниже.',
        'm12.economy': 'Режим «Экономный»: судья выключен, о любом браке — только уведомление.',
        'm12.nai.on': 'NAI Studio ждёт проверки, прежде чем рисовать.',
        'm12.nai.off': 'NAI Studio не ждёт проверки (не установлен, выключен или старше 0.11).',
        'm12.noChat': 'Чат не открыт.',
        'm12.group': 'Групповые чаты не поддерживаются: здесь Maestro спит.',

        'm12.verdicts': 'Последние проверки',
        'm12.verdicts.empty': 'В этом чате ещё ни один ответ не проверен.',
        'm12.verdict.title': 'Сообщение №{index}, свайп {swipe}',
        'm12.verdict.ok': 'всё хорошо',
        'm12.verdict.clean': 'Брака нет.',
        'm12.verdict.judged': 'спросили судью ({cost})',
        'm12.verdict.jump': 'Показать',
        'm12.verdict.recheck': 'Проверить ещё раз',
        'm12.action.none': 'брак оставлен как есть',
        'm12.action.cleaned': 'очищено',
        'm12.action.continued': 'попросили продолжить',
        'm12.action.swiped': 'переделывается свайпом',
        'm12.action.notified': 'ждёт твоего решения',
        'm12.action.repaired': 'трекер починен',
        'm12.invalidated.swiped': 'свайпнуто',
        'm12.invalidated.deleted': 'удалено',
        'm12.invalidated.edited': 'исправлено после проверки',
        'm12.status.cleaned': 'очищено',
        'm12.status.continued': 'продолжается',
        'm12.status.swiped': 'переделывается',
        'm12.status.repaired': 'починено',
        'm12.status.delegated': 'чинит Медик',
        'm12.status.notified': 'уведомление',
        'm12.status.dismissed': 'не брак',
        'm12.defect.suspected': 'возможно',
        'm12.defect.byJudge': 'судья',

        'm12.badge.text': 'В ответе брак: {kinds}',
        'm12.badge.possible': 'Возможно, брак: {kinds}',
        'm12.badge.redo': 'Переделать',
        'm12.badge.falseText': 'Ложная тревога?',
        'm12.badge.dismiss': 'Не брак',
        'm12.redo.notLast': 'Свайпом можно переделать только последний ответ.',
        'm12.redo.failed': 'SillyTavern занят: свайп не начался. Попробуй ещё раз чуть позже.',
        'm12.journal.clean': 'Чистка ответа №{index}: {kinds}',
        'm12.journal.swipe': 'Переделка ответа №{index} свайпом: {kinds}',
        'm12.journal.continue': 'Продолжение оборванного ответа №{index}',
        'm12.applied.clean': 'Почистил ответ №{index}: {kinds}.',
        'm12.applied.swipe': 'Попросил модель переписать ответ №{index}: {kinds}.',
        'm12.applied.continue': 'Ответ №{index} оборвался — попросил модель его дописать.',
        'm12.applied.many.one': 'Исправил брак в ответах: {count} правка',
        'm12.applied.many.few': 'Исправил брак в ответах: {count} правки',
        'm12.applied.many.many': 'Исправил брак в ответах: {count} правок',
        'target.quality-text': 'Ответ',
        'target.quality-swipe': 'Переделка свайпом',
        'target.quality-continue': 'Продолжение ответа',
        'm12.target.text': 'Текст ответа',

        'm12.actions': 'Что делать с браком',
        'm12.actions.hint':
            '«Само» — очистить, попросить продолжить или один раз за ход свайпнуть с точной инструкцией; «Уведомить» — под ответом появятся «Переделать» и «Не брак». Каждый авто-свайп — полная генерация и стоит как она. Когда несколько уведомлений подряд подтвердятся, Maestro предложит перевести вид в «Само»; граница контента всегда остаётся уведомлением.',
        'm12.actionSetting.off': 'Выкл',
        'm12.actionSetting.auto': 'Само',
        'm12.actionSetting.notify': 'Уведомить',
        'm12.kindHint.junk':
            'Служебные токены, код, протёкший HTML (блок трекера DES и маркеры NAI — норма). Само: очистка.',
        'm12.kindHint.truncated': 'Ответ оборвался на полуслове или упёрся в лимит токенов. Само: /continue.',
        'm12.kindHint.missingTracker': 'Нет JSON трекера DES в режиме «вместе». Само: ремонт через Медика (M3).',
        'm12.kindHint.language': 'Уход в другой язык, кальки и штампы. Само: свайп.',
        'm12.kindHint.userSpeech': 'Реплики и действия за тебя. Само: свайп.',
        'm12.kindHint.refusal': 'Отказы и оговорки вне роли. Само: свайп.',
        'm12.kindHint.moralizing': 'Нравоучения, предупреждения, оговорки. Само: свайп.',
        'm12.kindHint.softening':
            'Смягчённая или пропущенная сцена, бесконечные «ты уверен?», все слишком сговорчивы. Само: свайп.',
        'm12.kindHint.boundary': 'Твоя граница контента (правила ниже). Никогда не «Само».',
        'm12.kindHint.repetition': 'Повторы фраз и ходов из прошлых ответов. Само: свайп.',
        'm12.kindHint.canonContradiction': 'Противоречие канону чата. Само: свайп.',
        'm12.judge': 'Спрашивать судью, если правило не уверено',
        'm12.judge.hint':
            'Один быстрый запрос к дешёвой модели (профиль «Судья качества ответа»), только в ведущей вкладке и в пределах дневного лимита фоновых задач. В «Экономном» — никогда.',
        'm12.cutoff': 'Обрывать поток на служебных токенах',
        'm12.cutoff.hint':
            'Известный мусор в потоке (<｜begin▁of▁sentence｜>, <|im_start|>, <|eot_id|>…) останавливает генерацию, и ответ один раз свайпается. Работает, пока у «Служебного мусора» стоит «Само».',

        'm12.stats': 'Статистика',
        'm12.stats.kind': 'Брак',
        'm12.stats.detected': 'Найдено',
        'm12.stats.falsePositives': 'Ложные',
        'm12.stats.rate': 'Доля ложных',
        'm12.stats.auto': 'Исправлено само',
        'm12.stats.hint':
            'Ложное срабатывание — «Не брак» на уведомлении или отменённое автоматическое исправление. По низкой доле ложных вид брака можно переводить в «Само».',

        'm12.boundary': 'Граница контента',
        'm12.boundary.hint':
            'Правила, а не код: по шаблону на строку — слово или регулярное выражение (без учёта регистра, Unicode), на английском и русском. `both:<A>&&<B>` срабатывает, только если обе части есть в одном ответе. Одно совпадение — подозрение для судьи, два — брак. Проверить правила на тексте можно в тестовом режиме ниже.',
        'm12.boundary.empty':
            'Правил нет. Правило по умолчанию запрещает любой сексуальный контент с несовершеннолетними.',
        'm12.boundary.ruleTitle': 'Название',
        'm12.boundary.patterns': 'Шаблоны, по одному на строку',
        'm12.boundary.enabled': 'Вкл',
        'm12.boundary.remove': 'Удалить',
        'm12.boundary.add': 'Добавить правило',
        'm12.boundary.reset': 'Вернуть по умолчанию',
        'm12.boundary.save': 'Сохранить правила',
        'm12.boundary.saved': 'Правила границы сохранены.',
        'm12.boundary.invalid': 'В каком-то правиле нет шаблонов или есть сломанный шаблон: исправь перед сохранением.',
        'm12.boundary.badPattern': 'Неверный шаблон: {pattern}',

        'm12.test': 'Тестовый режим',
        'm12.test.hint':
            'Вставь текст: бесплатные проверки пройдут по нему, как по следующему ответу этого чата, с правилами выше (даже несохранёнными). Ничего не меняется, судью не спрашивают.',
        'm12.test.run': 'Проверить текст',
        'm12.test.clean': 'Брака не найдено.',
        'm12.test.judge': 'спросили бы судью',

        'm12.kind.language': 'чужой язык',
        'm12.kind.userSpeech': 'реплики за тебя',
        'm12.kind.refusal': 'отказ',
        'm12.kind.moralizing': 'нравоучения',
        'm12.kind.softening': 'смягчённая сцена',
        'm12.kind.repetition': 'повторы',
        'm12.kind.truncated': 'обрыв',
        'm12.kind.junk': 'служебный мусор',
        'm12.kind.missingTracker': 'нет трекера DES',
        'm12.kind.canonContradiction': 'противоречие канону',
        'm12.kind.boundary': 'граница контента',

        'kind.quality.language': 'Чужой язык в ответе',
        'kind.quality.userSpeech': 'Реплики за тебя',
        'kind.quality.refusal': 'Отказ или выход из роли',
        'kind.quality.moralizing': 'Нравоучения в ответе',
        'kind.quality.softening': 'Смягчённая сцена',
        'kind.quality.repetition': 'Повторы в ответе',
        'kind.quality.truncated': 'Оборванный ответ',
        'kind.quality.junk': 'Мусор в ответе',
        'kind.quality.missingTracker': 'Ответ без трекера DES',
        'kind.quality.canonContradiction': 'Противоречие канону чата',
        'kind.quality.boundary': 'Нарушение границы контента',
    },
};
