// Strings of M35 «Режим BunnyMo» (`m35b.*`). Russian is the primary UI language; the user is addressed as «ты».
import type { I18nParts } from '../../shared/contracts';

export const BUNNYMO_MODE_STRINGS: I18nParts = {
    en: {
        'm35b.title': 'BunnyMo mode',
        'm35b.tab': 'BunnyMo',
        'm35b.nav': 'BunnyMo mode sections',
        'm35b.view.dictionary': 'Tag dictionary',
        'm35b.view.packs': 'Packs',
        'm35b.view.integrity': 'Integrity',
        'm35b.view.sheets': 'Sheets',
        'm35b.view.edits': 'Runtime fixes',
        'm35b.loading': 'Reading lorebooks…',
        'm35b.refresh': 'Refresh',
        'm35b.health.title': 'BunnyMo integrity',
        'm35b.health.ok': 'BunnyMo books are in order.',
        'm35b.health.found': 'Problems: {count}. {first}',
        'm35b.slash.help':
            'Opens the BunnyMo mode: a tag (<SPECIES:ELF>) opens the dictionary, a character name opens the sheet editor.',
        'm35b.slash.value': 'tag or character name',

        'm35b.dict.search': 'Search tags, entries and characters',
        'm35b.dict.category': 'Category',
        'm35b.dict.allCategories': 'All categories',
        'm35b.dict.flags': 'Flags without a category',
        'm35b.dict.summary':
            '{tags} tags in {categories} categories · conflicts: {conflicts} · without a pack: {orphans}',
        'm35b.dict.none': 'Nothing found.',
        'm35b.dict.empty': 'No BunnyMo books found: the dictionary is empty.',
        'm35b.dict.more': 'Show {count} more',
        'm35b.dict.pulls': 'Pack entries',
        'm35b.dict.noEntries': 'No loaded pack has an entry for this tag.',
        'm35b.dict.infoTag': 'Informational tag: only the model and CarrotKernel read it, no pack entry is needed.',
        'm35b.dict.usedBy': 'Archives using it',
        'm35b.dict.unused': 'No archive uses this tag.',
        'm35b.dict.entry': '«{book}» · #{uid}',
        'm35b.dict.chars': '{chars} chars',
        'm35b.dict.kind.pull': 'pulls',
        'm35b.dict.kind.info': 'info',
        'm35b.dict.badge.conflict': 'version conflict',
        'm35b.dict.badge.duplicate': 'duplicate',
        'm35b.dict.badge.orphan': 'no pack',
        'm35b.dict.badge.info': 'informational',
        'm35b.dict.conflictHint':
            'This tag has different texts in several packs. Which version stays is decided by the rule «Pack version conflicts».',
        'm35b.dict.duplicateHint':
            'The same text in several packs: the rule «Byte-identical pack duplicates» keeps one copy.',
        'm35b.dict.openSheet': 'Open the sheet of {name}',

        'm35b.packs.allInChat': 'All packs in this chat',
        'm35b.packs.allHint':
            'Off: only the checked packs work in this chat, the others are left out of the scan. Files and global switches stay as they are.',
        'm35b.packs.noChat': 'Open a chat to choose packs for it.',
        'm35b.packs.inChat': 'In this chat',
        'm35b.packs.active': 'active',
        'm35b.packs.inactive': 'not active',
        'm35b.packs.edition.shared': 'one file',
        'm35b.packs.edition.split': 'separate edition',
        'm35b.packs.entries': 'entries: {count}',
        'm35b.packs.version': 'v{version}',
        'm35b.packs.none': 'No BunnyMo packs found.',
        'm35b.packs.core': 'Core «{book}» · V{version}',
        'm35b.packs.coreInactive': 'not active',
        'm35b.packs.compare': 'Compare with a file',
        'm35b.packs.conflicts': 'Version conflicts',
        'm35b.packs.conflict.chosen': '{books}: «{choice}» stays',
        'm35b.packs.conflict.every': '{books}: every version stays',
        'm35b.packs.conflict.open': '{books}: not decided yet',
        'm35b.packs.diff.title': '«{book}» compared with «{file}»',
        'm35b.packs.diff.added': 'New in the file ({count})',
        'm35b.packs.diff.removed': 'Only in the book ({count})',
        'm35b.packs.diff.changed': 'Changed ({count})',
        'm35b.packs.diff.same': 'The file holds the same entries.',
        'm35b.packs.diff.note':
            'Nothing has been written. To move to the new version, import the file as a new book in the Lore Studio and choose it for the chat here.',
        'm35b.packs.diff.close': 'Close the comparison',

        'm35b.integrity.ok': 'Everything is in order.',
        'm35b.integrity.coreMissing.inactive':
            'Active packs: {count}, but the core «{book}» is not active: sheet commands and Master entries do not work.',
        'm35b.integrity.coreMissing.absent': 'Active packs: {count}, but there is no BunnyMo core.',
        'm35b.integrity.coreVersion.several': 'Several BunnyMo cores are active at once: {books}. Keep one.',
        'm35b.integrity.coreVersion.old':
            'The core «{book}» looks like version {version}; Maestro is checked against V{expected}.',
        'm35b.integrity.packAsRepo.repo':
            '«{book}» is a BunnyMo book marked as a CarrotKernel Character Repo: CK reads its templates as characters. Unmark it in CarrotKernel.',
        'm35b.integrity.ckWrapRewrite.backup':
            'Entries of «{book}» rewritten with the CarrotKernel tag wrapper: {count} (compared with the .carrot_backup copy).',
        'm35b.integrity.ckWrapRewrite.backupPack':
            'Entries of the BunnyMo pack «{book}» rewritten with the CarrotKernel tag wrapper: {count}. Pack files must stay as shipped: import the original file again.',
        'm35b.integrity.ckWrapRewrite.nested': 'Entries of «{book}» wrapped by CarrotKernel twice: {count}.',
        'm35b.integrity.ckWrapRewrite.nestedPack':
            'Entries of the BunnyMo pack «{book}» wrapped by CarrotKernel twice: {count}. Import the original file again.',
        'm35b.integrity.ckWrapRewrite.pending':
            '«{book}» is a CarrotKernel Tag Library and «BunnyMo tag wrapping» is on: CK will rewrite this file on its next load.',
        'm35b.integrity.ckWrapRewrite.pendingPack':
            'CarrotKernel will rewrite the BunnyMo pack «{book}» on its next load (Tag Library with «BunnyMo tag wrapping» on). Turn the wrapping off in CarrotKernel.',
        'm35b.integrity.ckBackup.copy': 'CarrotKernel backup «{book}» (a copy of «{original}»).',
        'm35b.integrity.ckBackup.orphan': 'CarrotKernel backup «{book}»: its original «{original}» is gone.',
        'm35b.integrity.canonGlobal.global':
            'The chat canon «{book}» is switched on globally; it must work only through Maestro.',
        'm35b.integrity.chatBookGlobal.global':
            'The chat book «{book}» is also switched on globally: it works in every chat.',

        'm35b.sheets.none': 'No character archives found (CarrotKernel repositories or books with <BunnymoTags>).',
        'm35b.sheets.tags': 'tags: {count}',
        'm35b.sheets.back': 'Back to the list',
        'm35b.sheets.noName': '(no name)',
        'm35b.sheets.nameLocked': '<Name:…> never changes: CarrotKernel, RAG and DES find the character by it.',
        'm35b.sheets.tagsTitle': 'Tags',
        'm35b.sheets.noTags': 'The block has no tags yet.',
        'm35b.sheets.category': 'Category',
        'm35b.sheets.value': 'Value',
        'm35b.sheets.add': 'Add',
        'm35b.sheets.replace': 'Replace',
        'm35b.sheets.cancelEdit': 'Cancel',
        'm35b.sheets.remove': 'Remove {tag}',
        'm35b.sheets.edit': 'Edit {tag}',
        'm35b.sheets.mbti': 'MBTI',
        'm35b.sheets.mbtiNone': 'none',
        'm35b.sheets.healthy': 'H — healthy',
        'm35b.sheets.unhealthy': 'U — unhealthy',
        'm35b.sheets.linguistics': 'Linguistics',
        'm35b.sheets.sections': 'Prose sections',
        'm35b.sheets.untitled': 'Text without a title',
        'm35b.sheets.inText': 'Tags in the text',
        'm35b.sheets.check': 'Tag check',
        'm35b.sheets.checkOk': 'Every tag is fine.',
        'm35b.sheets.suggest': 'Use {tag}',
        'm35b.sheets.save': 'Save',
        'm35b.sheets.reset': 'Discard changes',
        'm35b.sheets.saved': 'Saved the character sheet: {name}.',
        'm35b.sheets.unchanged': 'Nothing to save: the sheet has not changed.',
        'm35b.sheets.multiBlock':
            'This entry holds {count} <BunnymoTags> blocks and CarrotKernel reads only the first. Split it into one entry per character before editing.',
        'm35b.sheets.notFound': 'This character sheet is gone.',
        'm35b.sheets.chatSheets': 'Sheets of this character in the chat',
        'm35b.sheets.chatSheet': 'message #{index} · !{command}',
        'm35b.sheets.commands':
            'Sheet commands (!fullsheet, !updatesheet…) go through the sheet scenario: type the command with the name in the chat.',

        'm35b.edits.intro':
            'Technical fixes Maestro applies to BunnyMo books on the fly: only scan copies change, the files stay as shipped. Each rule can be switched off.',
        'm35b.edits.noRules': 'The «Rules» module is off: no runtime fixes are made.',
        'm35b.edits.changes': 'changes in the last scan: {count}',
        'm35b.edits.none': 'no changes in the last scan',
        'm35b.edits.cuts': 'activations cut: {count}',
        'm35b.edits.waiting': 'waits for the first-run wizard',
        'm35b.edits.owner.desru': 'owner: DES-RU',
        'm35b.edits.change': '«{book}» · #{uid} · {field}: {before} → {after}',
        'm35b.edits.selection': 'Packs off in this chat',
        'm35b.edits.selectionItem': '«{book}»: entries left out of the scan: {count}',
        'm35b.edits.selectionNone': 'The per-chat pack choice took nothing out of the last scan.',
        'm35b.edits.selectionAll': 'Use every pack again',
        'm35b.edits.desru':
            'DES-RU (module 5) also patches BunnyMo entries on the fly: Russian detector keys and recursion flags. It is switched in the DES-RU settings.',

        'm35b.reason.malformed': 'malformed: CarrotKernel reads only <KEY:VALUE>',
        'm35b.reason.cyrillic': 'Russian letters: tags stay in English',
        'm35b.reason.placeholder': 'template placeholder',
        'm35b.reason.transitional': 'transition markup (→, %, FADING): write the final value',
        'm35b.reason.duplicate': 'repeated',
        'm35b.reason.unknownCategory': 'unknown category',
        'm35b.reason.unknownValue': 'no pack entry for this value',
        'm35b.reason.noPack': 'the pack of this category is not loaded: the tag pulls nothing',

        'm35b.journal.selectionAll': 'Every BunnyMo pack works in this chat again',
        'm35b.journal.selectionOnly': 'Only the chosen BunnyMo packs work in this chat: {count}',
        'm35b.journal.sheet': 'Character sheet saved: {name}',

        'kind.bunnymo.packSelection': 'BunnyMo packs for a chat',
        'kind.bunnymo.sheet': 'Character sheet edits',
        'target.m35b.packSelection': 'BunnyMo packs in the chat',
        'target.m35b.sheet': 'Character sheet',
        'm35b.target.mode': 'Packs at work',
        'm35b.target.mode.all': 'all',
        'm35b.target.mode.only': 'only the chosen ones',
        'm35b.target.books': 'Chosen packs',

        'm35b.error.noChat': 'Open a chat first.',
        'm35b.error.file': '«{file}» is not a lorebook file (JSON with entries).',
        'm35b.error.noBook': 'Lorebook «{book}» could not be read.',
        'm35b.error.noEntry': 'Lorebook «{book}» has no such entry.',
        'm35b.error.bunnymoBook': '«{book}» is a BunnyMo book: its files are never edited.',
        'm35b.error.noSave': 'This SillyTavern cannot save lorebooks.',
        'm35b.error.sheet.noBlock': 'This entry of «{book}» has no <BunnymoTags> block.',
        'm35b.error.sheet.multiBlock': 'This entry of «{book}» holds several characters: one entry must hold one.',
        'm35b.error.sheet.name': 'The name in <Name:…> cannot change.',
        'm35b.error.sheet.tag':
            'A tag cannot be written: the key takes Latin letters, digits, _ and -, the value has no < > or line breaks.',
    },
    ru: {
        'm35b.title': 'Режим BunnyMo',
        'm35b.tab': 'BunnyMo',
        'm35b.nav': 'Разделы режима BunnyMo',
        'm35b.view.dictionary': 'Словарь тегов',
        'm35b.view.packs': 'Паки',
        'm35b.view.integrity': 'Целостность',
        'm35b.view.sheets': 'Листы',
        'm35b.view.edits': 'Правки на лету',
        'm35b.loading': 'Читаю лорбуки…',
        'm35b.refresh': 'Обновить',
        'm35b.health.title': 'Целостность BunnyMo',
        'm35b.health.ok': 'С книгами BunnyMo всё в порядке.',
        'm35b.health.found': 'Проблем: {count}. {first}',
        'm35b.slash.help':
            'Открывает режим BunnyMo: тег (<SPECIES:ELF>) — словарь на этом теге, имя персонажа — редактор его листа.',
        'm35b.slash.value': 'тег или имя персонажа',

        'm35b.dict.search': 'Поиск по тегам, записям и персонажам',
        'm35b.dict.category': 'Категория',
        'm35b.dict.allCategories': 'Все категории',
        'm35b.dict.flags': 'Флаги без категории',
        'm35b.dict.summary': 'Тегов: {tags}, категорий: {categories} · конфликтов: {conflicts} · без пака: {orphans}',
        'm35b.dict.none': 'Ничего не нашлось.',
        'm35b.dict.empty': 'Книг BunnyMo не нашлось — словарь пуст.',
        'm35b.dict.more': 'Показать ещё {count}',
        'm35b.dict.pulls': 'Записи паков',
        'm35b.dict.noEntries': 'Ни в одном загруженном паке нет записи на этот тег.',
        'm35b.dict.infoTag': 'Информационный тег: его читают только модель и CarrotKernel, запись в паке не нужна.',
        'm35b.dict.usedBy': 'Где используется',
        'm35b.dict.unused': 'Ни один архив этот тег не использует.',
        'm35b.dict.entry': '«{book}» · #{uid}',
        'm35b.dict.chars': '{chars} симв.',
        'm35b.dict.kind.pull': 'подтягивает',
        'm35b.dict.kind.info': 'справка',
        'm35b.dict.badge.conflict': 'конфликт версий',
        'm35b.dict.badge.duplicate': 'дубль',
        'm35b.dict.badge.orphan': 'нет пака',
        'm35b.dict.badge.info': 'информационный',
        'm35b.dict.conflictHint':
            'У этого тега разные тексты в нескольких паках. Какая версия остаётся, решает правило «Конфликт версий паков».',
        'm35b.dict.duplicateHint':
            'Один и тот же текст в нескольких паках: правило «Побайтные дубли паков» оставляет одну копию.',
        'm35b.dict.openSheet': 'Открыть лист: {name}',

        'm35b.packs.allInChat': 'Все паки в этом чате',
        'm35b.packs.allHint':
            'Если выключить, в этом чате работают только отмеченные паки, остальные убираются из сканирования. Файлы и глобальные включения не меняются.',
        'm35b.packs.noChat': 'Открой чат, чтобы выбрать для него паки.',
        'm35b.packs.inChat': 'В этом чате',
        'm35b.packs.active': 'включён',
        'm35b.packs.inactive': 'не включён',
        'm35b.packs.edition.shared': 'общий файл',
        'm35b.packs.edition.split': 'раздельное издание',
        'm35b.packs.entries': 'записей: {count}',
        'm35b.packs.version': 'v{version}',
        'm35b.packs.none': 'Паков BunnyMo не нашлось.',
        'm35b.packs.core': 'Ядро «{book}» · V{version}',
        'm35b.packs.coreInactive': 'не включено',
        'm35b.packs.compare': 'Сравнить с файлом',
        'm35b.packs.conflicts': 'Конфликты версий',
        'm35b.packs.conflict.chosen': '{books}: остаётся «{choice}»',
        'm35b.packs.conflict.every': '{books}: остаются все версии',
        'm35b.packs.conflict.open': '{books}: ещё не решено',
        'm35b.packs.diff.title': '«{book}» в сравнении с «{file}»',
        'm35b.packs.diff.added': 'Новое в файле ({count})',
        'm35b.packs.diff.removed': 'Есть только в книге ({count})',
        'm35b.packs.diff.changed': 'Изменилось ({count})',
        'm35b.packs.diff.same': 'В файле те же записи.',
        'm35b.packs.diff.note':
            'Ничего не записано. Чтобы перейти на новую версию, импортируй файл новой книгой в Лор-студии и выбери её для чата здесь.',
        'm35b.packs.diff.close': 'Закрыть сравнение',

        'm35b.integrity.ok': 'Всё в порядке.',
        'm35b.integrity.coreMissing.inactive':
            'Включено паков: {count}, а ядро «{book}» не включено — команды листов и записи Master не работают.',
        'm35b.integrity.coreMissing.absent': 'Включено паков: {count}, а ядра BunnyMo нет.',
        'm35b.integrity.coreVersion.several': 'Включено сразу несколько ядер BunnyMo: {books}. Оставь одно.',
        'm35b.integrity.coreVersion.old': 'Ядро «{book}» похоже на версию {version}, а Maestro проверен с V{expected}.',
        'm35b.integrity.packAsRepo.repo':
            '«{book}» — книга BunnyMo, отмеченная в CarrotKernel как репозиторий персонажей: CK примет её шаблоны за персонажей. Сними отметку в CarrotKernel.',
        'm35b.integrity.ckWrapRewrite.backup':
            'Записей «{book}», переписанных обёрткой тегов CarrotKernel: {count} (видно по копии .carrot_backup).',
        'm35b.integrity.ckWrapRewrite.backupPack':
            'Записей пака BunnyMo «{book}», переписанных обёрткой тегов CarrotKernel: {count}. Файлы паков должны оставаться как есть — импортируй исходный файл заново.',
        'm35b.integrity.ckWrapRewrite.nested': 'Записей «{book}» с двойной обёрткой CarrotKernel: {count}.',
        'm35b.integrity.ckWrapRewrite.nestedPack':
            'Записей пака BunnyMo «{book}» с двойной обёрткой CarrotKernel: {count}. Импортируй исходный файл заново.',
        'm35b.integrity.ckWrapRewrite.pending':
            '«{book}» — библиотека тегов CarrotKernel, а «обёртка тегов BunnyMo» включена: при следующей загрузке CK перепишет этот файл.',
        'm35b.integrity.ckWrapRewrite.pendingPack':
            'При следующей загрузке CarrotKernel перепишет пак BunnyMo «{book}» (библиотека тегов при включённой «обёртке тегов BunnyMo»). Выключи обёртку в CarrotKernel.',
        'm35b.integrity.ckBackup.copy': 'Копия CarrotKernel «{book}» (копия «{original}»).',
        'm35b.integrity.ckBackup.orphan': 'Копия CarrotKernel «{book}»: исходной книги «{original}» уже нет.',
        'm35b.integrity.canonGlobal.global':
            'Канон чата «{book}» включён глобально, а должен работать только через Maestro.',
        'm35b.integrity.chatBookGlobal.global':
            'Книга чата «{book}» включена ещё и глобально — она работает во всех чатах.',

        'm35b.sheets.none': 'Архивов персонажей не нашлось (репозитории CarrotKernel или книги с <BunnymoTags>).',
        'm35b.sheets.tags': 'тегов: {count}',
        'm35b.sheets.back': 'К списку',
        'm35b.sheets.noName': '(без имени)',
        'm35b.sheets.nameLocked': '<Name:…> не меняется: по нему персонажа находят CarrotKernel, RAG и DES.',
        'm35b.sheets.tagsTitle': 'Теги',
        'm35b.sheets.noTags': 'В блоке пока нет тегов.',
        'm35b.sheets.category': 'Категория',
        'm35b.sheets.value': 'Значение',
        'm35b.sheets.add': 'Добавить',
        'm35b.sheets.replace': 'Заменить',
        'm35b.sheets.cancelEdit': 'Отмена',
        'm35b.sheets.remove': 'Убрать {tag}',
        'm35b.sheets.edit': 'Изменить {tag}',
        'm35b.sheets.mbti': 'MBTI',
        'm35b.sheets.mbtiNone': 'нет',
        'm35b.sheets.healthy': 'H — здоровый',
        'm35b.sheets.unhealthy': 'U — нездоровый',
        'm35b.sheets.linguistics': 'Linguistics',
        'm35b.sheets.sections': 'Прозаические разделы',
        'm35b.sheets.untitled': 'Текст без заголовка',
        'm35b.sheets.inText': 'Теги в тексте',
        'm35b.sheets.check': 'Проверка тегов',
        'm35b.sheets.checkOk': 'Все теги в порядке.',
        'm35b.sheets.suggest': 'Взять {tag}',
        'm35b.sheets.save': 'Сохранить',
        'm35b.sheets.reset': 'Отменить правки',
        'm35b.sheets.saved': 'Сохранил лист характера: {name}.',
        'm35b.sheets.unchanged': 'Сохранять нечего: в листе ничего не поменялось.',
        'm35b.sheets.multiBlock':
            'В этой записи блоков <BunnymoTags>: {count}, а CarrotKernel читает только первый. Перед правкой раздели её — одна запись на персонажа.',
        'm35b.sheets.notFound': 'Этого листа характера больше нет.',
        'm35b.sheets.chatSheets': 'Листы этого персонажа в чате',
        'm35b.sheets.chatSheet': 'сообщение №{index} · !{command}',
        'm35b.sheets.commands':
            'Команды листов (!fullsheet, !updatesheet…) идут через сценарий листов: напиши команду с именем в чате.',

        'm35b.edits.intro':
            'Технические правки, которые Maestro делает в книгах BunnyMo на лету: меняются только копии для сканирования, файлы остаются как есть. Любое правило можно выключить.',
        'm35b.edits.noRules': 'Модуль «Правила» выключен — правок на лету нет.',
        'm35b.edits.changes': 'изменений в последнем сканировании: {count}',
        'm35b.edits.none': 'в последнем сканировании ничего не изменило',
        'm35b.edits.cuts': 'срезано срабатываний: {count}',
        'm35b.edits.waiting': 'ждёт мастера первого запуска',
        'm35b.edits.owner.desru': 'владелец: DES-RU',
        'm35b.edits.change': '«{book}» · #{uid} · {field}: {before} → {after}',
        'm35b.edits.selection': 'Паки, выключенные в этом чате',
        'm35b.edits.selectionItem': '«{book}»: из сканирования убрано записей: {count}',
        'm35b.edits.selectionNone': 'Выбор паков для чата ничего не убрал из последнего сканирования.',
        'm35b.edits.selectionAll': 'Снова все паки',
        'm35b.edits.desru':
            'DES-RU (модуль 5) тоже правит записи BunnyMo на лету: русские ключи детекторов и флаги рекурсии. Это переключается в настройках DES-RU.',

        'm35b.reason.malformed': 'неверная запись: CarrotKernel читает только <KEY:VALUE>',
        'm35b.reason.cyrillic': 'русские буквы: теги пишутся по-английски',
        'm35b.reason.placeholder': 'заглушка из шаблона',
        'm35b.reason.transitional': 'разметка перехода (→, %, FADING): впиши итоговое значение',
        'm35b.reason.duplicate': 'повтор',
        'm35b.reason.unknownCategory': 'неизвестная категория',
        'm35b.reason.unknownValue': 'в паке нет записи с таким значением',
        'm35b.reason.noPack': 'пак этой категории не загружен — тег ничего не подтянет',

        'm35b.journal.selectionAll': 'В этом чате снова работают все паки BunnyMo',
        'm35b.journal.selectionOnly': 'В этом чате работают только выбранные паки BunnyMo: {count}',
        'm35b.journal.sheet': 'Сохранён лист характера: {name}',

        'kind.bunnymo.packSelection': 'Паки BunnyMo для чата',
        'kind.bunnymo.sheet': 'Правка листа характера',
        'target.m35b.packSelection': 'Паки BunnyMo в чате',
        'target.m35b.sheet': 'Лист характера',
        'm35b.target.mode': 'Какие паки работают',
        'm35b.target.mode.all': 'все',
        'm35b.target.mode.only': 'только выбранные',
        'm35b.target.books': 'Выбранные паки',

        'm35b.error.noChat': 'Сначала открой чат.',
        'm35b.error.file': '«{file}» — не файл книги лора (нужен JSON с записями).',
        'm35b.error.noBook': 'Не удалось прочитать книгу лора «{book}».',
        'm35b.error.noEntry': 'В книге лора «{book}» нет такой записи.',
        'm35b.error.bunnymoBook': '«{book}» — книга BunnyMo, её файлы не правятся.',
        'm35b.error.noSave': 'Эта версия SillyTavern не умеет сохранять книги лора.',
        'm35b.error.sheet.noBlock': 'В этой записи книги «{book}» нет блока тегов <BunnymoTags>.',
        'm35b.error.sheet.multiBlock': 'В этой записи книги «{book}» несколько персонажей, а должен быть один.',
        'm35b.error.sheet.name': 'Имя в <Name:…> менять нельзя.',
        'm35b.error.sheet.tag':
            'Тег нельзя записать: в ключе только латиница, цифры, _ и -, в значении не должно быть < > и переводов строки.',
    },
};
