import type { I18nParts } from '../../shared/contracts';

/** Strings of M40 «Команды BunnyMo» (`m40.*`). */
export const BUNNYMO_COMMANDS_STRINGS: I18nParts = {
    en: {
        'm40.title': 'BunnyMo commands',
        'm40.group': 'BunnyMo',
        'm40.cmd.fullsheet': 'Full sheet',
        'm40.cmd.fullsheet.hint': 'a psychological portrait of the character, slow',
        'm40.cmd.quicksheet': 'Short sheet',
        'm40.cmd.quicksheet.hint': 'the main things about the character, quick',
        'm40.cmd.tagsheet': 'Tags only',
        'm40.cmd.tagsheet.hint': 'BunnyMo tags without the write-up',
        'm40.cmd.updatesheet': 'Update the tags',
        'm40.cmd.updatesheet.hint': 'the tags after what changed in the story',
        'm40.cmd.physheet': 'Looks',
        'm40.cmd.physheet.hint': 'a sheet of how the character looks',
        'm40.cmd.memsheet': 'Remember a moment',
        'm40.cmd.memsheet.hint': 'a note about an important moment of the story',
        'm40.noSheets': '{hint} · Maestro’s «Sheets» are off: the sheet takes a lot of context',
        'm40.other': 'Someone else…',
        'm40.other.title': 'Whose sheet?',
        'm40.other.hint': 'The character’s name as the story has it.',
        'm40.moment.title': 'What to remember?',
        'm40.moment.hint': 'The moment in a few words: «the first kiss on the bridge».',
        'm40.dictionary': 'BunnyMo dictionary',
        'm40.dictionary.hint': 'tags, packs and sheets, no model',
        'm40.dossier': 'Character dossier',
        'm40.dossier.hint': 'everything known about the character, no model',
        'm40.you': '{name} (you)',
        'm40.busy': 'A reply is being written: the command waits in the message box, send it afterwards.',
        'm40.noBox': 'The message box was not found.',
        'm40.noDossier': 'No dossier on {name} yet.',
        'm40.settings.title': 'BunnyMo commands',
        'm40.settings.hint':
            'The Maestro button at the message box → BunnyMo. Shown only while the BunnyMo core is connected.',
        'm40.settings.sendNow': 'Send at once',
        'm40.settings.sendNow.hint':
            'The command goes out as your message and the reply starts. Without this it is put at the start of the message box: add to it and send it yourself.',
    },
    ru: {
        'm40.title': 'Команды BunnyMo',
        'm40.group': 'BunnyMo',
        'm40.cmd.fullsheet': 'Полный лист',
        'm40.cmd.fullsheet.hint': 'психологический разбор персонажа, долго',
        'm40.cmd.quicksheet': 'Короткий лист',
        'm40.cmd.quicksheet.hint': 'главное о персонаже, быстро',
        'm40.cmd.tagsheet': 'Только теги',
        'm40.cmd.tagsheet.hint': 'теги BunnyMo без описания',
        'm40.cmd.updatesheet': 'Обновить теги',
        'm40.cmd.updatesheet.hint': 'теги по тому, что изменилось в истории',
        'm40.cmd.physheet': 'Внешность',
        'm40.cmd.physheet.hint': 'лист о том, как выглядит персонаж',
        'm40.cmd.memsheet': 'Запомнить момент',
        'm40.cmd.memsheet.hint': 'запись о важном моменте истории',
        'm40.noSheets': '{hint} · «Листы» Maestro выключены — лист займёт много контекста',
        'm40.other': 'Другой…',
        'm40.other.title': 'Для кого лист?',
        'm40.other.hint': 'Имя персонажа, как в истории.',
        'm40.moment.title': 'Что запомнить?',
        'm40.moment.hint': 'Момент в двух словах: «первый поцелуй на мосту».',
        'm40.dictionary': 'Словарь BunnyMo',
        'm40.dictionary.hint': 'теги, паки и листы — без модели',
        'm40.dossier': 'Досье персонажа',
        'm40.dossier.hint': 'всё, что известно о персонаже, — без модели',
        'm40.you': '{name} (ты)',
        'm40.busy': 'Сейчас идёт ответ: команда стоит в поле ввода, отправь её потом.',
        'm40.noBox': 'Не нашёл поле ввода.',
        'm40.noDossier': 'Досье на {name} пока нет.',
        'm40.settings.title': 'Команды BunnyMo',
        'm40.settings.hint': 'Кнопка Maestro у поля ввода → BunnyMo. Видна, только когда подключено ядро BunnyMo.',
        'm40.settings.sendNow': 'Отправлять сразу',
        'm40.settings.sendNow.hint':
            'Команда сразу уходит твоим сообщением, и начинается ответ. Без этого она встаёт в начало поля ввода — можно дописать и отправить самому.',
    },
};
