// Strings of M6 «Канон чата» (`m6.*`, action kinds `kind.canon.*`, journal targets `target.canon-*`) and how its journal
// targets read in Inbox cards and the journal. Russian is the primary UI language; the user is addressed as «ты».
import { formatClip, formatPlain } from '../../core/labels';
import type { I18n, I18nParts, TargetSpec } from '../../shared/contracts';

/** «действует» / «в архиве» of a canon entry (its meta lives in `extensions.maestro`). */
function canonState(value: unknown, i18n: I18n): string {
    if (typeof value !== 'object' || value === null) return '';
    const meta = (value as { maestro?: unknown }).maestro;
    const status = typeof meta === 'object' && meta !== null ? (meta as { status?: unknown }).status : undefined;
    return typeof status === 'string' && status ? i18n.t(`m6.status.${status}`) : '';
}

/**
 * Entries are World Info entries: the title (comment) and the canon state read in words; the text is usually English
 * canon prose and the keys are search terms, so both stay under «Подробнее» with uid, order and the rest.
 */
export const CANON_TARGETS: TargetSpec[] = [
    {
        target: 'canon-entry',
        fields: {
            comment: { labelKey: 'm6.field.title', format: formatClip(80) },
            extensions: { labelKey: 'm6.field.state', format: canonState },
            content: { labelKey: 'm6.field.text', hidden: true },
            key: { labelKey: 'm6.field.keys', hidden: true },
        },
    },
    {
        target: 'canon-base-entry',
        fields: {
            comment: { labelKey: 'm6.field.title', format: formatClip(80) },
            disable: { labelKey: 'm6.field.off', format: formatPlain },
            content: { labelKey: 'm6.field.text', hidden: true },
            key: { labelKey: 'm6.field.keys', hidden: true },
        },
    },
    // A created lorebook (export, a branch's canon): the book names are technical, the summary says what happened.
    { target: 'canon-book', technical: true },
];

export const CANON_STRINGS: I18nParts = {
    en: {
        'm6.title': 'Chat canon',
        'm6.tab': 'Canon',
        'kind.canon.branchCopy': 'Copying the canon into a branch',
        'kind.canon.put': 'Chat canon entries',
        'kind.canon.remove': 'Removing from the chat canon',
        'kind.canon.status': 'Archiving and restoring canon entries',
        'kind.canon.promote': 'Canon for all chats',
        'kind.canon.export': 'Exporting the canon to a lorebook',
        'target.canon-entry': 'Chat canon entry',
        'target.canon-base-entry': 'Entry of a shared lorebook',
        'target.canon-book': 'Lorebook',
        'm6.field.title': 'Entry',
        'm6.field.state': 'State',
        'm6.field.text': 'Text',
        'm6.field.keys': 'Keys',
        'm6.field.off': 'Switched off',
        'm6.hint':
            'What the story changed lives here, not in your lorebooks: overrides replace a base entry for this chat only, additions are new entries, suppressions hide a base entry, pins force one in. Maestro mixes the canon into every scan; the book itself is never switched on.',
        'm6.noChat': 'No chat is open.',
        'm6.noBook': 'This chat has no canon yet.',
        'm6.empty': 'The canon of this chat is empty.',
        'm6.group.override': 'Overrides ({count})',
        'm6.group.addition': 'Additions ({count})',
        'm6.group.suppress': 'Suppressed ({count})',
        'm6.group.pin': 'Pinned ({count})',
        'm6.kind.override': 'Override',
        'm6.kind.addition': 'Addition',
        'm6.kind.suppress': 'Suppressed',
        'm6.kind.pin': 'Pinned',
        'm6.status.active': 'active',
        'm6.status.provisional': 'provisional',
        'm6.status.archived': 'archived',
        'm6.origin.user': 'by you',
        'm6.origin.revision': 'revision',
        'm6.origin.living': 'living canon',
        'm6.origin.chronicle': 'chronicle',
        'm6.origin.backstage': 'backstage',
        'm6.origin.entity': 'world model',
        'm6.origin.import': 'import',
        'm6.base': 'Base: {book}, entry {uid}',
        'm6.base.open': 'Open the base lorebook',
        'm6.action.archive': 'Archive',
        'm6.action.activate': 'Activate',
        'm6.action.confirm': 'Confirm',
        'm6.action.promote': 'Canon for all chats',
        'm6.action.promoteHint': 'Write this change into the base lorebook (asks first)',
        'm6.action.remove': 'Remove',
        'm6.remove.title': 'Remove from the canon?',
        'm6.remove.body': '«{title}» leaves the canon of this chat. You can undo it from the journal.',
        'm6.budget.line': 'Canon on the last turn: {used} of {limit} characters',
        'm6.budget.unlimited': 'Canon on the last turn: {used} characters (no limit)',
        'm6.scan.report':
            'Last scan ({time}): added {added}, replaced {replaced}, suppressed {suppressed}, pinned {pinned}, archived and silent {dormant}, cut by the budget {cut}.',
        'm6.scan.none': 'No generation has used the canon yet.',
        'm6.scan.missing':
            'Base entries not found in the last scan: {count} (their book is not active or the entry is gone).',
        'm6.drift.check': 'Check the bases',
        'm6.drift.title': 'Base entries changed',
        'm6.drift.none': 'No base entry has changed since its canon item was made.',
        'm6.drift.item': '«{title}»: the base entry in {book} has changed',
        'm6.drift.base': 'Base entry, then → now:',
        'm6.drift.override': 'The override:',
        'm6.promote.title': 'Make it canon for all chats?',
        'm6.promote.body':
            'The override is written into «{entry}» of the lorebook {book} and leaves the chat canon. Every chat with this book will see it.',
        'm6.promote.bodySuppress':
            'The entry «{entry}» of the lorebook {book} is switched off for every chat, and the suppression leaves the chat canon.',
        'm6.promote.readOnly': 'Maestro never edits the lorebook «{book}»: it is read-only (BunnyMo).',
        'm6.promote.missing': 'The original entry is gone from the lorebook «{book}».',
        'm6.export.action': 'Export',
        'm6.export.hint':
            'Save the canon as an ordinary lorebook (overrides expanded, suppressed entries listed in a note)',
        'm6.export.done': 'Canon exported to the lorebook «{book}»; it is not attached to anything.',
        'm6.export.empty': 'The canon of this chat is empty: nothing to export.',
        'm6.export.noteTitle': 'Maestro canon: base entries to review',
        'm6.export.suppressed': 'Suppressed in this chat (switch them off by hand):',
        'm6.export.overridden': 'Replaced in this chat (the copies above take their place; switch the originals off):',
        'm6.export.pinned': 'Always active in this chat:',
        'm6.export.line': '- {world} — {comment} (uid {uid})',
        'm6.warn.active':
            'The canon lorebook «{book}» is switched on in SillyTavern. Switch it off: Maestro mixes the canon in by itself, and while the book is on its entries are left out.',
        'm6.branch.title': 'Canon for the new branch of the chat',
        'm6.branch.description':
            'This chat branched off «{parent}», which already has a canon. Copy it here? Then the branch goes on with the same facts. The whole canon is copied, including what was added after the branch point.',
        'm6.branch.details': 'Canon lorebook of the parent chat: {book}',
        'm6.branch.applied': 'Copied the canon of «{parent}» into this branch.',
        'm6.branch.failed':
            'The canon was not copied: the branch already has its own, or the parent chat has no canon any more.',
        'm6.journal.put': 'Added to the chat canon: «{title}»',
        'm6.journal.update': 'Changed in the chat canon: «{title}»',
        'm6.journal.remove': 'Removed from the chat canon: «{title}»',
        'm6.journal.status': 'Canon entry «{title}» is now {status}',
        'm6.journal.promote': '«{title}» written into the lorebook «{book}» for all chats',
        'm6.journal.export': 'Canon exported to the lorebook «{book}»',
        'm6.error.noChat': 'No chat is open.',
        'm6.error.noWorldInfo': 'This SillyTavern cannot save lorebooks from extensions.',
        'm6.error.kind': 'Unknown kind of canon item.',
        'm6.error.base': 'An override, suppression or pin needs a base entry.',
        'm6.health.title': 'Chat canon is not switched on directly',
        'm6.health.ok': 'No canon lorebook is active in SillyTavern.',
        'm6.health.active':
            'Canon lorebooks active in SillyTavern: {books}. Switch them off: Maestro mixes the canon in.',
    },
    ru: {
        'm6.title': 'Канон чата',
        'm6.tab': 'Канон',
        'kind.canon.branchCopy': 'Копия канона в новую ветку чата',
        'kind.canon.put': 'Записи в каноне чата',
        'kind.canon.remove': 'Удаление из канона чата',
        'kind.canon.status': 'Архив и возврат записей канона',
        'kind.canon.promote': 'Канон для всех чатов',
        'kind.canon.export': 'Выгрузка канона в книгу лора',
        'target.canon-entry': 'Запись канона чата',
        'target.canon-base-entry': 'Запись в общей книге лора',
        'target.canon-book': 'Книга лора',
        'm6.field.title': 'Запись',
        'm6.field.state': 'Состояние',
        'm6.field.text': 'Текст',
        'm6.field.keys': 'Ключи',
        'm6.field.off': 'Выключена',
        'm6.hint':
            'Здесь живёт то, что изменил сюжет, — не в твоих лорбуках: переопределение заменяет базовую запись только в этом чате, добавление — новая запись, подавление прячет базовую запись, закрепление включает её всегда. Maestro подмешивает канон при каждом сканировании; сама книга не включается никогда.',
        'm6.noChat': 'Чат не открыт.',
        'm6.noBook': 'У этого чата пока нет канона.',
        'm6.empty': 'Канон этого чата пуст.',
        'm6.group.override': 'Переопределения ({count})',
        'm6.group.addition': 'Добавления ({count})',
        'm6.group.suppress': 'Подавленные ({count})',
        'm6.group.pin': 'Закреплённые ({count})',
        'm6.kind.override': 'Переопределение',
        'm6.kind.addition': 'Добавление',
        'm6.kind.suppress': 'Подавление',
        'm6.kind.pin': 'Закрепление',
        'm6.status.active': 'действует',
        'm6.status.provisional': 'пробная',
        'm6.status.archived': 'в архиве',
        'm6.origin.user': 'ты',
        'm6.origin.revision': 'ревизия',
        'm6.origin.living': 'живой канон',
        'm6.origin.chronicle': 'летопись',
        'm6.origin.backstage': 'закулисье',
        'm6.origin.entity': 'модель мира',
        'm6.origin.import': 'импорт',
        'm6.base': 'База: {book}, запись {uid}',
        'm6.base.open': 'Открыть базовый лорбук',
        'm6.action.archive': 'В архив',
        'm6.action.activate': 'Вернуть',
        'm6.action.confirm': 'Подтвердить',
        'm6.action.promote': 'Канон для всех чатов',
        'm6.action.promoteHint': 'Записать изменение в базовый лорбук (сначала спросит)',
        'm6.action.remove': 'Убрать',
        'm6.remove.title': 'Убрать из канона?',
        'm6.remove.body': '«{title}» уйдёт из канона этого чата. Отменить можно в журнале.',
        'm6.budget.line': 'Канон в прошлом ходе: {used} из {limit} символов',
        'm6.budget.unlimited': 'Канон в прошлом ходе: {used} символов (без потолка)',
        'm6.scan.report':
            'Последнее сканирование ({time}): добавлено {added}, заменено {replaced}, подавлено {suppressed}, закреплено {pinned}, в архиве без упоминаний {dormant}, срезано бюджетом {cut}.',
        'm6.scan.none': 'Ни одна генерация ещё не использовала канон.',
        'm6.scan.missing':
            'Базовых записей нет в последнем сканировании: {count} (их книга не активна или запись удалена).',
        'm6.drift.check': 'Проверить базу',
        'm6.drift.title': 'Базовые записи изменились',
        'm6.drift.none': 'Ни одна базовая запись не менялась с тех пор, как появилась запись канона.',
        'm6.drift.item': '«{title}»: базовая запись в {book} изменилась',
        'm6.drift.base': 'Базовая запись, было → стало:',
        'm6.drift.override': 'Переопределение:',
        'm6.promote.title': 'Сделать каноном для всех чатов?',
        'm6.promote.body':
            'Переопределение запишется в «{entry}» лорбука {book} и уйдёт из канона чата. Это увидят все чаты с этой книгой.',
        'm6.promote.bodySuppress':
            'Запись «{entry}» лорбука {book} выключится во всех чатах, а подавление уйдёт из канона чата.',
        'm6.promote.readOnly': 'Книгу лора «{book}» Maestro не правит: она только для чтения (BunnyMo).',
        'm6.promote.missing': 'Исходной записи в книге лора «{book}» больше нет.',
        'm6.export.action': 'Экспорт',
        'm6.export.hint':
            'Сохранить канон обычным лорбуком (переопределения развёрнуты, подавленные записи перечислены в заметке)',
        'm6.export.done': 'Канон выгружен в книгу лора «{book}» — она ни к чему не подключена.',
        'm6.export.empty': 'Канон этого чата пуст — выгружать нечего.',
        'm6.export.noteTitle': 'Канон Maestro: базовые записи, на которые стоит взглянуть',
        'm6.export.suppressed': 'Подавлены в этом чате (выключи их вручную):',
        'm6.export.overridden': 'Заменены в этом чате (их место заняли копии выше; оригиналы выключи):',
        'm6.export.pinned': 'Всегда включены в этом чате:',
        'm6.export.line': '- {world} — {comment} (uid {uid})',
        'm6.warn.active':
            'Книга канона «{book}» включена в SillyTavern. Выключи её: Maestro подмешивает канон сам, а пока книга включена, её записи не учитываются.',
        'm6.branch.title': 'Канон для новой ветки чата',
        'm6.branch.description':
            'Этот чат ответвился от «{parent}», а там у истории уже есть канон. Скопировать его сюда? Тогда ветка продолжит с теми же фактами. Канон копируется целиком — вместе с тем, что появилось после точки ветвления.',
        'm6.branch.details': 'Книга канона исходного чата: {book}',
        'm6.branch.applied': 'Перенёс в эту ветку канон из «{parent}».',
        'm6.branch.failed': 'Канон не скопирован: у ветки уже есть свой или у исходного чата канона больше нет.',
        'm6.journal.put': 'В канон чата добавлено: «{title}»',
        'm6.journal.update': 'В каноне чата изменено: «{title}»',
        'm6.journal.remove': 'Из канона чата убрано: «{title}»',
        'm6.journal.status': 'Запись канона «{title}» теперь {status}',
        'm6.journal.promote': '«{title}» записано в книгу лора «{book}» — для всех чатов',
        'm6.journal.export': 'Канон выгружен в книгу лора «{book}»',
        'm6.error.noChat': 'Чат не открыт.',
        'm6.error.noWorldInfo': 'Эта версия SillyTavern не даёт расширениям сохранять лорбуки.',
        'm6.error.kind': 'Неизвестный вид записи канона.',
        'm6.error.base': 'Переопределению, подавлению и закреплению нужна базовая запись.',
        'm6.health.title': 'Канон чата не включён напрямую',
        'm6.health.ok': 'Ни один лорбук канона не включён в SillyTavern.',
        'm6.health.active':
            'В SillyTavern включены лорбуки канона: {books}. Выключи их — Maestro подмешивает канон сам.',
    },
};
