import type { I18nParts } from '../../shared/contracts';

export const M1_STRINGS: I18nParts = {
    en: {
        'm1.title': 'Lore journal',
        'm1.tab': 'Turn lore',
        'm1.noChat': 'Open a chat to see what lore goes into its prompt.',

        'm1.turn.title': 'Last turn',
        'm1.turn.pick': 'Turn',
        'm1.turn.option': 'Message #{index} · {type} · {time}',
        'm1.turn.empty':
            'No turns recorded in this chat yet. Send a message: after the reply the journal shows the lore of that turn.',
        'm1.turn.summary': 'Entries in the prompt: {count} · {chars} chars · ~{tokens} tokens',
        'm1.turn.budget': 'World Info budget: {budget} tokens · used ~{percent}%',
        'm1.turn.overflow': 'The budget overflowed: some activated entries were cut and recursion stopped.',
        'm1.turn.cutCount': 'Cut: {count}',
        'm1.turn.keys': 'Which key?',
        'm1.turn.keysHint': 'Repeats the key matching on the chat as it was before this reply (ST does not store it).',
        'm1.turn.keysDone': 'Keys found for {found} of {total} entries.',

        'm1.col.book': 'Book',
        'm1.col.entry': 'Entry',
        'm1.col.place': 'Placement',
        'm1.col.chars': 'Chars',
        'm1.col.tokens': 'Tokens',
        'm1.col.loop': 'Scan step',
        'm1.col.via': 'Pulled in by',
        'm1.col.key': 'Key',
        'm1.col.cut': 'Cut',
        'm1.loop.direct': '{loop}',
        'm1.loop.recursion': '{loop} · recursion {level}',
        'm1.key.pending': '…',
        'm1.key.none': '—',
        'm1.via.none': '—',
        'm1.entry.untitled': 'entry #{uid}',
        'm1.cut.budget': 'budget',
        'm1.cut.maestro': 'Maestro rule',
        'm1.cut.other': 'another extension',

        'm1.pos.0': 'before the card',
        'm1.pos.1': 'after the card',
        'm1.pos.2': 'above Author’s Note',
        'm1.pos.3': 'below Author’s Note',
        'm1.pos.4': 'depth {depth}, {role}',
        'm1.pos.5': 'above examples',
        'm1.pos.6': 'below examples',
        'm1.pos.7': 'outlet',
        'm1.pos.other': 'position {position}',
        'm1.role.0': 'system',
        'm1.role.1': 'user',
        'm1.role.2': 'assistant',

        'm1.tag.bunnymo.core': 'BunnyMo core',
        'm1.tag.bunnymo.pack': 'BunnyMo pack',
        'm1.tag.ck.archive': 'CK archive',
        'm1.tag.localizer': 'Localizer keys',
        'm1.tag.des.book': 'DES book',
        'm1.tag.canon': 'canon',
        'm1.tag.maestro.book': 'Maestro book',
        'm1.tag.constant': 'constant',

        'm1.why.title': 'Why the book is active',
        'm1.why.empty': 'No active lorebooks.',
        'm1.why.loading': 'Checking…',
        'm1.reason.global': 'global list',
        'm1.reason.character': 'character card',
        'm1.reason.characterExtra': 'extra book of the character',
        'm1.reason.chat': 'chat book',
        'm1.reason.persona': 'persona',
        'm1.reason.desCampaign': 'DES campaign',
        'm1.reason.desAutoLink': 'DES auto-link by name',
        'm1.reason.ckConnector': 'CarrotKernel connection',
        'm1.reason.workshop': 'DES Workshop injection',
        'm1.reason.canon': 'chat canon',

        'm1.sim.title': 'What if',
        'm1.sim.run': 'What if I send now?',
        'm1.sim.hint': 'A scan of the current chat without generating, as for the next normal reply.',
        'm1.sim.caveat':
            'Probabilities are off. Sticky and cooldown are not evaluated in a dry run, and forced activations waiting for the next turn are used up by it.',
        'm1.sim.result': 'Would go into the prompt: {count} entries · {chars} chars · ~{tokens} tokens',
        'm1.sim.diff': 'Compared with the last turn: +{added} / −{removed} entries',
        'm1.sim.busy': 'Wait until the generation finishes.',
        'm1.sim.failed': 'The dry run failed: {error}',

        'm1.summary.title': 'Chat summary',
        'm1.summary.empty': 'The summary appears after the first recorded turn.',
        'm1.summary.turns': 'Turns counted: {turns}',
        'm1.summary.avg': 'Lore per turn on average: {chars} chars',
        'm1.summary.canon': 'Chat canon per turn on average: {chars} chars',
        'm1.summary.books': 'Heaviest books',
        'm1.summary.entries': 'Heaviest entries',
        'm1.summary.always': 'Active on every turn',
        'm1.summary.never': 'Never activated: {count}',
        'm1.summary.neverHint': 'Enabled entries of the books scanned last that no recorded turn activated.',
        'm1.summary.none': 'None.',
        'm1.col.perTurn': 'Chars per turn',
        'm1.col.activations': 'Activations',
        'm1.col.avgChars': 'Avg chars',
        'm1.col.lastSeen': 'Last seen',

        'm1.settings.title': 'Journal settings',
        'm1.settings.keepTurns': 'Turns to keep per chat',
        'm1.settings.keepTurnsHint': 'Older turns leave the list but stay in the summary counters.',
    },
    ru: {
        'm1.title': 'Журнал лора',
        'm1.tab': 'Лор хода',
        'm1.noChat': 'Откройте чат — здесь будет видно, какой лор уходит в его промпт.',

        'm1.turn.title': 'Последний ход',
        'm1.turn.pick': 'Ход',
        'm1.turn.option': 'Сообщение №{index} · {type} · {time}',
        'm1.turn.empty': 'В этом чате ходов ещё нет. Отправьте сообщение — после ответа здесь появится его лор.',
        'm1.turn.summary': 'В промпте записей: {count} · {chars} симв. · ~{tokens} токенов',
        'm1.turn.budget': 'Бюджет лора: {budget} токенов · занято ~{percent}%',
        'm1.turn.overflow': 'Бюджет переполнен: часть сработавших записей отрезана, рекурсия остановлена.',
        'm1.turn.cutCount': 'Отрезано: {count}',
        'm1.turn.keys': 'Каким ключом',
        'm1.turn.keysHint': 'Повторить сопоставление ключей по чату на момент этого ответа (ST сам его не хранит).',
        'm1.turn.keysDone': 'Ключ найден для {found} записей из {total}.',

        'm1.col.book': 'Книга',
        'm1.col.entry': 'Запись',
        'm1.col.place': 'Куда',
        'm1.col.chars': 'Симв.',
        'm1.col.tokens': 'Токены',
        'm1.col.loop': 'Шаг',
        'm1.col.via': 'Через запись',
        'm1.col.key': 'Ключ',
        'm1.col.cut': 'Отрезано',
        'm1.loop.direct': '{loop}',
        'm1.loop.recursion': '{loop} · рекурсия {level}',
        'm1.key.pending': '…',
        'm1.key.none': '—',
        'm1.via.none': '—',
        'm1.entry.untitled': 'запись №{uid}',
        'm1.cut.budget': 'бюджетом',
        'm1.cut.maestro': 'правилом Maestro',
        'm1.cut.other': 'другим расширением',

        'm1.pos.0': 'перед карточкой',
        'm1.pos.1': 'после карточки',
        'm1.pos.2': 'над заметкой автора',
        'm1.pos.3': 'под заметкой автора',
        'm1.pos.4': 'глубина {depth}, {role}',
        'm1.pos.5': 'над примерами',
        'm1.pos.6': 'под примерами',
        'm1.pos.7': 'аутлет',
        'm1.pos.other': 'позиция {position}',
        'm1.role.0': 'system',
        'm1.role.1': 'user',
        'm1.role.2': 'assistant',

        'm1.tag.bunnymo.core': 'ядро BunnyMo',
        'm1.tag.bunnymo.pack': 'пак BunnyMo',
        'm1.tag.ck.archive': 'архив CK',
        'm1.tag.localizer': 'ключи Localizer',
        'm1.tag.des.book': 'книга DES',
        'm1.tag.canon': 'канон',
        'm1.tag.maestro.book': 'книга Maestro',
        'm1.tag.constant': 'постоянная',

        'm1.why.title': 'Почему книга активна',
        'm1.why.empty': 'Активных лорбуков нет.',
        'm1.why.loading': 'Проверяю…',
        'm1.reason.global': 'глобальный список',
        'm1.reason.character': 'книга карточки',
        'm1.reason.characterExtra': 'доп. книга персонажа',
        'm1.reason.chat': 'книга чата',
        'm1.reason.persona': 'персона',
        'm1.reason.desCampaign': 'кампания DES',
        'm1.reason.desAutoLink': 'автопривязка DES по имени',
        'm1.reason.ckConnector': 'подключение CarrotKernel',
        'm1.reason.workshop': 'вставка из Workshop DES',
        'm1.reason.canon': 'канон чата',

        'm1.sim.title': 'Что если',
        'm1.sim.run': 'Что уйдёт, если отправить сейчас?',
        'm1.sim.hint': 'Прогон по текущему чату без генерации — как для следующего обычного ответа.',
        'm1.sim.caveat':
            'Вероятности выключены. Sticky и cooldown в прогоне не учитываются, а принудительные включения, ждущие следующего хода, прогон расходует.',
        'm1.sim.result': 'Ушло бы в промпт записей: {count} · {chars} симв. · ~{tokens} токенов',
        'm1.sim.diff': 'По сравнению с последним ходом: +{added} / −{removed} записей',
        'm1.sim.busy': 'Дождитесь окончания генерации.',
        'm1.sim.failed': 'Прогон не удался: {error}',

        'm1.summary.title': 'Сводка по чату',
        'm1.summary.empty': 'Сводка появится после первого записанного хода.',
        'm1.summary.turns': 'Учтено ходов: {turns}',
        'm1.summary.avg': 'Лора за ход в среднем: {chars} симв.',
        'm1.summary.canon': 'Канона чата за ход в среднем: {chars} симв.',
        'm1.summary.books': 'Самые тяжёлые книги',
        'm1.summary.entries': 'Самые тяжёлые записи',
        'm1.summary.always': 'Срабатывают на каждом ходу',
        'm1.summary.never': 'Ни разу не сработали: {count}',
        'm1.summary.neverHint':
            'Включённые записи книг из последнего сканирования, которых нет ни в одном записанном ходе.',
        'm1.summary.none': 'Нет.',
        'm1.col.perTurn': 'Симв. за ход',
        'm1.col.activations': 'Срабатываний',
        'm1.col.avgChars': 'Симв. в среднем',
        'm1.col.lastSeen': 'Последний раз',

        'm1.settings.title': 'Настройки журнала',
        'm1.settings.keepTurns': 'Сколько ходов хранить в чате',
        'm1.settings.keepTurnsHint': 'Старые ходы уходят из списка, но остаются в счётчиках сводки.',
    },
};
