// Strings of M29 «Фоны» (`m29.*`, action kinds `kind.backgrounds.*`, journal target `target.chat-background`).
// Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const BACKGROUNDS_STRINGS: I18nParts = {
    en: {
        'm29.title': 'Backgrounds',
        'kind.backgrounds.set': 'Chat background for the place',
        'kind.backgrounds.pick': 'Background chosen by hand',
        'kind.backgrounds.generate': 'Generated background',
        'target.chat-background': 'Chat background',
        'm29.tab': 'Backgrounds',
        'm29.hint':
            "The chat background follows the scene: the place's own background, else the best match from ST's background library by the place name, its surroundings, its state, the time of day and the weather. Only this chat's background changes, never the global one. A background you set yourself is never replaced.",
        'm29.noChat': 'No chat is open.',
        'm29.notLeader': 'Another Maestro tab changes the background on its own; here you can still pick and bind.',
        'm29.noPlaces': 'The «Places» module is off: without it Maestro does not know where the scene is.',

        'm29.now.title': 'Now',
        'm29.now.place': 'Place: {place}',
        'm29.now.noPlace': 'The place is not known yet — the background stays as it is.',
        'm29.now.scene': 'Scene: {scene}',
        'm29.now.sceneUnknown': 'DES has not written the time of day or the weather yet.',
        'm29.owner.none': 'The chat has no background of its own: the global ST background shows.',
        'm29.owner.maestro': 'Chat background set by Maestro: {file} ({source}).',
        'm29.owner.user': 'The chat background is yours: {file}. Maestro does not touch it.',
        'm29.owner.removed':
            'You removed the background Maestro had set, so Maestro no longer changes the background of this chat.',
        'm29.owner.released': 'Chat background: {file}. Maestro will replace it when it finds a fitting one.',
        'm29.source.library': 'picked from the library',
        'm29.source.user': 'bound to the place',
        'm29.source.generated': 'generated in NAI Studio',
        'm29.release': 'Let Maestro choose again',
        'm29.release.hint': 'Forget your background for this chat: Maestro picks one for the place now and later.',

        'm29.tag.morning': 'morning',
        'm29.tag.day': 'day',
        'm29.tag.evening': 'evening',
        'm29.tag.night': 'night',
        'm29.tag.clear': 'clear',
        'm29.tag.cloudy': 'cloudy',
        'm29.tag.rain': 'rain',
        'm29.tag.storm': 'thunderstorm',
        'm29.tag.snow': 'snow',
        'm29.tag.fog': 'fog',
        'm29.tag.spring': 'spring',
        'm29.tag.summer': 'summer',
        'm29.tag.autumn': 'autumn',
        'm29.tag.winter': 'winter',
        'm29.tag.ruined': 'ruined',
        'm29.tag.burning': 'burning',
        'm29.tag.abandoned': 'abandoned',
        'm29.tag.flooded': 'flooded',
        'm29.tag.festive': 'festive',

        'm29.candidates.title': 'For «{place}»',
        'm29.candidates.place': 'Place',
        'm29.candidates.loading': 'Looking through the library…',
        'm29.candidates.none': 'Nothing in the ST background library fits this place.',
        'm29.candidates.score': 'match {score}',
        'm29.candidates.bound': 'bound',
        'm29.candidates.shown': 'on now',
        'm29.action.pick': 'Set',
        'm29.action.pick.hint': "Make it this chat's background now (it stays while the scene is in this place).",
        'm29.action.bind': 'Bind to the place',
        'm29.action.bind.hint': 'Always use it for this place (or as the chosen variant).',
        'm29.bindAs': 'Bind as',
        'm29.bindAs.main': 'main background',
        'm29.bindAs.variant': 'variant: {tag}',

        'm29.bound.title': 'Bound to the place',
        'm29.bound.main': 'Main background',
        'm29.bound.variant': 'Variant: {tags}',
        'm29.bound.none': 'Nothing is bound to this place.',
        'm29.bound.missing': 'not in the library',
        'm29.action.unbind': 'Unbind',

        'm29.library.count': 'Backgrounds in the ST library: {count}.',
        'm29.library.unknown': 'The library has not been read yet.',
        'm29.library.refresh': 'Refresh the list',

        'm29.generate.title': 'Generate a background',
        'm29.generate.hint':
            'NAI Studio draws a background for «{place}» from the place name, its passport and the scene, uploads it to the ST library, and Maestro binds it to the place.',
        'm29.generate.noMatch': 'The library has no fitting background for this place.',
        'm29.generate.button': 'Generate a background',
        'm29.generate.busy': 'Generating…',
        'm29.generate.budget.free':
            'NAI Studio is in «free only» mode: the picture is made at a free size, or not at all if it would cost Anlas.',
        'm29.generate.budget.paid': 'May cost Anlas — NAI Studio asks by its own rules before spending.',
        'm29.generate.budget.unknown': 'The cost is up to NAI Studio and its Anlas settings.',
        'm29.generate.economy': 'In «Economy» mode backgrounds come from the library only.',
        'm29.generate.missing': 'Needs NAI Studio 0.12 or newer with background generation.',
        'm29.generate.unavailable': 'NAI Studio cannot generate backgrounds right now (off, or too old).',
        'm29.generate.freeOnly':
            'NAI Studio is in «free only» mode and this background would cost Anlas, so nothing was generated. Turn the limit off in NAI Studio if you want to spend Anlas on it.',
        'm29.generate.failed': 'The background was not generated: {error}',
        'm29.generate.empty': 'NAI Studio returned no picture.',
        'm29.generate.pinned':
            'The new background is bound to the place; your own chat background stays until you let me choose again.',
        'm29.generate.done': 'A new background for «{place}» is ready: it is in the library and bound to the place.',
        'm29.offer': 'No background in the library fits «{place}». Generate one in NAI Studio?',

        'm29.journal.set': 'Chat background for «{place}»',
        'm29.journal.pick': 'Set the background you chose for «{place}»',
        'm29.journal.bound': 'Set the background bound to «{place}»',
        'm29.journal.generate': 'Set the newly generated background for «{place}»',
        'm29.notice.set': 'Changed the chat background to fit «{place}».',
        'm29.proposal.library':
            'This background from your library fits the place best. Only the background of this chat changes.',
        'm29.proposal.user': 'This is the background you bound to the place. Only the background of this chat changes.',
        'm29.proposal.generated':
            'NAI Studio generated this background for the place. Only the background of this chat changes.',
        'm29.details.file': 'Background file: {file}',
        'm29.details.variant': 'Variant: {variant}',
        'm29.target.other': 'another background',

        'm29.error.stale': 'The chat background changed meanwhile, so I left it alone.',
        'm29.error.noPlaces': 'The «Places» module is off.',
        'm29.error.noPlace': 'This place is not among the places of this chat.',
        'm29.error.variant': 'Unknown variant: use a time of day, weather or season.',
        'm29.error.noChat': 'No chat is open.',

        'm29.settings.title': 'Settings',
        'm29.settings.auto': 'Change the chat background on my own',
        'm29.settings.auto.hint':
            'By place, time of day and weather; library only. Generation is always a button. Off: only your picks.',
        'm29.settings.threshold': 'Match threshold',
        'm29.settings.threshold.hint':
            'How sure a library match must be to be set automatically: 3 = the place type is in the file name (a tavern for a tavern); higher is stricter.',
        'm29.settings.variants': 'Variants by time of day and weather',
        'm29.settings.variants.hint':
            'Night, rain or winter pick the matching file («tavern night») and change the background when DES moves them.',
    },
    ru: {
        'm29.title': 'Фоны',
        'kind.backgrounds.set': 'Смена фона чата под место',
        'kind.backgrounds.pick': 'Фон, выбранный вручную',
        'kind.backgrounds.generate': 'Сгенерированный фон',
        'target.chat-background': 'Фон чата',
        'm29.tab': 'Фоны',
        'm29.hint':
            'Фон чата следует за сценой: свой фон места, а если его нет — лучший из библиотеки фонов ST по названию места, тому, что вокруг, его состоянию, времени суток и погоде. Меняется только фон этого чата, общий фон не трогается. Фон, который ты поставил сам, Maestro не заменяет.',
        'm29.noChat': 'Чат не открыт.',
        'm29.notLeader': 'Фон сам меняет другая вкладка Maestro; здесь можно выбирать и привязывать вручную.',
        'm29.noPlaces': 'Модуль «Места» выключен: без него Maestro не знает, где идёт сцена.',

        'm29.now.title': 'Сейчас',
        'm29.now.place': 'Место: {place}',
        'm29.now.noPlace': 'Место пока не определено — фон остаётся прежним.',
        'm29.now.scene': 'Сцена: {scene}',
        'm29.now.sceneUnknown': 'DES ещё не написал время суток и погоду.',
        'm29.owner.none': 'Своего фона у чата нет — виден общий фон ST.',
        'm29.owner.maestro': 'Фон чата поставил Maestro: {file} ({source}).',
        'm29.owner.user': 'Фон чата — твой: {file}. Maestro его не трогает.',
        'm29.owner.removed': 'Ты убрал фон, который ставил Maestro, — больше он не меняет фон в этом чате.',
        'm29.owner.released': 'Фон чата: {file}. Maestro сменит его, когда найдёт подходящий.',
        'm29.source.library': 'подобран в библиотеке',
        'm29.source.user': 'привязан к месту',
        'm29.source.generated': 'сгенерирован в NAI Studio',
        'm29.release': 'Снова выбирать самому',
        'm29.release.hint': 'Забыть твой фон для этого чата: Maestro подберёт фон месту сейчас и дальше.',

        'm29.tag.morning': 'утро',
        'm29.tag.day': 'день',
        'm29.tag.evening': 'вечер',
        'm29.tag.night': 'ночь',
        'm29.tag.clear': 'ясно',
        'm29.tag.cloudy': 'облачно',
        'm29.tag.rain': 'дождь',
        'm29.tag.storm': 'гроза',
        'm29.tag.snow': 'снег',
        'm29.tag.fog': 'туман',
        'm29.tag.spring': 'весна',
        'm29.tag.summer': 'лето',
        'm29.tag.autumn': 'осень',
        'm29.tag.winter': 'зима',
        'm29.tag.ruined': 'разрушено',
        'm29.tag.burning': 'в огне',
        'm29.tag.abandoned': 'заброшено',
        'm29.tag.flooded': 'затоплено',
        'm29.tag.festive': 'празднично',

        'm29.candidates.title': 'Для «{place}»',
        'm29.candidates.place': 'Место',
        'm29.candidates.loading': 'Смотрю библиотеку…',
        'm29.candidates.none': 'В библиотеке фонов ST для этого места ничего не нашлось.',
        'm29.candidates.score': 'совпадение {score}',
        'm29.candidates.bound': 'привязан',
        'm29.candidates.shown': 'стоит сейчас',
        'm29.action.pick': 'Поставить',
        'm29.action.pick.hint': 'Сделать фоном этого чата сейчас (останется, пока сцена в этом месте).',
        'm29.action.bind': 'Привязать к месту',
        'm29.action.bind.hint': 'Всегда ставить его для этого места (или как выбранный вариант).',
        'm29.bindAs': 'Привязывать как',
        'm29.bindAs.main': 'основной фон',
        'm29.bindAs.variant': 'вариант: {tag}',

        'm29.bound.title': 'Привязано к месту',
        'm29.bound.main': 'Основной фон',
        'm29.bound.variant': 'Вариант: {tags}',
        'm29.bound.none': 'К этому месту ничего не привязано.',
        'm29.bound.missing': 'нет в библиотеке',
        'm29.action.unbind': 'Отвязать',

        'm29.library.count': 'Фонов в библиотеке ST: {count}.',
        'm29.library.unknown': 'Библиотека ещё не прочитана.',
        'm29.library.refresh': 'Обновить список',

        'm29.generate.title': 'Сгенерировать фон',
        'm29.generate.hint':
            'NAI Studio нарисует фон для «{place}» по названию места, его паспорту и сцене и загрузит его в библиотеку ST, а Maestro привяжет его к месту.',
        'm29.generate.noMatch': 'Подходящего фона для этого места в библиотеке нет.',
        'm29.generate.button': 'Сгенерировать фон',
        'm29.generate.busy': 'Генерирую…',
        'm29.generate.budget.free':
            'В NAI Studio включено «только бесплатно»: картинка выйдет бесплатного размера, а если стоила бы Anlas — не выйдет вовсе.',
        'm29.generate.budget.paid': 'Может стоить Anlas — NAI Studio спросит перед тратой по своим правилам.',
        'm29.generate.budget.unknown': 'Стоимость определяет NAI Studio по своим настройкам Anlas.',
        'm29.generate.economy': 'В режиме «Экономный» фоны берутся только из библиотеки.',
        'm29.generate.missing': 'Нужна NAI Studio 0.12 или новее — с генерацией фонов.',
        'm29.generate.unavailable': 'NAI Studio сейчас не умеет генерировать фоны (выключена или старая версия).',
        'm29.generate.freeOnly':
            'В NAI Studio включено «только бесплатно», а этот фон стоил бы Anlas, поэтому он не сгенерирован. Если готов потратить Anlas, сними ограничение в NAI Studio.',
        'm29.generate.failed': 'Фон не сгенерирован: {error}',
        'm29.generate.empty': 'NAI Studio не вернула картинку.',
        'm29.generate.pinned':
            'Новый фон привязан к месту, но сейчас стоит твой фон чата — он останется, пока ты снова не доверишь выбор мне.',
        'm29.generate.done': 'Готов новый фон для «{place}»: он в библиотеке и привязан к месту.',
        'm29.offer': 'Для «{place}» в библиотеке нет подходящего фона. Сгенерировать его в NAI Studio?',

        'm29.journal.set': 'Фон чата под место «{place}»',
        'm29.journal.pick': 'Поставил выбранный тобой фон для «{place}»',
        'm29.journal.bound': 'Поставил фон, привязанный к «{place}»',
        'm29.journal.generate': 'Поставил новый сгенерированный фон для «{place}»',
        'm29.notice.set': 'Сменил фон чата под место «{place}».',
        'm29.proposal.library':
            'Из твоей библиотеки фонов месту лучше всего подходит этот. Сменится только фон этого чата.',
        'm29.proposal.user': 'Это фон, который ты привязал к месту. Сменится только фон этого чата.',
        'm29.proposal.generated': 'Этот фон NAI Studio сгенерировала для места. Сменится только фон этого чата.',
        'm29.details.file': 'Файл фона: {file}',
        'm29.details.variant': 'Вариант: {variant}',
        'm29.target.other': 'другой фон',

        'm29.error.stale': 'Фон чата за это время сменился, поэтому я ничего не менял.',
        'm29.error.noPlaces': 'Модуль «Места» выключен.',
        'm29.error.noPlace': 'Этого места нет среди мест чата.',
        'm29.error.variant': 'Неизвестный вариант: нужно время суток, погода или время года.',
        'm29.error.noChat': 'Чат не открыт.',

        'm29.settings.title': 'Настройки',
        'm29.settings.auto': 'Менять фон чата самому',
        'm29.settings.auto.hint':
            'По месту, времени суток и погоде, только из библиотеки. Генерация — всегда по кнопке. Выключено — только твой выбор.',
        'm29.settings.threshold': 'Порог совпадения',
        'm29.settings.threshold.hint':
            'Насколько точным должно быть совпадение, чтобы фон ставился сам: 3 — тип места есть в имени файла (таверна для таверны); больше — строже.',
        'm29.settings.variants': 'Варианты по времени суток и погоде',
        'm29.settings.variants.hint':
            'Ночь, дождь или зима выбирают подходящий файл («tavern night») и меняют фон, когда DES их сдвигает.',
    },
};
