// Strings of M26 «Живой канон» (`m26.*`). Russian is the primary UI language; the user is addressed as «ты».
import type { I18nParts } from '../../shared/contracts';

export const LIVING_STRINGS: I18nParts = {
    en: {
        'm26.title': 'Living canon',
        'm26.tab': 'Living canon',
        'kind.living.fact': 'New facts about the world',
        'kind.living.disputed': 'Disputed facts about the world',
        'target.living-fact': 'Fact about the world',
        'm26.field.name': 'Name',
        'm26.field.type': 'What it is',
        'm26.field.russian': 'In short',
        'm26.profileTask': 'Living canon (batch extraction)',
        'm26.hint':
            'What the model invents — a holiday, a tavern, a family, an old war — is saved as provisional canon after you send your next message (at most {k} per turn). It becomes confirmed canon when you mention it yourself, accept it here, when it comes up again on its own, or after {n} turns without contradictions. Swiping, editing or deleting the reply takes back its provisional facts; confirmed canon stays.',
        'm26.noChat': 'No chat is open.',
        'm26.group': 'Group chats are not supported: Maestro sleeps here.',
        'm26.noCanon': 'New facts have nowhere to go: “Chat canon” is off.',
        'm26.enableCanon': 'Turn on',
        'm26.drafts': 'In the last reply ({count})',
        'm26.drafts.hint': 'Nothing is saved until you send your next message; a swipe drops these.',
        'm26.draft.extends': 'another name of «{name}»',
        'm26.provisional': 'Provisional ({count})',
        'm26.provisional.empty': 'No provisional facts.',
        'm26.disputed': 'Disputed ({count})',
        'm26.disputed.hint': 'These contradict the canon or the lore; decide in the Inbox.',
        'm26.disputed.pending': 'waiting in the Inbox',
        'm26.disputed.kept': 'kept despite the contradiction',
        'm26.disputed.inbox': 'Inbox',
        'm26.confirmed': 'Confirmed recently ({count})',
        'm26.confirmed.empty': 'Nothing confirmed yet.',
        'm26.survived': 'turns without contradictions: {count} of {total}',
        'm26.source': 'message #{index}',
        'm26.source.hint': 'Show the message the fact came from',
        'm26.keys': 'Keys: {keys}',
        'm26.text': 'Canon text (English): {text}',
        'm26.noText': 'The English text comes with the next extraction.',
        'm26.conflict': 'Contradiction: {conflict}',
        'm26.conflict.line': '{label}: «{statement}» — «{other}»',
        'm26.accept': 'Confirm',
        'm26.accept.hint': 'Make it confirmed canon (only when nothing contradicts it)',
        'm26.drop': 'Drop',
        'm26.drop.hint': 'Remove it from the canon; this name will not be offered again',
        'm26.acceptAll': 'Confirm all provisional',
        'm26.acceptAll.done': 'Confirmed: {confirmed}. Held back by contradictions: {blocked}.',
        'm26.accept.conflict': 'Cannot confirm “{name}”: it disagrees with what is already known — {against}.',
        'm26.extract': 'Extract now',
        'm26.extract.hint':
            'Ask the background model for English canon texts and for invented things the quick search missed',
        'm26.extract.queued': 'I will look for new facts in a pause between replies.',
        'm26.extract.never': 'No extraction yet.',
        'm26.extract.last': 'Last extraction: {when} — new facts: {added}, texts: {updated}.',
        'm26.extract.failed': 'Last extraction ({when}) failed: {error}.',
        'm26.reason.userMentioned': 'you mentioned it',
        'm26.reason.userAccepted': 'you confirmed it',
        'm26.reason.resurfaced': 'came up again by itself',
        'm26.reason.survived': 'survived the turns without contradictions',
        'm26.type.tradition': 'tradition',
        'm26.type.place': 'place',
        'm26.type.item': 'item',
        'm26.type.faction': 'faction',
        'm26.type.event': 'event',
        'm26.type.person': 'person',
        'm26.type.other': 'other',
        'm26.settings': 'Settings',
        'm26.settings.k': 'New facts per turn (K)',
        'm26.settings.kHint': 'The most significant ones are kept; 0 stops new facts.',
        'm26.settings.survive': 'Turns to confirm (N)',
        'm26.settings.surviveHint':
            'A provisional fact is confirmed after this many turns without contradictions or edits; 0 turns it off.',
        'm26.settings.extract': 'Extraction every … messages',
        'm26.settings.extractHint': '0 — only with the «Extract now» button.',
        'm26.proposal.fact': 'A new fact about the world: {name}',
        'm26.proposal.factBody':
            '{statement}\nI will remember it as provisional: it becomes firm canon once the story confirms it.',
        'm26.proposal.disputed': 'Something new disagrees with the story: {name}',
        'm26.proposal.existing': 'A provisional fact is in doubt: {name}',
        'm26.proposal.conflict': 'The story disagrees with a known fact: {name}',
        'm26.proposal.newBody':
            '{statement}\nThis does not fit what is already known: {against}.\nAccept — I remember the new fact as provisional; reject — I forget it.',
        'm26.proposal.existingBody':
            '{statement}\nThis does not fit what is already known: {against}.\nAccept — it stays provisional; reject — I remove it.',
        'm26.proposal.conflictBody':
            'The reply tells it differently from what is written about “{name}”.\nAccept — I trust the story: the fact becomes provisional again, in the new words. Reject — I keep it as it was.',
        'm26.against.unknown': 'the chat canon',
        'm26.statement': '{type}: {name}.',
        'm26.details.book': 'Canon book: {book}',
        'm26.details.keys': 'Keys: {keys}',
        'm26.details.text': 'Canon text (English): {text}',
        'm26.details.conflict': 'Contradiction:\n{conflict}',
        'm26.notice.what': '{name} ({type})',
        'm26.notice.captured': 'Remembered as provisional: {what}',
        'm26.notice.capturedMany.one': 'Remembered {count} new fact about the world (provisional)',
        'm26.notice.capturedMany.few': 'Remembered {count} new facts about the world (provisional)',
        'm26.notice.capturedMany.many': 'Remembered {count} new facts about the world (provisional)',
        'm26.notice.confirmed': 'Fact confirmed: {name} — {reason}',
        'm26.notice.confirmedMany.one': '{count} fact about the world was confirmed',
        'm26.notice.confirmedMany.few': '{count} facts about the world were confirmed',
        'm26.notice.confirmedMany.many': '{count} facts about the world were confirmed',
        'm26.notice.dropped.swiped': 'Forgot the provisional fact “{name}”: its reply was swiped.',
        'm26.notice.dropped.edited': 'Forgot the provisional fact “{name}”: its reply was edited.',
        'm26.notice.dropped.deleted': 'Forgot the provisional fact “{name}”: its reply was deleted.',
        'm26.notice.droppedMany.one': 'Forgot {count} provisional fact from changed replies',
        'm26.notice.droppedMany.few': 'Forgot {count} provisional facts from changed replies',
        'm26.notice.droppedMany.many': 'Forgot {count} provisional facts from changed replies',
        'm26.notice.duplicate': 'Removed “{name}”: it is another name of “{other}”.',
        'm26.error.noCanon': '“Chat canon” is off: there is nowhere to write the fact.',
        'm26.error.stale': 'The reply this fact came from has changed.',
        'm26.error.payload': 'This card cannot be read.',
    },
    ru: {
        'm26.title': 'Живой канон',
        'm26.tab': 'Живой канон',
        'kind.living.fact': 'Новые факты о мире',
        'kind.living.disputed': 'Спорные факты о мире',
        'target.living-fact': 'Факт о мире',
        'm26.field.name': 'Название',
        'm26.field.type': 'Что это',
        'm26.field.russian': 'Коротко',
        'm26.profileTask': 'Живой канон (пакетное извлечение)',
        'm26.hint':
            'То, что придумала модель, — праздник, таверна, род, давняя война — после отправки твоего следующего сообщения сохраняется в канон как пробное (не больше {k} за ход). Подтверждённым каноном оно становится, если ты сам его упомянешь, примешь здесь, если оно само всплывёт снова или продержится {n} ходов без противоречий. Свайп, правка или удаление ответа убирают его пробные факты; подтверждённый канон остаётся.',
        'm26.noChat': 'Чат не открыт.',
        'm26.group': 'Групповые чаты не поддерживаются: здесь Maestro спит.',
        'm26.noCanon': 'Новые факты некуда записать: выключен «Канон чата».',
        'm26.enableCanon': 'Включить',
        'm26.drafts': 'В последнем ответе ({count})',
        'm26.drafts.hint': 'Пока ты не отправил следующее сообщение, ничего не сохраняется; свайп их отбросит.',
        'm26.draft.extends': 'другое название для «{name}»',
        'm26.provisional': 'Пробные ({count})',
        'm26.provisional.empty': 'Пробных фактов нет.',
        'm26.disputed': 'Спорные ({count})',
        'm26.disputed.hint': 'Они противоречат канону или лору — решение во «Входящих».',
        'm26.disputed.pending': 'ждёт во «Входящих»',
        'm26.disputed.kept': 'оставлен вопреки противоречию',
        'm26.disputed.inbox': 'Входящие',
        'm26.confirmed': 'Недавно подтверждённые ({count})',
        'm26.confirmed.empty': 'Пока ничего не подтверждено.',
        'm26.survived': 'ходов без противоречий: {count} из {total}',
        'm26.source': 'сообщение #{index}',
        'm26.source.hint': 'Показать сообщение, из которого взят факт',
        'm26.keys': 'Ключи: {keys}',
        'm26.text': 'Текст канона (англ.): {text}',
        'm26.noText': 'Английский текст появится при ближайшем извлечении.',
        'm26.conflict': 'Противоречие: {conflict}',
        'm26.conflict.line': '{label}: «{statement}» — «{other}»',
        'm26.accept': 'Подтвердить',
        'm26.accept.hint': 'Сделать подтверждённым каноном (только если ему ничего не противоречит)',
        'm26.drop': 'Отбросить',
        'm26.drop.hint': 'Убрать из канона; это название больше не предлагать',
        'm26.acceptAll': 'Принять все пробные',
        'm26.acceptAll.done': 'Подтвердил: {confirmed}. Задержал из-за противоречий: {blocked}.',
        'm26.accept.conflict': 'Не могу подтвердить «{name}»: это спорит с уже известным — {against}.',
        'm26.extract': 'Извлечь сейчас',
        'm26.extract.hint':
            'Попросить фоновую модель написать английские тексты канона и найти выдуманное, что пропустил быстрый поиск',
        'm26.extract.queued': 'Поищу новые факты в паузе между ответами.',
        'm26.extract.never': 'Извлечений ещё не было.',
        'm26.extract.last': 'Последнее извлечение: {when} — новых фактов: {added}, текстов: {updated}.',
        'm26.extract.failed': 'Последнее извлечение ({when}) не удалось: {error}.',
        'm26.reason.userMentioned': 'ты его упомянул',
        'm26.reason.userAccepted': 'ты его подтвердил',
        'm26.reason.resurfaced': 'всплыл в истории снова',
        'm26.reason.survived': 'продержался без противоречий',
        'm26.type.tradition': 'традиция',
        'm26.type.place': 'место',
        'm26.type.item': 'предмет',
        'm26.type.faction': 'фракция',
        'm26.type.event': 'событие',
        'm26.type.person': 'персонаж',
        'm26.type.other': 'другое',
        'm26.settings': 'Настройки',
        'm26.settings.k': 'Новых фактов за ход (K)',
        'm26.settings.kHint': 'Остаются самые значимые; 0 — новые факты не добавляются.',
        'm26.settings.survive': 'Ходов до подтверждения (N)',
        'm26.settings.surviveHint':
            'Пробный факт подтверждается, если столько ходов обошлось без противоречий и правок; 0 — так не подтверждать.',
        'm26.settings.extract': 'Извлечение каждые … сообщений',
        'm26.settings.extractHint': '0 — только по кнопке «Извлечь сейчас».',
        'm26.proposal.fact': 'Новый факт о мире: {name}',
        'm26.proposal.factBody':
            '{statement}\nЗапомню его пробно: твёрдым каноном он станет, когда история его подтвердит.',
        'm26.proposal.disputed': 'Новое спорит с историей: {name}',
        'm26.proposal.existing': 'Пробный факт под вопросом: {name}',
        'm26.proposal.conflict': 'История спорит с известным фактом: {name}',
        'm26.proposal.newBody':
            '{statement}\nЭто не сходится с уже известным: {against}.\nПринять — запомню новое пробно, отклонить — забуду его.',
        'm26.proposal.existingBody':
            '{statement}\nЭто не сходится с уже известным: {against}.\nПринять — оставлю его пробным, отклонить — уберу.',
        'm26.proposal.conflictBody':
            'В ответе сказано иначе, чем записано о «{name}».\nПринять — поверю истории: факт снова станет пробным, с новыми словами. Отклонить — оставлю как было.',
        'm26.against.unknown': 'канон чата',
        'm26.statement': '{type}: {name}.',
        'm26.details.book': 'Книга канона: {book}',
        'm26.details.keys': 'Ключи: {keys}',
        'm26.details.text': 'Текст канона (англ.): {text}',
        'm26.details.conflict': 'Противоречие:\n{conflict}',
        'm26.notice.what': '{name} ({type})',
        'm26.notice.captured': 'Запомнил пробно: {what}',
        'm26.notice.capturedMany.one': 'Запомнил {count} новый факт о мире (пробно)',
        'm26.notice.capturedMany.few': 'Запомнил {count} новых факта о мире (пробно)',
        'm26.notice.capturedMany.many': 'Запомнил {count} новых фактов о мире (пробно)',
        'm26.notice.confirmed': 'Факт подтвердился: {name} — {reason}',
        'm26.notice.confirmedMany.one': 'Подтвердился {count} факт о мире',
        'm26.notice.confirmedMany.few': 'Подтвердились {count} факта о мире',
        'm26.notice.confirmedMany.many': 'Подтвердились {count} фактов о мире',
        'm26.notice.dropped.swiped': 'Забыл пробный факт «{name}»: ответ, где он появился, заменён свайпом.',
        'm26.notice.dropped.edited': 'Забыл пробный факт «{name}»: ответ, где он появился, изменён.',
        'm26.notice.dropped.deleted': 'Забыл пробный факт «{name}»: ответ, где он появился, удалён.',
        'm26.notice.droppedMany.one': 'Забыл {count} пробный факт из изменённых ответов',
        'm26.notice.droppedMany.few': 'Забыл {count} пробных факта из изменённых ответов',
        'm26.notice.droppedMany.many': 'Забыл {count} пробных фактов из изменённых ответов',
        'm26.notice.duplicate': 'Убрал «{name}»: это другое название «{other}».',
        'm26.error.noCanon': 'Выключен «Канон чата»: записать факт некуда.',
        'm26.error.stale': 'Ответ, из которого взят факт, изменился.',
        'm26.error.payload': 'Не удаётся прочитать эту карточку.',
    },
};
