// Strings of M26 «Живой канон» (`m26.*`). Russian is the primary UI language; the user is addressed as «ты».
import type { I18nParts } from '../../shared/contracts';

export const LIVING_STRINGS: I18nParts = {
    en: {
        'm26.title': 'Living canon',
        'm26.tab': 'Living canon',
        'kind.living.fact': 'Living canon: a new provisional fact',
        'kind.living.disputed': 'Living canon: a disputed invented fact',
        'm26.profileTask': 'Living canon (batch extraction)',
        'm26.hint':
            'What the model invents — a holiday, a tavern, a family, an old war — is saved as provisional canon after you send your next message (at most {k} per turn). It becomes confirmed canon when you mention it yourself, accept it here, when it comes up again on its own, or after {n} turns without contradictions. Swiping, editing or deleting the reply takes back its provisional facts; confirmed canon stays.',
        'm26.noChat': 'No chat is open.',
        'm26.group': 'Group chats are not supported: Maestro sleeps here.',
        'm26.noCanon': 'The chat canon (M6) is off: living facts cannot be saved.',
        'm26.drafts': 'In the last reply ({count})',
        'm26.drafts.hint': 'Nothing is saved until you send your next message; a swipe drops these.',
        'm26.draft.extends': 'another name of «{name}»',
        'm26.provisional': 'Provisional ({count})',
        'm26.provisional.empty': 'No provisional facts.',
        'm26.disputed': 'Disputed ({count})',
        'm26.disputed.hint': 'These contradict the canon or the lore; decide in the Inbox.',
        'm26.disputed.pending': 'waiting in the Inbox',
        'm26.disputed.kept': 'kept despite the contradiction',
        'm26.disputed.inbox': 'Inbox',
        'm26.confirmed': 'Confirmed recently ({count})',
        'm26.confirmed.empty': 'Nothing confirmed yet.',
        'm26.survived': 'turns without contradictions: {count} of {total}',
        'm26.source': 'message #{index}',
        'm26.source.hint': 'Show the message the fact came from',
        'm26.keys': 'Keys: {keys}',
        'm26.text': 'Canon text: {text}',
        'm26.noText': 'The English text comes with the next extraction.',
        'm26.conflict': 'Contradiction: {conflict}',
        'm26.conflict.line': '{label}: «{statement}» — «{other}»',
        'm26.accept': 'Confirm',
        'm26.accept.hint': 'Make it confirmed canon (only when nothing contradicts it)',
        'm26.drop': 'Drop',
        'm26.drop.hint': 'Remove it from the canon; this name will not be offered again',
        'm26.acceptAll': 'Confirm all provisional',
        'm26.acceptAll.done': 'Confirmed: {confirmed}; held back by contradictions: {blocked}.',
        'm26.accept.conflict': '«{name}» is not confirmed: {conflict}',
        'm26.extract': 'Extract now',
        'm26.extract.hint':
            'Ask the background model for English canon texts and for invented things the quick search missed',
        'm26.extract.queued': 'The extraction is queued; it runs in a pause between replies.',
        'm26.extract.never': 'No extraction yet.',
        'm26.extract.last': 'Last extraction: {when} — new facts: {added}, texts: {updated}.',
        'm26.extract.failed': 'Last extraction ({when}) failed: {error}.',
        'm26.reason.userMentioned': 'you mentioned it',
        'm26.reason.userAccepted': 'you confirmed it',
        'm26.reason.resurfaced': 'came up again by itself',
        'm26.reason.survived': 'survived the turns without contradictions',
        'm26.type.tradition': 'tradition',
        'm26.type.place': 'place',
        'm26.type.item': 'item',
        'm26.type.faction': 'faction',
        'm26.type.event': 'event',
        'm26.type.person': 'person',
        'm26.type.other': 'other',
        'm26.settings': 'Settings',
        'm26.settings.k': 'New facts per turn (K)',
        'm26.settings.kHint': 'The most significant ones are kept; 0 stops new facts.',
        'm26.settings.survive': 'Turns to confirm (N)',
        'm26.settings.surviveHint':
            'A provisional fact is confirmed after this many turns without contradictions or edits; 0 turns it off.',
        'm26.settings.extract': 'Extraction every … messages',
        'm26.settings.extractHint': '0 — only with the «Extract now» button.',
        'm26.proposal.fact': 'New provisional fact: {name}',
        'm26.proposal.disputed': 'Disputed invented fact: {name}',
        'm26.proposal.conflict': 'The story contradicts confirmed canon: {name}',
        'm26.proposal.newBody':
            'The reply says: {quote}\nIt contradicts: {conflict}\nAccept to save it as provisional canon, reject to drop it.',
        'm26.proposal.existingBody':
            'Provisional fact: {quote}\nIt contradicts: {conflict}\nAccept to keep it provisional, reject to remove it.',
        'm26.proposal.conflictBody':
            'The reply says: {quote}\nThe canon says otherwise: {conflict}\nAccept if the story is right (the entry becomes provisional again with the new statement), reject to keep the canon as it is.',
        'm26.error.noCanon': 'The chat canon (M6) is off.',
        'm26.error.stale': 'The message this fact came from has changed.',
        'm26.error.payload': 'This card cannot be read.',
    },
    ru: {
        'm26.title': 'Живой канон',
        'm26.tab': 'Живой канон',
        'kind.living.fact': 'Живой канон: новый пробный факт',
        'kind.living.disputed': 'Живой канон: спорный выдуманный факт',
        'm26.profileTask': 'Живой канон (пакетное извлечение)',
        'm26.hint':
            'То, что придумала модель, — праздник, таверна, род, давняя война — после отправки твоего следующего сообщения сохраняется в канон как пробное (не больше {k} за ход). Подтверждённым каноном оно становится, если ты сам его упомянешь, примешь здесь, если оно само всплывёт снова или продержится {n} ходов без противоречий. Свайп, правка или удаление ответа убирают его пробные факты; подтверждённый канон остаётся.',
        'm26.noChat': 'Чат не открыт.',
        'm26.group': 'Групповые чаты не поддерживаются: здесь Maestro спит.',
        'm26.noCanon': 'Канон чата (M6) выключен — сохранять живые факты некуда.',
        'm26.drafts': 'В последнем ответе ({count})',
        'm26.drafts.hint': 'Пока ты не отправил следующее сообщение, ничего не сохраняется; свайп их отбросит.',
        'm26.draft.extends': 'другое название для «{name}»',
        'm26.provisional': 'Пробные ({count})',
        'm26.provisional.empty': 'Пробных фактов нет.',
        'm26.disputed': 'Спорные ({count})',
        'm26.disputed.hint': 'Они противоречат канону или лору — решение во «Входящих».',
        'm26.disputed.pending': 'ждёт во «Входящих»',
        'm26.disputed.kept': 'оставлен вопреки противоречию',
        'm26.disputed.inbox': 'Входящие',
        'm26.confirmed': 'Недавно подтверждённые ({count})',
        'm26.confirmed.empty': 'Пока ничего не подтверждено.',
        'm26.survived': 'ходов без противоречий: {count} из {total}',
        'm26.source': 'сообщение #{index}',
        'm26.source.hint': 'Показать сообщение, из которого взят факт',
        'm26.keys': 'Ключи: {keys}',
        'm26.text': 'Текст канона: {text}',
        'm26.noText': 'Английский текст появится при ближайшем извлечении.',
        'm26.conflict': 'Противоречие: {conflict}',
        'm26.conflict.line': '{label}: «{statement}» — «{other}»',
        'm26.accept': 'Подтвердить',
        'm26.accept.hint': 'Сделать подтверждённым каноном (только если ему ничего не противоречит)',
        'm26.drop': 'Отбросить',
        'm26.drop.hint': 'Убрать из канона; это название больше не предлагать',
        'm26.acceptAll': 'Принять все пробные',
        'm26.acceptAll.done': 'Подтверждено: {confirmed}; задержано из-за противоречий: {blocked}.',
        'm26.accept.conflict': '«{name}» не подтверждён: {conflict}',
        'm26.extract': 'Извлечь сейчас',
        'm26.extract.hint':
            'Попросить фоновую модель написать английские тексты канона и найти выдуманное, что пропустил быстрый поиск',
        'm26.extract.queued': 'Извлечение в очереди — оно пройдёт в паузе между ответами.',
        'm26.extract.never': 'Извлечений ещё не было.',
        'm26.extract.last': 'Последнее извлечение: {when} — новых фактов: {added}, текстов: {updated}.',
        'm26.extract.failed': 'Последнее извлечение ({when}) не удалось: {error}.',
        'm26.reason.userMentioned': 'ты его упомянул',
        'm26.reason.userAccepted': 'ты его подтвердил',
        'm26.reason.resurfaced': 'всплыло само',
        'm26.reason.survived': 'продержалось без противоречий',
        'm26.type.tradition': 'традиция',
        'm26.type.place': 'место',
        'm26.type.item': 'предмет',
        'm26.type.faction': 'фракция',
        'm26.type.event': 'событие',
        'm26.type.person': 'персонаж',
        'm26.type.other': 'другое',
        'm26.settings': 'Настройки',
        'm26.settings.k': 'Новых фактов за ход (K)',
        'm26.settings.kHint': 'Остаются самые значимые; 0 — новые факты не добавляются.',
        'm26.settings.survive': 'Ходов до подтверждения (N)',
        'm26.settings.surviveHint':
            'Пробный факт подтверждается, если столько ходов обошлось без противоречий и правок; 0 — так не подтверждать.',
        'm26.settings.extract': 'Извлечение каждые … сообщений',
        'm26.settings.extractHint': '0 — только по кнопке «Извлечь сейчас».',
        'm26.proposal.fact': 'Новый пробный факт: {name}',
        'm26.proposal.disputed': 'Спорный выдуманный факт: {name}',
        'm26.proposal.conflict': 'История противоречит подтверждённому канону: {name}',
        'm26.proposal.newBody':
            'В ответе: {quote}\nПротиворечит: {conflict}\nПринять — сохранить как пробный канон, отклонить — отбросить.',
        'm26.proposal.existingBody':
            'Пробный факт: {quote}\nПротиворечит: {conflict}\nПринять — оставить пробным, отклонить — убрать.',
        'm26.proposal.conflictBody':
            'В ответе: {quote}\nВ каноне иначе: {conflict}\nПринять, если права история (запись снова станет пробной с новым утверждением), отклонить — оставить канон как есть.',
        'm26.error.noCanon': 'Канон чата (M6) выключен.',
        'm26.error.stale': 'Сообщение, из которого взят факт, изменилось.',
        'm26.error.payload': 'Не удаётся прочитать эту карточку.',
    },
};
