// Strings of M15 «Голоса персонажей» (`m15.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const VOICES_STRINGS: I18nParts = {
    en: {
        'm15.title': 'Character voices',
        'm15.tab': 'Voices',
        'm15.noChat': 'No chat is open.',
        'm15.cards.title': 'Cards for the next reply',
        'm15.cards.hint':
            'One short card for everyone in the scene now: how they speak, their character (MBTI, and whether they are at their best right now), how they feel about your persona and what they want. It comes from the CarrotKernel character sheets and the DES tracker. The cards go near the end of the prompt instead of CarrotKernel’s «Character Consistency» hint.',
        'm15.cards.empty':
            'No cards: by the DES tracker nobody is in the scene, or nothing is known about the characters present.',
        'm15.cards.summary': 'Cards: {count} · {tokens} of {budget} tokens',
        'm15.budget.architect': 'budget from the Architect',
        'm15.budget.cap': 'own limit',
        'm15.tokens': '{count} tokens',
        'm15.trimmed': 'Shortened to fit: {steps}.',
        'm15.trim.goals': 'goals left out',
        'm15.trim.bonds': 'attitudes between characters left out',
        'm15.trim.speech': 'speech shortened',
        'm15.trim.state': 'current state left out',
        'm15.trim.extras': 'extra fields left out',
        'm15.trim.cards': 'some cards left out',
        'm15.dropped': 'Did not fit: {names}.',
        'm15.bonds': 'Between characters',
        'm15.preview': 'Everything as the model sees it',
        'm15.loading': 'Some character sheets are still loading; the cards will fill in.',
        'm15.quiet.title': 'CarrotKernel quiet mode',
        'm15.quiet.hint':
            'While the model gets these cards, Maestro takes the similar CarrotKernel hint («Character Consistency») out of the prompt, so the model does not read the same twice. CarrotKernel’s settings stay as they are, and DES-RU is asked not to rebuild the hint. Turn the module off and everything works as before.',
        'm15.quiet.ck.removed': 'CarrotKernel hint taken out ✓ (last reply: −{tokens} tokens, {time})',
        'm15.quiet.ck.absent': 'CarrotKernel hint taken out ✓ (CarrotKernel sent none last time)',
        'm15.quiet.ck.notFound': 'CarrotKernel hint not taken out ✗ — it was not found in the last prompt',
        'm15.quiet.ck.waiting': 'The CarrotKernel hint is taken out from the next reply on',
        'm15.quiet.ck.idle': 'The CarrotKernel hint stays: there are no cards',
        'm15.quiet.desru.told': 'DES-RU knows ✓ — it no longer rebuilds the hint',
        'm15.quiet.desru.notTold': 'DES-RU does not know ✗ — the request did not get through',
        'm15.quiet.desru.absent': 'No need to tell DES-RU (no DES-RU 0.8+)',
        'm15.quiet.dramatis.merged': 'The cards go into the Dramatis block now (one block with motives and speech) ✓',
        'm15.quiet.dramatis.separate':
            'Dramatis is here, but the cards go out on their own (it does not take them now)',
        'm15.settings.title': 'Settings',
        'm15.settings.cap': 'Token limit for all cards',
        'm15.settings.cap.hint':
            'Used while the Architect has no «Voices» budget. Over the limit, goals go first, then attitudes between characters, then speech gets shorter.',
        'm15.settings.cap.architect': 'The Architect’s «Voices» budget ({tokens} tokens) applies now.',
        'm15.settings.npcAttitudes': 'Attitudes between present characters (up to three lines)',
        'm15.settings.goals': 'Current goals (DES fields and quests)',
    },
    ru: {
        'm15.title': 'Голоса персонажей',
        'm15.tab': 'Голоса',
        'm15.noChat': 'Чат не открыт.',
        'm15.cards.title': 'Карточки для следующего ответа',
        'm15.cards.hint':
            'Короткая карточка на каждого, кто сейчас в сцене: как говорит, какой характер (MBTI и в форме ли сейчас), как относится к твоей персоне и чего хочет. Всё это — из листов характера CarrotKernel и трекера DES. Карточки идут ближе к концу промпта вместо подсказки CarrotKernel «Character Consistency».',
        'm15.cards.empty': 'Карточек нет: по трекеру DES в сцене никого нет или о присутствующих ничего не известно.',
        'm15.cards.summary': 'Карточек: {count} · {tokens} из {budget} токенов',
        'm15.budget.architect': 'бюджет из Архитектора',
        'm15.budget.cap': 'свой предел',
        'm15.tokens': 'токенов: {count}',
        'm15.trimmed': 'Сокращено, чтобы уложиться: {steps}.',
        'm15.trim.goals': 'без целей',
        'm15.trim.bonds': 'без отношений между персонажами',
        'm15.trim.speech': 'речь короче',
        'm15.trim.state': 'без текущего состояния',
        'm15.trim.extras': 'без дополнительных полей',
        'm15.trim.cards': 'часть карточек не вошла',
        'm15.dropped': 'Не поместились: {names}.',
        'm15.bonds': 'Между персонажами',
        'm15.preview': 'Всё так, как это видит модель',
        'm15.loading': 'Часть листов характера ещё загружается — карточки дополнятся.',
        'm15.quiet.title': 'Тихий режим CarrotKernel',
        'm15.quiet.hint':
            'Пока модель получает эти карточки, Maestro убирает из промпта похожую подсказку CarrotKernel («Character Consistency»), чтобы модель не читала одно и то же дважды. Настройки CarrotKernel не меняются, а DES-RU просит её больше не пересобирать. Выключишь модуль — всё работает как раньше.',
        'm15.quiet.ck.removed': 'Подсказка CarrotKernel убрана ✓ (в последнем ответе: −{tokens} токенов, {time})',
        'm15.quiet.ck.absent': 'Подсказка CarrotKernel убрана ✓ (в прошлый раз CarrotKernel её не прислал)',
        'm15.quiet.ck.notFound': 'Подсказка CarrotKernel не убрана ✗ — в последнем промпте её не нашлось',
        'm15.quiet.ck.waiting': 'Подсказка CarrotKernel уберётся со следующего ответа',
        'm15.quiet.ck.idle': 'Подсказка CarrotKernel остаётся: карточек нет',
        'm15.quiet.desru.told': 'DES-RU в курсе ✓ — больше не пересобирает подсказку',
        'm15.quiet.desru.notTold': 'DES-RU не в курсе ✗ — просьба не дошла',
        'm15.quiet.desru.absent': 'Предупреждать DES-RU не нужно (нет DES-RU 0.8+)',
        'm15.quiet.dramatis.merged': 'Карточки сейчас уходят в блок Dramatis (один блок с мотивами и речью) ✓',
        'm15.quiet.dramatis.separate': 'Dramatis подключён, но карточки уходят отдельно (сейчас он их не берёт)',
        'm15.settings.title': 'Настройки',
        'm15.settings.cap': 'Предел токенов на все карточки',
        'm15.settings.cap.hint':
            'Действует, пока в Архитекторе не задан бюджет «Голоса». Сверх предела сначала уходят цели, потом отношения между персонажами, потом сокращается речь.',
        'm15.settings.cap.architect': 'Сейчас действует бюджет Архитектора «Голоса»: {tokens} токенов.',
        'm15.settings.npcAttitudes': 'Отношения между присутствующими (до трёх строк)',
        'm15.settings.goals': 'Текущие цели (поля DES и квесты)',
    },
};
