// Strings of M15 «Голоса персонажей» (`m15.*`). Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const VOICES_STRINGS: I18nParts = {
    en: {
        'm15.title': 'Character voices',
        'm15.tab': 'Voices',
        'm15.noChat': 'No chat is open.',
        'm15.cards.title': 'Cards for the next reply',
        'm15.cards.hint':
            'One short card for every character present in the scene (DES tracker of your last answered turn): speech manner from LING tags and the archive’s Linguistics block, MBTI with its healthy/unhealthy state, how they feel about your persona now, and their goals. The cards go near the end of the prompt and replace CarrotKernel’s «Character Consistency» insert.',
        'm15.cards.empty':
            'No cards: by the DES tracker nobody is in the scene, or nothing is known about the characters present.',
        'm15.cards.summary': 'Cards: {count} · {tokens} of {budget} tokens',
        'm15.budget.architect': 'budget from the Architect',
        'm15.budget.cap': 'own limit',
        'm15.tokens': '{count} tokens',
        'm15.trimmed': 'Shortened to fit: {steps}.',
        'm15.trim.goals': 'goals left out',
        'm15.trim.bonds': 'attitudes between characters left out',
        'm15.trim.speech': 'speech shortened',
        'm15.trim.state': 'current state left out',
        'm15.trim.extras': 'extra fields left out',
        'm15.trim.cards': 'some cards left out',
        'm15.dropped': 'Did not fit: {names}.',
        'm15.bonds': 'Between characters',
        'm15.preview': 'Whole insert as the model sees it',
        'm15.loading': 'Some archives are still loading; the cards will fill in.',
        'm15.quiet.title': 'CarrotKernel quiet mode',
        'm15.quiet.hint':
            'While cards go out, Maestro takes CK’s «Character Consistency» insert out of the assembled prompt — CK’s settings are not touched — and asks DES-RU to stop rebuilding it. Turn the module off and both work as before.',
        'm15.quiet.ck.removed': 'CK insert silenced ✓ (last reply: −{tokens} tokens, {time})',
        'm15.quiet.ck.absent': 'CK insert silenced ✓ (CK sent nothing last time)',
        'm15.quiet.ck.notFound': 'CK insert silenced ✗ — its text was not found in the last prompt',
        'm15.quiet.ck.waiting': 'CK insert will be silenced in the next reply',
        'm15.quiet.ck.idle': 'CK insert is not silenced: there are no cards',
        'm15.quiet.desru.told': 'DES-RU told ✓ — it no longer rebuilds the CK insert',
        'm15.quiet.desru.notTold': 'DES-RU told ✗ — it did not accept the request',
        'm15.quiet.desru.absent': 'DES-RU told — not needed (no DES-RU 0.8+)',
        'm15.settings.title': 'Settings',
        'm15.settings.cap': 'Token limit for all cards',
        'm15.settings.cap.hint':
            'Used while the Architect has no «Voices» budget. Over the limit, goals go first, then attitudes between characters, then speech gets shorter.',
        'm15.settings.cap.architect': 'The Architect’s «Voices» budget ({tokens} tokens) applies now.',
        'm15.settings.npcAttitudes': 'Attitudes between present characters (up to three lines)',
        'm15.settings.goals': 'Current goals (DES fields and quests)',
    },
    ru: {
        'm15.title': 'Голоса персонажей',
        'm15.tab': 'Голоса',
        'm15.noChat': 'Чат не открыт.',
        'm15.cards.title': 'Карточки для следующего ответа',
        'm15.cards.hint':
            'Короткая карточка на каждого, кто сейчас в сцене (по трекеру DES последнего хода, на который ты ответил): манера речи по тегам LING и блоку Linguistics из архива, тип MBTI со здоровым или нездоровым состоянием, отношение к твоей персоне сейчас и цели. Карточки идут ближе к концу промпта и заменяют вставку CarrotKernel «Character Consistency».',
        'm15.cards.empty': 'Карточек нет: по трекеру DES в сцене никого нет или о присутствующих ничего не известно.',
        'm15.cards.summary': 'Карточек: {count} · {tokens} из {budget} токенов',
        'm15.budget.architect': 'бюджет из Архитектора',
        'm15.budget.cap': 'свой предел',
        'm15.tokens': 'токенов: {count}',
        'm15.trimmed': 'Сокращено, чтобы уложиться: {steps}.',
        'm15.trim.goals': 'без целей',
        'm15.trim.bonds': 'без отношений между персонажами',
        'm15.trim.speech': 'речь короче',
        'm15.trim.state': 'без текущего состояния',
        'm15.trim.extras': 'без дополнительных полей',
        'm15.trim.cards': 'часть карточек не вошла',
        'm15.dropped': 'Не поместились: {names}.',
        'm15.bonds': 'Между персонажами',
        'm15.preview': 'Вся вставка так, как её видит модель',
        'm15.loading': 'Часть архивов ещё загружается — карточки дополнятся.',
        'm15.quiet.title': 'Тихий режим CarrotKernel',
        'm15.quiet.hint':
            'Пока карточки уходят в промпт, Maestro убирает из собранного промпта вставку CK «Character Consistency» — настройки CK при этом не меняются — и просит DES-RU больше её не пересобирать. Выключишь модуль — оба работают как раньше.',
        'm15.quiet.ck.removed': 'Вставка CK погашена ✓ (последний ответ: −{tokens} токенов, {time})',
        'm15.quiet.ck.absent': 'Вставка CK погашена ✓ (в прошлый раз CK ничего не прислал)',
        'm15.quiet.ck.notFound': 'Вставка CK погашена ✗ — её текст не нашёлся в последнем промпте',
        'm15.quiet.ck.waiting': 'Вставка CK будет погашена в следующем ответе',
        'm15.quiet.ck.idle': 'Вставка CK не гасится: карточек нет',
        'm15.quiet.desru.told': 'DES-RU в курсе ✓ — больше не пересобирает вставку CK',
        'm15.quiet.desru.notTold': 'DES-RU не в курсе ✗ — просьба не прошла',
        'm15.quiet.desru.absent': 'DES-RU предупреждать не нужно (нет DES-RU 0.8+)',
        'm15.settings.title': 'Настройки',
        'm15.settings.cap': 'Предел токенов на все карточки',
        'm15.settings.cap.hint':
            'Действует, пока в Архитекторе не задан бюджет «Голоса». Сверх предела сначала уходят цели, потом отношения между персонажами, потом сокращается речь.',
        'm15.settings.cap.architect': 'Сейчас действует бюджет Архитектора «Голоса»: {tokens} токенов.',
        'm15.settings.npcAttitudes': 'Отношения между присутствующими (до трёх строк)',
        'm15.settings.goals': 'Текущие цели (поля DES и квесты)',
    },
};
