// @vitest-environment happy-dom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { createEphemeral } from '../../../src/core/ephemeral';
import { TurnPipeline } from '../../../src/core/turn';
import type { DesTrackerSnapshot } from '../../../src/domain/des-tracker';
import { scenariosModule } from '../../../src/features/scenarios';
import { sheetsModule, toRanges } from '../../../src/features/sheets';
import type { SheetsApi } from '../../../src/features/sheets/api';
import type { SlashCommandSpec } from '../../../src/shared/contracts';
import { analyseRequest, buildReply, sheetText } from '../../../tools/mock-llm/scenarios.mjs';
import { createFixture, flush, info } from '../scenarios/fixture';
import type { Fixture } from '../scenarios/fixture';

const FULLSHEET_ENTRY = {
    uid: 2,
    key: ['!fullsheet'],
    keysecondary: [],
    comment: '👤FULL CHARACTER SHEET FORMAT 👤',
    content:
        '@@dont_activate\n<BunnymoTags:MANDATORY HIGHEST PRIORITY DIRECTIVE>\nWhen {{user}} uses !fullsheet, create a full sheet.\n## SECTION 1/14: Core\n</BunnymoTags:MANDATORY HIGHEST PRIORITY DIRECTIVE>',
};
const QUICKSHEET_ENTRY = { uid: 3, key: ['!quicksheet'], comment: 'QUICK SHEET', content: 'Quick sheet rules.' };
const MASTER_ENTRY = { uid: 13, key: ['!dere'], comment: '💗 Master - Dere System', content: 'Dere rules.' };
const VERA_ARCHIVE = {
    uid: 1,
    key: ['Вера'],
    comment: 'Вера Character Archive - Generated by Baby Bunny Mode',
    content: '<BunnymoTags><Name:Вера>, <SPECIES:HUMAN>, <TRAIT:STOIC></BunnymoTags>',
};
const MARTIN_ARCHIVE = {
    uid: 2,
    key: ['Мартин'],
    comment: 'Мартин Character Archive',
    content: '<BunnymoTags><Name:Мартин>, <SPECIES:ELF></BunnymoTags>',
};
const WORLD_ENTRY = { uid: 7, key: ['порт'], comment: 'Port', content: 'The harbor of Silver Bay.' };

const TRACKER: DesTrackerSnapshot = {
    characters: [
        {
            name: 'Вера',
            details: { appearance: 'мокрый плащ' },
            relationship: 'Friend',
            stats: [],
            offScene: false,
        },
    ],
    infoBox: null,
    quests: null,
};

let fx: Fixture;
let api: SheetsApi;
let saves: number;
let renders: number[];
let slash: SlashCommandSpec | null;

function msg(name: string, text: string, user = false): STChatMessage {
    return { name, is_user: user, is_system: false, send_date: '', mes: text, extra: {} };
}

function renderChat(): void {
    document.body.innerHTML = `<div id="chat">${fx.mock.chat
        .map(
            (_, index) =>
                `<div class="mes" mesid="${index}"><div class="mes_block"><div class="ch_name"></div><div class="mes_text">t</div></div></div>`,
        )
        .join('')}</div>`;
}

function stPrompt(): Record<string, unknown>[] {
    return [
        { role: 'system', content: 'Marinara main prompt with DES tracker instructions' },
        { role: 'user', content: '!fullsheet Вера' },
    ];
}

/** A sheet generation through the engine; returns the request body and the reply index. */
async function sheetGeneration(command = '!fullsheet Вера', generation = info({ sheetCommand: 'fullsheet' })) {
    if (generation.type === 'normal') fx.mock.chat.push(msg('Кай', command, true));
    await fx.bus.emit('generation:before', generation);
    const loaded = {
        globalLore: [
            { ...FULLSHEET_ENTRY, world: 'BunnyMo' },
            { ...QUICKSHEET_ENTRY, world: 'BunnyMo' },
            { ...MASTER_ENTRY, world: 'BunnyMo' },
            { ...WORLD_ENTRY, world: 'World' },
        ],
        characterLore: [
            { ...VERA_ARCHIVE, world: 'Repo' },
            { ...MARTIN_ARCHIVE, world: 'Repo' },
        ],
        chatLore: [],
        personaLore: [],
    };
    await fx.emit('WORLDINFO_ENTRIES_LOADED', loaded);
    const eventData = { chat: stPrompt(), dryRun: false };
    await fx.emit('CHAT_COMPLETION_PROMPT_READY', eventData);
    await fx.emit('GENERATE_AFTER_DATA', { prompt: eventData.chat }, false);
    const request: Record<string, unknown> = {
        type: generation.type,
        messages: [...eventData.chat],
        stream: true,
        max_tokens: 300,
        temperature: 1,
    };
    await fx.emit('CHAT_COMPLETION_SETTINGS_READY', request);
    return { loaded, prompt: eventData.chat as { role: string; content: string }[], request };
}

/** The bench mock answers the prompt; ST adds the reply and fires its events (streaming order). */
async function receive(prompt: { role: string; content: string }[], type = 'normal'): Promise<number> {
    const content = buildReply(analyseRequest({ messages: prompt })).content;
    const reply = {
        ...msg('Вера', content),
        swipe_id: 0,
        swipes: [content],
        swipe_info: [{ send_date: '', extra: {} }],
    };
    fx.mock.chat.push(reply);
    const index = fx.mock.chat.length - 1;
    renderChat();
    await fx.bus.emit('generation:ended', { type, stopped: false });
    await fx.emit('MESSAGE_RECEIVED', index, type);
    await fx.emit('CHARACTER_MESSAGE_RENDERED', index, type);
    await fx.bus.emit('reply:ready', { messageIndex: index, type });
    await flush();
    return index;
}

async function startAll(options: { engine?: boolean } = {}) {
    if (options.engine !== false) await fx.start(scenariosModule);
    const started = await fx.start(sheetsModule);
    api = fx.apis.get('sheets') as SheetsApi;
    return started;
}

beforeEach(() => {
    fx = createFixture();
    saves = 0;
    renders = [];
    slash = null;
    const context = fx.mock.context as unknown as Record<string, unknown>;
    context.saveChat = async () => {
        saves++;
    };
    context.updateMessageBlock = (index: number) => renders.push(index);
    context.substituteParams = (text: string) => text.replace(/\{\{user\}\}/g, 'Кай');
    context.name1 = 'Кай';
    context.name2 = 'Вера';
    context.characterId = 0;
    context.characters = [
        {
            name: 'Вера',
            avatar: 'vera.png',
            description: 'Капитан стражи, давняя подруга {{user}}.',
            personality: 'Упрямая',
        },
    ];
    fx.ui.addSlashCommand = (spec) => {
        slash = spec;
        return () => {};
    };
    fx.books.set('BunnyMo', {
        entries: { 2: FULLSHEET_ENTRY, 3: QUICKSHEET_ENTRY, 13: MASTER_ENTRY },
    });
    fx.books.set('Repo', { entries: { 1: VERA_ARCHIVE, 2: MARTIN_ARCHIVE } });
    fx.adapters.ck.repos = ['Repo'];
    fx.adapters.trackers.set(0, TRACKER);
    fx.mock.chat.push(
        msg('Вера', '```json\n{"characters": [{"name": "Вера"}]}\n```\n\nВера смотрит на море.'),
        msg('Кай', 'Расскажи о себе', true),
        msg('Вера', 'Вера улыбается. <img src="x.png"> [nai:img:1]'),
    );
});

afterEach(() => {
    delete (globalThis as Record<string, unknown>).checkForCompletedSheets;
    document.body.innerHTML = '';
});

describe('sheet scenario', () => {
    it('replaces the prompt with the BunnyMo instruction, character data, excerpt and command', async () => {
        await startAll();
        const { loaded, prompt, request } = await sheetGeneration();

        // Only the command entries and Vera's archive pass the WI scan.
        expect(loaded.globalLore.map((entry) => entry.uid)).toEqual([2, 3]);
        expect(loaded.characterLore.map((entry) => entry.comment)).toEqual([VERA_ARCHIVE.comment]);

        expect(prompt.map((message) => message.role)).toEqual(['system', 'system', 'user', 'user']);
        const [instruction, data, excerpt, command] = prompt.map((message) => message.content);
        expect(instruction).toContain('When Кай uses !fullsheet, create a full sheet.');
        expect(instruction).not.toContain('@@dont_activate');
        expect(instruction).toContain('Output ONLY the !fullsheet sheet for Вера');
        expect(data).toContain('Капитан стражи, давняя подруга Кай.');
        expect(data).toContain('Упрямая');
        expect(data).toContain('<Name:Вера>, <SPECIES:HUMAN>');
        expect(data).not.toContain('Мартин');
        expect(data).toContain('- appearance: мокрый плащ');
        expect(excerpt).toContain('Вера: Вера смотрит на море.');
        expect(excerpt).toContain('Кай: Расскажи о себе');
        expect(excerpt).not.toContain('```');
        expect(excerpt).not.toContain('<img');
        expect(excerpt).not.toContain('nai:img');
        expect(excerpt).not.toContain('!fullsheet');
        expect(command).toBe('!fullsheet Вера');

        expect(request).toMatchObject({ max_tokens: 6000, temperature: 0.7, stream: true });
    });

    it('uses the settings, the current character by default and the book when WI did not load it', async () => {
        await fx.start(scenariosModule);
        await fx.start(sheetsModule, { maxTokens: 3000, temperature: 0.4, excerptMessages: 1 });
        fx.mock.chat.push(msg('Кай', '!fullsheet', true));
        await fx.bus.emit('generation:before', info({ sheetCommand: 'fullsheet' }));
        const eventData = { chat: stPrompt(), dryRun: false };
        await fx.emit('CHAT_COMPLETION_PROMPT_READY', eventData);
        const prompt = eventData.chat as { content: string }[];
        expect(prompt[0]!.content).toContain('create a full sheet');
        expect(prompt[0]!.content).toContain('sheet for Вера');
        expect(prompt[1]!.content).toContain('<Name:Вера>');
        expect(prompt[2]!.content.match(/\n\n/g)).toHaveLength(1);
        const request: Record<string, unknown> = {
            type: 'normal',
            messages: [...prompt],
            max_tokens: 1,
            stream: false,
        };
        await fx.emit('CHAT_COMPLETION_SETTINGS_READY', request);
        expect(request).toMatchObject({ max_tokens: 3000, temperature: 0.4, stream: false });
    });

    it('keeps ST’s prompt without the BunnyMo core, but still cleans the reply', async () => {
        fx.adapters.bunnymo.core = [];
        await startAll();
        fx.mock.chat.push(msg('Кай', '!fullsheet Вера', true));
        await fx.bus.emit('generation:before', info({ sheetCommand: 'fullsheet' }));
        const eventData = { chat: stPrompt(), dryRun: false };
        await fx.emit('CHAT_COMPLETION_PROMPT_READY', eventData);
        expect(eventData.chat[0]!.content).toContain('Marinara');
        const index = await receive([{ role: 'user', content: '!fullsheet Вера' }]);
        expect(fx.mock.chat[index]!.mes).toBe(
            sheetText('Вера', analyseRequest({ messages: [{ role: 'user', content: '!fullsheet Вера' }] })),
        );
    });

    it('keeps the lore and the prompt when the command has no BunnyMo entry', async () => {
        await startAll();
        const { loaded, prompt, request } = await sheetGeneration('!physheet Вера', info({ sheetCommand: 'physheet' }));
        expect(loaded.globalLore).toHaveLength(4);
        expect(loaded.characterLore).toHaveLength(2);
        expect(prompt[0]!.content).toContain('Marinara');
        expect(request.max_tokens).toBe(300);
    });

    it('does not take over continue, impersonate or quiet generations', async () => {
        await startAll();
        fx.mock.chat.push(msg('Кай', '!fullsheet Вера', true));
        for (const type of ['continue', 'impersonate']) {
            await fx.bus.emit('generation:before', info({ type, sheetCommand: 'fullsheet' }));
            const eventData = { chat: stPrompt(), dryRun: false };
            await fx.emit('CHAT_COMPLETION_PROMPT_READY', eventData);
            expect(eventData.chat).toHaveLength(2);
        }
    });
});

describe('other stories (plan-2 §9)', () => {
    const OTHER_VERA = {
        uid: 9,
        key: ['Вера'],
        comment: 'Вера Character Archive (another story)',
        content: '<BunnymoTags><Name:Вера>, <SPECIES:VAMPIRE></BunnymoTags>',
    };

    function otherStories(): void {
        fx.books.set('Old Repo', { entries: { 9: OTHER_VERA } });
        fx.adapters.ck.repos = ['Repo', 'Old Repo'];
        const context = fx.mock.context as unknown as { characters: Record<string, unknown>[] };
        context.characters.push({ name: 'Мартин', avatar: 'martin.png', description: 'Мартин из другой истории.' });
    }

    async function dataOf(
        command: string,
        extraLore: Record<string, unknown>[] = [],
    ): Promise<{
        data: string;
        kept: string[];
    }> {
        fx.mock.chat.push(msg('Кай', command, true));
        await fx.bus.emit('generation:before', info({ sheetCommand: 'fullsheet' }));
        const loaded = {
            globalLore: [{ ...FULLSHEET_ENTRY, world: 'BunnyMo' }],
            characterLore: [{ ...VERA_ARCHIVE, world: 'Repo' }, { ...MARTIN_ARCHIVE, world: 'Repo' }, ...extraLore],
            chatLore: [],
            personaLore: [],
        };
        await fx.emit('WORLDINFO_ENTRIES_LOADED', loaded);
        const eventData = { chat: stPrompt(), dryRun: false };
        await fx.emit('CHAT_COMPLETION_PROMPT_READY', eventData);
        const prompt = eventData.chat as { content: string }[];
        return { data: prompt[1]?.content ?? '', kept: loaded.characterLore.map((entry) => String(entry.comment)) };
    }

    it('with the world model only the target’s own archives speak for it', async () => {
        otherStories();
        const sources = (world: string, uid: number) => [
            { kind: 'ck.archive', ref: `${world}#${uid}`, label: 'Вера', world, uid },
        ];
        fx.apis.set('world', {
            resolve: (name: string) =>
                name === 'Вера'
                    ? {
                          id: 'character:вера',
                          kind: 'character',
                          name: 'Вера',
                          aliases: [],
                          forms: [],
                          sources: sources('Repo', 1),
                      }
                    : name === 'Мартин'
                      ? {
                            id: 'character:мартин',
                            kind: 'character',
                            name: 'Мартин',
                            aliases: [],
                            forms: [],
                            sources: [],
                        }
                      : undefined,
        });
        await startAll();
        const vera = await dataOf('!fullsheet Вера', [{ ...OTHER_VERA, world: 'Old Repo' }]);
        expect(vera.kept).toEqual([VERA_ARCHIVE.comment]);
        expect(vera.data).toContain('<SPECIES:HUMAN>');
        expect(vera.data).not.toContain('VAMPIRE');
        const martin = await dataOf('!fullsheet Мартин');
        expect(martin.kept).toEqual([]);
        expect(martin.data).not.toContain('<Name:Мартин>');
        // Another card named Мартин is another story's: its text stays out.
        expect(martin.data).not.toContain('из другой истории');
    });

    it('without it, the card’s own names reach every repo; other names only the chat’s books', async () => {
        otherStories();
        await startAll();
        const vera = await dataOf('!fullsheet Вера', [{ ...OTHER_VERA, world: 'Old Repo' }]);
        expect(vera.data).toContain('<SPECIES:HUMAN>');
        const martin = await dataOf('!fullsheet Мартин');
        expect(martin.kept).toEqual([]);
        expect(martin.data).not.toContain('<Name:Мартин>');
        expect(martin.data).not.toContain('из другой истории');
        // Named by the card itself, he is the card's: his archive speaks for him.
        const card = (fx.mock.context as unknown as { characters: Record<string, unknown>[] }).characters[0]!;
        card.description = 'Капитан стражи; её помощник — Мартин.';
        const named = await dataOf('!fullsheet Мартин');
        expect(named.kept).toEqual([MARTIN_ARCHIVE.comment]);
        expect(named.data).toContain('<Name:Мартин>');
    });
});

describe('sheet reply', () => {
    it('cuts the mock’s scene and tracker, keeps swipes consistent, marks and journals', async () => {
        fx.adapters.qvink.present = true;
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        const expected = sheetText('Вера', analyseRequest({ messages: prompt }));

        const reply = fx.mock.chat[index]!;
        expect(reply.mes).toBe(expected);
        expect((reply.swipes as string[])[0]).toBe(expected);
        expect(reply.extra?.maestro).toEqual({ sheet: { command: 'fullsheet', target: 'Вера', part: 'reply' } });
        const swipeInfo = (reply.swipe_info as { extra: Record<string, unknown> }[])[0]!;
        expect(swipeInfo.extra.maestro).toEqual(reply.extra?.maestro);
        expect(fx.mock.chat[index - 1]!.extra?.maestro).toEqual({
            sheet: { command: 'fullsheet', target: 'Вера', part: 'command' },
        });
        expect(renders).toContain(index);
        expect(saves).toBeGreaterThan(0);
        expect(fx.journal.records.map((record) => record.kind)).toEqual(['sheets.trim']);
        // Excluded in Qvink on MESSAGE_RECEIVED, before its auto-summary.
        expect(fx.commands[0]).toBe(`/qm-toggle-exclude ${index} exclude=true`);

        expect(api.isSheetMessage(index)).toBe(true);
        expect(api.isSheetMessage(index - 1)).toBe(true);
        expect(api.isSheetMessage(0)).toBe(false);
        expect(api.sheetsFor('Веры')).toEqual([{ index, command: 'fullsheet' }]);
        expect(api.sheetsFor('Мартин')).toEqual([]);

        // Undo from the journal brings the raw reply back.
        const raw = (reply.swipes as string[])[0];
        expect(await fx.journal.undo(fx.journal.records[0]!.id)).toBe(true);
        expect(reply.mes).not.toBe(raw);
        expect(reply.mes).toContain('```json');
        expect(await fx.journal.undo(fx.journal.records[0]!.id)).toBe(false);
    });

    it('unmarks a swipe that is not a sheet', async () => {
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        const reply = fx.mock.chat[index]!;
        await fx.bus.emit('generation:before', info({ type: 'swipe', sheetCommand: 'fullsheet' }));
        // ST copies `extra` into the new swipe's swipe_info: the mark comes along.
        reply.swipe_id = 1;
        reply.mes = 'Я не буду этого делать.';
        (reply.swipes as string[]).push(reply.mes);
        (reply.swipe_info as unknown[]).push({ extra: structuredClone(reply.extra) });
        await fx.bus.emit('generation:ended', { type: 'swipe', stopped: false });
        await fx.bus.emit('reply:ready', { messageIndex: index, type: 'swipe' });
        await flush();
        expect(api.isSheetMessage(index)).toBe(false);
        expect((reply.swipe_info as { extra: Record<string, unknown> }[])[1]!.extra.maestro).toBeUndefined();
        expect(reply.mes).toBe('Я не буду этого делать.');
    });

    it('leaves group chats to ST', async () => {
        (fx.app.host as unknown as { isGroupChat: () => boolean }).isGroupChat = () => true;
        await startAll({ engine: false });
        fx.mock.chat.push(msg('Кай', '!fullsheet Вера', true));
        await fx.bus.emit('generation:before', info({ sheetCommand: 'fullsheet' }));
        const index = await receive([{ role: 'user', content: '!fullsheet Вера' }]);
        expect(fx.mock.chat[index]!.mes).toContain('```json');
        expect(api.isSheetMessage(index)).toBe(false);
    });

    it('works as a safety net without the scenario engine', async () => {
        await startAll({ engine: false });
        fx.mock.chat.push(msg('Кай', '!fullsheet Вера', true));
        await fx.bus.emit('generation:before', info({ sheetCommand: 'fullsheet' }));
        const messages = [{ role: 'user', content: '!fullsheet Вера' }];
        const index = await receive(messages);
        expect(fx.mock.chat[index]!.mes).toBe(sheetText('Вера', analyseRequest({ messages })));
        expect(api.isSheetMessage(index)).toBe(true);
    });

    it('leaves a reply that is not a sheet alone', async () => {
        await startAll({ engine: false });
        fx.mock.chat.push(msg('Кай', '!fullsheet Вера', true));
        await fx.bus.emit('generation:before', info({ sheetCommand: 'fullsheet' }));
        const messages = [{ role: 'user', content: 'Продолжай [mock:refusal]' }];
        const index = await receive(messages);
        expect(fx.mock.chat[index]!.mes).toBe(buildReply(analyseRequest({ messages })).content);
        expect(api.isSheetMessage(index)).toBe(false);
        expect(fx.journal.records).toHaveLength(0);
    });

    it('queues the clean-up in the Inbox when the user asked for it', async () => {
        fx.app.settings.core().autonomy['sheets.trim'] = 'inbox';
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        expect(fx.mock.chat[index]!.mes).toContain('```json');
        expect(fx.inbox.cards.map((card) => card.kind)).toEqual(['sheets.trim']);
        await fx.inbox.appliers.get('sheets.trim')!(fx.inbox.cards[0]!.payload);
        expect(fx.mock.chat[index]!.mes).not.toContain('```json');
    });

    it('trims a continued sheet again', async () => {
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        const reply = fx.mock.chat[index]!;
        const clean = reply.mes;
        await fx.bus.emit('generation:before', info({ type: 'continue', sheetCommand: 'fullsheet' }));
        reply.mes = `${clean}\n\nВера поднимается и уходит к причалу, не оглядываясь.`;
        (reply.swipes as string[])[0] = reply.mes;
        await fx.bus.emit('reply:ready', { messageIndex: index, type: 'continue' });
        await flush();
        expect(reply.mes).toBe(clean);
    });
});

describe('Baby Bunny capture', () => {
    async function captureWith(settings: Record<string, unknown> | null) {
        const capture = vi.fn(async () => {});
        (globalThis as Record<string, unknown>).checkForCompletedSheets = capture;
        fx.adapters.ck.present = true;
        fx.adapters.ck.settings = settings;
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        return { capture, index };
    }

    it('captures the cleaned sheet itself outside the "thinking" mode', async () => {
        const { capture, index } = await captureWith({ babyBunnyMode: true, displayMode: 'cards' });
        expect(capture).toHaveBeenCalledTimes(1);
        expect(capture).toHaveBeenCalledWith(fx.mock.chat[index], index);
        expect((capture.mock.calls[0] as unknown as [STChatMessage])[0].mes).not.toContain('```json');
        expect(fx.journal.records.map((record) => record.kind)).toContain('sheets.capture');
    });

    it('leaves the capture to CK in "thinking" mode and does nothing with Baby Bunny off', async () => {
        expect((await captureWith({ babyBunnyMode: true, displayMode: 'thinking' })).capture).not.toHaveBeenCalled();
    });

    it('does nothing when Baby Bunny is off', async () => {
        expect((await captureWith({ babyBunnyMode: false, displayMode: 'none' })).capture).not.toHaveBeenCalled();
    });
});

describe('folding and hiding', () => {
    it('folds the sheet until the next message, then hides the pair from prompt and Qvink', async () => {
        fx.adapters.qvink.present = true;
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        const command = index - 1;
        await flush();

        const element = document.querySelector<HTMLElement>(`#chat .mes[mesid="${index}"]`)!;
        expect(element.classList.contains('maestro-sheet-reply')).toBe(true);
        const toggle = element.querySelector<HTMLButtonElement>('.maestro-sheet-toggle')!;
        expect(toggle.textContent).toBe('📋 Показать лист: Вера');
        toggle.click();
        expect(element.classList.contains('maestro-sheet-open')).toBe(true);
        expect(toggle.textContent).toBe('📋 Свернуть лист');
        toggle.click();
        expect(element.classList.contains('maestro-sheet-open')).toBe(false);
        expect(
            document.querySelector(`#chat .mes[mesid="${command}"]`)!.classList.contains('maestro-sheet-command'),
        ).toBe(true);

        // Still the last message: a commit now (e.g. /send at=…) must not hide it.
        await fx.bus.emit('turn:committed', { messageIndex: index });
        expect(fx.hides).toEqual([]);
        expect(fx.mock.chat[index]!.is_system).toBe(false);

        // The user sends the next message.
        fx.mock.chat.push(msg('Кай', 'Продолжим', true));
        renderChat();
        fx.commands.length = 0;
        await fx.bus.emit('turn:committed', { messageIndex: index });
        await flush();
        expect(fx.hides).toEqual([[command, index, false]]);
        expect(fx.mock.chat[command]!.is_system).toBe(true);
        expect(fx.mock.chat[index]!.is_system).toBe(true);
        expect((fx.mock.chat[index]!.extra?.maestro as { sheet: { committed: boolean } }).sheet.committed).toBe(true);
        expect(fx.commands).toEqual([`/qm-toggle-exclude ${command}-${index} exclude=true`]);
        expect(fx.journal.records.map((record) => record.kind)).toContain('sheets.hide');
        expect(element.isConnected).toBe(false);
        const rendered = document.querySelector<HTMLElement>(`#chat .mes[mesid="${index}"]`)!;
        expect(rendered.classList.contains('maestro-sheet-hidden')).toBe(true);
        expect(rendered.querySelector('.maestro-sheet-toggle')).not.toBeNull();

        // Committed sheets are not hidden twice.
        await fx.bus.emit('turn:committed', { messageIndex: index });
        expect(fx.hides).toHaveLength(1);
    });

    it('hides the pair synchronously inside MESSAGE_SENT, before ST builds the next prompt', async () => {
        const log = fx.app.log;
        const turn = new TurnPipeline(fx.app.host, fx.bus, createEphemeral({ host: fx.app.host, log }), log);
        turn.install();
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        fx.mock.chat.push(msg('Кай', 'Продолжим', true));
        // ST: chat.push(message); await emit(MESSAGE_SENT); … coreChat = chat.filter(x => !x.is_system).
        const sent = fx.emit('MESSAGE_SENT', fx.mock.chat.length - 1);
        expect(fx.mock.chat[index]!.is_system).toBe(true);
        expect(fx.mock.chat[index - 1]!.is_system).toBe(true);
        await sent;
        turn.dispose();
    });

    it('keeps sheets out of the next prompt even before they are hidden', async () => {
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        fx.mock.chat.push(msg('Кай', 'Продолжим', true));
        const coreChat = fx.mock.chat.map((message) => ({ ...message }));
        await fx.intercept(coreChat, info());
        expect(coreChat.map((message) => message.mes)).not.toContain(fx.mock.chat[index]!.mes);
        expect(coreChat).toHaveLength(fx.mock.chat.length - 2);
        expect(coreChat.at(-1)!.mes).toBe('Продолжим');

        // A continue of the sheet keeps it.
        const continued = fx.mock.chat.slice(0, index + 1).map((message) => ({ ...message }));
        await fx.intercept(continued, info({ type: 'continue' }));
        expect(continued).toHaveLength(index + 1);
    });

    it('shows a hidden sheet again when it becomes the last message', async () => {
        fx.adapters.qvink.present = true;
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        fx.mock.chat.push(msg('Кай', 'Продолжим', true));
        await fx.bus.emit('turn:committed', { messageIndex: index });
        await flush();
        fx.commands.length = 0;
        fx.mock.chat.pop();
        await fx.bus.emit('message:invalidated', { messageIndex: index + 1, reason: 'deleted' });
        expect(fx.hides.at(-1)).toEqual([index - 1, index, true]);
        expect(fx.mock.chat[index]!.is_system).toBe(false);
        expect((fx.mock.chat[index]!.extra?.maestro as { sheet: { committed: boolean } }).sheet.committed).toBe(false);
        expect(fx.commands).toEqual([`/qm-toggle-exclude ${index - 1}-${index} exclude=false`]);
    });

    it('undoes the hiding from the journal', async () => {
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        fx.mock.chat.push(msg('Кай', 'Продолжим', true));
        await fx.bus.emit('turn:committed', { messageIndex: index });
        await flush();
        const record = fx.journal.records.find((item) => item.kind === 'sheets.hide')!;
        expect(await fx.journal.undo(record.id)).toBe(true);
        expect(fx.mock.chat[index]!.is_system).toBe(false);
    });

    it('hides nothing on screen without the capability but still marks the sheets', async () => {
        fx.caps.delete('st.chats.hide');
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        fx.mock.chat.push(msg('Кай', 'Продолжим', true));
        await fx.bus.emit('turn:committed', { messageIndex: index });
        await flush();
        expect(fx.hides).toEqual([]);
        expect(fx.mock.chat[index]!.is_system).toBe(false);
    });

    it('does not fold when folding is off, and cleans up on dispose', async () => {
        await fx.start(scenariosModule);
        const started = await fx.start(sheetsModule, { collapse: false });
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        await flush();
        expect(document.querySelector(`#chat .mes[mesid="${index}"]`)!.classList.contains('maestro-sheet')).toBe(false);
        started.settings.collapse = true;
        fx.app.settings.notify('sheets.collapse');
        await flush();
        expect(document.querySelector(`#chat .mes[mesid="${index}"]`)!.classList.contains('maestro-sheet')).toBe(true);
        await started.dispose();
        expect(document.querySelector('.maestro-sheet')).toBeNull();
        expect(document.querySelector('.maestro-sheet-toggle')).toBeNull();
        expect(fx.apis.has('sheets')).toBe(false);
    });
});

describe('tag-loss check', () => {
    it('compares the raw reply with the stored archive', async () => {
        await startAll();
        const { prompt } = await sheetGeneration();
        const index = await receive(prompt);
        const report = await api.checkTags(index);
        expect(report?.name).toBe('Вера');
        expect(report?.archive).toEqual(['SPECIES:HUMAN', 'TRAIT:STOIC']);
        expect(report?.missing).toContain('TRAIT:LOYAL');
        expect(report?.missing.some((tag) => /^[EI][NS][FT][JP]-[UH]$/.test(tag))).toBe(true);
        expect(await api.checkTags(0)).toBeNull();

        const text = await slash!.callback({}, '');
        expect(JSON.parse(text).name).toBe('Вера');
        expect(JSON.parse(await slash!.callback({}, String(index))).archiveName).toBe('Вера');
        expect(await slash!.callback({}, '0')).toBe('Лист не найден.');
    });
});

describe('toRanges', () => {
    it('groups indexes into ascending ranges', () => {
        expect(toRanges([5, 3, 4, 9, -1, 4])).toEqual([
            [3, 5],
            [9, 9],
        ]);
        expect(toRanges([])).toEqual([]);
    });
});
