// Strings of the Lore Studio entry form (keys m23f.*). Russian follows ST's own Russian labels where they read well
// (research/parity-lore.md §3) and addresses the user as «ты» (masculine).
import type { I18nParts } from '../../../shared/contracts';

export const ENTRY_FORM_STRINGS: I18nParts = {
    en: {
        'm23f.loading': 'Loading…',
        'm23f.loadFailed': 'Could not load the entry: {error}',
        'm23f.notFound': 'Entry #{uid} is not in «{book}» (deleted or moved).',
        'm23f.legend': 'Entry fields',
        'm23f.back': 'Back',
        'm23f.close': 'Close',
        'm23f.uid': 'UID {uid}',
        'm23f.dirty': '● unsaved',
        'm23f.save': 'Save',
        'm23f.saveHint': 'Save the changed fields (Ctrl+S)',
        'm23f.revert': 'Undo edits',
        'm23f.reverted': 'Edits dropped: the entry is as stored.',
        'm23f.enabled': 'Enabled',
        'm23f.badge.disabled': 'disabled',
        'm23f.badge.readOnly': 'read only',

        'm23f.save.saving': 'Saving…',
        'm23f.save.done': 'Saved.',
        'm23f.save.nothing': 'Nothing changed.',
        'm23f.save.failed': 'Not saved: {error}',
        'm23f.save.blocked': 'Fix the marked fields first.',
        'm23f.save.fixErrors': 'Fields with errors: {fields}',
        'm23f.save.summary': 'Lore Studio: «{entry}» in «{book}» — {fields}',
        'm23f.discard.title': 'Unsaved edits',
        'm23f.discard.body': 'The entry has edits that are not saved. Leave without saving?',

        'm23f.external.changed': 'The entry was changed outside the studio while you were editing it.',
        'm23f.external.reload': 'Show the new version (drop my edits)',
        'm23f.external.reloaded': 'The entry was changed outside the studio: the form shows the new version.',
        'm23f.external.gone': 'The entry is gone from the book.',

        'm23f.ro.bunnymo':
            'BunnyMo packs are never edited: not the text, not the keys, no translations (P13). Technical fixes (role, recursion, duplicates) happen on the fly in «Rules», each one can be switched off.',
        'm23f.ro.generic': 'This book is open read-only.',
        'm23f.ro.openRules': 'Open «Rules»',

        'm23f.section.keys': 'Keys and conditions',
        'm23f.section.content': 'Content',
        'm23f.section.placement': 'Placement',
        'm23f.section.activation': 'Activation and recursion',
        'm23f.section.timers': 'Timers',
        'm23f.section.groups': 'Groups',
        'm23f.section.filters': 'Filters and triggers',
        'm23f.section.sources': 'Scan sources',
        'm23f.section.service': 'Service',
        'm23f.section.passport': 'Passport',
        'm23f.section.canon': 'Chat canon · {book}',
        'm23f.section.canonEntry': 'Canon entry',
        'm23f.section.insights': 'Analytics and doctor',
        'm23f.section.tester': 'Check activation',
        'm23f.section.history': 'Version history',
        'm23f.passport.loading': 'Reading the passport…',
        'm23f.passport.none': 'The entry has no passport yet.',
        'm23f.passport.bunnymo': 'BunnyMo pack entries never get passports (P13).',
        'm23f.passport.noRegistry':
            'The passport of a base book entry is kept in the Maestro registry: turn on the «Book roles» module.',
        'm23f.passport.badge.entry': 'in the entry',
        'm23f.passport.badge.sidecar': 'Maestro registry',
        'm23f.passport.whereEntry': 'Kept inside the entry (extensions.maestro): it travels with the book.',
        'm23f.passport.whereSidecar': 'Kept in the Maestro registry: the book file is not changed (P2).',
        'm23f.passport.madeBy': 'Made: {by}',
        'm23f.passport.by.nai': 'NAI Studio',
        'm23f.passport.by.model': 'background model',
        'm23f.passport.by.user': 'by hand',
        'm23f.passport.stale': 'The entry text changed after the passport was made: check it or generate it again.',
        'm23f.passport.kind': 'What it is',
        'm23f.passport.kind.character': 'Character or creature',
        'm23f.passport.kind.location': 'Place',
        'm23f.passport.kind.object': 'Object',
        'm23f.passport.kind.world': 'World, faction, culture',
        'm23f.passport.kind.scenario': 'Scenario',
        'm23f.passport.name': 'Name',
        'm23f.passport.aliases': 'Other names',
        'm23f.passport.aliasesHint': 'Comma separated; Russian spellings help NAI Studio find it in Russian text.',
        'm23f.passport.tags': 'Tags',
        'm23f.passport.tagsHint': 'English Danbooru tags in lower case, comma separated: how it looks.',
        'm23f.passport.slot.base': 'Base (count, who)',
        'm23f.passport.slot.hair': 'Hair',
        'm23f.passport.slot.eyes': 'Eyes',
        'm23f.passport.slot.body': 'Body',
        'm23f.passport.slot.skin': 'Skin',
        'm23f.passport.slot.clothing': 'Clothing',
        'm23f.passport.slot.accessories': 'Accessories',
        'm23f.passport.slot.style': 'Art style',
        'm23f.passport.nsfwOn': 'Use the NSFW layer in explicit scenes',
        'm23f.passport.nsfw': 'NSFW layer',
        'm23f.passport.nsfwHint': 'Explicit anatomy goes only here: NAI Studio adds it to explicit scenes only.',
        'm23f.passport.negative': 'Never draw',
        'm23f.passport.outfit': 'Outfit',
        'm23f.passport.state': 'State',
        'm23f.passport.outfits': 'Outfits: {list}',
        'm23f.passport.states': 'States on: {list}',
        'm23f.passport.dirty': '● passport edits not saved',
        'm23f.passport.issue.notEnglish': '{field}: «{tag}» is not an English tag.',
        'm23f.passport.issue.upperCase': '{field}: «{tag}» must be in lower case.',
        'm23f.passport.issue.underscore': '{field}: «{tag}» — NovelAI reads spaces, not underscores.',
        'm23f.passport.issue.anatomy': '{field}: «{tag}» is explicit anatomy: it belongs in the NSFW layer.',
        'm23f.passport.issue.empty': 'Nothing to draw yet: fill in the tags.',
        'm23f.passport.fixFirst': 'Fix the passport errors first.',
        'm23f.passport.save': 'Save passport',
        'm23f.passport.revert': 'Undo passport edits',
        'm23f.passport.fix': 'Fix automatically',
        'm23f.passport.generate': 'Generate',
        'm23f.passport.create': 'Make by hand',
        'm23f.passport.remove': 'Remove',
        'm23f.passport.working': 'Working…',
        'm23f.passport.saved': 'Passport saved.',
        'm23f.passport.removed': 'Passport removed.',
        'm23f.passport.generated': 'Passport generated ({by}) and saved.',
        'm23f.passport.nothing': 'Nothing was generated.',
        'm23f.passport.kept': 'The passport stays as it was.',
        'm23f.passport.removeTitle': 'Remove the passport?',
        'm23f.passport.removeBody': 'The passport of «{entry}» will be removed (the journal can bring it back).',
        'm23f.passport.overwriteTitle': 'Replace the passport?',
        'm23f.passport.overwriteBody': 'This passport was made or edited by hand. Replace it with the generated one?',
        'm23f.passport.discardTitle': 'Unsaved passport edits',
        'm23f.passport.discardBody': 'The passport has edits that are not saved. Drop them and generate a new one?',

        'm23f.keys.primary': 'Primary keywords',
        'm23f.keys.secondary': 'Optional filter (secondary keys)',
        'm23f.keys.placeholder': 'Comma-separated: Anna, Annie, /Ann(a|ie)/i',
        'm23f.keys.help':
            'Commas separate keys, except inside a regex /…/flags. A regex ignores the case and whole-word settings (use the i flag). Macros like {{char}} work in keys.',
        'm23f.keys.chipRegex': 'Regular expression',
        'm23f.keys.chipLocalizer': 'Added by Lorebook Localizer',
        'm23f.keys.badgeLocalizer': 'LL',
        'm23f.keys.noKeys':
            'Without primary keys the entry fires only as constant, by @@activate or through other extensions.',
        'm23f.keys.issue.badRegex':
            'Looks like a regex, but ST cannot parse it, so it is matched as plain text: {keys}',
        'm23f.keys.issue.comma': 'A comma inside a key (an unpaired slash kept it): ST keeps it as one key — {keys}',
        'm23f.keys.issue.macroBrace': 'ST’s macro engine turns \\{ into { before matching; write [{] instead: {keys}',
        'm23f.keys.issue.macro': 'Macros are substituted in these keys before matching: {keys}',
        'm23f.keys.issue.cyrillicWholeWord':
            '«Whole words» does not know Cyrillic in ST (JS \\W): these keys also match inside other words — {keys}. The M22 rule or a /…/iu regex fixes it.',
        'm23f.keys.issue.duplicate': 'Repeated keys: {keys}',
        'm23f.keys.selectiveOff':
            'The secondary keys are ignored now: «selective» is off. ST’s own editor switches it on when the entry is opened there.',
        'm23f.keys.selectiveFix': 'Use secondary keys',

        'm23f.logic.label': 'Logic',
        'm23f.logic.hint': 'How the secondary keys combine with a primary match.',
        'm23f.logic.0': 'AND ANY',
        'm23f.logic.3': 'AND ALL',
        'm23f.logic.1': 'NOT ALL',
        'm23f.logic.2': 'NOT ANY',
        'm23f.logic.other': 'Unknown ({value})',

        'm23f.ru.localizer': 'Russian keys',
        'm23f.ru.localizerHint':
            'Lorebook Localizer translates the keys of this entry and adds Russian forms (writes the book).',
        'm23f.ru.forms': 'Russian keys',
        'm23f.ru.formsHint': 'Adds Russian forms of the English keys (DES-RU declensions through the canon module).',
        'm23f.ru.saveFirst': 'Save or undo the edits first: the Localizer writes the book itself.',
        'm23f.ru.working': 'Looking for Russian forms…',
        'm23f.ru.localizerDone': 'Localizer added {added} keys.',
        'm23f.ru.localizerFailed': 'Localizer added {added} keys; {failures} entries were not translated.',
        'm23f.ru.failed': 'Localizer failed: {error}',
        'm23f.ru.noTerms': 'No plain English keys to translate.',
        'm23f.ru.nothingNew': 'No new forms.',
        'm23f.ru.added': 'Added {count} keys — check them and save.',
        'm23f.ru.unavailable': 'Needs Lorebook Localizer or the chat canon with DES-RU.',

        'm23f.comment.label': 'Title / memo',
        'm23f.comment.placeholder': 'Entry title or memo',
        'm23f.comment.hint': 'For you only: it never goes into the prompt.',
        'm23f.content.label': 'Content',
        'm23f.content.placeholder': 'What the AI should know about this keyword',
        'm23f.content.tokens': 'Tokens: {count}',
        'm23f.content.chars': 'Chars: {count}',
        'm23f.content.expand': 'Expand the editor',
        'm23f.deco.activate': '@@activate: the entry fires without keys (after filters, timers and recursion checks).',
        'm23f.deco.dontActivate':
            '@@dont_activate: the entry never fires — not as constant, sticky, by keys or from outside.',
        'm23f.deco.unknown': 'Unknown decorators are cut from the prompt without a word: {lines}',
        'm23f.deco.helpTitle': 'Decorators',
        'm23f.deco.help':
            'Lines at the very start of the content: @@activate fires the entry without keys, @@dont_activate switches it off. Every @@ line there is removed from the prompt; @@@x is read as @@x only after an unknown decorator. If the content is nothing but @@ lines, nothing is removed.',

        'm23f.typed.label': 'Entry type',
        'm23f.typed.none': '— no type —',
        'm23f.typed.compose': 'Compose content from fields',
        'm23f.typed.composeHint':
            'Writes «Label: value» lines (English labels, values as typed). Existing text is replaced only after you confirm.',
        'm23f.typed.composed': 'Content composed from the fields — check it and save.',
        'm23f.typed.emptyFields': 'The fields are empty.',
        'm23f.typed.same': 'The content already matches the fields.',
        'm23f.typed.replaceTitle': 'Replace the content?',
        'm23f.typed.replaceBody':
            'The entry already has text. It will be replaced with the text composed from the fields:',
        'm23f.typed.whereEntry': 'Stored in the entry (extensions.maestro); other extensions see only the content.',
        'm23f.typed.whereSidecar': 'Stored in Maestro’s registry: the book file stays as its author made it (P2).',
        'm23f.typed.unavailable': 'Entry types of base books need the book roles module (M35).',

        'm23f.type.character': 'Character',
        'm23f.type.place': 'Place',
        'm23f.type.item': 'Item',
        'm23f.type.faction': 'Faction',
        'm23f.type.event': 'Event',
        'm23f.type.tradition': 'Tradition',
        'm23f.type.mechanic': 'Mechanic',
        'm23f.type.rule': 'Rule',
        'm23f.type.chapter': 'Chronicle chapter',
        'm23f.type.note': 'Note',

        'm23f.tf.name': 'Name / title',
        'm23f.tf.aliases': 'Aliases',
        'm23f.tf.role': 'Role',
        'm23f.tf.age': 'Age',
        'm23f.tf.appearance': 'Appearance',
        'm23f.tf.personality': 'Personality',
        'm23f.tf.background': 'Background',
        'm23f.tf.relationships': 'Relationships',
        'm23f.tf.speech': 'Speech',
        'm23f.tf.goals': 'Goals',
        'm23f.tf.kind': 'Kind',
        'm23f.tf.location': 'Location',
        'm23f.tf.description': 'Description',
        'm23f.tf.atmosphere': 'Atmosphere',
        'm23f.tf.inhabitants': 'Inhabitants',
        'm23f.tf.features': 'Notable features',
        'm23f.tf.secrets': 'Secrets',
        'm23f.tf.properties': 'Properties',
        'm23f.tf.owner': 'Owner',
        'm23f.tf.origin': 'Origin',
        'm23f.tf.whereabouts': 'Whereabouts',
        'm23f.tf.leader': 'Leader',
        'm23f.tf.members': 'Members',
        'm23f.tf.territory': 'Territory',
        'm23f.tf.allies': 'Allies',
        'm23f.tf.enemies': 'Enemies',
        'm23f.tf.symbols': 'Symbols and customs',
        'm23f.tf.when': 'When',
        'm23f.tf.where': 'Where',
        'm23f.tf.participants': 'Participants',
        'm23f.tf.consequences': 'Consequences',
        'm23f.tf.culture': 'Culture',
        'm23f.tf.practice': 'Practice',
        'm23f.tf.meaning': 'Meaning',
        'm23f.tf.taboos': 'Taboos',
        'm23f.tf.summary': 'Summary',
        'm23f.tf.rules': 'Rules',
        'm23f.tf.limits': 'Costs and limits',
        'm23f.tf.examples': 'Examples',
        'm23f.tf.statement': 'Rule',
        'm23f.tf.scope': 'Scope',
        'm23f.tf.exceptions': 'Exceptions',
        'm23f.tf.period': 'Period',
        'm23f.tf.events': 'Key events',
        'm23f.tf.characters': 'Characters',
        'm23f.tf.threads': 'Open threads',
        'm23f.tf.text': 'Text',

        'm23f.state.label': 'Status',
        'm23f.state.hint':
            'Constant fires without keys. Vectorized still fires by keys; Vector Storage may also activate it.',
        'm23f.state.constant': 'Constant',
        'm23f.state.normal': 'Normal (by keys)',
        'm23f.state.vectorized': 'Vectorized',

        'm23f.pos.label': 'Position',
        'm23f.pos.before': '↑Char — before the character description',
        'm23f.pos.after': '↓Char — after the character description',
        'm23f.pos.emTop': '↑EM — before the example messages',
        'm23f.pos.emBottom': '↓EM — after the example messages',
        'm23f.pos.anTop': '↑AN — before the Author’s Note',
        'm23f.pos.anBottom': '↓AN — after the Author’s Note',
        'm23f.pos.depthSystem': '@D ⚙️ — at depth, as system',
        'm23f.pos.depthUser': '@D 👤 — at depth, as user',
        'm23f.pos.depthAssistant': '@D 🤖 — at depth, as assistant',
        'm23f.pos.outlet': '➡️ Outlet — only through {{outlet::name}}',
        'm23f.pos.other': 'Other ({value}) — kept as is',
        'm23f.pos.missing':
            'No position is stored: the engine puts the entry nowhere. ST’s editor would make it «↑Char».',
        'm23f.pos.anHint':
            'Author’s Note positions reach the prompt only on turns when the Author’s Note itself is inserted.',
        'm23f.depth.label': 'Depth',
        'm23f.depth.hint':
            'Messages from the end of the chat. Entries with the same depth and role are joined into one block.',
        'm23f.outlet.label': 'Outlet name',
        'm23f.outlet.placeholder': 'e.g. scene',
        'm23f.outlet.hint':
            'The content goes into the prompt only where {{outlet::name}} stands (several names: comma-separated).',
        'm23f.outlet.empty': 'Outlet without a name: ST skips the entry.',
        'm23f.order.label': 'Order',
        'm23f.order.hint': 'A higher order goes closer to the end of its block (outlets: the other way round).',

        'm23f.prob.label': 'Trigger %',
        'm23f.prob.use': 'Roll the probability',
        'm23f.prob.useHint': 'ST hides this flag and switches it on when the entry is opened in its editor.',
        'm23f.prob.empty':
            'No probability is stored: ST rolls against an empty value and the entry almost never fires.',
        'm23f.prob.notRolled':
            'The roll is off now, so {value}% does not apply. ST’s editor switches the roll on when the entry is opened there.',
        'm23f.scan.label': 'Scan depth',
        'm23f.scan.global': 'Global setting',
        'm23f.scan.globalNow': 'Global ({value})',
        'm23f.scan.hint': 'Empty — the global setting. 0…1000 messages.',
        'm23f.case.label': 'Case-sensitive',
        'm23f.case.hint': 'Does not apply to regex keys (use the i flag).',
        'm23f.whole.label': 'Whole words',
        'm23f.whole.hint': 'Keys of several words are always matched as substrings; Cyrillic needs the M22 rule.',
        'm23f.tri.global': 'Global setting',
        'm23f.tri.globalNow': 'Global (now: {value})',
        'm23f.tri.yes': 'Yes',
        'm23f.tri.no': 'No',
        'm23f.rec.exclude': 'Non-recursable',
        'm23f.rec.excludeHint': 'Not activated by the content of other entries (recursion steps).',
        'm23f.rec.prevent': 'Prevent further recursion',
        'm23f.rec.preventHint': 'Its content does not activate other entries.',
        'm23f.rec.delay': 'Delay until recursion',
        'm23f.rec.delayHint': 'Activated only on recursion steps.',
        'm23f.rec.level': 'Recursion level',
        'm23f.rec.levelHint':
            'Empty — level 1. Levels open in ascending order: the next one starts when nothing more fires on the current one.',
        'm23f.rec.levelPlaceholder': '1',
        'm23f.rec.levelInvalid': 'A level is a number (1, 2, …).',
        'm23f.budget.ignore': 'Ignore budget',
        'm23f.budget.ignoreHint': 'Inserted even after the World Info budget overflows.',

        'm23f.timer.sticky': 'Sticky',
        'm23f.timer.stickyHint': 'Stays active this many messages after firing.',
        'm23f.timer.cooldown': 'Cooldown',
        'm23f.timer.cooldownHint': 'Cannot fire again for this many messages.',
        'm23f.timer.delay': 'Delay',
        'm23f.timer.delayHint': 'Cannot fire while the chat has fewer messages.',
        'm23f.timer.none': 'None',
        'm23f.timer.hashReset':
            'Any edit of the entry changes its hash and ends a running sticky or cooldown in open chats.',

        'm23f.group.label': 'Inclusion group',
        'm23f.group.placeholder': 'group, another group',
        'm23f.group.hint': 'Only one entry with the same label fires per scan. Several groups — comma-separated.',
        'm23f.group.suggest': 'Groups used in this book',
        'm23f.group.override': 'Prioritize',
        'm23f.group.overrideHint':
            'Among the group’s activated entries the prioritized one with the highest order wins.',
        'm23f.group.weight': 'Group weight',
        'm23f.group.weightHint': 'Relative chance to win the group (1…10000).',
        'm23f.group.scoring': 'Group scoring',
        'm23f.group.scoringHint': 'Entries with fewer matched keys drop out of the group.',

        'm23f.filter.label': 'Characters and tags',
        'm23f.filter.hint': 'Tie the entry to characters (by avatar file) or to characters with tags.',
        'm23f.filter.search': 'Search characters and tags',
        'm23f.filter.exclude': 'Exclude mode',
        'm23f.filter.excludeHint': 'The listed characters and tags are excluded instead.',
        'm23f.filter.tag': '[Tag] {name}',
        'm23f.filter.missing': 'not found',
        'm23f.filter.missingNote':
            'Some names do not match any character (renamed or deleted). They are kept until you remove them.',
        'm23f.filter.dropMissing': 'Remove missing',
        'm23f.filter.remove': 'Remove {name}',
        'm23f.filter.nobody': 'Nothing selected: the entry works for every character.',
        'm23f.filter.more': '{count} more — refine the search.',
        'm23f.filter.empty': 'No characters or tags in this SillyTavern.',
        'm23f.trigger.label': 'Generation types',
        'm23f.trigger.hint': 'Nothing selected — all types.',
        'm23f.trigger.unknown': 'Unknown types are kept as stored (ST’s editor would drop them): {values}',
        'm23f.trigger.normal': 'Normal',
        'm23f.trigger.continue': 'Continue',
        'm23f.trigger.impersonate': 'Impersonate',
        'm23f.trigger.swipe': 'Swipe',
        'm23f.trigger.regenerate': 'Regenerate',
        'm23f.trigger.quiet': 'Quiet',

        'm23f.src.hint': 'Besides the chat, look for the keys in:',
        'm23f.src.matchPersonaDescription': 'Persona description',
        'm23f.src.matchCharacterDescription': 'Character description',
        'm23f.src.matchCharacterPersonality': 'Character personality',
        'm23f.src.matchCharacterDepthPrompt': 'Character’s note',
        'm23f.src.matchScenario': 'Scenario',
        'm23f.src.matchCreatorNotes': 'Creator’s notes',

        'm23f.svc.uid': 'UID (for /getentryfield and other commands)',
        'm23f.svc.automation': 'Automation ID',
        'm23f.svc.automationNone': '(none)',
        'm23f.svc.automationHint': 'Quick Reply scripts with this id run when the entry fires.',
        'm23f.svc.selective': 'Selective (use secondary keys)',
        'm23f.svc.selectiveHint': 'Hidden in ST: its editor always switches it on.',
        'm23f.svc.addMemo': 'Add memo',
        'm23f.svc.addMemoHint': 'Hidden in ST and unused by the engine; kept as stored.',
        'm23f.svc.cardBook': 'A book from a character card: the store mirrors changes into its originalData.',
        'm23f.svc.unknown': 'Fields of other extensions: {fields}',
        'm23f.svc.unknownKept': 'Fields the studio does not know are kept as they are.',
        'm23f.st.title': 'What ST’s own editor would change',
        'm23f.st.intro':
            'ST’s World Info window silently changes these values when it shows or opens the entry (written with the next save of the book). The studio keeps them as stored:',
        'm23f.st.none': 'Nothing: ST’s editor would keep this entry as it is.',
        'm23f.st.engine': 'changes how it fires',
        'm23f.st.banner':
            'Opening this entry in ST’s window would change how it fires: {fields}. The studio keeps the stored values.',
        'm23f.st.apply': 'Turn on «selective» and the roll',
        'm23f.st.applyHint': 'Sets selective and useProbability like ST’s editor does (as an edit you save).',

        'm23f.num.notNumber': 'Not a number.',
        'm23f.num.required': 'Enter a number.',
        'm23f.num.negative': 'Not less than {min}.',
        'm23f.num.notInteger': 'A whole number.',
        'm23f.num.clampedMin': 'Raised to {value} (the minimum).',
        'm23f.num.clampedMax': 'Lowered to {value} (the maximum).',
        'm23f.num.floored': 'Rounded down to {value}.',

        'm23f.canon.base': 'Base',
        'm23f.canon.override.title': 'Canon override',
        'm23f.canon.noKeys': 'no keys',
        'm23f.canon.emptyContent': '(empty)',
        'm23f.canon.diff': 'Base → canon',
        'm23f.canon.keysDiff': 'Keys: base → canon',
        'm23f.canon.noOverride': 'No override: this chat uses the base entry as it is.',
        'm23f.canon.drift': 'The base changed after the override was made: compare and update the override if needed.',
        'm23f.canon.override': 'Override in canon',
        'm23f.canon.overrideHint':
            'Copies the entry into this chat’s canon and opens the copy; the base book is not changed.',
        'm23f.canon.overrideDone': 'Override created.',
        'm23f.canon.editOverride': 'Edit the override',
        'm23f.canon.saveFirst': 'Save or undo the edits of the base entry first.',
        'm23f.canon.promote': 'Promote to the base',
        'm23f.canon.promoteHint': 'Writes the override into the base book for every chat (asks first).',
        'm23f.canon.promoted': 'The override is now in the base book.',
        'm23f.canon.promoteDeclined': 'Not promoted (declined or queued in the Inbox).',
        'm23f.canon.removeOverride': 'Remove the override',
        'm23f.canon.removeTitle': 'Remove the override?',
        'm23f.canon.removeBody': 'This chat goes back to the base entry. The change is journaled and can be undone.',
        'm23f.canon.removed': 'Override removed.',
        'm23f.canon.suppress': 'Suppress in this chat',
        'm23f.canon.suppressHint': 'The entry does not reach the prompt in this chat; the book is not changed.',
        'm23f.canon.suppressed': 'Suppressed in this chat.',
        'm23f.canon.unsuppress': 'Stop suppressing',
        'm23f.canon.unsuppressed': 'No longer suppressed.',
        'm23f.canon.isSuppressed': 'Suppressed in this chat.',
        'm23f.canon.pin': 'Pin',
        'm23f.canon.pinHint': 'The entry fires on every turn of this chat.',
        'm23f.canon.pinned': 'Pinned in this chat.',
        'm23f.canon.unpin': 'Unpin',
        'm23f.canon.unpinned': 'Unpinned.',
        'm23f.canon.isPinned': 'Pinned in this chat: fires on every turn.',
        'm23f.canon.failed': 'Canon action failed: {error}',
        'm23f.canon.loadFailed': 'Could not read the canon of this chat.',
        'm23f.canon.status.active': 'active',
        'm23f.canon.status.provisional': 'provisional',
        'm23f.canon.status.archived': 'archived',
        'm23f.canon.provisionalTurns': 'provisional · {count} turns without contradiction',
        'm23f.canon.provisionalNote':
            'A provisional fact: it becomes canon after a few turns without contradiction (M26).',
        'm23f.canon.kind.override': 'override',
        'm23f.canon.kind.addition': 'addition',
        'm23f.canon.kind.suppress': 'suppression',
        'm23f.canon.kind.pin': 'pin',
        'm23f.canon.origin.user': 'by you',
        'm23f.canon.origin.revision': 'from revision',
        'm23f.canon.origin.living': 'living canon',
        'm23f.canon.origin.chronicle': 'chronicle',
        'm23f.canon.origin.backstage': 'backstage',
        'm23f.canon.origin.entity': 'world model',
        'm23f.canon.origin.import': 'imported',
        'm23f.canon.baseLink': 'Base: «{book}» #{uid}',
        'm23f.canon.openBase': 'Open the base',
        'm23f.canon.baseGone': 'The base entry is gone.',
        'm23f.canon.diffBaseNow': 'Base now → this override',
        'm23f.canon.created': 'created {time}',
        'm23f.canon.updated': 'changed {time}',
        'm23f.canon.source': 'from message #{index}',

        'm23f.stats.title': 'Activations in this chat',
        'm23f.stats.noJournal': 'The lore journal (M1) is off: no activation statistics.',
        'm23f.stats.noTurns': 'No turns recorded in this chat yet.',
        'm23f.stats.frequency': 'Fired',
        'm23f.stats.frequencyValue': '{count} of {turns} turns ({percent})',
        'm23f.stats.last': 'Last time',
        'm23f.stats.lastValue': 'message #{index}, {time}',
        'm23f.stats.never': 'never',
        'm23f.stats.avgChars': 'Average size, chars',
        'm23f.stats.lastKey': 'Last key',
        'm23f.stats.findKey': 'Find the key',
        'm23f.stats.noKey': 'no key (constant, sticky or forced)',
        'm23f.stats.cut': 'Cut by the budget or a rule: {count} times.',
        'm23f.stats.recent': 'Recent activations',
        'm23f.stats.recentItem': 'message #{index}, {time}, {chars} chars',
        'm23f.stats.recentKey': 'key: {key}',
        'm23f.stats.recentRecursion': 'recursion {level}',
        'm23f.stats.recentCut': 'cut',
        'm23f.doctor.title': 'Doctor findings',
        'm23f.doctor.off': 'The doctor (M5) is off.',
        'm23f.doctor.none': 'No findings for this entry in the last check.',
        'm23f.doctor.sev.error': 'error',
        'm23f.doctor.sev.warn': 'warning',
        'm23f.doctor.sev.info': 'note',
        'm23f.doctor.ruleOn': 'Fixed on the fly by «{rule}» (on).',
        'm23f.doctor.ruleOff': 'Rule «{rule}» fixes it on the fly (off).',
        'm23f.doctor.ruleUnknown': 'Fixing rule: {rule}',
        'm23f.doctor.openRules': 'Open «Rules»',

        'm23f.test.label': 'Text',
        'm23f.test.placeholder': 'Paste a message or a few lines of the chat',
        'm23f.test.hint':
            'Checked against the keys as they are in the form now (unsaved edits included). Ctrl+Enter runs it.',
        'm23f.test.run': 'Check',
        'm23f.test.enterText': 'Enter some text first.',
        'm23f.test.yes': 'Fires.',
        'm23f.test.no': 'Does not fire.',
        'm23f.test.primary': 'Primary keys',
        'm23f.test.secondary': 'Secondary keys ({logic})',
        'm23f.test.secondaryIgnored': 'Secondary keys (ignored: «selective» is off)',
        'm23f.test.hit': 'found',
        'm23f.test.miss': 'not found',
        'm23f.test.secondaryFailed': 'A primary key matched, but the secondary keys do not satisfy «{logic}».',
        'm23f.test.outcome.disabled': 'The entry is disabled.',
        'm23f.test.outcome.dontActivate': '@@dont_activate switches it off.',
        'm23f.test.outcome.activateDecorator': '@@activate fires it without keys.',
        'm23f.test.outcome.constant': 'A constant entry fires without keys.',
        'm23f.test.outcome.noKeys': 'The entry has no primary keys.',
        'm23f.test.outcome.noPrimary': 'No primary key matched.',
        'm23f.test.outcome.activated': 'Matched by its keys.',
        'm23f.test.scope': 'Probability, timers, filters, groups and the budget are not part of this check.',

        'm23f.hist.empty': 'No earlier versions saved through Maestro yet.',
        'm23f.hist.failed': 'Could not read the history.',
        'm23f.hist.diff': 'Compare with now',
        'm23f.hist.restore': 'Restore this version',
        'm23f.hist.restored': 'The version of {time} is restored.',
        'm23f.hist.restoreSummary': 'Lore Studio: entry #{entry} restored to the version of {time}',
        'm23f.hist.same': 'This version matches the current entry.',
        'm23f.hist.discardBody': 'Restoring drops your unsaved edits. Continue?',
        'm23f.hist.all': 'Show all ({count})',
        'm23f.hist.by.user': 'you (Lore Studio)',
        'm23f.hist.by.localizer': 'Lorebook Localizer',
        'm23f.hist.by.ck': 'CarrotKernel',
        'm23f.hist.by.st': 'outside Maestro',

        'm23f.role.bunnymo.core': 'BunnyMo core',
        'm23f.role.bunnymo.pack': 'BunnyMo pack',
        'm23f.role.ck.archive': 'CK archive',
        'm23f.role.world': 'world',
        'm23f.role.card': 'card book',
        'm23f.role.npc': 'NPC book',
        'm23f.role.canon': 'chat canon',
        'm23f.role.maestro': 'Maestro book',
        'm23f.role.chat': 'chat book',
        'm23f.role.persona': 'persona book',
        'm23f.role.backup': 'backup',
        'm23f.role.unknown': 'unknown role',
    },
    ru: {
        'm23f.loading': 'Загрузка…',
        'm23f.loadFailed': 'Не удалось загрузить запись: {error}',
        'm23f.notFound': 'В книге «{book}» нет записи №{uid} (удалена или перенесена).',
        'm23f.legend': 'Поля записи',
        'm23f.back': 'Назад',
        'm23f.close': 'Закрыть',
        'm23f.uid': 'UID {uid}',
        'm23f.dirty': '● не сохранено',
        'm23f.save': 'Сохранить',
        'm23f.saveHint': 'Сохранить изменённые поля (Ctrl+S)',
        'm23f.revert': 'Отменить правки',
        'm23f.reverted': 'Правки отменены: запись такая, как сохранена.',
        'm23f.enabled': 'Включена',
        'm23f.badge.disabled': 'выключена',
        'm23f.badge.readOnly': 'только чтение',

        'm23f.save.saving': 'Сохраняю…',
        'm23f.save.done': 'Сохранено.',
        'm23f.save.nothing': 'Ничего не изменилось.',
        'm23f.save.failed': 'Не сохранено: {error}',
        'm23f.save.blocked': 'Сначала исправь отмеченные поля.',
        'm23f.save.fixErrors': 'Поля с ошибками: {fields}',
        'm23f.save.summary': 'Лор-студия: «{entry}» в «{book}» — {fields}',
        'm23f.discard.title': 'Несохранённые правки',
        'm23f.discard.body': 'В записи есть несохранённые правки. Уйти без сохранения?',

        'm23f.external.changed': 'Пока ты редактировал запись, её изменили вне студии.',
        'm23f.external.reload': 'Показать новую версию (мои правки пропадут)',
        'm23f.external.reloaded': 'Запись изменили вне студии — в форме уже новая версия.',
        'm23f.external.gone': 'Записи больше нет в книге.',

        'm23f.ro.bunnymo':
            'Паки BunnyMo никогда не редактируются: ни текст, ни ключи, ни переводы (P13). Технические исправления (роль, рекурсия, дубли) Maestro делает на лету во вкладке «Правила» — каждое можно выключить.',
        'm23f.ro.generic': 'Книга открыта только для чтения.',
        'm23f.ro.openRules': 'Открыть «Правила»',

        'm23f.section.keys': 'Ключи и условия',
        'm23f.section.content': 'Содержимое',
        'm23f.section.placement': 'Размещение',
        'm23f.section.activation': 'Активация и рекурсия',
        'm23f.section.timers': 'Таймеры',
        'm23f.section.groups': 'Группы',
        'm23f.section.filters': 'Фильтры и триггеры',
        'm23f.section.sources': 'Источники сканирования',
        'm23f.section.service': 'Служебное',
        'm23f.section.passport': 'Паспорт',
        'm23f.section.canon': 'Канон чата · {book}',
        'm23f.section.canonEntry': 'Запись канона',
        'm23f.section.insights': 'Аналитика и доктор',
        'm23f.section.tester': 'Проверить срабатывание',
        'm23f.section.history': 'История версий',
        'm23f.passport.loading': 'Читаю паспорт…',
        'm23f.passport.none': 'У записи пока нет паспорта.',
        'm23f.passport.bunnymo': 'У записей паков BunnyMo паспортов не бывает (P13).',
        'm23f.passport.noRegistry':
            'Паспорт записи базовой книги хранится в реестре Maestro — включи модуль «Роли книг».',
        'm23f.passport.badge.entry': 'в записи',
        'm23f.passport.badge.sidecar': 'реестр Maestro',
        'm23f.passport.whereEntry': 'Хранится в самой записи (extensions.maestro) и переезжает вместе с книгой.',
        'm23f.passport.whereSidecar': 'Хранится в реестре Maestro: файл книги не меняется (P2).',
        'm23f.passport.madeBy': 'Автор: {by}',
        'm23f.passport.by.nai': 'NAI Studio',
        'm23f.passport.by.model': 'фоновая модель',
        'm23f.passport.by.user': 'вручную',
        'm23f.passport.stale':
            'Текст записи изменился после того, как сделан паспорт: проверь его или сгенерируй заново.',
        'm23f.passport.kind': 'Что это',
        'm23f.passport.kind.character': 'Персонаж или существо',
        'm23f.passport.kind.location': 'Место',
        'm23f.passport.kind.object': 'Предмет',
        'm23f.passport.kind.world': 'Мир, фракция, культура',
        'm23f.passport.kind.scenario': 'Сценарий',
        'm23f.passport.name': 'Имя',
        'm23f.passport.aliases': 'Другие имена',
        'm23f.passport.aliasesHint':
            'Через запятую; русские написания помогают NAI Studio узнавать его в русском тексте.',
        'm23f.passport.tags': 'Теги',
        'm23f.passport.tagsHint': 'Английские теги Danbooru в нижнем регистре через запятую — как это выглядит.',
        'm23f.passport.slot.base': 'Основа (сколько, кто)',
        'm23f.passport.slot.hair': 'Волосы',
        'm23f.passport.slot.eyes': 'Глаза',
        'm23f.passport.slot.body': 'Телосложение',
        'm23f.passport.slot.skin': 'Кожа',
        'm23f.passport.slot.clothing': 'Одежда',
        'm23f.passport.slot.accessories': 'Аксессуары',
        'm23f.passport.slot.style': 'Стиль рисовки',
        'm23f.passport.nsfwOn': 'Использовать слой NSFW в откровенных сценах',
        'm23f.passport.nsfw': 'Слой NSFW',
        'm23f.passport.nsfwHint':
            'Откровенная анатомия — только сюда: NAI Studio добавляет её лишь в откровенные сцены.',
        'm23f.passport.negative': 'Никогда не рисовать',
        'm23f.passport.outfit': 'Наряд',
        'm23f.passport.state': 'Состояние',
        'm23f.passport.outfits': 'Наряды: {list}',
        'm23f.passport.states': 'Включённые состояния: {list}',
        'm23f.passport.dirty': '● правки паспорта не сохранены',
        'm23f.passport.issue.notEnglish': '{field}: «{tag}» — не английский тег.',
        'm23f.passport.issue.upperCase': '{field}: «{tag}» — нужен нижний регистр.',
        'm23f.passport.issue.underscore': '{field}: «{tag}» — NovelAI понимает пробелы, а не подчёркивания.',
        'm23f.passport.issue.anatomy': '{field}: «{tag}» — откровенная анатомия, ей место только в слое NSFW.',
        'm23f.passport.issue.empty': 'Пока рисовать нечего — заполни теги.',
        'm23f.passport.fixFirst': 'Сначала исправь ошибки в паспорте.',
        'm23f.passport.save': 'Сохранить паспорт',
        'm23f.passport.revert': 'Отменить правки паспорта',
        'm23f.passport.fix': 'Исправить автоматически',
        'm23f.passport.generate': 'Сгенерировать',
        'm23f.passport.create': 'Сделать вручную',
        'm23f.passport.remove': 'Убрать',
        'm23f.passport.working': 'Работаю…',
        'm23f.passport.saved': 'Паспорт сохранён.',
        'm23f.passport.removed': 'Паспорт убран.',
        'm23f.passport.generated': 'Паспорт сгенерирован ({by}) и сохранён.',
        'm23f.passport.nothing': 'Ничего не сгенерировалось.',
        'm23f.passport.kept': 'Паспорт остался прежним.',
        'm23f.passport.removeTitle': 'Убрать паспорт?',
        'm23f.passport.removeBody': 'Паспорт записи «{entry}» будет убран (вернуть его можно из журнала).',
        'm23f.passport.overwriteTitle': 'Заменить паспорт?',
        'm23f.passport.overwriteBody': 'Этот паспорт сделан или поправлен вручную. Заменить его сгенерированным?',
        'm23f.passport.discardTitle': 'Несохранённые правки паспорта',
        'm23f.passport.discardBody': 'В паспорте есть несохранённые правки. Отбросить их и сгенерировать новый?',

        'm23f.keys.primary': 'Основные ключевые слова',
        'm23f.keys.secondary': 'Дополнительный фильтр (вторичные ключи)',
        'm23f.keys.placeholder': 'Через запятую: Аня, Анечка, /Ан(я|ечк)/i',
        'm23f.keys.help':
            'Запятая разделяет ключи, кроме запятых внутри регулярки /…/флаги. Регулярка не смотрит на настройки регистра и целых слов (регистр — флаг i). Макросы вроде {{char}} в ключах работают.',
        'm23f.keys.chipRegex': 'Регулярное выражение',
        'm23f.keys.chipLocalizer': 'Добавлен Lorebook Localizer',
        'm23f.keys.badgeLocalizer': 'LL',
        'm23f.keys.noKeys':
            'Без основных ключей запись срабатывает только как постоянная, по @@activate или через другие расширения.',
        'm23f.keys.issue.badRegex':
            'Похоже на регулярку, но ST её не разберёт и будет искать как обычный текст: {keys}',
        'm23f.keys.issue.comma':
            'Запятая внутри ключа (её удержал непарный слеш): ST хранит это как один ключ — {keys}',
        'm23f.keys.issue.macroBrace': 'Движок макросов ST превращает \\{ в { ещё до поиска; пиши [{]: {keys}',
        'm23f.keys.issue.macro': 'В этих ключах перед поиском подставляются макросы: {keys}',
        'm23f.keys.issue.cyrillicWholeWord':
            '«Целые слова» в ST не знают кириллицы (\\W в JS): эти ключи сработают и внутри других слов — {keys}. Поможет правило M22 или регулярка /…/iu.',
        'm23f.keys.issue.duplicate': 'Повторяются ключи: {keys}',
        'm23f.keys.selectiveOff':
            'Вторичные ключи сейчас не работают: «Выборочно» (selective) выключено. Окно ST включит его, как только запись откроют там.',
        'm23f.keys.selectiveFix': 'Учитывать вторичные ключи',

        'm23f.logic.label': 'Логика',
        'm23f.logic.hint': 'Как вторичные ключи сочетаются с найденным основным.',
        'm23f.logic.0': 'И ЛЮБОЙ',
        'm23f.logic.3': 'И ВСЕ',
        'm23f.logic.1': 'НЕ ВСЕ',
        'm23f.logic.2': 'НЕ ЛЮБОЙ',
        'm23f.logic.other': 'Неизвестная ({value})',

        'm23f.ru.localizer': 'Русские ключи',
        'm23f.ru.localizerHint':
            'Lorebook Localizer переведёт ключи этой записи и добавит русские формы (сам запишет книгу).',
        'm23f.ru.forms': 'Русские ключи',
        'm23f.ru.formsHint': 'Добавить русские формы английских ключей (склонения DES-RU через модуль канона).',
        'm23f.ru.saveFirst': 'Сначала сохрани или отмени правки: Localizer сам записывает книгу.',
        'm23f.ru.working': 'Ищу русские формы…',
        'm23f.ru.localizerDone': 'Localizer добавил ключей: {added}.',
        'm23f.ru.localizerFailed': 'Localizer добавил ключей: {added}; не переведено записей: {failures}.',
        'm23f.ru.failed': 'Localizer не справился: {error}',
        'm23f.ru.noTerms': 'Нет простых английских ключей для перевода.',
        'm23f.ru.nothingNew': 'Новых форм нет.',
        'm23f.ru.added': 'Добавлено ключей: {count} — проверь и сохрани.',
        'm23f.ru.unavailable': 'Нужен Lorebook Localizer или канон чата с DES-RU.',

        'm23f.comment.label': 'Название / заметка',
        'm23f.comment.placeholder': 'Название или заметка о записи',
        'm23f.comment.hint': 'Только для тебя: в промпт не попадает.',
        'm23f.content.label': 'Содержимое',
        'm23f.content.placeholder': 'Что ИИ должен знать об этом ключевом слове',
        'm23f.content.tokens': 'Токенов: {count}',
        'm23f.content.chars': 'Символов: {count}',
        'm23f.content.expand': 'Развернуть редактор',
        'm23f.deco.activate':
            '@@activate: запись срабатывает без ключей (после фильтров, таймеров и проверок рекурсии).',
        'm23f.deco.dontActivate':
            '@@dont_activate: запись не срабатывает никогда — ни постоянной, ни липкой, ни по ключам, ни извне.',
        'm23f.deco.unknown': 'Неизвестные декораторы молча вырезаются из промпта: {lines}',
        'm23f.deco.helpTitle': 'Декораторы',
        'm23f.deco.help':
            'Строки в самом начале содержимого: @@activate включает запись без ключей, @@dont_activate выключает её. Все строки @@ в начале вырезаются из промпта; @@@x читается как @@x только после неизвестного декоратора. Если содержимое состоит из одних строк @@, ничего не вырезается.',

        'm23f.typed.label': 'Тип записи',
        'm23f.typed.none': '— без типа —',
        'm23f.typed.compose': 'Собрать содержимое из полей',
        'm23f.typed.composeHint':
            'Пишет строки «Label: значение» (подписи по-английски, значения как введены). Готовый текст заменяется только после подтверждения.',
        'm23f.typed.composed': 'Содержимое собрано из полей — проверь и сохрани.',
        'm23f.typed.emptyFields': 'Поля пустые.',
        'm23f.typed.same': 'Содержимое уже совпадает с полями.',
        'm23f.typed.replaceTitle': 'Заменить содержимое?',
        'm23f.typed.replaceBody': 'В записи уже есть текст. Он будет заменён текстом, собранным из полей:',
        'm23f.typed.whereEntry':
            'Хранится в самой записи (extensions.maestro); другие расширения видят только содержимое.',
        'm23f.typed.whereSidecar': 'Хранится в реестре Maestro: файл книги остаётся таким, как его сделал автор (P2).',
        'm23f.typed.unavailable': 'Типам записей базовых книг нужен модуль ролей книг (M35).',

        'm23f.type.character': 'Персонаж',
        'm23f.type.place': 'Место',
        'm23f.type.item': 'Предмет',
        'm23f.type.faction': 'Фракция',
        'm23f.type.event': 'Событие',
        'm23f.type.tradition': 'Традиция',
        'm23f.type.mechanic': 'Механика',
        'm23f.type.rule': 'Правило',
        'm23f.type.chapter': 'Глава летописи',
        'm23f.type.note': 'Заметка',

        'm23f.tf.name': 'Имя / название',
        'm23f.tf.aliases': 'Другие имена',
        'm23f.tf.role': 'Роль',
        'm23f.tf.age': 'Возраст',
        'm23f.tf.appearance': 'Внешность',
        'm23f.tf.personality': 'Характер',
        'm23f.tf.background': 'Предыстория',
        'm23f.tf.relationships': 'Отношения',
        'm23f.tf.speech': 'Манера речи',
        'm23f.tf.goals': 'Цели',
        'm23f.tf.kind': 'Вид',
        'm23f.tf.location': 'Где находится',
        'm23f.tf.description': 'Описание',
        'm23f.tf.atmosphere': 'Атмосфера',
        'm23f.tf.inhabitants': 'Обитатели',
        'm23f.tf.features': 'Приметы',
        'm23f.tf.secrets': 'Тайны',
        'm23f.tf.properties': 'Свойства',
        'm23f.tf.owner': 'Владелец',
        'm23f.tf.origin': 'Происхождение',
        'm23f.tf.whereabouts': 'Где сейчас',
        'm23f.tf.leader': 'Лидер',
        'm23f.tf.members': 'Состав',
        'm23f.tf.territory': 'Территория',
        'm23f.tf.allies': 'Союзники',
        'm23f.tf.enemies': 'Враги',
        'm23f.tf.symbols': 'Символы и обычаи',
        'm23f.tf.when': 'Когда',
        'm23f.tf.where': 'Где',
        'm23f.tf.participants': 'Участники',
        'm23f.tf.consequences': 'Последствия',
        'm23f.tf.culture': 'Чья традиция',
        'm23f.tf.practice': 'Как проходит',
        'm23f.tf.meaning': 'Смысл',
        'm23f.tf.taboos': 'Запреты',
        'm23f.tf.summary': 'Кратко',
        'm23f.tf.rules': 'Правила',
        'm23f.tf.limits': 'Цена и ограничения',
        'm23f.tf.examples': 'Примеры',
        'm23f.tf.statement': 'Правило',
        'm23f.tf.scope': 'Где действует',
        'm23f.tf.exceptions': 'Исключения',
        'm23f.tf.period': 'Период',
        'm23f.tf.events': 'Главные события',
        'm23f.tf.characters': 'Персонажи',
        'm23f.tf.threads': 'Незакрытые линии',
        'm23f.tf.text': 'Текст',

        'm23f.state.label': 'Статус',
        'm23f.state.hint':
            'Постоянная срабатывает без ключей. Векторизованная по-прежнему срабатывает по ключам, её может включить и Vector Storage.',
        'm23f.state.constant': 'Постоянная',
        'm23f.state.normal': 'Обычная (по ключам)',
        'm23f.state.vectorized': 'Векторизованная',

        'm23f.pos.label': 'Положение',
        'm23f.pos.before': '↑Перс. — перед описанием персонажа',
        'm23f.pos.after': '↓Перс. — после описания персонажа',
        'm23f.pos.emTop': '↑ПС — перед примерами сообщений',
        'm23f.pos.emBottom': '↓ПС — после примеров сообщений',
        'm23f.pos.anTop': '↑АЗ — перед заметками автора',
        'm23f.pos.anBottom': '↓АЗ — после заметок автора',
        'm23f.pos.depthSystem': 'На глуб. ⚙️ — на глубине, от системы',
        'm23f.pos.depthUser': 'На глуб. 👤 — на глубине, от пользователя',
        'm23f.pos.depthAssistant': 'На глуб. 🤖 — на глубине, от ассистента',
        'm23f.pos.outlet': '➡️ Outlet — только через {{outlet::имя}}',
        'm23f.pos.other': 'Другое ({value}) — сохраняется как есть',
        'm23f.pos.missing': 'Положение не записано: движок никуда не вставит запись. Окно ST сделало бы его «↑Перс.».',
        'm23f.pos.anHint':
            'Положения у заметок автора попадают в промпт только в те ходы, когда вставляется сама заметка автора.',
        'm23f.depth.label': 'Глубина',
        'm23f.depth.hint': 'Сообщений от конца чата. Записи с одинаковыми глубиной и ролью склеиваются в один блок.',
        'm23f.outlet.label': 'Имя outlet',
        'm23f.outlet.placeholder': 'например, scene',
        'm23f.outlet.hint':
            'Содержимое попадёт в промпт только туда, где стоит {{outlet::имя}} (несколько имён — через запятую).',
        'm23f.outlet.empty': 'Outlet без имени: ST пропустит запись.',
        'm23f.order.label': 'Приоритет',
        'm23f.order.hint': 'Чем больше приоритет, тем ближе к концу своего блока (у outlet — наоборот).',

        'm23f.prob.label': '% срабатывания',
        'm23f.prob.use': 'Бросать кубик вероятности',
        'm23f.prob.useHint': 'ST прячет этот флажок и включает его, когда запись открывают в его окне.',
        'm23f.prob.empty':
            'Вероятность не записана: ST бросает кубик против пустого значения, и запись почти никогда не срабатывает.',
        'm23f.prob.notRolled':
            'Бросок сейчас выключен, поэтому {value}% не действует. Окно ST включит бросок, как только запись откроют там.',
        'm23f.scan.label': 'Глубина сканирования',
        'm23f.scan.global': 'Глобальная настройка',
        'm23f.scan.globalNow': 'Глобальная ({value})',
        'm23f.scan.hint': 'Пусто — глобальная настройка. 0…1000 сообщений.',
        'm23f.case.label': 'С учётом регистра',
        'm23f.case.hint': 'На ключи-регулярки не влияет (для них — флаг i).',
        'm23f.whole.label': 'Целые слова',
        'm23f.whole.hint': 'Ключ из нескольких слов всегда ищется подстрокой; для кириллицы нужно правило M22.',
        'm23f.tri.global': 'Глобальная настройка',
        'm23f.tri.globalNow': 'Глобальная (сейчас: {value})',
        'm23f.tri.yes': 'Да',
        'm23f.tri.no': 'Нет',
        'm23f.rec.exclude': 'Не рекурсивная',
        'm23f.rec.excludeHint': 'Не активируется текстом других записей (на шагах рекурсии).',
        'm23f.rec.prevent': 'Пресечь дальнейшую рекурсию',
        'm23f.rec.preventHint': 'Её содержимое не активирует другие записи.',
        'm23f.rec.delay': 'Только при рекурсии',
        'm23f.rec.delayHint': 'Активируется только на шагах рекурсии.',
        'm23f.rec.level': 'Уровень рекурсии',
        'm23f.rec.levelHint':
            'Пусто — уровень 1. Уровни открываются по возрастанию: следующий — когда на текущем больше нечего активировать.',
        'm23f.rec.levelPlaceholder': '1',
        'm23f.rec.levelInvalid': 'Уровень — это число (1, 2, …).',
        'm23f.budget.ignore': 'Игнорировать бюджет',
        'm23f.budget.ignoreHint': 'Вставляется даже после переполнения бюджета лора.',

        'm23f.timer.sticky': 'Липучка',
        'm23f.timer.stickyHint': 'Сколько сообщений запись остаётся активной после срабатывания.',
        'm23f.timer.cooldown': 'Перезарядка',
        'm23f.timer.cooldownHint': 'Сколько сообщений после срабатывания запись не может сработать снова.',
        'm23f.timer.delay': 'Задержка',
        'm23f.timer.delayHint': 'Не срабатывает, пока в чате меньше сообщений.',
        'm23f.timer.none': 'Нет',
        'm23f.timer.hashReset':
            'Любая правка записи меняет её хеш и обрывает идущие липучку и перезарядку в открытых чатах.',

        'm23f.group.label': 'Группа включения',
        'm23f.group.placeholder': 'группа, другая группа',
        'm23f.group.hint':
            'Из записей с одной меткой за сканирование срабатывает только одна. Несколько групп — через запятую.',
        'm23f.group.suggest': 'Группы этой книги',
        'm23f.group.override': 'Важная',
        'm23f.group.overrideHint': 'Среди сработавших записей группы побеждает важная с наибольшим приоритетом.',
        'm23f.group.weight': 'Вес в группе',
        'm23f.group.weightHint': 'Относительный шанс выиграть в группе (1…10000).',
        'm23f.group.scoring': 'Групповой подсчёт',
        'm23f.group.scoringHint': 'Записи, у которых совпало меньше ключей, выбывают из группы.',

        'm23f.filter.label': 'Персонажи и теги',
        'm23f.filter.hint': 'Привязать запись к персонажам (по файлу аватара) или к персонажам с тегами.',
        'm23f.filter.search': 'Поиск персонажей и тегов',
        'm23f.filter.exclude': 'Режим исключения',
        'm23f.filter.excludeHint': 'Отмеченные персонажи и теги, наоборот, исключаются.',
        'm23f.filter.tag': '[Тег] {name}',
        'm23f.filter.missing': 'не найден',
        'm23f.filter.missingNote':
            'Часть имён не совпадает ни с одним персонажем (переименован или удалён). Они остаются, пока ты их не уберёшь.',
        'm23f.filter.dropMissing': 'Убрать отсутствующих',
        'm23f.filter.remove': 'Убрать {name}',
        'm23f.filter.nobody': 'Ничего не выбрано: запись работает для всех персонажей.',
        'm23f.filter.more': 'Ещё {count} — уточни поиск.',
        'm23f.filter.empty': 'В этом SillyTavern нет персонажей и тегов.',
        'm23f.trigger.label': 'Типы генерации',
        'm23f.trigger.hint': 'Ничего не выбрано — все типы.',
        'm23f.trigger.unknown': 'Неизвестные типы сохраняются как есть (окно ST их выбросило бы): {values}',
        'm23f.trigger.normal': 'Обычная',
        'm23f.trigger.continue': 'Продолжение',
        'm23f.trigger.impersonate': 'Перевоплощение',
        'm23f.trigger.swipe': 'Свайп',
        'm23f.trigger.regenerate': 'Повторная генерация',
        'm23f.trigger.quiet': 'Тихая',

        'm23f.src.hint': 'Кроме чата, искать ключи ещё и в:',
        'm23f.src.matchPersonaDescription': 'Описание персоны',
        'm23f.src.matchCharacterDescription': 'Описание персонажа',
        'm23f.src.matchCharacterPersonality': 'Характер персонажа',
        'm23f.src.matchCharacterDepthPrompt': 'Заметка о персонаже',
        'm23f.src.matchScenario': 'Сценарий',
        'm23f.src.matchCreatorNotes': 'Заметки создателя',

        'm23f.svc.uid': 'UID (для /getentryfield и других команд)',
        'm23f.svc.automation': 'Automation ID',
        'm23f.svc.automationNone': '(нет)',
        'm23f.svc.automationHint': 'Скрипты Quick Reply с этим id запускаются, когда запись срабатывает.',
        'm23f.svc.selective': 'Выборочно (учитывать вторичные ключи)',
        'm23f.svc.selectiveHint': 'В ST этот флажок спрятан: его окно всегда его включает.',
        'm23f.svc.addMemo': 'Add Memo',
        'm23f.svc.addMemoHint': 'В ST спрятан, движком не используется; хранится как есть.',
        'm23f.svc.cardBook': 'Книга из карточки персонажа: хранилище дублирует изменения в её originalData.',
        'm23f.svc.unknown': 'Поля других расширений: {fields}',
        'm23f.svc.unknownKept': 'Незнакомые студии поля сохраняются как есть.',
        'm23f.st.title': 'Что поменяло бы окно ST',
        'm23f.st.intro':
            'Окно «Миры и лорбуки» молча меняет эти значения, когда показывает или открывает запись (в файл они попадут со следующим сохранением книги). Студия хранит их как есть:',
        'm23f.st.none': 'Ничего: окно ST оставило бы запись как есть.',
        'm23f.st.engine': 'меняет срабатывание',
        'm23f.st.banner':
            'Если открыть эту запись в окне ST, изменится её срабатывание: {fields}. Студия хранит значения как есть.',
        'm23f.st.apply': 'Включить «Выборочно» и бросок',
        'm23f.st.applyHint':
            'Включает selective и useProbability, как это делает окно ST (как обычная правка, которую ты сохранишь).',

        'm23f.num.notNumber': 'Это не число.',
        'm23f.num.required': 'Введи число.',
        'm23f.num.negative': 'Не меньше {min}.',
        'm23f.num.notInteger': 'Нужно целое число.',
        'm23f.num.clampedMin': 'Поднято до {value} (минимум).',
        'm23f.num.clampedMax': 'Снижено до {value} (максимум).',
        'm23f.num.floored': 'Округлено вниз до {value}.',

        'm23f.canon.base': 'База',
        'm23f.canon.override.title': 'Переопределение в каноне',
        'm23f.canon.noKeys': 'ключей нет',
        'm23f.canon.emptyContent': '(пусто)',
        'm23f.canon.diff': 'База → канон',
        'm23f.canon.keysDiff': 'Ключи: база → канон',
        'm23f.canon.noOverride': 'Переопределения нет: в этом чате действует базовая запись как есть.',
        'm23f.canon.drift':
            'База изменилась после того, как сделали переопределение: сравни и при необходимости обнови его.',
        'm23f.canon.override': 'Переопределить в каноне',
        'm23f.canon.overrideHint': 'Копирует запись в канон этого чата и открывает копию; базовая книга не меняется.',
        'm23f.canon.overrideDone': 'Переопределение создано.',
        'm23f.canon.editOverride': 'Изменить переопределение',
        'm23f.canon.saveFirst': 'Сначала сохрани или отмени правки базовой записи.',
        'm23f.canon.promote': 'Повысить до базы',
        'm23f.canon.promoteHint': 'Записать переопределение в базовую книгу для всех чатов (сначала спросит).',
        'm23f.canon.promoted': 'Переопределение перенесено в базовую книгу.',
        'm23f.canon.promoteDeclined': 'Не перенесено (отказ или карточка во «Входящих»).',
        'm23f.canon.removeOverride': 'Убрать переопределение',
        'm23f.canon.removeTitle': 'Убрать переопределение?',
        'm23f.canon.removeBody': 'Чат вернётся к базовой записи. Изменение попадёт в журнал, его можно откатить.',
        'm23f.canon.removed': 'Переопределение убрано.',
        'm23f.canon.suppress': 'Подавить в этом чате',
        'm23f.canon.suppressHint': 'Запись не попадёт в промпт этого чата; книга не меняется.',
        'm23f.canon.suppressed': 'Подавлена в этом чате.',
        'm23f.canon.unsuppress': 'Снять подавление',
        'm23f.canon.unsuppressed': 'Подавление снято.',
        'm23f.canon.isSuppressed': 'Подавлена в этом чате.',
        'm23f.canon.pin': 'Закрепить',
        'm23f.canon.pinHint': 'Запись срабатывает в каждом ходе этого чата.',
        'm23f.canon.pinned': 'Закреплена в этом чате.',
        'm23f.canon.unpin': 'Открепить',
        'm23f.canon.unpinned': 'Откреплена.',
        'm23f.canon.isPinned': 'Закреплена в этом чате: срабатывает в каждом ходе.',
        'm23f.canon.failed': 'Действие с каноном не удалось: {error}',
        'm23f.canon.loadFailed': 'Не удалось прочитать канон этого чата.',
        'm23f.canon.status.active': 'действует',
        'm23f.canon.status.provisional': 'пробная',
        'm23f.canon.status.archived': 'в архиве',
        'm23f.canon.provisionalTurns': 'пробная · ходов без противоречий: {count}',
        'm23f.canon.provisionalNote': 'Пробный факт: станет каноном после нескольких ходов без противоречий (M26).',
        'm23f.canon.kind.override': 'переопределение',
        'm23f.canon.kind.addition': 'дополнение',
        'm23f.canon.kind.suppress': 'подавление',
        'm23f.canon.kind.pin': 'закрепление',
        'm23f.canon.origin.user': 'от тебя',
        'm23f.canon.origin.revision': 'из ревизии',
        'm23f.canon.origin.living': 'живой канон',
        'm23f.canon.origin.chronicle': 'летопись',
        'm23f.canon.origin.backstage': 'закулисье',
        'm23f.canon.origin.entity': 'модель мира',
        'm23f.canon.origin.import': 'импорт',
        'm23f.canon.baseLink': 'База: «{book}» №{uid}',
        'm23f.canon.openBase': 'Открыть базу',
        'm23f.canon.baseGone': 'Базовой записи больше нет.',
        'm23f.canon.diffBaseNow': 'База сейчас → это переопределение',
        'm23f.canon.created': 'создана {time}',
        'm23f.canon.updated': 'изменена {time}',
        'm23f.canon.source': 'из сообщения №{index}',

        'm23f.stats.title': 'Срабатывания в этом чате',
        'm23f.stats.noJournal': 'Журнал лора (M1) выключен: статистики срабатываний нет.',
        'm23f.stats.noTurns': 'В этом чате ходов ещё нет.',
        'm23f.stats.frequency': 'Срабатывала',
        'm23f.stats.frequencyValue': 'в {count} из {turns} ходов ({percent})',
        'm23f.stats.last': 'Последний раз',
        'm23f.stats.lastValue': 'сообщение №{index}, {time}',
        'm23f.stats.never': 'ни разу',
        'm23f.stats.avgChars': 'Средний размер, симв.',
        'm23f.stats.lastKey': 'Последний ключ',
        'm23f.stats.findKey': 'Найти ключ',
        'm23f.stats.noKey': 'без ключа (постоянная, липучка или принудительно)',
        'm23f.stats.cut': 'Отрезана бюджетом или правилом: {count} раз.',
        'm23f.stats.recent': 'Последние срабатывания',
        'm23f.stats.recentItem': 'сообщение №{index}, {time}, {chars} симв.',
        'm23f.stats.recentKey': 'ключ: {key}',
        'm23f.stats.recentRecursion': 'рекурсия {level}',
        'm23f.stats.recentCut': 'отрезана',
        'm23f.doctor.title': 'Находки доктора',
        'm23f.doctor.off': 'Доктор (M5) выключен.',
        'm23f.doctor.none': 'В последней проверке находок по этой записи нет.',
        'm23f.doctor.sev.error': 'ошибка',
        'm23f.doctor.sev.warn': 'предупреждение',
        'm23f.doctor.sev.info': 'заметка',
        'm23f.doctor.ruleOn': 'Исправляется на лету правилом «{rule}» (включено).',
        'm23f.doctor.ruleOff': 'Правило «{rule}» исправляет это на лету (выключено).',
        'm23f.doctor.ruleUnknown': 'Исправляющее правило: {rule}',
        'm23f.doctor.openRules': 'Открыть «Правила»',

        'm23f.test.label': 'Текст',
        'm23f.test.placeholder': 'Вставь сообщение или несколько строк чата',
        'm23f.test.hint':
            'Проверяются ключи в том виде, в каком они сейчас в форме (с несохранёнными правками). Ctrl+Enter — проверить.',
        'm23f.test.run': 'Проверить',
        'm23f.test.enterText': 'Сначала введи текст.',
        'm23f.test.yes': 'Сработает.',
        'm23f.test.no': 'Не сработает.',
        'm23f.test.primary': 'Основные ключи',
        'm23f.test.secondary': 'Вторичные ключи ({logic})',
        'm23f.test.secondaryIgnored': 'Вторичные ключи (не учитываются: «Выборочно» выключено)',
        'm23f.test.hit': 'найден',
        'm23f.test.miss': 'не найден',
        'm23f.test.secondaryFailed': 'Основной ключ найден, но вторичные не выполняют условие «{logic}».',
        'm23f.test.outcome.disabled': 'Запись выключена.',
        'm23f.test.outcome.dontActivate': '@@dont_activate её выключает.',
        'm23f.test.outcome.activateDecorator': '@@activate включает её без ключей.',
        'm23f.test.outcome.constant': 'Постоянная запись срабатывает без ключей.',
        'm23f.test.outcome.noKeys': 'У записи нет основных ключей.',
        'm23f.test.outcome.noPrimary': 'Ни один основной ключ не найден.',
        'm23f.test.outcome.activated': 'Найдена по ключам.',
        'm23f.test.scope': 'Вероятность, таймеры, фильтры, группы и бюджет в этой проверке не учитываются.',

        'm23f.hist.empty': 'Прежних версий, сохранённых через Maestro, пока нет.',
        'm23f.hist.failed': 'Не удалось прочитать историю.',
        'm23f.hist.diff': 'Сравнить с текущей',
        'm23f.hist.restore': 'Вернуть эту версию',
        'm23f.hist.restored': 'Версия от {time} возвращена.',
        'm23f.hist.restoreSummary': 'Лор-студия: запись №{entry} возвращена к версии от {time}',
        'm23f.hist.same': 'Эта версия совпадает с текущей записью.',
        'm23f.hist.discardBody': 'Возврат версии сбросит несохранённые правки. Продолжить?',
        'm23f.hist.all': 'Показать все ({count})',
        'm23f.hist.by.user': 'ты (Лор-студия)',
        'm23f.hist.by.localizer': 'Lorebook Localizer',
        'm23f.hist.by.ck': 'CarrotKernel',
        'm23f.hist.by.st': 'вне Maestro',

        'm23f.role.bunnymo.core': 'ядро BunnyMo',
        'm23f.role.bunnymo.pack': 'пак BunnyMo',
        'm23f.role.ck.archive': 'архив CK',
        'm23f.role.world': 'мир',
        'm23f.role.card': 'книга карточки',
        'm23f.role.npc': 'книга NPC',
        'm23f.role.canon': 'канон чата',
        'm23f.role.maestro': 'книга Maestro',
        'm23f.role.chat': 'книга чата',
        'm23f.role.persona': 'книга персоны',
        'm23f.role.backup': 'резервная копия',
        'm23f.role.unknown': 'роль не определена',
    },
};
