// Builders of World Info entries and books for the doctor's tests (domain and feature).
import { toDoctorEntry } from '../../src/domain/doctor-types';
import type { DoctorEntry } from '../../src/domain/doctor-types';

let nextUid = 1000;

/** A normalised entry; `raw` uses ST's field names (key, content, position, role, …). */
export function entry(book: string, raw: Record<string, unknown> = {}, localizerKeys: string[] = []): DoctorEntry {
    const uid = typeof raw.uid === 'number' ? raw.uid : nextUid++;
    return toDoctorEntry(book, { key: [], content: '', ...raw, uid }, uid, localizerKeys);
}

/** A stored lorebook `{entries: {uid: entry}}` as loadWorldInfo returns it. */
export function storedBook(...entries: Record<string, unknown>[]): {
    entries: Record<string, Record<string, unknown>>;
} {
    return {
        entries: Object.fromEntries(entries.map((item, index) => [String(index), { uid: index, ...item }])),
    };
}

/** A CK archive entry (Baby Bunny single path defaults). */
export function archive(name: string, extra: Record<string, unknown> = {}, body = ''): Record<string, unknown> {
    return {
        key: [name],
        comment: `${name} Character Archive - Generated by Baby Bunny Mode`,
        content: `<BunnymoTags><Name:${name}>, <GENRE:FANTASY> <SPECIES:ELF></BunnymoTags>${body}`,
        position: 4,
        depth: 2,
        role: 2,
        excludeRecursion: true,
        scanDepth: 1,
        ...extra,
    };
}

/** Three tag-keyed entries make a book a BunnyMo pack (domain/bunnymo.ts classifyWorlds). */
export function packEntries(
    prefix: string,
    count = 3,
    content = (i: number) => `pack text ${i}`,
): Record<string, unknown>[] {
    return Array.from({ length: count }, (_, i) => ({
        key: [`<${prefix}:VALUE${i}>`],
        comment: `${prefix} ${i}`,
        content: content(i),
    }));
}
