// Strings of M25 «Механики», the play surfaces and the constructor of plan-2 §6–6.А (release 1.14, second wave): the
// line under replies and roll cards (`m25.play.*`), narrator messages (`m25.narrator.*`), the HUD (`m25.hud.*`), the
// sections of the «Механики» window (`m25.win.*`, `m25.tab.*`) and the constructor's new fields (`m25.ctor.*`).
// Russian is the primary UI language; the user is addressed as «ты» (male). Plain story words; ids and English for
// the model only under «Подробнее».
import type { I18nParts } from '../../shared/contracts';

export const PLAY_STRINGS: I18nParts = {
    en: {
        'm25.tab.log': 'History',
        'm25.tab.build': 'Constructor',

        // durations
        'm25.play.turns.one': '{count} turn',
        'm25.play.turns.few': '{count} turns',
        'm25.play.turns.many': '{count} turns',
        'm25.play.time.minute.one': '{count} min',
        'm25.play.time.minute.few': '{count} min',
        'm25.play.time.minute.many': '{count} min',
        'm25.play.time.hour.one': '{count} h',
        'm25.play.time.hour.few': '{count} h',
        'm25.play.time.hour.many': '{count} h',
        'm25.play.time.day.one': '{count} day',
        'm25.play.time.day.few': '{count} days',
        'm25.play.time.day.many': '{count} days',
        'm25.play.time.week.one': '{count} week',
        'm25.play.time.week.few': '{count} weeks',
        'm25.play.time.week.many': '{count} weeks',
        'm25.play.until': 'until day {day}',
        'm25.play.untilTime': 'until day {day}, {time}',

        // the change line
        'm25.play.statusOn': '+ {name}',
        'm25.play.statusOnFor': '+ {name} ({left})',
        'm25.play.statusOff': '− {name}',
        'm25.play.itemGained': '+ {name}',
        'm25.play.itemGainedMany': '+ {name} ×{qty}',
        'm25.play.itemLost': '− {name}',
        'm25.play.itemLostMany': '− {name} ×{qty}',
        'm25.play.itemEquipped': '{name} — {slot}',
        'm25.play.itemUnequipped': '{name} put away',
        'm25.play.item.worn': 'worn',
        'm25.play.item.hand': 'in hand',
        'm25.play.revealed': 'now you know: {name}',
        'm25.play.hiddenAgain': 'hidden again: {name}',
        'm25.play.combatStart': 'the fight began',
        'm25.play.combatEnd': 'the fight is over',
        'm25.play.combatRound': 'round {round}',
        'm25.play.combatJoin': 'in the fight: {holder}',
        'm25.play.textChanged': '{name}: «{text}»',
        'm25.play.statuses': 'Conditions',
        'm25.play.items': 'Items',
        'm25.play.undo': 'Undo',
        'm25.play.undo.failed': 'Could not undo it: the value changed again since.',
        'm25.play.undo.partial': 'Not everything was undone ({count}): those values changed again since.',
        'm25.play.details': 'Details',

        // roll cards
        'm25.play.roll.opposed': '{check} ({holder}): {total} · {other} ({rival}): {rivalTotal} — {outcome}',
        'm25.play.roll.mode.adv': '(with advantage)',
        'm25.play.roll.mode.dis': '(with disadvantage)',
        'm25.play.roll.undone': '— taken back',
        'm25.play.roll.undo': 'Undo the roll',
        'm25.play.roll.dice': 'Dice {dice}:',
        'm25.play.roll.total': 'total {total}',
        'm25.play.roll.target': 'needed {target}',
        'm25.play.roll.other.adv': 'The second roll was {other}: the better one counts.',
        'm25.play.roll.other.dis': 'The second roll was {other}: the worse one counts.',
        'm25.play.roll.rival': 'Against {holder} ({check}):',
        'm25.play.roll.outcome': 'Outcome: {outcome}',
        'm25.play.roll.consequences': 'Consequences: {list}',
        'm25.play.roll.undoneHint': 'Its consequences were taken back; the roll stays in the journal.',

        // events and the status block
        'm25.play.event': '{holder} · {attribute}: {condition} — an event fired',
        'm25.play.event.atMost': '{value} or less',
        'm25.play.event.atLeast': '{value} or more',
        'm25.play.event.is': 'now {value}',
        'm25.play.event.changed': 'changed',
        'm25.play.event.status': '{holder}: a condition is over',
        'm25.play.block': 'After this turn: {summary}',

        // narrator messages
        'm25.narrator.name': 'Narrator',

        // the HUD
        'm25.hud.title': 'Mechanics',
        'm25.hud.drag': 'Drag to the top or the bottom of the chat',
        'm25.hud.roll': 'Roll',
        'm25.hud.items': 'Inventory',
        'm25.hud.window': 'Open the mechanics window',
        'm25.hud.more': 'Everything…',
        'm25.hud.mode.adv': 'Advantage',
        'm25.hud.mode.dis': 'Disadvantage',
        'm25.hud.side.body': 'Characters of the scene',
        'm25.hud.side.fight': 'Fight · round {round} · {name}’s turn',

        // the window
        'm25.win.peek': 'Peek',
        'm25.win.peek.title': 'Peek at the hidden?',
        'm25.win.peek.body':
            'Hidden values are meant to stay a mystery: the story reveals them itself. Show them in this window until you close it? Nothing changes for the model.',
        'm25.win.reveal': 'Reveal',
        'm25.win.reveal.hint': 'Your character learns it: from now on it shows like the rest.',
        'm25.win.hide': 'Hide again',
        'm25.win.hide.hint': 'Back to a mystery for your character.',
        'm25.win.pin.on': 'Pin «{name}» to the HUD',
        'm25.win.pin.off': 'Take «{name}» off the HUD',
        'm25.win.hud.on': 'To the HUD',
        'm25.win.hud.off': 'Off the HUD',
        'm25.win.reset': 'Reset',
        'm25.win.reset.holder': 'Reset {holder}',
        'm25.win.reset.title': 'Reset to the start?',
        'm25.win.reset.body':
            'Every value of «{name}» in this chat goes back to its start, conditions and items of it are gone. The journal can undo it.',
        'm25.win.reset.holderBody':
            'Values of {holder} in «{name}» go back to their start in this chat. The journal can undo it.',
        'm25.win.reset.done': 'Reset: {count} changes.',
        'm25.win.reset.nothing': 'Nothing to reset: everything is at its start.',
        'm25.win.roll.mode': 'Advantage',
        'm25.win.roll.mode.none': 'Plain roll',
        'm25.win.roll.mode.adv': 'With advantage',
        'm25.win.roll.mode.dis': 'With disadvantage',
        'm25.win.roll.vs': 'Against',
        'm25.win.roll.vs.none': 'Against the difficulty',
        'm25.win.roll.vs.holder': 'Against {holder}',

        'm25.win.combat.title': 'Fight',
        'm25.win.combat.none': 'No fight now. It starts with the director’s fight scene or here.',
        'm25.win.combat.enemies': 'Enemies',
        'm25.win.combat.enemies.hint': 'Enemies, comma-separated (may be empty)',
        'm25.win.combat.start': 'Start the fight',
        'm25.win.combat.round': 'Fight · round {round}',
        'm25.win.combat.init': 'initiative {value}',
        'm25.win.combat.foe': 'enemy',
        'm25.win.combat.out': 'out',
        'm25.win.combat.enemy': 'A new enemy',
        'm25.win.combat.add': 'Add the enemy',
        'm25.win.combat.next': 'Next turn',
        'm25.win.combat.end': 'End the fight',
        'm25.win.combat.end.title': 'End the fight?',
        'm25.win.combat.end.body': 'The turn order is cleared; values stay as they are. The journal can undo it.',

        'm25.win.people.title': 'Conditions and items',
        'm25.win.status.empty': 'No conditions.',
        'm25.win.status.forever': 'until removed',
        'm25.win.status.remove': 'Take off «{name}»',
        'm25.win.status.pick': 'Condition',
        'm25.win.status.own': 'Your own…',
        'm25.win.status.name': 'Condition, e.g. «Poisoned»',
        'm25.win.status.turns': 'Turns',
        'm25.win.status.hours': 'Hours',
        'm25.win.status.add': 'Put on',
        'm25.win.status.none': 'No mechanic of this chat keeps conditions for this character.',
        'm25.win.item.empty': 'Carries nothing.',
        'm25.win.item.price': 'price {price}',
        'm25.win.item.carried': 'carried',
        'm25.win.item.where': 'Where is «{name}»',
        'm25.win.item.take': 'Take one',
        'm25.win.item.sell': 'Sell one',
        'm25.win.item.sellFailed': 'Not sold: there is nothing of it or no money to take it into.',
        'm25.win.item.name': 'Item',
        'm25.win.item.qty': 'How many',
        'm25.win.item.priceInput': 'Price of one',
        'm25.win.item.give': 'Give',
        'm25.win.item.buy': 'Buy',
        'm25.win.item.buyFailed': 'Not bought: not enough money.',

        'm25.win.log.all': 'All mechanics',
        'm25.win.log.filter': 'Which mechanic',
        'm25.win.log.changes': 'Changes',
        'm25.win.log.rolls': 'Rolls',
        'm25.win.log.hiddenCount': 'And {count} hidden rolls — «Peek» shows them.',
        'm25.win.log.hiddenRoll': 'hidden',
        'm25.win.log.undone': 'taken back',
        'm25.win.log.event': 'An event',

        // the constructor
        'm25.ctor.more': 'Details',
        'm25.ctor.where': 'Where it is seen',
        'm25.ctor.icon': 'Sign',
        'm25.ctor.promptName': 'Name for the model (English)',
        'm25.ctor.dice.hint':
            'For example 1d20, 2d6+3, 1d20 + the value of a number (pick it in «Details» of the number as @id).',
        'm25.ctor.summarySource': 'In short',
        'm25.ctor.summarySource.hint': 'One line in your words: what this mechanic is.',
        'm25.ctor.rulesSource': 'Rules',
        'm25.ctor.rulesSource.hint':
            'In your words: what the values mean, what costs what, what happens at the limits. The model gets them in English.',
        'm25.ctor.english': 'For the model (English)',
        'm25.ctor.english.hint':
            'What the model reads. Maestro translates your words after saving; you can write or correct it here yourself.',
        'm25.ctor.translate': 'Translate now',
        'm25.ctor.translation.ready': 'The English for the model is ready.',
        'm25.ctor.translation.pending': 'Waits for the English: Maestro translates it in the background after saving.',
        'm25.ctor.translation.running': 'Translating…',
        'm25.ctor.translation.failed': 'The translation did not work. Maestro will try again after saving.',
        'm25.ctor.translation.nothing': 'Nothing to translate: the model already has everything in English.',
        'm25.ctor.translation.queued': 'Maestro will translate the rules for the model in the background.',
        'm25.ctor.translation.later': 'The rules will be translated for the model when a chat is open.',
        'm25.ctor.translation.noModel':
            'No model is chosen for Maestro’s background work, so nothing is translated: the model reads your words as they are.',
        'm25.ctor.translation.waiting': 'waits for the English',
        'm25.ctor.copy': 'Copy',
        'm25.ctor.copy.name': '{name} (copy)',
        'm25.ctor.export': 'To a file',
        'm25.ctor.exported': '«{name}» is saved to a file.',
        'm25.ctor.import': 'From a file',
        'm25.ctor.imported': '«{name}» is read from the file: check it and save.',
        'm25.ctor.import.json': 'This file is not JSON.',
        'm25.ctor.import.kind': 'This file is not a Maestro mechanic.',
        'm25.ctor.import.definition': 'No mechanic in this file.',
        'm25.ctor.describe': 'Describe in words',
        'm25.ctor.describe.title': 'Describe the mechanic in words',
        'm25.ctor.describe.hint':
            'Tell what you want: «mana that comes back at rest, spells cost 10–30, without mana the spell fails». The assistant builds the mechanic and asks you before saving it.',
        'm25.ctor.describe.field': 'Your description',
        'm25.ctor.describe.placeholder': 'What should be counted, who has it, what happens at the limits…',
        'm25.ctor.describe.send': 'Ask the assistant',
        'm25.ctor.describe.off': 'The assistant is off: switch it on in the settings of the modules.',
        'm25.ctor.describe.request':
            'Build a mechanic for this chat from my description, using the mechanic tools (attributes, checks with consequences, events, visibility). Show me the plan before saving. My description:\n\n{text}',
        'm25.ctor.kind.title': 'Drop the events that do not fit?',
        'm25.ctor.kind.body':
            '«{name}» changes its kind; {count} of its events no longer fit it. Drop them? «Cancel» keeps them, you fix them below.',
        'm25.ctor.preview': 'What the model gets',
        'm25.ctor.preview.hint': 'This mechanic as the next turn would give it to the model, with the start values.',
        'm25.ctor.preview.empty': 'Nothing yet.',
        'm25.ctor.preview.holder': 'Character',
        'm25.ctor.preview.turn': 'The whole mechanics block of the next turn',
        'm25.ctor.preview.noTurn': 'No mechanic takes part in the scene now.',
        'm25.ctor.part.statuses': 'Conditions',
        'm25.ctor.part.inventory': 'Inventory and money',
        'm25.ctor.part.progression': 'Experience and levels',
        'm25.ctor.part.time': 'Over time',
        'm25.ctor.part.combat': 'Fights',

        'm25.ctor.vis.title': 'Where it is seen',
        'm25.ctor.vis.inherit': 'As the mechanic',
        'm25.ctor.vis.more': 'Places and words',
        'm25.ctor.vis.hint.game': 'Numbers and bars in the HUD, the change line under replies, roll cards.',
        'm25.ctor.vis.hint.book': 'No numbers: words in the chat, only condition signs in the HUD.',
        'm25.ctor.vis.hint.hidden': 'Nothing for you until an event reveals it; the window has «Peek».',
        'm25.ctor.vis.hint.secret': 'Nobody sees it: Maestro counts it and gives the model only what came of it.',
        'm25.ctor.vis.view': 'Shown as',
        'm25.ctor.vis.view.number': 'a number',
        'm25.ctor.vis.view.bar': 'a bar',
        'm25.ctor.vis.view.words': 'words',
        'm25.ctor.vis.view.icon': 'a sign',
        'm25.ctor.vis.view.hidden': 'not shown',
        'm25.ctor.vis.prompt': 'The model knows',
        'm25.ctor.vis.prompt.value': 'the value',
        'm25.ctor.vis.prompt.words': 'words only',
        'm25.ctor.vis.prompt.none': 'nothing',
        'm25.ctor.vis.mention': 'The model mentions changes',
        'm25.ctor.vis.mention.none': 'never',
        'm25.ctor.vis.mention.words': 'in words',
        'm25.ctor.vis.mention.numbers': 'with numbers',
        'm25.ctor.vis.narratorToModel': 'The model reads the narrator messages of this mechanic too',
        'm25.ctor.words': 'Words by thresholds',
        'm25.ctor.words.upTo': 'Up to',
        'm25.ctor.words.level': 'Level',
        'm25.ctor.words.display': 'Word for you',
        'm25.ctor.words.display.hint': 'badly hurt',
        'm25.ctor.words.label': 'Word for the model (English)',
        'm25.ctor.words.label.hint': 'badly hurt',
        'm25.ctor.words.add': 'Add a word',
        'm25.ctor.words.remove': 'Remove the word',

        'm25.ctor.formula': 'Counted by a formula',
        'm25.ctor.formula.hint': 'For example 50 + 10 * @level (empty — a plain number)',
        'm25.ctor.formula.ok': 'The formula is fine.',
        'm25.ctor.growth': 'Grows with use',
        'm25.ctor.growth.perUse': 'By how much',
        'm25.ctor.growth.cap': 'Up to',
        'm25.ctor.growth.on': 'When',
        'm25.ctor.growth.on.success': 'after a success',
        'm25.ctor.growth.on.any': 'after any roll',

        'm25.ctor.effects': 'Consequences',
        'm25.ctor.effects.hint': 'What happens after the roll: «failure — −10 health», «spell — −15 mana».',
        'm25.ctor.effect.on': 'When',
        'm25.ctor.effect.on.success': 'success',
        'm25.ctor.effect.on.failure': 'failure',
        'm25.ctor.effect.on.critical': 'critical success',
        'm25.ctor.effect.on.fumble': 'critical failure',
        'm25.ctor.effect.on.any': 'any outcome',
        'm25.ctor.effect.add': 'Add a consequence',
        'm25.ctor.effect.remove': 'Remove the consequence',
        'm25.ctor.effect.text': 'What the model learns (English)',
        'm25.ctor.effect.text.hint': 'the guards raise the alarm',
        'm25.ctor.event.actions': 'Then:',
        'm25.ctor.event.chain': 'And then the event',
        'm25.ctor.event.chain.none': 'none',

        'm25.ctor.action.who': 'Whom',
        'm25.ctor.action.who.actor': 'who rolled / whose value',
        'm25.ctor.action.who.target': 'the other side',
        'm25.ctor.action.who.persona': 'your character',
        'm25.ctor.action.who.name': 'by name…',
        'm25.ctor.action.whoName': 'Name',
        'm25.ctor.action.attr': 'What',
        'm25.ctor.action.attr.status': 'a condition',
        'm25.ctor.action.attr.item': 'an item',
        'm25.ctor.action.attr.reveal': 'reveal a hidden value',
        'm25.ctor.action.attr.combat': 'the fight',
        'm25.ctor.action.attr.other': 'of another mechanic…',
        'm25.ctor.action.other': 'mechanic.value',
        'm25.ctor.action.op': 'How',
        'm25.ctor.action.op.value.add': 'add',
        'm25.ctor.action.op.value.sub': 'subtract',
        'm25.ctor.action.op.value.set': 'set to',
        'm25.ctor.action.op.value.mul': 'multiply by',
        'm25.ctor.action.op.value.push': 'add the option',
        'm25.ctor.action.op.value.pull': 'remove the option',
        'm25.ctor.action.op.status.push': 'put on',
        'm25.ctor.action.op.status.pull': 'take off',
        'm25.ctor.action.op.item.push': 'give',
        'm25.ctor.action.op.item.pull': 'take away',
        'm25.ctor.action.op.combat.push': 'joins',
        'm25.ctor.action.op.combat.pull': 'leaves',
        'm25.ctor.action.op.reveal.set': 'reveal',
        'm25.ctor.action.value': 'How much',
        'm25.ctor.action.value.hint': '10, 1d6, @mana / 2',
        'm25.ctor.action.statusName': 'Condition',
        'm25.ctor.action.turns': 'Turns',
        'm25.ctor.action.itemName': 'Item',
        'm25.ctor.action.qty': 'How many',
        'm25.ctor.action.reveal': 'Which value',
        'm25.ctor.action.revealPick': 'Choose…',
        'm25.ctor.action.add': 'Add a change',
        'm25.ctor.action.remove': 'Remove the change',

        'm25.ctor.statuses.on': 'Its holders can have conditions',
        'm25.ctor.statuses.hint':
            'Conditions with a duration: «Poisoned — 3 turns». They change values and checks while they last and go by themselves.',
        'm25.ctor.status.name': 'Condition',
        'm25.ctor.status.turns': 'Turns',
        'm25.ctor.status.hours': 'Hours',
        'm25.ctor.status.mods': 'Bonuses and penalties',
        'm25.ctor.status.mods.hint': 'Stealth -2, checks +1',
        'm25.ctor.status.text': 'Note for the model while it lasts (English)',
        'm25.ctor.status.stacks': 'Stacks up to',
        'm25.ctor.status.add': 'Add a condition',
        'm25.ctor.status.remove': 'Remove the condition',
        'm25.ctor.mod.checks': 'checks',

        'm25.ctor.inventory.on': 'Keeps the holders’ items',
        'm25.ctor.inventory.money': 'Money',
        'm25.ctor.inventory.noMoney': 'no money',
        'm25.ctor.inventory.otherMoney': 'of another mechanic…',

        'm25.ctor.progression.on': 'Experience and levels',
        'm25.ctor.progression.xp': 'Experience',
        'm25.ctor.progression.level': 'Level',
        'm25.ctor.progression.thresholds': 'Experience for the next levels',
        'm25.ctor.progression.levelUp': 'At a new level:',

        'm25.ctor.time.hint': 'Recovery and wear by story time (the DES date and time): «+10 mana per hour of rest».',
        'm25.ctor.time.attr': 'Value',
        'm25.ctor.time.amount': 'By how much',
        'm25.ctor.time.per': 'Per',
        'm25.ctor.time.per.turn': 'turn',
        'm25.ctor.time.per.hour': 'story hour',
        'm25.ctor.time.per.day': 'story day',
        'm25.ctor.time.when': 'When',
        'm25.ctor.time.when.always': 'always',
        'm25.ctor.time.when.rest': 'only at rest',
        'm25.ctor.time.when.awake': 'not at rest',
        'm25.ctor.time.add': 'Add a rule',
        'm25.ctor.time.remove': 'Remove the rule',
        'm25.ctor.time.noNumbers': 'Add a number value first.',

        'm25.ctor.combat.on': 'Runs fights',
        'm25.ctor.combat.initiative': 'Initiative',
        'm25.ctor.combat.initiative.none': 'without a check (1d20)',
        'm25.ctor.combat.enemy': 'A new enemy starts with',
        'm25.ctor.combat.enemy.hint': 'Health 10, attack 3',

        'm25.ctor.settings.hud': 'Mechanics HUD',
        'm25.ctor.settings.hud.hint':
            'Your character’s values, conditions and money; pin values and characters in the «In play» section. Over the chat it can be dragged to the top or the bottom.',
        'm25.ctor.settings.hudPlacement': 'Where the HUD shows',
        'm25.ctor.settings.hudPlacement.chat': 'Over the chat (top or bottom)',
        'm25.ctor.settings.hudPlacement.left': 'Left of the chat (on a wide screen)',
        'm25.ctor.settings.hudPlacement.hint':
            'On the left there is more room: every character of the scene with all the values the HUD may show, conditions and items. The panel shows when the window is at least 1200 px wide and at least 220 px are free left of the chat. If a Maestro window or the DES portrait panel is on the left, it stands to their right. On a phone, in a narrower window, while ST’s left panel is open or when there is no room, the HUD shows over the chat; the setting stays as it is.',
        'm25.ctor.settings.desPersona': 'Your character under the DES portraits',
        'm25.ctor.settings.desAttrs': 'Under the DES portraits',
        'm25.ctor.settings.desAttrs.hint': 'Which values show there (all of them when none is chosen).',
        'm25.ctor.settings.places.hint':
            'Narrator messages and the status block under the reply are switched on per mechanic: «Where it is seen» in the constructor.',
    },
    ru: {
        'm25.tab.log': 'История',
        'm25.tab.build': 'Конструктор',

        'm25.play.turns.one': '{count} ход',
        'm25.play.turns.few': '{count} хода',
        'm25.play.turns.many': '{count} ходов',
        'm25.play.time.minute.one': '{count} мин',
        'm25.play.time.minute.few': '{count} мин',
        'm25.play.time.minute.many': '{count} мин',
        'm25.play.time.hour.one': '{count} ч',
        'm25.play.time.hour.few': '{count} ч',
        'm25.play.time.hour.many': '{count} ч',
        'm25.play.time.day.one': '{count} день',
        'm25.play.time.day.few': '{count} дня',
        'm25.play.time.day.many': '{count} дней',
        'm25.play.time.week.one': '{count} неделя',
        'm25.play.time.week.few': '{count} недели',
        'm25.play.time.week.many': '{count} недель',
        'm25.play.until': 'до дня {day}',
        'm25.play.untilTime': 'до дня {day}, {time}',

        'm25.play.statusOn': '+ {name}',
        'm25.play.statusOnFor': '+ {name} ({left})',
        'm25.play.statusOff': '− {name}',
        'm25.play.itemGained': '+ {name}',
        'm25.play.itemGainedMany': '+ {name} ×{qty}',
        'm25.play.itemLost': '− {name}',
        'm25.play.itemLostMany': '− {name} ×{qty}',
        'm25.play.itemEquipped': '{name} — {slot}',
        'm25.play.itemUnequipped': '{name} убран',
        'm25.play.item.worn': 'надето',
        'm25.play.item.hand': 'в руках',
        'm25.play.revealed': 'теперь известно: {name}',
        'm25.play.hiddenAgain': 'снова скрыто: {name}',
        'm25.play.combatStart': 'начался бой',
        'm25.play.combatEnd': 'бой окончен',
        'm25.play.combatRound': 'раунд {round}',
        'm25.play.combatJoin': 'в бою: {holder}',
        'm25.play.textChanged': '{name}: «{text}»',
        'm25.play.statuses': 'Состояния',
        'm25.play.items': 'Вещи',
        'm25.play.undo': 'Отменить',
        'm25.play.undo.failed': 'Отменить не вышло: значение с тех пор уже менялось.',
        'm25.play.undo.partial': 'Отменилось не всё ({count}): эти значения с тех пор уже менялись.',
        'm25.play.details': 'Подробнее',

        'm25.play.roll.opposed': '{check} ({holder}): {total} · {other} ({rival}): {rivalTotal} — {outcome}',
        'm25.play.roll.mode.adv': '(с преимуществом)',
        'm25.play.roll.mode.dis': '(с помехой)',
        'm25.play.roll.undone': '— отменён',
        'm25.play.roll.undo': 'Отменить бросок',
        'm25.play.roll.dice': 'Кубики {dice}:',
        'm25.play.roll.total': 'итог {total}',
        'm25.play.roll.target': 'нужно {target}',
        'm25.play.roll.other.adv': 'Второй бросок дал {other}: засчитан лучший.',
        'm25.play.roll.other.dis': 'Второй бросок дал {other}: засчитан худший.',
        'm25.play.roll.rival': 'Против {holder} ({check}):',
        'm25.play.roll.outcome': 'Исход: {outcome}',
        'm25.play.roll.consequences': 'Последствия: {list}',
        'm25.play.roll.undoneHint': 'Последствия отменены; сам бросок остался в журнале.',

        'm25.play.event': '{holder} · {attribute}: {condition} — сработало событие',
        'm25.play.event.atMost': '{value} и меньше',
        'm25.play.event.atLeast': '{value} и больше',
        'm25.play.event.is': 'теперь {value}',
        'm25.play.event.changed': 'изменилось',
        'm25.play.event.status': '{holder}: состояние закончилось',
        'm25.play.block': 'После хода: {summary}',

        'm25.narrator.name': 'Рассказчик',

        'm25.hud.title': 'Механики',
        'm25.hud.drag': 'Перетащи к верху или к низу чата',
        'm25.hud.roll': 'Бросок',
        'm25.hud.items': 'Инвентарь',
        'm25.hud.window': 'Открыть окно механик',
        'm25.hud.more': 'Всё…',
        'm25.hud.mode.adv': 'Преимущество',
        'm25.hud.mode.dis': 'Помеха',
        'm25.hud.side.body': 'Персонажи сцены',
        'm25.hud.side.fight': 'Бой · раунд {round} · ходит {name}',

        'm25.win.peek': 'Подсмотреть',
        'm25.win.peek.title': 'Подсмотреть скрытое?',
        'm25.win.peek.body':
            'Скрытые значения задуманы как тайна: история раскроет их сама. Показать их в этом окне, пока ты его не закроешь? Для модели ничего не меняется.',
        'm25.win.reveal': 'Раскрыть',
        'm25.win.reveal.hint': 'Твой персонаж это узнал: дальше значение видно, как остальные.',
        'm25.win.hide': 'Снова скрыть',
        'm25.win.hide.hint': 'Для твоего персонажа это снова тайна.',
        'm25.win.pin.on': 'Закрепить «{name}» в HUD',
        'm25.win.pin.off': 'Убрать «{name}» из HUD',
        'm25.win.hud.on': 'В HUD',
        'm25.win.hud.off': 'Убрать из HUD',
        'm25.win.reset': 'Сбросить',
        'm25.win.reset.holder': 'Сбросить: {holder}',
        'm25.win.reset.title': 'Сбросить к началу?',
        'm25.win.reset.body':
            'Все значения «{name}» в этом чате вернутся к начальным, её состояния и вещи пропадут. Отменить можно в журнале.',
        'm25.win.reset.holderBody':
            'Значения {holder} в «{name}» вернутся к начальным в этом чате. Отменить можно в журнале.',
        'm25.win.reset.done': 'Сброшено: изменений — {count}.',
        'm25.win.reset.nothing': 'Сбрасывать нечего: всё и так в начале.',
        'm25.win.roll.mode': 'Преимущество',
        'm25.win.roll.mode.none': 'Обычный бросок',
        'm25.win.roll.mode.adv': 'С преимуществом',
        'm25.win.roll.mode.dis': 'С помехой',
        'm25.win.roll.vs': 'Против',
        'm25.win.roll.vs.none': 'Против сложности',
        'm25.win.roll.vs.holder': 'Против: {holder}',

        'm25.win.combat.title': 'Бой',
        'm25.win.combat.none': 'Сейчас боя нет. Он начнётся со сценой боя у режиссёра или отсюда.',
        'm25.win.combat.enemies': 'Противники',
        'm25.win.combat.enemies.hint': 'Противники через запятую (можно пусто)',
        'm25.win.combat.start': 'Начать бой',
        'm25.win.combat.round': 'Бой · раунд {round}',
        'm25.win.combat.init': 'инициатива {value}',
        'm25.win.combat.foe': 'противник',
        'm25.win.combat.out': 'выбыл',
        'm25.win.combat.enemy': 'Новый противник',
        'm25.win.combat.add': 'Добавить противника',
        'm25.win.combat.next': 'Следующий ход',
        'm25.win.combat.end': 'Закончить бой',
        'm25.win.combat.end.title': 'Закончить бой?',
        'm25.win.combat.end.body':
            'Очерёдность ходов сбросится, значения останутся как есть. Отменить можно в журнале.',

        'm25.win.people.title': 'Состояния и вещи',
        'm25.win.status.empty': 'Состояний нет.',
        'm25.win.status.forever': 'пока не снимут',
        'm25.win.status.remove': 'Снять «{name}»',
        'm25.win.status.pick': 'Состояние',
        'm25.win.status.own': 'Своё…',
        'm25.win.status.name': 'Состояние, например «Отравлен»',
        'm25.win.status.turns': 'Ходов',
        'm25.win.status.hours': 'Часов',
        'm25.win.status.add': 'Наложить',
        'm25.win.status.none': 'Ни одна механика этого чата не ведёт состояния этого персонажа.',
        'm25.win.item.empty': 'Ничего с собой нет.',
        'm25.win.item.price': 'цена {price}',
        'm25.win.item.carried': 'с собой',
        'm25.win.item.where': 'Где «{name}»',
        'm25.win.item.take': 'Забрать одну',
        'm25.win.item.sell': 'Продать одну',
        'm25.win.item.sellFailed': 'Не продано: такой вещи нет или некуда класть деньги.',
        'm25.win.item.name': 'Вещь',
        'm25.win.item.qty': 'Сколько',
        'm25.win.item.priceInput': 'Цена за штуку',
        'm25.win.item.give': 'Дать',
        'm25.win.item.buy': 'Купить',
        'm25.win.item.buyFailed': 'Не куплено: не хватает денег.',

        'm25.win.log.all': 'Все механики',
        'm25.win.log.filter': 'Какая механика',
        'm25.win.log.changes': 'Изменения',
        'm25.win.log.rolls': 'Броски',
        'm25.win.log.hiddenCount': 'И ещё скрытых бросков: {count} — их покажет «Подсмотреть».',
        'm25.win.log.hiddenRoll': 'скрытый',
        'm25.win.log.undone': 'отменён',
        'm25.win.log.event': 'Событие',

        'm25.ctor.more': 'Подробнее',
        'm25.ctor.where': 'Где видно',
        'm25.ctor.icon': 'Значок',
        'm25.ctor.promptName': 'Название для модели (по-английски)',
        'm25.ctor.dice.hint':
            'Например 1d20, 2d6+3, 1d20 + значение числа (его обозначение — в «Подробнее» у числа, пишется как @обозначение).',
        'm25.ctor.summarySource': 'Кратко',
        'm25.ctor.summarySource.hint': 'Одна строка своими словами: что это за механика.',
        'm25.ctor.rulesSource': 'Правила',
        'm25.ctor.rulesSource.hint':
            'Своими словами: что значат значения, что сколько стоит, что бывает на пределах. Модели они уйдут по-английски.',
        'm25.ctor.english': 'Для модели (по-английски)',
        'm25.ctor.english.hint':
            'Это читает модель. Maestro переводит твой текст после сохранения; можно написать или поправить здесь самому.',
        'm25.ctor.translate': 'Перевести сейчас',
        'm25.ctor.translation.ready': 'Перевод для модели готов.',
        'm25.ctor.translation.pending': 'Ждёт перевода: Maestro переведёт в фоне после сохранения.',
        'm25.ctor.translation.running': 'Перевожу…',
        'm25.ctor.translation.failed': 'Перевести не вышло. Maestro попробует снова после сохранения.',
        'm25.ctor.translation.nothing': 'Переводить нечего: у модели уже всё по-английски.',
        'm25.ctor.translation.queued': 'Maestro переведёт правила для модели в фоне.',
        'm25.ctor.translation.later': 'Правила переведутся для модели, когда будет открыт чат.',
        'm25.ctor.translation.noModel':
            'Для фоновой работы Maestro не выбрана модель, переводить некому: модель прочитает твои слова как есть.',
        'm25.ctor.translation.waiting': 'ждёт перевода',
        'm25.ctor.copy': 'Копия',
        'm25.ctor.copy.name': '{name} (копия)',
        'm25.ctor.export': 'В файл',
        'm25.ctor.exported': '«{name}» сохранена в файл.',
        'm25.ctor.import': 'Из файла',
        'm25.ctor.imported': '«{name}» прочитана из файла: проверь и сохрани.',
        'm25.ctor.import.json': 'Это не JSON-файл.',
        'm25.ctor.import.kind': 'Это не механика Maestro.',
        'm25.ctor.import.definition': 'В файле нет механики.',
        'm25.ctor.describe': 'Описать словами',
        'm25.ctor.describe.title': 'Описать механику словами',
        'm25.ctor.describe.hint':
            'Расскажи, что нужно: «мана, которая восстанавливается в отдыхе, заклинания стоят 10–30, без маны заклинание срывается». Ассистент соберёт механику и спросит тебя перед сохранением.',
        'm25.ctor.describe.field': 'Твоё описание',
        'm25.ctor.describe.placeholder': 'Что считать, у кого это есть, что бывает на пределах…',
        'm25.ctor.describe.send': 'Попросить ассистента',
        'm25.ctor.describe.off': 'Ассистент выключен: включи его в настройках модулей.',
        'm25.ctor.describe.request':
            'Собери механику для этого чата по моему описанию — инструментами механик (атрибуты, проверки с последствиями, события, видимость). Покажи план перед сохранением. Описание:\n\n{text}',
        'm25.ctor.kind.title': 'Убрать неподходящие события?',
        'm25.ctor.kind.body':
            'У «{name}» меняется вид; событий, которые ему больше не подходят: {count}. Убрать их? «Отмена» оставит их — поправишь ниже.',
        'm25.ctor.preview': 'Что получит модель',
        'm25.ctor.preview.hint': 'Эта механика так, как следующий ход отдаст её модели, с начальными значениями.',
        'm25.ctor.preview.empty': 'Пока ничего.',
        'm25.ctor.preview.holder': 'Персонаж',
        'm25.ctor.preview.turn': 'Весь блок механик следующего хода',
        'm25.ctor.preview.noTurn': 'Сейчас в сцене нет ни одной механики.',
        'm25.ctor.part.statuses': 'Состояния',
        'm25.ctor.part.inventory': 'Инвентарь и деньги',
        'm25.ctor.part.progression': 'Опыт и уровни',
        'm25.ctor.part.time': 'Со временем',
        'm25.ctor.part.combat': 'Бой',

        'm25.ctor.vis.title': 'Где видно',
        'm25.ctor.vis.inherit': 'Как у механики',
        'm25.ctor.vis.more': 'Места и слова',
        'm25.ctor.vis.hint.game': 'Числа и полосы в HUD, строка изменений под ответом, карточки бросков.',
        'm25.ctor.vis.hint.book': 'Без чисел: в чате словами, в HUD только значки состояний.',
        'm25.ctor.vis.hint.hidden': 'Тебе не видно, пока событие не раскроет; в окне — «Подсмотреть».',
        'm25.ctor.vis.hint.secret': 'Не видит никто: Maestro сам считает и отдаёт модели только последствия.',
        'm25.ctor.vis.view': 'Показывать',
        'm25.ctor.vis.view.number': 'числом',
        'm25.ctor.vis.view.bar': 'полосой',
        'm25.ctor.vis.view.words': 'словами',
        'm25.ctor.vis.view.icon': 'значком',
        'm25.ctor.vis.view.hidden': 'не показывать',
        'm25.ctor.vis.prompt': 'Модель знает',
        'm25.ctor.vis.prompt.value': 'значение',
        'm25.ctor.vis.prompt.words': 'только словами',
        'm25.ctor.vis.prompt.none': 'ничего',
        'm25.ctor.vis.mention': 'Модель упоминает изменения',
        'm25.ctor.vis.mention.none': 'никак',
        'm25.ctor.vis.mention.words': 'словами',
        'm25.ctor.vis.mention.numbers': 'с числами',
        'm25.ctor.vis.narratorToModel': 'Сообщения рассказчика этой механики видит и модель',
        'm25.ctor.words': 'Слова по порогам',
        'm25.ctor.words.upTo': 'До',
        'm25.ctor.words.level': 'Уровень',
        'm25.ctor.words.display': 'Слово для тебя',
        'm25.ctor.words.display.hint': 'тяжело ранен',
        'm25.ctor.words.label': 'Слово для модели (по-английски)',
        'm25.ctor.words.label.hint': 'badly hurt',
        'm25.ctor.words.add': 'Добавить слово',
        'm25.ctor.words.remove': 'Убрать слово',

        'm25.ctor.formula': 'Считается по формуле',
        'm25.ctor.formula.hint': 'Например 50 + 10 * @level (пусто — обычное число)',
        'm25.ctor.formula.ok': 'Формула в порядке.',
        'm25.ctor.growth': 'Растёт от применения',
        'm25.ctor.growth.perUse': 'На сколько',
        'm25.ctor.growth.cap': 'До',
        'm25.ctor.growth.on': 'Когда',
        'm25.ctor.growth.on.success': 'после успеха',
        'm25.ctor.growth.on.any': 'после любого броска',

        'm25.ctor.effects': 'Последствия',
        'm25.ctor.effects.hint': 'Что бывает после броска: «провал — −10 здоровья», «заклинание — −15 маны».',
        'm25.ctor.effect.on': 'Когда',
        'm25.ctor.effect.on.success': 'успех',
        'm25.ctor.effect.on.failure': 'провал',
        'm25.ctor.effect.on.critical': 'крит',
        'm25.ctor.effect.on.fumble': 'крит. провал',
        'm25.ctor.effect.on.any': 'любой исход',
        'm25.ctor.effect.add': 'Добавить последствие',
        'm25.ctor.effect.remove': 'Убрать последствие',
        'm25.ctor.effect.text': 'Что узнает модель (по-английски)',
        'm25.ctor.effect.text.hint': 'the guards raise the alarm',
        'm25.ctor.event.actions': 'Затем:',
        'm25.ctor.event.chain': 'И следом событие',
        'm25.ctor.event.chain.none': 'нет',

        'm25.ctor.action.who': 'Кому',
        'm25.ctor.action.who.actor': 'тому, кто бросал / чьё значение',
        'm25.ctor.action.who.target': 'другой стороне',
        'm25.ctor.action.who.persona': 'твоему персонажу',
        'm25.ctor.action.who.name': 'по имени…',
        'm25.ctor.action.whoName': 'Имя',
        'm25.ctor.action.attr': 'Что',
        'm25.ctor.action.attr.status': 'состояние',
        'm25.ctor.action.attr.item': 'вещь',
        'm25.ctor.action.attr.reveal': 'раскрыть скрытое',
        'm25.ctor.action.attr.combat': 'бой',
        'm25.ctor.action.attr.other': 'из другой механики…',
        'm25.ctor.action.other': 'механика.значение',
        'm25.ctor.action.op': 'Как',
        'm25.ctor.action.op.value.add': 'прибавить',
        'm25.ctor.action.op.value.sub': 'отнять',
        'm25.ctor.action.op.value.set': 'сделать равным',
        'm25.ctor.action.op.value.mul': 'умножить на',
        'm25.ctor.action.op.value.push': 'добавить вариант',
        'm25.ctor.action.op.value.pull': 'убрать вариант',
        'm25.ctor.action.op.status.push': 'наложить',
        'm25.ctor.action.op.status.pull': 'снять',
        'm25.ctor.action.op.item.push': 'дать',
        'm25.ctor.action.op.item.pull': 'забрать',
        'm25.ctor.action.op.combat.push': 'вступает',
        'm25.ctor.action.op.combat.pull': 'выходит',
        'm25.ctor.action.op.reveal.set': 'раскрыть',
        'm25.ctor.action.value': 'Сколько',
        'm25.ctor.action.value.hint': '10, 1d6, @mana / 2',
        'm25.ctor.action.statusName': 'Состояние',
        'm25.ctor.action.turns': 'Ходов',
        'm25.ctor.action.itemName': 'Вещь',
        'm25.ctor.action.qty': 'Сколько',
        'm25.ctor.action.reveal': 'Какое значение',
        'm25.ctor.action.revealPick': 'Выбери…',
        'm25.ctor.action.add': 'Добавить изменение',
        'm25.ctor.action.remove': 'Убрать изменение',

        'm25.ctor.statuses.on': 'У участников бывают состояния',
        'm25.ctor.statuses.hint':
            'Состояния с длительностью: «Отравлен — 3 хода». Пока длятся, меняют значения и проверки, потом проходят сами.',
        'm25.ctor.status.name': 'Состояние',
        'm25.ctor.status.turns': 'Ходов',
        'm25.ctor.status.hours': 'Часов',
        'm25.ctor.status.mods': 'Бонусы и штрафы',
        'm25.ctor.status.mods.hint': 'Скрытность -2, проверки +1',
        'm25.ctor.status.text': 'Заметка для модели, пока длится (по-английски)',
        'm25.ctor.status.stacks': 'Складывается до',
        'm25.ctor.status.add': 'Добавить состояние',
        'm25.ctor.status.remove': 'Убрать состояние',
        'm25.ctor.mod.checks': 'проверки',

        'm25.ctor.inventory.on': 'Ведёт вещи участников',
        'm25.ctor.inventory.money': 'Деньги',
        'm25.ctor.inventory.noMoney': 'без денег',
        'm25.ctor.inventory.otherMoney': 'из другой механики…',

        'm25.ctor.progression.on': 'Опыт и уровни',
        'm25.ctor.progression.xp': 'Опыт',
        'm25.ctor.progression.level': 'Уровень',
        'm25.ctor.progression.thresholds': 'Опыт для следующих уровней',
        'm25.ctor.progression.levelUp': 'На новом уровне:',

        'm25.ctor.time.hint':
            'Восстановление и расход по времени истории (дата и время DES): «+10 маны за час отдыха».',
        'm25.ctor.time.attr': 'Значение',
        'm25.ctor.time.amount': 'На сколько',
        'm25.ctor.time.per': 'За',
        'm25.ctor.time.per.turn': 'ход',
        'm25.ctor.time.per.hour': 'час истории',
        'm25.ctor.time.per.day': 'день истории',
        'm25.ctor.time.when': 'Когда',
        'm25.ctor.time.when.always': 'всегда',
        'm25.ctor.time.when.rest': 'только в отдыхе',
        'm25.ctor.time.when.awake': 'не в отдыхе',
        'm25.ctor.time.add': 'Добавить правило',
        'm25.ctor.time.remove': 'Убрать правило',
        'm25.ctor.time.noNumbers': 'Сначала добавь числовое значение.',

        'm25.ctor.combat.on': 'Ведёт бой',
        'm25.ctor.combat.initiative': 'Инициатива',
        'm25.ctor.combat.initiative.none': 'без проверки (1d20)',
        'm25.ctor.combat.enemy': 'Новый противник начинает с',
        'm25.ctor.combat.enemy.hint': 'Здоровье 10, атака 3',

        'm25.ctor.settings.hud': 'HUD механик',
        'm25.ctor.settings.hud.hint':
            'Значения, состояния и деньги твоего персонажа; что показывать, закрепляешь в разделе «В игре». Над чатом его можно перетащить к верху или к низу.',
        'm25.ctor.settings.hudPlacement': 'Где показывать HUD',
        'm25.ctor.settings.hudPlacement.chat': 'Над чатом (сверху или снизу)',
        'm25.ctor.settings.hudPlacement.left': 'Слева от чата (на широком экране)',
        'm25.ctor.settings.hudPlacement.hint':
            'Слева места больше: все персонажи сцены со всеми значениями, которые можно показывать в HUD, состояниями и вещами. Панель появляется, когда окно шириной от 1200 px и слева от чата свободно не меньше 220 px. Если слева стоит окно Maestro или панель портретов DES, она встаёт правее них. На телефоне, в окне поуже, пока открыта левая панель ST или без места HUD показывается над чатом; настройка при этом не меняется.',
        'm25.ctor.settings.desPersona': 'Твой персонаж под портретами DES',
        'm25.ctor.settings.desAttrs': 'Под портретами DES',
        'm25.ctor.settings.desAttrs.hint': 'Какие значения там видны (все, если ничего не выбрано).',
        'm25.ctor.settings.places.hint':
            'Сообщения рассказчика и статус-блок под ответом включаются у каждой механики: «Где видно» в конструкторе.',
    },
};
