// Strings of M25 «Механики», definitions part: the module and tab titles (`m25.title`, `m25.tab`) and the constructor,
// templates, validation issues, errors and journal lines (`m25.def.*`). Russian is the primary UI language; the user
// is addressed as «ты» (male). Rules, prompt names, levels and options stay English: the model reads them.
import type { I18nParts } from '../../shared/contracts';

export const DEF_STRINGS: I18nParts = {
    en: {
        'm25.title': 'Mechanics',
        'm25.tab': 'Mechanics',

        'm25.def.section': 'Mechanics constructor',
        'm25.def.hint':
            'Your own game systems: health, magic, reputation, money, skills — attributes, who has them, rules for the model, events and dice checks. A mechanic lives in a Maestro book and never activates as lore: Maestro gives the model its rules and the current values only when it takes part in the scene.',
        'm25.def.empty': 'No mechanics yet — start from a template.',
        'm25.def.noChat': 'No chat is open: only mechanics for every chat are shown.',
        'm25.def.fromTemplate': 'From a template',
        'm25.def.new': 'New mechanic',
        'm25.def.templates.title': 'Templates',
        'm25.def.templates.close': 'Close',
        'm25.def.templates.use': 'Create',
        'm25.def.enabled': 'On in this chat',
        'm25.def.edit': 'Edit',
        'm25.def.delete': 'Delete',
        'm25.def.delete.title': 'Delete the mechanic?',
        'm25.def.delete.body':
            '«{name}» will be removed from the book «{book}». Values in chats are kept but no longer used. The journal can undo it.',
        'm25.def.deleted': 'Mechanic «{name}» deleted.',
        'm25.def.saved': 'Mechanic «{name}» saved.',
        'm25.def.scope.global': 'Every chat',
        'm25.def.scope.card': 'This card',
        'm25.def.scope.chat': 'This chat',
        'm25.def.counts': 'Attributes: {attributes} · checks: {checks}',
        'm25.def.book': 'Book for new mechanics',
        'm25.def.book.hint':
            'A Maestro book. It is created when missing and never switched on: Maestro gives the rules to the model itself.',

        'm25.def.template.health': 'Health and stamina',
        'm25.def.template.health.hint':
            'Health and stamina from 0 to 100 for every character; at 0 — unconscious or exhausted.',
        'm25.def.template.magic': 'Magic',
        'm25.def.template.magic.hint':
            'Mana, schools of magic and a spellcasting check that rolls under the current mana.',
        'm25.def.template.reputation': 'Faction reputation',
        'm25.def.template.reputation.hint': 'A reputation scale from hostile to revered with every faction you list.',
        'm25.def.template.money': 'Money',
        'm25.def.template.money.hint': "Your character's purse in coins, with a short price list for the model.",
        'm25.def.template.skills': 'Skills with checks',
        'm25.def.template.skills.hint':
            'Persuasion, deception, intimidation, stealth, athletics and perception from 0 to 20; d20 checks are rolled when your message calls for them.',
        'm25.def.template.relationships': 'Relationships',
        'm25.def.template.relationships.hint':
            'How each character feels about your character: from hostile to devoted.',

        'm25.def.editor.new': 'New mechanic',
        'm25.def.editor.edit': 'Editing «{name}»',
        'm25.def.field.name': 'Name',
        'm25.def.field.id': 'Id',
        'm25.def.field.id.hint': 'Latin letters, digits and _. The flag for preset blocks is maestro_mech_{id}.',
        'm25.def.field.promptName': 'Name for the model',
        'm25.def.field.promptName.hint': 'In English ("Magic"). Empty: the name above.',
        'm25.def.field.summary': 'Summary for the model',
        'm25.def.field.summary.hint': 'In English, one line: what this mechanic is.',
        'm25.def.field.rules': 'Rules for the model',
        'm25.def.field.rules.hint':
            'In English: what the attributes mean, what costs what, what happens at the limits. The model reads this text.',
        'm25.def.field.scope': 'Where it works',
        'm25.def.field.holders': 'Who has it',
        'm25.def.holders.persona': 'Your character',
        'm25.def.holders.characters': 'Every character',
        'm25.def.holders.named': 'Named characters',
        'm25.def.holders.world': 'The world',
        'm25.def.holders.factions': 'Factions',
        'm25.def.holders.includePersona': 'Your character too',
        'm25.def.holders.names': 'Names, comma-separated',
        'm25.def.field.tracking': 'How changes are noticed',
        'm25.def.tracking.desStats': 'DES stats',
        'm25.def.tracking.block': 'Service block in the reply',
        'm25.def.tracking.background': 'Background parse',
        'm25.def.tracking.manual': 'By hand only',
        'm25.def.tracking.inherit': 'As the mechanic ({mode})',
        'm25.def.tracking.hint':
            "DES stats: numbers of characters live in DES's tracker. Service block: the model ends its reply with a short block that Maestro reads and hides. Background parse: Maestro reads the reply after you send the next message. Checks are always rolled by Maestro.",

        'm25.def.attributes': 'Attributes',
        'm25.def.attributes.empty': 'No attributes.',
        'm25.def.attributes.add': 'Add attribute',
        'm25.def.attr.name': 'Name',
        'm25.def.attr.promptName': 'Name for the model (English)',
        'm25.def.attr.id': 'Id',
        'm25.def.attr.kind': 'Kind',
        'm25.def.kind.number': 'Number',
        'm25.def.kind.scale': 'Scale',
        'm25.def.kind.list': 'List',
        'm25.def.kind.text': 'Text',
        'm25.def.attr.min': 'Minimum',
        'm25.def.attr.max': 'Maximum',
        'm25.def.attr.bound.none': 'none',
        'm25.def.attr.initial': 'Start value',
        'm25.def.attr.levels': 'Levels from lowest to highest, comma-separated (English)',
        'm25.def.attr.options': 'Options, comma-separated (English)',
        'm25.def.attr.multi': 'Several at once',
        'm25.def.attr.tracking': 'Tracking',
        'm25.def.attr.visible': 'Show in the widgets',
        'm25.def.attr.up': 'Move up',
        'm25.def.attr.down': 'Move down',
        'm25.def.attr.remove': 'Remove the attribute',
        'm25.def.attr.new': 'New attribute',
        'm25.def.events': 'Events',
        'm25.def.events.add': 'Add event',
        'm25.def.event.op': 'When the value',
        'm25.def.event.op.changed': 'changes',
        'm25.def.event.value': 'Value',
        'm25.def.event.text': 'Note for the model (English; {holder} and {value} are filled in)',
        'm25.def.event.once': 'Once, until the condition is false again',
        'm25.def.event.remove': 'Remove the event',

        'm25.def.checks': 'Checks',
        'm25.def.checks.empty': 'No checks.',
        'm25.def.checks.add': 'Add check',
        'm25.def.check.name': 'Name',
        'm25.def.check.promptName': 'Name for the model (English)',
        'm25.def.check.id': 'Id',
        'm25.def.check.dice': 'Dice',
        'm25.def.check.dice.hint': "1d20, 2d6+3, 1d20+@id, 1d20+mod(@id), 1d100<=@id, where id is an attribute's id.",
        'm25.def.check.diceOk': 'Roll: {text}, against the difficulty',
        'm25.def.check.diceUnder': 'Roll: {text}, success at or under the target',
        'm25.def.check.diceBad': 'Unknown formula. Examples: 1d20, 2d6+3, 1d20+mod(@persuasion), 1d100<=@stealth.',
        'm25.def.check.difficulty': 'Difficulty',
        'm25.def.check.difficulty.hint': 'Empty — the model only gets the number.',
        'm25.def.check.triggers': 'Trigger words, comma-separated',
        'm25.def.check.triggers.hint':
            'Stems in Russian and English: «убед», «уговор», persuad. A check is rolled when your message has one of them.',
        'm25.def.check.criticals': 'Highest and lowest roll are critical',
        'm25.def.check.remove': 'Remove the check',
        'm25.def.check.new': 'New check',

        'm25.def.des.title': 'DES stats',
        'm25.def.des.hint': "Attributes tracked as DES stats have to be in DES's tracker settings.",
        'm25.def.des.button': 'Make them DES stats',
        'm25.def.des.in': 'in DES',
        'm25.def.des.missing': 'not in DES',
        'm25.def.des.done': 'The stats were added to DES.',
        'm25.def.des.notDone': 'DES stats were not changed.',
        'm25.def.des.saveFirst': 'Save the mechanic first.',

        'm25.def.save': 'Save',
        'm25.def.cancel': 'Cancel',
        'm25.def.issues': 'To fix',

        'm25.def.issue.id': 'the id has to be Latin letters, digits and _, starting with a letter.',
        'm25.def.issue.name': 'the mechanic needs a name.',
        'm25.def.issue.empty': 'add attributes, checks or at least rules.',
        'm25.def.issue.noRules': 'no rules for the model: it will only see names and values.',
        'm25.def.issue.holderNames': 'no names are listed in «Who has it».',
        'm25.def.issue.scope': 'the place where it works is not known.',
        'm25.def.issue.attrId': '«{attribute}»: the id has to be Latin letters, digits and _.',
        'm25.def.issue.attrIdDuplicate': '«{attribute}»: another attribute has the same id.',
        'm25.def.issue.attrName': 'attribute {attribute} has no name.',
        'm25.def.issue.attrPromptName': '«{attribute}»: no name for the model.',
        'm25.def.issue.bounds': '«{attribute}»: the minimum is above the maximum.',
        'm25.def.issue.initial': '«{attribute}»: the start value is not a number.',
        'm25.def.issue.initialRange': '«{attribute}»: the start value is out of bounds.',
        'm25.def.issue.levels': '«{attribute}»: a scale needs at least two levels.',
        'm25.def.issue.initialLevel': '«{attribute}»: the start value is not one of the levels.',
        'm25.def.issue.options': '«{attribute}»: a list needs options.',
        'm25.def.issue.initialOption': '«{attribute}»: the start value is not one of the options.',
        'm25.def.issue.initialSingle': '«{attribute}»: only one option can be chosen at once.',
        'm25.def.issue.desStatsKind': '«{attribute}»: only numbers can be DES stats.',
        'm25.def.issue.desStatsHolders': '«{attribute}»: DES stats are for characters, not for the world or factions.',
        'm25.def.issue.eventId': '«{attribute}»: an event id has to be Latin letters, digits and _.',
        'm25.def.issue.eventIdDuplicate': '«{attribute}»: two events have the same id.',
        'm25.def.issue.eventText': '«{attribute}»: an event has no note for the model.',
        'm25.def.issue.eventValue': '«{attribute}»: an event needs a value.',
        'm25.def.issue.eventLevel': '«{attribute}»: an event value is not one of the levels.',
        'm25.def.issue.eventOp': '«{attribute}»: lists and texts only know «=» and «changes».',
        'm25.def.issue.checkId': '«{check}»: the id has to be Latin letters, digits and _.',
        'm25.def.issue.checkIdDuplicate': '«{check}»: another check has the same id.',
        'm25.def.issue.checkName': 'check {check} has no name.',
        'm25.def.issue.dice': '«{check}»: unknown dice formula.',
        'm25.def.issue.diceUnknown': '«{check}»: the dice use @{attribute}, but there is no such attribute.',
        'm25.def.issue.diceKind': '«{check}»: @{attribute} is not a number.',
        'm25.def.issue.difficulty': '«{check}»: the difficulty is not a number.',
        'm25.def.issue.noTriggers': '«{check}»: no trigger words — it is rolled only by the button.',

        'm25.def.error.invalid': 'The mechanic cannot be saved: {issue}',
        'm25.def.error.noWorldInfo': 'This SillyTavern cannot read or save lorebooks.',
        'm25.def.error.p13': '«{book}» is a BunnyMo book: Maestro never writes into it.',
        'm25.def.error.notMaestro':
            '«{book}» is not a Maestro book. Choose another book for mechanics or give it the role «Maestro» in the Lore Studio.',
        'm25.def.error.duplicateId': 'The id {id} is already taken by «{name}».',
        'm25.def.error.noChat': 'No chat is open.',

        'm25.def.journal.create': 'Mechanic «{name}» created',
        'm25.def.journal.update': 'Mechanic «{name}» changed',
        'm25.def.journal.remove': 'Mechanic «{name}» deleted',

        'm25.def.settings.title': 'Mechanics settings',
        'm25.def.settings.autoChecks': 'Roll checks when your message has a trigger word',
        'm25.def.settings.strip': 'Widgets next to the DES portraits',
        'm25.def.settings.background': 'Background parse of replies',
        'm25.def.settings.promptBudget': 'Prompt budget, tokens',
        'm25.def.settings.promptBudget.hint':
            "Rules and values of the mechanics in the scene. The architect's budget for mechanics wins when it is set.",
        'm25.def.settings.depth': 'Depth in the chat',
        'm25.def.settings.depth.hint':
            'How many messages from the end the rules go. Close to the end keeps the provider cache intact.',
    },
    ru: {
        'm25.title': 'Механики',
        'm25.tab': 'Механики',

        'm25.def.section': 'Конструктор механик',
        'm25.def.hint':
            'Свои игровые системы: здоровье, магия, репутация, деньги, навыки — атрибуты, у кого они есть, правила для модели, события и броски. Механика хранится в книге Maestro и никогда не срабатывает как лор: Maestro сам даёт модели её правила и текущие значения, только когда она участвует в сцене.',
        'm25.def.empty': 'Механик пока нет — начни с шаблона.',
        'm25.def.noChat': 'Чат не открыт: показаны только механики для всех чатов.',
        'm25.def.fromTemplate': 'Из шаблона',
        'm25.def.new': 'Новая механика',
        'm25.def.templates.title': 'Шаблоны',
        'm25.def.templates.close': 'Закрыть',
        'm25.def.templates.use': 'Создать',
        'm25.def.enabled': 'Включена в этом чате',
        'm25.def.edit': 'Изменить',
        'm25.def.delete': 'Удалить',
        'm25.def.delete.title': 'Удалить механику?',
        'm25.def.delete.body':
            '«{name}» будет удалена из книги «{book}». Значения в чатах останутся, но больше не будут использоваться. Отменить можно в журнале.',
        'm25.def.deleted': 'Механика «{name}» удалена.',
        'm25.def.saved': 'Механика «{name}» сохранена.',
        'm25.def.scope.global': 'Во всех чатах',
        'm25.def.scope.card': 'Эта карточка',
        'm25.def.scope.chat': 'Этот чат',
        'm25.def.counts': 'Атрибуты: {attributes} · проверки: {checks}',
        'm25.def.book': 'Книга для новых механик',
        'm25.def.book.hint':
            'Книга Maestro. Создаётся, если её нет, и никогда не включается: правила модели Maestro передаёт сам.',

        'm25.def.template.health': 'Здоровье и выносливость',
        'm25.def.template.health.hint':
            'Здоровье и выносливость от 0 до 100 у каждого персонажа; на нуле — потеря сознания или изнеможение.',
        'm25.def.template.magic': 'Магия',
        'm25.def.template.magic.hint': 'Мана, школы магии и проверка заклинания: бросок не выше текущей маны.',
        'm25.def.template.reputation': 'Репутация у фракций',
        'm25.def.template.reputation.hint':
            'Шкала репутации от «враждебно» до «почитание» у каждой фракции, которую ты перечислишь.',
        'm25.def.template.money': 'Деньги',
        'm25.def.template.money.hint': 'Кошелёк твоего персонажа в монетах и короткий прейскурант для модели.',
        'm25.def.template.skills': 'Навыки с проверками',
        'm25.def.template.skills.hint':
            'Убеждение, обман, запугивание, скрытность, атлетика и внимательность от 0 до 20; бросок d20 делается, когда этого требует твоё сообщение.',
        'm25.def.template.relationships': 'Отношения',
        'm25.def.template.relationships.hint': 'Как каждый персонаж относится к твоему: от вражды до преданности.',

        'm25.def.editor.new': 'Новая механика',
        'm25.def.editor.edit': 'Правка: «{name}»',
        'm25.def.field.name': 'Название',
        'm25.def.field.id': 'Идентификатор',
        'm25.def.field.id.hint': 'Латиница, цифры и _. Флаг для блоков пресета — maestro_mech_{id}.',
        'm25.def.field.promptName': 'Название для модели',
        'm25.def.field.promptName.hint': 'По-английски («Magic»). Пусто — название выше.',
        'm25.def.field.summary': 'Кратко для модели',
        'm25.def.field.summary.hint': 'По-английски, одной строкой: что это за механика.',
        'm25.def.field.rules': 'Правила для модели',
        'm25.def.field.rules.hint':
            'По-английски: что значат атрибуты, что сколько стоит, что бывает на границах. Этот текст читает модель.',
        'm25.def.field.scope': 'Где действует',
        'm25.def.field.holders': 'У кого',
        'm25.def.holders.persona': 'Твой персонаж',
        'm25.def.holders.characters': 'Все персонажи',
        'm25.def.holders.named': 'Названные персонажи',
        'm25.def.holders.world': 'Мир',
        'm25.def.holders.factions': 'Фракции',
        'm25.def.holders.includePersona': 'И твой персонаж тоже',
        'm25.def.holders.names': 'Имена через запятую',
        'm25.def.field.tracking': 'Как замечать изменения',
        'm25.def.tracking.desStats': 'Статы DES',
        'm25.def.tracking.block': 'Служебный блок в ответе',
        'm25.def.tracking.background': 'Фоновый разбор',
        'm25.def.tracking.manual': 'Только вручную',
        'm25.def.tracking.inherit': 'Как у механики ({mode})',
        'm25.def.tracking.hint':
            'Статы DES: числа персонажей живут в трекере DES. Служебный блок: модель заканчивает ответ коротким блоком, Maestro его читает и прячет. Фоновый разбор: Maestro читает ответ, когда ты отправишь следующее сообщение. Броски всегда делает Maestro.',

        'm25.def.attributes': 'Атрибуты',
        'm25.def.attributes.empty': 'Атрибутов нет.',
        'm25.def.attributes.add': 'Добавить атрибут',
        'm25.def.attr.name': 'Название',
        'm25.def.attr.promptName': 'Название для модели (по-английски)',
        'm25.def.attr.id': 'Идентификатор',
        'm25.def.attr.kind': 'Вид',
        'm25.def.kind.number': 'Число',
        'm25.def.kind.scale': 'Шкала',
        'm25.def.kind.list': 'Список',
        'm25.def.kind.text': 'Текст',
        'm25.def.attr.min': 'Минимум',
        'm25.def.attr.max': 'Максимум',
        'm25.def.attr.bound.none': 'нет',
        'm25.def.attr.initial': 'Начальное значение',
        'm25.def.attr.levels': 'Уровни от низшего к высшему, через запятую (по-английски)',
        'm25.def.attr.options': 'Варианты через запятую (по-английски)',
        'm25.def.attr.multi': 'Можно несколько сразу',
        'm25.def.attr.tracking': 'Отслеживание',
        'm25.def.attr.visible': 'Показывать в виджетах',
        'm25.def.attr.up': 'Выше',
        'm25.def.attr.down': 'Ниже',
        'm25.def.attr.remove': 'Убрать атрибут',
        'm25.def.attr.new': 'Новый атрибут',
        'm25.def.events': 'События',
        'm25.def.events.add': 'Добавить событие',
        'm25.def.event.op': 'Когда значение',
        'm25.def.event.op.changed': 'меняется',
        'm25.def.event.value': 'Значение',
        'm25.def.event.text': 'Заметка для модели (по-английски; {holder} и {value} подставятся)',
        'm25.def.event.once': 'Один раз, пока условие снова не станет ложным',
        'm25.def.event.remove': 'Убрать событие',

        'm25.def.checks': 'Проверки',
        'm25.def.checks.empty': 'Проверок нет.',
        'm25.def.checks.add': 'Добавить проверку',
        'm25.def.check.name': 'Название',
        'm25.def.check.promptName': 'Название для модели (по-английски)',
        'm25.def.check.id': 'Идентификатор',
        'm25.def.check.dice': 'Кости',
        'm25.def.check.dice.hint': '1d20, 2d6+3, 1d20+@id, 1d20+mod(@id), 1d100<=@id, где id — идентификатор атрибута.',
        'm25.def.check.diceOk': 'Бросок: {text}, против сложности',
        'm25.def.check.diceUnder': 'Бросок: {text}, успех — не выше цели',
        'm25.def.check.diceBad': 'Непонятная формула. Примеры: 1d20, 2d6+3, 1d20+mod(@persuasion), 1d100<=@stealth.',
        'm25.def.check.difficulty': 'Сложность',
        'm25.def.check.difficulty.hint': 'Пусто — модель узнает только число.',
        'm25.def.check.triggers': 'Слова-триггеры через запятую',
        'm25.def.check.triggers.hint':
            'Основы слов по-русски и по-английски: «убед», «уговор», persuad. Бросок делается, когда в твоём сообщении есть одна из них.',
        'm25.def.check.criticals': 'Наибольший и наименьший бросок — критические',
        'm25.def.check.remove': 'Убрать проверку',
        'm25.def.check.new': 'Новая проверка',

        'm25.def.des.title': 'Статы DES',
        'm25.def.des.hint': 'Атрибуты, которые отслеживаются статами DES, должны быть в настройках трекера DES.',
        'm25.def.des.button': 'Сделать статами DES',
        'm25.def.des.in': 'есть в DES',
        'm25.def.des.missing': 'нет в DES',
        'm25.def.des.done': 'Статы добавлены в DES.',
        'm25.def.des.notDone': 'Статы DES не изменились.',
        'm25.def.des.saveFirst': 'Сначала сохрани механику.',

        'm25.def.save': 'Сохранить',
        'm25.def.cancel': 'Отмена',
        'm25.def.issues': 'Что поправить',

        'm25.def.issue.id': 'идентификатор — латиница, цифры и _, первая — буква.',
        'm25.def.issue.name': 'у механики нет названия.',
        'm25.def.issue.empty': 'добавь атрибуты, проверки или хотя бы правила.',
        'm25.def.issue.noRules': 'нет правил для модели: она увидит только названия и значения.',
        'm25.def.issue.holderNames': 'в «У кого» не перечислены имена.',
        'm25.def.issue.scope': 'непонятно, где действует механика.',
        'm25.def.issue.attrId': '«{attribute}»: идентификатор — латиница, цифры и _.',
        'm25.def.issue.attrIdDuplicate': '«{attribute}»: такой идентификатор уже есть у другого атрибута.',
        'm25.def.issue.attrName': 'у атрибута {attribute} нет названия.',
        'm25.def.issue.attrPromptName': '«{attribute}»: нет названия для модели.',
        'm25.def.issue.bounds': '«{attribute}»: минимум больше максимума.',
        'm25.def.issue.initial': '«{attribute}»: начальное значение — не число.',
        'm25.def.issue.initialRange': '«{attribute}»: начальное значение за границами.',
        'm25.def.issue.levels': '«{attribute}»: у шкалы должно быть хотя бы два уровня.',
        'm25.def.issue.initialLevel': '«{attribute}»: начального значения нет среди уровней.',
        'm25.def.issue.options': '«{attribute}»: у списка нет вариантов.',
        'm25.def.issue.initialOption': '«{attribute}»: начального значения нет среди вариантов.',
        'm25.def.issue.initialSingle': '«{attribute}»: выбрать можно только один вариант.',
        'm25.def.issue.desStatsKind': '«{attribute}»: статами DES могут быть только числа.',
        'm25.def.issue.desStatsHolders': '«{attribute}»: статы DES бывают у персонажей, а не у мира или фракций.',
        'm25.def.issue.eventId': '«{attribute}»: идентификатор события — латиница, цифры и _.',
        'm25.def.issue.eventIdDuplicate': '«{attribute}»: у двух событий один идентификатор.',
        'm25.def.issue.eventText': '«{attribute}»: у события нет заметки для модели.',
        'm25.def.issue.eventValue': '«{attribute}»: у события не задано значение.',
        'm25.def.issue.eventLevel': '«{attribute}»: значения события нет среди уровней.',
        'm25.def.issue.eventOp': '«{attribute}»: у списков и текстов бывают только «=» и «меняется».',
        'm25.def.issue.checkId': '«{check}»: идентификатор — латиница, цифры и _.',
        'm25.def.issue.checkIdDuplicate': '«{check}»: такой идентификатор уже есть у другой проверки.',
        'm25.def.issue.checkName': 'у проверки {check} нет названия.',
        'm25.def.issue.dice': '«{check}»: непонятная формула костей.',
        'm25.def.issue.diceUnknown': '«{check}»: в костях есть @{attribute}, а такого атрибута нет.',
        'm25.def.issue.diceKind': '«{check}»: @{attribute} — не число.',
        'm25.def.issue.difficulty': '«{check}»: сложность — не число.',
        'm25.def.issue.noTriggers': '«{check}»: нет слов-триггеров — бросок только по кнопке.',

        'm25.def.error.invalid': 'Механику нельзя сохранить: {issue}',
        'm25.def.error.noWorldInfo': 'Этот SillyTavern не умеет читать и сохранять лорбуки.',
        'm25.def.error.p13': '«{book}» — книга BunnyMo: Maestro в неё никогда не пишет.',
        'm25.def.error.notMaestro':
            '«{book}» — не книга Maestro. Выбери другую книгу для механик или дай этой роль «Maestro» в Лор-студии.',
        'm25.def.error.duplicateId': 'Идентификатор {id} уже занят механикой «{name}».',
        'm25.def.error.noChat': 'Чат не открыт.',

        'm25.def.journal.create': 'Создана механика «{name}»',
        'm25.def.journal.update': 'Изменена механика «{name}»',
        'm25.def.journal.remove': 'Удалена механика «{name}»',

        'm25.def.settings.title': 'Настройки механик',
        'm25.def.settings.autoChecks': 'Бросать проверки, когда в твоём сообщении есть слово-триггер',
        'm25.def.settings.strip': 'Виджеты рядом с портретами DES',
        'm25.def.settings.background': 'Фоновый разбор ответов',
        'm25.def.settings.promptBudget': 'Бюджет в промпте, токенов',
        'm25.def.settings.promptBudget.hint':
            'Правила и значения механик, участвующих в сцене. Если у архитектора задан бюджет механик, действует он.',
        'm25.def.settings.depth': 'Глубина в чате',
        'm25.def.settings.depth.hint':
            'За сколько сообщений от конца ставятся правила. Ближе к концу — кэш провайдера не ломается.',
    },
};
