// Strings of M25 «Механики», part C: checks (`m25.check.*`), widgets (`m25.widget.*`), the prompt (`m25.prompt.*`)
// and the autonomy kind of the rolls. Russian is the primary UI language; the user is addressed as «ты» (male).
import type { I18nParts } from '../../shared/contracts';

export const CHECK_STRINGS: I18nParts = {
    en: {
        'kind.mechanics.check': 'Check rolls',

        'm25.check.outcome.critical': 'critical success',
        'm25.check.outcome.success': 'success',
        'm25.check.outcome.failure': 'failure',
        'm25.check.outcome.fumble': 'critical failure',
        'm25.check.outcome.none': 'no target',
        'm25.check.line': '{check} ({holder}): {total}{target} — {outcome}',
        'm25.check.line.plain': '{check} ({holder}): {total}',
        'm25.check.vs': ' vs {target}',
        'm25.check.under': ' (needs {target} or lower)',
        'm25.check.journal': 'Roll: {line}',
        'm25.check.badge': 'Roll: {line}',
        'm25.check.rolled': 'Rolled: {line}',
        'm25.check.by.auto': 'by your message',
        'm25.check.by.user': 'by hand',
        'm25.check.slash.help':
            'Rolls a mechanics check now: /maestro-roll <check> [who] [difficulty]. The result goes into the next reply as a fact.',
        'm25.check.slash.value': 'The check (name or id), then who rolls and the difficulty (a number, easy, hard)',
        'm25.check.slash.holder': 'Who rolls (default: your persona)',
        'm25.check.slash.difficulty': 'Difficulty: a number, or easy / hard / very hard',
        'm25.check.slash.usage': 'Usage: /maestro-roll <check> [who] [difficulty]',
        'm25.check.error.unknownCheck': 'None of the mechanics on in this chat has the check “{name}”.',
        'm25.check.error.unknownMechanic': 'Unknown mechanic: {id}',
        'm25.check.error.formula': 'This dice formula cannot be rolled: {dice}',
        'm25.check.error.noValue': 'Nothing to roll against: no value of “{attribute}” for {holder}.',
        'm25.check.error.noHolder': 'Who rolls? Name the character.',
        'm25.check.error.noChat': 'Open a chat first.',
        'm25.check.error.difficulty': 'Difficulty is a number or easy / hard / very hard: {value}',

        'm25.widget.state.title': 'Mechanics in the scene',
        'm25.widget.state.hint':
            'Values of everyone in the scene. A change made here counts as your edit; the model gets the state near the end of the prompt.',
        'm25.widget.noChat': 'No chat is open.',
        'm25.widget.none': 'No mechanics are on in this chat.',
        'm25.widget.noHolders': 'Nobody with these values is in the scene.',
        'm25.widget.level': '{level} ({index} of {count})',
        'm25.widget.list.none': 'none',
        'm25.widget.list.add': 'Add…',
        'm25.widget.list.remove': 'Remove {item}',
        'm25.widget.edit': 'Change: {name}',
        'm25.widget.edit.failed': 'The value was not changed: {error}',
        'm25.widget.recent': 'Recent changes',
        'm25.widget.recent.none': 'No changes yet.',
        'm25.widget.change': '{holder}: {attribute} {from} → {to}',
        'm25.widget.change.reason': '“{reason}”',
        'm25.widget.source.desStats': 'DES',
        'm25.widget.source.block': 'reply block',
        'm25.widget.source.background': 'background',
        'm25.widget.source.check': 'roll',
        'm25.widget.source.event': 'event',
        'm25.widget.source.user': 'by hand',
        'm25.widget.roll.title': 'Roll',
        'm25.widget.roll.check': 'Check',
        'm25.widget.roll.holder': 'Who',
        'm25.widget.roll.difficulty': 'Difficulty',
        'm25.widget.roll.default': 'Default difficulty: {value}',
        'm25.widget.roll.noDefault': 'No default difficulty: only the number is reported',
        'm25.widget.roll.under': 'Roll-under: the target is the value itself',
        'm25.widget.roll.button': 'Roll',
        'm25.widget.roll.hint': 'The result goes into the next reply as a fact.',
        'm25.widget.results': 'Recent rolls',
        'm25.widget.results.none': 'No rolls yet.',
        'm25.widget.pending': 'waits for the next reply',
        'm25.widget.events': 'Events',
        'm25.widget.events.none': 'No events yet.',
        'm25.widget.strip.title': 'Mechanics',
        'm25.widget.strip.collapse': 'Collapse the mechanics bars',
        'm25.widget.strip.expand': 'Expand the mechanics bars',

        'm25.prompt.flag': 'Mechanic “{name}” takes part in the scene',
        'm25.prompt.flag.hint':
            'On while someone in the scene has this mechanic’s values; Maestro sets it for one generation at a time.',
        'm25.prompt.budget.architect': 'budget from the Architect',
        'm25.prompt.budget.own': 'own limit',
        'm25.prompt.preview': 'What the model gets: {tokens} of {budget} tokens',
        'm25.prompt.cut': 'Shortened to fit: {count} steps',
    },
    ru: {
        'kind.mechanics.check': 'Броски проверок',

        'm25.check.outcome.critical': 'критический успех',
        'm25.check.outcome.success': 'успех',
        'm25.check.outcome.failure': 'провал',
        'm25.check.outcome.fumble': 'критический провал',
        'm25.check.outcome.none': 'без цели',
        'm25.check.line': '{check} ({holder}): {total}{target} — {outcome}',
        'm25.check.line.plain': '{check} ({holder}): {total}',
        'm25.check.vs': ' против {target}',
        'm25.check.under': ' (нужно {target} или меньше)',
        'm25.check.journal': 'Бросок: {line}',
        'm25.check.badge': 'Бросок: {line}',
        'm25.check.rolled': 'Бросок: {line}',
        'm25.check.by.auto': 'по твоему сообщению',
        'm25.check.by.user': 'вручную',
        'm25.check.slash.help':
            'Бросает проверку механики: /maestro-roll <проверка> [кто] [сложность]. Результат уйдёт в следующий ответ как факт.',
        'm25.check.slash.value': 'Проверка (название или id), затем кто бросает и сложность (число, «легко», «трудно»)',
        'm25.check.slash.holder': 'Кто бросает (по умолчанию — твоя персона)',
        'm25.check.slash.difficulty': 'Сложность: число или «легко» / «трудно» / «очень трудно»',
        'm25.check.slash.usage': 'Как вызвать: /maestro-roll <проверка> [кто] [сложность]',
        'm25.check.error.unknownCheck': 'Ни у одной механики этого чата нет проверки «{name}».',
        'm25.check.error.unknownMechanic': 'Нет такой механики: {id}',
        'm25.check.error.formula': 'Эту формулу броска не разобрать: {dice}',
        'm25.check.error.noValue': 'Бросать не с чем: нет значения «{attribute}» ({holder}).',
        'm25.check.error.noHolder': 'За кого бросать? Назови персонажа.',
        'm25.check.error.noChat': 'Сначала открой чат.',
        'm25.check.error.difficulty': 'Сложность — это число или «легко» / «трудно» / «очень трудно»: {value}',

        'm25.widget.state.title': 'Механики в сцене',
        'm25.widget.state.hint':
            'Значения всех, кто сейчас в сцене. Правка здесь считается твоей; модель получает состояние ближе к концу промпта.',
        'm25.widget.noChat': 'Чат не открыт.',
        'm25.widget.none': 'В этом чате механики не включены.',
        'm25.widget.noHolders': 'В сцене нет никого, у кого есть эти значения.',
        'm25.widget.level': '{level} ({index} из {count})',
        'm25.widget.list.none': 'нет',
        'm25.widget.list.add': 'Добавить…',
        'm25.widget.list.remove': 'Убрать: {item}',
        'm25.widget.edit': 'Изменить: {name}',
        'm25.widget.edit.failed': 'Значение не изменилось: {error}',
        'm25.widget.recent': 'Последние изменения',
        'm25.widget.recent.none': 'Изменений пока нет.',
        'm25.widget.change': '{holder}: {attribute} {from} → {to}',
        'm25.widget.change.reason': '«{reason}»',
        'm25.widget.source.desStats': 'DES',
        'm25.widget.source.block': 'блок ответа',
        'm25.widget.source.background': 'фоновый разбор',
        'm25.widget.source.check': 'бросок',
        'm25.widget.source.event': 'событие',
        'm25.widget.source.user': 'вручную',
        'm25.widget.roll.title': 'Бросок',
        'm25.widget.roll.check': 'Проверка',
        'm25.widget.roll.holder': 'Кто',
        'm25.widget.roll.difficulty': 'Сложность',
        'm25.widget.roll.default': 'Сложность по умолчанию: {value}',
        'm25.widget.roll.noDefault': 'Сложность не задана — будет только число',
        'm25.widget.roll.under': 'Бросок «под значение»: цель — само значение',
        'm25.widget.roll.button': 'Бросить',
        'm25.widget.roll.hint': 'Результат уйдёт в следующий ответ как факт.',
        'm25.widget.results': 'Последние броски',
        'm25.widget.results.none': 'Бросков пока не было.',
        'm25.widget.pending': 'ждёт следующего ответа',
        'm25.widget.events': 'События',
        'm25.widget.events.none': 'Событий пока не было.',
        'm25.widget.strip.title': 'Механики',
        'm25.widget.strip.collapse': 'Свернуть полоски механик',
        'm25.widget.strip.expand': 'Развернуть полоски механик',

        'm25.prompt.flag': 'Механика «{name}» в сцене',
        'm25.prompt.flag.hint':
            'Включён, пока у кого-то в сцене есть значения этой механики; Maestro ставит его на одну генерацию.',
        'm25.prompt.budget.architect': 'бюджет от Архитектора',
        'm25.prompt.budget.own': 'свой лимит',
        'm25.prompt.preview': 'Что получает модель: {tokens} из {budget} токенов',
        'm25.prompt.cut': 'Сокращено под бюджет: шагов — {count}',
    },
};
